### ISSUE TITLE
Sd.evaluate failure

### ISSUE THREAD

**Issue by adonnini** [deeplearning4j/deeplearning4j#10028]
<div class="modal-body" tabindex="-1"><div id="ember353" class="loading-container ember-view"><div id="revisions" data-post-id="8893" class=""><div id="ember356" class="row body-diff ember-view">

When I run the code reported below, execution fails with  

```Index can't be < 0 and >= 1984```  

What am I missing / doing wrong?   Thanks  

CODE  

```java                 
String outputVariable = outReduced.name();                  
evaluation = new Evaluation();                  
testData.reset();                 
sd.evaluate(testData, outputVariable, evaluation);
```  

```outReduced``` has shape ```[64, 2, 31]```  

```testData``` has 109 elements.  

ERROR LOG  
```java  
Exception in thread "main" java.lang.IllegalStateException: Index can't be < 0 and >= 1984 	at org.nd4j.linalg.factory.Nd4j.pullRows(Nd4j.java:4749) 	at org.nd4j.linalg.factory.Nd4j.pullRows(Nd4j.java:4722) 	at org.nd4j.evaluation.EvaluationUtils.extractNonMaskedTimeSteps(EvaluationUtils.java:208) 	at org.nd4j.evaluation.BaseEvaluation.reshapeAndExtractNotMasked(BaseEvaluation.java:186) 	at org.nd4j.evaluation.classification.Evaluation.eval(Evaluation.java:361) 	at org.nd4j.evaluation.BaseEvaluation.eval(BaseEvaluation.java:267) 	at org.nd4j.autodiff.samediff.SameDiff.evaluateHelper(SameDiff.java:2402) 	at org.nd4j.autodiff.samediff.SameDiff.evaluate(SameDiff.java:2296) 	at org.nd4j.autodiff.samediff.config.EvaluationConfig.exec(EvaluationConfig.java:197) 	at org.nd4j.autodiff.samediff.SameDiff.evaluate(SameDiff.java:2206) 	at org.deeplearning4j.examples.trajectorypredictiontransformer.LocationNextNeuralNetworkV7_04.fitAndEvaluateTestDataset(LocationNextNeuralNetworkV7_04.java:1083) 	at org.deeplearning4j.examples.trajectorypredictiontransformer.LocationNextNeuralNetworkV7_04.sameDiff3(LocationNextNeuralNetworkV7_04.java:685) 	at org.deeplearning4j.examples.trajectorypredictiontransformer.LocationNextNeuralNetworkV7_04.main(LocationNextNeuralNetworkV7_04.java:207)
```

**Comment by agibsonccc** [comment]
Closing — this issue is over 2 years old with no recent activity or reproduction steps. The underlying code has been significantly rewritten. If you still experience this issue with a recent version, please open a new issue.
