### ISSUE TITLE
The provided RNNEmbedding Example does not work, on 1.0.0-M2.1 release

### ISSUE THREAD

**Issue by nishisan** [deeplearning4j/deeplearning4j#10022]
#### Issue Description
The provided RNNEmbedding  Example does not work, on 1.0.0-M2.1 release
The provided example in dl4j-examples/src/main/java/org/deeplearning4j/examples/quickstart/modeling/recurrent/RNNEmbedding.java does not compile

Please describe your issue, along with:
- expected behavior 
  The example to compile and run
- encountered behavior
An Exception:
Exception in thread "main" java.lang.IllegalStateException: Sequence lengths do not match for RnnOutputLayer input and labels:Arrays should be rank 3 with shape [minibatch, size, sequenceLength] - mismatch on dimension 2 (sequence length) - input=[3, 7, 8] vs. label=[3, 4, 8]
	at org.nd4j.common.base.Preconditions.throwStateEx(Preconditions.java:639)
	at org.nd4j.common.base.Preconditions.checkState(Preconditions.java:337)
	at org.deeplearning4j.nn.layers.recurrent.RnnOutputLayer.backpropGradient(RnnOutputLayer.java:59)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.calcBackpropGradients(MultiLayerNetwork.java:1998)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2813)
	at com.osstelecom.ai.deeplearning.ai.api.AiApi.main(AiApi.java:60)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version:1.0.0-M2.1 
* platform information (OS, etc) Linux Ubuntu 22,04
* CUDA version: No Used
* NVIDIA driver version: Not Used

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by agibsonccc** [comment]
Closing — this issue references architecture (old UI, M1/M2.1 release, Spark, TF import, ParallelWrapper training, or legacy subsystem) that has been fundamentally rewritten in the upcoming release. If you still experience a similar issue with the new version, please open a new issue with reproduction steps.
