### ISSUE TITLE
TimeSeriesUtils.getFormatFromRnnLayer should support SameDiffLayer as it can be Recurrent as well

### ISSUE THREAD

**Issue by valb3r** [deeplearning4j/deeplearning4j#10024]
#### Issue Description

I'm not able to use custom `SameDiffLayer` as the `Recurrent` layer (it is of course possible to overcome the issue, but it does not look nice)

Currently TimeSeriesUtils.getFormatFromRnnLayer uses following logic:
```java
public static RNNFormat getFormatFromRnnLayer(Layer layer){
        if(layer instanceof BaseRecurrentLayer){
            return ((BaseRecurrentLayer) layer).getRnnDataFormat();
        } else if(layer instanceof MaskZeroLayer){
            return getFormatFromRnnLayer(((MaskZeroLayer) layer).getUnderlying());
        } else if(layer instanceof Bidirectional){
            return getFormatFromRnnLayer(((Bidirectional) layer).getFwd());
        } else if(layer instanceof LastTimeStep){
            return getFormatFromRnnLayer(((LastTimeStep) layer).getUnderlying());
        } else if(layer instanceof TimeDistributed){
            return ((TimeDistributed) layer).getRnnDataFormat();
        } else {
            throw new IllegalStateException("Unable to get RNNFormat from layer of type: " + layer);
        }
    }
```

Because of that, it is impossible to use custom SameDiffLayer wrapped into LastTimeStep, like that:
```kotlin
val conf: MultiLayerConfiguration = NeuralNetConfiguration.Builder()
            .weightInit(WeightInit.NORMAL)
            .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
            .updater(Adam())
            .list()
            .setInputType(InputType.recurrent(numInputFeatures))
            .layer(
                0, SimpleRnn.Builder().nOut(numHiddenRnn).activation(Activation.TANH).name("rnn").build()
            )
            .layer(1, LastTimeStep(BahdanauAttentionLayer(numHiddenRnn, 1))) // BahdanauAttentionLayer is SameDiff based recurrent layer
            .layer(2, DenseLayer.Builder().nOut(1).activation(Activation.TANH).name("dense").build())
            .layer(LossLayer.Builder().lossFunction(LossMSE()).build())
            .build()
 ```           
Due to:
```
Exception in thread "main" java.lang.IllegalStateException: Unable to get RNNFormat from layer of type: SameDiffLayer(weightInit=NORMAL, paramWeightInit=null)
	at org.deeplearning4j.util.TimeSeriesUtils.getFormatFromRnnLayer(TimeSeriesUtils.java:457)
	at org.deeplearning4j.nn.layers.recurrent.LastTimeStepLayer.getLastStep(LastTimeStepLayer.java:122)
	at org.deeplearning4j.nn.layers.recurrent.LastTimeStepLayer.activate(LastTimeStepLayer.java:102)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.ffToLayerActivationsInWs(MultiLayerNetwork.java:1147)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2798)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2756)
```

**Possible solution**
To me it makes sense to add interface `IRecurrentLayer` like that
```java
public interface IRecurrentLayer {
    public RNNFormat getRnnDataFormat();
}
```

so that `getFormatFromRnnLayer` could be 
```java
public static RNNFormat getFormatFromRnnLayer(Layer layer){
        if(layer instanceof BaseRecurrentLayer){
            return ((BaseRecurrentLayer) layer).getRnnDataFormat();
        } else if(layer instanceof MaskZeroLayer){
            return getFormatFromRnnLayer(((MaskZeroLayer) layer).getUnderlying());
        } else if(layer instanceof Bidirectional){
            return getFormatFromRnnLayer(((Bidirectional) layer).getFwd());
        } else if(layer instanceof LastTimeStep){
            return getFormatFromRnnLayer(((LastTimeStep) layer).getUnderlying());
        } else if(layer instanceof TimeDistributed){
            return ((TimeDistributed) layer).getRnnDataFormat();
        } else if(layer instanceof IRecurrentLayer){
            return ((IRecurrentLayer) layer).getRnnDataFormat();
        } else {
            throw new IllegalStateException("Unable to get RNNFormat from layer of type: " + layer);
        }
    }
```

**Comment by agibsonccc** [comment]
@valb3r how would you propose that? What sort of samediff network? We'd need some validation. If we do this I'd want to do it correctly. If you want, I'd be happy to look at a pull request for this.

**Comment by valb3r** [comment]
@agibsonccc I see the way to fix it like this: https://github.com/deeplearning4j/deeplearning4j/pull/10030
