### ISSUE TITLE
Unsupported keras layer type GRU

### ISSUE THREAD

**Issue by Zony7** [deeplearning4j/deeplearning4j#10039]
#### Issue Description

An error occurred when I loaded the tf.keras v2.5 (GRU) model using deeplearning4j

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 1.0.0
* Ubuntu 20.04

#### Additional Information
```
 org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type GRU. Please file an issue at https://github.com/eclipse/deeplearning4j/issues.
                	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:320)
                                                          	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:218)
                                                                        	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:110)
                    	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:57)
                                            	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:322)
                                                                              	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:208)
                                          	at zzq.Model.<init>(Model.java:24)
  	at org.onosproject.predict.LinkPredictTask.run(LinkPredictTask.java:43)
                                                                               at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
   	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
     	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
                                                   	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                                                                    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by agibsonccc** [comment]
@lzyxx77 there's no dl4j 1.0.0 - do you mean 1.0.0-M2.1?

**Comment by Zony7** [comment]
> @lzyxx77 there's no dl4j 1.0.0 - do you mean 1.0.0-M2.1?

Sorry, the information was incomplete just now
It is 1.0.0-beta6

**Comment by agibsonccc** [comment]
@lzyxx77 can you please try with 1.0.0-M2.1? beta6 is years old at this point. I'm closing this with that in mind. Feel free to comment again if that doesn't fix your issue.
