### ISSUE TITLE
Running a a basic CNN training fails on Google Colab!

### ISSUE THREAD

**Issue by aboullaite** [deeplearning4j/deeplearning4j#10058]
#### Issue Description
I am trying to Run a basic Deeplearking4j example, and building a similar version of the famous HotDog or not example. I am running the example on Google colab using jbang and IJava on GPU. Trying to run the code return an exception:

```
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacv.OpenCVFrameConverter$ToMat
	at org.datavec.image.loader.NativeImageLoader.<init>(NativeImageLoader.java:59)
	at org.datavec.image.loader.NativeImageLoader.<init>(NativeImageLoader.java:116)
	at org.datavec.image.recordreader.BaseImageRecordReader.initialize(BaseImageRecordReader.java:131)
	at .(#245:1)
```	

Hereis the link to the colab https://colab.research.google.com/drive/1m8BBTgkNMyfAnm4RaqTBERaht5qnNZ5D?usp=sharing
The same code works perfectly if I try to run it locally. Not sure If I missed some sort of dependency ?
Please describe our issue, along with:
- expected behavior
Training and saving the model
- encountered behavior
Failure and exception
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version  1.0.0-M2.1
* Platform information (OS, etc): Google Colab
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by agibsonccc** [comment]
Closing — this issue references architecture (old UI, M1/M2.1 release, Spark, TF import, ParallelWrapper training, or legacy subsystem) that has been fundamentally rewritten in the upcoming release. If you still experience a similar issue with the new version, please open a new issue with reproduction steps.
