### ISSUE TITLE
running example gives 'HTTP status code 403'

### ISSUE THREAD

**Issue by sdyura** [deeplearning4j/deeplearning4j#10142]
when i run the EarlyStoppingMNIST example: https://github.com/deeplearning4j/deeplearning4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/quickstart/features/earlystopping/EarlyStoppingMNIST.java

it gives me a 403 error

also when i try and run LinearDataClassifier, i get 403 error:
```
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl4jdata.blob.core.windows.net/dl4j-examples/dl4j-examples/classification.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2014)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1615)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1055)
	at org.nd4j.common.resources.Downloader.lambda$downloadAndExtract$1(Downloader.java:129)
	at org.nd4j.common.resources.Downloader.doOrWait(Downloader.java:197)
	at org.nd4j.common.resources.Downloader.downloadAndExtract(Downloader.java:125)
	at org.nd4j.common.resources.Downloader.downloadAndExtract(Downloader.java:120)
	at org.nd4j.common.resources.Downloader.downloadAndExtract(Downloader.java:101)
	at org.deeplearning4j.examples.utils.DownloaderUtility.Download(DownloaderUtility.java:118)
	at org.deeplearning4j.examples.utils.DownloaderUtility.Download(DownloaderUtility.java:99)
	at org.deeplearning4j.examples.quickstart.modeling.feedforward.classification.LinearDataClassifier.main(LinearDataClassifier.java:71)
```

**Comment by agibsonccc** [comment]
It looks like it's a permissions issue with the account. I'll investigate tomorrow.

**Comment by agibsonccc** [comment]
Give it a day or so. This should be worked out now.

**Comment by sdyura** [comment]
I am still getting the same error, will try again tomorrow

**Comment by sdyura** [comment]
hi, its been a few days but i am still getting that error when running: https://github.com/deeplearning4j/deeplearning4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/quickstart/modeling/feedforward/regression/CSVDataModel.java

```
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl4jdata.blob.core.windows.net/dl4j-examples/dl4j-examples/DataExamples.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2014)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1615)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1055)
	at org.nd4j.common.resources.Downloader.lambda$downloadAndExtract$1(Downloader.java:129)
	at org.nd4j.common.resources.Downloader.doOrWait(Downloader.java:197)
	at org.nd4j.common.resources.Downloader.downloadAndExtract(Downloader.java:125)
	at org.nd4j.common.resources.Downloader.downloadAndExtract(Downloader.java:120)
	at org.nd4j.common.resources.Downloader.downloadAndExtract(Downloader.java:101)
	at org.deeplearning4j.examples.utils.DownloaderUtility.Download(DownloaderUtility.java:118)
	at org.deeplearning4j.examples.utils.DownloaderUtility.Download(DownloaderUtility.java:99)
	at org.deeplearning4j.examples.quickstart.modeling.feedforward.regression.CSVDataModel.main(CSVDataModel.java:66)
```

i think it may be a better idea to host the files on github, as thats where the example code also it

**Comment by m0rt4de114** [comment]
Same here. Response says `AccountIsDisabled`.

**Comment by agibsonccc** [comment]
Track this issue here: https://github.com/deeplearning4j/deeplearning4j/issues/10148
I'm currently talking to microsoft about what's going on there.  The downloads there are hosted on azure.

**Comment by agibsonccc** [comment]
This still might exist yet. I engaged with microsoft again today and will
see if what I did resolves the issue.

**Comment by wmaoxian** [comment]
Me too. Is there anywhere else I can download this zip file?
![微信截图_20241120140907](https://github.com/user-attachments/assets/77820512-75f1-492f-843b-ff55d56dba4e)

**Comment by agibsonccc** [comment]
Unfortunately no. i would just recommend trying other examples for now.

MIcrosoft (the cloud provider) is giving the downloads issues right now.

It's not very high priority since it's not affecting production workloads
but I want to move the datasets and
other examples over to simpler github hosting but I haven't had the time.

I'm working on the background to get this back up and will close this issue
when that is the case.

It's not impossible it's just dealing with a big company can take a while
unfortunately.

**Comment by sdyura** [comment]
all the examples i have tried that seem relevant to my project are failing with 403 error.

having working examples is very important, it makes the difference between a company picking this lib or perhaps an alternative such as https://djl.ai/ to use for the next machine learning project.

**Comment by agibsonccc** [comment]
Yeah of course! Sorry I'm doing what I can. Microsoft should be restoring access any day now.

**Comment by agibsonccc** [comment]
@sdyura  please feel free to track the issue here: https://github.com/deeplearning4j/deeplearning4j/issues/10148 Sorry I know examples are a basic thing that a project needs. It's not really about whether that's understood or not. It's literally a big company we use for hosting being a big company and being a hassle restoring access.  I will be working on a migration after access is restored.

**Comment by agibsonccc** [comment]
Hey folks:

It took a few days but I wanted to notify anyone looking at this that
microsoft FINALLY put me in touch with an actual person after pinging them
daily for the last 2 weeks. I'll hopefully have this resolved within the
week.

**Comment by wmaoxian** [comment]
Thank you. I've been looking forward to it.
