### ISSUE TITLE
TSNEStandardExample exception

### ISSUE THREAD

**Issue by biliboc** [deeplearning4j/deeplearning4j#1017]
If I run it without BLAS library on a windows box works well.

But on my mint laptop throws this:

	o.d.e.t.TSNEStandardExample - Load & Vectorize data....
	Jan 05, 2016 7:14:42 PM com.github.fommil.jni.JniLoader liberalLoad
	INFO: successfully loaded /tmp/jniloader7580272013349128397netlib-native_system-linux-x86_64.so
	o.d.e.t.TSNEStandardExample - Build model....
	o.d.e.t.TSNEStandardExample - Store TSNE Coordinates for Plotting....
	o.d.plot.Tsne - Calculating probabilities of data similarities..
	o.d.plot.Tsne - Mean value of sigma 0.00
	o.d.plot.Tsne - Cost at iteration 0 was 5.545177459716797
	Exception in thread "main" java.lang.IllegalArgumentException: Shapes do not match: x.shape=[1, 2], y.shape=[1, 4]
		at org.nd4j.linalg.api.parallel.tasks.cpu.CPUTaskFactory.getTransformAction(CPUTaskFactory.java:92)
		at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.doTransformOp(DefaultOpExecutioner.java:409)
		at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:62)
		at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2701)
		at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2682)
		at org.deeplearning4j.plot.Tsne.step(Tsne.java:362)
		at org.deeplearning4j.plot.Tsne.calculate(Tsne.java:257)
		at org.deeplearning4j.plot.Tsne.plot(Tsne.java:388)
		at org.deeplearning4j.examples.tsne.TSNEStandardExample.main(TSNEStandardExample.java:57)

**Comment by agibsonccc** [comment]
Please update your example. Thanks!
