### ISSUE TITLE
Scala 2.11 support?

### ISSUE THREAD

**Issue by Hydrotoast** [deeplearning4j/deeplearning4j#1022]
Hi,

I am trying to include `deeplearning4j` into a project that uses Scala 2.11.7 in a Play application. This results in a build error. It looks like `deeplearning4j-nlp` artifact depends on `akka` on Scala 2.10 which results in `Conflicting cross-version suffixes` when I attempt to build the project.

```
[error] Modules were resolved with conflicting cross-version suffixes in {file:/home/hydrotoast/src/project/}m1:
[error]    com.typesafe.akka:akka-actor _2.10, _2.11
[error] (m1/*:update) Conflicting cross-version suffixes in: com.typesafe.akka:akka-actor
java.lang.RuntimeException: Conflicting cross-version suffixes in: com.typesafe.akka:akka-actor
	at scala.sys.package$.error(package.scala:27)
	at sbt.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:46)
	at sbt.ConflictWarning$.apply(ConflictWarning.scala:32)
	at sbt.Classpaths$$anonfun$69.apply(Defaults.scala:1179)
	at sbt.Classpaths$$anonfun$69.apply(Defaults.scala:1176)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] Conflicting cross-version suffixes in: com.typesafe.akka:akka-actor
```

Trying to exclude Akka, I receive the following error:

```
java.lang.ClassNotFoundException: akka.cluster.ClusterActorRefProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(DynamicAccess.scala:67)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(DynamicAccess.scala:66)
	at scala.util.Try$.apply(Try.scala:192)
	at akka.actor.ReflectiveDynamicAccess.getClassFor(DynamicAccess.scala:66)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
	at akka.actor.ActorSystemImpl.liftedTree1$1(ActorSystem.scala:585)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:578)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:126)
	at play.api.libs.concurrent.ActorSystemProvider$.start(Akka.scala:291)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:205)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:61)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:60)
	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:50)
	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at play.runsupport.Reloader$.startDevMode(Reloader.scala:223)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:100)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
```

**Comment by benmccann** [comment]
`deeplearning4j-nlp` really shouldn't depend on all of `deeplearning4j-scaleout-akka`. It could just depend on Akka. It doesn't need all the other crazy stuff that gets pulled in like Zookeeper

**Comment by agibsonccc** [comment]
We pulled the akka dep
