### ISSUE TITLE
Unable to save MultiLayerNetwork as JSON

### ISSUE THREAD

**Issue by TShockman** [deeplearning4j/deeplearning4j#1023]
Attempting to save a MultiLayerNetwork using an ObjectMapper (jackson) led to this exception
```
Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Shapes do not match: x.shape=[150, 3], y.shape=[5, 3] (through reference chain: org.deeplearning4j.nn.multilayer.MultiLayerNetwork["backPropGradient2"])
	at com.blackthorne.ffnn.NNPersist.toJson(NNPersist.java:62)
	at com.blackthorne.ffnn.FFNN.main(FFNN.java:244)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Shapes do not match: x.shape=[150, 3], y.shape=[5, 3] (through reference chain: org.deeplearning4j.nn.multilayer.MultiLayerNetwork["backPropGradient2"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:190)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:671)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:156)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3385)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2779)
	at com.blackthorne.ffnn.NNPersist.toJson(NNPersist.java:58)
	... 1 more
Caused by: java.lang.IllegalArgumentException: Shapes do not match: x.shape=[150, 3], y.shape=[5, 3]
	at org.nd4j.linalg.api.parallel.tasks.cpu.CPUTaskFactory.getTransformAction(CPUTaskFactory.java:92)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.doTransformOp(DefaultOpExecutioner.java:409)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:62)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2660)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2641)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.sub(BaseNDArray.java:2419)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeDeltas2(MultiLayerNetwork.java:805)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.backPropGradient2(MultiLayerNetwork.java:1073)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.getBackPropGradient2(MultiLayerNetwork.java:861)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:536)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:663)
	... 9 more
```
The MultiLayerNetwork is otherwise functional.

**Comment by AlexDBlack** [comment]
Could you provide us with some code that reproduces this issue?

FYI saving the network configuration + parameters separately, as per http://deeplearning4j.org/modelpersistence.html should work.

**Comment by TShockman** [comment]
Here is the relevant code:
```
public static String writeNetwork(MultiLayerNetwork myMultiLayerNetwork) {
                ObjectMapper mapper= new ObjectMapper();
		mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
		mapper.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
		mapper.configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true);
		mapper.enable(SerializationFeature.INDENT_OUTPUT);
		mapper.setVisibility(PropertyAccessor.FIELD, Visibility.ANY);

		try {
			String ret = mapper.writeValueAsString(myMultiLayerNetwork);
			return ret;

		} catch (com.fasterxml.jackson.core.JsonProcessingException e) {
			throw new RuntimeException(e);
		}
}
```
I'm not sure if this is an actual issue or just me misunderstanding how Jackson operates. I ended up just saving the params and configuration as you mentioned above.

**Comment by AlexDBlack** [comment]
Right. Saving network + parameters separately as per the link in my previous comment is what we are supporting currently.
Throwing the whole network, parameters and all, into a json is probably a bad idea. Storing hundreds of thousands or more parameters in json format instead of binary is going to be slow and space inefficient.

**Comment by gokayhuz** [comment]
@AlexDBlack : I am looking for a way to train the network using deeplearning4j and then using the network parameters (weights/coefficients) in another completely different setting. Is there a way to accomplish this? Your "slow and space inefficient" method seems to be my only way, although I cannot find support for this in dl4j.

**Comment by agibsonccc** [comment]
@gokayhuz I'm not sure exactly what you're even trying to do...I am locking this thread. Open up a new issue with your problem and code we can see.
