### ISSUE TITLE
Load Binary files as Input and get the nearest words or vectors of the nearest word.

### ISSUE THREAD

**Issue by Jalaj28** [deeplearning4j/deeplearning4j#1067]
Hi,

I'm using dl4j-spark-ml and I want to load GoogleNews-vectors-negative300.bin .So Is there any way to load binary files and get the words and vectors of them. 

Here is my code.

`import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import org.deeplearning4j.berkeley.StringUtils;
import org.deeplearning4j.models.embeddings.loader.WordVectorSerializer;
import org.deeplearning4j.models.embeddings.wordvectors.WordVectors;
import org.nd4j.linalg.factory.Nd4j;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Word2Vec {
	private static Logger log = LoggerFactory.getLogger(Word2Vec.class);

	public static void main(String[] args) throws IOException {

		log.info("Hi");
		Nd4j.factory().setOrder('f');
		File gModel = new File(args[0]);
		WordVectors vec = WordVectorSerializer.loadGoogleModel(gModel, true);
		// vec = WordVectorSerializer.loadGoogleModel(new File(args[0]),
		// Boolean.parseBoolean(args[1]));

		@SuppressWarnings("unchecked")
		List<String> words = StringUtils.split(args[1], ",");
		for (String s : words) {
			log.info("Vector for word " + Arrays.toString(vec.getWordVector(s)));
			log.info("Words nearest " + vec.wordsNearest(s, 20));

		}

	}
}`

When I buit the project by using mvn and run it on spark.
When I was loading the same and run it on spark I got following message.I didn't get nearest words as well as vector values.
I got following message.

`   [WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=word2vecgoogle.Word2Vec,maxpri=10]
        java.lang.IllegalThreadStateException
        	at java.lang.ThreadGroup.destroy(ThreadGroup.java:778)
        	at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:328)
        	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        	at java.lang.reflect.Method.invoke(Method.java:497)
        	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        [INFO] ------------------------------------------------------------------------
        [INFO] BUILD SUCCESS
        [INFO] ------------------------------------------------------------------------
        [INFO] Total time: 04:57 min
        [INFO] Finished at: 2016-01-19T14:13:39+02:00
        [INFO] Final Memory: 188M/15501M
        [INFO] ------------------------------------------------------------------------
        -- org.jblas INFO Deleting /tmp/jblas4690338666528051339/libjblas.so
        -- org.jblas INFO Deleting /tmp/jblas4690338666528051339/libjblas_arch_flavor.so
        -- org.jblas INFO Deleting /tmp/jblas4690338666528051339
`

**Comment by agibsonccc** [comment]
Hi,

We will upgrade the spark package this week. For now you are welcome to use
the current release of dl4j. See
https://github.com/deeplearning4j/dl4j-0.4-examples

Thanks!

**Comment by agibsonccc** [comment]
Yes. Please see our cdh examples for spark:

https://github.com/deeplearning4j/dl4j-spark-cdh5-examples

You will have to understand training data parallel rnns are different than
normal ones though. Please come in to gitter if you have detailed questions.

These things always depend on a wide variety of conditions and tuning.

It can be obscenely hard to get right.

**Comment by UchePhilz** [comment]
This is how I loaded from bin.
I know this is like really really late.

`try {

        String filePath = new ClassPathResource("googlenews-vectors-negative300.bin").getFile().getAbsolutePath();
        WordVectors wordVectors = WordVectorSerializer.loadStaticModel(new File(filePath));
        boolean hasword = wordVectors.hasWord("Nigeria");
        log.info(hasword+" has");

    }catch(IOException e){
        log.info(e.getMessage());
    }`
