### ISSUE TITLE
ArrayIndexOutOfBounds when training a model using a CSVRecordReader

### ISSUE THREAD

**Issue by klotz94** [deeplearning4j/deeplearning4j#1069]
Hi all, 
I'm trying to train a model using a CSV file. Every time I try I get the following error message:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 97
	at org.nd4j.linalg.factory.BaseNDArrayFactory.concat(BaseNDArrayFactory.java:1065)
	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:4180)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.vstack(BaseNDArrayFactory.java:1200)
	at org.nd4j.linalg.factory.Nd4j.vstack(Nd4j.java:4151)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:166)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:288)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:42)
	at org.deeplearning4j.examples.mlp.MLPHarddriveClassification.main(MLPHarddriveClassification.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
```
The error occurs at the 10th iteration of the while loop when calling the iterator.next()-function.
Here are the relevant lines of code I used (Parts of it are copied from the mnist example):
``` 
RecordReader recordReader = new CSVRecordReader(0,",");
recordReader.initialize(new FileSplit(new ClassPathResource("converted_data.csv").getFile()));
DataSetIterator iterator = new RecordReaderDataSetIterator(recordReader,100,0,2);

DataSet next;
SplitTestAndTrain trainTest;
DataSet trainInput;
List<INDArray> testInput = new ArrayList<>();
List<INDArray> testLabels = new ArrayList<>();

log.info("Build model....");
MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
		.seed(seed)
		.optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
		.iterations(iterations)
		.gradientNormalization(GradientNormalization.RenormalizeL2PerLayer)
		.learningRate(1e-1f)
		.momentum(0.5)
		.momentumAfter(Collections.singletonMap(3, 0.9))
		.useDropConnect(true)
		.list(2)
		.layer(0, new DenseLayer.Builder()
				.nIn(inputNum)
				.nOut(1000)
				.activation("relu")
				.weightInit(WeightInit.XAVIER)
				.build())
		.layer(1, new OutputLayer.Builder(LossFunction.MSE)
				.nIn(1000)
				.nOut(outputNum)
				.activation("softmax")
				.weightInit(WeightInit.XAVIER)
				.build())
		.build();

MultiLayerNetwork model = new MultiLayerNetwork(conf);
model.init();
model.setListeners(Arrays.asList((IterationListener) new ScoreIterationListener(listenerFreq)));

log.info("Train model....");
model.setListeners(Arrays.asList((IterationListener) new ScoreIterationListener(listenerFreq)));
while(iterator.hasNext()) {
	next = iterator.next();
	trainTest = next.splitTestAndTrain(splitTrainNum, new Random(seed)); // train set that is the result
	trainInput = trainTest.getTrain(); // get feature matrix and labels for training
	testInput.add(trainTest.getTest().getFeatureMatrix());
	testLabels.add(trainTest.getTest().getLabels());
	model.fit(trainInput);
}
``` 

And here is a sample of the csv file I used:
```
0,100.0,134.0,131.0,100.0,100.0,100.0,113.0,98.0,100.0,100.0,100.0,100.0,206.0,100.0,100.0,100.0,200.0
0,119.0,52897706.717190444,99.0,100.0,100.0,80.0,6898188226.384396,98.0,100.0,100.0,100.0,90.0,22.0,1819817919593.762,100.0,100.0,200.0
0,100.0,134.0,130.0,100.0,100.0,100.0,113.0,98.0,100.0,100.0,100.0,100.0,222.0,100.0,100.0,100.0,200.0
0,119.0,52897706.717190444,93.0,100.0,100.0,76.0,6898188226.384396,87.0,100.0,100.0,100.0,100.0,26.0,1819817919593.762,100.0,100.0,200.0
0,100.0,100.0,125.0,100.0,100.0,100.0,100.0,97.0,100.0,100.0,100.0,100.0,240.0,100.0,100.0,100.0,200.0
```

Thank you in advance.

**Comment by AlexDBlack** [comment]
So there's no obvious issues with how you are loading the data. Plus I've tested on the 5 lines you provided, and it works fine locally.
It could be a malformed line in the CSV file?
Otherwise, could you provide more data so I can track this down? If it's on the 10th iteration with batch size of 100, I'll need somewhere on the order of the first 1000 lines.

**Comment by klotz94** [comment]
I checked the csv file and everything looks fine. Here is the file I used:
[converted_data.zip](https://github.com/deeplearning4j/deeplearning4j/files/109755/converted_data.zip)

**Comment by AlexDBlack** [comment]
I've checked this on both 0.4-rc3.8 and current DL4J master. Both versions run fine without any issues.

**Comment by klotz94** [comment]
Okay probably it is an installation problem on my side. I will try with the current version. Thank you.

**Comment by AlexDBlack** [comment]
Yeah, check your versions for DL4J, ND4J and Canova. If you can work out a way to reproduce it on rc3.8, I'd be happy to take another look.
