### ISSUE TITLE
Layer.java: Cannot create a transpose Layer

### ISSUE THREAD

**Issue by alexde989** [deeplearning4j/deeplearning4j#1075]
The BaseLayer.java class has a glitch in the transpose method. The method uses an invalid reflection call that results in a NoSuchMethodException the entire details are here -:

Exception in thread "main" java.lang.RuntimeException: unable to construct transposed layer
	at org.deeplearning4j.nn.layers.BaseLayer.transpose(BaseLayer.java:559)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.transpose(RBM.java:196)
	at deeplearning.test.AETest.main(AETest.java:108)
Caused by: java.lang.NoSuchMethodException: org.deeplearning4j.nn.layers.feedforward.rbm.RBM.<init>(org.deeplearning4j.nn.conf.NeuralNetConfiguration, org.nd4j.linalg.api.ndarray.INDArray, org.nd4j.linalg.api.ndarray.INDArray, org.nd4j.linalg.api.ndarray.INDArray)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.deeplearning4j.nn.layers.BaseLayer.transpose(BaseLayer.java:548)
	... 2 more 

To reproduce this just create a simple DBN network with multiple layers and then use the model.getLayers() function to get the array of all the layers in the network. Then call the function transpose() on each of the Layer objects.

**Comment by AlexDBlack** [comment]
also: cloned layer configuration isn't used here: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/BaseLayer.java#L561

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/1077
