### ISSUE TITLE
Convolutional to Dense Layer Assertion Error

### ISSUE THREAD

**Issue by sato-cloudian** [deeplearning4j/deeplearning4j#1080]
I got the following error on my CNN.

```
Exception in thread "main" java.lang.IllegalStateException: Column of left array 3240 != rows of right 1620 or rows of left array 10 != columns of right 500
	at org.nd4j.linalg.util.LinAlgExceptions.assertMultiplies(LinAlgExceptions.java:76)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2480)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2343)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:338)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:356)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:513)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardToLayer(MultiLayerNetwork.java:636)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:590)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1752)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:132)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1497)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1529)
	at org.deeplearning4j.examples.convolution.TrainPeople.execute(TrainPeople.java:186)
	at org.deeplearning4j.examples.convolution.TrainPeople.main(TrainPeople.java:218)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

The source code is [here](https://gist.github.com/sato-cloudian/63aa0675a015052c9c86#file-trainpeople-java). As you can see, it was executed inside of dl4j-0.4-examples(exact version below).

```
commit e4433e5736d6ff02e0520b6acb3e6a5f311ee459
Merge: a140192 3f9de79
Author: Alex Black <blacka101@gmail.com>
Date:   Thu Jan 28 10:19:13 2016 +1100
```

Also, here's the initial investigation by @AlexDBlack .

```
AlexDBlack  12:38
@sato-cloudian hm, so looks like the dense layer is definitely expecting 1620 in, but is getting 3240 in... not sure why, but might be a bug in ConvolutionLayerSetup
```

**Comment by AlexDBlack** [comment]
looking into this more: looks like the issue is in how ConvolutionLayerSetup calculates the output sizes for pooling layers. Specifically, it doesn't take into account the padding for subsampling/pooling layers:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/layers/setup/ConvolutionLayerSetup.java#L220

Should be easy to fix; can probably get this done tomorrow.

**Comment by AlexDBlack** [comment]
Fixed. https://github.com/deeplearning4j/deeplearning4j/pull/1090
