### ISSUE TITLE
Give a better error if .list(X) exceeds the actual number of layers

### ISSUE THREAD

**Issue by sanity** [deeplearning4j/deeplearning4j#1091]
Currently the error is:

`
Exception in thread "main" java.lang.IllegalStateException: No layer defined.
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.build(NeuralNetConfiguration.java:580)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:155)
	at eliza.name.NameKt.buildModel(name.kt:60)
	at eliza.name.NameKt.main(name.kt:33)
`

This could be clearer.  In fact, why is it necessary to specify the number of layers in the first place?

**Comment by AlexDBlack** [comment]
See https://github.com/deeplearning4j/deeplearning4j/pull/1095
improves error messages, plus provides list() and list(Layer...) methods to replace list(int) method (i.e., no longer need to specify number of layers in network).
