### ISSUE TITLE
HistogramIterationListener IndexOutOfBoundsException with RBM pretraining

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1164]
For example, adding a HistogramIterationListener to the DeepAutoEncoderExample, results in the following exception, after some time:
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.deeplearning4j.ui.weights.HistogramIterationListener.iterationDone(HistogramIterationListener.java:112)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:219)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1508)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1544)
	at org.deeplearning4j.examples.deepbelief.DeepAutoEncoderExample.main(DeepAutoEncoderExample.java:82)

**Comment by raver119** [comment]
Fixed within this pr: https://github.com/deeplearning4j/deeplearning4j/pull/1133

Will be merged when pr will be finished.
