### ISSUE TITLE
Error when using spark over video example from scene classification 

### ISSUE THREAD

**Issue by ramsrivatsa** [deeplearning4j/deeplearning4j#1179]
When I try to scale up video classification example in spark using dl4j version 0.4-rc3.8, i get an error 

Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.getUpdater(MultiLayerNetwork.java:2258)
	at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.<init>(SparkDl4jMultiLayer.java:120)
	at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.<init>(SparkDl4jMultiLayer.java:129)
	at edu.umich.clarity.VideoClassificationExample.main(VideoClassificationExample.java:157)

This error is resolved when using 0.4-rc.7 but i get another error as shown below :- 
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'RnnToCnnPreProcessor' into a subtype of [simple type, class org.deeplearning4j.nn.conf.InputPreProcessor]

this is because RnnToCnnPreProcessor is supported in dl4j version 0.4-rc.8 only but the get update function is returning null as it is being called without setting it.

**Comment by theclaymethod** [comment]
Does this still occur if you override the jackson dependency?

In SBT, this looks like `dependencyOverrides ++=Set("com.fasterxml.jackson.core" % "jackson-databind" % "2.4.4")`

**Comment by ramsrivatsa** [comment]
Updated dl4j to 0.4-rc.8
down graded Jackson from 2.5.1 to 2.4.4.
getUpdate issue is fixed but still face jackson issues 

In addition to that found this specific error.

Error while invoking RpcHandler#receive() for one-way message.
org.apache.spark.SparkException: Could not find CoarseGrainedScheduler or it has been stopped.

**Comment by theclaymethod** [comment]
This seems like a spark error now. It could be that an executor died.

**Comment by ramsrivatsa** [comment]
my bad did some typo in the previous one. 
The neural network in VideoClassification requires inputPreProcessor which has RnnToCnnPreProcessor as arguments. These are supported by dl4j to 0.4-rc.8 but when providing that to spark its not able to perform  getUpdate function on the newtork due to the null pointer execption.

when downgrading spark that works but jackson fails.

**Comment by ramsrivatsa** [comment]
Found out the bug. dl4j version 0.4-rc.8 has a bug. When we initialize neural network we have to set updater to null and pass the network to the SparkDl4jMultiLayer.
