### ISSUE TITLE
ArrayIndexOutOfBoundsException in "CNNLFWExample"

### ISSUE THREAD

**Issue by pohsiangchen** [deeplearning4j/deeplearning4j#1225]
I changed the 
1. value of **outputNum**, **numSamples**, **batchSize**
2. **lfw** folder contains 3 persons and each person has 100 images. 
```
public class CNNLFWExample {
    private static final Logger log = LoggerFactory.getLogger(CNNLFWExample.class);
    private static DataSet trainInput;

    public static void main(String[] args) throws Exception {

        final int numRows = 40;
        final int numColumns = 40;
        int nChannels = 3;
        int outputNum = 3; // LFWLoader.NUM_LABELS; // 3483;
        int numSamples = 300; // LFWLoader.NUM_IMAGES; // 10355
        int batchSize = numSamples / 10; // 200;
        int iterations = 5;
        int splitTrainNum = (int) (batchSize * .8);
        int seed = 123;
        int listenerFreq = iterations / 5;
    }
}
```

then I get this exception

```
o.d.e.c.CNNLFWExample - Train model....
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
	at org.nd4j.linalg.util.FeatureUtil.toOutcomeVector(FeatureUtil.java:38)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.getDataSet(RecordReaderDataSetIterator.java:207)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:150)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:288)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:42)
	at org.deeplearning4j.examples.convolution.CNNLFWExample.main(CNNLFWExample.java:145)
```

**Comment by robertChen0925** [comment]
there's no exception until I add more labels >= 10.
1. **outputNum** = 10
2. lfw folder contains 10 persons and each person has 100 images.
```
public class CNNLFWExample {
    private static final Logger log = LoggerFactory.getLogger(CNNLFWExample.class);
    private static DataSet trainInput;

    public static void main(String[] args) throws Exception {

        final int numRows = 40;
        final int numColumns = 40;
        int nChannels = 3;
        int outputNum = 10; // LFWLoader.NUM_LABELS; // 3483;
        int numSamples = 1000; // LFWLoader.NUM_IMAGES; // 10355
        int batchSize = numSamples / 10; // 200;
        int iterations = 5;
        int splitTrainNum = (int) (batchSize * .8);
        int seed = 123;
        int listenerFreq = iterations / 5;
        ...
    }
}
```

**Comment by nyghtowl** [comment]
Required a fix in LimitFileSplit in Canova and the LFWIterator to pass through numCategories (numLabels).
