### ISSUE TITLE
How to use the GRU model

### ISSUE THREAD

**Issue by li910802** [deeplearning4j/deeplearning4j#1259]
Hi,

When I run the GRUTest.java I got the error as below:
Exception in thread "main" java.lang.UnsupportedOperationException: GRU layer disabled: Backprop implementation is incorrect in this version. Consider using GravesLSTM instead
	at org.deeplearning4j.nn.layers.recurrent.GRU.<init>(GRU.java:49)
	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.getInstance(DefaultLayerFactory.java:80)
	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.create(DefaultLayerFactory.java:60)
	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.create(DefaultLayerFactory.java:55)
	at com.rnn.GRUTest.testGRUForwardBasic(GRUTest.java:45)
	at com.rnn.GRUTest.main(GRUTest.java:198)

Please tell me where is the problem, thanks.

**Comment by AlexDBlack** [comment]
"GRU layer disabled: Backprop implementation is incorrect in this version. Consider using GravesLSTM instead"

I'm not sure what else there is to say other than that? It's disabled because we need to fix it, but haven't got to it yet.

**Comment by li910802** [comment]
ok, thanks.
