### ISSUE TITLE
POM.xml dependancy issue

### ISSUE THREAD

**Issue by lakarbatti** [deeplearning4j/deeplearning4j#1282]
Hello everyone. I am new to Deeplearning and ML and have been exploring word2vec code from ==> http://deeplearning4j.org/word2vec#just. I am trying to vectorize some xml content. So to begin with, I use Apache's TIKA to parse my xml and convert it to text, which I then feed into my w2v. I am using intellij + maven. I am unable to run my code since the classpath gets screwed when I include tika's dependancies into my pom as I want to build a pipeline or sorts. Any ideas on how to resolve this? 

Here is the content of POM.xml
```
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.deeplearning</groupId>
    <artifactId>word2vec.test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <nd4j.version>0.4-rc3.9-SNAPSHOT</nd4j.version>
        <dl4j.version>0.4-rc3.9-SNAPSHOT</dl4j.version>
    </properties>

    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases><enabled>false</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
        </repository>
    </repositories>

    <dependencies>

        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-core</artifactId>
            <version>1.12</version>
        </dependency>

        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-parsers</artifactId>
            <version>1.12</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-ui</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-nlp</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-x86</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

    </dependencies>

</project>
```

Here is the error
```
20:19:04.070 [main] INFO  o.d.m.s.SequenceVectors - Starting learning process...
Exception in thread "AsyncSequencer thread" java.lang.NoClassDefFoundError: org/apache/http/conn/HttpClientConnectionManager
	at org.nd4j.linalg.heartbeat.Heartbeat.<init>(Heartbeat.java:35)
	at org.nd4j.linalg.heartbeat.Heartbeat.<clinit>(Heartbeat.java:24)
	at org.deeplearning4j.models.embeddings.wordvectors.WordVectorsImpl.update(WordVectorsImpl.java:259)
	at org.deeplearning4j.models.embeddings.wordvectors.WordVectorsImpl.update(WordVectorsImpl.java:252)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.access$2200(SequenceVectors.java:48)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$AsyncSequencer.run(SequenceVectors.java:786)
Caused by: java.lang.ClassNotFoundException: org.apache.http.conn.HttpClientConnectionManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```

**Comment by raver119** [comment]
This issue should be fixed as soon as new snapshot recompiles. 

Thanks for flagging this out.
