### ISSUE TITLE
add pretrain to GravesLSTM

### ISSUE THREAD

**Issue by montyhall** [deeplearning4j/deeplearning4j#1321]
Possible to add pretraining to gravesLSTM?

Exception in thread "main" java.lang.UnsupportedOperationException: Not yet implemented
    at org.deeplearning4j.nn.layers.recurrent.GravesLSTM.gradient(GravesLSTM.java:55)
    at org.deeplearning4j.nn.layers.BaseLayer.gradientAndScore(BaseLayer.java:507)
    at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:153)
    at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
    at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
    at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:501)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:179)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1017)

**Comment by AlexDBlack** [comment]
The short answer: no. Or at least I haven't seen any unsupervised layerwise pretraining scheme for LSTMs described in the literature, so I'm not sure what it would even look like.

I'll change that message to something a little more informative.
