### ISSUE TITLE
MLPClassifier Feedforward Classification code failing at mode.fit

### ISSUE THREAD

**Issue by vipinn123** [deeplearning4j/deeplearning4j#1339]
Hello

I am trying to reuse the MLPClassifierLinear.java code from the org.deeplearning4j.examples.feedforward.classification package. I changed the input file to point to my dataset (attached). However my code fails at the model.fit statement with the following stack trace. Not sure if this is a data issue or a code issue. Please help if you have come across this error before and resolved it.
[InputandLabels.txt](https://github.com/deeplearning4j/deeplearning4j/files/199031/InputandLabels.txt)

Column1 has the labels (0/1), remaining columns have the features.

I am also attaching my source file.

[MLPNSEClassifier.zip](https://github.com/deeplearning4j/deeplearning4j/files/199069/MLPNSEClassifier.zip)

Apr 01, 2016 10:46:13 AM com.github.fommil.jni.JniLoader liberalLoad
INFO: successfully loaded C:\Users\IBM_AD~1\AppData\Local\Temp\jniloader1286755717174682797netlib-native_system-win-x86_64.dll
Columns :2500  Rows : 74
Columns :2  Rows : 74
o.d.o.s.BaseOptimizer - Objective function automatically set to minimize. Set stepFunction in neural net configuration to change default settings.
Exception in thread "main" java.lang.IllegalStateException: Column of left array 2500 != rows of right 2 or rows of left array 74 != columns of right 10
	at org.nd4j.linalg.util.LinAlgExceptions.assertMultiplies(LinAlgExceptions.java:76)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2480)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2343)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:338)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:356)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:513)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardToLayer(MultiLayerNetwork.java:636)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:590)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1752)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:132)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1168)
	at org.ta.input.MLPNSEClassifier.main(MLPNSEClassifier.java:93)

**Comment by AlexDBlack** [comment]
This is just a configuration issue... you have numInputs = 2, but your CSV file has way more than that. Your numInputs must match the size of the data you are trying to feed into the network.

**Comment by vipinn123** [comment]
Thanks Alex. I changed the numInputs and able to train successfully.
