### ISSUE TITLE
Error running example on Apache Spark

### ISSUE THREAD

**Issue by cqnguyen** [deeplearning4j/deeplearning4j#1361]
I was ran the example code for CNN on my spark cluster version 1.4 - it passed 2 stages before it hit the error on the third stage with the following message:

Exception in thread "main" java.lang.IllegalStateException: No updater to combine
at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.runIteration(SparkDl4jMultiLayer.java:382)
at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.fitDataSet(SparkDl4jMultiLayer.java:281)
at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.fitDataSet(SparkDl4jMultiLayer.java:255)
at org.deeplearning4j.examples.cnn.MnistExample.main(MnistExample.java:132)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:665)
at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:170)
at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:193)
at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:112)
at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by AlexDBlack** [comment]
This was already fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/1028
