### ISSUE TITLE
Neural net initialization fails

### ISSUE THREAD

**Issue by bennythedataguy** [deeplearning4j/deeplearning4j#1366]
Run this:
https://gist.github.com/bennythedataguy/a0b63cf0a92fc9b670280884124eb40a

Here's the pom.xml:
https://gist.github.com/bennythedataguy/7e52d9037c2196132fce2278b0b0d6b5

Built ND4J, DL4J, Canova from source, 2016-05-04

Get this output:
Exception in thread "main" java.lang.AbstractMethodError: org.nd4j.linalg.cpu.CpuNDArrayFactory.toFlattened(CLjava/util/Collection;)Lorg/nd4j/linalg/api/ndarray/INDArray;
	at org.nd4j.linalg.factory.Nd4j.toFlattened(Nd4j.java:1577)
	at org.deeplearning4j.nn.layers.BaseLayer.params(BaseLayer.java:260)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.params(MultiLayerNetwork.java:844)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pack(MultiLayerNetwork.java:903)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.initMask(MultiLayerNetwork.java:1767)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:364)
	at com.hello.TestNetCreation.main(TestNetCreation.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by agibsonccc** [comment]
Class path clash.

**Comment by edoardogiacomello** [comment]
I've got the same problem, any more information how to solve this?

**Comment by raver119** [comment]
The only reason you can get into this issue is you being using rc3.9-SNAPSHOT, but not building libnd4j and nd4j manually. Right now that's the only way to use snapshots.

**Comment by edoardogiacomello** [comment]
I managed to build and install deeplearning4j and all the dependencies (nd4j, libnd4j, canova, javaCpp, etc) without cuda support, but I'm still getting the same error. I also checked the latest commits and they appears in my library source code, so i'm pretty sure i'm referencing the latest snapshots of all the libraries I had to build.
I'm trying to figure out if I'm missing something, but I cannot find anything.
My code is pretty much the same to the one @bennythedataguy posted.

**Comment by treo** [comment]
When you are using the current master, you have to make sure that you **don't** use `nd4j-x86`. You should use `nd4j-native` instead.

**Comment by thealy** [comment]
I tried changing nd4j-x86 to nd4j-native using minimally changed code from Alex Black's example, but still get this error. My deeplearning4j and nd4j set to 0.4-rc3.9-SNAPSHOT; Iava at 1.8. Tried quite an assortment of pom.xml gyrations as suggested by dozens of searches, to no avail. Is this something that will become a moot point when 3.9 is released?

**Comment by raver119** [comment]
The only way to use nd4j snapshot now, is build it manually together with libnd4j.

However, this will change soon.

**Comment by thealy** [comment]
Changed code to use the released 0.4-rc3.9, and still get the same error. With this pom.xml snippet:
	<properties>
		<nd4j.version>0.4-rc3.9</nd4j.version>
		<dl4j.version>0.4-rc3.9</dl4j.version>
	</properties>

	<dependency>
		<groupId>org.nd4j</groupId>
		<artifactId>nd4j-native</artifactId>
		<version>${nd4j.version}</version>
	</dependency>
	<dependency>
		<groupId>org.nd4j</groupId>
		<artifactId>nd4j-cuda-7.5</artifactId>
		<version>${nd4j.version}</version>
	</dependency>
	<dependency>
		<groupId>org.nd4j</groupId>
		<artifactId>nd4j-api</artifactId>
		<version>${nd4j.version}</version>
	</dependency>
