### ISSUE TITLE
"Unable to create a buffer of length <= 0" when creating CNN

### ISSUE THREAD

**Issue by ajohnston9** [deeplearning4j/deeplearning4j#1381]
I'm trying to create a Convolutional Neural Network much like the example but I'm getting an error regarding a negative buffer when init() tries to build the layers. Below is the relevant code and stack trace.

EDIT: Having put the code through a debugger, it looks like layer 4 (the dense layer) is being initialized with a shape array of [-3760, 120]. This appears to be causing the error somewhere down the line. 

EDIT2: Further debugging indicates that the error occurs during the call to ConvolutionLayerSetup()

```
public static void main(String[] args) {
        loadData();
        System.out.println("Configuring model...");
        MultiLayerConfiguration.Builder builder = new NeuralNetConfiguration.Builder()
                .seed(1)
                .iterations(iterations)
                .regularization(true).l2(.0005) //Arbitrary
                .learningRate(0.01)
                .weightInit(WeightInit.XAVIER)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .updater(Updater.NESTEROVS).momentum(0.9)
                .list(6)
                .layer(0, new ConvolutionLayer.Builder(5,5)
                    .nIn(11*200).nOut(20).activation("relu").stride(1,1).dropOut(0.5).build()
                )
                .layer(1,new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.AVG)
                    .kernelSize(4,4).stride(1,1).build()
                )
                .layer(2, new ConvolutionLayer.Builder(5,5)
                    .nIn(1).nOut(20).activation("relu").stride(1,1).dropOut(0.5).build()
                )
                .layer(3, new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.AVG)
                        .kernelSize(2,2).stride(1,1).build()
                )
                .layer(4, new DenseLayer.Builder().activation("relu").nOut(120).build())
                .layer(5, new OutputLayer.Builder().nOut(num_people).activation("softmax").build())
                .backprop(true).pretrain(false);
        new ConvolutionLayerSetup(builder,11,200,1);

        MultiLayerConfiguration conf = builder.build();
        MultiLayerNetwork model = new MultiLayerNetwork(conf);
        model.init();
```
```

Exception in thread "main" java.lang.IllegalArgumentException: Unable to create a buffer of length <= 0
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:259)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:41)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:59)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1010)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:217)
	at org.nd4j.linalg.cpu.NDArray.<init>(NDArray.java:112)
	at org.nd4j.linalg.cpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:234)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3825)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3088)
	at org.nd4j.linalg.api.rng.DefaultRandom.nextGaussian(DefaultRandom.java:113)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.randn(BaseNDArrayFactory.java:710)
	at org.nd4j.linalg.factory.Nd4j.randn(Nd4j.java:2305)
	at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:104)
	at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:123)
	at org.deeplearning4j.nn.params.DefaultParamInitializer.createWeightMatrix(DefaultParamInitializer.java:74)
	at org.deeplearning4j.nn.params.DefaultParamInitializer.init(DefaultParamInitializer.java:46)
	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.getParams(DefaultLayerFactory.java:102)
	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.create(DefaultLayerFactory.java:63)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:352)
	at edu.fordham.cis.wisdm.deep_biometrics.Main.main(Main.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by saudet** [comment]
Based on the sizes of the kernels, you're going to need an image with height and width of at least 13:
```java
new ConvolutionLayerSetup(builder,13,200,1);
```
And that works, but is the issue about that? Or about the cryptic error message?

**Comment by ajohnston9** [comment]
My images are 11*200. Just so I learn, how did you come up with 13*200? How
can I modify it so it works with the size of images I have?

**Comment by saudet** [comment]
One thing you could do is to use padding on the convolution layers with 
```java
new ConvolutionLayer.Builder(5,5).padding(2,2)...
``` 
Details are here: http://deeplearning4j.org/convolutionalnets

**Comment by ajohnston9** [comment]
Now I'm getting the following error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Shapes do not match: x.shape=[10, 12], y.shape=[10, 31]
	at org.nd4j.linalg.api.parallel.tasks.cpu.CPUTaskFactory.getTransformAction(CPUTaskFactory.java:92)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.doTransformOp(DefaultOpExecutioner.java:409)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:62)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2660)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2641)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.sub(BaseNDArray.java:2419)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.getGradientsAndDelta(BaseOutputLayer.java:154)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.backpropGradient(BaseOutputLayer.java:133)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.calcBackpropGradients(MultiLayerNetwork.java:1224)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.backprop(MultiLayerNetwork.java:1178)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1753)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:132)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1497)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1529)
	at edu.fordham.cis.wisdm.deep_biometrics.Main.main(Main.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by saudet** [comment]
I'm not getting that here with the code you posted. Could you provide the updated code?

**Comment by nyghtowl** [comment]
@ajohnston9 can you check this again? #1368 could have solved this.

**Comment by nyghtowl** [comment]
Closing this assuming #1368 solved this issue. If it is still an issue reopen.

**Comment by saifahmedkhan9** [comment]
I am getting this error.. Please help.

java.lang.NullPointerException
	at org.canova.image.loader.ImageLoader.scalingIfNeed(ImageLoader.java:443)
	at org.canova.image.loader.ImageLoader.scalingIfNeed(ImageLoader.java:439)
	at org.canova.image.loader.ImageLoader.asRowVector(ImageLoader.java:114)
	at org.canova.image.recordreader.BaseImageRecordReader.next(BaseImageRecordReader.java:211)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:149)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:288)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:42)
	at com.saifapp.TrainAndTest.training(TrainAndTest.java:62)
	at com.saifapp.App.main(App.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Exception in thread "main" java.lang.IllegalArgumentException: Unable to create a buffer of length <= 0
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:259)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:41)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:59)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1010)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:941)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2603)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2471)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.getDataSet(RecordReaderDataSetIterator.java:186)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:150)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:288)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:42)
	at com.saifapp.TrainAndTest.training(TrainAndTest.java:62)
	at com.saifapp.App.main(App.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by AlexDBlack** [comment]
@saifahmedkhan9 please open a separate issue for this, with the stack trace and some code that we can run to reproduce the issue.
