### ISSUE TITLE
Error while loading native library "libnd4j-windows-x86_64" with base name "libnd4j", when using native backend for CPU

### ISSUE THREAD

**Issue by Habitats** [deeplearning4j/deeplearning4j#1400]
I've been trying to build the native backend for CPU on Windows 10 using Msys2.

Everything built fine using the Msys2 shell and the following commands:
### libnd4j
`bash ./buildnativeoperations.sh blas cpu`

### ND4J
`mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!org.nd4j:nd4j-cuda-7.5,!org.nd4j:nd4j-tests'`

### deeplearning4j
`mvn clean install -DskipTests -Dmaven.javadoc.skip=true`

### Dependencies
```
        compile 'org.deeplearning4j:deeplearning4j-nlp:0.4-rc3.9-SNAPSHOT'
        compile 'org.deeplearning4j:deeplearning4j-ui:0.4-rc3.9-SNAPSHOT'
        compile 'org.deeplearning4j:dl4j-spark:0.4-rc3.9-SNAPSHOT'
        compile 'org.nd4j:nd4j-native:0.4-rc3.9-SNAPSHOT'
```
### Error
However, when try to create a neural network I get the following error:
```
Stack trace from the attempt to load the library as a resource:
java.lang.NullPointerException: No resource found with name '/lib/libnd4j-windows-x86_64.dll'
	at org.nd4j.linalg.cpu.nativecpu.util.LibUtils.loadLibraryResource(LibUtils.java:149)
	at org.nd4j.linalg.cpu.nativecpu.util.LibUtils.loadLibrary(LibUtils.java:83)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOps.<clinit>(NativeOps.java:17)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:28)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4708)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4655)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:146)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:483)
```
```
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: no libnd4j-windows-x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.nd4j.linalg.cpu.nativecpu.util.LibUtils.loadLibrary(LibUtils.java:94)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOps.<clinit>(NativeOps.java:17)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:28)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4708)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4655)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:146)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:483)
```

**Comment by Habitats** [comment]
FYI: I've tried deleting the local maven repo to make sure everything is updated. I've also cleaned the project several times.

**Comment by Habitats** [comment]
Gradle cache was causing problems, pulling an old version. Works now.
