### ISSUE TITLE
CNN issues with nOut on first layer

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#1410]
- nOut on first layer is throwing sig error when less than 3 in a list format and less than 2 on a CompGraph

**Comment by agibsonccc** [comment]
Is this still the case?

**Comment by nyghtowl** [comment]
Still an issue under CompGraph and use this [test](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/graph/TestCompGraphCNN.java#L205)

Fixed for list as show in this [test](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/multilayer/MultiLayerTest.java#L648)

**Comment by AlexDBlack** [comment]
TestCompGraphCNN.testCNNComputationGraphSingleOutFeatureMap() is throwing this exception on my machine:

org.deeplearning4j.nn.conf.inputs.InvalidInputTypeException: Invalid input: activations into layer are h=21 but kernel size is 21 with padding 0

	at org.deeplearning4j.nn.layers.convolution.KernelValidationUtil.validateShapes(KernelValidationUtil.java:16)
	at org.deeplearning4j.nn.conf.graph.LayerVertex.getOutputType(LayerVertex.java:121)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.addPreProcessors(ComputationGraphConfiguration.java:425)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.build(ComputationGraphConfiguration.java:691)
	at org.deeplearning4j.nn.graph.TestCompGraphCNN.testCNNComputationGraphSingleOutFeatureMap(TestCompGraphCNN.java:246)

**Comment by nyghtowl** [comment]
Check that you have the latest deeplearning changes pulled

**Comment by nyghtowl** [comment]
Test is now passing
