### ISSUE TITLE
LSTM GradientCheckTest failures on Linux & Mac

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#1416]
UDPATE 5/13
Getting the following error on testGradientGravesBidirectionalLSTMEdgeCases

java.lang.IllegalArgumentException: B columns must match C columns

	at org.nd4j.linalg.api.blas.params.GemmParams.<init>(GemmParams.java:30)
	at org.nd4j.linalg.api.blas.params.GemmParams.<init>(GemmParams.java:114)
	at org.nd4j.linalg.api.blas.impl.BaseLevel3.gemm(BaseLevel3.java:77)
	at org.nd4j.linalg.factory.Nd4j.gemm(Nd4j.java:728)
	at org.deeplearning4j.nn.layers.recurrent.LSTMHelpers.backpropGradientHelper(LSTMHelpers.java:385)
	at org.deeplearning4j.nn.layers.recurrent.GravesBidirectionalLSTM.backpropGradientHelper(GravesBidirectionalLSTM.java:93)
	at org.deeplearning4j.nn.layers.recurrent.GravesBidirectionalLSTM.backpropGradient(GravesBidirectionalLSTM.java:76)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.calcBackpropGradients(MultiLayerNetwork.java:1093)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.backprop(MultiLayerNetwork.java:1028)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1689)
	at org.deeplearning4j.gradientcheck.GradientCheckUtil.checkGradients(GradientCheckUtil.java:60)
	at org.deeplearning4j.gradientcheck.GradientCheckTests.testGradientGravesBidirectionalLSTMEdgeCases(GradientCheckTests.java:758)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
**

UPDATE 5/9
~~testGradientGravesLSTMFull~~
testGradientGravesBidirectionalLSTMEdgeCases

***************
UPDATE 5/2:
testGradientGravesLSTMEdgeCases
testGradientLSTMBasicMultiLayer
testGradientGravesLSTMFull
testGradientGravesBidirectionalLSTMEdgeCases
testGradientGravesBidirectionalLSTMFull

Seeing failures on all LSTM tests without as follows: https://gist.github.com/nyghtowl/25ddc58e70f3e80de954d5f0e09a9c80

***************************
Running: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/gradientcheck/GradientCheckTests.java#L580

Throws the following errors:
o.d.g.GradientCheckUtil - GradientCheckUtil.checkGradients(): 679 params checked, 567 passed, 112 failed. Largest relative error = 1.0
java.lang.AssertionError: testGradientGravesLSTMEdgeCases() - timeSeriesLength=1, miniBatchSize=1

This has been tested on 2 different Macs and Linux

**Comment by AlexDBlack** [comment]
All passing currently.

**Comment by nyghtowl** [comment]
As noted in the original issue, fails on Linux and Mac. Tested on multiple machines and confirmed as of this latest comment. Do not close until it is confirmed passing on those OS.

**Comment by AlexDBlack** [comment]
It was failing on Windows too up until yesterday FYI. I've done some fixes since then.

**Comment by ds923y** [comment]
So does this imply that the problem is in platform specific code?

**Comment by nyghtowl** [comment]
Passing
