### ISSUE TITLE
Updater:NESTROV now crashes

### ISSUE THREAD

**Issue by sadatanwer** [deeplearning4j/deeplearning4j#1420]
So suddenly today when I tried running a train I got this 
````
2016-04-21 14:13:58.906  [1] WARN:  (BaseEarlyStoppingTrainer.java:117): Early stopping training terminated due to exception at epoch 0, iteration 0
java.lang.NullPointerException
    at org.deeplearning4j.nn.updater.BaseUpdater.applyMomentumDecayPolicy(BaseUpdater.java:78)
    at org.deeplearning4j.nn.updater.BaseUpdater.applyLrDecayPolicy(BaseUpdater.java:114)
    at org.deeplearning4j.nn.updater.BaseUpdater.update(BaseUpdater.java:46)
    at org.deeplearning4j.nn.updater.MultiLayerUpdater.update(MultiLayerUpdater.java:62)
    at org.deeplearning4j.optimize.solvers.BaseOptimizer.updateGradientAccordingToParams(BaseOptimizer.java:288)
    at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:155)
    at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
    at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1365)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1402)
    at org.deeplearning4j.earlystopping.trainer.EarlyStoppingTrainer.fit(EarlyStoppingTrainer.java:59)
    at org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer.fit(BaseEarlyStoppingTrainer.java:113)
````

To my surprise! This was all working perfectly well yesterday. Can some one tell me if I am missing something? or should the system be able to get a default schedule for the decay? 

This is my network setup part 
````
MultiLayerNetwork net =new MultiLayerNetwork(new NeuralNetConfiguration.Builder()
                    .seed(seed)
                    .iterations(numberOfIterations)
                    .optimizationAlgo(algorithm)
                    .learningRate(learningRate)
                    .weightInit(weightInit)
                    .updater(Updater.NESTROV)
                    .momentum(0.9)
                    .list()
                    .layer(0, new DenseLayer.Builder().nIn(inSize).nOut(hiddenNeuronCount)
                            .activation(activationFunction)
                            .build())
                    .layer(1, new OutputLayer.Builder(lossFunction)
                            .activation("identity")
                            .nIn(hiddenNeuronCount).nOut(outSize).build())
                    .pretrain(false).backprop(true).build());
            net.init();
````

**Comment by nyghtowl** [comment]
Resolved momentum decay null pointer: ae61781f55bd49e11299b8da684de1e5cb084f73 and your NESTROV is missing an e and s
