### ISSUE TITLE
Mismatched shape on training when Loading a saved Computation Graph with RMSProp updater

### ISSUE THREAD

**Issue by rubenfiszel** [deeplearning4j/deeplearning4j#1427]
```
    Exception in thread "main" java.lang.IllegalStateException: Mis matched shapes
	at org.nd4j.linalg.util.LinAlgExceptions.assertSameLength(LinAlgExceptions.java:38)
	at org.nd4j.linalg.api.ops.BaseTransformOp.<init>(BaseTransformOp.java:47)
	at org.nd4j.linalg.api.ops.impl.transforms.Set.<init>(Set.java:25)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:1035)
	at org.nd4j.linalg.api.shape.Shape.toOffsetZeroCopyHelper(Shape.java:148)
	at org.nd4j.linalg.api.shape.Shape.toOffsetZeroCopy(Shape.java:103)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.dup(BaseNDArray.java:1362)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.add(BaseNDArray.java:3022)
	at org.nd4j.linalg.learning.RmsProp.getGradient(RmsProp.java:45)
	at org.deeplearning4j.nn.updater.BaseUpdater.update(BaseUpdater.java:48)
	at org.deeplearning4j.nn.updater.graph.ComputationGraphUpdater.update(ComputationGraphUpdater.java:80)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.updateGradientAccordingToParams(BaseOptimizer.java:282)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:155)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:549)
	at ccup.SelfPlay$.trainModelRLDeep(SelfPlay.scala:86)
	at ccup.SoloGame$$anonfun$1.apply$mcVI$sp(SoloGame.scala:99)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
	at ccup.SoloGame$.delayedEndpoint$ccup$SoloGame$1(SoloGame.scala:98)
	at ccup.SoloGame$delayedInit$body.apply(SoloGame.scala:49)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at ccup.SoloGame$.main(SoloGame.scala:49)
	at ccup.SoloGame.main(SoloGame.scala)

```

Step to reproduce, save aand load a computation graph with RMSProp updater, then fit data.

**Comment by atollFP** [comment]
I guess I expected the ModelUtil to save also the updater and that it doesn't.

**Comment by agibsonccc** [comment]
Is this fixed?

**Comment by anil-tiwari** [comment]
bug is still there.

**Comment by eraly** [comment]
There is now functionality to save the updater. I am closing this out
