### ISSUE TITLE
LSTM backprop failing for minibatch size of 1

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1454]
Post the recent changes to tensorAlongDimension, LSTMs are failing with minibatch size of 1.

For example, the LSTM character example with minibatch size set to 1 throws the following exception:
Exception in thread "main" java.lang.IllegalStateException: Column of left array 50 != rows of right 200 or rows of left array 200 != columns of right 77
	at org.nd4j.linalg.util.LinAlgExceptions.assertMultiplies(LinAlgExceptions.java:80)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2476)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2342)
	at org.deeplearning4j.nn.layers.BaseLayer.preOutput(BaseLayer.java:327)
	at org.deeplearning4j.nn.layers.BaseLayer.preOutput(BaseLayer.java:314)
	at org.deeplearning4j.nn.layers.recurrent.RnnOutputLayer.preOutput2d(RnnOutputLayer.java:111)
	at org.deeplearning4j.nn.layers.recurrent.RnnOutputLayer.output(RnnOutputLayer.java:144)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.activate(BaseOutputLayer.java:248)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnActivateUsingStoredState(MultiLayerNetwork.java:2119)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1684)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:152)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doTruncatedBPTT(MultiLayerNetwork.java:1162)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1397)
	at org.deeplearning4j.examples.recurrent.character.GravesLSTMCharModellingExample.main(GravesLSTMCharModellingExample.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by Cryddit** [comment]
Appears to happen because no information is carried over between minibatches. This means LSTMs don't have access to values set or changed or preserved from the previous activation.They go into every new minibatch with freshly-initiaized values that have nothing to do with any ongoing situation.

This is a general issue for Recurrent networks of all kinds, not just LSTMs.  It's unclear what semantics would be meaningful for minibatch sizes smaller than the time over which memory/state needs to be preserved.

**Comment by AlexDBlack** [comment]
Fixed: https://github.com/deeplearning4j/deeplearning4j/pull/1469
