### ISSUE TITLE
Word2vec gets stuck in an infinite loop when the input text file has blank lines

### ISSUE THREAD

**Issue by nmramesh** [deeplearning4j/deeplearning4j#147]
I am running the class org.deeplearning4j.word2vec.Word2VecExample from dl4j-examples project with version number 0.0.3.2.7. The dl4j version it depends on is 0.0.3.2.7 as well.

When I run on my linux machine with the following command:
```
mvn exec:java -Dexec.mainClass="org.deeplearning4j.word2vec.Word2VecExample" -Dexec.args="toy.txt"
```
on the input file containing the following text (with the middle line left blank):
--------------------- toy.txt file --------------------------
A Russian Soyuz rocket carrying a Russo - Belgian cosmonaut team successfully docked with the > International Space Station early Friday , Russian mission control said .

Manly have offered Ben Walker the chance of a return to Australia 's National Rugby League , but > any switch depends on the former Northern Eagles standoff negotiating a release from his Leeds > contract .
--------------------- end of toy.txt file ----------------------

I get the following output:

SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
o.d.b.v.BaseTextVectorizer - latch count 2 with queued 3
o.d.b.v.BaseTextVectorizer - latch count 2 with queued 3
o.d.b.v.BaseTextVectorizer - latch count 2 with queued 3
o.d.b.v.BaseTextVectorizer - latch count 2 with queued 3
o.d.b.v.BaseTextVectorizer - latch count 2 with queued 3
o.d.b.v.BaseTextVectorizer - latch count 2 with queued 3

If I delete the blank middle line, the run is successful with the following output:

o.d.b.v.BaseTextVectorizer - latch count 2 with queued 2
o.d.b.v.BaseTextVectorizer - Invoking finish on index
o.d.m.w.Word2Vec - Building binary tree
o.d.m.w.Word2Vec - Constructing priority queue
o.d.m.w.Word2Vec - Built tree
o.d.m.w.Word2Vec - Resetting weights
o.d.m.w.Word2Vec - Training word2vec multithreaded
o.d.m.w.Word2Vec - Processing sentences...
[WARNING] thread Thread[ForkJoinPool-3-worker-15,5,org.deeplearning4j.word2vec.Word2VecExample] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[ForkJoinPool-3-worker-15,5,org.deeplearning4j.word2vec.Word2VecExample] will linger despite being asked to die via interruption
[WARNING] thread Thread[ForkJoinPool-3-worker-29,5,org.deeplearning4j.word2vec.Word2VecExample] will linger despite being asked to die via interruption
[WARNING] NOTE: 2 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=org.deeplearning4j.word2vec.Word2VecExample,maxpri=10]
java.lang.IllegalThreadStateException
	at java.lang.ThreadGroup.destroy(ThreadGroup.java:775)
	at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:328)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.201 s
[INFO] Finished at: 2015-02-05T14:08:13-05:00
[INFO] Final Memory: 20M/310M
[INFO] ------------------------------------------------------------------------

**Comment by agibsonccc** [comment]
Could you please test this with 0.0.3.3.x as well? I'm assuming this is a forward bug but it'd be good to understand the scope. Thanks!

**Comment by agibsonccc** [comment]
I skip blank lines with the vectorizer now. Should be good to go in latest commit. Re open this if there's any issues.
