### ISSUE TITLE
MultipleEpochsIteratorTest: NPE in unit test

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1473]
In MultipleEpochsIteratorTest.testNextAndReset()

java.lang.NullPointerException
	at org.nd4j.linalg.dataset.DataSet.<init>(DataSet.java:85)
	at org.nd4j.linalg.dataset.DataSet.<init>(DataSet.java:74)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.getDataSet(RecordReaderDataSetIterator.java:267)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:170)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:335)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:47)
	at org.deeplearning4j.datasets.iterator.MultipleEpochsIterator.next(MultipleEpochsIterator.java:66)
	at org.deeplearning4j.datasets.iterator.MultipleEpochsIterator.next(MultipleEpochsIterator.java:75)
	at org.deeplearning4j.datasets.iterator.MultipleEpochsIteratorTest.testNextAndReset(MultipleEpochsIteratorTest.java:58)

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/1478
