### ISSUE TITLE
Unit test failure: ConvolutionLayerSetupTest.testDenseToOutputLayer

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1475]
java.lang.IllegalStateException: Mis matched shapes

	at org.nd4j.linalg.util.LinAlgExceptions.assertSameLength(LinAlgExceptions.java:38)
	at org.nd4j.linalg.api.ops.BaseTransformOp.<init>(BaseTransformOp.java:47)
	at org.nd4j.linalg.api.ops.impl.transforms.Set.<init>(Set.java:25)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:1061)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3293)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3333)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3573)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayerSetupTest.testDenseToOutputLayer(ConvolutionLayerSetupTest.java:95)

**Comment by AlexDBlack** [comment]
Fixed: https://github.com/deeplearning4j/deeplearning4j/pull/1478
