### ISSUE TITLE
error in running deeplearning4j-example:Word2VecSentimentRNN

### ISSUE THREAD

**Issue by mansiisnam** [deeplearning4j/deeplearning4j#1495]
Data (.tar.gz file) already exists at D:\eclipse\work\aclImdb_v1.tar.gz
五月 03, 2016 3:52:49 下午 com.github.fommil.jni.JniLoader liberalLoad
信息: successfully loaded E:\intellij\blas\netlib-native_system-win-x86_64.dll
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:268)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:41)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:59)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1010)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:217)
	at org.nd4j.linalg.cpu.NDArray.<init>(NDArray.java:112)
	at org.nd4j.linalg.cpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:234)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3825)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3794)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3068)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readBinaryModel(WordVectorSerializer.java:182)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadGoogleModel(WordVectorSerializer.java:97)
	at test.TestWord2VecSentimentRNN.main(TestWord2VecSentimentRNN.java:90)

I'm sorry to bother you again.I used 4096m memory to run the program but failed.  How much memory should I use to run this program?

**Comment by agibsonccc** [comment]
Please use gitter for this. Thanks!
