### ISSUE TITLE
OutOfMemoryError: Cannot allocate 3740963793 bytes on moderate network

### ISSUE THREAD

**Issue by wutzebaer** [deeplearning4j/deeplearning4j#1505]
When running the class i get an OOM after ~5mins

OS Ubuntu 16.04 x64
libnd4j d88c07964267217618e728530e31e7b9db15c492
nd4j a59714a5502a578bc361cb141fd5b4ecefb1e84c
dl4j ba4fe100a6c8d574ee29a00c493e8f80f90c8b47

code to run
```
mvn clean package
java -jar target/deeplearning4j-examples-0.4-rc0-SNAPSHOT-bin.jar
```

pom

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<prerequisites>
		<maven>3.0.5</maven>
	</prerequisites>

	<groupId>org.deeplearning4j</groupId>
	<artifactId>deeplearning4j-examples</artifactId>
	<version>0.4-rc0-SNAPSHOT</version>

	<name>DeepLearning4j Examples</name>
	<description>Examples of training different data sets</description>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<shadedClassifier>bin</shadedClassifier>
		<java.version>1.8</java.version>
		<nd4j.version>0.4-rc3.9-SNAPSHOT</nd4j.version>
		<dl4j.version>0.4-rc3.9-SNAPSHOT</dl4j.version>
		<maven-shade-plugin.version>2.4.3</maven-shade-plugin.version>
		<exec-maven-plugin.version>1.4.0</exec-maven-plugin.version>
	</properties>

	<repositories>
		<repository>
			<id>snapshots-repo</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>

	<distributionManagement>
		<snapshotRepository>
			<id>sonatype-nexus-snapshots</id>
			<name>Sonatype Nexus snapshot repository</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</snapshotRepository>
		<repository>
			<id>nexus-releases</id>
			<name>Nexus Release Repository</name>
			<url>http://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
		</repository>
	</distributionManagement>

	<dependencies>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20090211</version>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-core</artifactId>
			<version>${dl4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>dl4j-spark</artifactId>
			<version>${dl4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native</artifactId>
			<!-- <artifactId>nd4j-cuda-7.5</artifactId> -->
			<!-- <artifactId>nd4j-native</artifactId> -->
			<version>${nd4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.1</version>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>19.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-collections4</artifactId>
			<version>4.0</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>${exec-maven-plugin.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>exec</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<executable>java</executable>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>${maven-shade-plugin.version}</version>
				<configuration>
					<shadedArtifactAttached>true</shadedArtifactAttached>
					<shadedClassifierName>${shadedClassifier}</shadedClassifierName>
					<createDependencyReducedPom>true</createDependencyReducedPom>
					<filters>
						<filter>
							<artifact>*:*</artifact>
							<excludes>
								<exclude>org/datanucleus/**</exclude>
								<exclude>META-INF/*.SF</exclude>
								<exclude>META-INF/*.DSA</exclude>
								<exclude>META-INF/*.RSA</exclude>
							</excludes>
						</filter>
					</filters>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<transformers>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
									<resource>reference.conf</resource>
								</transformer>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
								</transformer>
							</transformers>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.5.1</version>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>
							<mainClass>test.CrashSample</mainClass>
						</manifest>
					</archive>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>

```

exception
```
java.lang.OutOfMemoryError: Cannot allocate 3740963793 bytes
        at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:433)
        at org.bytedeco.javacpp.Pointer.init(Pointer.java:118)
        at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
        at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
        at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:563)
        at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:40)
        at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:227)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1157)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:225)
        at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:107)
        at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:239)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4026)
        at org.nd4j.linalg.api.shape.Shape.toOffsetZeroCopyHelper(Shape.java:147)
        at org.nd4j.linalg.api.shape.Shape.toOffsetZeroCopy(Shape.java:103)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.dup(BaseNDArray.java:1420)

```

CrashSample.java
```
package test;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import org.deeplearning4j.nn.api.OptimizationAlgorithm;
import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration.ListBuilder;
import org.deeplearning4j.nn.conf.Updater;
import org.deeplearning4j.nn.conf.distribution.GaussianDistribution;
import org.deeplearning4j.nn.conf.layers.DenseLayer;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.conf.layers.OutputLayer.Builder;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.optimize.listeners.ScoreIterationListener;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.lossfunctions.LossFunctions;

public class CrashSample {

	private static final double factor = 800;
	private static final int maxRandomFutureCount = 1440 * 1;
	private static final int maxRandomHistoryCount = 1440 * 5;
	private static final double minPlus = 2 / factor;
	private static final Random r = new Random(System.currentTimeMillis());
	private static final List<Double> values = new ArrayList<>();

	public static void main(String[] args) throws IOException, Exception {
		for (int x = 0; x < 179916; x++) {
			values.add(0d);
		}

		int cores = 6;
		for (int c = 0; c < cores; c++) {
			new Thread(new Runnable() {
				public void run() {
					while (true)
						try {
							runRamdomHyperParameters();
						} catch (Throwable e) {
							e.printStackTrace();
							System.exit(0);
						}
				}
			}).start();
		}

	}

	private static void runRamdomHyperParameters() throws IOException {
		int historycount = (int) (maxRandomHistoryCount * r.nextDouble());
		int futurecount = (int) (maxRandomFutureCount * r.nextDouble());
		int hiddenLayerCount = 1 + r.nextInt(6);
		int hiddenLayerWidth = 10 + r.nextInt(150);
		int samplesPerDataSet = 1;
		int iterations = 1;
		double weightA = 0;
		double weightB = r.nextDouble();

		GaussianDistribution weightDist = new GaussianDistribution(weightA, weightB);

		NeuralNetConfiguration.Builder builder = new NeuralNetConfiguration.Builder();
		builder.iterations(iterations);
		builder.learningRate(1e-5);
		builder.seed(123);

		builder.regularization(true);

		builder.updater(Updater.SGD);

		builder.optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT);
		builder.biasInit(0);
		builder.miniBatch(true);
		builder.weightInit(WeightInit.DISTRIBUTION);
		builder.dist(weightDist);
		builder.activation("relu");
		// builder.gradientNormalization(GradientNormalization.ClipElementWiseAbsoluteValue);

		ListBuilder listBuilder = builder.list();
		for (int i = 0; i < hiddenLayerCount; i++) {
			DenseLayer.Builder hiddenLayerBuilder = new DenseLayer.Builder();
			hiddenLayerBuilder.nIn(i == 0 ? historycount : hiddenLayerWidth);
			hiddenLayerBuilder.nOut(hiddenLayerWidth);
			listBuilder.layer(i, hiddenLayerBuilder.build());
		}

		Builder outputLayerBuilder = new OutputLayer.Builder(LossFunctions.LossFunction.SQUARED_LOSS);
		outputLayerBuilder.nIn(hiddenLayerWidth);
		outputLayerBuilder.nOut(1);
		outputLayerBuilder.activation("sigmoid");
		listBuilder.layer(hiddenLayerCount, outputLayerBuilder.build());

		listBuilder.pretrain(false);
		listBuilder.backprop(true);
		listBuilder.build();

		MultiLayerConfiguration conf = listBuilder.build();
		MultiLayerNetwork net = new MultiLayerNetwork(conf);
		net.init();
		net.setListeners(new ScoreIterationListener(1));

		for (int epoch = 0; epoch < 2000; epoch++) {
			DataSet ds = createDataset(samplesPerDataSet, historycount, futurecount, minPlus);
			net.fit(ds);
		}

	}

	public static DataSet createDataset(int samplesPerDataset, int historycount, int futurecount, double minPlus) {
		INDArray input = Nd4j.zeros(samplesPerDataset, historycount);
		INDArray labels = Nd4j.zeros(samplesPerDataset, 1);
		for (int sampleindex = 0; sampleindex < samplesPerDataset; sampleindex++) {
			int startindex = (int) ((values.size() - (historycount + futurecount)) * r.nextDouble());
			fillFromStartIndex(input, labels, sampleindex, startindex, historycount, futurecount, minPlus);
		}
		DataSet ds = new DataSet(input, labels);
		return ds;
	}

	static void fillFromStartIndex(INDArray input, INDArray labels, int sampleindex, int startindex, int historycount, int futurecount, double minPlus) {

		double firstvalue = values.get(startindex);
		for (int samplePos = 0; samplePos < historycount; samplePos++) {
			input.putScalar(new int[] { sampleindex, samplePos }, values.get(startindex + samplePos) - firstvalue);
		}

		labels.putScalar(new int[] { sampleindex, 0 }, 0);
		double lastvalue = values.get(startindex + (historycount - 1));
		for (int futureindex = 0; futureindex < futurecount; futureindex++) {
			Double newValue = values.get(startindex + historycount + futureindex);
			if (newValue - lastvalue > minPlus) {
				labels.putScalar(new int[] { sampleindex, 0 }, 1);
				break;
			}
		}
	}
}
```

**Comment by raver119** [comment]
Mind adding some system info? What's -Xmx? How much ram your system actually has?

**Comment by wutzebaer** [comment]
i started without xmx params, the system had 16GB ram and 8 cores

**Comment by saudet** [comment]
I'm able to reproduce the error on my machine. It's not possible to guarantee that garbage collection will actually take place after a `System.gc()`, but if we make the CPU idle long enough it should eventually kick in. 1 second in total seems to be enough on my machine: https://github.com/bytedeco/javacpp/commit/f55847f442f304fa60af70023604c6eff4262392

@wutzebaer Could you try again with this change and let me know if this looks good enough?

**Comment by nyghtowl** [comment]
@wutzebaer if you still see an issue please reopen

**Comment by siddharthBohra** [comment]
Hi,
I am running the word2VecSentimentRNN, and downloaded the GoogleNews-vectors-negative300.bin model.

I got the following error,

Exception in thread "main" java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(300): totalBytes = 3G, physicalBytes = 7G
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:76)
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:41)
	at org.nd4j.compression.impl.AbstractCompressor.compress(AbstractCompressor.java:127)
	at org.nd4j.compression.impl.AbstractCompressor.compress(AbstractCompressor.java:102)
	at org.nd4j.storage.CompressedRamStorage.store(CompressedRamStorage.java:68)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadStaticModel(WordVectorSerializer.java:2450)
	at org.deeplearning4j.examples.recurrent.word2vecsentiment.Word2VecSentimentRNN.main(Word2VecSentimentRNN.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes = 7G > maxPhysicalBytes = 7G
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:562)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
	at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
	... 11 more

I have the following in my idea.exe.vmoptions.
-server
-Xms128m
-Xmx10000m
-XX:ReservedCodeCacheSize=240m
-XX:+UseConcMarkSweepGC
-XX:SoftRefLRUPolicyMSPerMB=50
-ea
-Dsun.io.useCanonCaches=false
-Djava.net.preferIPv4Stack=true
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-XX:+UseG1GC
-XX:MaxGCPauseMillis=100

OS: 64bit windows 7
RAM : 16GB.

Kindly help me to resolve the issue. Please.

**Comment by siddharthBohra** [comment]
@raver119 I know this is not related to the arbiter. But can you help me in the query i raised above.?

**Comment by raver119** [comment]
You should set -Xmx value for your app, NOT for intelli idea. idea.exe.vmoptions has nothing to do with your application.

If you're launching your app from intellij idea - you should go to Run -> Edit configurations -> find the file you're ruinning in the lst -> add -Xmx10G to VM options text box.

**Comment by raver119** [comment]
And please stop spamming in closed issues. Your issue has nothing to do with issues like this one.

Got problem? File new issue.
