### ISSUE TITLE
[NullPointerException] WordVectorSerializer.loadTxtVectors

### ISSUE THREAD

**Issue by rehm** [deeplearning4j/deeplearning4j#1517]
Hi, 

i use the 0.4-rc3.9-SNAPSHOT Version and since yesterday the WordVectorSerializer.loadTxtVectors throw following Exception.   
 
```
File VectorFile = new File(App.class.getClassLoader().getResource("glove_model-6B.50d.txt").toURI());
WordVectors vec = WordVectorSerializer.loadTxtVectors(VectorFile);
```

Exception:

```
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4788)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4716)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:148)
	... 7 more
Caused by: java.lang.NullPointerException
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4749)
	... 9 more
```

**Comment by AlexDBlack** [comment]
Are you building nd4j and libnd4j from source? That's necessary currently.
Also you need to be using nd4j-native if you are using latest version - make sure you don't have a reference to nd4j-x86 in your pom/classpath.

**Comment by raver119** [comment]
Discussed that it in gitter: wrong backend used, nd4j-x86.
