### ISSUE TITLE
image-data-pipeline tutorial not working

### ISSUE THREAD

**Issue by plankes-projects** [deeplearning4j/deeplearning4j#1547]
Hello,

I am trying to implement a simple image recognition. 
I followed the tutorial on http://deeplearning4j.org/image-data-pipeline und used the following LFW images as data 
Training data: http://vis-www.cs.umass.edu/lfw/lfw-a.tgz

I attached my implementation. it should be exactly like the tutorial. But i get listed error.
Additionally the Evaluation class in this tutorial has the warning rawtypes.

Exception in thread "main" java.lang.IllegalArgumentException: Shapes do not match: x.shape=[10, 784], y.shape=[10, 432]
	at org.nd4j.linalg.api.parallel.tasks.cpu.CPUTaskFactory.getTransformAction(CPUTaskFactory.java:92)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.doTransformOp(DefaultOpExecutioner.java:409)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:62)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2660)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2641)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.sub(BaseNDArray.java:2419)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.getGradientsAndDelta(BaseOutputLayer.java:154)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.computeGradientAndScore(BaseOutputLayer.java:98)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:132)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:151)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.fit(BaseOutputLayer.java:363)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.finetune(MultiLayerNetwork.java:1430)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1482)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1529)
	at projecta_learning.TrainingLFW.main(TrainingLFW.java:64)

[TrainingLFW.txt](https://github.com/deeplearning4j/deeplearning4j/files/266034/TrainingLFW.txt)

**Comment by plankes-projects** [comment]
The problem is following:

In the config, the last layer defines .nOut(NUM_OF_CLASSES)
This has to match the number of subdirectories you have.
