### ISSUE TITLE
image-data-pipeline tutorial not working 0.4-rc3.9 (null pointer exception)

### ISSUE THREAD

**Issue by plankes-projects** [deeplearning4j/deeplearning4j#1584]
Hi,

Running the tutorial given on http://deeplearning4j.org/image-data-pipeline results in a null pointer exception in 0.4-rc3.9.

<pre>
Exception in thread "main" java.lang.NullPointerException
    at org.nd4j.linalg.dataset.DataSet.<init>(DataSet.java:85)
    at org.nd4j.linalg.dataset.DataSet.<init>(DataSet.java:74)
    at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.getDataSet(RecordReaderDataSetIterator.java:267)
    at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:170)
    at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:335)
    at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:47)
    at manual.TrainingLFW.main(TrainingLFW.java:58)
</pre>

Here is the setup [data.zip](https://github.com/deeplearning4j/deeplearning4j/files/275934/data.zip)

**Comment by christopher-beckham** [comment]
Am having this issue as well.

**Comment by JohnTheDang** [comment]
I also had this problem, but seems to have been solved by putting -1 instead of 784 (i.e. the nbr pixels) when creating the RecordReaderDataSetIterator.

**Comment by agibsonccc** [comment]
This is fixed now from what I understand.

**Comment by plankes-projects** [comment]
to put -1 is just a workaround, in my opinion this is not fixed

**Comment by pavin** [comment]
"DataSet getDataSet(Collection<Writable> record)" method in RecordReaderDataSetIterator.java always throws NPE.
the last line in method, "return new DataSet(featureVector, labelIndex >= 0 ? label : featureVector)", label is always null.

**Comment by saudet** [comment]
Since the image is now 1 value, we can also use 1 instead of -1. So, what should we put? 1 or -1?

**Comment by agibsonccc** [comment]
This has been fixed for a while.
