### ISSUE TITLE
Exception when calling method `Word2Vec::wordsNearest` after loading with `Word2VecSerializer::loadGoogleModel`

### ISSUE THREAD

**Issue by tikue** [deeplearning4j/deeplearning4j#160]
Using:

1. The Google News-trained model available [here](https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit)
2. nd4j version 0.0.3.5.5.3-SNAPSHOT
3. dl4j version 0.0.3.3.3.alpha1-SNAPSHOT

The following test program:
```java
import org.deeplearning4j.models.embeddings.loader.WordVectorSerializer;
import org.deeplearning4j.models.word2vec.Word2Vec;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.InputStreamReader;

public class Word2VecTest {
  private static Logger log = LoggerFactory.getLogger(Word2VecTest.class);

  public static void main(String[] args) throws Exception {
    log.debug("Loading google model...");
    final Word2Vec word2Vec = WordVectorSerializer.loadGoogleModel(
        "/Users/../Downloads/GoogleNews-vectors-negative300.bin", true);
    log.debug("Done.");

    System.out.print("word: ");
    new BufferedReader(new InputStreamReader(System.in))
        .lines()
        .forEach(word -> {
          System.out.println("\twords nearest " + word + ": " + word2Vec.wordsNearest(word, 10));
        });
  }
}
```

causes the following exception to be thrown:
```
word: word
Exception in thread "main" java.lang.IllegalStateException: Given ndarray does not have data type float
	at org.nd4j.linalg.factory.DataTypeValidation.assertFloat(DataTypeValidation.java:26)
	at org.nd4j.linalg.factory.DataTypeValidation.assertFloat(DataTypeValidation.java:17)
	at org.nd4j.linalg.jblas.BlasWrapper.gemv(BlasWrapper.java:494)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2528)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2349)
	at org.deeplearning4j.models.embeddings.wordvectors.WordVectorsImpl.wordsNearest(WordVectorsImpl.java:274)
	at org.deeplearning4j.models.embeddings.wordvectors.WordVectorsImpl.wordsNearest(WordVectorsImpl.java:321)
	at Word2VecTest.lambda$main$0(Word2VecTest.java:22)
	at Word2VecTest$$Lambda$1/2083117811.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at Word2VecTest.main(Word2VecTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by agibsonccc** [comment]
Hi, This happens whenever you mix floats and double data types. By default the word vector loader uses floats. You can force the data type via Nd4j:
   Nd4j.dtype = DataBuffer.FLOAT.

Or -Ddtype=float in your command line.

**Comment by tikue** [comment]
Hey, thank you for the swift response! That fixed the problem. As luck would have it, I'm now running into another mysterious bug. I figure I'll post it here instead of making another potentially unnecessary issue -- I apologize in advance if this isn't the correct place for this.

Using the same setup as above (except with `Nd4j.dtype = DataBuffer.FLOAT` at the top of the main method), I'm now seeing incorrect behavior from `wordsNearest`:

```
word: day
	words nearest 'day': [snowcapped_Caucasus, pulverizes_boulders, Mezze_Cafe, Bim_Skala_Bim, RAFFAELE, righthander_Kyle_Drabek, Thirsty_Owl, divider_pistons, Shilpa_Goenka, Mauri_Liberati, USA_TODAY_Reid_Cherner]
word: Obama
	words nearest 'Obama': [snowcapped_Caucasus, pulverizes_boulders, Mezze_Cafe, Bim_Skala_Bim, RAFFAELE, righthander_Kyle_Drabek, Thirsty_Owl, divider_pistons, Shilpa_Goenka, Mauri_Liberati, USA_TODAY_Reid_Cherner]
word: snow
	words nearest 'snow': [snowcapped_Caucasus, pulverizes_boulders, Mezze_Cafe, Bim_Skala_Bim, RAFFAELE, righthander_Kyle_Drabek, Thirsty_Owl, divider_pistons, Shilpa_Goenka, Mauri_Liberati, USA_TODAY_Reid_Cherner]
```

The same nearest words are returned for "day," "Obama," and "snow." Notably, the words returned are the most recent words loaded by `Word2VecSerializer:

```
11:44:07.854 [main] INFO  o.d.m.e.loader.WordVectorSerializer - Loading USA_TODAY_Reid_Cherner with word 2999989
11:44:07.854 [main] INFO  o.d.m.e.loader.WordVectorSerializer - Loading Mauri_Liberati with word 2999990
11:44:07.854 [main] INFO  o.d.m.e.loader.WordVectorSerializer - Loading Shilpa_Goenka with word 2999991
11:44:07.854 [main] INFO  o.d.m.e.loader.WordVectorSerializer - Loading divider_pistons with word 2999992
11:44:07.854 [main] INFO  o.d.m.e.loader.WordVectorSerializer - Loading Thirsty_Owl with word 2999993
11:44:07.854 [main] INFO  o.d.m.e.loader.WordVectorSerializer - Loading righthander_Kyle_Drabek with word 2999994
11:44:07.854 [main] INFO  o.d.m.e.loader.WordVectorSerializer - Loading RAFFAELE with word 2999995
11:44:07.854 [main] INFO  o.d.m.e.loader.WordVectorSerializer - Loading Bim_Skala_Bim with word 2999996
11:44:07.854 [main] INFO  o.d.m.e.loader.WordVectorSerializer - Loading Mezze_Cafe with word 2999997
11:44:07.854 [main] INFO  o.d.m.e.loader.WordVectorSerializer - Loading pulverizes_boulders with word 2999998
11:44:07.854 [main] INFO  o.d.m.e.loader.WordVectorSerializer - Loading snowcapped_Caucasus with word 2999999
```

Could this be underflow related?

**Comment by tikue** [comment]
Just wondering if anyone has been able to reproduce this problem?

**Comment by c0der1337** [comment]
Hey guys,

I saw this post to late, but I think your original issue is fixed. So I opened a new issue: https://github.com/deeplearning4j/deeplearning4j/issues/175 about the unexpected results of words nearest. The weightMatrix is in a false format for the setSyn0() . To fix it you have to add a transpose()
