### ISSUE TITLE
Errors while loading GoogleNews-vectos-negative300.bin.gz

### ISSUE THREAD

**Issue by Eilons** [deeplearning4j/deeplearning4j#1606]
Errors obtained while using the following commands:
File gModel = new File ("D:/Technion/Thesis/GoogleNews-vectors-negative300.bin.gz");
Word2Vec vec = (Word2Vec) org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadGoogleModel(gModel, true);
System.out.println(vec.similarity("people", "money"));

Exception in thread "main" java.lang.NullPointerException: This pointer address is NULL.
at org.bytedeco.javacpp.FloatPointer.put(Native Method)
at org.bytedeco.javacpp.FloatPointer.put(FloatPointer.java:110)
at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:42)
at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:237)
at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:120)
at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:328)
at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:282)
at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1179)
at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1914)
at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2763)
at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2587)
at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readBinaryModel(WordVectorSerializer.java:235)
at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadGoogleModel(WordVectorSerializer.java:115)
at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadGoogleModel(WordVectorSerializer.java:95)
at main.word2VecExample.main(word2VecExample.java:36)

Using 8G ram machine java 7 core i5 4200
When I switched to a 12Gram machine everything works fine

**Comment by saudet** [comment]
Are you using the latest version of JavaCPP? This problem shouldn't happen with this change: https://github.com/bytedeco/javacpp/commit/587f9e836d547f4d7ea72306a7846fd7cfd888bc

**Comment by Eilons** [comment]
I'm working with Eclipse.

my java version is:
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

**Comment by eraly** [comment]
@Eilons If you are installing from source which version of java cpp did you use? If not, your pom will tell you in mvn. 
https://github.com/bytedeco/javacpp

**Comment by raver119** [comment]
are you using gradle by any chance? We've saw similar issue in gitter few days ago, issue was caused by improper Nd4j initialization

**Comment by eraly** [comment]
@Eilons Will you file a new issue if you are still having problem? Thanks!

**Comment by Eilons** [comment]
@raver119 I'm not using gradle
@eraly sure! (there is no java cpp in my pom)

**Comment by saudet** [comment]
@Eilons The newer version of JavaCPP is pulled in by default with 0.4-rc3.10 so you should be getting a different error message now
