### ISSUE TITLE
Hitting a NPE when running MultiLayerTest.testDbnFaces()

### ISSUE THREAD

**Issue by smarthi** [deeplearning4j/deeplearning4j#162]
testDbnFaces(org.deeplearning4j.nn.multilayer.MultiLayerTest)  Time elapsed: 300.475 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.deeplearning4j.plot.NeuralNetPlotter.histogram(NeuralNetPlotter.java:179)
	at org.deeplearning4j.plot.NeuralNetPlotter.plotNetworkGradient(NeuralNetPlotter.java:103)
	at org.deeplearning4j.plot.iterationlistener.NeuralNetPlotterIterationListener.iterationDone(NeuralNetPlotterIterationListener.java:67)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:180)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:25)
	at org.deeplearning4j.nn.layers.OutputLayer.fit(OutputLayer.java:225)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.finetune(MultiLayerNetwork.java:1109)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1160)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1199)
	at org.deeplearning4j.nn.multilayer.MultiLayerTest.testDbnFaces(MultiLayerTest.java:70)

**Comment by agibsonccc** [comment]
Fixed.
