### ISSUE TITLE
Getting error if negative sampling is set during Word2Vec building

### ISSUE THREAD

**Issue by fmchowdhury** [deeplearning4j/deeplearning4j#1628]
Hi,

I am trying to build a Word2Vec using the following text - https://github.com/deeplearning4j/deeplearning4j/blob/master/dl4j-test-resources/src/main/resources/raw_sentences.txt

and following code -
`       InMemoryLookupCache cache = new InMemoryLookupCache();
        WeightLookupTable<VocabWord> table = new InMemoryLookupTable.Builder<VocabWord>()
                .vectorLength(100)
                .useAdaGrad(false)
                .cache(cache)
                .lr(0.025f).build();
        
        log.info("Building model....");
        Word2Vec vec = new Word2Vec.Builder()
	        .batchSize(1000)
	        .minWordFrequency(5)
	        .iterations(3)
	        .epochs(1)
	        .layerSize(100) 
	        .seed(42)
	        .windowSize(5)
	        .iterate(iter)
	        .tokenizerFactory(t)
	        .minLearningRate(1e-3) 
	        .negativeSample(10) 
	        .lookupTable(table)
	        .vocabCache(cache)
	        .build();`

If don't set negativeSample (i.e. comment it out), it works fine. But when I try to set it, I get the following errors.

Is there something I am doing wrong or is it a bug?

_o.d.m.s.SequenceVectors - Starting vocabulary building...
o.d.m.w.w.VocabConstructor - Sequences checked: [97162], Current vocabulary size: [236]
o.d.m.s.SequenceVectors - Building learning algorithms:
o.d.m.s.SequenceVectors -           building ElementsLearningAlgorithm: [SkipGram]
o.d.m.s.SequenceVectors - Starting learning process...
Exception in thread "VectorCalculationsThread 0" java.lang.RuntimeException: java.lang.NullPointerException
Exception in thread "VectorCalculationsThread 1" java.lang.RuntimeException: java.lang.NullPointerException
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:780)
Caused by: java.lang.NullPointerException
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:201)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:124)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:99)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:153)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:768)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:780)Exception in thread "VectorCalculationsThread 3" java.lang.RuntimeException: java.lang.NullPointerException
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:780)
Caused by: java.lang.NullPointerException
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:201)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:124)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:99)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:153)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:768)

Caused by: java.lang.NullPointerException
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:201)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:124)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:99)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:153)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:768)
Exception in thread "VectorCalculationsThread 2" java.lang.RuntimeException: java.lang.NullPointerException
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:780)
Caused by: java.lang.NullPointerException
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:201)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:124)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:99)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:153)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:768)

**Comment by raver119** [comment]
Please, use the most recent versions for dl4j/nd4j.

As of now rc3.9 is the most recent one, and the bug you're reporting is already fixed there.
