### ISSUE TITLE
UnsupportedOperationException: empty collection in Apache Spark

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#1631]
When using `SparkEarlyStoppingTrainer` and `SparkDl4jMultilayer` I'm getting consistent UOEs in Apache Spark. Reproducible repo is readily available, please DM me on Gitter for access.

### Stacktrace
```
17:02:50,743 INFO  ~ Processing updaters
17:02:57,418 WARN  ~ Early stopping training terminated due to exception at epoch 0, iteration 0
java.lang.UnsupportedOperationException: empty collection
	at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1344)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.first(RDD.scala:1341)
	at org.apache.spark.api.java.JavaRDDLike$class.first(JavaRDDLike.scala:495)
	at org.apache.spark.api.java.AbstractJavaRDDLike.first(JavaRDDLike.scala:46)
	at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.runIteration(SparkDl4jMultiLayer.java:413)
	at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.fitDataSet(SparkDl4jMultiLayer.java:341)
	at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.fitDataSet(SparkDl4jMultiLayer.java:316)
	at org.deeplearning4j.spark.earlystopping.SparkEarlyStoppingTrainer.fit(SparkEarlyStoppingTrainer.java:78)
	at org.deeplearning4j.spark.earlystopping.BaseSparkEarlyStoppingTrainer.fit(BaseSparkEarlyStoppingTrainer.java:163)
	at ai.bernie.researchtests.TrainNetSpark$.main(TrainNetSpark.scala:131)
	at ai.bernie.researchtests.TrainNetSpark.main(TrainNetSpark.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Exception in thread "main" java.lang.NullPointerException
	at ai.bernie.researchtests.TrainNetSpark$.main(TrainNetSpark.scala:133)
	at ai.bernie.researchtests.TrainNetSpark.main(TrainNetSpark.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

### Cut-and-paste implementation
```
    // create spark context
    val sparkConf = new SparkConf()
    sparkConf.setAppName("CNNTEST")
    sparkConf.set(SparkDl4jMultiLayer.AVERAGE_EACH_ITERATION, String.valueOf(false))
    sparkConf.set(SparkDl4jMultiLayer.ACCUM_GRADIENT, String.valueOf(true))
    sparkConf.set(SparkDl4jMultiLayer.DIVIDE_ACCUM_GRADIENT, String.valueOf(false))
    val sc = new JavaSparkContext(sparkConf)

    // neural network parameters
    val imageWidth = 100
    val imageHeight = 100
    val nChannels = 3
    val outputNum = 8 // number of labels
//    val numSamples = 9383 // total samples
    val numSamples = 768
    val batchSize = 96
    val iterations = 4
    val splitTrainNum = (batchSize*.8).toInt
    val seed = 123
    val listenerFreq = 1

    // load datasets

    // training dataset
    println("Load training data...")

    val trainRecordReader = new ImageRecordReader(imageWidth, imageHeight, nChannels, true)
    try {
      trainRecordReader.initialize(new LimitFileSplit(new java.io.File("/home/ubuntu/cnn_dataset"), BaseImageLoader.ALLOWED_FORMATS, numSamples, outputNum, null, new Random(123)))
    } catch {
      case ioe: IOException => ioe.printStackTrace()
      case e: InterruptedException => e.printStackTrace()
    }

//    val trainingSetIterator: DataSetIterator = new RecordReaderDataSetIterator(trainRecordReader, batchSize, imageWidth*imageHeight*nChannels, outputNum)
    val trainingSetIterator: DataSetIterator = new RecordReaderDataSetIterator(trainRecordReader, batchSize, -1, outputNum)

    // parallelize the dataset
    val list = new util.ArrayList[DataSet](numSamples)
    while(trainingSetIterator.hasNext) list.add(trainingSetIterator.next)
    println("Dataset is "+list.size()+" records long.")
    val trainRDD = sc.parallelize(list)


    // perform training

    // configure the early stopping trainer
    val earlyStoppingListener: LoggingEarlyStoppingListener = new LoggingEarlyStoppingListener()

    val esConf = new EarlyStoppingConfiguration.Builder()
      .epochTerminationConditions(new MaxEpochsTerminationCondition(30))
      .epochTerminationConditions(new ScoreImprovementEpochTerminationCondition(2))
      .scoreCalculator(new SparkDataSetLossCalculator(trainRDD, true, sc))
      .evaluateEveryNEpochs(1)
      .modelSaver(new InMemoryModelSaver())
      .build()

//    val nn = new MultiLayerNetwork(CNN.alexNetConf(seed, iterations, nChannels, outputNum, imageWidth, imageHeight))
//    nn.setListeners(new HistogramIterationListener(1))
    val nn = CNN.tinyNetConf(seed, iterations, nChannels, outputNum, imageWidth, imageHeight)
    nn.setListeners(Collections.singletonList(new ScoreIterationListener(listenerFreq).asInstanceOf[IterationListener]))

    val trainer: SparkEarlyStoppingTrainer = new SparkEarlyStoppingTrainer(sc, esConf, nn, trainRDD, 10, numSamples, 6, earlyStoppingListener)

    val result = trainer.fit
    val bestModel: MultiLayerNetwork = result.getBestModel
    println("Score of best model is: "+bestModel.score().toString())
```

**Comment by crockpotveggies** [comment]
In what I imagine is related to this very same error, when I set `ACCUM_GRADIENTS` to `false`, the results aggregator throws an NPE:

```
17:24:54,540 WARN  ~ Layer "Layer cnn1" momentum has been set but will not be applied unless the updater is set to NESTEROVS.
17:24:54,541 WARN  ~ Layer "Layer pool1" momentum has been set but will not be applied unless the updater is set to NESTEROVS.
17:24:54,541 WARN  ~ Layer "Layer not named" momentum has been set but will not be applied unless the updater is set to NESTEROVS.
17:24:54,541 WARN  ~ Layer "Layer cnn2" momentum has been set but will not be applied unless the updater is set to NESTEROVS.
17:24:54,541 WARN  ~ Layer "Layer pool2" momentum has been set but will not be applied unless the updater is set to NESTEROVS.
17:24:54,541 WARN  ~ Layer "Layer not named" momentum has been set but will not be applied unless the updater is set to NESTEROVS.
17:24:54,541 WARN  ~ Layer "Layer cnn3" momentum has been set but will not be applied unless the updater is set to NESTEROVS.
17:24:54,541 WARN  ~ Layer "Layer pool3" momentum has been set but will not be applied unless the updater is set to NESTEROVS.
17:24:54,541 WARN  ~ Layer "Layer ffn1" momentum has been set but will not be applied unless the updater is set to NESTEROVS.
17:24:54,541 WARN  ~ Layer "Layer not named" momentum has been set but will not be applied unless the updater is set to NESTEROVS.
17:24:55,172 INFO  ~ Starting early stopping training
17:24:55,332 INFO  ~ Initiating distributed training of subset 1 of 77
17:24:55,332 INFO  ~ Running distributed training:  (averaging each iteration = false), (iterations = 4), (num partions = 6)
17:24:55,332 INFO  ~ Broadcasting initial parameters of length 2017586
17:24:56,065 INFO  ~ Running iterative reduce and averaging parameters
17:25:11,897 INFO  ~ Accumulated and set parameters
17:25:24,651 WARN  ~ Early stopping training terminated due to exception at epoch 0, iteration 0
java.lang.NullPointerException
	at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.runIteration(SparkDl4jMultiLayer.java:453)
	at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.fitDataSet(SparkDl4jMultiLayer.java:341)
	at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.fitDataSet(SparkDl4jMultiLayer.java:316)
	at org.deeplearning4j.spark.earlystopping.SparkEarlyStoppingTrainer.fit(SparkEarlyStoppingTrainer.java:78)
	at org.deeplearning4j.spark.earlystopping.BaseSparkEarlyStoppingTrainer.fit(BaseSparkEarlyStoppingTrainer.java:163)
	at ai.bernie.researchtests.TrainNetSpark$.main(TrainNetSpark.scala:131)
	at ai.bernie.researchtests.TrainNetSpark.main(TrainNetSpark.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Exception in thread "main" java.lang.NullPointerException
	at ai.bernie.researchtests.TrainNetSpark$.main(TrainNetSpark.scala:133)
	at ai.bernie.researchtests.TrainNetSpark.main(TrainNetSpark.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by agibsonccc** [comment]
I fixed the null pointers already with a warning. Closing this.
