### ISSUE TITLE
Cannot use gpu with aws ami

### ISSUE THREAD

**Issue by davireis** [deeplearning4j/deeplearning4j#1649]
Hi,

I am trying to use gpu with 3.9, and so far I did not find a workable setup. Here is what I did so far.

First, get a gpu enabled ami in amazon. I took this one: https://aws.amazon.com/marketplace/ordering?productId=df03e1dc-d2b3-40ae-b975-c223a29ce7c8&ref_=dtl_psb_continue&region=us-east-1. I checked that deviceQuery, nvidia-smi and tensorflow are working fine.

```
docker-machine create --driver amazonec2 --amazonec2-region=us-east-1 --amazonec2-zone=a --amazonec2-root-size=64 --amazonec2-request-spot-instance --amazonec2-instance-type=g2.2xlarge --amazonec2-spot-price=0.5 --amazonec2-ami ami-0ecc2463 gpu0
docker-machine ssh gpu0
```

Notice that I am using docker for convenience, and I am not inside the container, hence docker headaches do not apply here, afaik.

Then I used scala shell to run a few lines of nd4j code, passing only the jars for the cuda backend, no native backend. First I installed it:

```
export PATH=$PATH:/usr/local/cuda/bin/  # nd4j wants to see nvcc in path
wget www.scala-lang.org/files/archive/scala-2.11.7.deb
sudo dpkg -i scala-2.11.7.deb
````

And then I tried to run the code:

```
# Minimum set of dependencies for nd4j
scala -cp annotations-2.0.1.jar:commons-io-2.4.jar:commons-lang3-3.3.1.jar:commons-math3-3.4.1.jar:commons-pool2-2.4.2.jar:guava-18.0.jar:javacpp-1.2.jar:javassist-3.19.0-GA.jar:lombok-1.16.4.jar:nd4j-api-0.4-rc3.9.jar:nd4j-buffer-0.4-rc3.9.jar:nd4j-common-0.4-rc3.9.jar:nd4j-context-0.4-rc3.9.jar:nd4j-cuda-7.5-0.4-rc3.9.jar:nd4j-cuda-7.5-0.4-rc3.9-linux-x86_64.jar:nd4j-native-api-0.4-rc3.9.jar:netty-buffer-4.0.28.Final.jar:netty-common-4.0.28.Final.jar:reflections-0.9.10.jar:slf4j-api-1.7.10.jar
````

Then run

```
val a = Array(Nd4j.create(Array(1.0)), Nd4j.create(Array(2.0)))
val b = Array(Nd4j.create(Array(2.0)), Nd4j.create(Array(3.0)))
Nd4j.concat(1, a: _*)
Nd4j.concat(1, b: _*)
```

And you get (sometimes in the first, sometimes in the second concat):

````
CUDA error at /skymind/libnd4j/blas/cuda/NativeOps.cu:4149 code=77(<unknown>) "result"
Failed on [140297393929072] -> [8608812544], size: [4], direction: [0]
java.lang.IllegalStateException: MemcpyAsync failed
  at org.nd4j.jita.handler.impl.CudaZeroHandler.memcpyAsync(CudaZeroHandler.java:531)
  at org.nd4j.jita.allocator.impl.AtomicAllocator.memcpyAsync(AtomicAllocator.java:770)
  at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.set(BaseCudaDataBuffer.java:318)
  at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:102)
  at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:68)
  at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:151)
  at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1058)
  at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:347)
  at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:587)
  at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:286)
  at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:306)
  at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1338)
  at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2855)
  at org.nd4j.linalg.factory.BaseNDArrayFactory.valueArrayOf(BaseNDArrayFactory.java:925)
  at org.nd4j.linalg.factory.Nd4j.valueArrayOf(Nd4j.java:4209)
  at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.exec(JCudaExecutioner.java:192)
  at org.nd4j.linalg.api.ndarray.BaseNDArray.max(BaseNDArray.java:3435)
  at org.nd4j.linalg.api.ndarray.BaseNDArray.maxNumber(BaseNDArray.java:1021)
  at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:35)
  at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:4324)
  at org.nd4j.linalg.jcublas.JCublasNDArray.toString(JCublasNDArray.java:394)
  at scala.runtime.ScalaRunTime$.scala$runtime$ScalaRunTime$$inner$1(ScalaRunTime.scala:332)
  at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:337)
  at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:345)
  at .$print$lzycompute(<console>:10)
  at .$print(<console>:6)
  at $print(<console>)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:784)
  at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1039)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:636)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:635)
  at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
  at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:635)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:567)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:563)
  at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:802)
  at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:836)
  at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:694)
  at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:404)
  at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:424)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:925)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:911)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:911)
  at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
  at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:911)
  at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
  at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
  at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
  at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
  at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by davireis** [comment]
I have tested different amis and different driver versions, and they all give me the same failure. I would be happy to test in a known-to-work setup.

**Comment by treo** [comment]
This looks pretty much like a known bug in the rc3.9 release. You could either try building from source, or wait until the next release that is supposed to be coming very soon.

**Comment by raver119** [comment]
Unfortunately @treo is right, gpu concat is an issue for rc3.9, and is arleady fixed.

Also, right now next release is getting baked, so it should be available later today. This release brings few bug fixes and performance improvements for both cpu and gpu.
