### ISSUE TITLE
ModelSerializer.restore: OutOfMemory Exception although Network can be trained etc.

### ISSUE THREAD

**Issue by OliverScheel** [deeplearning4j/deeplearning4j#1683]
Hello, I create a CNN for images of sizes 500 x 10 x 3. 
My network configuration is: 

  MultiLayerConfiguration.Builder builder = new NeuralNetConfiguration.Builder().seed(seed).iterations(iterations)
	            .regularization(true).l2(0.0005).learningRate(0.001)// .biasLearningRate(0.02)
	            // .learningRateDecayPolicy(LearningRatePolicy.Inverse).lrPolicyDecayRate(0.001).lrPolicyPower(0.75)
	            .weightInit(WeightInit.XAVIER).optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
	            .updater(Updater.NESTEROVS).momentum(0.9).list()
	            .layer(0,
	                new ConvolutionLayer.Builder(5, 2).nIn(nChannels).stride(1, 1).nOut(20).activation("identity")
	                    .build())
	            .layer(1,
	                new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.MAX).kernelSize(2, 1).stride(2, 1)
	                    .build())
	            .layer(2,
	                new ConvolutionLayer.Builder(5, 1).nIn(nChannels).stride(1, 1).nOut(50).activation("identity")
	                    .build())
	            .layer(3,
	                new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.MAX).kernelSize(2, 1).stride(2, 1)
	                    .build())
	            .layer(4, new DenseLayer.Builder().activation("relu").nOut(500).build())
	            .layer(5, new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD).nOut(outputNum)
	                .activation("softmax").build())
	            .backprop(true).pretrain(false);
	        new ConvolutionLayerSetup(builder, width, height, channels);

I can successfully train the network. Now I want to store and save the network. For this I call 
ModelSerializer.writeModel(model, file, true); This works.
But then I try MultiLayerNetwork network = ModelSerializer.restoreMultiLayerNetwork(file);, here I get an outofmemory exception (https://gist.github.com/OliverScheel/0b04f7054bb2161680ef29f41b119610).
I am using Windows 7 64 bit with like 8 GB Ram, I changed the heapspace of my JVM to 2 GB.

**Comment by raver119** [comment]
According to that exception, you're somewhere around 1GB limit. Can i have your model? :)

**Comment by OliverScheel** [comment]
What do u mean? :) Isnt the network code above enough?

**Comment by raver119** [comment]
No, it's not. I want to check restoration process, to check if there's bug, or it's really something wrong with memory on your side.

**Comment by OliverScheel** [comment]
Ok sorry but i dont understand. what do u want? the model file i exported?

**Comment by raver119** [comment]
Yes, exactly exported file.

**Comment by AlexDBlack** [comment]
@raver119 we should be able to reproduce it with just the config, I think
Doesn't really matter what is actually *in* the parameters (in terms of specific values)

**Comment by OliverScheel** [comment]
ok is it ok? i cant upload the file here

**Comment by raver119** [comment]
I just want to be sure there's nothing bad happened during model serialization as well.
Since number of params is small enough, sharing 1 zip file isn't a big deal :)

**Comment by AlexDBlack** [comment]
sure, fair enough :)

**Comment by OliverScheel** [comment]
it doenst compress. so im uploading it somewhere else, hang on

**Comment by OliverScheel** [comment]
here you go, pw is cnn: http://www.megafileupload.com/b9fn/model.zip

**Comment by raver119** [comment]
So, apparently -Xmx768M and -Xmx1G is enough to restore model, and -Xmx512M is NOT enough.

Here's my stack trace for that:

```
Exception in thread "main" java.lang.OutOfMemoryError: Cannot allocate 439292974 + 109800000 bytes (> Pointer.maxBytes)
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:446)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:118)
	at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:556)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:45)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:237)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1159)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1153)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:227)
	at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:107)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:241)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4032)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.toFlattened(CpuNDArrayFactory.java:496)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.toFlattened(BaseNDArrayFactory.java:318)
	at org.nd4j.linalg.factory.Nd4j.toFlattened(Nd4j.java:1650)
	at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:126)
	at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:82)
	at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:144)
	at org.deeplearning4j.nn.params.DefaultParamInitializer.createWeightMatrix(DefaultParamInitializer.java:109)
	at org.deeplearning4j.nn.params.DefaultParamInitializer.init(DefaultParamInitializer.java:70)
	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.getParams(DefaultLayerFactory.java:98)
	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.create(DefaultLayerFactory.java:57)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:385)
	at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:163)
	at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:175)
	at org.deeplearning4j.examples.unsupervised.deepbelief.Test.main(Test.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by raver119** [comment]
This issue is going to be addressed with this change: https://github.com/deeplearning4j/deeplearning4j/issues/1684

**Comment by AlexDBlack** [comment]
Turns out this was due to xmx not being set properly.
