### ISSUE TITLE
Unable to get linear index >= 1 - after upgrading to 0.4-rc3.10

### ISSUE THREAD

**Issue by Alex-Cosma** [deeplearning4j/deeplearning4j#1685]
I have modified the basic Xor example a little bit such that it has only one output neuron instead of two.

```
 INDArray labels = Nd4j.zeros(4, 1);

        input.putScalar(new int[] { 0, 0 }, 0);
        input.putScalar(new int[] { 0, 1 }, 0);
        labels.putScalar(new int[] { 0, 0 }, 1);

        input.putScalar(new int[] { 1, 0 }, 1);
        input.putScalar(new int[] { 1, 1 }, 0);
        labels.putScalar(new int[] { 1, 0 }, 1);

        input.putScalar(new int[] { 2, 0 }, 0);
        input.putScalar(new int[] { 2, 1 }, 1);
        labels.putScalar(new int[] { 2, 0 }, 1);

        input.putScalar(new int[] { 3, 0 }, 1);
        input.putScalar(new int[] { 3, 1 }, 1);
        labels.putScalar(new int[] { 3, 0 }, 0);
```

for input and of course, modified the output layer to

```
        outputLayerBuilder.nOut(1);
```

Now the following code:
```
        Evaluation eval = new Evaluation(2);
        eval.eval(ds.getLabels(), output);
        System.out.println(eval.stats());
```

gives this error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unable to get linear index >= 1
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3248)
	at org.deeplearning4j.eval.Evaluation.eval(Evaluation.java:140)
	at org.deeplearning4j.examples.experiments.Xor.main(Xor.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

`(Xor.java:167)`  =  `eval.eval(ds.getLabels(), output);`

And I have no idea why.

Note, I have just now upgraded to `0.4-rc3.10` (basically copied the whole `.pom` file from [here](https://github.com/deeplearning4j/dl4j-0.4-examples) into my project) and before I did this, I was using the `0.4-rc3.8` version and this error did not occur!

Why is it so? 
Many thanks!

**Comment by agibsonccc** [comment]
Nout on the output layer has to be equal to the number of labels for evaluation.

**Comment by Alex-Cosma** [comment]
Why?

**Comment by agibsonccc** [comment]
Please come on gitter for clarifying questions thanks.
