### ISSUE TITLE
DataSetIerator.next() crashes when there is only 1 element in folder

### ISSUE THREAD

**Issue by OliverScheel** [deeplearning4j/deeplearning4j#1695]
I use:

						File parentDir = new File("\\RunCNN");
						FileSplit filesInDir = new FileSplit(parentDir, allowedExtensions, randNumGen);
						ParentPathLabelGenerator labelMaker = new ParentPathLabelGenerator();
						BalancedPathFilter pathFilter = new BalancedPathFilter(randNumGen, allowedExtensions,
								labelMaker);
						InputSplit[] filesInDirSplit = filesInDir.sample(pathFilter, 100, 0);
						InputSplit trainData = filesInDirSplit[0];
						InputSplit testData = filesInDirSplit[1];

						ImageRecordReader recordReader = new ImageRecordReader(y, x, 3, labelMaker);

						try {
							recordReader.initialize(trainData);
						} catch (IOException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
						DataSetIterator dataIter = new RecordReaderDataSetIterator(recordReader, 1, -1, 40);

						SimplePreProcessor SP = new SimplePreProcessor();
						dataIter.setPreProcessor(SP);

						boolean GivesTrue = dataIter.hasNext();
						DataSet testMnist = dataIter.next();

In the folder RunCNN there is only one element, then dataIter.next() crashes with the following stacktrace: 

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at org.nd4j.linalg.util.FeatureUtil.toOutcomeVector(FeatureUtil.java:38)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.getDataSet(RecordReaderDataSetIterator.java:241)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:170)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:337)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:47)
	at CNNTrainer.Schedule(CNNTrainer.java:121)
	at CNNTrainer.CreateExamples(CNNTrainer.java:155)
	at Main.main(Main.java:475)

With more elements in the folder it works.

**Comment by saudet** [comment]
I can't reproduce it with the latest code from the master branches. Looks like https://github.com/deeplearning4j/nd4j/pull/1022 fixes this. Could you please confirm?

**Comment by saudet** [comment]
Actually, this is unrelated to nd4j and I was able to reproduce this issue. I had other code interfering. This should fix it: https://github.com/deeplearning4j/Canova/pull/212
