### ISSUE TITLE
exception to load pre-trained GloVe 

### ISSUE THREAD

**Issue by kamol** [deeplearning4j/deeplearning4j#1714]
Hi,
I tried to load a pre-trained GloVe by simply using the folowing code:
WordVectors wv = WordVectorSerializer.loadTxtVectors(new File("glove.6B.50d.txt"));
unfortunately it got exception: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 49
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadTxt(WordVectorSerializer.java:1107)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadTxtVectors(WordVectorSerializer.java:1033)
If I use other models for example, glove.6B.100d.txt, glove.6B.200d.txt it got same exception at java.lang.ArrayIndexOutOfBoundsException: 99, java.lang.ArrayIndexOutOfBoundsException: 199

**Comment by raver119** [comment]
Yes, this is a bug. It's already fixed on current master. As workaround you can copy those methods (or entire class) to your project and use them instead.

Sorry for inconveniences.
