### ISSUE TITLE
word2vec ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ThxForUrHelp** [deeplearning4j/deeplearning4j#1721]
I trained the word2vec model from http://deeplearning4j.org/word2vec successfully and now get this exception when trying to apply the wordsNearest:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 99
at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadTxt(WordVectorSerializer.java:1107)
at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadTxtVectors(WordVectorSerializer.java:1033)
at org.deeplearning4j.examples.nlp.word2vec.NearestWords.main(NearestWords.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Code:
[NearestWords.txt](https://github.com/deeplearning4j/deeplearning4j/files/322439/NearestWords.txt)

**Comment by raver119** [comment]
Yes, this is a bug. It's already fixed on current master. As workaround you can copy those methods (or entire class) to your project and use them instead.

Sorry for inconveniences.

**Comment by ThxForUrHelp** [comment]
Thanks! I tried to do so, but I really despair. I am a real beginner and would appreciate your help.
I included the snapshots (like explained here http://deeplearning4j.org/snapshot) but this is not working at all. 
Is this the right link to current master? https://github.com/deeplearning4j/deeplearning4j

**Comment by raver119** [comment]
All you need is just copy-paste methods from sources: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/loader/WordVectorSerializer.java

**Comment by ThxForUrHelp** [comment]
But where do I paste the methods? Do I have to create a jar file? Because the path of the error class is leading to a jar file.

**Comment by raver119** [comment]
Paste them in your project, like you've wrote your own method loadTxtVectors()

**Comment by ThxForUrHelp** [comment]
Alright, now I get this:
`Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadTxt(WordVectorSerializer.java:1091)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadTxtVectors(WordVectorSerializer.java:1014)
	at org.deeplearning4j.examples.nlp.word2vec.NearestWords.main(NearestWords.java:12)`

**Comment by raver119** [comment]
I'm sorry, i don't know how exactly you've managed to get that error, since i've told you to copy 1 method in your project, and use that method to load vector :(

**Comment by ThxForUrHelp** [comment]
Yes, thats because I did everything but just copying the method... But I found my error and now it's working and I can't tell how thankful I am for your help! Really you made my day, thanks for your great work. And your response time is insane :O Best regards

**Comment by arunwizz** [comment]
Hi @raver119 , in which version this fix will be available in maven central?

**Comment by raver119** [comment]
Next one. Shouldn't take long till next release.
