### ISSUE TITLE
Word2VecUptrainingExample gives JsonMappingException when trying to update the model

### ISSUE THREAD

**Issue by AmsterdamJK** [deeplearning4j/deeplearning4j#1738]
When running the Word2VecUptrainingExample, everything goes well until the example code tries to reload the model to update the weights. A JsonMappingException is returned (see stack trace below). At first I thought it was caused by me running the examples on Eclipse, but I get the same exception in IntelliJ. I have just setup dl4J, so I have changed nothing in the example code. I'm using OS X 10.11.5, dl4j & nd4j version 0.4-rc3.10 and canova version 0.0.0.16. 

Thanks in advance!

Stack trace:

o.d.e.n.w.Word2VecRawTextExample - Load & Vectorize Sentences....
o.d.e.n.w.Word2VecRawTextExample - Building model....
o.d.e.n.w.Word2VecRawTextExample - Fitting Word2Vec model....
o.d.m.s.SequenceVectors - Starting vocabulary building...
o.d.m.w.w.VocabConstructor - Sequences checked: [97162], Current vocabulary size: [242]
o.d.m.s.SequenceVectors - Building learning algorithms:
o.d.m.s.SequenceVectors -           building ElementsLearningAlgorithm: [SkipGram]
o.d.m.s.SequenceVectors - Starting learning process...
o.d.m.s.SequenceVectors - Epoch: [1]; Words vectorized so far: [634303];  Lines vectorized so far: [97162]; learningRate: [1.0E-4]
o.d.e.n.w.Word2VecRawTextExample - Closest words to 'day' on 1st run: [night, week, year, game, season, time, office, group, street, second]
o.d.m.e.l.WordVectorSerializer - Word2Vec conf. JSON: 0.0024726231566347748 0.0024729191554214817 0.0024732151895544793 0.002473511259037965 0.00247380736387614 0.0024741035040732077 0.0024743996796333643 
> (... JSON shortened to keep body under 65536 characters)

Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class org.deeplearning4j.models.embeddings.loader.VectorsConfiguration] from Floating-point number (0.0024726231566347748); no one-double/Double-arg constructor/factory method
 at [Source: java.io.StringReader@6c372fe6; line: 1, column: 1]
	at org.deeplearning4j.models.embeddings.loader.VectorsConfiguration.fromJson(VectorsConfiguration.java:96)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadFullModel(WordVectorSerializer.java:787)
	at org.deeplearning4j.examples.nlp.word2vec.Word2VecUptrainingExample.main(Word2VecUptrainingExample.java:86)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class org.deeplearning4j.models.embeddings.loader.VectorsConfiguration] from Floating-point number (0.0024726231566347748); no one-double/Double-arg constructor/factory method
 at [Source: java.io.StringReader@6c372fe6; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:843)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromDouble(StdValueInstantiator.java:336)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromDouble(BeanDeserializerBase.java:1172)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:157)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:144)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at org.deeplearning4j.models.embeddings.loader.VectorsConfiguration.fromJson(VectorsConfiguration.java:93)
	... 2 more

**Comment by raver119** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/1703
