### ISSUE TITLE
MultiLayerNetwork.java labelProbabilities not working

### ISSUE THREAD

**Issue by gmachine1** [deeplearning4j/deeplearning4j#1752]
I am doing image classification with deeplearning4j. Everything worked including output(INDArray) but when I run labelProbabilities I get:

java.lang.NullPointerException
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.getInputMiniBatchSize(MultiLayerNetwork.java:2141)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:700)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.labelProbabilities(MultiLayerNetwork.java:1464)

I am using
"org.nd4j" % "nd4j-x86" % "0.4-rc3.8",
  "org.nd4j" % "nd4s_2.11" % "0.4-rc3.8",
  "org.deeplearning4j" % "deeplearning4j-core" % "0.4-rc3.8",

Do you have any idea what could be causing this?

Thanks!

**Comment by agibsonccc** [comment]
Upgrade to the latest example versions:
https://github.com/deeplearning4j/dl4j-0.4-examples
