### ISSUE TITLE
ArrayIndexOutOfBoundsException: ConvolutionDownSampleLayerTest.testMultiLayer

### ISSUE THREAD

**Issue by smarthi** [deeplearning4j/deeplearning4j#176]
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.053 sec <<< FAILURE! - in org.deeplearning4j.models.layers.ConvolutionDownSampleLayerTest
testMultiLayer(org.deeplearning4j.models.layers.ConvolutionDownSampleLayerTest)  Time elapsed: 0.049 sec  <<< ERROR!
java.lang.ArrayIndexOutOfBoundsException: 18
	at org.nd4j.linalg.api.buffer.FloatBuffer.put(FloatBuffer.java:158)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.put(BaseDataBuffer.java:222)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.apply(BaseDataBuffer.java:208)
	at org.nd4j.linalg.ops.BaseElementWiseOp.exec(BaseElementWiseOp.java:122)
	at org.nd4j.linalg.ops.transforms.Transforms.exec(Transforms.java:748)
	at org.nd4j.linalg.ops.transforms.Transforms.exp(Transforms.java:622)
	at org.nd4j.linalg.ops.transforms.Transforms.exp(Transforms.java:370)
	at org.nd4j.linalg.fft.VectorFFT.apply(VectorFFT.java:75)
	at org.nd4j.linalg.fft.FFTSliceOp.operate(FFTSliceOp.java:60)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.iterateOverAllRows(BaseNDArray.java:1626)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.iterateOverAllRows(BaseNDArray.java:1630)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.iterateOverAllRows(BaseNDArray.java:1630)
	at org.nd4j.linalg.fft.DefaultFFTInstance.rawfft(DefaultFFTInstance.java:167)
	at org.nd4j.linalg.fft.DefaultFFTInstance.fft(DefaultFFTInstance.java:63)
	at org.nd4j.linalg.fft.BaseFFTInstance.rawfftn(BaseFFTInstance.java:271)
	at org.nd4j.linalg.fft.FFT.rawfftn(FFT.java:273)
	at org.nd4j.linalg.convolution.DefaultConvolutionInstance.convn(DefaultConvolutionInstance.java:86)
	at org.nd4j.linalg.convolution.BaseConvolution.conv2d(BaseConvolution.java:41)
	at org.nd4j.linalg.convolution.Convolution.conv2d(Convolution.java:52)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionDownSampleLayer.activate(ConvolutionDownSampleLayer.java:57)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:211)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:453)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:475)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.finetune(MultiLayerNetwork.java:1097)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1148)
	at org.deeplearning4j.models.layers.ConvolutionDownSampleLayerTest.testMultiLayer(ConvolutionDownSampleLayerTest.java:114)

**Comment by agibsonccc** [comment]
Fixed. This was an nd4j bug with the new architecture. Tested on CUDA and Native.
