### ISSUE TITLE
ModelSerializer.restoreMultiLayerNetwork java.io.EOFException

### ISSUE THREAD

**Issue by amoellmann** [deeplearning4j/deeplearning4j#1832]
```
import java.nio.file.Files;
// ...
Path modelFile
ModelSerializer.restoreMultiLayerNetwork(Files.newInputStream(modelFile));
```

ends up in an exception

```
Exception in thread "main" java.lang.RuntimeException: java.io.EOFException
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.read(BaseDataBuffer.java:1255)
	at org.nd4j.linalg.factory.Nd4j.read(Nd4j.java:2191)
	at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:252)
	at org.deeplearning4j.examples.convolution.LenetMnistExample.<init>(LenetMnistExample.java:64)
	at org.deeplearning4j.examples.convolution.LenetMnistExample.main(LenetMnistExample.java:44)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readUTF(DataInputStream.java:609)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
at org.nd4j.linalg.api.buffer.BaseDataBuffer.read(BaseDataBuffer.java:1226)
```

**Comment by raver119** [comment]
Fixed: https://github.com/deeplearning4j/deeplearning4j/pull/1828

As temporary workaround - please use File instead of InputStream
