### ISSUE TITLE
Illegal index errors when loading word2Vectors using GoogleNews-vectors

### ISSUE THREAD

**Issue by zaemyung** [deeplearning4j/deeplearning4j#185]
Hi,

After playing around with the word2vec codes, I've found a few errors:

1)
The following codes in Word2VecTest.java that loads GoogleNews model,

public class Word2VecGoogleTest {
	private static Logger log = LoggerFactory.getLogger(Word2VecGoogleTest.class);

	public static void main(String[] args) throws Exception {
		Nd4j.dtype = DataBuffer.FLOAT;
		log.debug("Loading google model...");
		//Nd4j.factory().setOrder(NDArrayFactory.C);
		final Word2Vec word2Vec = WordVectorSerializer.loadGoogleModel(
				"GoogleNews-vectors-negative300.bin", true);
		log.debug("Done.");
		System.out.println("vec for day: "+word2Vec.getWordVectorMatrixNormalized("day"));
		System.out.println("vec for days: "+word2Vec.getWordVectorMatrixNormalized("days"));
		System.out.println("vec for museum: "+word2Vec.getWordVectorMatrixNormalized("musuem"));
		System.out.println("vec for museums: "+word2Vec.getWordVectorMatrixNormalized("musuems"));
		System.out.println("vec for woman: "+word2Vec.getWordVectorMatrixNormalized("woman"));
		System.out.println("vec for man: "+word2Vec.getWordVectorMatrixNormalized("man"));

produces the following error:

Exception in thread "main" java.lang.IllegalStateException: Illegal index 3000113
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:2854)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.apply(DefaultOpExecutioner.java:214)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.apply(DefaultOpExecutioner.java:205)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:113)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:37)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.divi(BaseNDArray.java:912)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.divi(BaseNDArray.java:2723)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.div(BaseNDArray.java:2718)
	at org.deeplearning4j.models.embeddings.wordvectors.WordVectorsImpl.getWordVectorMatrixNormalized(WordVectorsImpl.java:248)
	at org.deeplearning4j.models.word2vec.Word2VecGoogleTest.main(Word2VecGoogleTest.java:24)

2)
After adding Nd4j.factory().setOrder(NDArrayFactory.C); before final Word2Vec word2Vec = WordVectorSerializer.loadGoogleModel(...), produces:

vec for day: [9.593289286767698E-42, 5.317787542266248E-41, 8.976717962464778E-41, 1.5152240294744247E-41, , ..., 2.598007352858211E-42, 6.214618559434131E-41, 5.497013615853392E-41]
 
vec for days: [1.3424439288231748E-42, 5.17443470936582E-41, 4.420816395251933E-41, 2.286498704238804E-41, , ..., 8.546379204070627E-41, 2.9501536569430374E-41, 5.156357959176029E-41]
 
vec for museum: [8.940984851624495E-41, 2.842674064729324E-41, 5.407470643983037E-41, 1.820146575311505E-41, , ..., 6.591287586644642E-41, 1.4793507887877094E-41, 4.690145960095163E-41]
 
Exception in thread "main" java.lang.IllegalArgumentException: Illegal index 1010205600 derived from 505102800 with offset of 505102800 and stride of 1
	at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:2569)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:2852)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.apply(DefaultOpExecutioner.java:214)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.apply(DefaultOpExecutioner.java:205)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:113)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:37)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.divi(BaseNDArray.java:912)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.divi(BaseNDArray.java:2723)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.div(BaseNDArray.java:2718)
	at org.deeplearning4j.models.embeddings.wordvectors.WordVectorsImpl.getWordVectorMatrixNormalized(WordVectorsImpl.java:248)
	at org.deeplearning4j.models.word2vec.Word2VecGoogleTest.main(Word2VecGoogleTest.java:27)

3)
The same codes appended with
System.out.println("\twords nearest " + "day" + ": " + word2Vec.wordsNearest("day", 10));
		System.out.println("\twords nearest " + "museum" + ": " + word2Vec.wordsNearest("museum", 10));
		System.out.println("\twords nearest " + "woman" + ": " + word2Vec.wordsNearest("woman", 10));

gives the following results:
words nearest day: [snowcapped_Caucasus, pulverizes_boulders, Mezze_Cafe, Bim_Skala_Bim, RAFFAELE, righthander_Kyle_Drabek, Thirsty_Owl, divider_pistons, Shilpa_Goenka, Mauri_Liberati, USA_TODAY_Reid_Cherner]
for every word.

Could you take a look into this please?

Thank you

**Comment by agibsonccc** [comment]
Would you mind trying with the latest changes? I did a lot of bug fixing in nd4j master today. I also pushed some changes related to the wordvectorserializer (mainly the downloading test issue) I'd love to see if this still persists.

Thanks!

**Comment by agibsonccc** [comment]
Closing this. Re open if you find more issues.
