### ISSUE TITLE
Help with CNN and word2vec

### ISSUE THREAD

**Issue by neosyon** [deeplearning4j/deeplearning4j#1850]
Hi all,
I'm trying to reproduce Yoon Kim work about CNN for sentence classification (https://github.com/yoonkim/CNN_sentence). However I'm getting this error :

Exception in thread "main" java.lang.IllegalStateException: Unable to get number of of columns for a non 2d matrix
    at org.nd4j.linalg.api.ndarray.BaseNDArray.columns(BaseNDArray.java:3547)
    at org.deeplearning4j.nn.conf.preprocessor.FeedForwardToCnnPreProcessor.preProcess(FeedForwardToCnnPreProcessor.java:83)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:520)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardToLayer(MultiLayerNetwork.java:644)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1722)
    at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:152)
    at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
    at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1023)
    at TestCNN.test.main(test.java:113)

"Unable to get number of of columns for a non 2d matrix" 

What I tried was to put the word2vec-based dataset of the Word2VecSentimentRNN.java example in the code of the MNISTimageClassification.java example.

Here you can find the code: https://gist.github.com/neosyon/1571d542c257e1289b4d1dcc0915704f

Can somedoby help me? Thanks!

**Comment by astier** [comment]
The problem with dl4j seems to be that the ConvNets in dl4j are implemented only for the purpose of classifying images which are usually 3 dimensionally height x width x depth (e.g. RGB). I solved it by artificially adding rows filled with zeros to simulate an 3rd dimension. For this you have to write your own DataSetIterator. You can study my example here:

https://gist.github.com/astier/f769cc58ae20915ac3f9f25b4a513653

**Comment by raver119** [comment]
@astier you're not required to have depth > 1. I.e. you may have it 1 (as grayscale image), or 3 (as rgb image) or whatever.

**Comment by astier** [comment]
@raver119 

Ok. You are maybe right that the depth don't have to be >1 but the filters have to be >1 (width and height) if I want to catch with a filter more than one word.

The problem I have if I use ConvNets for with word-vectors is the following: The kernelsize of a filter from a Conv-Layer must have the same height and width (like 3 x 3) otherwise I get an error:

`Exception in thread "main" java.lang.IllegalStateException: Column of left array 8700 != rows of right 3100 or rows of left array 20 != columns of right 3`

This leads to the following problem:
For example  the word-vectors (e.g. 50 dimensions) are aligned in the depth. The words are aligned in the width. If I want now to iterate over 4 words I have to build an filter 4 x 4. That means my matrix for a sentence have to be 4x4x50 (height width depth). The first row represent the sentence. The depth the word-vectors. The 3rd dimension (the other 3 rows) are filled with zeros since I only can iterate over 4 words if I have a filter 4x4. I would love to have a filter like 1x4 but its not possible in the moment.

An other suggestion would be to align the wordvectors not in the depth but instead in the height. Each column would be a wordvector. But for this I still would need filters like 50x4.

**Comment by saudet** [comment]
I think the question is about supporting 3D images. This would also be useful for volumetric data where voxels are used instead of pixels, as used for volume rendering of medical data, for example.

**Comment by agibsonccc** [comment]
We've added pooling over time now as  well.
