### ISSUE TITLE
getInputMiniBatchSize throws NullPointerException

### ISSUE THREAD

**Issue by japhar81** [deeplearning4j/deeplearning4j#1889]
Passing an INDArray to rnnTimeStep;
```INDArray testOutput = net.rnnTimeStep(testInput);```
throws;
```
Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.getInputMiniBatchSize(MultiLayerNetwork.java:2123)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:2154)
```

Adding a call to ```net.setInput(testInput)``` before ```rnnTimeStep``` seems to resolve this, but I'm told this is incorrect behavior.

**Comment by raver119** [comment]
issue is getInputMiniBatchSize() call, which refers to global input field. Which may be empty, in case of averaged model, or deserialized model.

**Comment by AlexDBlack** [comment]
Looks like I can't reproduce this. Can you give me more details?

For example, the following code works totally fine on 0.4.0:

```java
    public static void main(String[] args) throws Exception {

        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
            .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT).iterations(1)
            .list()
            .layer(0, new GravesLSTM.Builder().nIn(10).nOut(10).activation("tanh").build())
            .layer(1, new GravesLSTM.Builder().nIn(10).nOut(10).activation("tanh").build())
            .layer(2, new RnnOutputLayer.Builder(LossFunctions.LossFunction.MCXENT).activation("softmax").nIn(10).nOut(10).build())
            .pretrain(false).backprop(true)
            .build();

        MultiLayerNetwork net = new MultiLayerNetwork(conf);
        net.init();

        INDArray in = Nd4j.rand(1,10);
        net.rnnTimeStep(in);

        ModelSerializer.writeModel(net, new File("tempmodel.bin"), true);
        MultiLayerNetwork net2 = ModelSerializer.restoreMultiLayerNetwork(new File("tempmodel.bin"));

        net2.rnnTimeStep(in);
    }
```

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/1896
