### ISSUE TITLE
GAUSSIAN hidden unit causing IndexOutOfBound exception

### ISSUE THREAD

**Issue by winstonquock** [deeplearning4j/deeplearning4j#189]
```
Exception in thread "main" java.lang.IllegalArgumentException: Illegal index 5599 derived from 5599 with offset of 0 and stride of 1
	at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:2569)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:2852)
	at org.nd4j.linalg.sampling.Sampling.normal(Sampling.java:49)
	at org.deeplearning4j.models.featuredetectors.rbm.RBM.sampleHiddenGivenVisible(RBM.java:263)
	at org.deeplearning4j.models.featuredetectors.rbm.RBM.gradient(RBM.java:123)
	at org.deeplearning4j.nn.layers.BaseLayer.gradientAndScore(BaseLayer.java:325)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:117)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:131)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:41)
	at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:319)
	at org.deeplearning4j.models.featuredetectors.rbm.RBM.fit(RBM.java:451)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:215)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1138)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1173)
```
network config:
```kotlin
    // in kotlin syntax
    val hiddenLayerSizes = array(500, 100, 10) // 500, 100, 10
    val gen = MersenneTwister(123)

    val iteration = 10
    val layerFactory = LayerFactories.getFactory(javaClass<RBM>())
    val listBuilder = NeuralNetConfiguration.Builder()
            .iterations(iteration)!!
            .weightInit(WeightInit.DISTRIBUTION)!!
            .dist(Distributions.normal(gen, 1e-2))!!
            .activationFunction("tanh")!!
            .hiddenUnit(RBM.HiddenUnit.GAUSSIAN)!!
            .visibleUnit(RBM.VisibleUnit.GAUSSIAN)!!
            .layerFactory(layerFactory)!!
            .constrainGradientToUnitNorm(true )!!
            .optimizationAlgo(OptimizationAlgorithm.CONJUGATE_GRADIENT)!!
            .rng(gen)!!
            .learningRate(5e-2.toDouble())!!
            .nIn(trainingSet.numInputs())!!
            .nOut(trainingSet.numOutcomes())!!
            .list(hiddenLayerSizes.size() + 1)!!
            .hiddenLayerSizes(*hiddenLayerSizes.toIntArray())

    listBuilder.override({ i, builder ->
                if (i >= hiddenLayerSizes.size() ) { // 0 based, last one is output
                    builder.layerFactory(DefaultLayerFactory(javaClass<OutputLayer>()))
                    builder.activationFunction("tanh")
                    builder.lossFunction(LossFunctions.LossFunction.MSE)
                    builder.iterations(iteration * 5)
                }
            })
    val conf = listBuilder.build()!!
    val nn = MultiLayerNetwork(conf)
```

**Comment by agibsonccc** [comment]
Do you have the latest verison of nd4j?

**Comment by winstonquock** [comment]
Yes, I just retrieved the latest nd4j and dl4j. Still same problem. Note: only GAUSSIAN hidden units cause problem; the GAUSSIAN visible units are OK.

**Comment by agibsonccc** [comment]
Fixed.
