### ISSUE TITLE
UnsatisfiedLinkError: no jnind4j in java.library.path

### ISSUE THREAD

**Issue by GrtAndPwrflTrtl** [deeplearning4j/deeplearning4j#1924]
my program runs okay, but when I build artifacts to make a jar and try to run it on my other pc I get:

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnind4j in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:726)
        at org.bytedeco.javacpp.Loader.load(Loader.java:501)
        at org.nd4j.nativeblas.NativeOps.<clinit>(NativeOps.java:31)
        at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:33)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

```
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5093)
    at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5021)
    at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:169)
    at com.AutopredictiveCoding.App.xls2nndata(App.java:1573)
    at com.AutopredictiveCoding.App.train_NN_wearble_sensor(App.java:501)
    at com.AutopredictiveCoding.App.apc_sound(App.java:314)
    at com.AutopredictiveCoding.App.main(App.java:255)
```

Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Robert\AppData\Local\Temp\javacpp137708017629541\jnind4j.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:709)
## I don't understand what's going wrong, I had a jar working in 0.4.rc3.6, but I needed some of the newer functions, and swapping between cpu and gpu versions in my pom.xml didn't seem to be kicking in immediately every time, so I made a fresh _cpu project from scratch. I added the 3 additional dependencies (nd4j-native-platform, windows-x86_64-openblas, windows-x86_64) mentioned in https://github.com/deeplearning4j/deeplearning4j/issues/1819, but it didn't seem to make a difference:

My pom.xml:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

```
<groupId>com.AutopredictiveCoding</groupId>
<artifactId>APCSound</artifactId>
<version>1.0-SNAPSHOT</version>
<packaging>jar</packaging>

<name>APCSound</name>
<url>http://maven.apache.org</url>

<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <nd4j.version>0.4.0</nd4j.version>
    <dl4j.version>0.4.0</dl4j.version>
    <canova.version>0.0.0.14</canova.version>
    <jackson.version>2.7.4</jackson.version>
    <jblas.version>1.2.4</jblas.version>
</properties>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>

    <dependency>
        <groupId>org.nd4j</groupId>
        <artifactId>nd4j-native</artifactId>
        <version>${nd4j.version}</version>
    </dependency>

    <dependency>
        <groupId>org.nd4j</groupId>
        <artifactId>nd4j-native</artifactId>
        <version>${nd4j.version}</version>
        <classifier>windows-x86_64-openblas</classifier>
    </dependency>

    <dependency>
        <groupId>org.nd4j</groupId>
        <artifactId>nd4j-native</artifactId>
        <version>${nd4j.version}</version>
        <classifier>windows-x86_64</classifier>
        <scope>provided</scope>
    </dependency>

    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-nlp</artifactId>
        <version>${dl4j.version}</version>
    </dependency>

    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-core</artifactId>
        <version>${dl4j.version}</version>
    </dependency>

    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-ui</artifactId>
        <version>${dl4j.version}</version>
    </dependency>

    <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>19.0</version>
    </dependency>

    <dependency>
        <artifactId>canova-nd4j-image</artifactId>
        <groupId>org.nd4j</groupId>
        <version>${canova.version}</version>
    </dependency>

    <dependency>
        <artifactId>canova-nd4j-codec</artifactId>
        <groupId>org.nd4j</groupId>
        <version>${canova.version}</version>
    </dependency>

    <dependency>
        <groupId>com.fasterxml.jackson.dataformat</groupId>
        <artifactId>jackson-dataformat-yaml</artifactId>
        <version>${jackson.version}</version>
    </dependency>

    <!-- Used in the RegressionMathFunctions example -->
    <dependency>
        <groupId>jfree</groupId>
        <artifactId>jfreechart</artifactId>
        <version>1.0.13</version>
    </dependency>

    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>3.8.1</version>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>org.jblas</groupId>
        <artifactId>jblas</artifactId>
        <version>${jblas.version}</version>
    </dependency>

    <dependency>
        <groupId>gov.nist.math</groupId>
        <artifactId>jama</artifactId>
        <version>1.0.3</version>
    </dependency>

    <dependency>
        <groupId>com.mkobos</groupId>
        <artifactId>pca_transform</artifactId>
        <version>1.0.2</version>
    </dependency>

</dependencies>
```

</project>

**Comment by chrisvnicholson** [comment]
Did you look at the troubleshooting section at the bottom of the quickstart page? http://deeplearning4j.org/quickstart
