### ISSUE TITLE
MultiLayerNetwork: Updating with external loss seems broken for RMSProp

### ISSUE THREAD

**Issue by mschaars** [deeplearning4j/deeplearning4j#1937]
In 0.4.0, this was possible, where errorBatch was some externally calculated loss:

Pair<Gradient, INDArray> backpropGradient = network.backpropGradient(errorBatch);
 network.getUpdater().update(network, backpropGradient.getFirst(), 1, batchSize);'

The update call in the second line seems broken (don't get exception), updater is RMSProp - SGD works

Stacktrace:
java.lang.IllegalStateException: Updater has not been initialized with view state

	at org.nd4j.linalg.learning.RmsProp.getGradient(RmsProp.java:56)
	at org.deeplearning4j.nn.updater.BaseUpdater.update(BaseUpdater.java:78)
	at value_functions.NAFNetwork.update(NAFNetwork.java:172)
	at rl_agents.NAFAgent.computeLoss(NAFAgent.java:183)
	at rl_agents.NAFAgent.executeStep(NAFAgent.java:105)
	at NAFPerformanceTest.testFullSteps(NAFPerformanceTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by mschaars** [comment]
Update: This is solved by calling
initGradientsView() 

after calling init() on the network.
