### ISSUE TITLE
Unexpected class cast exception

### ISSUE THREAD

**Issue by BDUG** [deeplearning4j/deeplearning4j#1945]
0    [main] INFO  org.reflections.Reflections  - Reflections took 199 ms to scan 8 urls, producing 111 keys and 368 values 
Exception in thread "main" java.lang.ClassCastException: org.deeplearning4j.nn.conf.layers.LocalResponseNormalization cannot be cast to org.deeplearning4j.nn.conf.layers.FeedForwardLayer
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.addPreProcessors(ComputationGraphConfiguration.java:411)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.build(ComputationGraphConfiguration.java:691)
	at imagenet.Models.GoogleLeNet.init(GoogleLeNet.java:203)
	at imagenet.ImageNetMain.main(ImageNetMain.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Configuration snipped:

                //-- kernel size, stride , padding
                .addLayer("cnn1", new org.deeplearning4j.nn.conf.layers.ConvolutionLayer.Builder(new int[]{7, 7}, new int[]{2, 2}, new int[]{3, 3})
                        .nIn(channels)
                        .nOut(64)
                        .biasInit(0.2)
                        .build(), "input")

                 //-- kernel size, stride
                .addLayer("max1", new org.deeplearning4j.nn.conf.layers.SubsamplingLayer.Builder(org.deeplearning4j.nn.conf.layers.SubsamplingLayer.PoolingType.MAX, new int[]{3, 3}, new int[]{2, 2})
                        .build(), "cnn1")

                //--
                .addLayer("lrn1", new org.deeplearning4j.nn.conf.layers.LocalResponseNormalization.Builder(5, 1e-4, 0.75)
                        .build(), "max1")

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/1946
