### ISSUE TITLE
Exception "Cannot do forward pass: inputs not set", but they are set

### ISSUE THREAD

**Issue by BDUG** [deeplearning4j/deeplearning4j#1957]
Gist 1: https://gist.github.com/BDUG/cde8d3c207c9e98ee12a1bc6ea3cf629
Gist 2: https://gist.github.com/BDUG/4273c2d869179a1e68be096aea068117

and the stacktrace

Exception in thread "main" java.lang.IllegalStateException: Cannot do forward pass: inputs not set
	at org.deeplearning4j.nn.graph.vertex.impl.MergeVertex.doForward(MergeVertex.java:77)
	at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:984)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:890)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:152)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:54)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:769)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:737)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:612)
	at imagenet.ImageNetMain.main(ImageNetMain.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by AlexDBlack** [comment]
Could well be your network is misconfigured.
However, if that is the case, it should be picked up at the configuration time, not runtime.
I'll run this locally and take a look. BTW, is this 0.5.0 release or current dl4j/nd4j masters?

**Comment by AlexDBlack** [comment]
And 'inputs not set' means that the input arrays in a particular graph vertex haven't been set during the forward pass. Basically, the network is trying to do forward pass for a layer/vertex, where the input data isn't available for some reason.

**Comment by AlexDBlack** [comment]
Network is misconfigured.
https://gist.github.com/BDUG/4273c2d869179a1e68be096aea068117#file-googlelenet-L444

Your output vertices have to be the final thing in the network. Adding a merge vertex after the output layer isn't supported (merge vertex assumes errors are backpropagated through; however, labels and errors are separate arrays).

Also, it really helps when posting an issue if I can run it, one click, rather than trying to infer the missing pieces like input sizes, etc. For example, I can't run your code without the missing iterator.

**Comment by BDUG** [comment]
i will add the iterator

**Comment by AlexDBlack** [comment]
Don't worry about adding it here. The reason you are getting the issue is because your network is misconfigured.
Ideally that configuration problem should be identified earlier; I've added an issue for that here https://github.com/deeplearning4j/deeplearning4j/issues/1961
