### ISSUE TITLE
Unexpected exception: java.lang.ClassCastException

### ISSUE THREAD

**Issue by BDUG** [deeplearning4j/deeplearning4j#1958]
While doing 

.addVertex(top+"pre"+_name_merge_layer, new org.deeplearning4j.nn.conf.graph.MergeVertex(), "cnn1"+_name_merge_layer, "cnn5"+_name_merge_layer,"cnn6"+_name_merge_layer,"cnn7"+_name_merge_layer)

.addLayer(top, new OutputLayer.Builder().nIn(60*60*60).nOut(128).build(), top+"pre"+_name_merge_layer);

the following exception occures:

0    [main] INFO  org.reflections.Reflections  - Reflections took 251 ms to scan 8 urls, producing 111 keys and 368 values 
Exception in thread "main" 306  [main] WARN  org.deeplearning4j.nn.conf.ComputationGraphConfiguration  - Automatic addition of FF -> CNN preprocessors: not yet implemented (layer: max964df3cd-bc19-4851-ab5e-baa7ecee2b57)
java.lang.ClassCastException: org.deeplearning4j.nn.conf.inputs.InputType$InputTypeFeedForward cannot be cast to org.deeplearning4j.nn.conf.inputs.InputType$InputTypeConvolutional
	at org.deeplearning4j.nn.conf.graph.LayerVertex.getOutputType(LayerVertex.java:117)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.addPreProcessors(ComputationGraphConfiguration.java:433)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.build(ComputationGraphConfiguration.java:699)
	at imagenet.Models.GoogleLeNet.init(GoogleLeNet.java:451)
	at imagenet.ImageNetMain.main(ImageNetMain.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by AlexDBlack** [comment]
Hm, looks like you are feeding the output of a dense layer into a CNN layer somewhere. I assume this isn't what you intended?
I don't think that's a good idea in general - unlike CNN/pooling layers, your dense layer won't maintain any of the spatial relationships due to the globally-connected (rather than locally-connected) structure.

**Comment by AlexDBlack** [comment]
Can you give me something I can run to reproduce the issue? I'm assuming this is a different configuration than in your other issue, as I didn't run into this with that.

**Comment by BDUG** [comment]
Adapted one of your example to reproduce the failure:
https://drive.google.com/file/d/0Bxiqf8TfphsMSEZWWnJfNFBONVE/view?usp=sharing

**Comment by BDUG** [comment]
ClassCast is raised in class LayerVertex.java at line 117

            } else {
--›                afterPreProcessor = (InputType.InputTypeConvolutional) vertexInputs[0];
            }

**Comment by AlexDBlack** [comment]
Thanks, reproduced it with your code. Looking into it now.

**Comment by BDUG** [comment]
thanks in advance

**Comment by AlexDBlack** [comment]
So, this is one step forward: https://github.com/deeplearning4j/deeplearning4j/pull/1965

With that, I'm getting the following in your code:
Exception in thread "main" java.lang.IllegalStateException: Layer "max283375ca-6bda-4623-a7cd-37e2098a1838" of type class org.deeplearning4j.nn.conf.layers.SubsamplingLayer receiving input of type [InputTypeFeedForward(128)]
So, it looks like a misconfiguration issue.

I'll keep the issue open until we've confirmed that though.

**Comment by BDUG** [comment]
afaik it should not occure because of 

.setInputTypes(org.deeplearning4j.nn.conf.inputs.InputType.convolutional(height,width,channels));

correct?

**Comment by BDUG** [comment]
The illegal state is saying, that a dense layer ist not valid after a max pooling? is my understanding correct?

**Comment by AlexDBlack** [comment]
Other way around. The exception is stating that the specified subsampling layer is getting standard feed-forward input, given that configuration (i.e., a row vector for each example, like you would feed into a DenseLayer). It expects CNN input.
So either it's a bug or your network is misconfigured - haven't been able to tell which, last time I looked at it.

**Comment by AlexDBlack** [comment]
Significant rewrite to configuration validation and the InputTypes functionality here:
https://github.com/deeplearning4j/deeplearning4j/pull/1994

I'd suggest trying again after that PR, and opening another issue if you are still encountering problems.
