### ISSUE TITLE
NullPointerException in org.nd4j.linalg.api.rng.distribution.impl.NormalDistribution.sample()

### ISSUE THREAD

**Issue by carschno** [deeplearning4j/deeplearning4j#197]
When `org.nd4j.linalg.api.rng.distribution.impl.NormalDistribution#sample()` is called, the field `NormalDistribution#means` can be null, resulting in an uncaught `NullPointerException`. This can be reproduced by running `FacesDemo.java` from deeplearning4j-examples:
> Exception in thread "main" java.lang.NullPointerException
	at org.nd4j.linalg.api.rng.distribution.impl.NormalDistribution.sample(NormalDistribution.java:319)
>	at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:94)
>	at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:117)
>	at org.deeplearning4j.nn.params.DefaultParamInitializer.createWeightMatrix(DefaultParamInitializer.java:60)
>	at org.deeplearning4j.nn.params.DefaultParamInitializer.init(DefaultParamInitializer.java:39)
>	at org.deeplearning4j.nn.params.PretrainParamInitializer.init(PretrainParamInitializer.java:36)
>	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.getParams(DefaultLayerFactory.java:73)
>	at org.deeplearning4j.nn.layers.factory.DefaultLayerFactory.create(DefaultLayerFactory.java:51)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:357)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.initializeLayers(MultiLayerNetwork.java:323)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.setInput(MultiLayerNetwork.java:1384)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:201)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1138)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1173)
>	at org.deeplearning4j.lfw.FacesDemo.main(FacesDemo.java:59)

**Comment by carschno** [comment]
This issue should actually be in nd4j rather than in deeplearning4j.
