### ISSUE TITLE
Model updater saved with 0.4.0 cannot be loaded with 0.5.0

### ISSUE THREAD

**Issue by fac2003** [deeplearning4j/deeplearning4j#1974]
Got the following exception when loading a model trained and saved with DL4J 0.4.0 using 0.5.0. It seems that org.deeplearning4j.nn.updater.MultiLayerUpdater does not hard-code serialVersionUID. As a result, any change to the class, even compatible changes such as adding a method or field, will break loading of updaters saved with an earlier version of the class.

Exception in thread "main" java.io.InvalidClassException: org.deeplearning4j.nn.updater.MultiLayerUpdater; local class incompatible: stream classdesc serialVersionUID = 5140445576767494002, local class serialVersionUID = 7792279892583822027
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:621)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:196)
	at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:266)

**Comment by raver119** [comment]
It's a known bug, sorry.

There's workaround available for this issue:
- Open your saved model file as ZIP file
- remove updater
- Save back zipped model
- Model will be able to restore.
