### ISSUE TITLE
Exception in HistogramIterationListener propagates out

### ISSUE THREAD

**Issue by anovstrup** [deeplearning4j/deeplearning4j#1982]
An error in an iteration listener (specifically, `HistogramIterationListener`) is causing the training process to stop early. In my case, it would be preferable to log a warning and move on with training.

Workaround: wrap the listener?

```
WARN  [2016-08-08 21:41:03,574] org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer: Early stopping training terminated due to exception at epoch 0, iteration 0
! java.lang.NumberFormatException: Infinite or NaN
! at java.math.BigDecimal.<init>(BigDecimal.java:895) ~[na:1.8.0_73]
! at java.math.BigDecimal.<init>(BigDecimal.java:872) ~[na:1.8.0_73]
! at org.deeplearning4j.ui.weights.HistogramBin.calcHistogram(HistogramBin.java:60) ~[deeplearning4j-ui-0.5.0.jar:na]
! at org.deeplearning4j.ui.weights.HistogramBin.access$300(HistogramBin.java:20) ~[deeplearning4j-ui-0.5.0.jar:na]
! at org.deeplearning4j.ui.weights.HistogramBin$Builder.build(HistogramBin.java:127) ~[deeplearning4j-ui-0.5.0.jar:na]
! at org.deeplearning4j.ui.weights.HistogramIterationListener.iterationDone(HistogramIterationListener.java:169) ~[deeplearning4j-ui-0.5.0.jar:na]
! at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:65) ~[deeplearning4j-core-0.5.0.jar:na]
! at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51) ~[deeplearning4j-core-0.5.0.jar:na]
! at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doTruncatedBPTT(MultiLayerNetwork.java:1215) ~[deeplearning4j-core-0.5.0.jar:na]
! at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1477) ~[deeplearning4j-core-0.5.0.jar:na]
! at org.deeplearning4j.earlystopping.trainer.EarlyStoppingTrainer.fit(EarlyStoppingTrainer.java:59) ~[deeplearning4j-core-0.5.0.jar:na]
! at org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer.fit(BaseEarlyStoppingTrainer.java:109) ~[deeplearning4j-core-0.5.0.jar:na]
```

**Comment by raver119** [comment]
I've added temporary workaround here: https://github.com/deeplearning4j/deeplearning4j/pull/2005

But right now i think it's wrong approach. Instead, probably Min op should be checked, if it really should return NaN as minimal value in the array. As well as Max, returning INF as maximal value in the array.
