### ISSUE TITLE
Unexpected state occurred for AsyncDataSetIterator

### ISSUE THREAD

**Issue by johndemic** [deeplearning4j/deeplearning4j#1998]
I'm getting an java.lang.IllegalStateException in AsyncDataSetIterator when trying to run Word2VecSentimentRNN example imported into my own project.  The exception always occurs after the 500th iteration.   The only modifications I've made to the example are changing the path to the word vectors and serializing the model once evaluation is finished.  The serialization code is never hit because the exception is thrown before evaluation.  

Here is the stack trace:

Exception in thread "main" java.lang.IllegalStateException: Unexpected state occurred for AsyncDataSetIterator: runnable died or no data available
        at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.next(AsyncDataSetIterator.java:226)
        at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.next(AsyncDataSetIterator.java:35)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1054)
        at io.deepsail.cormorant.core.scratch.Word2VecSentimentRNN.main(Word2VecSentimentRNN.java:106)

Here are my classes:
https://gist.github.com/johndemic/f7f6dcb8af45281584a96e44f32a2bd9
https://gist.github.com/johndemic/9f8722c066b47dd1fab01a12dc292f9a

Here's the dependency graph:
https://gist.github.com/johndemic/dd1eb6dd1fc858a73050298f42761978

**Comment by johndemic** [comment]
Note that I refactored the example to feed the vectors in one at a time (per @raver119's suggestion) and it completes successfully:

 while (train.hasNext()) {
                net.fit(train.next());
            }

**Comment by raver119** [comment]
What about tests i've asked you to run?

**Comment by raver119** [comment]
No input for a month, and still no other people confirming this issue. 

Closing this issue for now.
