### ISSUE TITLE
Exception: java.lang.UnsatisfiedLinkError: org.nd4j.nativeblas.NativeOps.ompGetMaxThreads()

### ISSUE THREAD

**Issue by pedrofale** [deeplearning4j/deeplearning4j#2002]
Hi guys, 
After updating from 0.4rc3.9 to 0.5.0, I'm getting the following exception: 

```
Exception in thread "Thread-9" java.lang.UnsatisfiedLinkError: org.nd4j.nativeblas.NativeOps.ompGetMaxThreads()I
	org.nd4j.nativeblas.NativeOps.ompGetMaxThreads(Native Method)
	org.nd4j.nativeblas.NativeOps.<init>(NativeOps.java:50)
	org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:27)
	sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	java.lang.Class.newInstance(Class.java:442)
	org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4770)
	org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4716)
	org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:148)
	weka.classifiers.functions.dl4j.Utils.RNNinstancesToDataSet(Utils.java:58)
	weka.classifiers.functions.Dl4jRNNForecaster.buildClassifier(Dl4jRNNForecaster.java:285)
	weka.classifiers.timeseries.WekaForecaster$SingleTargetForecaster.buildForecaster(WekaForecaster.java:1748)
	weka.classifiers.timeseries.WekaForecaster.buildForecaster(WekaForecaster.java:1006)
	weka.classifiers.timeseries.gui.ForecastingPanel$ForecastingThread.run(ForecastingPanel.java:304)

	at org.nd4j.nativeblas.NativeOps.ompGetMaxThreads(Native Method)
	at org.nd4j.nativeblas.NativeOps.<init>(NativeOps.java:50)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:27)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4770)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4716)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:148)
	at weka.classifiers.functions.dl4j.Utils.RNNinstancesToDataSet(Utils.java:58)
	at weka.classifiers.functions.Dl4jRNNForecaster.buildClassifier(Dl4jRNNForecaster.java:285)
	at weka.classifiers.timeseries.WekaForecaster$SingleTargetForecaster.buildForecaster(WekaForecaster.java:1748)
	at weka.classifiers.timeseries.WekaForecaster.buildForecaster(WekaForecaster.java:1006)
	at weka.classifiers.timeseries.gui.ForecastingPanel$ForecastingThread.run(ForecastingPanel.java:304)
```

My pom.xml is as follows: 

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.deeplearning4j</groupId>
    <artifactId>deeplearning4j-examples</artifactId>
    <version>0.4-rc0-SNAPSHOT</version>

    <name>WEKA DL4J PACKAGE</name>
    <description>Deep learning for WEKA</description>

    <properties>
        <nd4j.version>0.5.0</nd4j.version>
        <dl4j.version>0.5.0</dl4j.version>
        <datavec.version>0.5.0</datavec.version>
        <jackson.version>2.8.1</jackson.version>
	    <weka.version>3.8.0</weka.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <!--<repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases><enabled>false</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
        </repository>
    </repositories> -->

    <distributionManagement>
        <!-- <snapshotRepository>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus snapshot repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>nexus-releases</id>
            <name>Nexus Release Repository</name>
            <url>http://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        </repository> -->
    </distributionManagement>

    <dependencies>
        <!--<dependency>-->
            <!--<groupId>nz.ac.waikato.cms.weka</groupId>-->
            <!--<artifactId>weka-stable</artifactId>-->
            <!--<version>${weka.version}</version>-->
            <!--<scope>test</scope>-->
            <!--<type>test-jar</type>-->
        <!--</dependency>-->
        <!-- <dependency>
            <groupId>nz.ac.waikato.cms.weka</groupId>
            <artifactId>weka-dev</artifactId>
            <version>3.7.14</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/weka.jar</systemPath>
        </dependency> -->
        <dependency>
            <groupId>nz.ac.waikato.cms.weka</groupId>
            <artifactId>weka-stable</artifactId>
            <version>${weka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-nlp</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-ui</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>19.0</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-api</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.datavec</groupId>
            <artifactId>datavec-api</artifactId>
            <version>${datavec.version}</version>
        </dependency>
        <dependency>
            <groupId>org.datavec</groupId>
            <artifactId>datavec-data-image</artifactId>
            <version>${datavec.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.basedir}/lib-full</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.4.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <executable>java</executable>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>1.6</version>
                <configuration>
                    <createDependencyReducedPom>true</createDependencyReducedPom>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>org/datanucleus/**</exclude>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>reference.conf</resource>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

And this is the dependency tree (as seen by running mvn dependency:tree):
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building WEKA DL4J PACKAGE 0.4-rc0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ deeplearning4j-examples ---
[INFO] org.deeplearning4j:deeplearning4j-examples:jar:0.4-rc0-SNAPSHOT
[INFO] +- nz.ac.waikato.cms.weka:weka-stable:jar:3.8.0:compile
[INFO] |  +- nz.ac.waikato.cms.weka.thirdparty:java-cup-11b:jar:2015.03.26:compile
[INFO] |  +- nz.ac.waikato.cms.weka.thirdparty:java-cup-11b-runtime:jar:2015.03.26:compile
[INFO] |  +- nz.ac.waikato.cms.weka.thirdparty:bounce:jar:0.18:compile
[INFO] |  +- com.googlecode.matrix-toolkits-java:mtj:jar:1.0.4:compile
[INFO] |  |  \- com.github.fommil.netlib:all:pom:1.1.2:compile
[INFO] |  |     +- com.github.fommil.netlib:netlib-native_ref-osx-x86_64:jar:natives:1.1:compile
[INFO] |  |     |  \- com.github.fommil.netlib:native_ref-java:jar:1.1:compile
[INFO] |  |     |     \- com.github.fommil:jniloader:jar:1.1:compile
[INFO] |  |     +- com.github.fommil.netlib:netlib-native_ref-linux-x86_64:jar:natives:1.1:compile
[INFO] |  |     +- com.github.fommil.netlib:netlib-native_ref-linux-i686:jar:natives:1.1:compile
[INFO] |  |     +- com.github.fommil.netlib:netlib-native_ref-win-x86_64:jar:natives:1.1:compile
[INFO] |  |     +- com.github.fommil.netlib:netlib-native_ref-win-i686:jar:natives:1.1:compile
[INFO] |  |     +- com.github.fommil.netlib:netlib-native_ref-linux-armhf:jar:natives:1.1:compile
[INFO] |  |     +- com.github.fommil.netlib:netlib-native_system-osx-x86_64:jar:natives:1.1:compile
[INFO] |  |     |  \- com.github.fommil.netlib:native_system-java:jar:1.1:compile
[INFO] |  |     +- com.github.fommil.netlib:netlib-native_system-linux-x86_64:jar:natives:1.1:compile
[INFO] |  |     +- com.github.fommil.netlib:netlib-native_system-linux-i686:jar:natives:1.1:compile
[INFO] |  |     +- com.github.fommil.netlib:netlib-native_system-linux-armhf:jar:natives:1.1:compile
[INFO] |  |     +- com.github.fommil.netlib:netlib-native_system-win-x86_64:jar:natives:1.1:compile
[INFO] |  |     \- com.github.fommil.netlib:netlib-native_system-win-i686:jar:natives:1.1:compile
[INFO] |  +- net.sourceforge.f2j:arpack_combined_all:jar:0.1:compile
[INFO] |  \- com.googlecode.netlib-java:netlib-java:jar:1.1:compile
[INFO] |     \- com.github.fommil.netlib:core:jar:1.1:compile
[INFO] +- org.deeplearning4j:deeplearning4j-nlp:jar:0.5.0:compile
[INFO] |  +- org.apache.directory.studio:org.apache.commons.codec:jar:1.8:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.8:compile
[INFO] |  +- it.unimi.dsi:dsiutils:jar:2.2.2:compile
[INFO] |  |  +- it.unimi.dsi:fastutil:jar:6.5.15:compile
[INFO] |  |  +- com.martiansoftware:jsap:jar:2.1:compile
[INFO] |  |  +- commons-configuration:commons-configuration:jar:1.8:compile
[INFO] |  |  |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |  |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |  \- commons-collections:commons-collections:jar:20040616:compile
[INFO] |  +- org.cleartk:cleartk-snowball:jar:2.0.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-snowball:jar:3.0.3:compile
[INFO] |  |  +- org.cleartk:cleartk-util:jar:2.0.0:compile
[INFO] |  |  |  +- org.apache.uima:uimaj-core:jar:2.5.0:compile
[INFO] |  |  |  \- org.apache.uima:uimafit-core:jar:2.0.0:compile
[INFO] |  |  |     +- commons-logging:commons-logging-api:jar:1.1:compile
[INFO] |  |  |     +- org.springframework:spring-core:jar:3.1.2.RELEASE:compile
[INFO] |  |  |     |  \- org.springframework:spring-asm:jar:3.1.2.RELEASE:compile
[INFO] |  |  |     +- org.springframework:spring-context:jar:3.1.2.RELEASE:compile
[INFO] |  |  |     |  +- org.springframework:spring-aop:jar:3.1.2.RELEASE:compile
[INFO] |  |  |     |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |  |     |  \- org.springframework:spring-expression:jar:3.1.2.RELEASE:compile
[INFO] |  |  |     \- org.springframework:spring-beans:jar:3.1.2.RELEASE:compile
[INFO] |  |  \- org.cleartk:cleartk-type-system:jar:2.0.0:compile
[INFO] |  +- org.cleartk:cleartk-opennlp-tools:jar:2.0.0:compile
[INFO] |  |  +- org.apache.opennlp:opennlp-maxent:jar:3.0.3:compile
[INFO] |  |  +- org.apache.opennlp:opennlp-tools:jar:1.5.3:compile
[INFO] |  |  |  \- net.sf.jwordnet:jwnl:jar:1.3.3:compile
[INFO] |  |  \- org.apache.opennlp:opennlp-uima:jar:1.5.3:compile
[INFO] |  +- io.dropwizard:dropwizard-assets:jar:0.8.0:compile
[INFO] |  |  +- io.dropwizard:dropwizard-core:jar:0.8.0:compile
[INFO] |  |  |  +- io.dropwizard:dropwizard-util:jar:0.8.0:compile
[INFO] |  |  |  |  \- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] |  |  |  +- io.dropwizard:dropwizard-jackson:jar:0.8.0:compile
[INFO] |  |  |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk7:jar:2.5.1:compile
[INFO] |  |  |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.5.1:compile
[INFO] |  |  |  |  \- com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.5.1:compile
[INFO] |  |  |  +- io.dropwizard:dropwizard-validation:jar:0.8.0:compile
[INFO] |  |  |  |  +- org.hibernate:hibernate-validator:jar:5.1.3.Final:compile
[INFO] |  |  |  |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  |  |  |  +- org.jboss.logging:jboss-logging:jar:3.1.3.GA:compile
[INFO] |  |  |  |  |  \- com.fasterxml:classmate:jar:1.0.0:compile
[INFO] |  |  |  |  \- org.glassfish:javax.el:jar:3.0.0:compile
[INFO] |  |  |  +- io.dropwizard:dropwizard-configuration:jar:0.8.0:compile
[INFO] |  |  |  +- io.dropwizard:dropwizard-logging:jar:0.8.0:compile
[INFO] |  |  |  |  +- io.dropwizard.metrics:metrics-logback:jar:3.1.0:compile
[INFO] |  |  |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.10:compile
[INFO] |  |  |  |  +- org.slf4j:log4j-over-slf4j:jar:1.7.10:compile
[INFO] |  |  |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.10:compile
[INFO] |  |  |  |  \- org.eclipse.jetty:jetty-util:jar:9.2.9.v20150224:compile
[INFO] |  |  |  +- io.dropwizard:dropwizard-metrics:jar:0.8.0:compile
[INFO] |  |  |  +- io.dropwizard:dropwizard-jersey:jar:0.8.0:compile
[INFO] |  |  |  |  +- org.glassfish.jersey.core:jersey-server:jar:2.16:compile
[INFO] |  |  |  |  |  \- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.16:compile
[INFO] |  |  |  |  +- org.glassfish.jersey.ext:jersey-metainf-services:jar:2.16:compile
[INFO] |  |  |  |  +- io.dropwizard.metrics:metrics-jersey2:jar:3.1.0:compile
[INFO] |  |  |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.5.1:compile
[INFO] |  |  |  |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.5.1:compile
[INFO] |  |  |  |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.5.1:compile
[INFO] |  |  |  |  +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.16:compile
[INFO] |  |  |  |  |  \- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.16:compile
[INFO] |  |  |  |  +- org.eclipse.jetty:jetty-server:jar:9.2.9.v20150224:compile
[INFO] |  |  |  |  |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  |  |  |  |  \- org.eclipse.jetty:jetty-io:jar:9.2.9.v20150224:compile
[INFO] |  |  |  |  +- org.eclipse.jetty:jetty-webapp:jar:9.2.9.v20150224:compile
[INFO] |  |  |  |  |  \- org.eclipse.jetty:jetty-xml:jar:9.2.9.v20150224:compile
[INFO] |  |  |  |  \- org.eclipse.jetty:jetty-continuation:jar:9.2.9.v20150224:compile
[INFO] |  |  |  +- io.dropwizard:dropwizard-jetty:jar:0.8.0:compile
[INFO] |  |  |  |  +- io.dropwizard.metrics:metrics-jetty9:jar:3.1.0:compile
[INFO] |  |  |  |  +- org.eclipse.jetty:jetty-servlet:jar:9.2.9.v20150224:compile
[INFO] |  |  |  |  |  \- org.eclipse.jetty:jetty-security:jar:9.2.9.v20150224:compile
[INFO] |  |  |  |  +- org.eclipse.jetty:jetty-servlets:jar:9.2.9.v20150224:compile
[INFO] |  |  |  |  \- org.eclipse.jetty:jetty-http:jar:9.2.9.v20150224:compile
[INFO] |  |  |  +- io.dropwizard:dropwizard-lifecycle:jar:0.8.0:compile
[INFO] |  |  |  +- io.dropwizard.metrics:metrics-core:jar:3.1.0:compile
[INFO] |  |  |  +- io.dropwizard.metrics:metrics-jvm:jar:3.1.0:compile
[INFO] |  |  |  +- io.dropwizard.metrics:metrics-servlets:jar:3.1.0:compile
[INFO] |  |  |  |  \- io.dropwizard.metrics:metrics-json:jar:3.1.0:compile
[INFO] |  |  |  +- io.dropwizard.metrics:metrics-healthchecks:jar:3.1.0:compile
[INFO] |  |  |  +- net.sourceforge.argparse4j:argparse4j:jar:0.4.4:compile
[INFO] |  |  |  \- org.eclipse.jetty.toolchain.setuid:jetty-setuid-java:jar:1.0.2:compile
[INFO] |  |  \- io.dropwizard:dropwizard-servlets:jar:0.8.0:compile
[INFO] |  |     \- io.dropwizard.metrics:metrics-annotation:jar:3.1.0:compile
[INFO] |  +- io.dropwizard:dropwizard-views-mustache:jar:0.8.0:compile
[INFO] |  |  +- io.dropwizard:dropwizard-views:jar:0.8.0:compile
[INFO] |  |  \- com.github.spullara.mustache.java:compiler:jar:0.8.17:compile
[INFO] |  +- io.dropwizard:dropwizard-views-freemarker:jar:0.8.0:compile
[INFO] |  \- org.nd4j:nd4j-jackson:jar:0.5.0:compile
[INFO] +- org.deeplearning4j:deeplearning4j-core:jar:0.5.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.12:compile
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.1.2:compile
[INFO] |  +- ch.qos.logback:logback-core:jar:1.1.2:compile
[INFO] |  +- org.apache.commons:commons-math3:jar:3.4.1:compile
[INFO] |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  +- org.apache.commons:commons-compress:jar:1.8:compile
[INFO] |  |  \- org.tukaani:xz:jar:1.5:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.3.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.5.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.5.1:compile
[INFO] |  +- org.json:json:jar:20131018:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.5.1:compile
[INFO] |  +- org.projectlombok:lombok:jar:1.16.4:compile
[INFO] |  \- org.datavec:datavec-nd4j-common:jar:0.5.0:compile
[INFO] +- org.deeplearning4j:deeplearning4j-ui:jar:0.5.0:compile
[INFO] |  +- io.dropwizard:dropwizard-client:jar:0.8.0:compile
[INFO] |  |  +- org.glassfish.jersey.core:jersey-client:jar:2.16:compile
[INFO] |  |  |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] |  |  |  +- org.glassfish.hk2:hk2-api:jar:2.4.0-b09:compile
[INFO] |  |  |  |  +- org.glassfish.hk2:hk2-utils:jar:2.4.0-b09:compile
[INFO] |  |  |  |  \- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.4.0-b09:compile
[INFO] |  |  |  +- org.glassfish.hk2.external:javax.inject:jar:2.4.0-b09:compile
[INFO] |  |  |  \- org.glassfish.hk2:hk2-locator:jar:2.4.0-b09:compile
[INFO] |  |  |     \- org.javassist:javassist:jar:3.18.1-GA:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-httpclient:jar:3.1.0:compile
[INFO] |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.3.5:compile
[INFO] |  |  |     \- org.apache.httpcomponents:httpcore:jar:4.3.2:compile
[INFO] |  |  \- org.glassfish.jersey.connectors:jersey-apache-connector:jar:2.16:compile
[INFO] |  +- io.dropwizard:dropwizard-forms:jar:0.8.0:compile
[INFO] |  \- org.glassfish.jersey.media:jersey-media-multipart:jar:2.16:compile
[INFO] |     +- org.glassfish.jersey.core:jersey-common:jar:2.16:compile
[INFO] |     |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |     |  +- org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.16:compile
[INFO] |     |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO] |     \- org.jvnet.mimepull:mimepull:jar:1.9.3:compile
[INFO] +- com.google.guava:guava:jar:19.0:compile
[INFO] +- org.nd4j:nd4j-native:jar:0.5.0:compile
[INFO] |  +- org.nd4j:nd4j-native:jar:linux-x86_64:0.5.0:compile
[INFO] |  \- org.nd4j:nd4j-native-api:jar:0.5.0:compile
[INFO] +- org.nd4j:nd4j-api:jar:0.5.0:compile
[INFO] |  +- org.nd4j:nd4j-buffer:jar:0.5.0:compile
[INFO] |  |  \- org.nd4j:nd4j-common:jar:0.5.0:compile
[INFO] |  |     \- org.reflections:reflections:jar:0.9.10:compile
[INFO] |  |        \- com.google.code.findbugs:annotations:jar:2.0.1:compile
[INFO] |  \- org.nd4j:nd4j-context:jar:0.5.0:compile
[INFO] +- org.datavec:datavec-api:jar:0.5.0:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.4.4:compile
[INFO] |  +- joda-time:joda-time:jar:2.9.2:compile
[INFO] |  \- org.freemarker:freemarker:jar:2.3.23:compile
[INFO] +- org.datavec:datavec-data-image:jar:0.5.0:compile
[INFO] |  +- com.github.jai-imageio:jai-imageio-core:jar:1.3.0:compile
[INFO] |  +- com.twelvemonkeys.imageio:imageio-jpeg:jar:3.1.1:compile
[INFO] |  |  +- com.twelvemonkeys.imageio:imageio-core:jar:3.1.1:compile
[INFO] |  |  +- com.twelvemonkeys.imageio:imageio-metadata:jar:3.1.1:compile
[INFO] |  |  +- com.twelvemonkeys.common:common-lang:jar:3.1.1:compile
[INFO] |  |  +- com.twelvemonkeys.common:common-io:jar:3.1.1:compile
[INFO] |  |  \- com.twelvemonkeys.common:common-image:jar:3.1.1:compile
[INFO] |  +- com.twelvemonkeys.imageio:imageio-tiff:jar:3.1.1:compile
[INFO] |  +- com.twelvemonkeys.imageio:imageio-psd:jar:3.1.1:compile
[INFO] |  +- com.twelvemonkeys.imageio:imageio-bmp:jar:3.1.1:compile
[INFO] |  +- org.bytedeco:javacpp:jar:1.2.3:compile
[INFO] |  +- org.bytedeco:javacv:jar:1.2:compile
[INFO] |  +- org.bytedeco.javacpp-presets:opencv:jar:3.1.0-1.2:compile
[INFO] |  +- org.bytedeco.javacpp-presets:opencv:jar:linux-x86_64:3.1.0-1.2:compile
[INFO] |  +- org.bytedeco.javacpp-presets:opencv:jar:macosx-x86_64:3.1.0-1.2:compile
[INFO] |  +- org.bytedeco.javacpp-presets:opencv:jar:windows-x86_64:3.1.0-1.2:compile
[INFO] |  +- org.bytedeco.javacpp-presets:opencv:jar:linux-ppc64le:3.1.0-1.2:compile
[INFO] |  +- org.bytedeco.javacpp-presets:ffmpeg:jar:3.0.2-1.2:compile
[INFO] |  +- org.bytedeco.javacpp-presets:ffmpeg:jar:linux-x86_64:3.0.2-1.2:compile
[INFO] |  +- org.bytedeco.javacpp-presets:ffmpeg:jar:macosx-x86_64:3.0.2-1.2:compile
[INFO] |  +- org.bytedeco.javacpp-presets:ffmpeg:jar:windows-x86_64:3.0.2-1.2:compile
[INFO] |  +- org.bytedeco.javacpp-presets:ffmpeg:jar:linux-ppc64le:3.0.2-1.2:compile
[INFO] |  +- org.bytedeco.javacpp-presets:leptonica:jar:1.73-1.2:compile
[INFO] |  +- org.bytedeco.javacpp-presets:leptonica:jar:linux-x86_64:1.73-1.2:compile
[INFO] |  +- org.bytedeco.javacpp-presets:leptonica:jar:macosx-x86_64:1.73-1.2:compile
[INFO] |  +- org.bytedeco.javacpp-presets:leptonica:jar:windows-x86_64:1.73-1.2:compile
[INFO] |  \- org.bytedeco.javacpp-presets:leptonica:jar:linux-ppc64le:1.73-1.2:compile
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.8.1:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.15:compile
[INFO] \- junit:junit:jar:4.12:compile
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.046 s
[INFO] Finished at: 2016-08-11T12:52:02+01:00
[INFO] Final Memory: 17M/166M
```

**Comment by pedrofale** [comment]
Not a DL4J problem, but mine.
