### ISSUE TITLE
IndexOutOfBoundsException when using DataBuffer.Type.HALF

### ISSUE THREAD

**Issue by seebacherd** [deeplearning4j/deeplearning4j#2018]
Hi everybody,

I have a little problem when using `DataBuffer.Type.HALF`. I'm getting the following `IndexOutOfBoundsException`

```java
Exception in thread "main" java.lang.IndexOutOfBoundsException: 9144
	at org.bytedeco.javacpp.indexer.Indexer.checkIndex(Indexer.java:90)
	at org.bytedeco.javacpp.indexer.HalfRawIndexer.get(HalfRawIndexer.java:59)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.getFloat(BaseDataBuffer.java:854)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.getFloat(BaseCudaDataBuffer.java:888)
	at org.nd4j.linalg.jcublas.buffer.CudaHalfDataBuffer.getDouble(CudaHalfDataBuffer.java:239)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3280)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3704)
	at org.deeplearning4j.plot.Tsne.x2p(Tsne.java:266)
	at org.deeplearning4j.plot.Tsne.calculate(Tsne.java:89)
	at kn.seebacher.DataExplorer.App.main(App.java:95)
```

I have created a SSCCE to illustrate that issue:

```java
		// set to half data type
		DataTypeUtil.setDTypeForContext(DataBuffer.Type.HALF);

		// create 9144x4096 randomly filled array
		double[][] array = IntStream.range(0, 9144)
				.mapToObj(a -> IntStream.range(0, 4096).mapToDouble(index -> Math.random()).toArray())
				.toArray(double[][]::new);

		// crate INDArray
		INDArray data = Nd4j.create(array);
		
		// calculate tsne mapping
		BarnesHutTsne bhTSNE = new BarnesHutTsne.Builder().build();
		INDArray tsne = bhTSNE.calculate(data, 2, 30);
```

If comment out the line `DataTypeUtil.setDTypeForContext(DataBuffer.Type.HALF);` the code works fine.

**Comment by raver119** [comment]
Could you please translate your code to Java, so i could run it locally? It looks like a bug somewhere in the depths, but i need something i can run myself.

**Comment by seebacherd** [comment]
That shouldn't be a problem. The example is already written in plain Java (1.8), but you can replace the `IntStream` line with this 1.7 compatible code:

```java
		double[][] array = new double[9144][4096];
		for (int i = 0; i < array.length; i++) {
			for (int j = 0; j < array[0].length; j++) {
				array[i][j] = Math.random();
			}
		}
```

**Comment by raver119** [comment]
Thanks for flagging this issue, fixed now: https://github.com/deeplearning4j/nd4j/pull/1225
