### ISSUE TITLE
ConvolutionalIterationListener throws an IllegalArgumentException

### ISSUE THREAD

**Issue by s103451** [deeplearning4j/deeplearning4j#2029]
When trying to use the ConvolutionalIterationListener on my convnet it doesn't work.
I'm using a windows 10-64 bit machine, with 8GB of ram and a 2.9 Quad core processor.
I'm using jdk1.8.0_25

Exception: 
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: Illegal index 2 out of tads 1
	at org.deeplearning4j.ui.weights.ConvolutionalIterationListener.iterationDone(ConvolutionalIterationListener.java:127)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:65)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1067)
	at org.deeplearning4j.examples.convolution.Driver2.main(Driver2.java:157)
Caused by: java.lang.IllegalArgumentException: Illegal index 2 out of tads 1
	at org.nd4j.linalg.api.ndarray.BaseNDArray.tensorAlongDimension(BaseNDArray.java:789)
	at org.deeplearning4j.ui.weights.ConvolutionalIterationListener.restoreRGBImage(ConvolutionalIterationListener.java:525)
	at org.deeplearning4j.ui.weights.ConvolutionalIterationListener.iterationDone(ConvolutionalIterationListener.java:124)
	... 4 more

Code:
https://gist.github.com/s103451/cfe413f25264c0885dab1c423941043d

**Comment by raver119** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2063

Will be merged soon &trade;
