### ISSUE TITLE
Using HistogramIterationListener on 0.5.0 causes CuDNN error

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/deeplearning4j#2037]
OS: Windows 10 
CPU: i5-4460 3.2GHz
GPU: GTX 970
Driver: 353.90
CUDA Version: 7.5

**Steps to reproduce:**

Modify dl4j-examples pom.xml nd4j.backend to <nd4j.backend>nd4j-cuda-7.5-platform</nd4j.backend>
Modify dl4j-examples/dl4j-examples pom.xml: Add:
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-cuda-7.5</artifactId>
            <version>0.5.0</version>
        </dependency>
Modify LenetMnistExample modifying model.setListeners line to:
        model.setListeners(
            new HistogramIterationListener(1),
            new ScoreIterationListener(1)
        );

**Output:**
```
o.d.e.c.LenetMnistExample - Load data....


o.d.e.c.LenetMnistExample - Build model....
o.d.n.l.c.ConvolutionLayer - Could not load CudnnConvolutionHelper
java.lang.UnsatisfiedLinkError: no jnicudnn in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864) ~[na:1.8.0_65]
	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[na:1.8.0_65]
	at java.lang.System.loadLibrary(System.java:1122) ~[na:1.8.0_65]
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:726) ~[javacpp-1.2.3.jar:1.2.3]
	at org.bytedeco.javacpp.Loader.load(Loader.java:501) ~[javacpp-1.2.3.jar:1.2.3]
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\egonzalez\AppData\Local\Temp\javacpp112622691285046\jnicudnn.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.8.0_65]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938) ~[na:1.8.0_65]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821) ~[na:1.8.0_65]
	at java.lang.Runtime.load0(Runtime.java:809) ~[na:1.8.0_65]
	at java.lang.System.load(System.java:1086) ~[na:1.8.0_65]
o.d.n.l.c.s.SubsamplingLayer - Could not load CudnnSubsamplingHelper
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.cudnn
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper$CudnnContext.createHandles(CudnnSubsamplingHelper.java:89) ~[deeplearning4j-cuda-7.5-0.5.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper$CudnnContext.<init>(CudnnSubsamplingHelper.java:76) ~[deeplearning4j-cuda-7.5-0.5.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper.<init>(CudnnSubsamplingHelper.java:105) ~[deeplearning4j-cuda-7.5-0.5.0.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_65]
o.d.n.l.c.ConvolutionLayer - Could not load CudnnConvolutionHelper
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.cudnn
	at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper$CudnnContext.createHandles(CudnnConvolutionHelper.java:95) ~[deeplearning4j-cuda-7.5-0.5.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper$CudnnContext.<init>(CudnnConvolutionHelper.java:79) ~[deeplearning4j-cuda-7.5-0.5.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper.<init>(CudnnConvolutionHelper.java:137) ~[deeplearning4j-cuda-7.5-0.5.0.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_65]
o.d.n.l.c.s.SubsamplingLayer - Could not load CudnnSubsamplingHelper
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.cudnn
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper$CudnnContext.createHandles(CudnnSubsamplingHelper.java:89) ~[deeplearning4j-cuda-7.5-0.5.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper$CudnnContext.<init>(CudnnSubsamplingHelper.java:76) ~[deeplearning4j-cuda-7.5-0.5.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper.<init>(CudnnSubsamplingHelper.java:105) ~[deeplearning4j-cuda-7.5-0.5.0.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_65]
o.d.e.c.LenetMnistExample - Train model....
INFO  [2016-08-26 23:05:15,961] org.eclipse.jetty.util.log: Logging initialized @6846ms
INFO  [2016-08-26 23:05:16,023] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: assets for path /assets/*
      port: 8080
      port: 8081
WARN  [2016-08-26 23:05:16,175] org.glassfish.jersey.internal.Errors: The following warnings have been detected: WARNING: Cannot create new registration for component type class org.deeplearning4j.ui.exception.GenericExceptionMapper: Existing previous registration found for the type.

INFO  [2016-08-26 23:05:16,184] io.dropwizard.server.ServerFactory: Starting UiServer
WARN  [2016-08-26 23:05:16,209] org.glassfish.jersey.internal.Errors: The following warnings have been detected: WARNING: Cannot create new registration for component type class io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: Existing previous registration found for the type.

WARN  [2016-08-26 23:05:16,298] org.eclipse.jetty.server.ServerConnector: Acceptors should be <= availableProcessors: ServerConnector@1c5c616f{HTTP/1.1}{0.0.0.0:0}
INFO  [2016-08-26 23:05:16,311] org.eclipse.jetty.setuid.SetUIDListener: Opened application@1c5c616f{HTTP/1.1}{0.0.0.0:8080}
INFO  [2016-08-26 23:05:16,311] org.eclipse.jetty.setuid.SetUIDListener: Opened admin@3f985a86{HTTP/1.1}{0.0.0.0:8081}
INFO  [2016-08-26 23:05:16,315] org.eclipse.jetty.server.Server: jetty-9.2.9.v20150224
INFO  [2016-08-26 23:05:17,487] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    GET     /tsne (org.deeplearning4j.ui.tsne.TsneDropwiz)
    GET     /tsne/{path} (org.deeplearning4j.ui.tsne.TsneDropwiz)
    POST    /tsne/update (org.deeplearning4j.ui.tsne.TsneDropwiz)
    POST    /tsne/upload (org.deeplearning4j.ui.tsne.TsneDropwiz)
    POST    /tsne/vocab (org.deeplearning4j.ui.tsne.TsneDropwiz)
    GET     /weights (org.deeplearning4j.ui.weights.WeightDropwiz)
    GET     /weights/data (org.deeplearning4j.ui.weights.WeightDropwiz)
    GET     /weights/updated (org.deeplearning4j.ui.weights.WeightDropwiz)
    POST    /weights/update (org.deeplearning4j.ui.weights.WeightDropwiz)
    GET     /rl (org.deeplearning4j.ui.rl.RlDropwiz)
    GET     /rl/state (org.deeplearning4j.ui.rl.RlDropwiz)
    POST    /rl/state (org.deeplearning4j.ui.rl.RlDropwiz)
    GET     /flow (org.deeplearning4j.ui.flow.FlowDropwiz)
    GET     /flow/action/{id} (org.deeplearning4j.ui.flow.FlowDropwiz)
    GET     /flow/state (org.deeplearning4j.ui.flow.FlowDropwiz)
    POST    /flow/action/{id} (org.deeplearning4j.ui.flow.FlowDropwiz)
    POST    /flow/state (org.deeplearning4j.ui.flow.FlowDropwiz)
    GET     /api/coords (org.deeplearning4j.ui.api.ApiResource)
    GET     /api/{path} (org.deeplearning4j.ui.api.ApiResource)
    POST    /api/coords (org.deeplearning4j.ui.api.ApiResource)
    POST    /api/update (org.deeplearning4j.ui.api.ApiResource)
    POST    /api/upload (org.deeplearning4j.ui.api.ApiResource)
    GET     /filters (org.deeplearning4j.ui.renders.RendersDropwiz)
    GET     /filters/img (org.deeplearning4j.ui.renders.RendersDropwiz)
    POST    /filters/update (org.deeplearning4j.ui.renders.RendersDropwiz)
    GET     /word2vec (org.deeplearning4j.ui.nearestneighbors.word2vec.NearestNeighborsDropwiz)
    GET     /word2vec/{path} (org.deeplearning4j.ui.nearestneighbors.word2vec.NearestNeighborsDropwiz)
    POST    /word2vec/upload (org.deeplearning4j.ui.nearestneighbors.word2vec.NearestNeighborsDropwiz)
    POST    /word2vec/vocab (org.deeplearning4j.ui.nearestneighbors.word2vec.NearestNeighborsDropwiz)
    POST    /word2vec/words (org.deeplearning4j.ui.nearestneighbors.word2vec.NearestNeighborsDropwiz)
    GET     / (org.deeplearning4j.ui.defaults.DefaultDropwiz)
    GET     /events (org.deeplearning4j.ui.defaults.DefaultDropwiz)
    GET     /sessions (org.deeplearning4j.ui.defaults.DefaultDropwiz)
    GET     /whatsup (org.deeplearning4j.ui.defaults.DefaultDropwiz)
    GET     /activations (org.deeplearning4j.ui.activation.ActivationsDropwiz)
    GET     /activations/img (org.deeplearning4j.ui.activation.ActivationsDropwiz)
    POST    /activations/update (org.deeplearning4j.ui.activation.ActivationsDropwiz)

INFO  [2016-08-26 23:05:17,495] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@1642eeae{/,null,AVAILABLE}
INFO  [2016-08-26 23:05:17,498] io.dropwizard.setup.AdminEnvironment: tasks = 

    POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
    POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)

WARN  [2016-08-26 23:05:17,498] io.dropwizard.setup.AdminEnvironment: 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    THIS APPLICATION HAS NO HEALTHCHECKS. THIS MEANS YOU WILL NEVER KNOW      !
!     IF IT DIES IN PRODUCTION, WHICH MEANS YOU WILL NEVER KNOW IF YOU'RE      !
!    LETTING YOUR USERS DOWN. YOU SHOULD ADD A HEALTHCHECK FOR EACH OF YOUR    !
!         APPLICATION'S DEPENDENCIES WHICH FULLY (BUT LIGHTLY) TESTS IT.       !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
INFO  [2016-08-26 23:05:17,504] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@78422efb{/,null,AVAILABLE}
INFO  [2016-08-26 23:05:17,524] org.eclipse.jetty.server.ServerConnector: Started application@1c5c616f{HTTP/1.1}{0.0.0.0:8080}
INFO  [2016-08-26 23:05:17,528] org.eclipse.jetty.server.ServerConnector: Started admin@3f985a86{HTTP/1.1}{0.0.0.0:8081}
INFO  [2016-08-26 23:05:17,528] org.eclipse.jetty.server.Server: Started @8415ms
UI Histogram URL: http://localhost:8080/weights?sid=5d2d974c-c270-4919-8e8b-3d93dee43e93
INFO  [2016-08-26 23:05:19,753] org.deeplearning4j.optimize.listeners.ScoreIterationListener: Score at iteration 0 is 2.521898223350428
INFO  [2016-08-26 23:05:21,047] org.deeplearning4j.optimize.listeners.ScoreIterationListener: Score at iteration 1 is 2.3332566977590465
INFO  [2016-08-26 23:05:22,249] org.deeplearning4j.optimize.listeners.ScoreIterationListener: Score at iteration 2 is 1.9908612018536949
```

Without HistogramIterationListner the GPU works fine.

**Comment by raver119** [comment]
Does it work without cuDNN?

**Comment by wmeddie** [comment]
Ah, CuDNN is missing on this computer so this is just a CUDA issue I guess.

**Comment by raver119** [comment]
Yep, java.lang.UnsatisfiedLinkError: no jnicudnn in java.library.path says that.

**Comment by wmeddie** [comment]
The effect of 0 GPU usage still remains though.  The error message is just unrelated.

No HistogramIterationLIstener many iterations/sec With HistogramIterationListener 1 Iteration/sec.

**Comment by raver119** [comment]
I don't see anything about 0 GPU usage in this issue. File new issue about it please.
