### ISSUE TITLE
Running ParagraphVectorsClassifierExample on GPU

### ISSUE THREAD

**Issue by dmallela** [deeplearning4j/deeplearning4j#2058]
Hi , I have recently started using deeplearning4J, I wanted to use paragraphVector and word2Vector on GPU. However, I'm getting exception 

```
23:13:11.979 [main] INFO  org.reflections.Reflections - Reflections took 284 ms to scan 1 urls, producing 129 keys and 428 values
23:13:12.072 [main] INFO  o.d.m.s.SequenceVectors - Starting vocabulary building...
23:13:12.072 [main] DEBUG o.d.m.w.wordstore.VocabConstructor - Target vocab size before building: [0]
23:13:12.072 [main] DEBUG o.d.m.w.wordstore.VocabConstructor - Trying source iterator: [0]
23:13:12.072 [main] DEBUG o.d.m.w.wordstore.VocabConstructor - Target vocab size before building: [0]
23:13:12.072 [main] DEBUG o.d.m.w.wordstore.VocabConstructor - Vocab size before truncation: [0],  NumWords: [0], sequences parsed: [0], counter: [0]
23:13:12.073 [main] DEBUG o.d.m.w.wordstore.VocabConstructor - Vocab size after truncation: [0],  NumWords: [0], sequences parsed: [0], counter: [0]
23:13:12.073 [main] INFO  o.d.m.w.wordstore.VocabConstructor - Sequences checked: [0], Current vocabulary size: [0]
Exception in thread "main" java.lang.ArithmeticException: / by zero at
org.deeplearning4j.models.sequencevectors.SequenceVectors.buildVocab(SequenceVectors.java:115)

at org.deeplearning4j.models.sequencevectors.SequenceVectors.fit(SequenceVectors.java:138)
at com.Classifier.paragraphvectors.ParagraphVectorsClassifierExample.makeParagraphVectors(ParagraphVectorsClassifierExample.java:89) 
at com.Classifier.paragraphvectors.ParagraphVectorsClassifierExample.main(ParagraphVectorsClassifierExample.java:47)
```

**Comment by raver119** [comment]
Unfortunately NLP part, w2v and paravec, are not suited for GPU. They are kind of unique snowflakes at this moment.

Also, as far as i see your issue isn't GPU, but empty iterator, which gave nothing to vocab constructor.

**Comment by dmallela** [comment]
Can you please suggest some  models that work on GPU for processing text data in deeLearning4J
