### ISSUE TITLE
Test failure AutoEncoderTest.testAutoEncoder()

### ISSUE THREAD

**Issue by smarthi** [deeplearning4j/deeplearning4j#206]
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.304 sec <<< FAILURE! - in org.deeplearning4j.models.featuredetectors.autoencoder.AutoEncoderTest
testAutoEncoder(org.deeplearning4j.models.featuredetectors.autoencoder.AutoEncoderTest)  Time elapsed: 0.304 sec  <<< ERROR!
org.apache.commons.math3.exception.NoBracketingException: function values at endpoints do not have different signs, endpoints: [0, 1], values: [0.514, 0.914]
	at org.apache.commons.math3.analysis.solvers.BrentSolver.doSolve(BrentSolver.java:122)
	at org.apache.commons.math3.analysis.solvers.BaseAbstractUnivariateSolver.solve(BaseAbstractUnivariateSolver.java:195)
	at org.apache.commons.math3.analysis.solvers.BaseAbstractUnivariateSolver.solve(BaseAbstractUnivariateSolver.java:200)
	at org.apache.commons.math3.analysis.solvers.UnivariateSolverUtils.solve(UnivariateSolverUtils.java:81)
	at org.nd4j.linalg.api.rng.distribution.BaseDistribution.inverseCumulativeProbability(BaseDistribution.java:150)
	at org.nd4j.linalg.api.rng.distribution.BaseDistribution.sample(BaseDistribution.java:204)
	at org.deeplearning4j.nn.layers.BasePretrainNetwork.getCorruptedInput(BasePretrainNetwork.java:102)
	at org.deeplearning4j.models.featuredetectors.autoencoder.AutoEncoder.gradient(AutoEncoder.java:111)
	at org.deeplearning4j.nn.layers.BaseLayer.gradientAndScore(BaseLayer.java:323)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:117)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:131)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:44)
	at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:317)
	at org.deeplearning4j.models.featuredetectors.autoencoder.AutoEncoderTest.testAutoEncoder(AutoEncoderTest.java:72)

**Comment by agibsonccc** [comment]
Fixed.
