### ISSUE TITLE
Error running MultiGPULenetMnistExample on Azure NV24

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/deeplearning4j#2060]
CPU: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
GPU: Tesla M60 x 4
CUDA Version: 7.5
CUDA Driver: 361.45.09
OS: Docker FROM nvidia/cuda:7.5-cudnn4-devel-centos7 (CentOS Linux release 7.2.1511 (Core))
Host OS: Ubuntu 16.04.1 LTS

When I run dl4j-examples's MultiGPULenetMnistExample from 0.5.0 or master (0.5.1-SNAPSHOT) I get the following error:

```
CUDA error at /opt/libnd4j/blas/cuda/NativeOps.cu:5343 code=77(<unknown>) "result"
o.d.p.ParallelWrapper - Averaged score: 2.0396938428767024
CUDA error at /opt/libnd4j/blas/cuda/NativeOps.cu:5292 code=77(<unknown>) "result"
Failed on [140394272981392] -> [8883763712], size: [32], direction: [0], result: [77]
Exception in thread "main" java.lang.IllegalStateException: MemcpyAsync H2H failed: [140394272981392] -> [8883763712]
        at org.nd4j.jita.handler.impl.CudaZeroHandler.memcpyAsync(CudaZeroHandler.java:510)
        at org.nd4j.jita.handler.impl.CudaZeroHandler.memcpyBlocking(CudaZeroHandler.java:611)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.memcpyBlocking(AtomicAllocator.java:801)
        at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.average(JCublasNDArrayFactory.java:800)
        at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.average(JCublasNDArrayFactory.java:851)
        at org.nd4j.linalg.factory.Nd4j.averageAndPropagate(Nd4j.java:4784)
        at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:143)
        at org.deeplearning4j.examples.multigpu.MultiGpuLenetMnistExample.main(MultiGpuLenetMnistExample.java:145)
```

Setting `CudaEnvironment.getInstance().getConfiguration().allowCrossDeviceAccess(false);` Has no effect.  The example does run to completion after Setting `CudaEnvironment.getInstance().getConfiguration().allowMultiGPU(false)` but using only a single GPU.

**Comment by raver119** [comment]
in ParallelWrapper there's an option: useLegacyAveraging(). In example it's set to false. Please set it to true, and you'll be fine.

**Comment by agibsonccc** [comment]
Regardless of whether this is true we should try avoid letting this stuff propagate down to the c level if we can.

**Comment by wmeddie** [comment]
Works fine with useLegacyAveraging(true).

**Comment by raver119** [comment]
@agibsonccc yea i'll add checks for p2p availability there.
