### ISSUE TITLE
 AnimalsClassification computer vision example runs for 3 hours and throws exception

### ISSUE THREAD

**Issue by ramgo2** [deeplearning4j/deeplearning4j#2090]
I was trying to run the AnimalsClassification computer vision example.  It runs for 3 hours and finally throws exception as below on a 6th Gen i7 processor with 16GB RAM and SSD.  

[Example Code](https://github.com/deeplearning4j/ComputerVision-examples/blob/master/src/main/java/org/deeplearning4j/examples/cv/animalRecognition/AnimalsClassification.java)

o.d.o.l.ScoreIterationListener - Score at iteration 3916 is 1.3862971819934105
o.d.o.l.ScoreIterationListener - Score at iteration 3917 is 1.386297181312827
o.d.o.l.ScoreIterationListener - Score at iteration 3918 is 1.386297180636377
o.d.o.l.ScoreIterationListener - Score at iteration 3919 is 1.3862971799620063
o.d.o.l.ScoreIterationListener - Score at iteration 3920 is 1.3862971792894323
o.d.o.l.ScoreIterationListener - Score at iteration 3921 is 1.3862971786195788
Exception in thread "Thread-7696926" java.lang.StackOverflowError
    at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$IteratorRunnable.hasLatch(AsyncDataSetIterator.java:284)
    at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.hasNext(AsyncDataSetIterator.java:186)
    at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$IteratorRunnable.hasLatch(AsyncDataSetIterator.java:274)
    at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.hasNext(AsyncDataSetIterator.java:186)
    at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$IteratorRunnable.hasLatch(AsyncDataSetIterator.java:274)
    at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.hasNext(AsyncDataSetIterator.java:186)
    at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$IteratorRunnable.hasLatch(AsyncDataSetIterator.java:274)
    at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.hasNext(AsyncDataSetIterator.java:186)

Not knowing why it was taking so long for just some 80 test images (standard images that come with the example), I replaced the MultipleEpochsIterator with RecordReaderDataSetIterator and epochs loop as in main LenetMnistExample.  It now runs in less than 10 seconds though accuracy/F1 scores are low.  While MultipleEpochsIterator threw exceptions after 3hours.  Any idea why?

The modified example code and the new log is given below.
[NewLog.txt](https://github.com/deeplearning4j/deeplearning4j/files/463776/NewLog.txt)

[AnimalsClassificationEx.java.txt](https://github.com/deeplearning4j/deeplearning4j/files/463767/AnimalsClassificationEx.java.txt)

**Comment by raver119** [comment]
I've missed this issue somehow :(

Is it still reproducible with current master?

**Comment by ramgo2** [comment]
The issue doesn't occur now.  You can close the issue.  

Now the log looks like below...
o.d.d.i.MultipleEpochsIterator - Epoch 1, number of batches completed 70
o.d.d.i.MultipleEpochsIterator - Epoch 2, number of batches completed 70

Is there a way of getting the scores at each iteration in the batch like with the ScoreIterationListener?
