### ISSUE TITLE
org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out

### ISSUE THREAD

**Issue by jjzhu** [deeplearning4j/deeplearning4j#211]
I maybe use an old version. But I have git pull all the latest sources from 0.0.3.3 branch for deeplearning4j and ND4j. I have a project depended on deeplearning4j, therefore it will take me sometime to use canova. 

Trying to see if I we can still use the 0.0.3.3 branch. Here is the error:

org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/home/hunter/workspace/npsmultint_repo/NPSHadoop/word2vec-index/write.lock
	at org.apache.lucene.store.Lock.obtain(Lock.java:89)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:753)
	at org.deeplearning4j.text.invertedindex.LuceneInvertedIndex.tryCreateWriter(LuceneInvertedIndex.java:605)
	at org.deeplearning4j.text.invertedindex.LuceneInvertedIndex.getWriterWithRetry(LuceneInvertedIndex.java:569)
	at org.deeplearning4j.text.invertedindex.LuceneInvertedIndex.getWriter(LuceneInvertedIndex.java:619)

**Comment by agibsonccc** [comment]
Please try this with the latest master. I haven't ran in to this issue in a while. Re open this if it's still a problem with the latest master. Thanks!
