### ISSUE TITLE
writeEntry(InputStream inputStream, ZipOutputStream zipStream) is writing slowly

### ISSUE THREAD

**Issue by valncrt** [deeplearning4j/deeplearning4j#2140]
It took around 5 minutes to write a 1.7G file, significantly more slowly than when using writeWordVectors (which was deprecated) and replaced with writeParagraphVectors.  Partial stack track trace is below.  Looks like the code needs a buffered writer, Maybe something like this?  http://stackoverflow.com/questions/14462371/preferred-way-to-use-java-zipoutputstream-and-bufferedoutputstream

 java.lang.Thread.State: RUNNABLE
        at java.util.zip.Deflater.deflateBytes(java.base@9-ea/Native Method)
        at java.util.zip.Deflater.deflate(java.base@9-ea/Deflater.java:447)
        - locked <0x000000032e09bc68> (a java.util.zip.ZStreamRef)
        at java.util.zip.Deflater.deflate(java.base@9-ea/Deflater.java:366)
        at java.util.zip.DeflaterOutputStream.deflate(java.base@9-ea/DeflaterOutputStream.java:251)
        at java.util.zip.DeflaterOutputStream.write(java.base@9-ea/DeflaterOutputStream.java:211)
        at java.util.zip.ZipOutputStream.write(java.base@9-ea/ZipOutputStream.java:330)
        - locked <0x0000000324face50> (a java.util.zip.ZipOutputStream)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.writeEntry(WordVectorSerializer.java:805)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.writeParagraphVectors(WordVectorSerializer.java:587)

**Comment by raver119** [comment]
Fixed. Thanks for highlighting this issue.
