### ISSUE TITLE
ComputationGraph Network can't be built because of some length issues

### ISSUE THREAD

**Issue by sid-sahani** [deeplearning4j/deeplearning4j#2146]
```
        ComputationGraphConfiguration conf = new NeuralNetConfiguration.Builder()
                .seed(seed)
                .iterations(iterations)
                .regularization(true).l2(0.0005)
                .learningRate(0.01)
                .weightInit(WeightInit.XAVIER)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .updater(Updater.NESTEROVS).momentum(0.9)

                .graphBuilder()
                .addInputs("input")

                .addLayer("first", new ConvolutionLayer.Builder(3,300).nIn(nChannels).padding(1,1).stride(1,1)
                    .nOut(100).activation("relu").build(),"input")
                .addLayer("second", new ConvolutionLayer.Builder(4,300).nIn(nChannels).padding(1,1).stride(1,1)
                    .nOut(100).activation("relu").build(),"input")
                .addLayer("third",  new ConvolutionLayer.Builder(5,300).nIn(nChannels).padding(1,1).stride(1,1)
                    .nOut(100).activation("relu").build(),"input")
                .addVertex("merge", new MergeVertex(), "first", "second", "third")
                .addLayer("L1", new OutputLayer.Builder().nIn(300).nOut(100).build(), "merge")

                .addLayer("L2", new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.MAX).kernelSize(2,2)
                    .stride(1,1).build() ,"L1")

                .addLayer("L3", new DenseLayer.Builder().activation("relu").nOut(500).dropOut(0.5).build(), "L2")

                .addLayer("L4", new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
                    .nOut(outputNum).activation("softmax").build() ,"L3")
                .setOutputs("L4")  //List the output. For a ComputationGraph with multiple outputs, this also defines the input array orders
                .pretrain(false).backprop(true)
                .build();

        ComputationGraph net = new ComputationGraph(conf);
        net.init();
        net.setListeners(new ScoreIterationListener(1));

```

net.init() causes the following Error

```
Exception in thread "main" java.lang.IllegalArgumentException: Length must be >= 1
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:118)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:78)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.create(DefaultDataBufferFactory.java:66)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1042)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:167)
	at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:70)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:258)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3696)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.create(BaseNDArray.java:1766)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subArray(BaseNDArray.java:1922)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3810)
	at org.deeplearning4j.nn.params.DefaultParamInitializer.init(DefaultParamInitializer.java:73)
	at org.deeplearning4j.nn.conf.layers.DenseLayer.instantiate(DenseLayer.java:51)
	at org.deeplearning4j.nn.conf.graph.LayerVertex.instantiate(LayerVertex.java:85)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:352)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:263)
```

What is wrong in the Neural Net?

**Comment by sid-sahani** [comment]
I can run the following Net perfectly.

```
MultiLayerConfiguration.Builder builder = new NeuralNetConfiguration.Builder()
                .seed(seed)
                .iterations(iterations)
                .regularization(true).l2(0.0005)
                .learningRate(0.01)//.biasLearningRate(0.02)
                .learningRateDecayPolicy(LearningRatePolicy.Inverse).lrPolicyDecayRate(0.001).lrPolicyPower(0.75)
                .weightInit(WeightInit.XAVIER)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .updater(Updater.NESTEROVS).momentum(0.9)
                .list()
                .layer(0, new ConvolutionLayer.Builder(4,300)
                        //nIn and nOut specify depth. nIn here is the nChannels and nOut is the number of filters to be applied
                        .nIn(nChannels)
                        .padding(1,1)
                        .stride(1,1)
                        .nOut(100)
                        .activation("relu")
                        .build())
                .layer(1, new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.MAX)
                        .kernelSize(2,2)
                        .stride(1,1)
                        .build())
                .layer(2, new DenseLayer.Builder().activation("relu")
                        .nOut(500).dropOut(0.5).build())
                .layer(3, new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
                        .nOut(outputNum)
                        .activation("softmax")
                        .build())
                .backprop(true).pretrain(false);
 
        new ConvolutionLayerSetup(builder,199,300,1);
```

I want layer 0 from the above to be used as the "input" layers "first", "second", "third" with different filter sizes of 3, 4 and 5 respectively, and merge them as is neatly done here  https://github.com/tflearn/tflearn/blob/master/examples/nlp/cnn_sentence_classification.py

**Comment by AlexDBlack** [comment]
As discussed in gitter: missing nIn values on L3 and L4.
Alternatively, use InputType functionality. (.setInputType(InputType....))

**Comment by sid-sahani** [comment]
```
        int nChannels = 1;
        int outputNum = 2;
        int batchSize = 1; //64
        int nEpochs = 100;
        int iterations = 1;
        int seed = 123;

        System.out.println("Load data....");

       RecordReader rr = new CSVRecordReader();
       rr.initialize(new FileSplit(new File("dl4j-examples\\dl4j-examples\\src\\main\\resources\\classification\\trainableData.csv")));
       DataSetIterator LSTrain = new RecordReaderDataSetIterator(rr,batchSize,0,2);


       RecordReader rrTest = new CSVRecordReader();
       rrTest.initialize(new FileSplit(new File("dl4j-examples\\dl4j-examples\\src\\main\\resources\\classification\\testableData.csv")));
       DataSetIterator LSTest = new RecordReaderDataSetIterator(rrTest,batchSize,0,2);

        System.out.println("Build model....");
        ComputationGraphConfiguration conf = new NeuralNetConfiguration.Builder()
                .seed(seed)
                .iterations(iterations)
                .regularization(true).l2(0.0005)
                .learningRate(0.01)
                .weightInit(WeightInit.XAVIER)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .updater(Updater.NESTEROVS).momentum(0.9)

                .graphBuilder()
                .addInputs("input")

                .setInputTypes(InputType.convolutional(199, 300, nChannels))
                .addLayer("first", new ConvolutionLayer.Builder(3,300).nIn(nChannels).padding(1,1).stride(1,1)
                    .nOut(50).activation("relu").build(),"input")
//                .addLayer("second", new ConvolutionLayer.Builder(4,300).nIn(nChannels).padding(1,1).stride(1,1)
//                    .nOut(50).activation("relu").build(),"input")
//                .addLayer("third",  new ConvolutionLayer.Builder(5,300).nIn(nChannels).padding(1,1).stride(1,1)
//                    .nOut(50).activation("relu").build(),"input")
//                .addVertex("merge", new MergeVertex(), "first", "second", "third")
                .addLayer("L1", new OutputLayer.Builder().nIn(150).nOut(300).build(), "first")

                .addLayer("L2", new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.MAX).kernelSize(2,2)
                    .stride(1,1).build() ,"L1")

                .addLayer("L3", new DenseLayer.Builder().activation("relu").nIn(400).nOut(500).dropOut(0.5).build(), "L2")

                .addLayer("L4", new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD).nIn(500)
                    .nOut(outputNum).activation("softmax").build() ,"L3")
                .setOutputs("L4")  //List the output. For a ComputationGraph with multiple outputs, this also defines the input array orders
                .pretrain(false).backprop(true)
                .build();

        ComputationGraph net = new ComputationGraph(conf);
        net.init();
        net.setListeners(new ScoreIterationListener(1));

```

@AlexDBlack With the aforementioned changes I get this :

```
Exception in thread "main" org.deeplearning4j.nn.conf.inputs.InvalidInputTypeException: Invalid input: MergeVertex cannot merge CNN activations of different width/heights:first [depth,width,height] = [50,3,199], input 1 = [50,3,198]
	at org.deeplearning4j.nn.conf.graph.MergeVertex.getOutputType(MergeVertex.java:133)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.addPreProcessors(ComputationGraphConfiguration.java:372)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.build(ComputationGraphConfiguration.java:620)
	at org.deeplearning4j.examples.convolution.LegalSifterCompGraphCNN.main(LegalSifterCompGraphCNN.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by AlexDBlack** [comment]
"Invalid input: MergeVertex cannot merge CNN activations of different width/heights:first [depth,width,height] = [50,3,199], input 1 = [50,3,198]"
For CNNs, merging is done along depth dimension (which is arguably the only way that makes sense for CNNs). Consequently, the width and heights of all inputs must match (though the depths can differ, as they are added/stacked).
I assume this is what you are going for? If not - do you have a reference for the architecture you are trying to build?

**Comment by sid-sahani** [comment]
https://github.com/tflearn/tflearn/blob/master/examples/nlp/cnn_sentence_classification.py

Yes I wanna merge them along depth only. Above is the architecture I'm trying to recreate.

**Comment by sid-sahani** [comment]
@AlexDBlack My data is in the form of a single vector of 59700 elements... (600 data points) As I stated in my absolute 2nd comment ... I can run it with MultiLayerConfiguration.Builder and I specify the dimensions like
new ConvolutionLayerSetup(builder,199,300,1); And I've got the same data. I'm not sure how does 198 creep in.

**Comment by AlexDBlack** [comment]
"I can run it with MultiLayerConfiguration.Builder"
No, you can't. The configuration you are using is not possible with MultiLayerNetwork/Configuration.
you are using different kernel sizes in the 3 layers, hence you get different output sizes. Then you are trying to merge the different sizes along depth, which is not possible.
To work out output sizes: read "spatial arrangement" here: http://cs231n.github.io/convolutional-networks/
specifically (w-f+2p)/s+1
As for exactly how tflearn handles that: I'm not sure.

**Comment by sid-sahani** [comment]
@AlexDBlack Sorry for the confusion, the "it" refered to my 2nd comment, i shouldn't have put those dots. You're right MultiLayer Configuration/Network doesn't allow to merge layers. I'll workout the Output bit and open the Issue, if needed.
