### ISSUE TITLE
Test Failure in MultiLayerTest.testDbnFaces

### ISSUE THREAD

**Issue by smarthi** [deeplearning4j/deeplearning4j#216]
o.d.n.m.MultiLayerNetwork - Training on layer 1 with 28 examples
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 22.983 sec <<< FAILURE! - in org.deeplearning4j.nn.multilayer.MultiLayerTest
testDbnFaces(org.deeplearning4j.nn.multilayer.MultiLayerTest) Time elapsed: 3.488 sec <<< FAILURE!
java.lang.AssertionError: Invalid output on labels. Must not contain nan or infinite numbers.
at org.nd4j.linalg.lossfunctions.LossFunctions.score(LossFunctions.java:44)
at org.deeplearning4j.nn.layers.BasePretrainNetwork.setScore(BasePretrainNetwork.java:68)
at org.deeplearning4j.nn.layers.BaseLayer.setParams(BaseLayer.java:143)
at org.deeplearning4j.optimize.solvers.BackTrackLineSearch.optimize(BackTrackLineSearch.java:219)
at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:172)
at org.deeplearning4j.optimize.Solver.optimize(Solver.java:44)
at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:309)
at org.deeplearning4j.models.featuredetectors.rbm.RBM.fit(RBM.java:409)
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:211)
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1137)
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1177)
at org.deeplearning4j.nn.multilayer.MultiLayerTest.testDbnFaces(MultiLayerTest.java:82)

**Comment by smarthi** [comment]
The offending line is Nd4j.invalidNumber(z)

**Comment by agibsonccc** [comment]
Got rid of that exception.
