### ISSUE TITLE
ClassNotFoundException: org.nd4j.linalg.api.complex.IComplexNumber

### ISSUE THREAD

**Issue by Gh0s7** [deeplearning4j/deeplearning4j#2167]
I'm trying to follow [this tutorial](http://deeplearning4j.org/word2vec#just) but I'm getting this stack trace:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/nd4j/linalg/api/complex/IComplexNumber
	at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable$Builder.<init>(InMemoryLookupTable.java:636)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$Builder.presetTables(SequenceVectors.java:678)
	at org.deeplearning4j.models.word2vec.Word2Vec$Builder.build(Word2Vec.java:449)
	at mypackage.MyClass.myMethod(MyClass.java:57)
Caused by: java.lang.ClassNotFoundException: org.nd4j.linalg.api.complex.IComplexNumber
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```

at this line:

```
Word2Vec model = new Word2Vec.Builder()
                .minWordFrequency(5)
                .iterations(1)
                .layerSize(100)
                .seed(42)
                .windowSize(5)
                .iterate(iterator)
                .tokenizerFactory(tokenizer)
                .build();
```

I don't use Maven, so I manually added these libraries:

- deeplearning4j-core-0.6.0
- deeplearning4j-nlp-0.6.0
- jackson-core-2.8.3
- nd4j-api-0.6.0
- nd4j-native-0.6.0
- nd4j-x86-0.4-rc3.8

What am I missing?

**Comment by raver119** [comment]
Remove nd4j-x86 from dependencies.

8 окт. 2016 г. 13:11 пользователь "Gh0s7" <notifications@github.com>
написал:

**Comment by Gh0s7** [comment]
That one was added as a final try before posting here, same exception even without it.

**Comment by raver119** [comment]
Show full pom.xml without it.

8 окт. 2016 г. 13:16 пользователь "Gh0s7" <notifications@github.com>
написал:

**Comment by Gh0s7** [comment]
> I don't use Maven, so I manually added these libraries

I don't have any pom.xml since I'm not using Maven.

**Comment by raver119** [comment]
Ah, so you're missing 100500 other dependencies, which are usually handled by maven/gradle/sbt/whatever.

You have to use build system, sorry. Just too many dependencies to track them manually.

**Comment by Khalid-Usman** [comment]
@raver119  I used maven with IntelliJ , still having the same issue.  Can you please guide me on it?

**Comment by raver119** [comment]
If your issue is the same - answer is the same. Remove x86 dependency.

**Comment by Khalid-Usman** [comment]
@raver119  I don't have this dependency in my pom file. I have installed all through maven, if you have time can you solve my issue via skype screen sharing, I am stuck from last 3 days. :(

**Comment by agibsonccc** [comment]
Closing comments on this. We can not and will not offer that kind of support for free.
I told you multiple times in the channel to learn the tools you're given.
