### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by yilaguan** [deeplearning4j/deeplearning4j#2177]
Hi, I use the example "/dl4j-spark-examples/dl4j-spark-local/src/main/java/org.deeplearning4j/mlp/MnistMLPPreprocessed.java" to submit myself spark job, and I use yarn to launch instead of local model. Some error occurred below:
```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 31 in stage 1.0 failed 4 times, most recent failure: Lost task 31.3 in stage 1.0 (TID 108, longzhou-hdp6.lz.dscc): java.lang.NullPointerException
        at org.nd4j.linalg.dataset.DataSet.numExamples(DataSet.java:1203)
        at org.deeplearning4j.spark.data.BatchAndExportDataSetsFunction.call(BatchAndExportDataSetsFunction.java:73)
        at org.deeplearning4j.spark.data.BatchAndExportDataSetsFunction.call(BatchAndExportDataSetsFunction.java:46)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$mapPartitionsWithIndex$1.apply(JavaRDDLike.scala:105)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$mapPartitionsWithIndex$1.apply(JavaRDDLike.scala:105)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$22.apply(RDD.scala:745)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$22.apply(RDD.scala:745)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
How can I deal with this program?

**Comment by agibsonccc** [comment]
Ensure you have kryo enabled: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-serde/nd4j-kryo/src/main/java/org/nd4j/Nd4jRegistrator.java#L7

**Comment by yilaguan** [comment]
It seems to useless to set kryo. When I use : 
```
sparkConf.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer");
sparkConf.set("spark.kryo.registrator", "org.nd4j.Nd4jRegistrator");
```
The error will be: 
```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task serialization failed: org.apache.spark.SparkException: Failed to register classes with Kryo
org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:128)
org.apache.spark.serializer.KryoSerializerInstance.borrowKryo(KryoSerializer.scala:273)
org.apache.spark.serializer.KryoSerializerInstance.<init>(KryoSerializer.scala:258)
org.apache.spark.serializer.KryoSerializer.newInstance(KryoSerializer.scala:174)
org.apache.spark.broadcast.TorrentBroadcast$.blockifyObject(TorrentBroadcast.scala:201)
org.apache.spark.broadcast.TorrentBroadcast.writeBlocks(TorrentBroadcast.scala:102)
org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:85)
org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:34)
org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:63)
org.apache.spark.SparkContext.broadcast(SparkContext.scala:1326)
org.apache.spark.scheduler.DAGScheduler.submitMissingTasks(DAGScheduler.scala:1006)
org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$submitStage(DAGScheduler.scala:921)
org.apache.spark.scheduler.DAGScheduler.handleJobSubmitted(DAGScheduler.scala:861)
org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1607)
org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
```

**Comment by agibsonccc** [comment]
You need to add the nd4j-kryo dependency I linked to earlier.

**Comment by yilaguan** [comment]
Thanks for your help.
