### ISSUE TITLE
ConjugateGradient triggers OutOfMemory for bigger dataset on Spark

### ISSUE THREAD

**Issue by psuszyns** [deeplearning4j/deeplearning4j#2186]
I'm using deeplearning4j & nd4j 0.6.0 and cannot get rid of OutOfMemory issues while using CONJUGATE_GRADIENT algorithm. It works ok for very small inputs (< 100 training examples) but for bigger, but still very small, input containing 2663 examples Spark (version 1.6.0) job fails with:

```
java.lang.OutOfMemoryError: Cannot allocate new PointerPointer(2), totalBytes = 282104630, physicalBytes = 20594274304
    at org.bytedeco.javacpp.PointerPointer.<init>(PointerPointer.java:126)
    at org.bytedeco.javacpp.PointerPointer.<init>(PointerPointer.java:61)
    at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:224)
    at org.nd4j.linalg.api.ndarray.BaseNDArray.var(BaseNDArray.java:3534)
    at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.propUp(RBM.java:325)
    at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.activate(RBM.java:399)
    at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:385)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:552)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardToLayer(MultiLayerNetwork.java:675)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1820)
    at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:152)
    at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:171)
    at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1453)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1490)
    at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingWorker.processMinibatch(ParameterAveragingTrainingWorker.java:91)
    at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingWorker.processMinibatch(ParameterAveragingTrainingWorker.java:27)
    at org.deeplearning4j.spark.api.worker.ExecuteWorkerFlatMap.call(ExecuteWorkerFlatMap.java:99)
    at org.deeplearning4j.spark.api.worker.ExecuteWorkerFlatMap.call(ExecuteWorkerFlatMap.java:28)
    at org.deeplearning4j.spark.api.worker.ExecuteWorkerPathFlatMap.call(ExecuteWorkerPathFlatMap.java:27)
    at org.deeplearning4j.spark.api.worker.ExecuteWorkerPathFlatMap.call(ExecuteWorkerPathFlatMap.java:18)
    at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
    at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Physical memory usage is too high (20594241536 > Pointer.maxPhysicalBytes)
    at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:547)
    at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
    at org.bytedeco.javacpp.PointerPointer.allocateArray(Native Method)
    at org.bytedeco.javacpp.PointerPointer.<init>(PointerPointer.java:118)
```

I'm using following network setup (it's quite big, probably I'm not going to need that big network in the end but I'd like to test if deeplearning4j scales well enough):
```
    val conf = new NeuralNetConfiguration.Builder()
      .seed(15485863)
      .learningRate(0.1)
      .learningRateScoreBasedDecayRate(0.5)
      .weightInit(WeightInit.XAVIER)
      .iterations(5)
      .optimizationAlgo(OptimizationAlgorithm.CONJUGATE_GRADIENT)
      .list()
      .layer(0, new RBM.Builder()
        .nIn(530).nOut(800)
        .lossFunction(LossFunction.RMSE_XENT)  
        .visibleUnit(RBM.VisibleUnit.GAUSSIAN)
        .hiddenUnit(RBM.HiddenUnit.RECTIFIED)
        .sparsity(0.15)
        .build())
      .layer(1, new RBM.Builder()
        .nIn(800).nOut(600)
        .lossFunction(LossFunction.RMSE_XENT) 
        .visibleUnit(RBM.VisibleUnit.GAUSSIAN)
        .hiddenUnit(RBM.HiddenUnit.RECTIFIED)
        .sparsity(0.15)
        .build())
      .layer(2, new RBM.Builder()
        .nIn(600).nOut(400)
        .lossFunction(LossFunction.RMSE_XENT)  
        .visibleUnit(RBM.VisibleUnit.GAUSSIAN)
        .hiddenUnit(RBM.HiddenUnit.RECTIFIED)
        .sparsity(0.1)
        .build())
      .layer(3, new RBM.Builder()
        .nIn(400).nOut(200)
        .lossFunction(LossFunction.RMSE_XENT)  
        .visibleUnit(RBM.VisibleUnit.GAUSSIAN)
        .hiddenUnit(RBM.HiddenUnit.RECTIFIED)
        .sparsity(0.1)
        .build())
      .layer(4, new RBM.Builder()
        .nIn(200).nOut(100)
        .lossFunction(LossFunction.RMSE_XENT)  
        .visibleUnit(RBM.VisibleUnit.GAUSSIAN)
        .hiddenUnit(RBM.HiddenUnit.RECTIFIED)
        .sparsity(0.1)
        .build())
      .layer(5, new OutputLayer.Builder(LossFunction.NEGATIVELOGLIKELIHOOD)  
        .activation("softmax")
        .nIn(100).nOut(30)
        .build())
      .pretrain(true)
      .backprop(true)
      .build()


val net = new MultiLayerNetwork(conf)
net.init()

val tm = new ParameterAveragingTrainingMaster.Builder(1)
  .averagingFrequency(10)
  .workerPrefetchNumBatches(2)
  .saveUpdater(true)
  .repartionData(Repartition.Always)
  .repartitionStrategy(RepartitionStrategy.SparkDefault)
  .build()

val sparkNet = new SparkDl4jMultiLayer(sc, net, tm)
```

spark-submit  arguments are:
`
--master yarn 
--executor-cores 8 
--driver-memory 10g 
--executor-memory 10g 
--num-executors 5 
--deploy-mode cluster 
--conf "spark.executor.extraJavaOptions=-Dorg.bytedeco.javacpp.maxbytes=48318382080" 
--conf "spark.driver.extraJavaOptions=-Dorg.bytedeco.javacpp.maxbytes=48318382080" 
--conf spark.yarn.executor.memoryOverhead=49152 
--conf spark.locality.wait=0 
--conf spark.driver.maxResultSize=8g 
`

yarn.schduler.maximum-allocation-mb on the Cloudera cluster is set to 64GiB

**Comment by psuszyns** [comment]
It looks like using spark-submit arguments:

`
--master yarn --executor-cores 8 --driver-memory 10g --executor-memory 10g --num-executors 5 --deploy-mode cluster --conf "spark.executor.extraJavaOptions=-Dorg.bytedeco.javacpp.maxbytes=23622320128" --conf "spark.driver.extraJavaOptions=-Dorg.bytedeco.javacpp.maxbytes=23622320128" --conf "spark.executor.extraJavaOptions=-Dorg.bytedeco.javacpp.maxphysicalbytes=48318382080" --conf "spark.driver.extraJavaOptions=-Dorg.bytedeco.javacpp.maxphysicalbytes=48318382080" --conf spark.yarn.executor.memoryOverhead=49152 --conf spark.locality.wait=0 --conf spark.driver.maxResultSize=8g 
`

helped (although testing this on a really bigger dataset is still ahead of me). I think that the information at https://deeplearning4j.org/spark#memory3 should be updated because it is important to also set org.bytedeco.javacpp.maxphysicalbytes not only org.bytedeco.javacpp.maxbytes

**Comment by saudet** [comment]
Just set `spark.executor.memory` in addition to `spark.yarn.executor.memoryOverhead`. You shouldn't need to set anything else.

**Comment by psuszyns** [comment]
I was already using --executor-memory 10g. You comment contradicts https://deeplearning4j.org/spark#memory3 My experimets work after setting `org.bytedeco.javacpp.maxphysicalbytes` but previously they were failing

**Comment by saudet** [comment]
Right, so 10g, "physicalBytes = 20594274304" -> You're already using 20g. If you need more, you could simply increase the 10g there. And yes, the documentation needs updating.

**Comment by psuszyns** [comment]
Well I've been using various other configs including --executor-memory 55g and it didn't work.

In https://deeplearning4j.org/spark#memory3 you can find an example:

`--class my.class.name.here --num-executors 4 --executor-cores 8 --executor-memory 4G --driver-memory 4G --conf "spark.executor.extraJavaOptions=-Dorg.bytedeco.javacpp.maxbytes=5368709120" --conf "spark.driver.extraJavaOptions=-Dorg.bytedeco.javacpp.maxbytes=5368709120" --conf spark.yarn.executor.memoryOverhead=6144`

and a comment:

> The total off-heap memory is 5+1=6GB; the total memory (JVM + off-heap/overhead) is 4+6=10GB, which is less than the YARN maximum allocation of 11GB. Note that the JavaCPP memory is specified in bytes, and 5GB is 5,368,709,120 bytes; YARN memory overhead is specified in MB, and 6GB is 6,144MB.

In my configuration the total memory (JVM + off-heap/overhead) is 10+48=58GB and it is lower than the YARN maximum allocation which is in my case 64GB. `org.bytedeco.javacpp.maxbytes=23622320128` equals 22GB which is lower than 48GB and this is ok.

With these settings (following documentation + setting also _org.bytedeco.javacpp.maxphysicalbytes_) it works, with what you propose (simply increasing --executor-memory) it doesn't.

**Comment by raver119** [comment]
Closing this issue as outdated/stalled: too much changes were applied since it was opened first.
