### ISSUE TITLE
AbstractMethodError when running word2Vec.train(corpus);

### ISSUE THREAD

**Issue by jobernberger** [deeplearning4j/deeplearning4j#2199]
Hi all - been trying to run Word2Vec training on a spark2 cluster with YARN (specifically CDH running their spark2 beta).  Code looks like:
------------
Word2Vec word2Vec = new Word2Vec.Builder()
                .setNGrams(1)
                .tokenizerFactory(t)
                .seed(42L)
                .negative(10)
                .useAdaGrad(false)
                .layerSize(150)
                .windowSize(5)
                .learningRate(0.025)
                .minLearningRate(0.0001)
                .iterations(1)
                .batchSize(100)
                .minWordFrequency(5)
                .stopWords(Arrays.asList("three"))
                .useUnknown(true)
                .build();

        try {
            word2Vec.train(corpus);
        } catch (Exception ex) {
            System.out.println("Error training corpus: " + ex);
        }
-----------------------------
The error that I'm getting is:
java.lang.AbstractMethodError: org.deeplearning4j.spark.models.embeddings.word2vec.FirstIterationFunction.call(Ljava/lang/Object;)Ljava/util/Iterator;
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:152)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:152)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:779)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:779)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

The corpus is a JavaRDD<String> from a text file stored in HDFS.
Other parameters set are:
sparkConf.set("spark.network.timeout", "3600s");
sparkConf.set("spark.executor.heartbeatInterval", "50000s");

This is being run on 2 nodes running Scientific Linux 7.2 with ldd (GNU libc) 2.17.

Pom.xml contains:
<dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>0.6.0</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>dl4j-spark_2.11</artifactId>
            <version>0.6.0</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>dl4j-spark-nlp_2.11</artifactId>
            <version>0.6.0</version>
        </dependency>

Thank you for any ideas!
-Joe

**Comment by jobernberger** [comment]
This happened because I was using spark 2.0 which requires the use of an Iterator instead of Iteraable.
