### ISSUE TITLE
Maxout layer activation function not supported

### ISSUE THREAD

**Issue by ashgh** [deeplearning4j/deeplearning4j#2259]
I tried to create a neural network layer with a maxout activation function. See that it is currently unsupported. Creating an issue for tracking purposes. 

```
Exception in thread "main" java.lang.UnsupportedOperationException
	at org.nd4j.linalg.api.ops.impl.transforms.MaxOut.opNum(MaxOut.java:60)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:531)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:55)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.execAndReturn(DefaultOpExecutioner.java:178)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:366)
```

**Comment by AlexDBlack** [comment]
Closing this to avoid duplicate with this issue here: https://github.com/deeplearning4j/deeplearning4j/issues/2539

Maxout isn't yet implemented, but the first enabling step (refactoring) has been completed.
