### ISSUE TITLE
ParallelWrapper causes OOM Error

### ISSUE THREAD

**Issue by daanvdn** [deeplearning4j/deeplearning4j#2262]
Hi,

A question about the ParallelWrapper. I have been training a MultiLayerNetwork for time series-data and am feeding data to it using the CSVSequenceRecordReader. My configuration is as follows:

`public class MyClass{

		private final nIn = 21382;
		private final  = getHiddenLayerInputSizes(nIn);

		private List<Integer> getHiddenLayerInputSizes(int totalNrOfFeatures) {

				List<Integer> sizes = Lists.newArrayListWithCapacity(4);
				int first = totalNrOfFeatures / 10;
				sizes.add(first);
				int second = first / 2;
				sizes.add(second);
				int third = second / 5;
				sizes.add(third);
				int fourth = third / 10;
				sizes.add(fourth);
				return sizes;

			}

		private MultiLayerNetwork configureNetwork() {
				
				AtomicInteger layerIndex = new AtomicInteger(0);
				MultiLayerConfiguration conf =
						new NeuralNetConfiguration.Builder().optimizationAlgo(OptimizationAlgorithm
								.STOCHASTIC_GRADIENT_DESCENT)
								.iterations(1)
								.learningRate(0.1)
								.rmsDecay(0.95)
								.seed(12345)
								.regularization(true)
								.l2(0.001)
								.weightInit(WeightInit.XAVIER)
								.updater(Updater.RMSPROP)
								.list()
								.layer(0, new GravesLSTM.Builder().nIn(nIn)
										.nOut(hiddenLayerSizes.get(layerIndex.intValue()))
										.activation("tanh")
										.build())
								.layer(1, new GravesLSTM.Builder().nIn(hiddenLayerSizes.get(layerIndex.intValue()))
										.nOut(hiddenLayerSizes.get(layerIndex.incrementAndGet()))
										.activation("tanh")
										.build())
								.layer(2, new GravesLSTM.Builder().nIn(hiddenLayerSizes.get(layerIndex.intValue()))
										.nOut(hiddenLayerSizes.get(layerIndex.incrementAndGet()))
										.activation("tanh")
										.build())
								.layer(3, new GravesLSTM.Builder().nIn(hiddenLayerSizes.get(layerIndex.intValue()))
										.nOut(hiddenLayerSizes.get(layerIndex.incrementAndGet()))
										.activation("tanh")
										.build())
								.layer(4, new RnnOutputLayer.Builder(LossFunctions.LossFunction.MCXENT).activation("softmax")
										.nIn(hiddenLayerSizes.get(layerIndex.intValue()))
										.nOut(nrOfLabels)
										.build())
								.backpropType(BackpropType.Standard)
								.pretrain(false)
								.backprop(true)
								.build();
				MultiLayerNetwork net = new MultiLayerNetwork(conf);
				net.init();

				List<IterationListener> listeners = new ArrayList<>();
				listeners.add(new ScoreIterationListener(1)); 
				net.setListeners(listeners);
				return net;
			}
}`

I have been able to run it (using -Xmx5g), but training takes a long time (+8 days, which probably makes sense, since I have a network with 3 hidden layers and I'm processing over 5 billion data points for training). To speed up things, I wanted to give the ParallelWrapper a try. I configured the wrapper like this:
`public ParallelWrapper getWrapper(MultiLayerNetwork net){
          ParallelWrapper wrapper = new ParallelWrapper.Builder(net).prefetchBuffer(6).workers(6)
				    .averagingFrequency(1)
				    .reportScoreAfterAveraging(true)
				    .useLegacyAveraging(false)
				    .build();
      }`
 
However, when I try to run my application, constantly get an OOM error. The stacktrace is the following:

`Exception in thread "ParallelWrapper trainer 0" java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(136416605), totalBytes = 9178936574, physicalBytes = 12142575616
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:76)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:454)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:57)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:238)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1277)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:262)
	at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:125)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createUninitialized(CpuNDArrayFactory.java:253)
	at org.nd4j.linalg.factory.Nd4j.createUninitialized(Nd4j.java:4391)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.initGradientsView(MultiLayerNetwork.java:450)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.calcBackpropGradients(MultiLayerNetwork.java:1100)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.backprop(MultiLayerNetwork.java:1085)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1826)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:152)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:54)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1453)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1490)
	at org.deeplearning4j.parallelism.ParallelWrapper$Trainer.run(ParallelWrapper.java:444)
Caused by: java.lang.OutOfMemoryError: Cannot allocate 9178936574 + 545666420 bytes (> Pointer.maxBytes)
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:543)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
	at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
	... 18 more`

I have played around with the sizes of the  ``prefetchBuffer`` and ``workers`` and obviously I have tried giving it more memory. On a windows server with 24gb of RAM, 2 physical CPUs and 24 cores, I cannot get it to run with 2 ``workers``, a ``prefetchBuffer`` of either 2 or 0 and 20gb of memory. I *am* able to run it on a linux machine (total of 2 physical cpus, 32 cores, 125gb RAM), but only if i give my process 50gb of memory. Moreover, I have the impression that the ParallelWrapper is relatively slow: using 6 ``workers`` and a ``prefetchBuffer`` of 6 it takes 10 hours to finish a single epoch. Setting OMP_NUM_THREADS=1 makes everything much slower. So my question basically is: is the described behaviour of the ParallelWrapper w.r.t memory consumption and speed as expected? If not, is there a direction in which anybody could point me to solve this problem? Thanks!

**Comment by raver119** [comment]
Right now ParallelWrapper does copy initial model within worker threads. Obviously this gives one spare model that's not really used - initial one.

That should be changed, so one of the threads, say first one, will be using that model, while others will be using copies.

**Comment by raver119** [comment]
This will also address absence of listeners within pw.
