### ISSUE TITLE
IllegalStateException during training a CNN model with DL4J

### ISSUE THREAD

**Issue by okaradeli** [deeplearning4j/deeplearning4j#2293]
I am getting the following exception.
I got support from gitter from Alex and raver119 but they mentioned this could be a bug.
So opening this TICKET,
We are stuck here so we would be really grateful for the help.

BR 
Onur

o.d.e.c.DLAgeGender - Train model....
Exception in thread "main" java.lang.IllegalStateException: Column of left array 336 != rows of right 384 or rows of left array 1 != columns of right 2
	at org.nd4j.linalg.util.LinAlgExceptions.assertMultiplies(LinAlgExceptions.java:85)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2635)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2501)
	at org.deeplearning4j.nn.layers.BaseLayer.preOutput(BaseLayer.java:354)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.preOutput2d(BaseOutputLayer.java:401)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.backpropGradient(BaseOutputLayer.java:151)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.calcBackpropGradients(MultiLayerNetwork.java:1133)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.backprop(MultiLayerNetwork.java:1085)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1826)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:152)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:54)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1075)
	at org.deeplearning4j.examples.convolution.DLAgeGender.main(DLAgeGender.java:221)

Here is the model and dataiterator files

[DL4J_AgeGender.zip](https://github.com/deeplearning4j/deeplearning4j/files/580788/DL4J_AgeGender.zip)

**Comment by okaradeli** [comment]
During my trial & fail sessions i found out that the parameter orders should be different for input and model config.

In the model 
            .setInputType(InputType.convolutional(height,width,nChannels))

where as in the INDArray matrix SHOULD BE  
   INDArray weekMatrix = Nd4j.ones(new int[]{1,DLAgeGender.nChannels,DLAgeGender.height,DLAgeGender.width});

This solved the above error. Two questions:
1- Is this solution correct
2- Is it possible to make the error messages a bit expressive ? 

Thanks for the support.
