### ISSUE TITLE
NPE while fitting with jcublas

### ISSUE THREAD

**Issue by paulheideman** [deeplearning4j/deeplearning4j#230]
I've made a simple scala example based off the MNIST code in the examples.  The code works with jblas, but I get a null pointer exception with jcublas-7.0.

```scala
object Main {
  def main(args: Array[String]) = {
    Nd4j.dtype = DataBuffer.FLOAT
    println("Creating network")
    val conf = new NeuralNetConfiguration.Builder()
      .momentum(0.5).layerFactory(LayerFactories.getFactory(classOf[RBM]))
      .momentumAfter(Map(new Integer(3) -> new JDouble(0.9))).optimizationAlgo(OptimizationAlgorithm.CONJUGATE_GRADIENT)
      .iterations(5).weightInit(WeightInit.DISTRIBUTION)
      .dist(Nd4j.getDistributions().createUniform(0, 1)).iterationListener(new ScoreIterationListener(1))
      .lossFunction(LossFunctions.LossFunction.RMSE_XENT)
      .learningRate(1e-1f).nIn(784).nOut(10).list(4)
      .hiddenLayerSizes(500, 250, 200).`override`(new ClassifierOverride(3))
      .build
    val d = new MultiLayerNetwork(conf)
    println("Getting MNIST")
    val iter = new MnistDataSetIterator(100,1000)
    println("Fitting")
    iter foreach d.fit
    iter.reset
    val eval = new Evaluation

    println("Evaluating")
    iter foreach {
      d2 =>
        val predict2 = d.output(d2.getFeatureMatrix)
        eval.eval(d2.getLabels, predict2)
    }

    println(eval.stats)
  }
}
```

Stack trace:
```
java.lang.NullPointerException
	at org.nd4j.linalg.lossfunctions.LossFunctions.score(LossFunctions.java:69)
	at org.deeplearning4j.nn.layers.BasePretrainNetwork.setScore(BasePretrainNetwork.java:65)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:116)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:131)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:44)
	at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:306)
	at org.deeplearning4j.models.featuredetectors.rbm.RBM.fit(RBM.java:400)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:212)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1095)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1123)
        ...
```

Any ideas?

**Comment by agibsonccc** [comment]
Closing this. This is currently being worked on:
https://github.com/deeplearning4j/nd4j/issues/74

All of these issues fall in to the same boat of: Get GPUs with multiple threads, no memory leaking and optimal speed working.
