### ISSUE TITLE
RecordReaderMultiDataSetIterator not working with ImageRecordReader

### ISSUE THREAD

**Issue by ambraspace** [deeplearning4j/deeplearning4j#2305]
It seems that `RecordReaderMultiDataSetIterator` is not working properly with `ImageRecordReader`s.
Here's my setup:
```java
        File parentDir = new File("/home/user/training-images/");
        FileSplit filesInDir = new FileSplit(parentDir, new String[]{"png"}, randNumGen);
        
        ParentPathLabelGenerator labelMaker = new ParentPathLabelGenerator();

        BalancedPathFilter pathFilter = new BalancedPathFilter(
        		randNumGen,
        		new String[]{"png"},
        		labelMaker, 2000);

        InputSplit[] filesInDirSplit = filesInDir.sample(pathFilter, 80, 20);
        InputSplit trainData = filesInDirSplit[0];
        InputSplit testData = filesInDirSplit[1];
        
        ImageRecordReader rr1 = new ImageRecordReader(10, 10, 1, labelMaker);
        ImageRecordReader rr1s = new ImageRecordReader(5, 5, 1, labelMaker);

        try {
			rr1.initialize(trainData);
			rr1s.initialize(trainData);
		} catch (IOException e1) {
			e1.printStackTrace();
		}

        
        MultiDataSetIterator trainDataIterator = new RecordReaderMultiDataSetIterator.Builder(1)
        		.addReader("rr1", rr1)
        		.addReader("rr1s", rr1s)
        		.addInput("rr1", 0, 0)
        		.addInput("rr1s", 0, 0)
        		.addOutputOneHot("rr1s", 1, outputNum)
        		.build();
        
        MultiDataSet mds = trainDataIterator.next();
        mds.toString();
```
The line before the last one fails with:
```
Exception in thread "main" java.lang.IllegalStateException: Mis matched lengths: [1] != [100]
	at org.nd4j.linalg.util.LinAlgExceptions.assertSameLength(LinAlgExceptions.java:39)
	at org.nd4j.linalg.api.ops.BaseTransformOp.<init>(BaseTransformOp.java:48)
	at org.nd4j.linalg.api.ops.impl.transforms.Set.<init>(Set.java:25)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:1126)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.put(BaseNDArray.java:1837)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putRow(BaseNDArray.java:3414)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritables(RecordReaderMultiDataSetIterator.java:302)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:212)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:163)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:101)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:55)
```
I tried to investigate this and found the following:
- rr1 and rr1s return the same file in every iteration
- all examples and unit test classes deal with CSV readers (so I don't have any references to see if my code is wrong)
- it seems that `ImageRecordReader`s are "one level deeper" because appending of the labels, so these lines:
```java
        if(details.entireReader) arr = Nd4j.create(minValues, list.get(0).size());
        else if(details.oneHot) arr = Nd4j.zeros(minValues, details.oneHotNumClasses);
        else arr = Nd4j.create(minValues, details.subsetEndInclusive-details.subsetStart + 1);
```
in `RecordReaderMultiDataSetIterator.convertWritables(List<List<Writable>> list, int minValues, SubsetDetails details )` create `INDArray` with size 1×1.
This is my "list" inside this method:
```
[[[[[[52.00, 139.00, 158.00, 174.00, 165.00, 164.00, 174.00, 146.00, 108.00, 35.00],
   [81.00, 103.00, 132.00, 138.00, 157.00, 141.00, 133.00, 119.00, 84.00, 65.00],
   [124.00, 112.00, 63.00, 56.00, 121.00, 65.00, 44.00, 56.00, 60.00, 83.00],
   [143.00, 165.00, 190.00, 157.00, 197.00, 158.00, 140.00, 144.00, 125.00, 84.00],
   [176.00, 140.00, 161.00, 140.00, 207.00, 123.00, 146.00, 136.00, 95.00, 77.00],
   [177.00, 109.00, 106.00, 152.00, 128.00, 101.00, 118.00, 96.00, 87.00, 71.00],
   [215.00, 101.00, 98.00, 142.00, 72.00, 76.00, 106.00, 89.00, 90.00, 39.00],
   [220.00, 109.00, 123.00, 98.00, 91.00, 77.00, 76.00, 93.00, 93.00, 58.00],
   [219.00, 206.00, 122.00, 105.00, 100.00, 95.00, 97.00, 105.00, 39.00, 36.00],
   [176.00, 160.00, 67.00, 122.00, 103.00, 86.00, 119.00, 40.00, 52.00, 44.00]]]], 0]]
```
It seems that the first line above should call `list.get(0).get(0).size()`, but this would probably screw up things with other readers.

Regards!

**Comment by AlexDBlack** [comment]
Thanks for reporting.
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2312
