### ISSUE TITLE
Word2Vec Upsert Training: Illegal point -11686

### ISSUE THREAD

**Issue by KonceptGeek** [deeplearning4j/deeplearning4j#2332]
When the Word2Vec model is reloaded and trained with new data, it throws and IllegalStateException: Illegal point -11686
`
Exception in thread "VectorCalculationsThread 3" java.lang.RuntimeException: java.lang.IllegalStateException: Illegal point -11686
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:965)
Caused by: java.lang.IllegalStateException: Illegal point -11686
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:193)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.skipGram(SkipGram.java:168)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.learnSequence(SkipGram.java:138)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:225)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:940)
`

The code for loading the persisted model is:
`
Word2Vec word2Vec = WordVectorSerializer.readWord2Vec(new File(modelPath));
((InMemoryLookupTable) word2Vec.getLookupTable()).setNegative(5.0);
word2Vec.getLookupTable().resetWeights(false);
`

And the code for training the model is:
`
word2Vec.setTokenizerFactory(getTokenizerFactory());
word2Vec.setSentenceIter(new CollectionSentenceIterator(content)); //content is a list of strings
word2Vec.fit();
`

**Comment by raver119** [comment]
Issue was discussed in pm + additional test + few checks were added.
