### ISSUE TITLE
Remote UI fails with HTTP 413

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#2342]
Getting an HTTP entity too large error when using the remote router for the UI server:

```
Caused by: java.io.IOException: Server returned HTTP response code: 413 for URL: http://localhost:9000/remoteReceive
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.deeplearning4j.api.storage.impl.RemoteUIStatsStorageRouter.tryPost(RemoteUIStatsStorageRouter.java:288)
	... 4 more
java.io.IOException: Server returned HTTP response code: 413 for URL: http://localhost:9000/remoteReceive
```

@AlexDBlack any ideas here? I assume there's a post body max bytes setting somewhere in Play.

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2343

I was able to reproduce this with a 1000 layer network; same network works OK after the config change.
