### ISSUE TITLE
ImageLoad.asMatrix(BufferedImage) throws exception, mixes width and height for getRGB

### ISSUE THREAD

**Issue by thhart** [deeplearning4j/deeplearning4j#2349]
In the loop in this method i has to iterate till w and j has to iterate till h.

```
         int w = image.getWidth();
         int h = image.getHeight();
         INDArray ret = Nd4j.create(h, w);

         for(int i = 0; i < h; ++i) {
            for(int j = 0; j < w; ++j) {
               ret.putScalar(new int[]{i, j}, image.getRGB(i, j));
            }
         }

```

```
java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
	at sun.awt.image.ByteInterleavedRaster.getDataElements(ByteInterleavedRaster.java:318) ~[na:1.8.0_111]
	at java.awt.image.BufferedImage.getRGB(BufferedImage.java:917) ~[na:1.8.0_111]
	at org.datavec.image.loader.ImageLoader.asMatrix(ImageLoader.java:269) ~[datavec-data-image-0.6.0.jar:na]

```

**Comment by raver119** [comment]
Please, use NativeImageLoader

**Comment by raver119** [comment]
And in other words, image.getRGB() params should be used in different order. Loop itself is ok.
