### ISSUE TITLE
mvn exec:java alway get the warning "java.lang.RuntimeException: java.lang.InterruptedException: sleep interrupted"

### ISSUE THREAD

**Issue by yylonly** [deeplearning4j/deeplearning4j#2376]
i alway use meavn to running my code. just like:
`mvn exec:java -Dexec.mainClass="net.mydreamy.encrpyed.ministdes.TranningEncrypedDESMinistMultiGPUFFSingle"`

I will get following warnning when finishing train the network.

> [WARNING] 
[WARNING] 
[WARNING] 
[WARNING] 
java.lang.RuntimeException: java.lang.InterruptedException: sleep interrupted
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool$ResourceGarbageCollectorThread.run(LimitedContextPool.java:198)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool$ResourceGarbageCollectorThread.run(LimitedContextPool.java:196)
java.lang.RuntimeException: java.lang.InterruptedException: sleep interrupted
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool$ResourceGarbageCollectorThread.run(LimitedContextPool.java:198)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool$ResourceGarbageCollectorThread.run(LimitedContextPool.java:196)
java.lang.RuntimeException: java.lang.InterruptedException: sleep interrupted
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool$ResourceGarbageCollectorThread.run(LimitedContextPool.java:198)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool$ResourceGarbageCollectorThread.run(LimitedContextPool.java:196)
java.lang.RuntimeException: java.lang.InterruptedException: sleep interrupted
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool$ResourceGarbageCollectorThread.run(LimitedContextPool.java:198)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool$ResourceGarbageCollectorThread.run(LimitedContextPool.java:196)
[WARNING] thread Thread[UniGC thread 0,5,net.mydreamy.encrpyed.ministdes.TranningEncrypedDESMinistMultiGPUFFSingle] was interrupted but is still alive after waiting at least 14997msecs
[WARNING] thread Thread[UniGC thread 0,5,net.mydreamy.encrpyed.ministdes.TranningEncrypedDESMinistMultiGPUFFSingle] will linger despite being asked to die via interruption
[WARNING] thread Thread[UniGC thread 1,5,net.mydreamy.encrpyed.ministdes.TranningEncrypedDESMinistMultiGPUFFSingle] will linger despite being asked to die via interruption
[WARNING] thread Thread[UniGC thread 2,5,net.mydreamy.encrpyed.ministdes.TranningEncrypedDESMinistMultiGPUFFSingle] will linger despite being asked to die via interruption
[WARNING] thread Thread[UniGC thread 3,5,net.mydreamy.encrpyed.ministdes.TranningEncrypedDESMinistMultiGPUFFSingle] will linger despite being asked to die via interruption
[WARNING] thread Thread[UniGC thread 4,5,net.mydreamy.encrpyed.ministdes.TranningEncrypedDESMinistMultiGPUFFSingle] will linger despite being asked to die via interruption
[WARNING] thread Thread[UniGC thread 5,5,net.mydreamy.encrpyed.ministdes.TranningEncrypedDESMinistMultiGPUFFSingle] will linger despite being asked to die via interruption
[WARNING] thread Thread[NativeRandomDeallocator thread 0,5,net.mydreamy.encrpyed.ministdes.TranningEncrypedDESMinistMultiGPUFFSingle] will linger despite being asked to die via interruption
[WARNING] NOTE: 7 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=net.mydreamy.encrpyed.ministdes.TranningEncrypedDESMinistMultiGPUFFSingle,maxpri=10]
java.lang.IllegalThreadStateException
	at java.lang.ThreadGroup.destroy(ThreadGroup.java:778)
	at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:328)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23:19 min
[INFO] Finished at: 2016-11-26T00:31:04+08:00
[INFO] Final Memory: 164M/11140M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:java (default-cli) on project net.mydreamy.encrpyed.ministdes: An exception occured while executing the Java class. java.lang.InterruptedException: sleep interrupted -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

That does not affect the result.  But really anoying.

**Comment by raver119** [comment]
Good point. I've removed that exception, it was used during debug only, and pretty useless now.
