### ISSUE TITLE
v0.7.0 with Cuda: IllegalStateException: Queue full

### ISSUE THREAD

**Issue by mjakobus** [deeplearning4j/deeplearning4j#2397]
Hi,

when using the DoublesDataSetIterator with the cuda 7.5 backend the internal AsyncDataSetIterator of the MultiLayerNetwork is throwing an Exception when calling fit():

```
Exception in thread "main" java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(AbstractQueue.java:98)
	at org.deeplearning4j.datasets.iterator.AbstractDataSetIterator.fillQueue(AbstractDataSetIterator.java:208)
	at org.deeplearning4j.datasets.iterator.AbstractDataSetIterator.hasNext(AbstractDataSetIterator.java:163)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$IteratorRunnable.hasLatch(AsyncDataSetIterator.java:283)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.hasNext(AsyncDataSetIterator.java:186)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1064)
	at com.simple.example.MainSimpleExample.main(MainSimpleExample.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**System details:**
- Deeplearning4j, nd4j, datavec version: 0.7.0
- Cuda Version 7.5
- Graphics Card: Nvidia Geforce GTX 950 with 2048MB
- Windows 10

**Condensed setup of my program (for reproducing the exception):**
https://gist.github.com/mjakobus/7383188532aec6c841e9ed68f96f1902

**Complete output log:**
https://gist.github.com/mjakobus/e53277e19ccf2c3030e7a015a76fdeeb

Best regards and keep up the good work!
Martin

**Comment by raver119** [comment]
I'm not sure now, how is it possible to get this exception. Looks like double spending for, so requires investigation.

I'll triage it for now, and will do detailed investigation after 0.7.1 gets released.
