### ISSUE TITLE
Need a little help setting up

### ISSUE THREAD

**Issue by shenkev** [deeplearning4j/deeplearning4j#2398]
Hi there,

I've been trying to set up dl4j and nd4j in my existing project for a few hours now, and it's getting frustrating. I would really appreciate it if I could get a bit of help. As it stands, I converted my project to a Maven project (I'm working in Eclipse).

My pom.xml contains:
```
    <dependency>
	   <groupId>org.nd4j</groupId>
	   <artifactId>nd4j-native-platform</artifactId>
	   <version>${nd4j.version}</version>
    </dependency>  
    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-nlp</artifactId>
        <version>${dl4j.version}</version>
    </dependency>  
    
    <dependency>
	     <groupId>org.deeplearning4j</groupId>
	     <artifactId>deeplearning4j-core</artifactId>
	     <version>${deeplearning4j.version}</version>
	</dependency>

    <properties>
    	<nd4j.version>0.4.0</nd4j.version>
        <nd4j.backend>nd4j-native-platform</nd4j.backend>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <shadedClassifier>bin</shadedClassifier>
        <java.version>1.8</java.version>
        <nd4j.version>0.7.0</nd4j.version>
        <deeplearning4j.version>0.7.0</deeplearning4j.version>
        <dl4j.version>0.7.0</dl4j.version>
        <datavec.version>0.7.0</datavec.version>
        <arbiter.version>0.7.0</arbiter.version>
        <guava.version>19.0</guava.version>
        <logback.version>1.1.7</logback.version>
        <jfreechart.version>1.0.13</jfreechart.version>
        <jcommon.version>1.0.23</jcommon.version>
        <maven-shade-plugin.version>2.4.3</maven-shade-plugin.version>
        <exec-maven-plugin.version>1.4.0</exec-maven-plugin.version>
        <maven.minimum.version>3.3.1</maven.minimum.version>
    </properties>
```

I'm able to write code using dl4j and nd4j without Eclipse complaining (no red wriggly underlines). However, when I try to run my project, I get errors:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:16)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:9)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:38)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5441)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5351)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:183)
	at dl4jImplementation.offlineTrain.main(offlineTrain.java:41)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOps.<clinit>(NativeOps.java:39)
	... 12 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4j in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:784)
	at org.bytedeco.javacpp.Loader.load(Loader.java:586)
	at org.nd4j.nativeblas.NativeOps.<clinit>(NativeOps.java:37)
	... 12 more
Caused by: java.lang.UnsatisfiedLinkError: no nd4j in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:784)
	at org.bytedeco.javacpp.Loader.load(Loader.java:577)
	... 13 more
```

**Comment by raver119** [comment]
Helped in gitter.

**Comment by agibsonccc** [comment]
Usual answer to this for search results, follow our example versions:
https://github.com/deeplearning4j/dl4j-examples
