### ISSUE TITLE
StaticWord2vec.lookupTable : java.lang.UnsupportedOperationException: Method isn't implemented

### ISSUE THREAD

**Issue by superbug7** [deeplearning4j/deeplearning4j#2400]
While trying to run Word2vecSentimentimentRNN example with 0.7 version, I get this error. I just moved from 0.5 on which it was working fine, but I need staticWord2vec implementation for this example to work with GPUs.
Exception in thread "main" java.lang.UnsupportedOperationException: Method isn't implemented. Please use usual Word2Vec implementation
at org.deeplearning4j.models.word2vec.StaticWord2Vec.lookupTable(StaticWord2Vec.java:306)
at org.deeplearning4j.examples.recurrent.word2vecsentiment.SentimentExampleIterator.<init>(SentimentExampleIterator.java:53)
at org.deeplearning4j.examples.recurrent.word2vecsentiment.Word2VecSentimentRNN.main(Word2VecSentimentRNN.java:99)

**Comment by raver119** [comment]
As far as i know issue was fixed few releases ago.
