### ISSUE TITLE
RuntimeException occurs when using RBM/AutoEncoder layers with InMemoryStatsStorage Listener

### ISSUE THREAD

**Issue by iManinesan** [deeplearning4j/deeplearning4j#2412]
I have created a MultiLayerNetwork model with AutoEncoder layers, it works fine when I'm training it without adding a StatsListener of InMemoryStatsStorage for UIserver visualization purpose.

But an exception occurs if I add these lines,
 StatsStorage statsStorage = new InMemoryStatsStorage();
 model.setListeners(new StatsListener(statsStorage));

Exception happens like this:
Exception in thread "main" java.lang.RuntimeException: Invalid model: Expected MultiLayerNetwork or ComputationGraph. Got: class org.deeplearning4j.nn.layers.feedforward.autoencoder.AutoEncoder
	at org.deeplearning4j.ui.stats.StatsListener.doInit(StatsListener.java:556)
	at org.deeplearning4j.ui.stats.StatsListener.iterationDone(StatsListener.java:228)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:227)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:545)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:232)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1481)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1461)
	at org.taz.core.autoencoder.AutoEncoderTest.main(AutoEncoderTest.java:93)

p.s: I'm new to deeplearning4j. if I'm doing it wrongly, please point it out.

**Comment by AlexDBlack** [comment]
No, this is an oversight in the new UI. As of 0.7.1 it does not function with unsupervised layers like RBMs.

**Comment by agibsonccc** [comment]
Did we fix this?

**Comment by eraly** [comment]
We are dropping support for RBMs in favour of newer and more effective methods. Please take a look at variational autoencoders 
https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/unsupervised/variational
