### ISSUE TITLE
Kryo serialization + spark + stats collection requires kryo registrator?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2424]
It appears that Kryo serialization and the SBE/Agrona-based objects (i.e., stats storage objects via StatsListener) are incompatible (probably due to agrona buffers etc).
It is likely necessary to implement a kyro registrator for this, similar to what we have for ND4J.

```
Serialization trace:
listenerMetaData (org.deeplearning4j.spark.impl.paramavg.aggregator.ParameterAveragingAggregationTuple)
        at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:626)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:729)
        at org.apache.spark.serializer.KryoSerializerInstance.deserialize(KryoSerializer.scala:311)
        at org.apache.spark.scheduler.DirectTaskResult.value(TaskResult.scala:97)
        at org.apache.spark.scheduler.TaskResultGetter$$anon$2$$anonfun$run$1.apply$mcV$sp(TaskResultGetter.scala:60)
        at org.apache.spark.scheduler.TaskResultGetter$$anon$2$$anonfun$run$1.apply(TaskResultGetter.scala:51)
        at org.apache.spark.scheduler.TaskResultGetter$$anon$2$$anonfun$run$1.apply(TaskResultGetter.scala:51)
        at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1817)
        at org.apache.spark.scheduler.TaskResultGetter$$anon$2.run(TaskResultGetter.scala:50)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at java.util.Collections$SynchronizedCollection.add(Collections.java:2035)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:109)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:18)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:648)
        at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:605)
        ... 12 more
```

**Comment by agibsonccc** [comment]
Workaround: Use J7StatsListener

**Comment by AlexDBlack** [comment]
Turns out: this was due do Kryo not being able to handle Collections.synchronizedList(...) by default :/

https://github.com/deeplearning4j/deeplearning4j/pull/2750
