### ISSUE TITLE
word2vec stream closed exception

### ISSUE THREAD

**Issue by xuzhongxing** [deeplearning4j/deeplearning4j#2431]
dl4j 0.7.0 and 0.7.1

The problem is not deterministic. It can be fixed by adding .allowParallelTokenization(false) to the builder.

source code:
```
public static void main(String[] args) {
        File file = new File(args[0]);
        System.out.println(args[0]);

        SentenceIterator iter = new LineSentenceIterator(file);

        TokenizerFactory t = new DefaultTokenizerFactory();
        t.setTokenPreProcessor(new CommonPreprocessor());

        Word2Vec vec = new Word2Vec.Builder()
                .useHierarchicSoftmax(false)
                .negativeSample(5)
                .minWordFrequency(5)
                .iterations(1)
                .layerSize(100)
                .seed(42)
                .windowSize(5)
                .iterate(iter)
                .tokenizerFactory(t)
                .allowParallelTokenization(false)
                .build();

        vec.fit();
```
output:
```
11:01:36.313 [main] INFO  org.nd4j.nativeblas.NativeOps - Number of threads used for NativeOps: 4
11:01:36.357 [main] INFO  org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 4
11:01:36.470 [main] DEBUG org.reflections.Reflections - going to scan these urls:
jar:file:/opt/cerebro/lib/nd4j-native-0.7.0-linux-x86_64.jar!/
jar:file:/opt/cerebro/lib/nd4j-native-0.7.0-macosx-x86_64.jar!/
jar:file:/opt/cerebro/lib/jackson-0.7.0.jar!/
jar:file:/opt/cerebro/lib/nd4j-native-api-0.7.0.jar!/
jar:file:/opt/cerebro/lib/nd4j-api-0.7.0.jar!/
jar:file:/opt/cerebro/lib/nd4j-native-0.7.0.jar!/
jar:file:/opt/cerebro/lib/nd4j-buffer-0.7.0.jar!/
jar:file:/opt/cerebro/lib/nd4j-jackson-0.7.0.jar!/
jar:file:/opt/cerebro/lib/nd4j-native-0.7.0-linux-ppc64le.jar!/
jar:file:/opt/cerebro/lib/nd4j-common-0.7.0.jar!/
jar:file:/opt/cerebro/lib/nd4j-native-0.7.0-windows-x86_64.jar!/
jar:file:/opt/cerebro/lib/nd4j-context-0.7.0.jar!/
11:01:36.909 [main] INFO  org.reflections.Reflections - Reflections took 434 ms to scan 12 urls, producing 29 keys and 172 values 
Exception in thread "AsyncIterator Reader thread" java.lang.RuntimeException: java.lang.IllegalStateException: java.io.IOException: Stream closed
	at org.deeplearning4j.parallelism.AsyncIterator$ReaderThread.run(AsyncIterator.java:101)
Caused by: java.lang.IllegalStateException: java.io.IOException: Stream closed
	at org.apache.commons.io.LineIterator.hasNext(LineIterator.java:106)
	at org.deeplearning4j.text.sentenceiterator.LineSentenceIterator.hasNext(LineSentenceIterator.java:62)
	at org.deeplearning4j.text.sentenceiterator.interoperability.SentenceIteratorConverter.hasNextDocument(SentenceIteratorConverter.java:34)
	at org.deeplearning4j.text.documentiterator.BasicLabelAwareIterator.hasNextDocument(BasicLabelAwareIterator.java:34)
	at org.deeplearning4j.text.documentiterator.BasicLabelAwareIterator.hasNext(BasicLabelAwareIterator.java:63)
	at org.deeplearning4j.parallelism.AsyncIterator$ReaderThread.run(AsyncIterator.java:92)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:336)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at org.apache.commons.io.LineIterator.hasNext(LineIterator.java:95)
	... 5 more
11:01:37.568 [main] INFO  o.d.m.s.SequenceVectors - Starting vocabulary building...
```

**Comment by saudet** [comment]
Sounds like a known issue with 0.7.0. Please try again with 0.7.1.

**Comment by xuzhongxing** [comment]
In BasicTransformerIterator's ctor, AsyncLabelAwareIterator.reset() is called. AsyncIterator.shutdown() is called. Then backedIterator.reset() is called. At this moment, the backed file stream is closed. But AsyncIterator's ReadThread might still be running and reading from that file stream.

**Comment by xuzhongxing** [comment]
Pull request: https://github.com/deeplearning4j/deeplearning4j/pull/2433
