### ISSUE TITLE
ParaVectors.inferVector has issues inside of an rdd

### ISSUE THREAD

**Issue by dmmiller612** [deeplearning4j/deeplearning4j#2490]
I am running into an issue where ParagraphVector.inferVector is timing out inside of an rdd that has not had an operation performed on it yet (like collect, save, etc). First, I'll put the code here then explain the behavior.

loading google model
```
    public static WordVectors loadGoogleModel(String bucketName) throws Exception {
        S3Object s3Object = s3Client.getObject(bucketName, "spark/data/google.bin");
        File tmpFile = File.createTempFile("temp", "txt");
        tmpFile.deleteOnExit();
        FileUtils.copyInputStreamToFile(s3Object.getObjectContent(), tmpFile);
        return WordVectorSerializer.loadGoogleModel(tmpFile, true);
    }
```
converting to paragraph vector
```
    public static ParagraphVectors convertWordVectorsToParagraphVector(WordVectors wordVectors) {
        ParagraphVectors paragraphVectors = loadConfig(); // builder for paragraphVectors
        paragraphVectors.setLookupTable(wordVectors.lookupTable());
        paragraphVectors.setVocab(wordVectors.vocab());
        return paragraphVectors;
    }
```

Then in the main class:

```
final ParagraphVectors googleModel = loadGoogleModel(properties.getQualityBucket());
JavaRDD<String> message = //a non null rdd of strings here;
JavaRDD<INDArray> indArrayJavaRDD = rdd2.map(item -> googleModel.inferVector(item));
//timeout failure
```

What is weird is when I run this in yarn on the emr, I see no errors in the log, but the process fails. Locally, I consistently receive this error:

```
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
        at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:48)
        at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:63)
        at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:59)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
        at org.apache.spark.rpc.RpcEndpointRef.askWithRetry(RpcEndpointRef.scala:101)
        at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:449)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply$mcV$sp(Executor.scala:470)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply(Executor.scala:470)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply(Executor.scala:470)
        at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1765)
        at org.apache.spark.executor.Executor$$anon$1.run(Executor.scala:470)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.Await$.result(package.scala:107)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
        ... 14 more
```

What is weird to me about this is that I am not even sure what an operation is being ran inside of an rdd. I am guessing it is because googleModel.inferVector is the driver, and needs to operate first before being passed down to an executor.

This is also using spark-submit for the emr and locally.

**Comment by dmmiller612** [comment]
Also, when running this without spark, the paragraphvector.inferVector runs fine.

**Comment by raver119** [comment]
Please show me full function source.

**Comment by dmmiller612** [comment]
Are you referring to the JavaRDD<String> method. Or the whole class?

**Comment by raver119** [comment]
I'm asking for source code of Function which is called on your JavaRDD<String>. That Function where you call for inferVector()

**Comment by dmmiller612** [comment]
That's the thing. I never call it. As soon as I run 
```
JavaRDD<INDArray> indArrayJavaRDD = rdd2.map(item -> googleModel.inferVector(item));
```
it timesout.

**Comment by dmmiller612** [comment]
It may be easier with a full representation. I will create a gist, and remove some company specific things.

**Comment by raver119** [comment]
Cool, please also don't forget to include actual paravec configuration, and model sharing mechanism you've used.

**Comment by raver119** [comment]
Also, if you want to keep it private - you can always ping me in PM.

**Comment by dmmiller612** [comment]
Created a gist that can reproduce the issue @raver119 

https://gist.github.com/dmmiller612/48bd1dd83c99ad61badefe411147fa99

**Comment by raver119** [comment]
Is it supposed to run on localhost? or spark cluster assumed here?

**Comment by dmmiller612** [comment]
well, both probably. This particular example is local.

**Comment by dmmiller612** [comment]
```
mvn clean package
spark-submit --class com.inin.sparkscripts.jobs.DForJ --master local[2] --driver-memory 6g --executor-memory 4g target/jarFile.jar
```

**Comment by raver119** [comment]
Ok. My concern is this line: JavaRDD<INDArray> indArrayJavaRDD = stuff.map(item -> googleModel.inferVector(item));

I'm not sure how lambda compiler will introduce this function in bytecode, and i wonder, if it tries to serialize your model. Which should be around 4GB unpacked.

**Comment by dmmiller612** [comment]
I'll try adding more memory to the executor(s). I can also try just making it a normal Java 7 function. I will add updates, once I get results.

**Comment by dmmiller612** [comment]
changing to a normal java function and upping the memory caused the same error to happen.

```
        JavaRDD<String> stuff = SparkConfig.getSparkContext().parallelize(tonsOfStrings());
        final ParagraphVectors googleModel = loadGoogleModel(properties.getQualityBucket());
        JavaRDD<INDArray> indArrayJavaRDD = stuff.map(new Function<String, INDArray>() {
            @Override
            public INDArray call(String s) throws Exception {
                return googleModel.inferVector(s);
            }
        });
        return indArrayJavaRDD;
```

**Comment by raver119** [comment]
Can i see exception stack trace?

**Comment by dmmiller612** [comment]
Exception in thread "main" java.lang.OutOfMemoryError
        at java.io.ByteArrayOutputStream.hugeCapacity(ByteArrayOutputStream.java:123)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:117)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
        at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
        at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1189)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:44)
        at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:101)
        at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:301)
        at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:294)
        at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:122)
        at org.apache.spark.SparkContext.clean(SparkContext.scala:2055)
        at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:324)
        at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:323)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
        at org.apache.spark.rdd.RDD.map(RDD.scala:323)
        at org.apache.spark.api.java.JavaRDDLike$class.map(JavaRDDLike.scala:96)
        at org.apache.spark.api.java.AbstractJavaRDDLike.map(JavaRDDLike.scala:46)
        at com.inin.sparkscripts.jobs.DForJ.handleFeatures(DForJ.java:71)
        at com.inin.sparkscripts.jobs.DForJ.main(DForJ.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by dmmiller612** [comment]
it makes sense to me, I think. It is trying to actively serialize this massive google model to the executors. What has me a bit confused is the object is smaller than the amount of memory I give to an executor by a couple of gigs..

**Comment by dmmiller612** [comment]
So after doing some more research, it was a memory issue. I trained a much smaller dataset, and it got past that issue. On a side note, I don't ParagraphVectors prediction will ever work inside of an rdd unless several operations are made to set the tokenizerFactory. The tokenizerFactory in the Word2Vec class is transient, so I am constantly getting the error that "TokenizerFactory should be defined, prior to predict() call", since it isn't getting serialized.

**Comment by raver119** [comment]
Yes, but how much times it serializes it? once? once per executor? once per rdd entry? Code isn't obvious for me right now. I.e. if that would be broadcast - i would be able to say something, but right now it's more like your own issue with strange handling of huge object in spark  :)

As of tokenizer etc. The same actually - you shouldn't rely on non-obvious behavior in your pipeline. Issue broadcast with model manually, pick it up within your function, post-initialize it with tokenizer, and use it within function.

**Comment by raver119** [comment]
As of TokenizerFactory field being transient. I think you're right here, but that'll also rise requirement for TokenizerFactory being serializable as well. I'll check our default implementations, and will make that field serializable.

**Comment by dmmiller612** [comment]
Yeah, I didn't put it in a broadcast variable because the model is too large with the google news dataset and spark can't handle it, which is a known bug. I get the error message, "Size exceeds Integer.MAX_VALUE". I think I read that a broadcast variable at most can handle 2 gb from some threads I found on the issue.

**Comment by raver119** [comment]
So, it looks like it's not our issue at this moment. Feel free to reopen this issue, if you'll find that we could do something there.

**Comment by saritajoshi9389** [comment]
I am struggling to find a way to solve this issue. May I know what needs to be done ?
