### ISSUE TITLE
Unable to evaluate. Outcome matrices not same length

### ISSUE THREAD

**Issue by dnaase** [deeplearning4j/deeplearning4j#2512]
There is an old issue about it. But i don't think my problem is the same as that. 
I am using LSTM on spark for Many-to-One prediction, batchSizePerWorker=64.
For each of the JavaRDD<DataSet>, feature matrix is a 30(time length)X 342 (feature size). Label is a single int with 0/1.
According to the help doc, i should use mask array, then I found that during my DataSet creation, i should add the mask array to it. So I create

INDArray featureMask = Nd4j.ones(batchSizePerWorker, 30);
INDArray labelMask = Nd4j.zeros(batchSizePerWorker, 30);

INDArray label = Nd4j.zeros(1);
INDArray features = Nd4j.create(30, 342);
for(int i = 0; i < 30; i++){
	for(int s = 0; s < batchSizePerWorker; s++){
		labelMask.putScalar(s, i, my_indicator_for_mask);
	}
	for(int j = 0; j < 342; j++){
		features.putScalar(i, j, my_double_data_value);
	}
}

new DataSet(features, label, featureMask, labelMask);

But I still got the same error:

Here is the error msg i have:

Caused by: java.lang.IllegalArgumentException: Unable to evaluate. Outcome matrices not same length
	at org.deeplearning4j.eval.Evaluation.eval(Evaluation.java:217)
	at org.deeplearning4j.eval.Evaluation.eval(Evaluation.java:191)
	at org.deeplearning4j.spark.impl.multilayer.evaluation.EvaluateFlatMapFunction.call(EvaluateFlatMapFunction.java:112)
	at org.deeplearning4j.spark.impl.multilayer.evaluation.EvaluateFlatMapFunction.call(EvaluateFlatMapFunction.java:41)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:159)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by AlexDBlack** [comment]
```INDArray label = Nd4j.zeros(1);``` there's your problem: your labels array isn't valid: it needs to have a value for every example. So Nd4j.zeros(30,1) then set the values for each example as appropriate.

i.e., size(0) for all arrays (features, labels, mask arrays) represents the number of examples in the minibatch  must be the same - this holds for all network types as well as both spark and local training.
