### ISSUE TITLE
EarlyStoppingMNIST: The system cannot find the path specified

### ISSUE THREAD

**Issue by Parasolio** [deeplearning4j/deeplearning4j#2529]
When running the class EarlyStoppingMNIST I got the following error:

Exception in thread "main" java.lang.RuntimeException: Error saving best model
	at org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer.fit(BaseEarlyStoppingTrainer.java:207)
	at org.deeplearning4j.examples.misc.earlystopping.EarlyStoppingMNIST.main(EarlyStoppingMNIST.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.io.FileNotFoundException: C:\Temp\DL4JEarlyStoppingExample\bestModel.bin (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at org.deeplearning4j.util.ModelSerializer.writeModel(ModelSerializer.java:62)
	at org.deeplearning4j.earlystopping.saver.LocalFileModelSaver.save(LocalFileModelSaver.java:73)
	at org.deeplearning4j.earlystopping.saver.LocalFileModelSaver.saveBestModel(LocalFileModelSaver.java:51)
	at org.deeplearning4j.earlystopping.saver.LocalFileModelSaver.saveBestModel(LocalFileModelSaver.java:25)
	at org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer.fit(BaseEarlyStoppingTrainer.java:205)
	... 6 more

**Comment by AlexDBlack** [comment]
Try manually setting the output directory when saving to somewhere that exists (like 85 in the example) - let me know if that helps.
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/earlystopping/EarlyStoppingMNIST.java#L85

**Comment by Parasolio** [comment]
Yes it helps. I hard coded the directory (c://test/) and it seems to work well. Do you want I debug it more and fix it?

**Comment by AlexDBlack** [comment]
No, it's probably just some quirk on your system - it uses java.io.tempdir, and I'm guessing that doesn't exist on your system? Either way, we haven't had any other reports of issues here (and it's not related to DL4J per-se) so I'm going to close this.
