### ISSUE TITLE
NeuralNet serialization exception

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#259]
On current stable release of dl4j and nd4j there's an issue: serialization called on MultiLayerNetwork causes serialization exception:

Call to serialization: 

SerializationUtils.saveObject(d,new File("test.neuro"));

Exception:

Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:130)
Caused by: java.lang.RuntimeException: java.io.NotSerializableException: org.nd4j.linalg.api.rng.DefaultRandom
    at org.deeplearning4j.util.SerializationUtils.saveObject(SerializationUtils.java:110)
    at org.hive.cloud.neurality.networks.POSNetwork.main(POSNetwork.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
    ... 5 more
Caused by: java.io.NotSerializableException: org.nd4j.linalg.api.rng.DefaultRandom
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
    at org.deeplearning4j.util.SerializationUtils.saveObject(SerializationUtils.java:105)
    ... 11 more

**Comment by agibsonccc** [comment]
I'm going to suggest you save the net the following way:

INDArray params = layer.params();
String conf = layer.conf().toJson();

Nd4j.write/writeTxt(params,"somefile");
//it's a string save however you want

**Comment by EronWright** [comment]
@agibsonccc your suggestion is to avoid serializing the network itself, rather serialize the configuration and the parameters.   My assertion is that marking the network (and related execution elements) as Serializable is overreach.   A difficult/undue guarantee to make.

**Comment by agibsonccc** [comment]
You're absolutely right. It's a workaround for now.I need to dive more in to the details for the serde. Ideally I'd write a read/writeObject routine to handle this. I'll look in to this in a bit.

**Comment by agibsonccc** [comment]
This is fixed. I've made distribution and rng transient.

**Comment by EronWright** [comment]
@agibsonccc a slight misunderstanding of the issue - @raver119 is trying to serialize the MultiLayerNetwork (which contains the ND4J random type), not the configuration (which is truly serializable).   Please undo d27f640264a650a4b59c50a53de64c0e50fb0eee and aspects of 6f08a3bd2019d1161bfc594294e7901ea669060b (unfortunately the change was made within a merge commit).

**Comment by EronWright** [comment]
The regression has been fixed and we may close this again.
