### ISSUE TITLE
Evaluation exceptions

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#260]
On latest stable dl4j & nd4j:

Training & test data are both sourced from the same CSV, but the evaluation code throws exception:
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:130)
Caused by: java.lang.IllegalArgumentException: Unable to evaluate. Outcome matrices not same length
	at org.deeplearning4j.eval.Evaluation.eval(Evaluation.java:50)
	at org.hive.cloud.neurality.networks.POSNetwork.main(POSNetwork.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
	... 5 more

Evaluation code was taken from examples:

CSVDataSetIterator test = new CSVDataSetIterator(100, 5, new File("test_pos.csv"), 0);
        DataSet next = test.next();

        Evaluation eval = new Evaluation();
        INDArray output = d.output(next.getFeatureMatrix());
        eval.eval(next.getLabels(),output);
        System.out.printf("Score: %s\n", eval.stats());

**Comment by raver119** [comment]
This is totally my fault, exception was caused by shape mismatches between train and test data.
