### ISSUE TITLE
WordVectorsImpl.wordsNearest no longer working

### ISSUE THREAD

**Issue by carschno** [deeplearning4j/deeplearning4j#264]
Hi,
I am not sure since when this goes on, but when I call `WordVectorsImpl.wordsNearest()`, the following exception is thrown:

    java.lang.AssertionError: Illegal row vector must have the same length as the number of rows in this ndarray
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assertRowVector(BaseNDArray.java:2085)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.doRowWise(BaseNDArray.java:2129)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.diviRowVector(BaseNDArray.java:2260)
	at org.deeplearning4j.models.embeddings.wordvectors.WordVectorsImpl.wordsNearest(WordVectorsImpl.java:345)
	at org.deeplearning4j.models.word2vec.DistanceTest.interaction(DistanceTest.java:55)
	at org.deeplearning4j.models.word2vec.DistanceTest.main(DistanceTest.java:33)

I've investigated this a bit and apparently the vector returned by `distances.norm2(1)` is a column vector (1 column, n rows) while `distances` is a row vector (n columns, 1 row). That is why the assertion in `assertRowVector()` fails. This seems to happen independently of the vectors and the dimensionality as I have tried with multiple embeddings read/produced from various sources with varying parameters.

**Comment by carschno** [comment]
Apparently, this is somehow related to the Java version. I had switched to JDK 8 (Oracle); after switching back to Java 7 (Open JDK), the assertion passes again and `nearestWords()` works. Might be something the keep an eye on anyway.

**Comment by ozborn** [comment]
I can verify that this problem still exists in the 0.4 version as:
```
Exception in thread "main" java.lang.AssertionError: Illegal row vector must have the same length as the number of rows in this ndarray
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assertRowVector(BaseNDArray.java:1962)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.doRowWise(BaseNDArray.java:1987)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.diviRowVector(BaseNDArray.java:2219)
	at org.deeplearning4j.models.embeddings.wordvectors.WordVectorsImpl.wordsNearest(WordVectorsImpl.java:409)
	at org.deeplearning4j.models.embeddings.wordvectors.WordVectorsImpl.wordsNearest(WordVectorsImpl.java:497)
	at edu.uab.ccts.nlp.uima.client.UABWord2VecClient.main(UABWord2VecClient.java:115)
-- org.jblas INFO Deleting /tmp/jblas1168805275671510065/libjblas.so
-- org.jblas INFO Deleting /tmp/jblas1168805275671510065/libjblas_arch_flavor.so
-- org.jblas INFO Deleting /tmp/jblas1168805275671510065
```
Unfortunately the workaround used by carschno doesn't work for me - I have tried both Oracle's 1.7 and 1.8 as well as OpenJDK 7 and 8 without success.

Once I get a small test case going where I can actually replicate the problem I will post again.

**Comment by agibsonccc** [comment]
Please wait for the next release due out tonight.

Thanks!
