### ISSUE TITLE
Fatal Error: SIGBUS

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#2693]
Got this while tuning Inception-ResNet
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007f62fcf5ca32, pid=5166, tid=0x00007f61ebbfd700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.111-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libzip.so+0x11a32]  newEntry+0x62
#
```

Full error log:
https://gist.github.com/crockpotveggies/2d9533bc768dffe572873db12347d93e

**Comment by crockpotveggies** [comment]
Saw this again, here's latest dump:
https://gist.github.com/crockpotveggies/4ad1dde5c4ca6dc50ccf043718d79959

**Comment by raver119** [comment]
So, in both cases it's jar access triggers crash...

**Comment by crockpotveggies** [comment]
Does that imply a problem with the JAR then? Not DL4J?

**Comment by raver119** [comment]
Well, i hadn't heard of similar issues before this one :)

**Comment by crockpotveggies** [comment]
Alright then. Let's close it for now.

**Comment by raver119** [comment]
No-no, let's keep it as reference, just in case somebody else reports it.

**Comment by crockpotveggies** [comment]
Just got this error during startup of my JAR, related to JavaCPP but mentions zip functionality, related?
```
[main] ERROR java.lang.Throwable - Exception in thread "main" java.lang.ExceptionInInitializerError
[main] ERROR java.lang.Throwable - 	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.setMaxThreads(CpuBlas.java:87)
[main] ERROR java.lang.Throwable - 	at org.nd4j.nativeblas.Nd4jBlas.<init>(Nd4jBlas.java:33)
[main] ERROR java.lang.Throwable - 	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.<init>(CpuBlas.java:11)
[main] ERROR java.lang.Throwable - 	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createBlas(CpuNDArrayFactory.java:79)
[main] ERROR java.lang.Throwable - 	at org.nd4j.linalg.factory.BaseNDArrayFactory.blas(BaseNDArrayFactory.java:71)
[main] ERROR java.lang.Throwable - 	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.getEnvironmentInformation(NativeOpExecutioner.java:1057)
[main] ERROR java.lang.Throwable - 	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.printEnvironmentInformation(DefaultOpExecutioner.java:558)
[main] ERROR java.lang.Throwable - 	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5680)
[main] ERROR java.lang.Throwable - 	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5554)
[main] ERROR java.lang.Throwable - 	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:189)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:631)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.FaceNetVariant.graphBuilder(FaceNetVariant.java:141)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.FaceNetVariant.initTripletTraining(FaceNetVariant.java:98)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.TripletTraining.run(TripletTraining.java:69)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.ParallelOptimization.main(ParallelOptimization.java:94)
[main] ERROR java.lang.Throwable - Caused by: java.lang.NullPointerException: Inflater has been closed
[main] ERROR java.lang.Throwable - 	at java.util.zip.Inflater.ensureOpen(Inflater.java:389)
[main] ERROR java.lang.Throwable - 	at java.util.zip.Inflater.inflate(Inflater.java:257)
[main] ERROR java.lang.Throwable - 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152)
[main] ERROR java.lang.Throwable - 	at java.io.FilterInputStream.read(FilterInputStream.java:133)
[main] ERROR java.lang.Throwable - 	at java.io.FilterInputStream.read(FilterInputStream.java:107)
[main] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.Loader.extractResource(Loader.java:551)
[main] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:411)
[main] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:913)
[main] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.Loader.load(Loader.java:738)
[main] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.Loader.load(Loader.java:657)
[main] ERROR java.lang.Throwable - 	at org.bytedeco.javacpp.openblas.<clinit>(openblas.java:10)
[main] ERROR java.lang.Throwable - 	... 15 more
```

**Comment by saudet** [comment]
Maybe a regression of this http://bugs.java.com/view_bug.do?bug_id=7003462 ?

**Comment by agibsonccc** [comment]
So this *is* or *isn't* a bug here?

**Comment by saudet** [comment]
Well, it's a bug somewhere alright, but it looks like it might be in the JDK. @crockpotveggies did you manage to reproduce that with a small self-contained example? I might be able to find a workaround that way...

**Comment by crockpotveggies** [comment]
I will provide a reproducible Docker in the morning :)

**Comment by saudet** [comment]
Docker, well just some small project would be best, if possible. :)

**Comment by crockpotveggies** [comment]
I suggested Docker because the problem seems to originate from the Docker
environment. I can try to recreate it in OSX but I'm unsure it will occur

**Comment by crockpotveggies** [comment]
Haven't seen this at all since I filed the issue. Closing...
