### ISSUE TITLE
Error running TestSparkMultiLayer 

### ISSUE THREAD

**Issue by dgkris** [deeplearning4j/deeplearning4j#270]
While trying to run the class TestSparkMultiLayer, the following error occurs

18:32:03,818 INFO  ~ Running distributed training averaging each iteration false and 15 partitions
18:32:14,186 ERROR ~ Exception in task 0.0 in stage 4.0 (TID 32)
java.lang.IllegalArgumentException: Unable to get linear index >= 1
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3180)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.slice(BaseNDArray.java:2867)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3608)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3609)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.setParameters(MultiLayerNetwork.java:1415)
	at org.deeplearning4j.spark.impl.multilayer.IterativeReduceFlatMap.call(IterativeReduceFlatMap.java:65)
	at org.deeplearning4j.spark.impl.multilayer.IterativeReduceFlatMap.call(IterativeReduceFlatMap.java:38)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:143)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:143)
	at org.apache.spark.rdd.RDD$$anonfun$14.apply(RDD.scala:634)
	at org.apache.spark.rdd.RDD$$anonfun$14.apply(RDD.scala:634)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
18:32:14,196 ERROR ~ Task 0 in stage 4.0 failed 1 times; aborting job

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4.0 (TID 32, localhost): java.lang.IllegalArgumentException: Unable to get linear index >= 1
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3180)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.slice(BaseNDArray.java:2867)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3608)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3609)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.setParameters(MultiLayerNetwork.java:1415)
	at org.deeplearning4j.spark.impl.multilayer.IterativeReduceFlatMap.call(IterativeReduceFlatMap.java:65)
	at org.deeplearning4j.spark.impl.multilayer.IterativeReduceFlatMap.call(IterativeReduceFlatMap.java:38)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:143)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:143)
	at org.apache.spark.rdd.RDD$$anonfun$14.apply(RDD.scala:634)
	at org.apache.spark.rdd.RDD$$anonfun$14.apply(RDD.scala:634)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1203)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1192)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1191)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1191)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:693)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1393)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1354)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)

**Comment by agibsonccc** [comment]
Fixed in nd4j master. This was related to row vector indexing semantics (off by one errors due to shapes being forced to be 1,m now.

**Comment by dgkris** [comment]
the static invocation fails with message : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4.0 (TID 32, localhost): java.lang.IllegalStateException: Column of left 600 != rows of right 4
	at org.nd4j.linalg.util.LinAlgExceptions.assertMultiplies(LinAlgExceptions.java:50)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2471)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2320)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.propUp(RBM.java:325)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.transform(RBM.java:383)
	at org.deeplearning4j.nn.layers.BasePretrainNetwork.setScore(BasePretrainNetwork.java:66)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:118)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:133)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:368)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.fit(RBM.java:397)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:217)

@agibsonccc

**Comment by agibsonccc** [comment]
What's your configuration? This looks to be due to wrong layer sizes.

**Comment by dgkris** [comment]
Its the test case : testStaticInvocation on TestMultiLayerSpark

On Thu, May 21, 2015 at 2:39 PM, Adam Gibson <notifications@github.com>
wrote:

> What's your configuration? This looks to be due to wrong layer sizes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deeplearning4j/deeplearning4j/issues/270#issuecomment-104382725>
> .
>



-- 
Regards,
*Deepak Gopalakrishnan*
*Mobile*:+918891509774
*Skype* : deepakgk87
http://myexps.blogspot.com

**Comment by agibsonccc** [comment]
This is fixed.
