### ISSUE TITLE
InMemoryLookupTable#plotVocab(): Unable to get linear index

### ISSUE THREAD

**Issue by carschno** [deeplearning4j/deeplearning4j#273]
Whenever I call `plotVocab()`, the following exception is thrown:

    java.lang.IllegalArgumentException: Unable to get linear index >= 1
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3180)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.slice(BaseNDArray.java:2867)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3608)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:3609)
	at org.deeplearning4j.plot.Tsne.computeGaussianPerplexity(Tsne.java:143)
	at org.deeplearning4j.plot.Tsne.calculate(Tsne.java:237)
	at org.deeplearning4j.plot.Tsne.plot(Tsne.java:385)
	at org.deeplearning4j.plot.Tsne.plot(Tsne.java:372)
	at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable.plotVocab(InMemoryLookupTable.java:115)
	at org.deeplearning4j.models.word2vec.Word2VecTests.testWord2VecRunThroughVectorsTsne(Word2VecTests.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

This happens in the provided test case `testWord2VecRunThroughVectorsTsne()` from `Word2VecTests` (this is when the exact stack trace pasted above is thrown), but also for multiple other Word2Vec instances that I've tried. I also tried to run the JVM with `-Ddtype=float`, but (as expected) this does not make a difference.

I am aware that there have been a couple of issues reported with regard to the `plotVocab()` method, but none of them seems to cover this exact problem. Also, I am not sure where to start debugging.

**Comment by agibsonccc** [comment]
This is related to the row vector change I made (all row vectors have are 1 x m no matter what) will push a fix soon.

**Comment by carschno** [comment]
Seems to be resolved with the most recent updates.
