### ISSUE TITLE
CSVDataSetIterator crash

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#274]
CSVDataSetIterator crashes on loading big files.

Test file was binary dataset, 3587 values per row, 700k rows+, 5.5GB in total.
Small file with the same format loads without any issues.

CSVDataSetIterator csv = new CSVDataSetIterator(4000, 20, new File("task_pos.csv"), 0);

Exception in thread "main" java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:130)
Caused by: java.lang.NegativeArraySizeException
at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:40)
at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:38)
at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:557)
at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:199)
at org.nd4j.linalg.jblas.NDArray.<init>(NDArray.java:100)
at org.nd4j.linalg.jblas.JblasNDArrayFactory.create(JblasNDArrayFactory.java:204)
at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:185)
at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3058)
at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2448)
at org.nd4j.linalg.dataset.DataSet.merge(DataSet.java:87)
at org.deeplearning4j.datasets.fetchers.CSVDataFetcher.init(CSVDataFetcher.java:142)
at org.deeplearning4j.datasets.fetchers.CSVDataFetcher.<init>(CSVDataFetcher.java:94)
at org.deeplearning4j.datasets.fetchers.CSVDataFetcher.<init>(CSVDataFetcher.java:105)
at org.deeplearning4j.datasets.iterator.CSVDataSetIterator.<init>(CSVDataSetIterator.java:54)
at org.hive.cloud.neurality.networks.POSNetwork.main(POSNetwork.java:105)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
... 5 more

**Comment by agibsonccc** [comment]
Oh interesting. This looks to be related to the maximum size of an array ( 2 Billion etc)

Could you adapt this:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/datasets/canova/RecordReaderDataSetiteratorTest.java#L38

And compare? Thanks!

**Comment by raver119** [comment]
Will do in a hour.

**Comment by raver119** [comment]
No crashes with canova.

**Comment by agibsonccc** [comment]
Great. I'm actually going to close this and annotate csvdatasetiterator with deprecated. I will fix the underlying issue in nd4j (array size issues) I will migrate the nd4j arrays to be buffers instead. This will allow us to bypass the jvm size limit on arrays.
