### ISSUE TITLE
Disable validation and error logging

### ISSUE THREAD

**Issue by someonedeep** [deeplearning4j/deeplearning4j#2741]
When initializing or training a network, dl4j outputs information to console. For particular applications/implementations, this may overflood the console with information. Preferably, the user can better control the output that is being generated.  In other words, the possibility to disable validation and error messages would be welcome.

Some example of dl4j output:

```
o.d.n.c.NeuralNetConfiguration - Layer "Layer not named" rmsdecay is set but will not be applied unless the updater is set to RMSPROP.

org.deeplearning4j.exception.DL4JInvalidInputException: Invalid input data or configuration: kernel height and input height must satisfy 0 < kernel height <= input height + 2 * padding height. 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Got kernel height = 4, input height = 2 and padding height = 0 which do not satisfy 0 < 4 <= 2
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Input size: [numExamples,inputDepth,inputHeight,inputWidth]=[24, 20, 2, 6], kernel=[4, 4], strides=[6, 2], padding=[0, 0]
	at org.deeplearning4j.util.ConvolutionUtils.getOutputSize(ConvolutionUtils.java:60) ~[deeplearning4j-nn-0.7.2.jar:na]
```

**Comment by raver119** [comment]
Disabling validation is NEVER any good idea when it comes down to native code. You prefer to see mysterious segfaults when running your app, instead of human-readable input validation messages?

**Comment by someonedeep** [comment]
I get your point, in most cases validation and error messages are usefull and perhaps even vital. In my application however, I prefer to see nothing. Having said that, it is not that big a deal to keep it in. A disable option would simply make the output in this one application more readable.
