### ISSUE TITLE
RecordReaderDataSetIterator exception

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#275]
File task_pos.csv.MINI containes 3500 lines.

RecordReader recordReader = new CSVRecordReader();
FileSplit csv = new FileSplit(new File("task_pos.csv.MINI"));
recordReader.initialize(csv);
DataSetIterator iter = new RecordReaderDataSetIterator(recordReader, 3000, 0, 22);
DataSet set = iter.next();

If you initialize RecordReaderDataSetIterator with batchSize below actual number of rows - everything is ok.

If batchSize is higher, then actual number of rows - then iter.reset() throws Exception after training is done:

Exception in thread "main" java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:130)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
at org.nd4j.linalg.factory.BaseNDArrayFactory.vstack(BaseNDArrayFactory.java:1084)
at org.nd4j.linalg.factory.Nd4j.vstack(Nd4j.java:2000)
at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:144)
at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:200)
at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:43)
at org.hive.cloud.neurality.networks.POSNetwork.main(POSNetwork.java:149)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
... 5 more

**Comment by agibsonccc** [comment]
Merged a fix that will do a hard stop if it finds an empty dataset. It will train on the last dataset returned twice if it overshoots.
