### ISSUE TITLE
ModelSerializer.restoreMultiLayerNetwork breaks on Android

### ISSUE THREAD

**Issue by Erhannis** [deeplearning4j/deeplearning4j#2756]
ModelSerializer.restoreMultiLayerNetwork(InputStream) depends on java.nio.file.Paths, which doesn't exist on Android, so it crashes there.  ("Files" may also cause issues, for the same reason.)

```
E/AndroidRuntime: FATAL EXCEPTION: Thread-21537
                  Process: com.aptima.android.dl4jandroidtest, PID: 32755
                  java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Paths;
                      at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:291)
                      at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:296)
                      at com.aptima.android.dl4jandroidtest.BasicRNNExample.runModel(BasicRNNExample.java:195)
                      at com.aptima.android.dl4jandroidtest.MainActivity$1$1.run(MainActivity.java:81)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.Paths" on path: DexPathList[[dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-videoinput-0.200-1.3_35a43941b2af5de58d4369e609710846416f65b0-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-support-annotations-24.2.1_b05ff2388c99156f5062f27de816c0604390f760-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-stax2-api-3.1.4_61ef87bf23f522cee2b70165765b989a5ee8ec97-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-snakeyaml-1.12_e77a7babfc3b10edd828e0f0810bb361f85e7b55-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-slf4j-api-1.7.12_4b953b1dd75f6726b6b48f9a51dac5603bd4b183-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-reflections-0.9.10_f3d776993dc419f318bba298279571a103b0e87f-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-opencv-3.1.0-1.3_3df9a28afd68b031d6894c66e37d3d07c6e35789-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-openblas-0.2.19-1.3_8fcfdf13c97efa1aea1805331ade2725821192ec-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-nd4j-native-api-0.7.2_96e7477c153c5b44f4d96056d0fb7b47853a042b-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-nd4j-native-0.7.2_a92a1166682680979884facde96c70a72fbc3246-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-nd4j-context-0.7.2_a211ddfbcdad66c55758271b1239966cfd26e3a0-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-nd4j-common-0.7.2_286f9d6b3851efdc8cb998fd8300d07a6f85ed1e-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-nd4j-buffer-0.7.2_b28dc0dffbdc6e3ab3402c770555da345aa1b024-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-nd4j-api-0.7.2_f9d6e7770ced9917554171ef8638ab959da683f2-classes.dex", dex file "/data/data/com.aptima.android.dl4jandroidtest/files/instant-run/dex/slice-lombok-1.16.10_3ce35a15d436eda9105
```

**Comment by raver119** [comment]
Fix applied & merged.

Thanks for highlighting this issue. Please, let us know if you'll find any more issues with Android.
