### ISSUE TITLE
AWS CUDA devices not found with deep learning AMI on p2.xlarge

### ISSUE THREAD

**Issue by ptah23** [deeplearning4j/deeplearning4j#2757]
i have just tried using nd4j-cuda-8.0-platform on aws p2.xlarge with deeplearning AMI
and get Caused by: java.lang.RuntimeException: No CUDA devices were found in system
at org.nd4j.jita.conf.Configuration.<init>(Configuration.java:343)
i can see the GPU though: nvidia-smi -q | head
==============NVSMI LOG==============
Timestamp : Thu Jan 26 22:37:23 2017
Driver Version : 352.99
Attached GPUs : 1
GPU 0000:00:1E.0
Product Name : Tesla K80
Product Brand : Tesla
is that the right AMI to use?
i was using AMI: Deep Learning AMI - Amazon Linux - 1.5 (MXNet with MKL Support) (ami-41570b32)

**Comment by agibsonccc** [comment]
Do you have a stack trace and cuda version? I'm guessing this isn't actually a problem on our side.
Either way we need a lot more information here.

**Comment by ptah23** [comment]
2870 [main] INFO  org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
2915 [main] INFO  org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 32
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.jita.concurrency.CudaAffinityManager.<clinit>(CudaAffinityManager.java:33)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5611)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5554)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:189)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:624)
	at io.regularization.leafclassifier.ResNetTrainer.buildModelConfig(ResNetTrainer.java:153)
	at io.regularization.leafclassifier.ResNetTrainer.main(ResNetTrainer.java:93)
Caused by: java.lang.RuntimeException: No CUDA devices were found in system
	at org.nd4j.jita.conf.Configuration.<init>(Configuration.java:343)
	at org.nd4j.jita.conf.CudaEnvironment.<init>(CudaEnvironment.java:24)
	at org.nd4j.jita.conf.CudaEnvironment.<clinit>(CudaEnvironment.java:18)
	... 9 more

**Comment by ptah23** [comment]
I changed from 8.0 back end to 7.5 and it is getting further now

**Comment by eduramiba** [comment]
Is there any way to use CUDA 8 on AWS? I am using the nd4j version 0.9.2-SNAPSHOT and there is no snapshots available here for 0.9.2 https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-cuda-7.5-platform

Thanks

**Comment by eduramiba** [comment]
This is the AMI I'm using https://aws.amazon.com/marketplace/pp/B01M0AXXQB

**Comment by eduramiba** [comment]
It works fine with this AMI https://aws.amazon.com/marketplace/pp/B077GCZ4GR no changes needed at all :)

**Comment by saudet** [comment]
Use these instead for CUDA 8.0:
https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-cuda-8.0/
