### ISSUE TITLE
Find a way to automatically handle errors in MNIST download

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2763]
This comes up enough that we should handle it automatically: perhaps retry a few times, and throw an informative exception if it fails enough.

```
Exception in thread "main" java.io.EOFException: Unexpected end of ZLIB input stream
at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
at java.io.FilterInputStream.read(FilterInputStream.java:107)
at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
at org.deeplearning4j.util.ArchiveUtils.unzipFileTo(ArchiveUtils.java:150)
at org.deeplearning4j.base.MnistFetcher.downloadAndUntar(MnistFetcher.java:82)
at org.deeplearning4j.datasets.fetchers.MnistDataFetcher.<init>(MnistDataFetcher.java:65)
at org.deeplearning4j.datasets.iterator.impl.MnistDataSetIterator.<init>(MnistDataSetIterator.java:65)
at org.deeplearning4j.datasets.iterator.impl.MnistDataSetIterator.<init>(MnistDataSetIterator.java:43)
```

**Comment by raver119** [comment]
Hash for archive + validation after it's not. If hash failed - retry download.

**Comment by erobic** [comment]
What is the main cause behind this error? I have tried running a sample 10 times, and I still get this error. I just downloaded the data manually.
