### ISSUE TITLE
ParagraphVectors throws NPE

### ISSUE THREAD

**Issue by oliverdain** [deeplearning4j/deeplearning4j#2773]
I trained a ParagrphVectors model and then used it to tag some existing text. One of the existing texts is just the string "?". Clearly not a very good piece of text, but it causes an NPE:

```
    java.lang.NullPointerException
        at org.nd4j.linalg.ops.transforms.Transforms.unitVec(Transforms.java:92)
        at org.deeplearning4j.models.paragraphvectors.ParagraphVectors.nearestLabels(ParagraphVectors.java:376)
        at org.deeplearning4j.models.paragraphvectors.ParagraphVectors.nearestLabels(ParagraphVectors.java:345)
        at org.deeplearning4j.models.paragraphvectors.ParagraphVectors.nearestLabels(ParagraphVectors.java:332)
        at com.analyticspot.nlp.transforms.LabeledDoc2Vec.transform(LabeledDoc2Vec.kt:60)
        at com.analyticspot.nlp.transforms.LabeledDoc2Vec.trainTransform(LabeledDoc2Vec.kt:98)
        at com.analyticspot.nlp.transforms.LabeledDoc2VecTest.testRealStuff(LabeledDoc2VecTest.kt:80)
```

**Comment by oliverdain** [comment]
It also throws an NPE on longer texts. This one caused an NPE: `Summera Fallea Springa Wintera`

**Comment by oliverdain** [comment]
Another examples that results in an NPE: `tei eleookses eleike tehey aeree juesete studyeing ani woirking.`

**Comment by raver119** [comment]
Show paravec configuration you've used to build initial model please.

**Comment by oliverdain** [comment]
ParagraphVectors is built as follows (in Kotlin):

```
        doc2Vec = ParagraphVectors.Builder()
                .iterate(docIter)
                .iterations(3)
                .windowSize(5)
                .layerSize(100)
                .learningRate(0.1)
                .minWordFrequency(5)
                .tokenizerFactory(DefaultTokenizerFactory())
                // DM appears to be necessary. Passing DBOW causes it not to learn anything.
                .sequenceLearningAlgorithm(DM())
                .build()
```

Then fit:

```
 doc2Vec.fit()
```

Then used to make predictions:

```
    override fun transform(dataSet: DataSet): CompletableFuture<DataSet> {
        val labelList = mutableListOf<String?>()
        val distList = mutableListOf<Double?>()
        dataSet.column(docColumn).forEachIndexed { idx, doc ->
            try {
                val inferred = doc2Vec.inferVector(doc)
                val label = doc2Vec.nearestLabels(doc, 1).first()
                val labelVec = doc2Vec.lookupTable.vector(label)
                val dist = Transforms.cosineSim(inferred, labelVec)
                distList.add(dist)
                labelList.add(label)
            } catch (e: NullPointerException) {
                // The catch is needed because ParagraphVectors throws on short texts, texts that contain words not
                // in the vocabulary, etc. See https://github.com/deeplearning4j/deeplearning4j/issues/2773.
                log.warn("ParagraphVectors threw an NPE on the text: {}", doc)
                distList.add(null)
                labelList.add(null)
            }
            if (idx % 1000 == 0) {
                log.debug("Transformed {} items", idx)
            }
        }
        val ds = DataSet.build {
            addColumn(ColumnId.create<String>("label"), labelList)
            addColumn(ColumnId.create<Double>("dist"), distList)
        }
        return CompletableFuture.completedFuture(ds)
    }
```

The catch block there is necessary due to the bug reported here. I don't think you'll find the unit test code very helpful as it's mostly code that uses our ML framework (the DataSet class, etc.) to feed in 300k text examples. The texts are short Spanish snippets - usually a hundred words or so each.

**Comment by raver119** [comment]
Well, the only suspect i can see here is simple, but i'll need you to check if that's the case:

For any doc that throws NPE - tokenize it manually, and check if it has at least one word matching your vocab.

**Comment by oliverdain** [comment]
Yes, I think you're correct that it happens only for texts that contain only words that aren't in the vocab. I understand why you can't get a valid inference for such texts. However, since that isn't a crazy edge case (e.g. this would be very common if processing tweets) it seems like something other than an NPE would be a more appropriate outcome -- maybe just return null?

**Comment by raver119** [comment]
Yep, you're right, since you've confirmed that's the case - i'll add proper handling there right now.

**Comment by raver119** [comment]
Issue fixed, appropriate exceptions/notifications were added.
