### ISSUE TITLE
Unavailable file in dl4j-test-resources

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/deeplearning4j#2868]
Running tests:

```
Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.199 sec <<< FAILURE! - in org.deeplearning4j.nn.modelimport.keras.KerasModelConfigurationTest
importMnistCnnTensorFlowConfigurationTest(org.deeplearning4j.nn.modelimport.keras.KerasModelConfigurationTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.io.FileNotFoundException: class path resource [modelimport/keras/examples/mnist_cnn/mnist_cnn_tf_config.json] cannot be opened because it does not exist
	at org.nd4j.linalg.io.ClassPathResource.getInputStream(ClassPathResource.java:106)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelConfigurationTest.importMnistCnnTensorFlowConfigurationTest(KerasModelConfigurationTest.java:107)
```

Checking in dl4j-test-resources (master):

```
huitseeker@sleipnir➜huitseeker/DL4J/dl4j-test-resources(master)» ls target/classes/modelimport/keras/examples/
mnist_mlp
```

**Comment by turambar** [comment]
Added: https://github.com/deeplearning4j/dl4j-test-resources/tree/master/src/main/resources/modelimport/keras/examples/mnist_cnn.
