### ISSUE TITLE
"OutOfMemoryError: GC overhead limit exceeded" in BarnesHutTsne on large datasets

### ISSUE THREAD

**Issue by saudet** [deeplearning4j/deeplearning4j#2878]
Sample code plotting 50000 random points with BarnesHutTsne:
https://gist.github.com/saudet/be8c695b447e7f0fc296e2347ec596b1

The equivalent code using https://github.com/lejon/T-SNE-Java in the sample above runs fine in a couple of minutes, but BarnesHutTsne from Deeplearning4j eventually throws an OutOfMemoryError. Sample log:
```
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 8
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Linux]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [14.0GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:870)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:95)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.execAndReturn(DefaultOpExecutioner.java:221)
	at org.deeplearning4j.clustering.sptree.DataPoint.distance(DataPoint.java:75)
	at org.deeplearning4j.clustering.vptree.VPTree.getDistance(VPTree.java:151)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:172)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:200)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:200)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:200)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:199)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:200)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:200)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:200)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:200)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:200)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:199)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:199)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:199)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:199)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:199)
	at org.deeplearning4j.clustering.vptree.VPTree.buildFromPoints(VPTree.java:199)
	at org.deeplearning4j.clustering.vptree.VPTree.<init>(VPTree.java:72)
	at org.deeplearning4j.plot.BarnesHutTsne.computeGaussianPerplexity(BarnesHutTsne.java:182)
	at org.deeplearning4j.plot.BarnesHutTsne.fit(BarnesHutTsne.java:457)
	at org.deeplearning4j.plot.BarnesHutTsne.fit(BarnesHutTsne.java:669)
	at org.deeplearning4j.plot.BarnesHutTsne.plot(BarnesHutTsne.java:577)
	at TSnePlot.main(TSnePlot.java:74)
```

**Comment by saudet** [comment]
This seems to be fixed now in 0.9.2-SNAPSHOT, but performance continues to suffer (issue #2890).
