### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jnicudnn in java.library.path

### ISSUE THREAD

**Issue by Felix333** [deeplearning4j/deeplearning4j#2879]
Hi,

I have set-up DL4J for the 1st time today using Win7, Maven und IntelliJ IDE as recommended.

The examples worked fine so far until enabling cuDNN - I'm getting these exceptions now:

o.d.n.l.c.ConvolutionLayer - Could not load CudnnConvolutionHelper
java.lang.UnsatisfiedLinkError: no jnicudnn in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[na:1.8.0_102]
	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[na:1.8.0_102]
	at java.lang.System.loadLibrary(System.java:1122) ~[na:1.8.0_102]
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:945) ~[javacpp-1.3.1.jar:1.3.1]
	at org.bytedeco.javacpp.Loader.load(Loader.java:750) ~[javacpp-1.3.1.jar:1.3.1]
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Jürgen\.javacpp\cache\cuda-7.5-1.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jnicudnn.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.8.0_102]

Apparently jnicudnn.dll cannot be found. A quick search showed that it exists in 
<user>\.javacpp\cache\cuda-7.5-1.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64
together with other related DLLS.

Any ideas why the JVM cannot find it? Do I need to install javacpp separately?
	
Thanks,
Juergen

**Comment by Felix333** [comment]
OK - DependencyWalker showed that jnicudnn depends on a specific cuDNN DLL which was not present on my system because I had an older cuDNN version installed.

Upgrading to cuDNN 5.1 solved the issue.
