### ISSUE TITLE
deeplearning4j-core: SubsampleTests failing

### ISSUE THREAD

**Issue by sonaliii** [deeplearning4j/deeplearning4j#288]
Need to account for 1 and 10 on slices when downsampling. Otherwise getting the following error under SubSamplingLayer.java activate function. In test gets downsample of shape 10 x 20 when it should be 1x10x20:

java.lang.AssertionError: Slices must be equivalent.
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putSlice(BaseNDArray.java:1370)
	at org.deeplearning4j.nn.layers.convolution.subsampling.SubsamplingLayer.activate(SubsamplingLayer.java:122)
	at org.deeplearning4j.nn.layers.convolution.SubsampleTests.testSubSampleLayer(SubsampleTests.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)

**Comment by agibsonccc** [comment]
Can you try with the fixslices branch of nd4j?

**Comment by sonaliii** [comment]
Getting the same error with that branch.

**Comment by agibsonccc** [comment]
Fixed. Will merge the branch here soon.
