### ISSUE TITLE
Using SubsetVertex followed by an EmbeddingLayer throws an exception

### ISSUE THREAD

**Issue by RoiViber** [deeplearning4j/deeplearning4j#2885]
Name: org.apache.spark.SparkException
Message: Job aborted due to stage failure: Task 461 in stage 14.0 failed 4 times, most recent failure: Lost task 461.3 in stage 14.0 (TID 18314, ip-10-166-9-28.ec2.internal): java.lang.IllegalStateException: Cannot do backward pass: error not set
	at org.deeplearning4j.nn.graph.vertex.impl.SubsetVertex.doBackward(SubsetVertex.java:93)
	at org.deeplearning4j.nn.graph.ComputationGraph.calcBackpropGradients(ComputationGraph.java:1203)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:969)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:151)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:54)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:833)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:740)
	at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingWorker.processMinibatch(ParameterAveragingTrainingWorker.java:205)
	at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingWorker.processMinibatch(ParameterAveragingTrainingWorker.java:43)
	at org.deeplearning4j.spark.api.worker.ExecuteWorkerMultiDataSetFlatMap.call(ExecuteWorkerMultiDataSetFlatMap.java:83)
	at org.deeplearning4j.spark.api.worker.ExecuteWorkerMultiDataSetFlatMap.call(ExecuteWorkerMultiDataSetFlatMap.java:26)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:152)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:152)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:785)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:785)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by AlexDBlack** [comment]
@RoiViber can you post the network configuration that you are using here?

Also fyi embedding layers are typically used as the first layer in a network, though, subsetting a set of *integer* inputs should be OK (I assume that's what you are doing)

**Comment by AlexDBlack** [comment]
Closing due to inactivity.
