### ISSUE TITLE
BarnesHutTsne with AdaGrad: Updater has not been initialized with view state

### ISSUE THREAD

**Issue by amo876** [deeplearning4j/deeplearning4j#2889]
By using 

```
        BarnesHutTsne tsne = new BarnesHutTsne.Builder()
                .perplexity(tSnePerplexity) // 40
                .setMaxIter(tSneIterations) // 10000
                //.stopLyingIteration(250)
                .learningRate(tSneLearningRate)
                .theta(T_SNE_THETA)
                .setMomentum(0.7)
                .useAdaGrad(true)
                .normalize(false)
                .build();
```

i receive

```
Exception in thread "main" java.lang.IllegalStateException: Updater has not been initialized with view state
	at org.nd4j.linalg.learning.AdaGrad.getGradient(AdaGrad.java:117)
	at org.deeplearning4j.plot.BarnesHutTsne.update(BarnesHutTsne.java:495)
	at org.deeplearning4j.plot.BarnesHutTsne.step(BarnesHutTsne.java:472)
	at org.deeplearning4j.plot.BarnesHutTsne.fit(BarnesHutTsne.java:444)
        at org.deeplearning4j.plot.BarnesHutTsne.fit(BarnesHutTsne.java:641)
```

**Comment by jageshmaharjan** [comment]
I had the same issue, Then i did my dimension Reduction in Python using TSNE, which is straightFordward:

data = np.loadtxt(PATH_VECTORS, dtype=np.float64, delimiter=',')
X = data[:, 0: data.shape[1] - 1].astype(np.float64)
tsne = TSNE(n_jobs=8, n_components=2)
X_ = tsne.fit_transform(X)

**Comment by agibsonccc** [comment]
Here's getting the Y and running the UI:
https://github.com/deeplearning4j/deeplearning4j/blob/0fe5422d4b355f7235b0ecc01c1e425b5e1e1d21/deeplearning4j-ui-parent/deeplearning4j-ui/src/test/java/org/deeplearning4j/ui/ManualTests.java#L105

This doesn't feel relevant anymore.
