### ISSUE TITLE
Exception in thread "main" java.io.IOException: Not a file: file:/tmp/pulse-9TlyKFCPc59g

### ISSUE THREAD

**Issue by dlenthusiast** [deeplearning4j/deeplearning4j#2947]
-bash-4.1$ java -cp datavec-examples/target/datavec-examples-0.7-SNAPSHOT-bin.jar org/datavec/transform/basic/BasicDataVecExample
Input data schema details:
Schema():
idx name type meta data
0 "DateTimeString" String StringMetaData(name="DateTimeString",)
1 "CustomerID" String StringMetaData(name="CustomerID",)
2 "MerchantID" String StringMetaData(name="MerchantID",)
3 "NumItemsInTransaction" Integer IntegerMetaData(name="NumItemsInTransaction",)
4 "MerchantCountryCode" Categorical CategoricalMetaData(name="MerchantCountryCode",stateNames=["CAN","USA","MX","FR"])
5 "TransactionAmountUSD" Double DoubleMetaData(name="TransactionAmountUSD",minAllowed=0.0,allowNaN=false,allowInfinite=false)
6 "FraudLabel" Categorical CategoricalMetaData(name="FraudLabel",stateNames=["Legit","Fraud"])

Other information obtainable from schema:
Number of columns: 7
Column names: [DateTimeString, CustomerID, MerchantID, NumItemsInTransaction, MerchantCountryCode, TransactionAmountUSD, FraudLabel]
Column types: [String, String, String, Integer, Categorical, Double, Categorical]

Schema after transforming data:
Schema():
idx name type meta data
0 "HourOfDay" Integer IntegerMetaData(name="HourOfDay",)
1 "NumItemsInTransaction" Integer IntegerMetaData(name="NumItemsInTransaction",)
2 "MerchantCountryCode" Categorical CategoricalMetaData(name="MerchantCountryCode",stateNames=["CAN","USA","MX","FR"])
3 "TransactionAmountUSD" Double DoubleMetaData(name="TransactionAmountUSD",minAllowed=0.0,allowNaN=false,allowInfinite=false)
4 "FraudLabel" Categorical CategoricalMetaData(name="FraudLabel",stateNames=["Legit","Fraud"])

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
17/02/28 14:26:17 INFO SparkContext: Running Spark version 1.6.2
17/02/28 14:26:17 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/02/28 14:26:18 INFO SecurityManager: Changing view acls to: arustagi
17/02/28 14:26:18 INFO SecurityManager: Changing modify acls to: arustagi
17/02/28 14:26:18 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(arustagi); users with modify permissions: Set(arustagi)
17/02/28 14:26:19 INFO Utils: Successfully started service 'sparkDriver' on port 50335.
17/02/28 14:26:19 INFO Slf4jLogger: Slf4jLogger started
17/02/28 14:26:19 INFO Remoting: Starting remoting
17/02/28 14:26:19 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@10.196.168.15:53262]
17/02/28 14:26:19 INFO Utils: Successfully started service 'sparkDriverActorSystem' on port 53262.
17/02/28 14:26:19 INFO SparkEnv: Registering MapOutputTracker
17/02/28 14:26:19 INFO SparkEnv: Registering BlockManagerMaster
17/02/28 14:26:19 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-2d081194-cada-42e0-ba7b-e0bb24fd9e8b
17/02/28 14:26:19 INFO MemoryStore: MemoryStore started with capacity 19.8 GB
17/02/28 14:26:19 INFO SparkEnv: Registering OutputCommitCoordinator
17/02/28 14:26:20 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
17/02/28 14:26:20 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
17/02/28 14:26:20 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
17/02/28 14:26:20 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
17/02/28 14:26:20 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
17/02/28 14:26:20 INFO Utils: Successfully started service 'SparkUI' on port 4045.
17/02/28 14:26:20 INFO SparkUI: Started SparkUI at http://10.196.168.15:4045
17/02/28 14:26:20 INFO Executor: Starting executor ID driver on host localhost
17/02/28 14:26:20 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 52268.
17/02/28 14:26:20 INFO NettyBlockTransferService: Server created on 52268
17/02/28 14:26:20 INFO BlockManagerMaster: Trying to register BlockManager
17/02/28 14:26:20 INFO BlockManagerMasterEndpoint: Registering block manager localhost:52268 with 19.8 GB RAM, BlockManagerId(driver, localhost, 52268)
17/02/28 14:26:20 INFO BlockManagerMaster: Registered BlockManager
17/02/28 14:26:21 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 107.7 KB, free 107.7 KB)
17/02/28 14:26:21 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 9.8 KB, free 117.5 KB)
17/02/28 14:26:21 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:52268 (size: 9.8 KB, free: 19.8 GB)
17/02/28 14:26:21 INFO SparkContext: Created broadcast 0 from textFile at BasicDataVecExample.java:145
17/02/28 14:26:22 INFO FileInputFormat: Total input paths to process : 338
Exception in thread "main" java.io.IOException: Not a file: file:/tmp/pulse-9TlyKFCPc59g
at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:277)
at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:199)
at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
at scala.Option.getOrElse(Option.scala:120)
at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
at scala.Option.getOrElse(Option.scala:120)
at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
at scala.Option.getOrElse(Option.scala:120)
at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1307)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
at org.apache.spark.rdd.RDD.take(RDD.scala:1302)
at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1342)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
at org.apache.spark.rdd.RDD.first(RDD.scala:1341)
at org.apache.spark.api.java.JavaRDDLike$class.first(JavaRDDLike.scala:495)
at org.apache.spark.api.java.AbstractJavaRDDLike.first(JavaRDDLike.scala:46)
at org.datavec.spark.transform.SparkTransformExecutor.execute(SparkTransformExecutor.java:166)
at org.datavec.spark.transform.SparkTransformExecutor.execute(SparkTransformExecutor.java:94)
at org.datavec.transform.basic.BasicDataVecExample.main(BasicDataVecExample.java:153)
17/02/28 14:26:22 INFO SparkContext: Invoking stop() from shutdown hook
17/02/28 14:26:22 INFO SparkUI: Stopped Spark web UI at http://10.196.168.15:4045
17/02/28 14:26:22 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/02/28 14:26:22 INFO MemoryStore: MemoryStore cleared
17/02/28 14:26:22 INFO BlockManager: BlockManager stopped
17/02/28 14:26:22 INFO BlockManagerMaster: BlockManagerMaster stopped
17/02/28 14:26:22 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/02/28 14:26:22 INFO SparkContext: Successfully stopped SparkContext
17/02/28 14:26:22 INFO ShutdownHookManager: Shutdown hook called
17/02/28 14:26:22 INFO RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
17/02/28 14:26:22 INFO ShutdownHookManager: Deleting directory /tmp/spark-637411fc-8d92-4fba-a554-763ed1fb51b1

**Comment by agibsonccc** [comment]
This

**Comment by dlenthusiast** [comment]
why I am not able to run the following example ?
java -cp datavec-examples/target/datavec-examples-0.7-SNAPSHOT-bin.jar org/datavec/transform/basic/BasicDataVecExample
