### ISSUE TITLE
TrainedModels.VGG16 from tutorial doesn't load

### ISSUE THREAD

**Issue by rohrl** [deeplearning4j/deeplearning4j#2951]
Following piece of code taken from DL4J tutorial fails:
```
TrainedModelHelper helper = new TrainedModelHelper(TrainedModels.VGG16);
ComputationGraph network = helper.loadModel(); 
```
fails with:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:130)
Caused by: java.lang.RuntimeException: Unknown exception.
	at org.bytedeco.javacpp.hdf5$H5File.allocate(Native Method)
	at org.bytedeco.javacpp.hdf5$H5File.<init>(hdf5.java:12713)
	at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.<init>(Hdf5Archive.java:60)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.weightsHdf5Filename(KerasModel.java:535)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:181)
	at org.deeplearning4j.nn.modelimport.keras.trainedmodels.TrainedModelHelper.loadModel(TrainedModelHelper.java:69)
	at com.nuix.tools.deeplearning.ModelImport.trainVGG(ModelImport.java:114)
	at com.nuix.tools.deeplearning.ModelImport.main(ModelImport.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
	... 5 more
```
Executed on 0.7.3-SNAPSHOT

**Comment by tomthetrainer** [comment]
I would need to know what version the OP is using. 
As someone who has built 7-3-SNAPTSHOT frequently over the last few weeks, and worked with model import helpers I can confirm that the pieces that make some of that work have come and gone from version to version. 

Not much advice to the bug reporter except to rebuild and/or wait. 

I am building today, and I think I have code that relies on this, I can test

**Comment by eraly** [comment]
Thanks Tom. I'll test on my end also.

**Comment by eraly** [comment]
So it looks fine on my end. I ran off today's master. @rohrl Will you build and try again? As far as I know there hasn't been any problems with this.

**Comment by eraly** [comment]
I am closing this out.
