### ISSUE TITLE
TsneTest error

### ISSUE THREAD

**Issue by sonaliii** [deeplearning4j/deeplearning4j#296]
java.lang.IllegalArgumentException: Dx and dy must be same length
	at org.nd4j.linalg.jblas.BlasWrapper.axpy(BlasWrapper.java:162)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2674)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2651)
	at org.deeplearning4j.plot.Tsne.step(Tsne.java:359)
	at org.deeplearning4j.plot.Tsne.calculate(Tsne.java:255)
	at org.deeplearning4j.plot.Tsne.plot(Tsne.java:385)
	at org.deeplearning4j.plot.Tsne.plot(Tsne.java:372)
	at org.deeplearning4j.plot.TsneTest.testTsne(TsneTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by agibsonccc** [comment]
Fixed.
