### ISSUE TITLE
How to provide LabelledDocument to ParagraphVectors

### ISSUE THREAD

**Issue by krazavet** [deeplearning4j/deeplearning4j#2999]
Hello,

I am using deeplearning4j with scala to set up a doc2vec model but I have some troubles during training. I would like to use this model in order to auto-tag my datasets based on their semantic metadata.
For this purpose, I tried to associate each document (i.e. semantic metadata) with their labels (i.e. tags).

First of all, I prepare the data using the below method.

```
def prepareData(): Future[List[LabelledDocument]] = {
    val datasets: Source[Dataset, NotUsed] = datasetService.streamDatasets(PageReq(size = Paging.MAX_SIZE))

    val flow: Flow[Dataset, LabelledDocument, NotUsed] = Flow[Dataset]
        .mapAsync(parallelism = 5) { d =>
          Future {
            val labels = d.metadata.tags ++ List(d.id)
            val documentContent = d.metadata.extractSemantic.values.flatten.toList.map(_.trim).filter(_.nonEmpty)
            val documentContentString = documentContent.mkString(" ").trim
            if (documentContentString.isEmpty || d.metadata.tags.isEmpty)
              Left()
            else if (documentContent.length < 3 || d.metadata.tags.length < 3)
              Left()
            else {
              val labelledDocument = new LabelledDocument
              labelledDocument.setContent(documentContentString)
              labelledDocument.setLabels(labels.distinct.asJava)
              Right(labelledDocument)
            }
          }
        }
        .filter(_.isRight)
        .map(_.right.get)

    val sink: Sink[LabelledDocument, Future[List[LabelledDocument]]] = Sink
        .fold(List[LabelledDocument]())((a, b) => a ++ List(b))

    val labelledDocumentsFuture: Future[List[LabelledDocument]] = datasets
        .via(flow)
        .runWith(sink)

    labelledDocumentsFuture
  }
```

Then I run training using this method:

   ```
  def train() = {
        prepareData().map { labelledDocuments =>
          val iterator = new SimpleLabelAwareIterator(labelledDocuments.asJava)
    
          val tokenizerFactory = new DefaultTokenizerFactory()
          tokenizerFactory.setTokenPreProcessor(new CommonPreprocessor())
    
          val vec: ParagraphVectors = new ParagraphVectors.Builder()
              .minWordFrequency(5)
              .iterations(5)
              .epochs(1)
              .layerSize(100)
              .learningRate(0.025)
              .windowSize(10)
              .workers(4)
              .iterate(iterator)
              .trainWordVectors(true)
              .tokenizerFactory(tokenizerFactory)
              .negativeSample(5)
              .sampling(0.0001)
              .build()
        
          vec.fit()
    
          model = Some(vec)
        }
      }
```

During training I have the following error logs for each worker:

```
Exception in thread "VectorCalculationsThread 0" java.lang.RuntimeException: java.lang.IllegalStateException: Label is NULL
        at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1112)
Caused by: java.lang.IllegalStateException: Label is NULL
        at org.deeplearning4j.models.embeddings.learning.impl.sequence.DBOW.dbow(DBOW.java:104)
        at org.deeplearning4j.models.embeddings.learning.impl.sequence.DBOW.learnSequence(DBOW.java:81)
        at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:309)
        at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1087)
```

So obviously, I am not providing the data correctly as the stack trace expressed. I do not know why the labels are not well provided.

Could anyone help me?

**Comment by raver119** [comment]
```
   if (documentContentString.isEmpty || d.metadata.tags.isEmpty)
              Left()
            else if (documentContent.length < 3 || d.metadata.tags.length < 3)
              Left()
```
Basically you're not defining labels for some of your documents. 

In current master there's no such exception anymore though, documents without labels will be just skipped.

**Comment by krazavet** [comment]
Thank you @raver119 for your answer.

However, to train the model, I'm filtering only documents with labels.

```
        .filter(_.isRight)
        .map(_.right.get)
```

**Comment by raver119** [comment]
Tbh i just don't see any other viable explanations. Label either exists or not. The only place where you assign labels is shown above. Not too much room for other possibilities :)

**Comment by krazavet** [comment]
I have another error, @raver119 would you have a clue?

```
Exception in thread "Tokenization thread 5" java.lang.RuntimeException: java.lang.IllegalArgumentException: Word must not be null or empty
        at org.deeplearning4j.models.sequencevectors.transformers.impl.iterables.ParallelTransformerIterator$TokenizerThread.run(ParallelTransformerIterator.java:160)
Caused by: java.lang.IllegalArgumentException: Word must not be null or empty
        at org.deeplearning4j.models.word2vec.VocabWord.<init>(VocabWord.java:58)
        at org.deeplearning4j.models.sequencevectors.transformers.impl.iterables.ParallelTransformerIterator$TokenizerThread.run(ParallelTransformerIterator.java:148)
```

**Comment by raver119** [comment]
>Caused by: java.lang.IllegalArgumentException: Word must not be null or empty

Literally as is. You're trying to create VocabWord with empty string. And it fails.

**Comment by krazavet** [comment]
Thank you @raver119 for your quick answers :)

Last question: if I set up the model with `minWordFrequency(5)`. Does it mean that if I have a document with a content without a word with at least 5 occurrences, it won't be trained or the algorithm will skip this document out of the training?

Thx again

**Comment by raver119** [comment]
Word frequency is calculated over the whole corpus, so if you suddenly will face a document without a single word above that threshold it'll be equal to empty document. It will be just skipped.

**Comment by krazavet** [comment]
Okay @raver119 many thanks
