### ISSUE TITLE
RNTN Stack Trace - Issue when running 

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#300]
java.lang.IllegalStateException: Given ndarray does not have data type double
	at org.nd4j.linalg.factory.DataTypeValidation.assertDouble(DataTypeValidation.java:43) ~[nd4j-api-0.0.3.5.5.4.jar:na]
	at org.nd4j.linalg.jblas.BlasWrapper.scal(BlasWrapper.java:82) ~[nd4j-jblas-0.0.3.5.5.4.jar:na]
	at org.deeplearning4j.models.rntn.RNTN.backpropDerivativesAndError(RNTN.java:658) ~[deeplearning4j-nlp-0.0.3.3.4.alpha1-SNAPSHOT.jar:na]
	at org.deeplearning4j.models.rntn.RNTN.backpropDerivativesAndError(RNTN.java:623) ~[deeplearning4j-nlp-0.0.3.3.4.alpha1-SNAPSHOT.jar:na]
	at org.deeplearning4j.models.rntn.RNTN.access$100(RNTN.java:81) ~[deeplearning4j-nlp-0.0.3.3.4.alpha1-SNAPSHOT.jar:na]
o.d.t.c.t.TreeParser - More than one top level node for a treebank parse. Only accepting first input node.
o.d.m.rntn.RNTN - Working mini batch 0
o.d.p.Parallelization - Error occurred processing data

**Comment by agibsonccc** [comment]
Fixed.
