### ISSUE TITLE
cuDNN throws status == 3 exception

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3010]
Currently getting this on master:

```
[main] ERROR java.lang.Throwable - Exception in thread "main" java.lang.RuntimeException: cuDNN status = 3
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.layers.normalization.CudnnLocalResponseNormalizationHelper.checkCudnn(CudnnLocalResponseNormalizationHelper.java:56)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.layers.normalization.CudnnLocalResponseNormalizationHelper.activate(CudnnLocalResponseNormalizationHelper.java:187)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.layers.normalization.LocalResponseNormalization.activate(LocalResponseNormalization.java:141)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:103)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1112)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1002)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:158)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:57)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:752)
[main] ERROR java.lang.Throwable -     at ai.bernie.train.ClassifierTraining.run(ClassifierTraining.java:226)
[main] ERROR java.lang.Throwable -     at ai.bernie.train.ParallelOptimization.main(ParallelOptimization.java:125)
```

Worked on this with @raver119 and looks like cuDNN is thinking wrong params are set for it. Suggest @saudet have a look.

**Comment by saudet** [comment]
Yeah, sure, sample code?

**Comment by crockpotveggies** [comment]
@saudet can I email you a zipped repo?

**Comment by saudet** [comment]
Sure, thanks! Although a failing unit test would be ideal :)

**Comment by saudet** [comment]
With the changes in the PR above, we get a more informative message:
```
[main] ERROR java.lang.Throwable - Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Error: beta < CUDNN_LRN_MIN_BETA (1.0E-4 < 0.01)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:403)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.ClassifierTraining.run(ClassifierTraining.java:221)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.ParallelOptimization.main(ParallelOptimization.java:118)
[main] ERROR java.lang.Throwable - Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Error: beta < CUDNN_LRN_MIN_BETA (1.0E-4 < 0.01)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.parallelism.ParallelWrapper$Trainer.waitTillRunning(ParallelWrapper.java:814)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:401)
[main] ERROR java.lang.Throwable - 	... 2 more
[main] ERROR java.lang.Throwable - Caused by: java.lang.IllegalArgumentException: Error: beta < CUDNN_LRN_MIN_BETA (1.0E-4 < 0.01)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.layers.normalization.CudnnLocalResponseNormalizationHelper.activate(CudnnLocalResponseNormalizationHelper.java:196)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.layers.normalization.LocalResponseNormalization.activate(LocalResponseNormalization.java:141)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:103)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1116)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1006)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:158)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:57)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:872)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:837)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:690)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.parallelism.ParallelWrapper$Trainer.run(ParallelWrapper.java:778)
```
Now you know how to fix your code :)

**Comment by crockpotveggies** [comment]
That's super helpful thank you very much for updating this.
