### ISSUE TITLE
ModelSerializer throws IOException

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3013]
Every time I try to serialize a model (using 0.7.3-SNAPSHOT), I get the following:
```
[main] ERROR java.lang.Throwable - Exception in thread "main" java.io.IOException: Stream closed
[main] ERROR java.lang.Throwable - 	at java.util.zip.ZipOutputStream.ensureOpen(ZipOutputStream.java:97)
[main] ERROR java.lang.Throwable - 	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:190)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.util.ModelSerializer.writeModel(ModelSerializer.java:111)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.util.ModelSerializer.writeModel(ModelSerializer.java:54)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.ClassifierTraining.run(ClassifierTraining.java:260)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.ParallelOptimization.main(ParallelOptimization.java:127)
```

My usage is very simple, just serialization of a ComputationGraph
```
File locationToSave = new File(System.getProperty("user.home"), "saved-models/FaceNet-" + loggerName + "-" + i + ".zip");
ModelSerializer.writeModel(network, locationToSave, true);
```

**Comment by agibsonccc** [comment]
Didn't this get fixed?

**Comment by crockpotveggies** [comment]
This has been fixed. Closing.
