### ISSUE TITLE
ModelSerializer.writeModel fails on Android (non-x86) with  java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.flush()' on a null object reference

### ISSUE THREAD

**Issue by Cawfree** [deeplearning4j/deeplearning4j#3067]
Repeatable on Samsung Galaxy Tab A6.

Download and run this [repo](https://github.com/Cawfree/serialization-error-dl4j).

```
03-18 01:19:08.991 18342-18342/dl4j.cawfree.github.io.networkserializationerror E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                  Process: dl4j.cawfree.github.io.networkserializationerror, PID: 18342
                                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{dl4j.cawfree.github.io.networkserializationerror/dl4j.cawfree.github.io.networkserializationerror.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.flush()' on a null object reference
                                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3305)
                                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3401)
                                                                                                      at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                                      at android.app.ActivityThread.main(ActivityThread.java:7303)
                                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.flush()' on a null object reference
                                                                                                      at java.util.zip.DeflaterOutputStream.flush(DeflaterOutputStream.java:200)
                                                                                                      at org.deeplearning4j.util.ModelSerializer.writeModel(ModelSerializer.java:126)
                                                                                                      at dl4j.cawfree.github.io.networkserializationerror.MainActivity.onCreate(MainActivity.java:45)
                                                                                                      at android.app.Activity.performCreate(Activity.java:6904)
                                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3252)
                                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3401) 
                                                                                                      at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                                                      at android.app.ActivityThread.main(ActivityThread.java:7303) 
                                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 

```

**Comment by raver119** [comment]
Not quite sure how it's possible to be null for underlying buffer, but i've removed flush() call.

**Comment by Cawfree** [comment]
Hey Raver, thanks a lot. I know it's strange, I'll be glad to test it on my current setup. Sorry to ask, but how may I download your updated version?

**Comment by raver119** [comment]
The only way for now, is to build from sources manually.

**Comment by huitseeker** [comment]
@Cawfree have a look here: https://deeplearning4j.org/buildinglocally
And at the script there: https://github.com/deeplearning4j/deeplearning4j/blob/master/build-dl4j-stack.sh 
And shout in gitter if you need help :)

**Comment by huitseeker** [comment]
@Cawfree have a look here: https://deeplearning4j.org/buildinglocally
And at the script there: https://github.com/deeplearning4j/deeplearning4j/blob/master/build-dl4j-stack.sh 
And shout in [gitter](https://github.com/deeplearning4j/deeplearning4j/blob/master/build-dl4j-stack.sh) if you need help :)

**Comment by raver119** [comment]
Btw, i think it's good time to introduce some sort of android example in dl4j-examples repo, and some android emulator bundle, so we can test for such use cases..

**Comment by raver119** [comment]
I mean - there ARE some minor differences between dalvik jvm & oracle/openjdk jvm. So it would be nice to have some sort of test environment for it
