### ISSUE TITLE
NPE in Trainer UI

### ISSUE THREAD

**Issue by vlovsky** [deeplearning4j/deeplearning4j#3097]
I think happens after selecting input layer in the Model tab. Repeatable and coincides with the reporting cycle. Tried only on VAE and RBM NNs.

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[InvocationTargetException: null]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:151) [play-netty-server_2.11-2.4.6.jar:2.4.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:148) [play-netty-server_2.11-2.4.6.jar:2.4.6]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.6.jar:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at play.routing.RouterBuilderHelper$$anonfun$build$1$$anonfun$apply$1$$anonfun$5.apply(RouterBuilderHelper.scala:66) ~[play-java_2.11-2.4.6.jar:2.4.6]
	at play.routing.RouterBuilderHelper$$anonfun$build$1$$anonfun$apply$1$$anonfun$5.apply(RouterBuilderHelper.scala:62) ~[play-java_2.11-2.4.6.jar:2.4.6]
Caused by: java.lang.NullPointerException: null
	at java.lang.String.startsWith(String.java:1405) ~[na:1.8.0_121]
	at java.lang.String.startsWith(String.java:1434) ~[na:1.8.0_121]
	at org.deeplearning4j.ui.module.train.TrainModule.getLayerLearningRates(TrainModule.java:1171) ~[deeplearning4j-play_2.11-0.8.1-20170321.090621-1.jar:na]
	at org.deeplearning4j.ui.module.train.TrainModule.getModelData(TrainModule.java:778) ~[deeplearning4j-play_2.11-0.8.1-20170321.090621-1.jar:na]
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source) ~[na:na]

**Comment by AlexDBlack** [comment]
Fixed here: will be merged soon.
https://github.com/deeplearning4j/deeplearning4j/pull/3104
