### ISSUE TITLE
arbiter-classification-error

### ISSUE THREAD

**Issue by lfadljevic** [deeplearning4j/deeplearning4j#3108]
Hi guys,
I'm trying to set up an arbiter for classification and got weird error:
"Cannot get value: ParameterSpace index has not been set".

It constantly crashes at point runner.execute();
I tried to debug it, but only I have noticed is that something is wrong with index in IntegerParameterSpace class and I think that none of the parameters have managed to pass which I gave to the candidateGenerator.

 ```
Exception in thread "main" java.lang.IllegalStateException: Cannot get value: ParameterSpace index has not been set
	at org.deeplearning4j.arbiter.optimize.parameter.integer.IntegerParameterSpace.getValue(IntegerParameterSpace.java:78)
	at org.deeplearning4j.arbiter.optimize.parameter.integer.IntegerParameterSpace.getValue(IntegerParameterSpace.java:40)
	at org.deeplearning4j.arbiter.layers.FeedForwardLayerSpace.setLayerOptionsBuilder(FeedForwardLayerSpace.java:48)
	at org.deeplearning4j.arbiter.layers.GravesLSTMLayerSpace.setLayerOptionsBuilder(GravesLSTMLayerSpace.java:59)
	at org.deeplearning4j.arbiter.layers.GravesLSTMLayerSpace.getValue(GravesLSTMLayerSpace.java:54)
	at org.deeplearning4j.arbiter.layers.GravesLSTMLayerSpace.getValue(GravesLSTMLayerSpace.java:36)
	at org.deeplearning4j.arbiter.MultiLayerSpace.getValue(MultiLayerSpace.java:66)
	at org.deeplearning4j.arbiter.MultiLayerSpace.getValue(MultiLayerSpace.java:24)
	at org.deeplearning4j.arbiter.optimize.candidategenerator.RandomSearchGenerator.getCandidate(RandomSearchGenerator.java:57)
	at org.deeplearning4j.arbiter.optimize.runner.BaseOptimizationRunner.execute(BaseOptimizationRunner.java:146)
	at foo.ClassificationArbiterCPU.trainMultiInputNetwork(ClassificationArbiterCPU.java:107)
	at foo.CategoryArbiterCPURunner.main(CategoryArbiterCPURunner.java:25)
var code = "formatted";
```

I've prepared an example [repository](https://github.com/lfadljevic/arbiter-classification-error) with some data. Could you please check it out and see if you could reproduce the error? I'm developing under Ubuntu 16.04.

If you run foo.CategoryArbiterCPURunner class you should be able to reproduce the error.

**Comment by lfadljevic** [comment]
It looks like the error is present when you have more than 1 Integer ParameterSpace defined.
When I used just one for hidden width and fix integer value for tbptt parameter the error was gone.

**Comment by AlexDBlack** [comment]
Same issue as this, already fixed: https://github.com/deeplearning4j/Arbiter/issues/84
