### ISSUE TITLE
Possible race condition when using UI+PW

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3110]
When running ParallelWrapper with 16M inception model and UI backed by `FileStatsStorage` it would appear that some sort of race condition occurs in MapDB:

```
[ParallelWrapper trainer 1] INFO org.deeplearning4j.optimize.listeners.PerformanceListener - Device: [1]; iteration 31; iteration time: 405 ms; samples/sec: 103.704; batches/sec: 2.469; score: 9.103368770258069;
[main] ERROR java.lang.Throwable - Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.util.NoSuchElementException
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:404)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.TrainClassifier.run(TrainClassifier.java:223)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.TrainerRunner.main(TrainerRunner.java:120)
[main] ERROR java.lang.Throwable - Caused by: java.lang.RuntimeException: java.util.NoSuchElementException
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.parallelism.ParallelWrapper$Trainer.waitTillRunning(ParallelWrapper.java:802)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:402)
[main] ERROR java.lang.Throwable - 	... 2 more
[main] ERROR java.lang.Throwable - Caused by: java.util.NoSuchElementException
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.ui.stats.sbe.UpdateEncoder$PerParameterStatsEncoder$SummaryStatEncoder.next(UpdateEncoder.java:963)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.ui.stats.impl.SbeStatsReport.appendOrDefault(SbeStatsReport.java:357)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.ui.stats.impl.SbeStatsReport.encode(SbeStatsReport.java:751)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.ui.stats.impl.SbeStatsReport.encode(SbeStatsReport.java:611)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.ui.stats.impl.SbeStatsReport.encode(SbeStatsReport.java:897)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.ui.storage.mapdb.MapDBStatsStorage$PersistableSerializer.serialize(MapDBStatsStorage.java:330)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.ui.storage.mapdb.MapDBStatsStorage$PersistableSerializer.serialize(MapDBStatsStorage.java:322)
[main] ERROR java.lang.Throwable - 	at org.mapdb.StoreDirectAbstract.serialize(StoreDirectAbstract.kt:243)
[main] ERROR java.lang.Throwable - 	at org.mapdb.StoreWAL.put(StoreWAL.kt:379)
[main] ERROR java.lang.Throwable - 	at org.mapdb.HTreeMap.valueWrap(HTreeMap.kt:1208)
[main] ERROR java.lang.Throwable - 	at org.mapdb.HTreeMap.putprotected(HTreeMap.kt:344)
[main] ERROR java.lang.Throwable - 	at org.mapdb.HTreeMap.put(HTreeMap.kt:324)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.ui.storage.mapdb.MapDBStatsStorage.putUpdate(MapDBStatsStorage.java:142)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.ui.stats.BaseStatsListener.iterationDone(BaseStatsListener.java:539)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:69)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:872)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:837)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:690)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.parallelism.ParallelWrapper$Trainer.run(ParallelWrapper.java:766)
```

@AlexDBlack is the solution to drop MapDB, or is this an implementation issue on our end?

**Comment by raver119** [comment]
I think this was fixed long ago. If not - please let me know.
