### ISSUE TITLE
Input mismatch when replacing CenterLossOutputLayer with Transfer API

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3112]
When I try to replace a CenterLossOutputLayer via the Transfer learning API I get the following when running network.evaluate():

```
[main] ERROR java.lang.Throwable - Exception in thread "main" org.deeplearning4j.exception.DL4JInvalidInputException: Input that is not a matrix; expected matrix (rank 2), got rank 4 array with shape [48, 736, 1, 1]
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.layers.BaseLayer.preOutput(BaseLayer.java:367)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:393)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:103)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1116)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1086)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1171)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.graph.ComputationGraph.evaluate(ComputationGraph.java:2371)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.graph.ComputationGraph.evaluate(ComputationGraph.java:2337)
[main] ERROR java.lang.Throwable -     at org.deeplearning4j.nn.graph.ComputationGraph.evaluate(ComputationGraph.java:2327)
[main] ERROR java.lang.Throwable -     at ai.bernie.train.TrainClassifier.run(TrainClassifier.java:199)
[main] ERROR java.lang.Throwable -     at ai.bernie.train.TrainerRunner.main(TrainerRunner.java:121)
```

Here's how I'm using it:
```
        FineTuneConfiguration fineTuneConf = new FineTuneConfiguration.Builder()
                .learningRate(learningRate)
                .learningRatePolicy(LearningRatePolicy.None)
                .build();

        ComputationGraph transferredModel = new TransferLearning.GraphBuilder(oldModel)
                .fineTuneConfiguration(fineTuneConf)
                .removeVertexKeepConnections("lossLayer") //replace the functionality of the final vertex
                .setFeatureExtractor("dropout")
                .addLayer("lossLayer", new CenterLossOutputLayer.Builder()
                        .lossFunction(LossFunctions.LossFunction.MCXENT)
                        .activation(Activation.SOFTMAX)
                        .nIn(736).nOut(numLabels).lambda(1e-4).alpha(0.9)
                        .gradientNormalization(GradientNormalization.RenormalizeL2PerLayer)
                        .build(), "dropout")
                .build();
```

The layer before CL output is a dropout layer. However, I'd imagine the shape here is not related. Note that I've tried this with `loadUpdater` set to either true or false.

@eraly hopefully it's something I'm doing wrong?

**Comment by eraly** [comment]
Can you post json conf for the oldModel and the transferredModel?

It's complaining about a shape mismatch I think at the losslayer. It would probably go away if a preprocessor was manually added. But I am just wondering what the shape out of the dropout layer was in the oldModel. I can tell that and if there were any preprocessors that ended up not being transferred over from the json.

**Comment by AlexDBlack** [comment]
I was able to reproduce this with the code below.
The solution seems to be simply adding a .setInputType() call...
@crockpotveggies if that's sufficient (or, unless anyone disagrees) I think we can close this?

```
        ComputationGraphConfiguration c = new NeuralNetConfiguration.Builder()
                .graphBuilder()
                .addInputs("in")
                .addLayer("l0", new ConvolutionLayer.Builder().nIn(1).nOut(1).convolutionMode(ConvolutionMode.Same).build(), "in")
                .addLayer("dropout", new DropoutLayer.Builder(0.5).build(), "l0")
                .addLayer("cl", new CenterLossOutputLayer.Builder(LossFunctions.LossFunction.MCXENT).nIn(28*28*1).nOut(10).build(), "dropout")
                .setOutputs("cl")
                .build();

        ComputationGraph oldModel = new ComputationGraph(c);
        oldModel.init();

        int numLabels = 10;
        double learningRate = 0.1;

        FineTuneConfiguration fineTuneConf = new FineTuneConfiguration.Builder()
                .learningRate(learningRate)
                .learningRatePolicy(LearningRatePolicy.None)
                .build();

        ComputationGraph transferredModel = new TransferLearning.GraphBuilder(oldModel)
                .fineTuneConfiguration(fineTuneConf)
                .removeVertexKeepConnections("lossLayer") //replace the functionality of the final vertex
                .setFeatureExtractor("dropout")
                .addLayer("lossLayer", new CenterLossOutputLayer.Builder()
                        .lossFunction(LossFunctions.LossFunction.MCXENT)
                        .activation(Activation.SOFTMAX)
                        .nIn(28*28*1)
                        .nOut(numLabels).lambda(1e-4).alpha(0.9)
                        .gradientNormalization(GradientNormalization.RenormalizeL2PerLayer)
                        .build(), "dropout")
                .setInputTypes(InputType.convolutional(28,28,1))        //*** Remove this line, get the exception ***
                .build();


        transferredModel.output(Nd4j.create(1,1,28,28));
```

**Comment by crockpotveggies** [comment]
Ah yes I believe that's how I solved it, too, when I made a later attempt at this. I'm going to close this for now, but let's reopen it if we think it's a usability issue.
