### ISSUE TITLE
MultiTimestepRegressionExample with multicolumn input data

### ISSUE THREAD

**Issue by raver1975** [deeplearning4j/deeplearning4j#3120]
I'm trying to run the MultiTimestepRegressionExample with an input file with multiple columns. I'm feeding it a dummy csv file which looks like this:
1,1,1
0,0,0
1,1,1
0,0,0
etc...

Program crashes with this error:
Exception in thread "main" java.lang.IllegalStateException: Mis matched shapes
	at org.nd4j.linalg.util.LinAlgExceptions.assertSameShape(LinAlgExceptions.java:45)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:3071)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:3050)
	at org.deeplearning4j.eval.RegressionEvaluation.eval(RegressionEvaluation.java:110)
	at org.deeplearning4j.eval.BaseEvaluation.evalTimeSeries(BaseEvaluation.java:28)
	at org.deeplearning4j.eval.BaseEvaluation.evalTimeSeries(BaseEvaluation.java:19)
	at com.klemstinegroup.wub.ai.regression.MultiTimestepRegressionExample.main(MultiTimestepRegressionExample.java:153)

I know this isn't a burning issue, but I do appreciate your help with this. Thank you!

**Comment by eraly** [comment]
Will you post a gist with your code in it and also a few lines from the csv thats being read?

**Comment by raver1975** [comment]
The code is almost exactly the example, just modified to use my local paths:
https://gist.github.com/raver1975/6059779fa6cf42b6551fcd3ec8bc7203

I'm just feeding it a dummy csv file at the moment, which consists of 5000 lines of:
0,0,0
1,1,1
0,0,0
1,1,1
...

**Comment by vlovsky** [comment]
The argument for this call here: https://github.com/deeplearning4j/dl4j-examples/blob/0d7ff1969a5b955e3d775ffb5f37386f9f8e25ab/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/regression/MultiTimestepRegressionExample.java#L148 should probably be **numOfVariables** like this: https://gist.github.com/anonymous/ab45c27e8aa0b5e8bd4a7c1680349989

**Comment by raver1975** [comment]
That seems to have fixed it, it looks like it will run without crashing now. Thank's much for your help. 
I'll let you close this issue, as you may want to update the examples with your fix.
