### ISSUE TITLE
Add informative warning for importing Keras 2 models

### ISSUE THREAD

**Issue by turambar** [deeplearning4j/deeplearning4j#3128]
Support for [Keras 2](https://blog.keras.io/introducing-keras-2.html) may take some time so let's do a version check when importing and gracefully die with an informative warning (this will head off a bunch of redundant issues).

**Comment by elusive-code** [comment]
Oh, +1, I didn't know Keras 2 models are not supported.
I actually have problem loading keras model, and failing to find solution online was going to post an issue, when found this one. 

Well, it's not really relevant now, but just in case, here's an error I get.
(I'm using Keras 2.0.2)

```
Caused by: java.lang.RuntimeException: Unknown exception.
	at org.bytedeco.javacpp.hdf5$H5File.allocate(Native Method)
	at org.bytedeco.javacpp.hdf5$H5File.<init>(hdf5.java:12713)
	at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.<init>(Hdf5Archive.java:60)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.modelHdf5Filename(KerasModel.java:549)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:155)
	at su.opencode.rupost.postman.estimation.service.ReportMLServiceImpl.loadDeliveryTimeModel(ReportMLServiceImpl.java:81)
	at su.opencode.rupost.postman.estimation.service.ReportMLServiceImpl.init(ReportMLServiceImpl.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 67 more

Disconnected from the target VM, address: 'javadebug', transport: 'shared memory'
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: C:\autotest\HDF5110ReleaseRWDITAR\src\H5F.c line 579 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: C:\autotest\HDF5110ReleaseRWDITAR\src\H5Fint.c line 1208 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: C:\autotest\HDF5110ReleaseRWDITAR\src\H5Fsuper.c line 273 in H5F__super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
```

**Comment by tulay** [comment]
The exception I get when trying to import Keras 2 model: 
`Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.InvalidKerasConfigurationException: Could not determine number of outputs for layer: no output_dim or nb_filter field found. For more information, see http://deeplearning4j.org/model-import-keras.`
Unfortunately, the link mentioned here has no information about the keras version supported.

**Comment by maxpumperla** [comment]
@tulay there's an open PR right now that will address this, see #3831

**Comment by maxpumperla** [comment]
keras 2 is now fully supported, closing.

**Comment by schrum2** [comment]
In what version of DL4J is this Keras import bug fixed? What do I put in my pom file? Is the fix currently only in a SNAPSHOT?

**Comment by maxpumperla** [comment]
@schrum2 master build only for now
