### ISSUE TITLE
Better handling for non existing data in BaseImageRecordReader and/or FileSplit

### ISSUE THREAD

**Issue by vlovsky** [deeplearning4j/deeplearning4j#3130]
To prevent stale exceptions, add checks for non-existent data either in the FileSplit.sample() (and all siblings) or BaseImageRecordReader.initialize(), or both. Got following exception when accidentally misspelled training data folder. This doesn't point to what's actually wrong.

o.d.e.m.MultiGpuObjectsClassification - Load data....
o.d.e.m.MultiGpuObjectsClassification - Build model....
o.d.e.m.MultiGpuObjectsClassification - Train model....
Exception in thread "main" java.lang.RuntimeException: Exception thrown in base iterator
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.next(AsyncDataSetIterator.java:247)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.next(AsyncDataSetIterator.java:33)
	at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:353)
	at org.deeplearning4j.examples.multigpu.MultiGpuObjectsClassification.run(MultiGpuObjectsClassification.java:171)
	at org.deeplearning4j.examples.multigpu.MultiGpuObjectsClassification.main(MultiGpuObjectsClassification.java:319)
Caused by: java.lang.IllegalStateException: Indeterminant state: record must not be null, or a file iterator must exist
	at org.datavec.image.recordreader.BaseImageRecordReader.hasNext(BaseImageRecordReader.java:247)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.hasNext(RecordReaderDataSetIterator.java:406)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:171)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:411)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:53)
	at org.deeplearning4j.datasets.iterator.MultipleEpochsIterator.next(MultipleEpochsIterator.java:120)
	at org.deeplearning4j.datasets.iterator.MultipleEpochsIterator.next(MultipleEpochsIterator.java:143)
	at org.deeplearning4j.datasets.iterator.MultipleEpochsIterator.next(MultipleEpochsIterator.java:37)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$IteratorRunnable.run(AsyncDataSetIterator.java:322)

**Comment by agibsonccc** [comment]
You fixed this.
