### ISSUE TITLE
NPE parallelwrapper on current master 

### ISSUE THREAD

**Issue by kepricon** [deeplearning4j/deeplearning4j#3145]
I am running [W2Vsentiment cuda example](https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/w2vsentiment)

It shows NPE at pw.fit() like below
```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:377)
	at org.deeplearning4j.examples.multigpu.w2vsentiment.Word2VecSentimentRNN.main(Word2VecSentimentRNN.java:107)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.deeplearning4j.parallelism.trainer.DefaultTrainer.waitTillRunning(DefaultTrainer.java:243)
	at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:375)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.deeplearning4j.parallelism.trainer.DefaultTrainer.run(DefaultTrainer.java:196)
```

here is the [full stack trace](https://gist.github.com/kepricon/77ea9011fae3854b2e06f73f9d8f9551)

@raver119 @agibsonccc  do you have any idea?

**Comment by raver119** [comment]
I'm slightly behind current master for dl4j ;( it looks @agibsonccc merged his changes to pw

**Comment by kepricon** [comment]
yup 
I pulled dl4j repo this morning.

**Comment by kepricon** [comment]
@agibsonccc thanks
