### ISSUE TITLE
Null pointer exception while trying to build a deep q learning network using rl4j for a custom mdp

### ISSUE THREAD

**Issue by taraliza** [deeplearning4j/deeplearning4j#3168]
#### Issue Description
While trying to implement deep q-learning, using the rl4j libraries, for a custom model, which implements the MDP interface, I encountered a null pointer exception.
I referred to the examples in rl4j since I could not find any other documentation for it.
My code is as below (and is very similar to the code in the rl4j toy example).

```
public static MyModel createNewModel(){
	System.out.println("Creating a new model");
	MyModel newModel = new MyModel();
	return newModel;
}
/*Q Learning Code*/
public static QLearning.QLConfiguration TOY_QL =
     new QLearning.QLConfiguration(
          123,   //Random seed
          100000,//Max step By epoch
          80000, //Max step
          10000, //Max size of experience replay
          32,    //size of batches
          100,   //target update (hard)
          0,     //num step noop warmup
          0.05,  //reward scaling
          0.99,  //gamma
          10.0,  //td-error clipping
          0.1f,  //min epsilon
          2000,  //num step for eps greedy anneal
          true   //double DQN
      );
            
 public static DQNFactoryStdDense.Configuration TOY_NET =
             DQNFactoryStdDense.Configuration.builder()
        .l2(0.01).learningRate(1e-2).numLayer(3).numHiddenNodes(16).build();

public static void simpleModel(){ 

//record the training data in rl4j-data in a new folder
DataManager manager = new DataManager();

//define the mdp from toy (toy length)
MyModel mdp = createNewModel();

//define the training method

QLearningDiscreteDense dql = new QLearningDiscreteDense<MyStateObs>(mdp, TOY_NET, TOY_QL, manager);
//Learning<MyStateObs, Integer, DiscreteSpace, IDQN> dql = new QLearningDiscreteDense<MyStateObs>(mdp, TOY_NET, TOY_QL, manager);

//enable some logging for debug purposes on toy mdp
//mdp.setFetchable(dql);

//start the training
dql.train();

mdp.close();
} 
```

I call simpleModel() to start the program execution.
MyModel is an mdp which implements the interface MDP as below.
public class MyModel implements MDP<MyStateObs, Integer, DiscreteSpace> {...)

I was thinking this sufficient to get rl4j working for my model. However, I am getting the NPE below:

```
Creating a new model
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 2
o.n.n.Nd4jBlas - Number of threads used for BLAS: 2
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [4]; Memory: [0.9GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
DQNFactoryStdDense.Configuration(numLayer=3, numHiddenNodes=16, learningRate=0.01, l2=0.01)
Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.rl4j.network.dqn.DQNFactoryStdDense.buildDQN(DQNFactoryStdDense.java:42)
	at org.deeplearning4j.rl4j.network.dqn.DQNFactoryStdDense.buildDQN(DQNFactoryStdDense.java:21)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscreteDense.<init>(QLearningDiscreteDense.java:25)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscreteDense.<init>(QLearningDiscreteDense.java:29)
	at testdl4j_tara.CustomExperiment.simpleModel(CustomExperiment.java:197)
	at testdl4j_tara.CustomExperiment.run(CustomExperiment.java:123)
```

Please let me know if I am missing any steps, or please add some documentation that would give me an idea of what I need to update/add in this code to make it work. Thanks a lot!!

**Comment by saudet** [comment]
Please try again with version 1.0.0-alpha, and if it's still an issue, reopen the issue, thanks!
