### ISSUE TITLE
Missing Mixture of Experts 

### ISSUE THREAD

**Issue by AJku7** [deeplearning4j/deeplearning4j#3179]
It would be nice to add features to support Mixture of Experts network.
Example" I am building a complex network where I want to use multiple trained models to make a new prediction.

I tried extracting each layer from the saved model but it would end up having multiple Outputs layer in the network leading to Exception.
`Exception in thread "main" java.lang.IllegalStateException: Cannot do forward pass: inputs not set
	at org.deeplearning4j.nn.graph.vertex.impl.MergeVertex.doForward(MergeVertex.java:77)
	at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1069)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:963)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:151)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:54)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:781)
at com.expert.sample.Test.main(Test.java:137)`

**Comment by AlexDBlack** [comment]
FYI That exception basically means that your network configuration isn't valid (and, wasn't picked up for some reason during the earlier configuration validation stage when building the ComputationGraphConfiguration).

**Comment by AJku7** [comment]
yes that's because I have 3 separate models each having output layer and combining them by merging and feeding to output layer of new computation graph is giving this error.So i thought a new functionality to merge separate models.or Say feeding outputs from separate models would be helpful.
I am adding my complete setup  where (L04,L14,L24,L34) are output layers from separate saved models.
[Computation graph combining multiple models](https://gist.github.com/AJku7/26ef6195ad560291f18c0bf91b1545b1)

**Comment by AJku7** [comment]
I am trying to merge different classifiers to make new classification.So a new functionality that allows to merge pre-trained models and providing these pre-trained models as input to Output layer of computation graph would be helpful.

**Comment by agibsonccc** [comment]
Closing — this issue is over 7 years old with no recent activity. The codebase has undergone a major rewrite. If this is still relevant, please open a new issue with current reproduction steps.
