### ISSUE TITLE
CifarDataSetIterator ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kepricon** [deeplearning4j/deeplearning4j#3198]
cifar dataset iterator has this issue.

```
        int height = 224;
        int width = 224;
        int channels = 3;
        int batchSize = 32;
        int totalExamples = CifarLoader.NUM_TRAIN_IMAGES;
        DataSetIterator iter = new CifarDataSetIterator(batchSize, totalExamples, new int[] {height, width, channels});
        iter.next();
```

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 100353
	at org.datavec.image.loader.CifarLoader.convertMat(CifarLoader.java:320)
	at org.datavec.image.loader.CifarLoader.convertDataSet(CifarLoader.java:339)
	at org.datavec.image.loader.CifarLoader.next(CifarLoader.java:424)
	at org.datavec.image.loader.CifarLoader.next(CifarLoader.java:392)
	at org.deeplearning4j.datasets.iterator.impl.CifarDataSetIterator.next(CifarDataSetIterator.java:110)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:389)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:52)
	at org.deeplearning4j.benchmarks.BenchmarkCifar.run(BenchmarkCifar.java:88)
	at org.deeplearning4j.benchmarks.BenchmarkCifar.main(BenchmarkCifar.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by kepricon** [comment]
https://github.com/deeplearning4j/DataVec/blob/master/datavec-data/datavec-data-image/src/main/java/org/datavec/image/loader/CifarLoader.java#L57

https://github.com/deeplearning4j/DataVec/blob/master/datavec-data/datavec-data-image/src/main/java/org/datavec/image/loader/CifarLoader.java#L335

let me investigate it.

**Comment by crockpotveggies** [comment]
I've discovered that when this happens, it means the batch size chosen for the dataset size doesn't align and ultimately the iterator will fail because there's a remainder on the very last iteration. It expects more data.

To describe:
If I say I want total images of 27, I should choose a batch size of 9 because `27 % 9 == 0`. However if I choose 10, there's a remainder of 7, because the last remaining batch is only size 7.

**Comment by kepricon** [comment]
solved this issue
see : https://github.com/deeplearning4j/DataVec/pull/234
