### ISSUE TITLE
ParallelWrapper with .useMQ(true) leads ND4JIllegalStateException

### ISSUE THREAD

**Issue by kepricon** [deeplearning4j/deeplearning4j#3199]
with .useMQ(ture) ends with below

```
o.d.o.l.ScoreIterationListener - Score at iteration 300 is 5.351529730795364
o.d.o.l.ScoreIterationListener - Score at iteration 310 is 5.355756684021423
o.d.o.l.ScoreIterationListener - Score at iteration 320 is 5.354928013496566
o.d.o.s.BaseOptimizer - Hit termination condition on iteration 0: score=5.352137738280914, oldScore=5.3521828492207915, condition=org.deeplearning4j.optimize.terminations.EpsTermination@12711fee
o.d.o.l.ScoreIterationListener - Score at iteration 330 is 5.354945527418203
o.d.o.l.ScoreIterationListener - Score at iteration 340 is 5.355727887464246
o.d.p.ParallelWrapper - Averaged score: 5.3559037022380505
o.d.o.l.ScoreIterationListener - Score at iteration 350 is 5.353457404382378
o.d.o.l.ScoreIterationListener - Score at iteration 360 is 5.35618122926954
o.d.o.l.ScoreIterationListener - Score at iteration 370 is 5.3478495629624465
o.d.o.l.ScoreIterationListener - Score at iteration 380 is 5.353274568538434
o.d.o.l.ScoreIterationListener - Score at iteration 390 is 5.356506504665816
o.d.o.l.ScoreIterationListener - Score at iteration 400 is 5.356248429876356
o.d.o.l.ScoreIterationListener - Score at iteration 410 is 5.354987430497932
o.d.p.ParallelWrapper - Averaged score: 5.352096503255497
o.d.o.l.ScoreIterationListener - Score at iteration 420 is 5.3555561666344875
o.d.o.l.ScoreIterationListener - Score at iteration 430 is 5.353143296345379
o.d.o.l.ScoreIterationListener - Score at iteration 440 is 5.353261968599063
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: You can't have NULL as DataSet
    at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:356)
    at org.deeplearning4j.benchmarks.BaseBenchmark.benchmark(BaseBenchmark.java:104)
    at org.deeplearning4j.benchmarks.BaseBenchmark.benchmarkCNN(BaseBenchmark.java:39)
    at org.deeplearning4j.benchmarks.BenchmarkTinyImageNet.run(BenchmarkTinyImageNet.java:92)
    at org.deeplearning4j.benchmarks.BenchmarkTinyImageNet.main(BenchmarkTinyImageNet.java:96)
o.d.o.l.ScoreIterationListener - Score at iteration 450 is 5.35441419266791
```

after the above exception, the first worker dead and training is stalled .

this is my confiuration for PW.
```
int numGPUs = 7;
ParallelWrapper pw = new ParallelWrapper.Builder<>(model)
                        .prefetchBuffer(numGPUs)
                        .reportScoreAfterAveraging(true)
                        .averagingFrequency(10)
                        .useLegacyAveraging(false)
                        .useMQ(true)
                        .workers(numGPUs)
                        .build();
```

@raver119 I am reporting what we discussed yesterday.

**Comment by raver119** [comment]
Thanks!

**Comment by crockpotveggies** [comment]
I believe this is now fixed? @raver119 ?
