### ISSUE TITLE
Frozen layers don't work with UI

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3203]
```java
        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .list()
                .layer(0, new DenseLayer.Builder().nIn(10).nOut(10).build())
                .layer(1, new OutputLayer.Builder().nIn(10).nOut(10).build()).build();

        MultiLayerNetwork net = new MultiLayerNetwork(conf);
        net.init();


        MultiLayerNetwork net2 = new TransferLearning.Builder(net)
                .fineTuneConfiguration(new FineTuneConfiguration.Builder()
                .learningRate(0.01).build())
                .setFeatureExtractor(0)
                .build();

        File f = new File("Temp.bin");
        net2.setListeners(new StatsListener(new FileStatsStorage(f)));

        net2.fit(new DataSet(Nd4j.rand(8,10), Nd4j.rand(8,10)));
```

```
java.util.NoSuchElementException
	at org.deeplearning4j.ui.stats.sbe.UpdateEncoder$PerParameterStatsEncoder$SummaryStatEncoder.next(UpdateEncoder.java:963)
	at org.deeplearning4j.ui.stats.impl.SbeStatsReport.appendOrDefault(SbeStatsReport.java:357)
	at org.deeplearning4j.ui.stats.impl.SbeStatsReport.encode(SbeStatsReport.java:751)
	at org.deeplearning4j.ui.stats.impl.SbeStatsReport.encode(SbeStatsReport.java:611)
	at org.deeplearning4j.ui.stats.impl.SbeStatsReport.encode(SbeStatsReport.java:897)
	at org.deeplearning4j.ui.storage.mapdb.MapDBStatsStorage$PersistableSerializer.serialize(MapDBStatsStorage.java:330)
	at org.deeplearning4j.ui.storage.mapdb.MapDBStatsStorage$PersistableSerializer.serialize(MapDBStatsStorage.java:322)
	at org.mapdb.StoreDirectAbstract.serialize(StoreDirectAbstract.kt:243)
	at org.mapdb.StoreWAL.put(StoreWAL.kt:379)
	at org.mapdb.HTreeMap.valueWrap(HTreeMap.kt:1208)
	at org.mapdb.HTreeMap.putprotected(HTreeMap.kt:344)
	at org.mapdb.HTreeMap.put(HTreeMap.kt:324)
	at org.deeplearning4j.ui.storage.mapdb.MapDBStatsStorage.putUpdate(MapDBStatsStorage.java:142)
	at org.deeplearning4j.ui.stats.BaseStatsListener.iterationDone(BaseStatsListener.java:539)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:69)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1426)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1395)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1472)
	at org.deeplearning4j.ui.stats.TestTransferStatsCollection.test(TestTransferStatsCollection.java:44)
```

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/3205
