### ISSUE TITLE
CnnSentenceDataSetIterator remove unknown words causes ND4JIllegalStateException

### ISSUE THREAD

**Issue by rj93** [deeplearning4j/deeplearning4j#3254]
#### Issue Description

When the iterator has a sentence where the word vector does not know any of the words and `unknownWordHandling` is set to `removeWord`, `tokenizeSentence` returns an empty array. This then causes the following stack trace:

	Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: Invalid shape: Requested INDArray shape [1, 0] contains dimension size values < 1 (all dimensions must be 1 or more)
		at org.nd4j.linalg.factory.Nd4j.checkShapeValues(Nd4j.java:4776)
		at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3997)
		at org.nd4j.linalg.api.ndarray.BaseNDArray.create(BaseNDArray.java:1906)
		at org.nd4j.linalg.api.ndarray.BaseNDArray.subArray(BaseNDArray.java:2064)
		at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:4015)
		at org.deeplearning4j.iterator.CnnSentenceDataSetIterator.next(CnnSentenceDataSetIterator.java:282)
		at org.deeplearning4j.iterator.CnnSentenceDataSetIterator.next(CnnSentenceDataSetIterator.java:200)
		at org.deeplearning4j.iterator.CnnSentenceDataSetIterator.next(CnnSentenceDataSetIterator.java:47)
		at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$IteratorRunnable.run(AsyncDataSetIterator.java:322)

Is there a solution to this?

#### Version Information

* Deeplearning4j version: 0.8.0
* platform information (OS, etc): Windows 10

**Comment by raver119** [comment]
Not sure, what kind of solution would you expect here. Use other option, not removeWord?

**Comment by AlexDBlack** [comment]
Right, not solution is possible here for that case.
However, a better exception/error message and *maybe* the option to skip empty sentences would be good.

**Comment by tripathysa** [comment]
I am also getting same issues with a large sentiment dataset. What would be the solution? any idea?

**Comment by tripathysa** [comment]
Same  org.nd4j.linalg.exception.ND4JIllegalStateException: Invalid shape: Requested INDArray shape [1, 0] contains dimension size values < 1 (all dimensions must be 1 or more)

**Comment by tripathysa** [comment]
@raver119 @AlexDBlack Did you get any solution for the same?

**Comment by AlexDBlack** [comment]
There's configuration for how unknown words should be handled:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/iterator/CnnSentenceDataSetIterator.java#L455-L462

We still haven't got a good proposal/solution here for what should actually be done in this case, other  than maybe skipping empty sentences.

**Comment by tripathysa** [comment]
For now I have used UseUnknownVector instead of RemoveWord to avoid the error.

**Comment by AlexDBlack** [comment]
Turns out this was actually fixed some time ago - we have a test for exactly that situation here:
https://github.com/deeplearning4j/deeplearning4j/blob/09c2979cf875a796c51ec9f34cfa22b0180b2fae/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/test/java/org/deeplearning4j/iterator/TestCnnSentenceDataSetIterator.java#L170-L226
