### ISSUE TITLE
Error importing Keras LSTM model -- "Invalid input for RNN layer"

### ISSUE THREAD

**Issue by neutralino** [deeplearning4j/deeplearning4j#3275]
#### Issue Description

I'm trying to import a basic Keras LSTM model:
```python
(X_train, y_train), (X_test, y_test) = imdb.load_data(nb_words=5000)
X_train = sequence.pad_sequences(X_train, maxlen=500)
X_test = sequence.pad_sequences(X_test, maxlen=500)
model = Sequential()
model.add(Embedding(5000, 32, input_length=500))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, nb_epoch=1, batch_size=64)
model.save_weights("model_weights_file.h5")
with open("model_file.json", "w") as f_out:
    f_out.write(model.to_json())
```
When importing via:
```java
MultiLayerNetwork model = KerasModelImport.importKerasSequentialModelAndWeights(modelJsonPath, weightsH5Path, false);
```
I get this error:
```
Exception in thread "main" java.lang.IllegalStateException: Invalid input for RNN layer (layer index = -1, layer name = "lstm_1"): expect RNN input type with size > 0. Got: InputTypeFeedForward(32)
	at org.deeplearning4j.nn.conf.layers.BaseRecurrentLayer.getOutputType(BaseRecurrentLayer.java:21)
	at org.deeplearning4j.nn.modelimport.keras.layers.KerasLstm.getOutputType(KerasLstm.java:119)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.helperInferOutputTypes(KerasModel.java:286)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:129)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:56)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.buildSequential(KerasModel.java:581)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:216)
```

Thanks for any help.

#### Version Information

* Deeplearning4j version: 0.8.0
* Keras version: 1.2.2

**Comment by neil-boyette-ibm** [comment]
Any updates on this? I'm running into the exact same type of error when trying to use an LSTM model that we trained.

**Comment by ChrisYohann** [comment]
I have the same problem trying to import an LSTM model. Any iupdates on this ?

**Comment by tomthetrainer** [comment]
@turambar do you have any insight on this?

**Comment by turambar** [comment]
@tomthetrainer best guess: we're having trouble inferring the input type and shape from the Embedding layer. I need someone @neutralino @neil-boyette-ibm @ChrisYohann) to post a simple model config JSON so I can step through this in a debugger.

Context: for Keras Sequential models, we have to infer the input shape based on the configuration of the first Keras layer, in this case an Embedding. Keras Embedding layers behave a little differently from other Keras layers (in terms of defining their input shape, etc.), and we've previously had some problems with that.

**FYI, easiest potential fix: just use the Keras Functional API. The Functional API forces you to explicitly define your input layer shapes, and that makes import WAY easier.**

**Comment by neutralino** [comment]
@turambar - thanks for the tip.  Here's the JSON for the above model:
```
{
  "class_name": "Sequential",
  "keras_version": "1.2.2",
  "config": [
    {
      "class_name": "Embedding",
      "config": {
        "trainable": true,
        "name": "embedding_1",
        "activity_regularizer": null,
        "W_constraint": null,
        "init": "uniform",
        "input_dtype": "int32",
        "mask_zero": false,
        "input_dim": 5000,
        "batch_input_shape": [
          null,
          500
        ],
        "W_regularizer": null,
        "dropout": 0,
        "output_dim": 32,
        "input_length": 500
      }
    },
    {
      "class_name": "LSTM",
      "config": {
        "U_regularizer": null,
        "name": "lstm_1",
        "inner_activation": "hard_sigmoid",
        "go_backwards": false,
        "activation": "tanh",
        "trainable": true,
        "unroll": false,
        "consume_less": "cpu",
        "stateful": false,
        "init": "glorot_uniform",
        "inner_init": "orthogonal",
        "dropout_U": 0,
        "dropout_W": 0,
        "input_dim": 32,
        "return_sequences": false,
        "b_regularizer": null,
        "W_regularizer": null,
        "output_dim": 100,
        "forget_bias_init": "one",
        "input_length": null
      }
    },
    {
      "class_name": "Dense",
      "config": {
        "W_constraint": null,
        "b_constraint": null,
        "name": "dense_1",
        "activity_regularizer": null,
        "trainable": true,
        "init": "glorot_uniform",
        "bias": true,
        "input_dim": 100,
        "b_regularizer": null,
        "W_regularizer": null,
        "activation": "sigmoid",
        "output_dim": 1
      }
    }
  ]
}
```

**Comment by maxpumperla** [comment]
@neutralino so, does the import work following @turambar 's tip?

**Comment by maxpumperla** [comment]
we fixed this with https://github.com/deeplearning4j/deeplearning4j/pull/4053 and have unit test for it. closing this. let me know in case you still have problems, thanks!

**Comment by okalitova** [comment]
@turambar 's solution with Functional API didn't work for me. Waiting to see this patch in stable release!
