### ISSUE TITLE
Regression in 0.8.0 with ParagraphVector inferVector

### ISSUE THREAD

**Issue by nschimme** [deeplearning4j/deeplearning4j#3290]
#### Issue Description

I've noticed in DL4J 0.8.0 that there has been a regression with the ParagraphVector inferVector(List<VocabWord> document) method with a provided w2v model.

The bug is that we're not calling the following code like the other inferVector() methods:
```
      if (this.vocab == null || this.vocab.numWords() == 0)
            reassignExistingModel();
```

The result is that syn0 won't be initialized and a NPE is thrown:

```
2017-04-21 10:23:36 INFO  main  SequenceVectors:160 - Building learning algorithms:
2017-04-21 10:23:36 INFO  main  SequenceVectors:168 -           building SequenceLearningAlgorithm: [PV-DM]

java.lang.NullPointerException: syn0

	at org.nd4j.linalg.api.ops.aggregates.impl.AggregateCBOW.<init>(AggregateCBOW.java:67)
	at org.nd4j.linalg.api.ops.aggregates.impl.AggregateCBOW.<init>(AggregateCBOW.java:39)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.CBOW.iterateSample(CBOW.java:168)
	at org.deeplearning4j.models.embeddings.learning.impl.sequence.DM.dm(DM.java:137)
	at org.deeplearning4j.models.embeddings.learning.impl.sequence.DM.inferSequence(DM.java:179)
	at org.deeplearning4j.models.paragraphvectors.ParagraphVectors.inferVector(ParagraphVectors.java:245)
	at org.deeplearning4j.models.paragraphvectors.ParagraphVectors.inferVector(ParagraphVectors.java:278)
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 0.8.0

#### Contributing

I'll try to fix this and also add a unit test for this method

**Comment by nschimme** [comment]
I have a small 20KB Gensim model here if anyone is able to add it to the unit test.

[model0.zip](https://github.com/deeplearning4j/deeplearning4j/files/949429/model0.zip)

**Comment by nschimme** [comment]
FYI I gave up on the unit test. I can't figure out how to wire up or add to the existing resources in ParagraphVectorTest
