### ISSUE TITLE
Transfer API: ClassCast exception w/ FrozenLayer and UI

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3327]
#### Issue Description

Looks like an incorrect annotation or Jackson issue after using the Transfer API.

```
[main] ERROR java.lang.Throwable - Exception in thread "main" java.lang.ClassCastException: org.deeplearning4j.nn.layers.FrozenLayer cannot be cast to org.deeplearning4j.nn.layers.convolution.ConvolutionLayer
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.ui.weights.ConvolutionalIterationListener.iterationDone(ConvolutionalIterationListener.java:164)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:68)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:57)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:810)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.TrainClassifier.run(TrainClassifier.java:207)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.TrainerRunner.run(TrainerRunner.java:148)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.TrainerRunner.main(TrainerRunner.java:193)
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j MASTER
* Ubuntu
* CUDA 8

#### Contributing

@eraly want me to take a look at this?

**Comment by eraly** [comment]
Yes please.
