### ISSUE TITLE
n

### ISSUE THREAD

**Issue by arunzz** [deeplearning4j/deeplearning4j#3362]
#### ISparkword2vec
Please describe our issue, along with:
- should return model trained 
- encountered behavior - stuck at nd4j parameter

#### Version Information - 0.8.0

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - 0.8.0
* platform information (OS, etc) - linuz x86 14
* CUDA version, if used
* NVIDIA driver version, if in use
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: Unknown response from Aeron received: [-4]
	at org.nd4j.parameterserver.distributed.logic.RetransmissionHandler.getTransmissionStatus(RetransmissionHandler.java:32)
	at org.nd4j.parameterserver.distributed.transport.RoutedTransport.sendCommandToShard(RoutedTransport.java:369)
	at org.nd4j.parameterserver.distributed.transport.BaseTransport.sendMessageAndGetResponse(BaseTransport.java:89)
	at org.nd4j.parameterserver.distributed.transport.BaseTransport.sendMessage(BaseTransport.java:160)
	at org.nd4j.parameterserver.distributed.VoidParameterServer.initializeSeqVec(VoidParameterServer.java:415)
	at org.deeplearning4j.spark.models.sequencevectors.SparkSequenceVectors.fitSequences(SparkSequenceVectors.java:294)
	at org.deeplearning4j.spark.models.word2vec.SparkWord2Vec.fitSentences(SparkWord2Vec.java:78)
	at testing.sparkrun.main(sparkrun.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
17/05/05 08:20:17 WARN QueuedThreadPool: 8 threads could not be stopped

Code:
		 List<String> sentences;
		sentences = new ArrayList();

        sentences.add("one two thee four");
        sentences.add("some once again");
        sentences.add("one another sentence");
        
			  SparkConf sparkConf = new SparkConf()
			          .setAppName("Example Spark App");
			  
			  JavaSparkContext sparkContext = new JavaSparkContext(sparkConf);
			  JavaRDD<String> rddSentences = sparkContext.parallelize(sentences);
		 
VectorsConfiguration configuration=new VectorsConfiguration();
VoidConfiguration psconfiguration=new VoidConfiguration();
psconfiguration.setFaultToleranceStrategy(FaultToleranceStrategy.NONE);
configuration.setIterations(1);
configuration.setElementsLearningAlgorithm(SparkSkipGram.class.getCanonicalName());
configuration.setLayersSize(100);
configuration.setWindow(5);
configuration.setMinWordFrequency(1);
configuration.setLearningRate(0.25);
configuration.setBatchSize(100);
configuration.setUseAdaGrad(false);

//psconfiguration.setNumberOfShards(2);
//psconfiguration.setUnicastPort(40123);
//psconfiguration.setMulticastPort(40124);
//configuration.setSequenceLearningAlgorithm(SparkCBOW.class.getCanonicalName());

SparkWord2Vec sv=new SparkWord2Vec.Builder(psconfiguration, configuration).setModelExporter(new VocabCacheExporter()).setTokenizerFactory(new DefaultTokenizerFactory()).build();

//sv.setElementsLearningAlgorithm(new SparkSkipGram())
			  sv.fitSentences(rddSentences);

**Comment by huitseeker** [comment]
Hi @arunzz, thanks for reporting this issue. However, we'd love if you gave it a bit more effort on formatting to make it a bit more useful. In particular, giving a title would be a nice touch :)
