### ISSUE TITLE
Running DBN examples with the latest ND4J and DL4J errors out

### ISSUE THREAD

**Issue by dgkris** [deeplearning4j/deeplearning4j#337]
Stack trace as below : 
Exception in thread "main" java.lang.IllegalArgumentException: Illegal index 30 derived from 3 with offset of 0 and stride of 10
	at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:2885)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putScalar(BaseNDArray.java:869)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:862)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.execAndReturn(DefaultOpExecutioner.java:352)
	at org.deeplearning4j.nn.layers.OutputLayer.output(OutputLayer.java:344)
	at org.deeplearning4j.nn.layers.OutputLayer.setScore(OutputLayer.java:88)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:118)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:133)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.layers.OutputLayer.fit(OutputLayer.java:246)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.finetune(MultiLayerNetwork.java:1078)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1133)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1160)
	at org.deeplearning4j.multilayer.MLPBackpropIrisExample.main(MLPBackpropIrisExample.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
-- org.jblas INFO Deleting /var/folders/p8/bfx8h8nn5fb0k8fw8xzr7bgh0000gn/T/jblas5362750760097171301/libjblas.dylib
-- org.jblas INFO Deleting /var/folders/p8/bfx8h8nn5fb0k8fw8xzr7bgh0000gn/T/jblas5362750760097171301/libjblas_arch_flavor.dylib
-- org.jblas INFO Deleting /var/folders/p8/bfx8h8nn5fb0k8fw8xzr7bgh0000gn/T/jblas5362750760097171301

**Comment by agibsonccc** [comment]
This was nd4j related in the DefaultOpExecutioner with setting the results. Fixed now.
