### ISSUE TITLE
JsonMappingException causing runtime error in in testJson

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#343]
Stacktrace for the testJson in NeuralNetConfigurationTest:

java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class org.deeplearning4j.nn.conf.NeuralNetConfiguration]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: {
  "sparsity" : 0.0,
  "useAdaGrad" : false,
  "lr" : 0.10000000149011612,
  "corruptionLevel" : 0.30000001192092896,
  "numIterations" : 3,
  "momentum" : 0.5,
  "l2" : 0.0,
  "useRegularization" : false,
  "customLossFunction" : null,
  "momentumAfter" : null,
  "resetAdaGradIterations" : -1,
  "numLineSearchIterations" : 100,
  "dropOut" : 0.0,
  "applySparsity" : false,
  "weightInit" : "SIZE",
  "optimizationAlgo" : "CONJUGATE_GRADIENT",
  "lossFunction" : "RMSE_XENT",
  "constrainGradientToUnitNorm" : false,
  "rng" : {
    "default" : {
      "seed" : 1434393767402
    }
  },
  "dist" : {
    "normal" : {
      "mean" : 0.001,
      "std" : 1.0
    }
  },
  "stepFunction" : {
    "default" : { }
  },
  "layer" : {
    "RBM" : { }
  },
  "variables" : [ ],
  "activationFunction" : "sigmoid",
  "visibleUnit" : "GAUSSIAN",
  "hiddenUnit" : "RECTIFIED",
  "k" : 1,
  "weightShape" : [ 40, 2 ],
  "filterSize" : [ 2, 2, 2, 2 ],
  "stride" : [ 2, 2 ],
  "kernel" : 5,
  "batchSize" : 100,
  "minimize" : false,
  "l1" : 0.0,
  "featureMapSize" : [ 2, 2 ],
  "rmsDecay" : 0.0,
  "convolutionType" : "MAX",
  "nin" : 40,
  "nout" : 2
}; line: 2, column: 3]
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration.fromJson(NeuralNetConfiguration.java:376)
	at org.deeplearning4j.nn.conf.NeuralNetConfigurationTest.testJson(NeuralNetConfigurationTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class org.deeplearning4j.nn.conf.NeuralNetConfiguration]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: {
  "sparsity" : 0.0,
  "useAdaGrad" : false,
  "lr" : 0.10000000149011612,
  "corruptionLevel" : 0.30000001192092896,
  "numIterations" : 3,
  "momentum" : 0.5,
  "l2" : 0.0,
  "useRegularization" : false,
  "customLossFunction" : null,
  "momentumAfter" : null,
  "resetAdaGradIterations" : -1,
  "numLineSearchIterations" : 100,
  "dropOut" : 0.0,
  "applySparsity" : false,
  "weightInit" : "SIZE",
  "optimizationAlgo" : "CONJUGATE_GRADIENT",
  "lossFunction" : "RMSE_XENT",
  "constrainGradientToUnitNorm" : false,
  "rng" : {
    "default" : {
      "seed" : 1434393767402
    }
  },
  "dist" : {
    "normal" : {
      "mean" : 0.001,
      "std" : 1.0
    }
  },
  "stepFunction" : {
    "default" : { }
  },
  "layer" : {
    "RBM" : { }
  },
  "variables" : [ ],
  "activationFunction" : "sigmoid",
  "visibleUnit" : "GAUSSIAN",
  "hiddenUnit" : "RECTIFIED",
  "k" : 1,
  "weightShape" : [ 40, 2 ],
  "filterSize" : [ 2, 2, 2, 2 ],
  "stride" : [ 2, 2 ],
  "kernel" : 5,
  "batchSize" : 100,
  "minimize" : false,
  "l1" : 0.0,
  "featureMapSize" : [ 2, 2 ],
  "rmsDecay" : 0.0,
  "convolutionType" : "MAX",
  "nin" : 40,
  "nout" : 2
}; line: 2, column: 3]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1080)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration.fromJson(NeuralNetConfiguration.java:373)
	... 27 more

-- org.jblas INFO Deleting /var/folders/_m/15fcv4yn3y9dh93shs2lgql80000gn/T/jblas8451250132021318235/libjblas.dylib
-- org.jblas INFO Deleting /var/folders/_m/15fcv4yn3y9dh93shs2lgql80000gn/T/jblas8451250132021318235/libjblas_arch_flavor.dylib
-- org.jblas INFO Deleting /var/folders/_m/15fcv4yn3y9dh93shs2lgql80000gn/T/jblas8451250132021318235

**Comment by EronWright** [comment]
I observed that the lombok commit removed the default constructor.  I thought that it would be generated instead, but this bug suggests otherwise.

**Comment by nyghtowl** [comment]
Yeah I thought it would too. I have the plugin for lombok in Intellij but its still giving me this error for some reason.

**Comment by EronWright** [comment]
Seems the NoArgsConstructor annotation is the missing ingredient here.

**Comment by EronWright** [comment]
Fixed
