### ISSUE TITLE
load keras model appear error

### ISSUE THREAD

**Issue by jasstionzyf** [deeplearning4j/deeplearning4j#3441]
#### when i load a keras model ,  it appear error

i try to load a keras inceptionv3 model,  then i update 
https://github.com/fchollet/deep-learning-models/blob/master/inception_v3.py
to  export a json and h5 file, 
then i run following code to load the generate model:
   ```
     String jsonPath="/data/projects/my_work/deep-learning-models/model.json";
        String h5Path="/data/projects/my_work/deep-learning-models/model.h5";
        ComputationGraph graph = 
        KerasModelImport.importKerasModelAndWeights(jsonPath,h5Path);
        log.info(graph.summary());
```
        
- i expected above code run well
- but i get following error:
```
LF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.UnsupportedKerasConfigurationException: Unsupported keras layer type Conv2D. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.KerasLayer.getKerasLayerFromConfig(KerasLayer.java:254)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.helperPrepareLayers(KerasModel.java:190)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:164)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:97)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.buildModel(KerasModel.java:576)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:195)
	at edu.usc.irds.dl.dl4j.examples.ModelTest.main(ModelTest.java:21)
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version:0.8.1-SNAPSHOT
* platform information:OS

**Comment by turambar** [comment]
@jasstionzyf "Conv2D" is a Keras 2 layer (in Keras 1, it was much more helpfully named "Convolution2D") -- we do not yet support Keras 2. As such, I'm going to close this since it is redundant with https://github.com/deeplearning4j/deeplearning4j/issues/3129.
