### ISSUE TITLE
Word2Vec Spark Performance

### ISSUE THREAD

**Issue by jakobzlee** [deeplearning4j/deeplearning4j#3472]
Hello,
I've been trying to utilize the DL4J word2vec spark implementation in our project. The current sample data is a million lines of text extracted from Wikipedia. While I was able to successfully run the standalone implementation of word2vec in less than 10 minutes on my MacBook (2.7GHz Core i7 16GB), the spark implementation took about 1.5 hours. I've tried varying the different parameters without noticeable improvement.

My cluster is EMR on AWS with 3 nodes.
Master Node (1): 16 vCPU, 30 GiB memory, 320 SSD GB storage
Core Node (2): 16 vCPU, 30 GiB memory, 160 SSD GB storage

My spark submit is as follows:

spark-submit \
--master yarn \
--deploy-mode client \
--conf spark.shuffle.service.enabled=true \
--conf spark.dynamicAllocation.enabled=true \
--class "mil.darpa.ea.fusion.w2v.dl4j.spark.impl.DL4JWord2VecSparkDriver0 \
--num-executors 8 \
--executor-cores 4 \
--executor-memory 4G \
--driver-memory 4G \
--conf "spark.executor.extraJavaOptions=-Dorg.bytedeco.javacpp.maxbytes=5368709120" \
--conf "spark.driver.extraJavaOptions=-Dorg.bytedeco.javacpp.maxbytes=5368709120" \
--conf spark.yarn.executor.memoryOverhead=6144 \
/mnt/jlee/w2v/build/v0/darpa-ea-analytics-*.jar \
-dataFilePath "hdfs:///user/jlee/dl4j/input/one_million_sentences.txt" \
-sparkLocalModeEnabled false

The following is my code snippet:

```
import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.storage.StorageLevel;
import org.datavec.api.util.ClassPathResource;
import org.deeplearning4j.models.embeddings.loader.VectorsConfiguration;
import org.deeplearning4j.models.embeddings.loader.WordVectorSerializer;
import org.deeplearning4j.models.embeddings.reader.impl.FlatModelUtils;
import org.deeplearning4j.models.embeddings.wordvectors.WordVectors;
import org.deeplearning4j.spark.models.embeddings.word2vec.Word2Vec;
import org.deeplearning4j.spark.models.sequencevectors.learning.elements.SparkSkipGram;
import org.deeplearning4j.text.tokenization.tokenizer.preprocessor.CommonPreprocessor;
import org.deeplearning4j.text.tokenization.tokenizer.preprocessor.LowCasePreProcessor;
import org.deeplearning4j.text.tokenization.tokenizerfactory.DefaultTokenizerFactory;
import org.deeplearning4j.text.tokenization.tokenizerfactory.TokenizerFactory;
{
        this.sparkConf = new SparkConf();

        if (sparkLocalModeEnabled) {
            this.sparkConf
                    .setMaster("local[*]")
                    .set("spark.locality.wait", "0")
                    .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
                    .set("spark.kryoserializer.buffer.max", "2147483644b") // < 2 GB Spark Max
                    .set("spark.kryo.registrator", "org.nd4j.Nd4jRegistrator")
            ;
        }
        else {
            this.sparkConf
                    .setMaster( sparkMaster )
                    .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
                    .set("spark.kryoserializer.buffer.max", "2147483644b") // < 2 GB Spark Max
                    .set("spark.kryo.registrator", "org.nd4j.Nd4jRegistrator")
            ;
        }

        // Set SparkContext
        JavaSparkContext sparkContext = new JavaSparkContext(sparkConf);

        log.info("parameter_data_file_path: " + dataFilePath);
        //ClassPathResource classPathResource = new ClassPathResource(dataFilePath);
        //String trainingDataPath = classPathResource.getFile().getAbsolutePath();
        String trainingDataPath = dataFilePath;

        log.info("corpus_data_path: " + trainingDataPath);

        // Read in data
        JavaRDD<String> corpus = sparkContext.textFile(trainingDataPath);

        corpus.persist(StorageLevel.MEMORY_AND_DISK_SER());
        //corpus.persist(StorageLevel.MEMORY_ONLY_SER());

        // initial DL4J Word2Vec Spark implementation
        log.info("Setting configuration parameters ...");

        VectorsConfiguration vectorsConfiguration = new VectorsConfiguration();
        vectorsConfiguration.setElementsLearningAlgorithm(SparkSkipGram.class.getCanonicalName());
        vectorsConfiguration.setMinWordFrequency( 5 ); // default: 5
        vectorsConfiguration.setIterations( 1 );  // default: 1
        vectorsConfiguration.setLayersSize( 200 ); // default: 200
        vectorsConfiguration.setSeed( 42L );
        vectorsConfiguration.setWindow( 5 );  // default: 5
        vectorsConfiguration.setBatchSize( 512 );  // default: 512
        vectorsConfiguration.setNegative( 5.0 ); // default: 0.0d
        vectorsConfiguration.setUseAdaGrad( false ); // default: false
        vectorsConfiguration.setLearningRate( 0.025 ); // default: 0.025
        vectorsConfiguration.setMinLearningRate( 0.0001 ); // default: 0.0001
        vectorsConfiguration.setNGram( 1 );
        vectorsConfiguration.setUseUnknown( false );
        vectorsConfiguration.setEpochs( 1 );  // default: 1
        vectorsConfiguration.setHugeModelExpected( true ); // default: false
        vectorsConfiguration.setUseHierarchicSoftmax( true ); // default: true

        TokenizerFactory tokenizerFactory = new DefaultTokenizerFactory();
        tokenizerFactory.setTokenPreProcessor( new CommonPreprocessor() );

        Word2Vec word2Vec = new Word2Vec.Builder( vectorsConfiguration )
                .tokenizerFactory(tokenizerFactory)
                .build();

        word2Vec.train(corpus);

        word2Vec.setModelUtils(new FlatModelUtils());

        log.info("UNK: " + word2Vec.getWordVectorMatrix("UNK"));

        double sim = word2Vec.similarity("day", "night");
        log.info("day/night similarity: " + sim);

        sim = word2Vec.similarity("two", "four");
        log.info("two/four similarity: " + sim);

        Collection<String> words = word2Vec.wordsNearest("two", 10);
        printWords("two", words, word2Vec);

        String targetKeyWord = "media", targetLogicExtWord = "television";
        String targetLogicExtWord2 = "tweet";

        words = word2Vec.wordsNearest(targetKeyWord, 20);
        printWords(targetKeyWord, words, word2Vec);

        sparkContext.stop();
}
```

The following is my pom.xml :
```

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>darpa-ea-analytics</artifactId>
        <version>0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>darpa-ea-analytics-dl4j</artifactId>

    <properties>
        <!-- Change the nd4j.backend property to nd4j-cuda-7.5-platform or nd4j-cuda-8.0-platform to use CUDA GPUs -->
        <nd4j.backend>nd4j-native-platform</nd4j.backend>
        <!-- <nd4j.backend>nd4j-cuda-8.0-platform</nd4j.backend> -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <shadedClassifier>all</shadedClassifier>


        <java.version>1.8</java.version>
        <nd4j.version>0.8.0</nd4j.version>
        <dl4j.version>0.8.0</dl4j.version>
        <datavec.version>0.8.0</datavec.version>
        <arbiter.version>0.8.0</arbiter.version>
        <rl4j.version>0.8.0</rl4j.version>

        <!-- For Spark examples: change the _1 to _2 to switch between Spark 1 and Spark 2 -->
        <dl4j.spark.version>0.8.0_spark_2</dl4j.spark.version>
        <datavec.spark.version>0.8.0_spark_2</datavec.spark.version>

        <!-- Scala binary version: DL4J's Spark and UI functionality are released with both Scala 2.10 and 2.11 support -->
        <scala.binary.version>2.11</scala.binary.version>

        <guava.version>19.0</guava.version>
        <logback.version>1.1.7</logback.version>
        <jfreechart.version>1.0.13</jfreechart.version>
        <jcommon.version>1.0.23</jcommon.version>
        <maven-shade-plugin.version>2.4.3</maven-shade-plugin.version>
        <exec-maven-plugin.version>1.4.0</exec-maven-plugin.version>
        <maven.minimum.version>3.3.1</maven.minimum.version>
        <javafx.version>2.2.3</javafx.version>
        <javafx.runtime.lib.jar>${env.JAVAFX_HOME}/jfxrt.jar</javafx.runtime.lib.jar>
        <aws.sdk.version>1.11.109</aws.sdk.version>
        <jackson.version>2.6.6</jackson.version>
    </properties>

    <dependencyManagement>
    	<dependencies>
            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-api</artifactId>
                <version>${nd4j.version}</version>
            </dependency>

            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-common</artifactId>
                <version>${nd4j.version}</version>
            </dependency>

    	    <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>${jackson.version}</version>
            </dependency>

            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.module</groupId>
                <artifactId>jackson-module-scala_2.11</artifactId>
                <version>${jackson.version}</version>
            </dependency>
    	</dependencies>
    </dependencyManagement>

    <dependencies>

        <!-- ND4J -->
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>${nd4j.backend}</artifactId>
            <version>${nd4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-common</artifactId>
            <version>${nd4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-parameter-server-node_2.11</artifactId>
            <version>${nd4j.version}</version>
        </dependency>

        <!-- added Kryo serialization lib for SPARK serialization -->
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-kryo_2.10</artifactId>
            <version>${nd4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-nlp</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>dl4j-spark-nlp_2.11</artifactId>
            <version>${dl4j.spark.version}</version>
        </dependency>

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>dl4j-spark_${scala.binary.version}</artifactId>
            <version>${dl4j.spark.version}</version>
        </dependency>

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>dl4j-spark-nlp-java8_2.11</artifactId>
            <version>${dl4j.spark.version}</version>
        </dependency>

        <dependency>
            <groupId>org.datavec</groupId>
            <artifactId>datavec-hadoop</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

        <dependency>
            <groupId>com.beust</groupId>
            <artifactId>jcommander</artifactId>
            <version>${jcommander.version}</version>
        </dependency>

        <dependency>
	    <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-emr</artifactId>
            <version>${aws.sdk.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>${aws.sdk.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.11</artifactId>
            <version>2.1.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.11</artifactId>
            <version>2.1.0</version>
            <scope>provided</scope>
        </dependency>

        <!-- Logging Dependencies -->

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>

        <dependency>
            <groupId>com.typesafe.scala-logging</groupId>
            <artifactId>scala-logging_2.11</artifactId>
            <version>3.5.0</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>${exec-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <executable>java</executable>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${maven-shade-plugin.version}</version>
                <configuration>
                    <shadedArtifactAttached>true</shadedArtifactAttached>
                    <shadedClassifierName>${shadedClassifier}</shadedClassifierName>
                    <!--<shadedClassifierName>all</shadedClassifierName>-->
                    <createDependencyReducedPom>true</createDependencyReducedPom>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <!--<exclude>org/deeplearning4j/ui/**</exclude>-->
                                <exclude>org/datanucleus/**</exclude>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>reference.conf</resource>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

#### Contributing

Yes, I'd like to help if I can, though I'm new in machine learning. I've been a programmer for years. This is my first opportunity working with machine learning, and the DL4J project/site provides wonderful resources.

**Comment by agibsonccc** [comment]
This is already being worked on. Wait till we get the new parameter server out please.

**Comment by raver119** [comment]
This thing you're trying - is prototype. It works, but not even close to being optimal. So it wasn't announced in 0.8.0 release, despite it works. Just prototype.

**Comment by raver119** [comment]
Ugh. Sorry, no. You're using old implementation.

**Comment by jakobzlee** [comment]
Thanks the quick responses... Yes, I noticed there are at least 2 spark implementations in the code base. I managed to get the original "old" implementation (above) working. When trying the "newer" implementations, I ran into exceptions seemingly related to VoidParameterServer. Can I get the "newer" implementation/protytype at least working, while the latest version is being worked on?
I might miss something trivial.

The following is driver code snippet, with all else (cluster, pom, etc) being the same:
```
import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.storage.StorageLevel;
import org.datavec.api.util.ClassPathResource;
import org.deeplearning4j.models.embeddings.loader.VectorsConfiguration;
import org.deeplearning4j.models.embeddings.loader.WordVectorSerializer;
import org.deeplearning4j.models.embeddings.reader.impl.FlatModelUtils;
import org.deeplearning4j.models.embeddings.wordvectors.WordVectors;
import org.deeplearning4j.spark.models.sequencevectors.export.impl.HdfsModelExporter;
import org.deeplearning4j.spark.models.sequencevectors.learning.elements.SparkSkipGram;
import org.deeplearning4j.spark.models.word2vec.SparkWord2Vec;
import org.deeplearning4j.text.tokenization.tokenizer.preprocessor.CommonPreprocessor;
import org.deeplearning4j.text.tokenization.tokenizer.preprocessor.LowCasePreProcessor;
import org.deeplearning4j.text.tokenization.tokenizerfactory.DefaultTokenizerFactory;
import org.deeplearning4j.text.tokenization.tokenizerfactory.TokenizerFactory;
import org.nd4j.parameterserver.distributed.conf.VoidConfiguration;
  
    {
        this.sparkConf = new SparkConf();

        if (sparkLocalModeEnabled) {
            this.sparkConf
                    .setMaster("local[*]")
                    .set("spark.locality.wait", "0")
                    .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
                    .set("spark.kryoserializer.buffer.max", "2147483644b") // < 2 GB Spark Max
                    .set("spark.kryo.registrator", "org.nd4j.Nd4jRegistrator")
            ;
        }
        else {
            this.sparkConf
                    .setMaster( sparkMaster )
                    .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
                    .set("spark.kryoserializer.buffer.max", "2147483644b") // < 2 GB Spark Max
                    .set("spark.kryo.registrator", "org.nd4j.Nd4jRegistrator")
            ;
        }

        // Set SparkContext
        JavaSparkContext sparkContext = new JavaSparkContext(sparkConf);

        log.info("parameter_data_file_path: " + dataFilePath);
        //ClassPathResource classPathResource = new ClassPathResource(dataFilePath);
        //String trainingDataPath = classPathResource.getFile().getAbsolutePath();
        String trainingDataPath = dataFilePath;

        log.info("corpus_data_path: " + trainingDataPath);

        // Read in data
        JavaRDD<String> corpus = sparkContext.textFile( trainingDataPath );

        corpus.persist(StorageLevel.MEMORY_AND_DISK_SER());
        //corpus.persist(StorageLevel.MEMORY_ONLY_SER());

        // newer DL4J spark implementation prototype
        log.info("Setting configuration parameters ...");

        VectorsConfiguration vectorsConfiguration = new VectorsConfiguration();
        vectorsConfiguration.setElementsLearningAlgorithm(SparkSkipGram.class.getCanonicalName());
        vectorsConfiguration.setMinWordFrequency( 5 ); // default: 5
        vectorsConfiguration.setIterations( 1 );  // default: 1
        vectorsConfiguration.setLayersSize( 200 ); // default: 200
        vectorsConfiguration.setSeed( 42L );
        vectorsConfiguration.setWindow( 5 );  // default: 5
        vectorsConfiguration.setBatchSize( 512 );  // default: 512
        vectorsConfiguration.setNegative( 5.0 ); // default: 0.0d
        vectorsConfiguration.setUseAdaGrad( false ); // default: false
        vectorsConfiguration.setLearningRate( 0.025 ); // default: 0.025
        vectorsConfiguration.setMinLearningRate( 0.0001 ); // default: 0.0001
        vectorsConfiguration.setNGram( 1 );
        vectorsConfiguration.setUseUnknown( false );
        vectorsConfiguration.setEpochs( 1 );  // default: 1
        vectorsConfiguration.setHugeModelExpected( true ); // default: false
        vectorsConfiguration.setUseHierarchicSoftmax( true ); // default: true

        TokenizerFactory tokenizerFactory = new DefaultTokenizerFactory();
        tokenizerFactory.setTokenPreProcessor( new CommonPreprocessor() );

        VoidConfiguration voidConfiguration = new VoidConfiguration();

        SparkWord2Vec word2Vec = new SparkWord2Vec.Builder(voidConfiguration, vectorsConfiguration)
                .setTokenizerFactory( tokenizerFactory )
                .setModelExporter(new HdfsModelExporter(vectorsFilePath))
                .build();

        word2Vec.fitSentences(corpus);


        word2Vec.setModelUtils(new FlatModelUtils());

        //log.info("UNK: " + word2Vec.getWordVectorMatrix("UNK"));
        //InMemoryLookupTable<VocabWord> table = (InMemoryLookupTable<VocabWord>) word2Vec.lookupTable();

        double sim = word2Vec.similarity("day", "night");
        log.info("day/night similarity: " + sim);

        sim = word2Vec.similarity("two", "four");
        log.info("two/four similarity: " + sim);

        Collection<String> words = word2Vec.wordsNearest("two", 10);
        printWords("two", words, word2Vec);

        String targetKeyWord = "media", targetLogicExtWord = "television";
        String targetLogicExtWord2 = "tweet";

        words = word2Vec.wordsNearest(targetKeyWord, 20);
        printWords(targetKeyWord, words, word2Vec);

        sparkContext.stop();
    }

```
The following is exception during runtime:
```
...
17/05/31 00:45:47 INFO TorrentBroadcast: Started reading broadcast variable 3
17/05/31 00:45:47 INFO MemoryStore: Block broadcast_3_piece0 stored as bytes in memory (estimated size 142.0 B, free 1936.2 MB)
17/05/31 00:45:47 INFO TorrentBroadcast: Reading broadcast variable 3 took 7 ms
17/05/31 00:45:47 INFO MemoryStore: Block broadcast_3 stored as values in memory (estimated size 184.0 B, free 1936.2 MB)
17/05/31 00:45:47 INFO VoidParameterServer: Got [null] as sparkIp
17/05/31 00:45:48 ERROR Executor: Exception in task 1.0 in stage 1.0 (TID 2)
io.aeron.exceptions.RegistrationException: java.net.UnknownHostException: could not resolve endpoint address: null:0
	at io.aeron.ClientConductor.onError(ClientConductor.java:264)
	at io.aeron.DriverListenerAdapter.onMessage(DriverListenerAdapter.java:141)
	at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:99)
	at io.aeron.DriverListenerAdapter.pollMessage(DriverListenerAdapter.java:59)
	at io.aeron.ClientConductor.doWork(ClientConductor.java:331)
	at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:350)
	at io.aeron.ClientConductor.addSubscription(ClientConductor.java:194)
	at io.aeron.Aeron.addSubscription(Aeron.java:203)
	at org.nd4j.parameterserver.distributed.transport.RoutedTransport.init(RoutedTransport.java:86)
	at org.nd4j.parameterserver.distributed.VoidParameterServer.init(VoidParameterServer.java:228)
	at org.deeplearning4j.spark.models.sequencevectors.functions.VocabRddFunctionFlat$VocabRddFunctionAdapter.call(VocabRddFunctionFlat.java:62)
	at org.deeplearning4j.spark.models.sequencevectors.functions.VocabRddFunctionFlat$VocabRddFunctionAdapter.call(VocabRddFunctionFlat.java:31)
	at org.datavec.spark.transform.BaseFlatMapFunctionAdaptee.call(BaseFlatMapFunctionAdaptee.java:23)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1.apply(JavaRDDLike.scala:125)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1.apply(JavaRDDLike.scala:125)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:191)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
17/05/31 00:45:48 INFO CoarseGrainedExecutorBackend: Got assigned task 5
17/05/31 00:45:48 INFO Executor: Running task 1.1 in stage 1.0 (TID 5)
17/05/31 00:45:48 INFO BlockManager: Found block rdd_1_1 locally
17/05/31 00:46:02 INFO Executor: Finished task 1.1 in stage 1.0 (TID 5). 1673 bytes result sent to driver
17/05/31 00:46:02 INFO CoarseGrainedExecutorBackend: Got assigned task 7
17/05/31 00:46:02 INFO Executor: Running task 1.0 in stage 2.0 (TID 7)
17/05/31 00:46:02 INFO MapOutputTrackerWorker: Updating epoch to 1 and clearing cache
17/05/31 00:46:02 INFO TorrentBroadcast: Started reading broadcast variable 6
17/05/31 00:46:02 INFO MemoryStore: Block broadcast_6_piece0 stored as bytes in memory (estimated size 2.2 KB, free 1936.2 MB)
...

```

**Comment by raver119** [comment]
That's fine, VoidConfiguration should be filled properly, i've said before - it's prototype, and not recommended for use, at least for 2 next weeks. Here's non-merged example i've used for testing, though: https://github.com/deeplearning4j/dl4j-examples/blob/r119_spark/dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/nlp/DistributedWord2VecExample.java#L83-L88

**Comment by jakobzlee** [comment]
Nice, I finally made this prototype impl worked in spark-local. Though all distributed spark-submit attempts ended with some parameterServer related exceptions.
Still, progress made... We'll certainly be waiting to try the new release. Thanks ahead!

Exception if provided shardAddresses:
```
org.nd4j.linalg.exception.ND4JIllegalStateException: Can't connect to Shard: [aeron:udp?endpoint=172.31.44.253:49876]
	at org.nd4j.parameterserver.distributed.transport.RoutedTransport.lambda$sendCoordinationCommand$2(RoutedTransport.java:220)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870)
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at org.nd4j.parameterserver.distributed.transport.RoutedTransport.sendCoordinationCommand(RoutedTransport.java:191)
	at org.nd4j.parameterserver.distributed.transport.RoutedTransport.launch(RoutedTransport.java:487)
	at org.nd4j.parameterserver.distributed.VoidParameterServer.init(VoidParameterServer.java:279)
```
Exception if auto-discover shardAddresses:
```
INFO VoidParameterServer: Got [null] as sparkIp
Exception in thread "main" io.aeron.exceptions.RegistrationException: java.net.UnknownHostException: could not resolve endpoint address: null:49876
	at io.aeron.ClientConductor.onError(ClientConductor.java:264)
	at io.aeron.DriverListenerAdapter.onMessage(DriverListenerAdapter.java:141)
	at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:99)
	at io.aeron.DriverListenerAdapter.pollMessage(DriverListenerAdapter.java:59)
	at io.aeron.ClientConductor.doWork(ClientConductor.java:331)
	at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:350)
	at io.aeron.ClientConductor.addSubscription(ClientConductor.java:194)
	at io.aeron.Aeron.addSubscription(Aeron.java:203)
	at org.nd4j.parameterserver.distributed.transport.RoutedTransport.init(RoutedTransport.java:86)
	at org.nd4j.parameterserver.distributed.VoidParameterServer.init(VoidParameterServer.java:228)

```

**Comment by agibsonccc** [comment]
We finished the new param server here..retesting here wouldn't hurt.

**Comment by jakobzlee** [comment]
Thanks. I did pull on example repos and the project repos. Since I'm not building from source (but to be aware of changes while using version 0.8), is there an example of the 'right' way to use the new param server? Also, are the latest changes built into the 0.8 jars on Maven (or else I won't be able to pick up the latest changes)?

**Comment by aznwarmonkey** [comment]
Is there any update to this?  I think I am having similar issues

Here's the snippet code i am using

```
val voidConfig = VoidConfiguration.builder().unicastPort(40123).networkMask("172.27.57.0/24").build();

val vectorConfig = new VectorsConfiguration();
vectorConfig.setSeed(word2vec_seed);
vectorConfig.setBatchSize(100);
vectorConfig.setEpochs(max_interation);
vectorConfig.setIterations(max_interation);
vectorConfig.setHugeModelExpected(false);
vectorConfig.setLayersSize(vector_size);
vectorConfig.setLearningRate(min_learn_rate);
vectorConfig.setMinWordFrequency(min_word_frequence);
vectorConfig.setAllowParallelTokenization(true);
vectorConfig.setWindow(window_size);

                                    
final val word2Vec = new SparkWord2Vec.Builder(voidConfig,vectorConfig)
                                    .setStorageLevel(StorageLevel.MEMORY_AND_DISK_2)
                                    .setTokenizerFactory(new DefaultTokenizerFactory())
                                    .setLearningAlgorithm(new SparkCBOW())
                                    .setModelExporter(new HdfsModelExporter("hdfs:////data/AN/word2vec/spark_word2vec"))
                                    .workers(num_workers)
                                    .build();
word2Vec.fitSentences(features_javardd.repartition(2001))
```

Here's the exception.  I am not sure how i start a parameter server.  documentation is kind of sparse for Word2Vec

```
word2Vec: org.deeplearning4j.spark.models.word2vec.SparkWord2Vec = org.deeplearning4j.spark.models.word2vec.SparkWord2Vec@57c701a2
java.lang.NullPointerException
  at org.nd4j.parameterserver.distributed.transport.RoutedTransport.sendCommandToShard(RoutedTransport.java:492)
  at org.nd4j.parameterserver.distributed.transport.BaseTransport.sendMessageAndGetResponse(BaseTransport.java:114)
  at org.nd4j.parameterserver.distributed.transport.BaseTransport.sendMessage(BaseTransport.java:185)
  at org.nd4j.parameterserver.distributed.VoidParameterServer.initializeSeqVec(VoidParameterServer.java:463)
  at org.deeplearning4j.spark.models.sequencevectors.SparkSequenceVectors.fitSequences(SparkSequenceVectors.java:308)
  at org.deeplearning4j.spark.models.word2vec.SparkWord2Vec.fitSentences(SparkWord2Vec.java:93)
  ... 74 elided
```

**Comment by nicola007b** [comment]
Is there any update on using the new parameter server based implementation of Word2vec? Can anyone share a working example ? Thanks

**Comment by raver119** [comment]
Sorry, not yet. Overhaul was postponed until distributed SameDiff implemented, because they must share the same networking primitives.

**Comment by nicola007b** [comment]
Thanks for the prompt reply. Is the ‘old implementation’ still the recommended way of running word2vec on spark ? Any advice on this ?

**Comment by agibsonccc** [comment]
Closing: Spark is no longer supported in DL4J.
