### ISSUE TITLE
Corrupt? jar file in repo

### ISSUE THREAD

**Issue by mattbushell** [deeplearning4j/deeplearning4j#3487]
#### Issue Description
When adding the dep for UI
```
<dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-ui_2.10</artifactId>
            <version>0.8.1-SNAPSHOT</version>
         </dependency>
```

The build fails while creating jar with dependancies as shown below
```
Cleaning up unclosed ZipFile for archive C:\Users\Matt\.m2\repository\org\scala-lang\scala-library\2.10.5\scala-library-2.10.5.jar
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (default) on project stock-data-rangler: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (default) on project stock-data-rangler: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.codehaus.plexus.components.io.resources.PlexusIoURLResource.getContents(PlexusIoURLResource.java:41)
	at org.codehaus.plexus.components.io.resources.Deferred.getContents(Deferred.java:60)
	at org.codehaus.plexus.components.io.resources.proxy.ResourceInvocationHandler.invoke(ResourceInvocationHandler.java:62)
	at com.sun.proxy.$Proxy32.getContents(Unknown Source)
	at org.codehaus.plexus.archiver.ArchiveEntry.getInputStream(ArchiveEntry.java:137)
	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver$1.get(AbstractZipArchiver.java:559)
	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver$2.get(AbstractZipArchiver.java:673)
	at org.apache.commons.compress.archivers.zip.ZipArchiveEntryRequest.getPayloadStream(ZipArchiveEntryRequest.java:62)
	at org.apache.commons.compress.archivers.zip.ScatterZipOutputStream.addArchiveEntry(ScatterZipOutputStream.java:95)
	at org.codehaus.plexus.archiver.zip.ConcurrentJarCreator.addArchiveEntry(ConcurrentJarCreator.java:153)
	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.zipFile(AbstractZipArchiver.java:511)
	at org.codehaus.plexus.archiver.jar.JarArchiver.zipFile(JarArchiver.java:501)
	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.zipFile(AbstractZipArchiver.java:570)
	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.addResources(AbstractZipArchiver.java:420)
	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchiveMain(AbstractZipArchiver.java:330)
	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.execute(AbstractZipArchiver.java:233)
	at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:993)
	at org.apache.maven.plugins.assembly.archive.archiver.AssemblyProxyArchiver.createArchive(AssemblyProxyArchiver.java:445)
	at org.apache.maven.plugins.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:184)
	at org.apache.maven.plugins.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:476)
	at org.apache.maven.plugins.assembly.mojos.SingleAssemblyMojo.execute(SingleAssemblyMojo.java:58)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

**Comment by mattbushell** [comment]
Further Info
The following errors show during the compilation phase:

```
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ stock-data-rangler ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 22 source files to C:\devworkspace\stock-data-rangler\target\classes
[ERROR] error reading C:\Users\Matt\.m2\repository\com\typesafe\play\play_2.10\2.4.6\play_2.10-2.4.6.jar; invalid CEN header (bad signature)
[ERROR] error reading C:\Users\Matt\.m2\repository\com\typesafe\play\play-iteratees_2.10\2.4.6\play-iteratees_2.10-2.4.6.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Matt\.m2\repository\com\typesafe\play\play-json_2.10\2.4.6\play-json_2.10-2.4.6.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Matt\.m2\repository\com\typesafe\play\play-functional_2.10\2.4.6\play-functional_2.10-2.4.6.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Matt\.m2\repository\com\typesafe\akka\akka-actor_2.10\2.3.13\akka-actor_2.10-2.3.13.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Matt\.m2\repository\org\scala-stm\scala-stm_2.10\0.7\scala-stm_2.10-0.7.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Matt\.m2\repository\com\typesafe\play\play-netty-server_2.10\2.4.6\play-netty-server_2.10-2.4.6.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Matt\.m2\repository\com\typesafe\akka\akka-cluster_2.10\2.3.13\akka-cluster_2.10-2.3.13.jar; invalid LOC header (bad signature)
```

**Comment by saudet** [comment]
Delete your `.m2` folder and try again.

**Comment by huitseeker** [comment]
Thanks for filing this issue! We regret the problem you're encountering, but it looks like they are related to a distinct upstream project. There's, unfortunately, nothing we can do on our side to help you, hence we have to close this issue.
