### ISSUE TITLE
Keras Model Import : Conv2D error

### ISSUE THREAD

**Issue by maxgfr** [deeplearning4j/deeplearning4j#3490]
Hi everyone 😄 

When I tried to import a Keras model, I've this error : 

`org.deeplearning4j.nn.modelimport.keras.UnsupportedKerasConfigurationException: Unsupported keras layer type Conv2D. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.KerasLayer.getKerasLayerFromConfig(KerasLayer.java:254)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.helperPrepareLayers(KerasModel.java:190)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:99)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:56)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.buildSequential(KerasModel.java:581)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:156)
	at KerasManager.loadFile(KerasManager.java:52)
	at Main.main(Main.java:41)
`

Can this error be solve ? 

Is it that d4j didn't implement that import ?

Thank you all for your future answer 🦊

**Comment by maxgfr** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/3105
here is the solution
