### ISSUE TITLE
UIserver packaged in jar with dependencies - exception "No configuration setting found for key 'play.crypto.provider'"

### ISSUE THREAD

**Issue by ironflood** [deeplearning4j/deeplearning4j#3496]
#### Issue Description

Rooter:target gd$ java -jar dl4j-visualize-webapp-1.0-SNAPSHOT-jar-with-dependencies.jar
12:38:54.799 [main] DEBUG play.api.libs.CryptoConfigParser - Generated dev mode secret 28ee5a5e40eeedc7de6282fa77a3366c for app at jar:file:/Volumes/DATA/Dev/dl4j_visualize_webapp/target/dl4j-visualize-webapp-1.0-SNAPSHOT-jar-with-dependencies.jar!/application.conf
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'play.crypto.provider'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:198)
	at com.typesafe.config.impl.SimpleConfig.getIsNull(SimpleConfig.java:208)
	at play.api.PlayConfig.getOptional(Configuration.scala:951)
	at play.api.libs.CryptoConfigParser.get$lzycompute(Crypto.scala:250)
	at play.api.libs.CryptoConfigParser.get(Crypto.scala:203)
	at play.api.BuiltInComponents$class.cryptoConfig(Application.scala:284)
	at play.api.BuiltInComponentsFromContext.cryptoConfig$lzycompute(ApplicationLoader.scala:100)
	at play.api.BuiltInComponentsFromContext.cryptoConfig(ApplicationLoader.scala:100)
	at play.api.BuiltInComponents$class.crypto(Application.scala:285)
	at play.api.BuiltInComponentsFromContext.crypto$lzycompute(ApplicationLoader.scala:100)
	at play.api.BuiltInComponentsFromContext.crypto(ApplicationLoader.scala:100)
	at play.api.BuiltInComponents$class.injector(Application.scala:270)
	at play.api.BuiltInComponentsFromContext.injector$lzycompute(ApplicationLoader.scala:100)
	at play.api.BuiltInComponentsFromContext.injector(ApplicationLoader.scala:100)
	at play.api.BuiltInComponents$class.application(Application.scala:279)
	at play.api.BuiltInComponentsFromContext.application$lzycompute(ApplicationLoader.scala:100)
	at play.api.BuiltInComponentsFromContext.application(ApplicationLoader.scala:100)
	at play.core.server.JavaServerHelper$.forRouter(Server.scala:153)
	at play.core.server.JavaServerHelper.forRouter(Server.scala)
	at play.server.Server.forRouter(Server.java:96)
	at org.deeplearning4j.ui.play.PlayUIServer.runMain(PlayUIServer.java:184)
	at org.deeplearning4j.ui.api.UIServer.getInstance(UIServer.java:27)
	at Main.main(Main.java:13)

To reproduce, the pom file and the main class:

POM: 
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.tastemap</groupId>
    <artifactId>dl4j-visualize-webapp</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-ui_2.11</artifactId>
            <version>0.8.0</version>
        </dependency>
    </dependencies>

    <build>
    <plugins>
        <plugin>
            <artifactId>maven-assembly-plugin</artifactId>
            <version>3.0.0</version>
            <configuration>
                <archive>
                    <manifest>
                        <mainClass>Main</mainClass>
                    </manifest>
                </archive>
                <descriptorRefs>
                    <descriptorRef>jar-with-dependencies</descriptorRef>
                </descriptorRefs>
            </configuration>
        </plugin>
    </plugins>
    </build>

</project>`

MAIN class:
`import org.deeplearning4j.ui.api.UIServer;

public class Main {

    public static void main(String[] args){

        //------------ In the first JVM: Start the UI server and enable remote listener support ------------
        //Initialize the user interface backend

        UIServer uiServer = UIServer.getInstance();
        uiServer.enableRemoteListener();
    }
}`

**Comment by drivenbyentropy** [comment]
I encountered the same issue while attempting to create an uber-jar for my project. I was able to work around this issue by using the `maven-shade-plugin` instead of the the `maven-assembly-plugin`. The solution was mentioned on the [DL4J Gitter channel](https://gitter.im/deeplearning4j/deeplearning4j/archives/2017/02/01) by user `sragrawal` and consists of adding an two additional transformers to the shade plugin (`ServicesResourceTransformer` and `AppendingTransformer`). The relevant part of the `pom.xml` looks as follows:
```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-shade-plugin</artifactId>
	<version>3.1.0</version>
	<configuration>
		<shadedArtifactAttached>true</shadedArtifactAttached>
		<shadedClassifierName>${shadedClassifier}</shadedClassifierName>
		<createDependencyReducedPom>true</createDependencyReducedPom>
		<filters>
			<filter>
				<artifact>*:*</artifact>
				<excludes>
					<exclude>org/datanucleus/**</exclude>
					<exclude>META-INF/*.SF</exclude>
					<exclude>META-INF/*.DSA</exclude>
					<exclude>META-INF/*.RSA</exclude>
				</excludes>
			</filter>
		</filters>
	</configuration>
	<executions>
		<execution>
			<phase>package</phase>
			<goals>
				<goal>shade</goal>
			</goals>
			<configuration>
				<transformers>
					<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
						<resource>reference.conf</resource>
					</transformer>
					<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
					<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
						<mainClass>your.main.class.here</mainClass>
					</transformer>
				</transformers>
			</configuration>
		</execution>
	</executions>
</plugin>
```

**Comment by AlexDBlack** [comment]
Right, it's a case of building the JAR correctly...
But I'll leave this open - even though it's a problem with the jar building (and the Play framework more generally) it would be nice to detect this at the DL4J level and tell users why things are failing (that error is *very* cryptic).
Or even somehow inject a default configuration if one isn't present/found...

**Comment by drivenbyentropy** [comment]
I agree. The error message leads down a deep rabbit hole. It might be advantageous to add a small section explaining the issue to the [Visualization section](https://deeplearning4j.org/visualization) of the DL4J webpage. I believe this might save a lot of time for people running into this issue. 

In any case, thank you for making this project available to everyone. It represents a true milestone in terms of portability, integrability into existing frameworks, and expandability in the field of deep learning.

**Comment by AlexDBlack** [comment]
Thanks. Good idea on the docs - cc @tomthetrainer @crockpotveggies

**Comment by AlexDBlack** [comment]
Fixed here:
https://github.com/deeplearning4j/deeplearning4j/pull/4376
https://github.com/deeplearning4j/deeplearning4j/pull/4374
