### ISSUE TITLE
java.lang.UnsupportedClassVersionError: org/mapdb/Serializer : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by san21886** [deeplearning4j/deeplearning4j#3510]
#### I am running DL4J on Spark(CPU) with Java-1.7.0_79 and came across following exception:

...java.lang.UnsupportedClassVersionError: org/mapdb/Serializer : Unsupported major.minor version 52.0
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

Here is my code where the exception occurs:

var conf = new NeuralNetConfiguration.Builder()
            .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT).iterations(1)
            .learningRate(0.1)
            .rmsDecay(0.95)
            .seed(12345)
            .regularization(true)
            .l2(0.001)
            .weightInit(WeightInit.XAVIER)
            .updater(Updater.RMSPROP)
            .list()
            .layer(0, new GravesLSTM.Builder().nIn(2).nOut(10).activation(Activation.TANH).build())
            .layer(1, new GravesLSTM.Builder().nIn(10).nOut(10).activation(Activation.TANH).build())
            .layer(2, new RnnOutputLayer.Builder(LossFunction.MCXENT).activation(Activation.SOFTMAX)        
            .nIn(10).nOut(2).build())
            .backpropType(BackpropType.TruncatedBPTT).tBPTTForwardLength(50).tBPTTBackwardLength(50)
            .pretrain(false).backprop(true)
            .build();

Please let me if there is a way to fix this.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.8.0
* platform information (OS, etc): Ubuntu 14.04
* Java Version: 1.7.0_79
* CUDA version, if used
* NVIDIA driver version, if in use

**Comment by raver119** [comment]
Some stuff coming from DataVec requires java 8. You're trying to use something from it i guess.
