### ISSUE TITLE
dropout is giving generalValidation error

### ISSUE THREAD

**Issue by Joshuaalbert** [deeplearning4j/deeplearning4j#3511]
#**Problem**
When I build a simple CG with dropout I get a validation error.
This code reproduces the bug:
https://gist.github.com/Joshuaalbert/c34366d5c20413aa29f0699b903d3f55
If you comment out the parts about dropout it works fine.
Traceback is:
```
Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.nn.conf.layers.LayerValidation.generalValidation(LayerValidation.java:296)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.build(NeuralNetConfiguration.java:1183)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.build(ComputationGraphConfiguration.java:711)
	at com.tactico.tm.bugs.ValidationError.main(ValidationError.java:37)
```

**Version**
Latest local build of 0.8.1-SNAPSHOT, same happens using maven 0.8.1-SNAPSHOT
Update: It runs with 0.8.0

**Comment by Joshuaalbert** [comment]
This is happening also with 0.8.1-SNAPSHOT from local build latest commit.
Can anyone else reproduce by running that gist?

**Comment by AlexDBlack** [comment]
Fixed here with test: https://github.com/deeplearning4j/deeplearning4j/pull/3585
