### ISSUE TITLE
NativeImageLoader fails in OpenCV for black-and-white TIFFs

### ISSUE THREAD

**Issue by amansheim-bm-net** [deeplearning4j/deeplearning4j#3550]
#### Issue Description

NativeImageLoader fails in OpenCV for black-and-white TIFFs.

Here are steps to reproduce the error. The dl4j-examples AnimalsClassification fails if beforehand I do:

1. Get a sample, typical, black-and-white TIFF. I used this particular CCITT Group 4 TIFF, [CCITT_4.TIF from fileformat.info](http://www.fileformat.info/format/tiff/sample/0919217f712c4b4385c91d11b8e0e5b8/download).

2. Overwrite every example image with the TIFF. I accomplished that using this bash one-liner:

    find IdeaProjects/dl4j-examples/dl4j-examples/src/main/resources/animals -type f -print0 | while read -d $'\0' file; do cp Downloads/CCITT_4.TIF "$file"; done

Expected: After printing "Train model....", the ScoreIterationListener begins printing.

Encountered: After printing "Train model....", the program stops with a runtime exception, with the following stack trace:

    OpenCV Error: Assertion failed (j < nsrcs && src[j].depth() == depth) in cv::mixChannels, file C:\projects\bytedeco\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.1.0\modules\core\src\convert.cpp, line 466
    Exception in thread "main" java.lang.RuntimeException: Exception thrown in base iterator

...

        at org.deeplearning4j.examples.convolution.AnimalsClassification.run(AnimalsClassification.java:159)
        at org.deeplearning4j.examples.convolution.AnimalsClassification.main(AnimalsClassification.java:311)
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: C:\projects\bytedeco\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.1.0\modules\core\src\convert.cpp:466: error: (-215) j < nsrcs && src[j].depth() == depth in function cv::mixChannels
    
        at org.datavec.image.recordreader.BaseImageRecordReader.next(BaseImageRecordReader.java:219)

...

#### Version Information

* Deeplearning4j version: 8be4998 Alex Black <blacka101@gmail.com> on 6/15/2017 at 7:23 AM
* platform information (OS, etc): Windows 10 Pro v 1703 (build 15063). Using bash shell is via Windows Subsystem for Linux.
* CUDA version: I think it doesn't matter. I think no CUDA operations are reached.
* NVIDIA driver version: I think it doesn't matter. I think no CUDA operations are reached.

**Comment by amansheim-bm-net** [comment]
Doing this additional step does not change the result.

3. In AnimalsClassification.java, replace "channels = 3" with "channels = 1".

**Comment by saudet** [comment]
Fixed, thanks for reporting!
