### ISSUE TITLE
Import keras module failed,  weights is null when copying keras weights to DL4J

### ISSUE THREAD

**Issue by zheolong** [deeplearning4j/deeplearning4j#3597]
## Env & Versions

**OS**: mac os 10.10.5
**JAVA version**：1.8.0_31
**keras**: 1.2.2
**dl4j**: 0.8.1-SNAPSHOT

## Problem
I am using keras `1.2.2` to export model(json and h5), and dl4j `0.8.1-SNAPSHOT` to import model, but got the message below.  Do you guys know what is happening ?

ps: The json and h5 file is really ok, and I've checked the two files with keras's model loading.

## The Error Message

```
org.deeplearning4j.nn.modelimport.keras.InvalidKerasConfigurationException: Error when attempting to copy weights from Keras layer dense_1 to DL4J layer dense_1(weights is null). For more information, see http://deeplearning4j.org/model-import-keras.
	at org.deeplearning4j.nn.modelimport.keras.KerasLayer.copyWeightsToLayer(KerasLayer.java:439)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.helperCopyWeightsToModel(KerasModel.java:636)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:227)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:213)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:236)
	at com.antfin.matrix.h7p.huabei.DL4JTest.loadModel(DL4JTest.java:85)
	at com.antfin.matrix.h7p.huabei.DL4JTest.ArksRequestTest(DL4JTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

## the java code is 
```
MultiLayerNetwork network = KerasModelImport.importKerasSequentialModelAndWeights("PATH TO YOUR JSON FILE","PATH TO YOUR H5 FILE")
```

## model files
[model.tar.gz](https://github.com/deeplearning4j/deeplearning4j/files/1114700/model.tar.gz)

**Comment by zheolong** [comment]
![model_json](https://user-images.githubusercontent.com/5104916/27729515-c53b164e-5db8-11e7-8de3-446723175b01.png)
![model_save](https://user-images.githubusercontent.com/5104916/27729529-d3a43e68-5db8-11e7-8320-94edd9dbc58d.png)

**Comment by zheolong** [comment]
## The same problem with dl4j 0.7.2 version and I fixed it

patch is

```
diff --git a/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/KerasModel.java b/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/KerasModel.java
index 107d068..725d8ad 100644
--- a/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/KerasModel.java
+++ b/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/KerasModel.java
@@ -652,6 +652,8 @@ public class KerasModel {
                                 break;
                         }
                     }
+                } else {
+                    dl4jParamValue = kerasParamValue;
                 }
                 if (!layer.paramTable().keySet().contains(dl4JParamName))
                     throw new InvalidKerasConfigurationException("Layer " + layerName + ": Keras param " + kerasParamName + " maps to unknown param " + dl4JParamName);
```

**Comment by agibsonccc** [comment]
We didn't have model import before 0.8.0. Would you mind submitting a pull request?

**Comment by zheolong** [comment]
ok, I will submit it later. By the way, 0.7.2 just for import and core.

```
<dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-modelimport</artifactId>
            <version>0.7.2</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/resources/deeplearning4j-modelimport-0.7.2.jar</systemPath>
        </dependency>

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>0.7.2</version>
        </dependency>
```

**Comment by zheolong** [comment]
@agibsonccc I try to debug this with 0.8.1-SNAPSHOT, and follow the debugger, the problem maybe 
 hdf5 file parsing as below.

```weightsArchive.getDataSets(layerName)``` is empty when parsing my hdf5 file.

<img width="1440" alt="dingtalk20170706135541" src="https://user-images.githubusercontent.com/5104916/27897424-d48c7658-6252-11e7-9408-1a6508936c8a.png">

**Comment by zheolong** [comment]
I've found the truth about this problem. The tensorflow scope and keras mixing cause exported h5 file like below, has nested group.

```
HDF5 "/Users/qiaojunlong/GitHub/alibaba/h7p-blink-huabei-rec/src/main/resources/model_save" {
GROUP "/" {
   ATTRIBUTE "layer_names" {
      DATATYPE  H5T_STRING {
         STRSIZE 7;
         STRPAD H5T_STR_NULLPAD;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 3 ) / ( 3 ) }
      DATA {
      (0): "input_1", "dense_1", "dense_2"
      }
   }
   GROUP "dense_1" {
      ATTRIBUTE "weight_names" {
         DATATYPE  H5T_STRING {
            STRSIZE 25;
            STRPAD H5T_STR_NULLPAD;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
         DATA {
         (0): "global/shared/dense_1_W:0", "global/shared/dense_1_b:0"
         }
      }
      GROUP "global" {
         GROUP "shared" {
            DATASET "dense_1_W:0" {
               DATATYPE  H5T_IEEE_F32LE
               DATASPACE  SIMPLE { ( 70, 256 ) / ( 70, 256 ) }
               DATA {
               (0,0): -0.115867, 0.085163, 0.079829, 0.0583863, 0.0404952,
```

**Comment by agibsonccc** [comment]
Hmmm - I forget. Were you using keras 1 or 2? Is this something we should be supporting?

**Comment by zheolong** [comment]
keras 1.2.2, but dl4j may have no enough information to parsing such h5 file.

**Comment by turambar** [comment]
Yeah, the TensorFlow scoping stuff really makes parsing the Keras HDF5 files...difficult.

**Comment by maxpumperla** [comment]
@zheolong thanks for reporting this. It seems the title is a little outdated, a lot has happened in them meantime.

Would it be possible for you to summarise / describe the problem that remains? Maybe even create a new ticket for it? It's difficult to keep track of such tickets midterm. Thanks

**Comment by zheolong** [comment]
Already Fixed. Refer to #3842
