### ISSUE TITLE
nd4j-native out of  memory

### ISSUE THREAD

**Issue by akhodakivskiy** [deeplearning4j/deeplearning4j#3630]
- I'm training several (identical) models in parallel (see model setup code in the gist).
- Model configuration is in the gist 
- All the feature and label data is in memory in `ArrayList<List<Double>>`. 
- The data is passed to my own implementation `DataSetIterator` similar to `DoublesDataSetIterator` that supports shuffling between epochs (see implementation in the gist)
- The parallelism is set up as shown in the snippet below.
- The models are fit using early stopping configuration.
- I'm using `LocalFileModelSaver` to avoid unnecessary memory usage.
- The backend is nd4j-native
- The OS is Ubuntu Linux 16.04
- JVM is given ~40G of RAM. 
- JavaCpp had default memory setting.
- Happens with 30+ parallel models. Doesn't happen with less than that.
- CPU: (14+14)*2 Xeon. Total memory is 128G RAM. (This is the only beefy process running)
- Batch size: 1000, train samples: 1.5M, test samples: 500K. Every model has its own iterator, but Most of the samples are reused between iterators.
- Dl4j 0.8.0
- Model fitting passed 20 epochs and then crashed (suggesting a memory leak)

Some relevant code can be found in this gist:

https://gist.github.com/akhodakivskiy/20227d100dd9009f86815da2a2b39a65

Exception:

```
java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(2000): totalBytes = 2G, physicalBytes = 53G
        at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:76)
        at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:41)
        at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:177)
        at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:133)
        at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:341)
        at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:296)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1344)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:190)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:181)
        at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:71)
        at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:134)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3090)
        at kdkvsk.btcmkr.neural.lib.DoublesBatchDataSetIterator.fillQueue(DoublesBatchDataSetIterator.java:199)
        at kdkvsk.btcmkr.neural.lib.DoublesBatchDataSetIterator.hasNext(DoublesBatchDataSetIterator.java:169)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doEvaluation(MultiLayerNetwork.java:2466)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.evaluate(MultiLayerNetwork.java:2522)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.evaluate(MultiLayerNetwork.java:2502)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.evaluate(MultiLayerNetwork.java:2414)
        at kdkvsk.btcmkr.neural.lib.F1ScoreCalculator.calculateScore(F1ScoreCalculator.scala:17)
        at kdkvsk.btcmkr.neural.lib.F1ScoreCalculator.calculateScore(F1ScoreCalculator.scala:12)
        at org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer.fit(BaseEarlyStoppingTrainer.java:180)
        at kdkvsk.btcmkr.neural.app.NeuralApp$$anonfun$52$$anonfun$apply$5.apply(NeuralApp.scala:219)
        at kdkvsk.btcmkr.neural.app.NeuralApp$$anonfun$52$$anonfun$apply$5.apply(NeuralApp.scala:183)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes = 53G > maxPhysicalBytes = 53G
        at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:572)
        at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
        at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
        at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
        ... 29 more
```

**Comment by saudet** [comment]
Is this with 0.8.0? or with 0.8.1-SNAPSHOT? Using workspaces?

**Comment by raver119** [comment]
@saudet according to gitter, that's 0.8.0.

**Comment by raver119** [comment]
So far it sounds like occasional spike... 30 models in parallel, even if each thread holds only 1GB worth of resources - that's already 30GB... And with pre-workspaces mechanics - that doesn't sound like impossible event

**Comment by akhodakivskiy** [comment]
This is 0.8.0.
I also added a detail that training passed 20 epochs and then crashed

**Comment by raver119** [comment]
Can we have YourKit profiler memory dump of your training process?

**Comment by raver119** [comment]
@akhodakivskiy Any news there? Have you tried snapshots with workspaces? Any chance for memory dump?

**Comment by akhodakivskiy** [comment]
I have not tried workspaces, and was not able to recover a memory dump. But after setting `OMP_NUM_THREADS=1` this issue doesn't seem to occur anymore. Before this change, I noticed a few times the following error: 

```
libgomp: Thread creation failed: Resource temporarily unavailable
```

I suspect that this setting was causing the memory leaks because when it occurred entire system was coming to a stall, I was to able to type anything into the console. Probably memory deallocation was stalling as well causing the Out of Memory error. I will monitor and reopen if this happens again.
