### ISSUE TITLE
Nd4j OutOfMemoryError as SparkDl4jMultiLayer run more numEpochs

### ISSUE THREAD

**Issue by jasstionzyf** [deeplearning4j/deeplearning4j#3635]
##  driver esception:
```
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 15 in stage 297.0 failed 4 times, most recent failure: Lost task 15.3 in stage 297.0 (TID 10354, 172.16.241.136, executor 5): java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(8375320): totalBytes = 8G, physicalBytes = 17G
        at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:76)
        at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:524)
        at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:61)
        at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:255)
        at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createSame(DefaultDataBufferFactory.java:290)
        at org.nd4j.linalg.cpu.nativecpu.NDArray.unsafeDuplication(NDArray.java:368)
        at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingWorker.getInitialModel(ParameterAveragingTrainingWorker.java:104)
        at org.deeplearning4j.spark.api.worker.ExecuteWorkerFlatMapAdapter.call(ExecuteWorkerFlatMap.java:89)
        at org.deeplearning4j.spark.api.worker.ExecuteWorkerFlatMapAdapter.call(ExecuteWorkerFlatMap.java:43)
        at org.deeplearning4j.spark.api.worker.ExecuteWorkerPathFlatMapAdapter.call(ExecuteWorkerPathFlatMap.java:71)
        at org.deeplearning4j.spark.api.worker.ExecuteWorkerPathFlatMapAdapter.call(ExecuteWorkerPathFlatMap.java:38)
        at org.datavec.spark.transform.BaseFlatMapFunctionAdaptee.call(BaseFlatMapFunctionAdaptee.java:24)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Native allocator returned address == 0
```
## spark executor exception:
```
17/07/07 13:35:02 ERROR util.SparkUncaughtExceptionHandler: [Container in shutdown] Uncaught exception in thread Thread[Executor task launch worker-5,5,main]
java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(8375320): totalBytes = 8G, physicalBytes = 17G
        at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:76)
        at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:524)
        at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:61)
        at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:255)
        at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createSame(DefaultDataBufferFactory.java:290)
        at org.nd4j.linalg.cpu.nativecpu.NDArray.unsafeDuplication(NDArray.java:368)
        at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingWorker.getInitialModel(ParameterAveragingTrainingWorker.java:104)
        at org.deeplearning4j.spark.api.worker.ExecuteWorkerFlatMapAdapter.call(ExecuteWorkerFlatMap.java:89)
        at org.deeplearning4j.spark.api.worker.ExecuteWorkerFlatMapAdapter.call(ExecuteWorkerFlatMap.java:43)
        at org.deeplearning4j.spark.api.worker.ExecuteWorkerPathFlatMapAdapter.call(ExecuteWorkerPathFlatMap.java:71)
        at org.deeplearning4j.spark.api.worker.ExecuteWorkerPathFlatMapAdapter.call(ExecuteWorkerPathFlatMap.java:38)
        at org.datavec.spark.transform.BaseFlatMapFunctionAdaptee.call(BaseFlatMapFunctionAdaptee.java:24)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
```

Please describe our issue, along with:
- expected behavior:  i except the memory will not keep grow up as the program run
- encountered behavior:  the memory keep grow as the program run

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.8.1-SNAPSHOT<
* platform information (OS, etc) centos 7.x

**Comment by jasstionzyf** [comment]
https://gist.github.com/jasstionzyf/536c4448380acafe58b05fd4d8469cee   this contains the main code and config, if you want to run it ,  just call MultiLabel.MultiLabeledTrainAndTest

**Comment by saudet** [comment]
```
Caused by: java.lang.OutOfMemoryError: Native allocator returned address == 0
```
That means the OS itself has ran out of memory, possibly caused by fragmentation. Does this happen with "workspaces" as well?

**Comment by AlexDBlack** [comment]
More info on your environment (spark local? yarn?) + configuration (memory xms/xmx, total RAM) would be helpful here.

**Comment by jasstionzyf** [comment]
@saudet   yes, i have use workspace also different mode: including flowing: 
conf.setInferenceWorkspaceMode(WorkspaceMode.SINGLE);
        conf.setTrainingWorkspaceMode(WorkspaceMode.SINGLE);

or 

conf.setInferenceWorkspaceMode(WorkspaceMode.SEPERATE);
        conf.setTrainingWorkspaceMode(WorkspaceMode.SEPERATE);

or 
for (int i = 0; i < numEpochs; i++) {
            mode=sparkNet.fit(trainData);
            **Nd4j.getWorkspaceManager().destroyAllWorkspacesForCurrentThread();**


            mLog.info("Completed Epoch {}", i);
        }

**Comment by jasstionzyf** [comment]
@AlexDBlack i use spark cluster,  http://tensorflow1.vcg.com/  you can use this link to check the config

**Comment by jasstionzyf** [comment]
also one point is that:  my input format in the csv is one hot vector with size 6320, and then features with size 2048

**Comment by jasstionzyf** [comment]
if you guys have any suggestions ?  , i can quickly change and run the program to try

**Comment by jasstionzyf** [comment]
currently i have reduce spark worker number on each machine (so make more memory for the workspace) , and currently the memory usage seems stable , i will continue to observer it , if still no problem after the program ended, i think  this issues should be closed.

**Comment by raver119** [comment]
Please, do not call this: `Nd4j.getWorkspaceManager().destroyAllWorkspacesForCurrentThread();`

Never call for things you don't need.

**Comment by jasstionzyf** [comment]
i think this issues can be closed now, i have confirmed that this is because memory settings mistake
