### ISSUE TITLE
LeakyRelu in Keras is not supported

### ISSUE THREAD

**Issue by hristo-vrigazov** [deeplearning4j/deeplearning4j#3669]
#### Issue Description

I created a Keras model adaptation for the YOLO neural network for object detection. When I tried to import it in Deep Learing 4J, it can't do that because it does not support the LeakyRelu layer.
You can download the configuration and weights from these links: [configuration](https://www.dropbox.com/s/mwg6lquve4q6ja1/yolo_model.json), [weights](https://www.dropbox.com/s/gd5862tuplxzsb7/yolo_weights.h5)
When I run:
```
MultiLayerNetwork network = KerasModelImport.importKerasSequentialModelAndWeights(
                    "yolo_model.json",
                    "yolo_weights.h5");
```
it throws the following exception:

```
org.deeplearning4j.nn.modelimport.keras.UnsupportedKerasConfigurationException: Unsupported keras layer type LeakyReLU. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.KerasLayer.getKerasLayerFromConfig(KerasLayer.java:254)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.helperPrepareLayers(KerasModel.java:190)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:99)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:56)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.buildSequential(KerasModel.java:581)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:235)
	at com.play.computer.vision.App.main(App.java:18)
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - 0.8, 
* deeplearning4j-modelimport - 0.8.0-2
* OS - Ubuntu 16.04

**Comment by tomthetrainer** [comment]
DeepLearning4J includes LeakyRelu, 

https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/transforms/LeakyReLU.java

If the implementation is the same this might simply be a failure to map the keras leakyRelu to our Leaky relu. 

Note to @turambar , to see if he   has more information.
