### ISSUE TITLE
NPE on preprocessor when using ADSI

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3680]
#### Issue Description

Getting the following error on my RRDSI:

```
Exception in thread "ADSI prefetch thread" java.lang.RuntimeException: java.lang.NullPointerException: toPreProcess
    at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:435)
Caused by: java.lang.NullPointerException: toPreProcess
    at org.nd4j.linalg.dataset.api.preprocessor.AbstractDataSetNormalizer.preProcess(AbstractDataSetNormalizer.java:113)
    at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:296)
    at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:394)
    at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:52)
    at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:423)
```

I'm using a Hadoop map file as per @AlexDBlack's suggestion. Here's how I set it up:

```
    log.info("Load data...");
    RecordReader trainRR = new MapFileRecordReader();
    trainRR.initialize( new FileSplit( new File( transformedTrain ) ) );
    RecordReader testRR = new MapFileRecordReader();
    testRR.initialize( new FileSplit( new File( transformedTest ) ) );

    log.info("Creating RecordReader iterator....");
    DataSetIterator trainIter = new RecordReaderDataSetIterator(trainRR, batchSize, 11, 7);
    DataSetIterator testIter = new RecordReaderDataSetIterator(testRR, batchSize, 11, 7);

    log.info("Fitting normalizer...");
    DataNormalization normalizer = new NormalizerStandardize();
    normalizer.fit(trainIter);
    normalizer.fit(testIter);
    trainIter.setPreProcessor(normalizer);
    testIter.setPreProcessor(normalizer);
```

#### Version Information

snapshots

**Comment by raver119** [comment]
Issue isn't in ADSI. It's RRDSI returned DataSet being null, and that's causing NPE.

**Comment by crockpotveggies** [comment]
Why is it that when I remove ADSI the NPE goes away? I don't understand.

**Comment by raver119** [comment]
Can you give me something i could run locally?

**Comment by crockpotveggies** [comment]
Closing due to inactivity.
