### ISSUE TITLE
dl4j-scaleout - update curator/zk/log4j framework dependency

### ISSUE THREAD

**Issue by danyaljj** [deeplearning4j/deeplearning4j#370]
I have an empty project in Scala with the following `build.sbt`
```
name := "Word2Vec"

version := "1.0"

scalaVersion := "2.11.7"

libraryDependencies ++= Seq(
  "org.deeplearning4j" % "deeplearning4j-nlp" % "0.0.3.3"
)
```
Any idea why I am getting the following error? 

```
Error:Error while importing SBT project:
...
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] sbt.ResolveException: download failed: javax.jms#jms;1.1!jms.jar
[error] download failed: com.sun.jdmk#jmxtools;1.2.1!jmxtools.jar
[error] download failed: com.sun.jmx#jmxri;1.2.1!jmxri.jar
[error] Use 'last' for the full log.

See complete log in /Users/i-danielk/Library/Logs/IntelliJIdea14/sbt.last.log
```

**Comment by danyaljj** [comment]
for some reason the logging dependencies are missing `javax.jms`. So I am excluding it. I ended up changing my `build.sbt` as following:
```
name := "Word2Vec"

version := "1.0"

scalaVersion := "2.11.7"

val slf4jVersion = "1.7.10"

val logbackVersion = "1.1.2"

val slf4jApi = "org.slf4j" % "slf4j-api" % slf4jVersion

val logbackCore = "ch.qos.logback" % "logback-core" % logbackVersion

val logbackClassic = "ch.qos.logback" % "logback-classic" % logbackVersion

libraryDependencies ++= Seq(
  "org.deeplearning4j" % "deeplearning4j-nlp" % "0.0.3.3" exclude ("commons-logging", "commons-logging") exclude ("log4j", "log4j"),
  slf4jApi,
  logbackCore,
  logbackClassic,
  "org.slf4j" % "jcl-over-slf4j" % slf4jVersion,
  "org.slf4j" % "log4j-over-slf4j" % slf4jVersion,
  "org.slf4j" % "jul-to-slf4j" % slf4jVersion
)
```

**Comment by agibsonccc** [comment]
Not sure where JMS is coming from. I don't even use AMQP let alone JMS. I'd
need more info =/
ᐧ

**Comment by twerkmeister** [comment]
I am experiencing the same problem as @danyaljj. I created a dependency graph using the sbt plugin (https://github.com/jrudolph/sbt-dependency-graph). Here is part of the output:

```
[info]       +-org.deeplearning4j:deeplearning4j-scaleout-zookeeper:0.4-rc0
[info]       | +-org.apache.curator:curator-framework:2.4.0
[info]       | | +-com.google.guava:guava:18.0
[info]       | | +-org.apache.curator:curator-client:2.4.0
[info]       | | | +-com.google.guava:guava:18.0
[info]       | | | +-org.apache.zookeeper:zookeeper:3.4.5
[info]       | | | | +-jline:jline:0.9.94
[info]       | | | | | +-junit:junit:4.12
[info]       | | | | |   +-org.hamcrest:hamcrest-core:1.3
[info]       | | | | |   
[info]       | | | | +-log4j:log4j:1.2.15
[info]       | | | | | +-com.sun.jdmk:jmxtools:1.2.1
[info]       | | | | | +-com.sun.jmx:jmxri:1.2.1
[info]       | | | | | +-javax.jms:jms:1.1
[info]       | | | | | +-javax.mail:mail:1.4
[info]       | | | | |   +-javax.activation:activation:1.1
[info]       | | | | |   
[info]       | | | | +-org.slf4j:slf4j-api:1.7.12
[info]       | | | | 
[info]       | | | +-org.slf4j:slf4j-api:1.7.12
[info]       | | | 
[info]       | | +-org.apache.zookeeper:zookeeper:3.4.5
[info]       | |   +-jline:jline:0.9.94
[info]       | |   | +-junit:junit:4.12
[info]       | |   |   +-org.hamcrest:hamcrest-core:1.3
[info]       | |   |   
[info]       | |   +-log4j:log4j:1.2.15
[info]       | |   | +-com.sun.jdmk:jmxtools:1.2.1
[info]       | |   | +-com.sun.jmx:jmxri:1.2.1
[info]       | |   | +-javax.jms:jms:1.1
[info]       | |   | +-javax.mail:mail:1.4
[info]       | |   |   +-javax.activation:activation:1.1
[info]       | |   |   
[info]       | |   +-org.slf4j:slf4j-api:1.7.12
[info]       | |   
[info]       | +-org.apache.curator:curator-recipes:2.4.0
[info]       | | +-com.google.guava:guava:18.0
[info]       | | +-org.apache.curator:curator-framework:2.4.0
[info]       | | | +-com.google.guava:guava:18.0
[info]       | | | +-org.apache.curator:curator-client:2.4.0
[info]       | | | | +-com.google.guava:guava:18.0
[info]       | | | | +-org.apache.zookeeper:zookeeper:3.4.5
[info]       | | | | | +-jline:jline:0.9.94
[info]       | | | | | | +-junit:junit:4.12
[info]       | | | | | |   +-org.hamcrest:hamcrest-core:1.3
[info]       | | | | | |   
[info]       | | | | | +-log4j:log4j:1.2.15
[info]       | | | | | | +-com.sun.jdmk:jmxtools:1.2.1
[info]       | | | | | | +-com.sun.jmx:jmxri:1.2.1
[info]       | | | | | | +-javax.jms:jms:1.1
[info]       | | | | | | +-javax.mail:mail:1.4
[info]       | | | | | |   +-javax.activation:activation:1.1
[info]       | | | | | |   
[info]       | | | | | +-org.slf4j:slf4j-api:1.7.12
[info]       | | | | | 
[info]       | | | | +-org.slf4j:slf4j-api:1.7.12
[info]       | | | | 
[info]       | | | +-org.apache.zookeeper:zookeeper:3.4.5
[info]       | | |   +-jline:jline:0.9.94
[info]       | | |   | +-junit:junit:4.12
[info]       | | |   |   +-org.hamcrest:hamcrest-core:1.3
[info]       | | |   |   
[info]       | | |   +-log4j:log4j:1.2.15
[info]       | | |   | +-com.sun.jdmk:jmxtools:1.2.1
[info]       | | |   | +-com.sun.jmx:jmxri:1.2.1
[info]       | | |   | +-javax.jms:jms:1.1
[info]       | | |   | +-javax.mail:mail:1.4
[info]       | | |   |   +-javax.activation:activation:1.1
[info]       | | |   |   
[info]       | | |   +-org.slf4j:slf4j-api:1.7.12
[info]       | | |   
```
log4j version 1.2.15 requires those libraries. This issue also has been discussed here:
http://stackoverflow.com/questions/4908651/the-following-artifacts-could-not-be-resolved-javax-jmsjmsjar1-1
It seems that upgrading zookeeper or requiring a higher version of log4j can resolve this issue for future releases.

A short term fix is adding this repo to your build.sbt. It happens to have those very old jar files
``` sbt
resolvers += "jboss-m2proxy" at "https://repository.jboss.org/nexus/content/repositories/m2-proxy/"
```

**Comment by danyaljj** [comment]
Although I gave up on this, but thanks for figuring it out, @twerkmeister !

**Comment by agibsonccc** [comment]
We will fix this for the rc due out in a few weeks. Thanks for finding this.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/commit/c2ba1192877dfe21d8a960e13d1d6fae01c5d326
