### ISSUE TITLE
java.lang.IllegalStateException: Mis matched lengths - propably bug

### ISSUE THREAD

**Issue by levil221** [deeplearning4j/deeplearning4j#3724]
#### Issue Description
`Exception in thread "main" java.lang.IllegalStateException: Mis matched lengths: [40] != [320]
	at org.nd4j.linalg.util.LinAlgExceptions.assertSameLength(LinAlgExceptions.java:40)
	at org.nd4j.linalg.api.ops.BaseTransformOp.<init>(BaseTransformOp.java:47)
	at org.nd4j.linalg.api.ops.impl.transforms.Set.<init>(Set.java:24)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:1263)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.put(BaseNDArray.java:2024)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritablesSequence(RecordReaderMultiDataSetIterator.java:578)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:276)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:234)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:177)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:335)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:314)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:37)
	at Network.traning(Network.java:173)
	at Trainer.main(Trainer.java:21)`

I think that problem may be a wrongly calculated size of a new array at pair method in RecordRreaderMultiDataSetIterator. My input was series of 8x40(cols x rows).
And it was working before, somewhere between the end of june and first days of july.
How do I know that my code isn't causing it? I've already ended up with a couple of trained networks from this code.

- expected behavior
work
- encountered behavior
exception
#### Version Information
lasted 0.8.1 snapshot
windows 10 and ubuntu 16.04
cpu backend and cuda 8 backend
lasted nvidia drivers

**Comment by saudet** [comment]
Can we see the code?

**Comment by levil221** [comment]
class for loading data: https://gist.github.com/levil221/5708f7ee221c2c2031897c74dab89ace
learning: https://gist.github.com/levil221/c125fc8d1c62c7926a05f903619db7b4
data in one file: https://gist.github.com/levil221/9042b94aecd6393bc35d8d500f71d3ed
file structure:
myo/
    1/
        example_123421512.csv
        example_123421513.csv
        example_123421514.csv
        example_123421515.csv
    2/
        example_123421512.csv
        example_123421513.csv
        example_123421514.csv
        example_123421515.csv
    3/
        example_123421512.csv
        example_123421513.csv
        example_123421514.csv
        example_123421515.csv
      ...

**Comment by saudet** [comment]
Ok, thanks, but what does the network architecture look like?

**Comment by levil221** [comment]
https://gist.github.com/levil221/744f31ea019bb11d88ff47745ef1579a

**Comment by AlexDBlack** [comment]
Closing this as invalid - your custom record reader is producing 3d NDArrayWritables here:
```
INDArray array = Nd4j.create(dataVec).reshape(1,40,8);
dataInFile = RecordConverter.toRecord(array);
```

The ```List<List<Writable>>``` for sequences may contain NDArrayWritables, but they must be (a) row vectors, and (b) for a single time step only, within the inner loop.
