### ISSUE TITLE
Issues when using very large batch

### ISSUE THREAD

**Issue by dgl85** [deeplearning4j/deeplearning4j#3775]
If model.fit is called with a batch of shape (400000,5600) or larger (>2.1b), the following exception is thrown:
`Exception in thread "main" java.lang.IllegalArgumentException: Length must be >= 1
at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:527)
at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:522)
at org.nd4j.linalg.api.buffer.LongBuffer.<init>(LongBuffer.java:50)
at org.nd4j.linalg.cpu.nativecpu.CpuTADManager.getTADOnlyShapeInfo(CpuTADManager.java:77)
at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.invoke(NativeOpExecutioner.java:522)
at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:581)
at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:100)
at org.nd4j.linalg.api.ndarray.BaseNDArray.doRowWise(BaseNDArray.java:2403)
at org.nd4j.linalg.api.ndarray.BaseNDArray.addiRowVector(BaseNDArray.java:2782)
at org.deeplearning4j.nn.layers.BaseLayer.preOutput(BaseLayer.java:318)
at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:329)
at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:107)
at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1460)
at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1292)
at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:174)
at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:60)
at org.deeplearning4j.optimize.Solver.optimize(Solver.java:53)
at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1149)
at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:963)
at MLPClassifier.main(MLPClassifier.java:244)`

**Comment by AlexDBlack** [comment]
Closing this: this is due to integer overflow, and is (for all intents and purposes) a duplicate of this issue: https://github.com/deeplearning4j/deeplearning4j/issues/3775
