### ISSUE TITLE
Index Out of Bounds Exception in NewsIterator for TrainNews Example

### ISSUE THREAD

**Issue by pythonBooker** [deeplearning4j/deeplearning4j#3830]
#### Issue Description
I ran the TrainNews Example with other Text data and after a few hours of iterations I get:

These relevant files to this example are found with these paths:
*NewsIterator.java: dl4jexamples\src\main\java\org\deeplearning4j\examples\recurrent\processnews\NewsIterator.java

*TrainNews.java: 
dl4j-examples\src\main\java\org\deeplearning4j\examples\recurrent\processnews\TrainNews.java

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 11966, Size: 11966
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.deeplearning4j.examples.recurrent.processnews.NewsIterator.nextDataSet(NewsIterator.java:109)
	at org.deeplearning4j.examples.recurrent.processnews.NewsIterator.next(NewsIterator.java:95)
	at org.deeplearning4j.examples.recurrent.processnews.NewsIterator.next(NewsIterator.java:307)
	at org.deeplearning4j.examples.recurrent.processnews.NewsIterator.next(NewsIterator.java:41)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$IteratorRunnable.run(AsyncDataSetIterator.java:322)

I would expect the behavior just to keep training until complete.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.0
* platform information (OS, etc): Windows 10 Enterprise 64-Bit
* CUDA version, if used: Nvidia Quadro M1000M, CUDA version: 8.0
* NVIDIA driver version, if in use: Driver: 376.51

**Comment by OmSao** [comment]
This issue is reproducible on 17th May 2018 version of DL4J also.
