### ISSUE TITLE
error when run nd4j on gpu

### ISSUE THREAD

**Issue by jasstionzyf** [deeplearning4j/deeplearning4j#3873]
#### Issue Description

i try to run a dl4j program  on gpu,  
but the program throw exeption:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.nd4j.jita.concurrency.CudaAffinityManager.getNumberOfDevices(CudaAffinityManager.java:185)
        at org.nd4j.jita.constant.ConstantProtector.purgeProtector(ConstantProtector.java:38)
        at org.nd4j.jita.constant.ConstantProtector.<init>(ConstantProtector.java:31)
        at org.nd4j.jita.constant.ConstantProtector.<clinit>(ConstantProtector.java:20)
        at org.nd4j.jita.constant.ProtectedCudaConstantHandler.<clinit>(ProtectedCudaConstantHandler.java:48)
        at org.nd4j.jita.constant.CudaConstantHandler.<clinit>(CudaConstantHandler.java:17)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6150)
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
        at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readDataSet(Hdf5Archive.java:182)
        at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readDataSet(Hdf5Archive.java:76)
        at org.deeplearning4j.nn.modelimport.keras.KerasModel.helperImportWeights(KerasModel.java:419)
        at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:176)
        at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:98)
        at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.buildModel(KerasModel.java:641)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:177)
        at org.deeplearning4j.nn.modelimport.keras.trainedmodels.TrainedModelHelper.loadModel(TrainedModelHelper.java:71)
        at com.comm.component.dl4j.FitFromFeaturized.main(FitFromFeaturized.java:54)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
        at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
        at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
        ... 20 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcuda in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
        at org.bytedeco.javacpp.Loader.load(Loader.java:777)
        at org.bytedeco.javacpp.Loader.load(Loader.java:684)
        at org.nd4j.nativeblas.Nd4jCuda.<clinit>(Nd4jCuda.java:10)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.bytedeco.javacpp.Loader.load(Loader.java:739)
        at org.bytedeco.javacpp.Loader.load(Loader.java:684)
        at org.nd4j.nativeblas.Nd4jCuda$NativeOps.<clinit>(Nd4jCuda.java:63)
        at java.lang.Class.forName0(Native Method)
```
related pom: 
```
 <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-ui-model</artifactId>
        <version>${dl4j.version}</version>
    </dependency>
    <dependency>
        <groupId>org.nd4j</groupId>
        <artifactId>nd4j-kryo_2.11</artifactId>
        <version>${nd4j.version}</version>
        <scope>compile</scope>
        <exclusions>
            <exclusion>
                <groupId>de.javakaffee</groupId>
                <artifactId>kryo-serializers</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>de.javakaffee</groupId>
        <artifactId>kryo-serializers</artifactId>
        <version>0.41</version>
        <scope>compile</scope>
        <exclusions>
            <exclusion>
                <groupId>com.esotericsoftware</groupId>
                <artifactId>kryo</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>dl4j-spark_2.11</artifactId>
        <version>${dl4j.version}_spark_2</version>
        <exclusions>
            <exclusion>
                <artifactId>scala-library</artifactId>
                <groupId>org.scala-lang</groupId>

            </exclusion>
        </exclusions>

    </dependency>
    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-core</artifactId>
        <version>${dl4j.version}</version>
        <exclusions>
            <exclusion>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-math3</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-modelimport</artifactId>
        <version>${dl4j.version}</version>
    </dependency>
    <!--<dependency>-->
        <!--<groupId>org.nd4j</groupId>-->
        <!--<artifactId>${nd4j.backend}</artifactId>-->
        <!--<version>${nd4j.version}</version>-->
    <!--</dependency>-->

    <dependency>
        <groupId>org.nd4j</groupId>
        <artifactId>nd4j-cuda-8.0-platform</artifactId>
        <version>${nd4j.version}</version>
    </dependency>
```
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 0.9.1
* platform information ubuntu-14.04
* CUDA version cuda-repo-ubuntu1404_8.0.61-1_amd64.deb

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
is it GOMP 4.0 being missing issue?

**Comment by jasstionzyf** [comment]
@raver119 https://github.com/bytedeco/javacpp-presets/issues/74

**Comment by raver119** [comment]
cc @saudet

**Comment by saudet** [comment]
@raver119 Added some functions that use OpenMP from the CUDA backend, but the lib isn't getting bundled.. Anyway, we can back both backends loaded at the same time, so including nd4j-native in the dependencies might work. Can you try that?

**Comment by jasstionzyf** [comment]
@saudet   i have also try to use nd4j-native  instead of nd4j-native-platform, but also same error

**Comment by saudet** [comment]
@raver119 Xcode and MSVC don't have OpenMP anyway, so maybe we could
disable OpenMP for Linux as well? And use the nd4j-native backend when it's
available?

**Comment by jasstionzyf** [comment]
@saudet @raver119  any updates ?  i also try to run amazone linux ,  also this error

**Comment by saudet** [comment]
@jasstionzyf If you need a solution right now, setting something like the following should work:
```
LD_PRELOAD=~/.javacpp/cache/nd4j-native-0.9.1-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libgomp.so.1
```

**Comment by tripathysa** [comment]
@raver119 : Any fix on this??

**Comment by raver119** [comment]
sam posted fix 1 message above. another fix: install lib manually.

**Comment by tripathysa** [comment]
ok..the posted fix doesn't work for me somehow..same error. Let me work on installing lib manually

**Comment by thhart** [comment]
Have no problems running 0.9.1 in Linux 64 bit with CUDA. Please try to run deeplearning4j-examples from clean checkout and follow: https://deeplearning4j.org/gpu

**Comment by saudet** [comment]
@tripathysa You need to specify a path where libgomp.so.1 actually exists.

**Comment by tripathysa** [comment]
you mean path of libgomp.so.1 on GPU or in project?

**Comment by saudet** [comment]
In JavaCPP cache.

**Comment by tripathysa** [comment]
I can only find libjnind4jcuda.so and  libnd4jcuda.so in path ~/.javacpp/cache/CNNGPU.jar/org/nd4j/nativeblas/linux-x86_64. The path is correct right?

**Comment by saudet** [comment]
Yes, it will show up when using the CPU backend (nd4j-native).

**Comment by tripathysa** [comment]
@jasstionzyf : Is your issue resolved?

**Comment by tripathysa** [comment]
@saudet : Still the same error..I cannot figure this out. Any help would be appreciated.
My build.gradle: https://gist.github.com/tripathysa/fd205186715cb5519bb82d7a24747568
My Training file: https://gist.github.com/tripathysa/a667cfdcca4ea43d71b87f2ccf7df688

**Comment by saudet** [comment]
Where are you setting LD_PRELOAD?
