### ISSUE TITLE
IllegalStateException from BackTrackLineSearch.java

### ISSUE THREAD

**Issue by cqiaoYc** [deeplearning4j/deeplearning4j#3879]
#### Issue Description
java.lang.IllegalStateException: Mis matched shapes
	at org.nd4j.linalg.util.LinAlgExceptions.assertSameShape(LinAlgExceptions.java:45)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.divi(BaseNDArray.java:3066)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.divi(BaseNDArray.java:3046)
	at org.deeplearning4j.optimize.solvers.BackTrackLineSearch.optimize(BackTrackLineSearch.java:175)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:232)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:53)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1780)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1729)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1832)
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.1
* platform information : win10 64
<dependency>
            <groupId>org.jcuda</groupId>
            <artifactId>jcuda</artifactId>
            <version>0.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.jcuda</groupId>
            <artifactId>jcublas</artifactId>
            <version>0.8.0</version>
        </dependency>

**Comment by agibsonccc** [comment]
Stick to SGD..we are going to deprecate the line search based algos.
