### ISSUE TITLE
Running ParagraphVectorsClassifierExample from the command line, I get java.io.FileNotFoundException: /tmp/datavec_temp3705004023053468dir/META-INF/MANIFEST.MF

### ISSUE THREAD

**Issue by ivan4github** [deeplearning4j/deeplearning4j#3910]
#### Issue Description

After an install from Quickstart and a successful run from IntelliJ,
running ParagraphVectorsClassifierExample from the command line, I get java.io.FileNotFoundException: /tmp/datavec_temp3705004023053468dir/META-INF/MANIFEST.MF

MLPClassifierLinearExample run fine from the command line.

Here is my command line:

java -noverify -cp $SOFTWARE/dl4j-examples/dl4j-examples/target/dl4j-examples-0.9.1-bin.jar org.deeplearning4j.examples.nlp.paragraphvectors.ParagraphVectorsClassifierExample

Here is the full trace:

Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: /tmp/datavec_temp3705004023053468dir/META-INF/MANIFEST.MF (Aucun fichier ou dossier de ce type)
	at org.datavec.api.util.ClassPathResource.getFile(ClassPathResource.java:160)
	at org.datavec.api.util.ClassPathResource.getFile(ClassPathResource.java:100)
	at org.deeplearning4j.examples.nlp.paragraphvectors.ParagraphVectorsClassifierExample.makeParagraphVectors(ParagraphVectorsClassifierExample.java:73)
	at org.deeplearning4j.examples.nlp.paragraphvectors.ParagraphVectorsClassifierExample.main(ParagraphVectorsClassifierExample.java:49)
Caused by: java.io.FileNotFoundException: /tmp/datavec_temp3705004023053468dir/META-INF/MANIFEST.MF (Aucun fichier ou dossier de ce type)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.datavec.api.util.ArchiveUtils.unzipFileTo(ArchiveUtils.java:78)
	at org.datavec.api.util.ClassPathResource.getFile(ClassPathResource.java:134)
	... 3 more

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.1
* platform information (OS, etc): Debian 9 "Stretch"
* CUDA version, if used: CPU only
* NVIDIA driver version, if in use: None
* Java:  openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by jariojose** [comment]
Did you solve the problem? I have the same error...

**Comment by raver119** [comment]
Can you please give us more details about your environment? Members of our team were unable to reproduce this issue...
