### ISSUE TITLE
Regression: WordVectorsImpl#readBinaryModel() can't read GoogleNews-vectors

### ISSUE THREAD

**Issue by carschno** [deeplearning4j/deeplearning4j#396]
I am afraid that the fix for #390 causes an end-of-file exception when reading GoogleNews-vectors-negative300.bin as downloadable from the Word2Vec page:
```
Exception in thread "main" java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readString(WordVectorSerializer.java:244)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readBinaryModel(WordVectorSerializer.java:187)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadGoogleModel(WordVectorSerializer.java:79)
[...]
```
However, it works for Word2Vec files that I created with the most recent Word2Vec version. I wonder if there has been a change in the output format. I suppose the root error is hidden in the readString() method in relation to line breaks in the binary file.
For the time being, I recommend to revert the fix for #390; I'm trying to figure out what is really going on there. Any hints appreciated.

**Comment by carschno** [comment]
Turns out that some files (presumably ones created with recent Word2Vec version) have line breaks at the end of each word/vector while others, like GoogeVectors, don't. I am adding an option to define whether or not the input file has line breaks with a default set to "no".
