### ISSUE TITLE
CUDA - MemcpyAsync failed on last time step vertex test

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3966]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/graph/graphnodes/TestGraphNodes.java#L542-L591

Not sure what's up here - it's not workspaces though (they are set to none).

```
Failed on [759244288] -> [163653120], size: [12800], direction: [2], result: [11]
CUDA error at D:/jenkins/workspace/dl4j/all-multiplatform_windows-x86_64/libnd4j/stream3/libnd4j/blas/cuda/NativeOps.cu:4887 code=11(cudaErrorInvalidValue) "result" 

java.lang.IllegalStateException: MemcpyAsync failed: AllocationShape(offset=0, length=1600, stride=1, elementSize=8, dataType=DOUBLE)

	at org.nd4j.jita.flow.impl.SynchronousFlowController.synchronizeToHost(SynchronousFlowController.java:63)
	at org.nd4j.jita.flow.impl.GridFlowController.synchronizeToHost(GridFlowController.java:34)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.synchronizeThreadDevice(CudaZeroHandler.java:1253)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.synchronizeHostData(AtomicAllocator.java:350)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.getDouble(BaseCudaDataBuffer.java:1059)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3650)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:113)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:127)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:95)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:91)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:4848)
	at org.nd4j.linalg.jcublas.JCublasNDArray.toString(JCublasNDArray.java:456)
	at org.deeplearning4j.nn.graph.graphnodes.TestGraphNodes.testLastTimeStepWithTransfer(TestGraphNodes.java:590)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code -1

```

**Comment by raver119** [comment]
I guess this issue is irrelevant now.
