### ISSUE TITLE
Spark evaluation NPEs

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3970]
Under some rare circumstances, Spark evaluation can lead to a NPE here:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark/src/main/java/org/deeplearning4j/spark/impl/multilayer/evaluation/IEvaluationReduceFunction.java#L19-L21

I'm not totally sure on the cause here - I suspect this can occur with empty partitions, or fewer partitions than executors (10 objects on 16 workers causes NPE, but 10 objects on 8 workers doesn't). Either way, a defensive null check in that merge function should help.
Tested with Spark 2.1.0.

```
Caused by: java.lang.NullPointerException
	at org.deeplearning4j.spark.impl.multilayer.evaluation.IEvaluationReduceFunction.call(IEvaluationReduceFunction.java:22)
	at org.deeplearning4j.spark.impl.multilayer.evaluation.IEvaluationReduceFunction.call(IEvaluationReduceFunction.java:16)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction2$1.apply(JavaPairRDD.scala:1037)
```

**Comment by GregaVrbancic** [comment]
Hi! I'm experiencing the same issue in evaluation phase using DL4J 0.9.1 with Spark 2.1: 

```
Caused by: java.lang.NullPointerException
	at org.deeplearning4j.spark.impl.multilayer.evaluation.IEvaluationReduceFunction.call(IEvaluationReduceFunction.java:19)
	at org.deeplearning4j.spark.impl.multilayer.evaluation.IEvaluationReduceFunction.call(IEvaluationReduceFunction.java:13)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction2$1.apply(JavaPairRDD.scala:1037)
```

Is there any workaround I could try to make it work? I tried running it with different number of workers with no success.

Thanks!

**Comment by AlexDBlack** [comment]
@GregaVrbancic only thing I can suggest: take the code from here
https://github.com/deeplearning4j/deeplearning4j/blob/802ea94617d2eb7c43b554d29f28636430b92abc/deeplearning4j-scaleout/spark/dl4j-spark/src/main/java/org/deeplearning4j/spark/impl/multilayer/SparkDl4jMultiLayer.java#L596-L600

and adapt it in your project to use the fix from this PR (i.e., the modified IEvaluationReduceFunction) :
https://github.com/deeplearning4j/deeplearning4j/pull/4394

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4394
