### ISSUE TITLE
How to use Convolution1DLayer with TBPTT?

### ISSUE THREAD

**Issue by OssamaAlshabrawy** [deeplearning4j/deeplearning4j#3994]
* Deeplearning4j version 0.9
* platform information (OS): Linux

I have a time series data. I've tried to use Convolution1DLayer, Subsampling1DLayer preceding the Graves LSTM layers with TBPTT. My network conf:
```
MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .seed(123)
                .iterations(1)
                .regularization(true).dropOut(0.8)
                .regularization(true).l1(0.0005) // l1 as a penalty on the activations
                .learningRate(0.001)
                .weightInit(WeightInit.XAVIER)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
               

                .list()
                .layer(0, new Convolution1DLayer.Builder(16)  // no need to .inputPreProcessor()
                        .nIn(256) // in case of Conv1D
                        .nOut(32) // # filters
                        .stride(2) // step size
                        .activation(Activation.LEAKYRELU)
                        .weightInit(WeightInit.RELU)
                        .updater(Updater.RMSPROP)
                        .build()) //
                .layer(1, new Subsampling1DLayer.Builder(SubsamplingLayer.PoolingType.MAX)
                        .kernelSize(2)
                        .stride(1)
                        .build()) //
                .layer(2, new Convolution1DLayer.Builder(16)
                        .nIn(32)
                        .nOut(32)
                        .stride(2)
                        .activation(Activation.LEAKYRELU)
                        .weightInit(WeightInit.RELU)
                        .updater(Updater.RMSPROP)
                        .build()) //
                .layer(3, new DenseLayer.Builder()
                        .activation(Activation.LEAKYRELU)
                        .nIn(32) // 
                        .nOut(256)
                        .weightInit(WeightInit.RELU)
                        .updater(Updater.ADAM)
                        .build())
                .layer(4, new GravesLSTM.Builder().nIn(256).nOut(256)
                        .activation(Activation.LEAKYRELU).updater(Updater.ADAM).build())
                .layer(5, new GravesLSTM.Builder().nIn(256).nOut(256)
                        .activation(Activation.LEAKYRELU).updater(Updater.ADAM).build())
                .layer(6, new GravesLSTM.Builder().nIn(256).nOut(256)
                        .activation(Activation.LEAKYRELU).updater(Updater.ADAM).build())
                .layer(7, new GravesLSTM.Builder().nIn(256).nOut(256)
                        .activation(Activation.LEAKYRELU).updater(Updater.ADAM).build())
                .layer(8, new GravesLSTM.Builder().nIn(256).nOut(256)
                        .activation(Activation.LEAKYRELU).updater(Updater.ADAM).build())
                .layer(9, new GravesLSTM.Builder().nIn(256).nOut(256)
                        .activation(Activation.LEAKYRELU).updater(Updater.ADAM).build())
                .layer(10, new GravesLSTM.Builder().nIn(256).nOut(256)
                        .activation(Activation.LEAKYRELU).updater(Updater.ADAM).build())
                .layer(11, new RnnOutputLayer.Builder(LossFunctions.LossFunction.MCXENT)
                        .activation(Activation.SOFTMAX)
                        .nIn(256).nOut(2).build())

                .setInputType(InputType.recurrent(256))

                .pretrain(false).backprop(true)
                .backpropType(BackpropType.TruncatedBPTT).tBPTTForwardLength(tbpttLength).tBPTTBackwardLength(tbpttLength)
                .build();
```
and I've got the following exception:
```
Exception in thread "main" java.lang.IllegalStateException: Mis matched shapes
	at org.nd4j.linalg.util.LinAlgExceptions.assertSameShape(LinAlgExceptions.java:45)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:3138)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:3119)
	at org.nd4j.linalg.lossfunctions.impl.LossMCXENT.computeGradient(LossMCXENT.java:157)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.getGradientsAndDelta(BaseOutputLayer.java:169)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.backpropGradient(BaseOutputLayer.java:148)
	at org.deeplearning4j.nn.layers.recurrent.RnnOutputLayer.backpropGradient(RnnOutputLayer.java:63)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.truncatedBPTTGradient(MultiLayerNetwork.java:1526)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2219)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:174)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:60)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:53)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doTruncatedBPTT(MultiLayerNetwork.java:1468)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1227)
```
After discussion with Susan Early (DL4J team), we agree on RnnOutputLayer received different # time steps  than the # labels passed to this output layer.

_I can say the reason for that is because the convolution layers downsample the data then the # time steps will be reduced even if you try .convolutionMode and choose Same_

**Comment by OssamaAlshabrawy** [comment]
After looking over the source code for Convolution layer and see how the ConvolutionMode, I can say the only solution which I tried it is:
choose convolution mode to be **Same**
& the stride must be **1**. This will prevent the downsampling of the timesteps.

_still needed how can we perform that with any number of stride?_
_and so the padding in the convolution mode should be generalised_

**Comment by AlexDBlack** [comment]
By definition, any stride > 1 will result in downsampling, even with SAME mode.
I'll close this - it's not possible to have the same output size with stride > 1. That said, transposed/fractionally strided/deconvolutional layers can (afaik) in principle support such connection structures, but I'm not sure that's what you want here.
