### ISSUE TITLE
Keras conv2d layer support

### ISSUE THREAD

**Issue by dani97** [deeplearning4j/deeplearning4j#4003]
#### Issue Description

I could not load my model with conv2d function

dl4j version 0.9.1

*please provide the snapshot version and how to represent in pom.xml 

this is the exception 
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.UnsupportedKerasConfigurationException: Unsupported keras layer type Conv2D. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.KerasLayer.getKerasLayerFromConfig(KerasLayer.java:261)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.helperPrepareLayers(KerasModel.java:191)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:99)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:56)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.buildSequential(KerasModel.java:646)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:140)
	at org.deeplearning4j.examples.dataexamples.ModelImportKeraConfig.main(ModelImportKeraConfig.java:13)

**Comment by maxpumperla** [comment]
@dani97 this is not actually an issue, we only support keras 2 model import since `0.9.2-SNAPSHOT` and `Conv2D` is a Keras 2 layer.

**Comment by maxpumperla** [comment]
so either upgrade your dl4j version or downgrade to keras 1.2.2

**Comment by hendriks73** [comment]
Hint: If you're using maven, you can use `0.9.2-SNAPSHOT` by adding the snapshot repo to your `pom.xml`.

```
<repository>
    <id>sonatype-nexus-snapshots</id>
    <name>Sonatype Nexus Snapshots</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
```
