### ISSUE TITLE
Please support ELU activation function (Keras 2 import)

### ISSUE THREAD

**Issue by hendriks73** [deeplearning4j/deeplearning4j#4030]
#### Issue Description

The `elu` (*not* `relu`) activation function is not supported.
When importing a Keras 2 model with `elu`, an exception is thrown:

```
org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unknown Keras activation function elu. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasActivationUtils.mapActivation(KerasActivationUtils.java:62)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasActivationUtils.getActivationFromConfig(KerasActivationUtils.java:82)
```

ELU is described in https://arxiv.org/pdf/1511.07289.pdf%5Cnhttp://arxiv.org/abs/1511.07289%5Cnhttp://arxiv.org/abs/1511.07289 :

> The exponential linear unit (ELU) with 0 < α is
```
f(x) = x              if x > 0
f(x) = α(exp(x)−1)    if x ≤ 0

f'(x) = 1             if x > 0
f'(x) = f(x)+α        if x ≤ 0

By default, α is 1.0
```

[Keras docs](https://keras.io/layers/advanced-activations/#elu)
[Keras source](https://github.com/fchollet/keras/blob/master/keras/layers/advanced_activations.py#L141)
#### Version Information

This is on the most recent snapshot, i.e. `0.9.2-20170906.063037-230`

#### Note

I'm aware that this is not a bug, but a feature request (especially given that I've used the snapshot).

Thanks.

**Comment by hendriks73** [comment]
Just realized, the function itself is already implemented in `org.nd4j.linalg.api.ops.impl.transforms.ELU`. Just the mapping is missing.

**Comment by hendriks73** [comment]
I suspect, modifying `KerasActivationUtils.mapActivation()` like this, might do the trick:

```
    public static IActivation mapActivation(String kerasActivation, KerasLayerConfiguration conf)
            throws UnsupportedKerasConfigurationException {
        IActivation dl4jActivation = null;
        /* Keras and DL4J use the same name for most activations. */
        if (kerasActivation.equals(conf.getKERAS_ACTIVATION_SOFTMAX())) {
            dl4jActivation = new ActivationSoftmax();
        } else if (kerasActivation.equals(conf.getKERAS_ACTIVATION_SOFTPLUS())) {
            dl4jActivation = new ActivationSoftPlus();
        } else if (kerasActivation.equals(conf.getKERAS_ACTIVATION_SOFTSIGN())) {
            dl4jActivation = new ActivationSoftSign();
        } else if (kerasActivation.equals(conf.getKERAS_ACTIVATION_RELU())) {
            dl4jActivation = new ActivationReLU();
        } else if (kerasActivation.equals(conf.getKERAS_ACTIVATION_TANH())) {
            dl4jActivation = new ActivationTanH();
        } else if (kerasActivation.equals(conf.getKERAS_ACTIVATION_SIGMOID())) {
            dl4jActivation = new ActivationSigmoid();
        } else if (kerasActivation.equals(conf.getKERAS_ACTIVATION_HARD_SIGMOID())) {
            dl4jActivation = new ActivationHardSigmoid();
        } else if (kerasActivation.equals(conf.getKERAS_ACTIVATION_LINEAR())) {
            dl4jActivation = new ActivationIdentity();
        // ========= SELU and ELU are new ========= //
        } else if (kerasActivation.equals(conf.getKERAS_ACTIVATION_SELU())) {
            dl4jActivation = new ActivationSELU();
        } else if (kerasActivation.equals(conf.getKERAS_ACTIVATION_ELU())) {
            dl4jActivation = new ActivationELU();
        } else {
            throw new UnsupportedKerasConfigurationException(
                    "Unknown Keras activation function " + kerasActivation);
        }
        return dl4jActivation;
    }
```

**Comment by maxpumperla** [comment]
done, check master :)
