### ISSUE TITLE
Ressource: "data/svmLight/iris_svmLight_0.txt" missing in deeplearning4j-scaleout/spark/dl4j-spark/src/test/resources

### ISSUE THREAD

**Issue by olafhel** [deeplearning4j/deeplearning4j#405]
```
java.io.FileNotFoundException: class path resource [data/svmLight/iris_svmLight_0.txt] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:177)
	at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:48)
	at org.deeplearning4j.spark.canova.MiniBatchTests.testMiniBatches(MiniBatchTests.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by olafhel** [comment]
The resource is actually missing.
Even by adding the dependency in the poms

    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>dl4j-test-resources</artifactId>
        <version>${project.version}</version>
        <scope>test</scope>
    </dependency>

**Comment by Lewuathe** [comment]
@olafhel 
As dicussed in https://github.com/deeplearning4j/deeplearning4j/issues/421, there are some cases when you cannot find test-resources in test. What type of command did you run? And from where?

**Comment by agibsonccc** [comment]
This is related to dl4j-test-resources. All of the resource should be put in there. Mainly need bandwidth to clean it up.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/commit/6d58897143dead32a042597fcef13e436b95f2fb
