### ISSUE TITLE
Test failure on E2E KerasmodelImport DCGAN (probable forgotten file)

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/deeplearning4j#4056]
#### Issue Description

On backend cpu, one probably forgotten file that should be added to and read from dl4j-test-resources.

```
FAILURE! - in org.deeplearning4j.nn.modelimport.keras.e2e.KerasModelEndToEndTest
importDcganDiscriminator(org.deeplearning4j.nn.modelimport.keras.e2e.KerasModelEndToEndTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.io.FileNotFoundException: class path resource [modelimport/keras/examples/mnist_dcgan/dcgan_discriminator_epoch_50.h5] cannot be opened because it does not exist
	at org.deeplearning4j.nn.modelimport.keras.e2e.KerasModelEndToEndTest.importModelH5Test(KerasModelEndToEndTest.java:216)
	at org.deeplearning4j.nn.modelimport.keras.e2e.KerasModelEndToEndTest.importDcganDiscriminator(KerasModelEndToEndTest.java:203)

importDcganGenerator(org.deeplearning4j.nn.modelimport.keras.e2e.KerasModelEndToEndTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.io.FileNotFoundException: class path resource [modelimport/keras/examples/mnist_dcgan/dcgan_generator_epoch_50.h5] cannot be opened because it does not exist
	at org.deeplearning4j.nn.modelimport.keras.e2e.KerasModelEndToEndTest.importModelH5Test(KerasModelEndToEndTest.java:216)
	at org.deeplearning4j.nn.modelimport.keras.e2e.KerasModelEndToEndTest.importDcganGenerator(KerasModelEndToEndTest.java:207)


Results :

Tests in error: 
  KerasModelEndToEndTest.importDcganDiscriminator:203->importModelH5Test:216 » FileNotFound
  KerasModelEndToEndTest.importDcganGenerator:207->importModelH5Test:216 » FileNotFound
```

Full log: https://gist.github.com/c16afa0bc88f24b4af2bf28c9c7bc13f

Bisection:
```
700d7e5454a0a0cbb5cff1598613d499fe802a6c is the first bad commit
commit 700d7e5454a0a0cbb5cff1598613d499fe802a6c
Author: Max Pumperla <max.pumperla@googlemail.com>
Date:   Mon Sep 11 13:37:04 2017 +0200

    import DCGAN

:040000 040000 2736eaa154e52529a85372ca7276b456014d0ab6 377a544b26c4631c5835c39c3b22f17e83ee6c0b M	deeplearning4j-modelimport
```

**Comment by huitseeker** [comment]
Argh, nevermind, I had not noticed https://github.com/deeplearning4j/dl4j-test-resources/commit/9d69e14bd0d11fbb6011a6f06797868c6b45d149 which solves this

**Comment by maxpumperla** [comment]
:)
