### ISSUE TITLE
SVMLight parser is throwing exceptions for my 

### ISSUE THREAD

**Issue by kryton** [deeplearning4j/deeplearning4j#409]
my code sample is here.
I'm just trying to read the file I generated via canova.

https://gist.github.com/kryton/2d8d8b3ffe27052f6d28

It seems to work ok if there is >1< record in the file. but fails if there >1.
```
17:03:47.565 [main] DEBUG org.reflections.Reflections 186 - going to scan these urls:
jar:file:/Users/iholsman/.m2/repository/org/nd4j/nd4j-jackson/0.0.3.5.5.6-SNAPSHOT/nd4j-jackson-0.0.3.5.5.6-SNAPSHOT.jar!/
jar:file:/Users/iholsman/.m2/repository/org/nd4j/nd4j-jblas/0.0.3.5.5.6-SNAPSHOT/nd4j-jblas-0.0.3.5.5.6-SNAPSHOT.jar!/
jar:file:/Users/iholsman/.m2/repository/org/nd4j/nd4j-api/0.0.3.5.5.6-SNAPSHOT/nd4j-api-0.0.3.5.5.6-SNAPSHOT.jar!/
17:03:47.708 [main] INFO  org.reflections.Reflections 229 - Reflections took 137 ms to scan 3 urls, producing 69 keys and 207 values 
Exception in thread "main" java.lang.IllegalStateException: Illegal number of rows for array 1
	at org.nd4j.linalg.factory.BaseNDArrayFactory.vstack(BaseNDArrayFactory.java:1152)
	at org.nd4j.linalg.factory.Nd4j.vstack(Nd4j.java:3702)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:136)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:251)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:45)
	at com.XXXX.gruesomeBird.dl4j.DL.main(DL.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
-- org.jblas INFO Deleting /var/folders/7n/z3_355f93p51y8chtcm82tt80000gn/T/jblas8216124597205152938/libjblas.dylib
-- org.jblas INFO Deleting /var/folders/7n/z3_355f93p51y8chtcm82tt80000gn/T/jblas8216124597205152938/libjblas_arch_flavor.dylib
-- org.jblas INFO Deleting /var/folders/7n/z3_355f93p51y8chtcm82tt80000gn/T/jblas8216124597205152938
```

**Comment by kryton** [comment]
note .. switching to  SVMLightRecordReader() from LibSvmRecordReader() didn't change the exception.

**Comment by agibsonccc** [comment]
SVMLight can handle sparse data now. I'll give Lib svm a similar treatment
