### ISSUE TITLE
cuDNN - "This pointer address is NULL" error

### ISSUE THREAD

**Issue by Wilwilly** [deeplearning4j/deeplearning4j#4106]
The pom file and source code is pretty much the same as in https://github.com/deeplearning4j/nd4j/issues/2140, except for the layers which now are LSTM instead of GravesLSTM to support cudNN.

The error I'm getting is this, but training continuous normally (or so it seems): 

```
Exception in thread "JavaCPP Deallocator" java.lang.NullPointerException: This pointer address is NULL.
	at org.bytedeco.javacpp.PointerPointer.get(Native Method)
	at org.deeplearning4j.nn.layers.BaseCudnnHelper$TensorArray$Deallocator.deallocate(BaseCudnnHelper.java:146)
	at org.bytedeco.javacpp.Pointer$DeallocatorReference.clear(Pointer.java:278)
	at org.bytedeco.javacpp.Pointer$DeallocatorThread.run(Pointer.java:300)
```

Full backtrace:

```
04:06:28.107 [main] INFO  org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
04:06:28.132 [main] DEBUG org.reflections.Reflections - going to scan these urls:
file:/home/user/.jdk1.8.0_144/jre/lib/ext/cldrdata.jar
file:/home/user/.jdk1.8.0_144/jre/lib/ext/localedata.jar
file:/home/user/.jdk1.8.0_144/jre/lib/ext/nashorn.jar
file:/home/user/.jdk1.8.0_144/jre/lib/ext/jaccess.jar
file:/home/user/.jdk1.8.0_144/jre/lib/ext/dnsns.jar
file:/home/user/op/t.jar
file:/home/user/.jdk1.8.0_144/jre/lib/ext/sunpkcs11.jar
file:/home/user/.jdk1.8.0_144/jre/lib/ext/zipfs.jar
file:/home/user/.jdk1.8.0_144/jre/lib/ext/jfxrt.jar
file:/home/user/.jdk1.8.0_144/jre/lib/ext/sunec.jar
file:/home/user/.jdk1.8.0_144/jre/lib/ext/sunjce_provider.jar
04:06:28.159 [main] INFO  org.reflections.Reflections - Reflections took 26 ms to scan 11 urls, producing 9182 keys and 9503 values 
04:06:30.792 [main] INFO  org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 32
04:06:31.079 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.082 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.083 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.083 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.085 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.085 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.086 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.087 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.088 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.088 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.089 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.090 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.091 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.092 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.093 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.094 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.095 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.096 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.096 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.097 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.098 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.099 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.100 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.101 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.101 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.103 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.103 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.104 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.105 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.106 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.107 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.108 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
04:06:31.335 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.337 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.338 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.339 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.340 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.341 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.342 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.343 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.343 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.344 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.345 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.346 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.347 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.348 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.349 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.350 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.351 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.352 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.353 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.354 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.355 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.355 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.356 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.357 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.358 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.359 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.360 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.361 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.362 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.362 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.363 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.364 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [1]...
04:06:31.591 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.593 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.594 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.595 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.596 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.597 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.598 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.599 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.599 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.600 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.601 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.602 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.603 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.604 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.605 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.606 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.607 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.608 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.609 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.610 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.611 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.611 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.612 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.613 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.614 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.615 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.616 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.617 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.618 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.619 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.619 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.620 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [2]...
04:06:31.623 [main] DEBUG o.n.j.c.CudaAffinityManager - Mapping thread [1] to device [0], out of [3] devices...
04:06:31.623 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [17] to device [0], out of [3] devices...
04:06:31.624 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [18] to device [0], out of [3] devices...
04:06:31.624 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [19] to device [0], out of [3] devices...
04:06:31.624 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [20] to device [0], out of [3] devices...
04:06:31.624 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [21] to device [0], out of [3] devices...
04:06:31.626 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [22] to device [0], out of [3] devices...
04:06:31.628 [main] DEBUG org.reflections.Reflections - going to scan these urls:
jar:file:/home/user/op/nd4j-parameter-server-model-0.9.1.jar!/
jar:file:/home/user/op/nd4j-cuda-8.0-0.9.1-linux-x86_64.jar!/
jar:file:/home/user/op/nd4j-native-api-0.9.1.jar!/
jar:file:/home/user/op/nd4j-jackson-0.9.1.jar!/
jar:file:/home/user/op/nd4j-parameter-server-0.9.1.jar!/
jar:file:/home/user/op/nd4j-context-0.9.1.jar!/
jar:file:/home/user/op/nd4j-cuda-8.0-0.9.1.jar!/
jar:file:/home/user/op/nd4j-api-0.9.1.jar!/
jar:file:/home/user/op/nd4j-cuda-8.0-0.9.1-macosx-x86_64.jar!/
jar:file:/home/user/op/nd4j-base64-0.9.1.jar!/
jar:file:/home/user/op/jackson-0.9.1.jar!/
jar:file:/home/user/op/nd4j-buffer-0.9.1.jar!/
jar:file:/home/user/op/nd4j-cuda-8.0-0.9.1-windows-x86_64.jar!/
jar:file:/home/user/op/nd4j-aeron-0.9.1.jar!/
jar:file:/home/user/op/nd4j-cuda-8.0-0.9.1-linux-ppc64le.jar!/
jar:file:/home/user/op/nd4j-parameter-server-client-0.9.1.jar!/
jar:file:/home/user/op/nd4j-common-0.9.1.jar!/
04:06:31.672 [main] INFO  org.reflections.Reflections - Reflections took 44 ms to scan 17 urls, producing 31 keys and 227 values 
04:06:31.731 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Linux]
04:06:31.731 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [14.0GB];
04:06:31.731 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
04:06:31.731 [main] INFO  o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 980 Ti]; CC: [5.2]; Total/free memory: [6370885632]
04:06:31.732 [main] INFO  o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 1060 3GB]; CC: [6.1]; Total/free memory: [3159687168]
04:06:31.732 [main] INFO  o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 980 Ti]; CC: [5.2]; Total/free memory: [6372982784]
04:06:31.762 [main] DEBUG o.n.j.handler.impl.CudaZeroHandler - Creating bucketID: 4
04:06:31.773 [main] DEBUG o.n.j.handler.impl.CudaZeroHandler - Creating bucketID: 1
04:06:31.776 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [23] to device [0], out of [3] devices...
04:06:31.778 [AMDSI prefetch thread] DEBUG o.n.l.memory.abstracts.Nd4jWorkspace - Steps: 10
04:06:31.781 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [24] to device [0], out of [3] devices...
04:06:31.781 [ADSI prefetch thread] DEBUG o.n.l.memory.abstracts.Nd4jWorkspace - Steps: 10
04:06:31.781 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [25] to device [0], out of [3] devices...
Datasets ready in 3ms
04:06:31.782 [ADSI prefetch thread] DEBUG o.n.j.handler.impl.CudaZeroHandler - Creating bucketID: 3
04:06:31.783 [ADSI prefetch thread] DEBUG o.n.j.handler.impl.CudaZeroHandler - Creating bucketID: 5
04:06:31.976 [main] DEBUG org.reflections.Reflections - going to scan these urls:
file:/home/user/op/t.jar
04:06:32.018 [main] INFO  org.reflections.Reflections - Reflections took 41 ms to scan 1 urls, producing 13 keys and 154 values 
04:06:32.070 [main] INFO  o.d.nn.multilayer.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: SINGLE; inference: SINGLE]
04:06:32.074 [main] DEBUG o.n.j.handler.impl.CudaZeroHandler - Creating bucketID: 2
04:06:32.087 [ADSI prefetch thread] DEBUG o.n.j.handler.impl.CudaZeroHandler - Creating bucketID: 0
04:06:32.141 [main] DEBUG org.reflections.Reflections - going to scan these urls:
jar:file:/home/user/op/nd4j-parameter-server-model-0.9.1.jar!/
jar:file:/home/user/op/nd4j-cuda-8.0-0.9.1-linux-x86_64.jar!/
jar:file:/home/user/op/nd4j-native-api-0.9.1.jar!/
jar:file:/home/user/op/nd4j-jackson-0.9.1.jar!/
jar:file:/home/user/op/nd4j-parameter-server-0.9.1.jar!/
jar:file:/home/user/op/nd4j-context-0.9.1.jar!/
jar:file:/home/user/op/nd4j-cuda-8.0-0.9.1.jar!/
jar:file:/home/user/op/nd4j-api-0.9.1.jar!/
jar:file:/home/user/op/nd4j-cuda-8.0-0.9.1-macosx-x86_64.jar!/
jar:file:/home/user/op/nd4j-base64-0.9.1.jar!/
jar:file:/home/user/op/jackson-0.9.1.jar!/
jar:file:/home/user/op/nd4j-buffer-0.9.1.jar!/
jar:file:/home/user/op/nd4j-cuda-8.0-0.9.1-windows-x86_64.jar!/
jar:file:/home/user/op/nd4j-aeron-0.9.1.jar!/
jar:file:/home/user/op/nd4j-cuda-8.0-0.9.1-linux-ppc64le.jar!/
jar:file:/home/user/op/nd4j-parameter-server-client-0.9.1.jar!/
jar:file:/home/user/op/nd4j-common-0.9.1.jar!/
04:06:32.281 [main] INFO  org.reflections.Reflections - Reflections took 140 ms to scan 17 urls, producing 416 keys and 1637 values 
04:06:32.674 [main] DEBUG o.d.nn.layers.recurrent.LSTM - CudnnLSTMHelper successfully initialized
04:06:32.684 [main] DEBUG o.d.nn.layers.recurrent.LSTM - CudnnLSTMHelper successfully initialized
04:06:32.690 [main] DEBUG o.d.nn.layers.recurrent.LSTM - CudnnLSTMHelper successfully initialized
04:06:32.765 [main] DEBUG o.d.d.iterator.AsyncDataSetIterator - Manually destroying ADSI workspace
04:06:32.783 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [27] to device [0], out of [3] devices...
04:06:32.783 [ADSI prefetch thread] DEBUG o.n.l.memory.abstracts.Nd4jWorkspace - Steps: 10
04:06:43.239 [main] DEBUG o.d.d.iterator.AsyncDataSetIterator - Manually destroying ADSI workspace
04:06:43.254 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [28] to device [0], out of [3] devices...
04:06:43.254 [ADSI prefetch thread] DEBUG o.n.l.memory.abstracts.Nd4jWorkspace - Steps: 10
04:06:43.681 [main] INFO  o.d.e.t.BaseEarlyStoppingTrainer - Starting early stopping training
04:06:43.706 [main] DEBUG o.d.d.iterator.AsyncDataSetIterator - Manually destroying ADSI workspace
04:06:43.722 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [30] to device [0], out of [3] devices...
04:06:43.722 [ADSI prefetch thread] DEBUG o.n.l.memory.abstracts.Nd4jWorkspace - Steps: 10
04:06:43.852 [main] INFO  org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 0
04:06:44.107 [main] DEBUG o.d.d.iterator.AsyncDataSetIterator - Manually destroying ADSI workspace
04:06:44.123 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [31] to device [0], out of [3] devices...
04:06:44.123 [main] INFO  o.d.o.listeners.EvaluativeListener - Starting evaluation nr. 1
04:06:44.123 [ADSI prefetch thread] DEBUG o.n.l.memory.abstracts.Nd4jWorkspace - Steps: 10
Exception in thread "JavaCPP Deallocator" java.lang.NullPointerException: This pointer address is NULL.
  at org.bytedeco.javacpp.PointerPointer.get(Native Method)
  at org.deeplearning4j.nn.layers.BaseCudnnHelper$TensorArray$Deallocator.deallocate(BaseCudnnHelper.java:146)
  at org.bytedeco.javacpp.Pointer$DeallocatorReference.clear(Pointer.java:278)
  at org.bytedeco.javacpp.Pointer$DeallocatorThread.run(Pointer.java:300)
04:06:45.684 [main] INFO  o.d.o.listeners.EvaluativeListener - Reporting evaluation results:
04:06:45.686 [main] INFO  o.d.o.listeners.EvaluativeListener - ThresholdEvaluation:

... training continuous normally ...
```

**Comment by saudet** [comment]
Could you also provide a small code snippet to reproduce this? Thanks!
