### ISSUE TITLE
DL4J and Nd4j incompatibilities in 9.0.2-SNAPSHOT

### ISSUE THREAD

**Issue by nilsgumpfer** [deeplearning4j/deeplearning4j#4158]
#### Issue Description

Hey guys,
I´m trying to use the implemented Keras 2.0 stuff in current snapshot version. Seems there are some incompatibilities between dl4j and nd4j, though.

what I used in my pom:

`<properties>
        <deeplearning4j.version>0.9.2-SNAPSHOT</deeplearning4j.version>
        <nd4j.version>0.9.2-SNAPSHOT</nd4j.version>
        <datavec.version>0.9.2-SNAPSHOT</datavec.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-modelimport</artifactId>
            <version>${deeplearning4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.datavec</groupId>
            <artifactId>datavec-data-image</artifactId>
            <version>${datavec.version}</version>
        </dependency>

        

        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
    </dependencies>`

the error I receive:

`Exception in thread "main" java.lang.NoSuchMethodError: org.nd4j.linalg.learning.config.IUpdater.applySchedules(ID)V
	at org.deeplearning4j.nn.conf.layers.LayerValidation.updaterValidation(LayerValidation.java:85)
	at org.deeplearning4j.nn.conf.layers.LayerValidation.updaterValidation(LayerValidation.java:35)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.copyConfigToLayer(NeuralNetConfiguration.java:1378)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.configureLayer(NeuralNetConfiguration.java:1318)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.build(NeuralNetConfiguration.java:1301)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:304)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerConfiguration(KerasSequentialModel.java:199)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:219)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:209)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:238)`

#### Version Information

Win 7 x64
JDK 1.8.40 x64
deeplearning4 0.9.2-SNAPSHOT
nd4j 0.9.2-SNAPSHOT
datavec 0.9.2-SNAPSHOT

**Comment by maxpumperla** [comment]
@nilsgumpfer I changed the title of your issue, as it doesn't really have anything to do with keras import (afaict). 

It seems you need `IUpdater.applySchedules`, but don't have them in the snapshot. Not sure how this comes about, maybe the snapshots were built at different points in time.

@AlexDBlack  @raver119  do you know where this might come from?

**Comment by raver119** [comment]
It comes from broken snapshots.

пн, 9 окт. 2017 г. в 14:42, Max Pumperla <notifications@github.com>:

**Comment by maxpumperla** [comment]
ok. I thought that was fixed by now. then you have to build from source.

**Comment by nilsgumpfer** [comment]
What exactly is the Problem there? Is the automatic Build Buggy?

**Comment by DonaldAlan** [comment]
Looks like I'm hitting this issue too  on 0.9.2-SNAPSHOT, both with MultiLayerNetwork and ComputationGraph.

**Comment by AlexDBlack** [comment]
This was due to snapshots, not any problem with the library itself. Closing this.
