### ISSUE TITLE
spark-nlp Word2Vec assertion failed: copyAndReset must return a zero value copy

### ISSUE THREAD

**Issue by mirko1978** [deeplearning4j/deeplearning4j#4178]
#### Issue Description

Spark implementation of Word2Vec return with the follow exception:
```
Exception in thread "main" java.lang.AssertionError: assertion failed: copyAndReset must return a zero value copy
	at scala.Predef$.assert(Predef.scala:170)
	at org.apache.spark.util.AccumulatorV2.writeReplace(AccumulatorV2.scala:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteReplace(ObjectStreamClass.java:1118)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1136)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:43)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:295)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:288)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:108)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2287)
	at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:370)
	at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:369)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.map(RDD.scala:369)
	at org.apache.spark.api.java.JavaRDDLike$class.map(JavaRDDLike.scala:93)
	at org.apache.spark.api.java.AbstractJavaRDDLike.map(JavaRDDLike.scala:45)
	at org.deeplearning4j.spark.text.functions.TextPipeline.updateAndReturnAccumulatorVal(TextPipeline.java:115)
	at org.deeplearning4j.spark.text.functions.TextPipeline.buildVocabCache(TextPipeline.java:175)
	at org.deeplearning4j.spark.models.embeddings.word2vec.Word2Vec.train(Word2Vec.java:163)
	at com.ixxus.word2vec.W2VProgram$.delayedEndpoint$com$ixxus$word2vec$W2VProgram$1(W2VProgram.scala:17)
	at com.ixxus.word2vec.W2VProgram$delayedInit$body.apply(W2VProgram.scala:6)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.ixxus.word2vec.W2VProgram$.main(W2VProgram.scala:6)
	at com.ixxus.word2vec.W2VProgram.main(W2VProgram.scala)
```

My snipped to reproduce it:

```scala
import org.apache.spark.{SparkConf, SparkContext}
import org.deeplearning4j.spark.models.embeddings.word2vec.Word2Vec

object W2VProgram extends App {
    val sparkConf = new SparkConf().setAppName("Word2Vec")
    sparkConf.setMaster("local[*]")
        .set("spark.locality.wait", "0")
    val sc = new SparkContext(sparkConf)
    sc.setLogLevel("WARN")
    val sentences = sc.parallelize(Seq("one two thee four", "some once again", "one another sentence"))

    val model: Word2Vec = new Word2Vec.Builder()
        .workers(4)
        .build()
    model.train(sentences)
}
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.1_spark_2
* platform information: OSX
* Spark version: 2.2.0
* Scala version: 2.11.11

**Comment by elifaj** [comment]
I'm getting the same exception. Same version information on OSX and AWS EMR.

**Comment by elifaj** [comment]
Looks like we were using the wrong implementation. This looks like the correct one: org.deeplearning4j.spark.models.word2vec.SparkWord2Vec
