### ISSUE TITLE
BasicRNTNTest fails - "Array must be a vector"

### ISSUE THREAD

**Issue by olafhel** [deeplearning4j/deeplearning4j#419]
https://gist.github.com/olafhel/d10394a10826bc75df93

**Comment by EronWright** [comment]
The test still fails on rc0 with the same error.   

```
mvn test -Dtest=BasicRNTNTest
```
```
o.d.p.Parallelization - Error occurred processing data
java.lang.NullPointerException: null
	at org.deeplearning4j.models.rntn.RNTN.backpropDerivativesAndError(RNTN.java:715) ~[classes/:na]
	at org.deeplearning4j.models.rntn.RNTN.backpropDerivativesAndError(RNTN.java:759) ~[classes/:na]
	at org.deeplearning4j.models.rntn.RNTN.backpropDerivativesAndError(RNTN.java:759) ~[classes/:na]
	at org.deeplearning4j.models.rntn.RNTN.backpropDerivativesAndError(RNTN.java:653) ~[classes/:na]
	at org.deeplearning4j.models.rntn.RNTN.access$100(RNTN.java:83) ~[classes/:na]
o.d.m.rntn.RNTN - Error occurred training batch
java.lang.IllegalArgumentException: Array must be a vector
	at org.nd4j.linalg.util.LinAlgExceptions.assertVector(LinAlgExceptions.java:55) ~[nd4j-api-0.4-rc0.jar:na]
	at org.nd4j.linalg.factory.BaseBlasWrapper.scal(BaseBlasWrapper.java:111) ~[nd4j-api-0.4-rc0.jar:na]
	at org.deeplearning4j.models.rntn.RNTN.scaleAndRegularize(RNTN.java:582) ~[classes/:na]
	at org.deeplearning4j.models.rntn.RNTN.getValueGradient(RNTN.java:1050) ~[classes/:na]
	at org.deeplearning4j.models.rntn.RNTN$2.call(RNTN.java:436) ~[classes/:na]
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 60.337 sec <<< FAILURE! - in org.deeplearning4j.models.rntn.BasicRNTNTest
testGetValuesAndDerivativeLengths(org.deeplearning4j.models.rntn.BasicRNTNTest)  Time elapsed: 28.26 sec  <<< ERROR!
java.lang.IllegalArgumentException: Array must be a vector
	at org.nd4j.linalg.util.LinAlgExceptions.assertVector(LinAlgExceptions.java:55)
	at org.nd4j.linalg.factory.BaseBlasWrapper.scal(BaseBlasWrapper.java:111)
	at org.deeplearning4j.models.rntn.RNTN.scaleAndRegularize(RNTN.java:582)
	at org.deeplearning4j.models.rntn.RNTN.getValueGradient(RNTN.java:1050)
	at org.deeplearning4j.models.rntn.BasicRNTNTest.testGetValuesAndDerivativeLengths(BasicRNTNTest.java:109)

testRNTNEval(org.deeplearning4j.models.rntn.BasicRNTNTest)  Time elapsed: 32.075 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.deeplearning4j.eval.ConfusionMatrix.add(ConfusionMatrix.java:59)
	at org.deeplearning4j.eval.ConfusionMatrix.add(ConfusionMatrix.java:52)
	at org.deeplearning4j.models.rntn.RNTNEval.count(RNTNEval.java:70)
	at org.deeplearning4j.models.rntn.RNTNEval.count(RNTNEval.java:67)
	at org.deeplearning4j.models.rntn.RNTNEval.count(RNTNEval.java:67)
	at org.deeplearning4j.models.rntn.RNTNEval.eval(RNTNEval.java:54)
	at org.deeplearning4j.models.rntn.BasicRNTNTest.testRNTNEval(BasicRNTNTest.java:128)
```

**Comment by agibsonccc** [comment]
Not relevant anymore.
