### ISSUE TITLE
importKerasModelAndWeights - NoSuchMethodError

### ISSUE THREAD

**Issue by KeironO** [deeplearning4j/deeplearning4j#4193]
#### Issue Description

Currently experiencing a strange problem using the Keras converter on ```9.2.0-SNAPSHOT```.

```java
package Converter;


import org.deeplearning4j.nn.graph.ComputationGraph;
import org.deeplearning4j.nn.modelimport.keras.KerasModelImport;
import org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException;
import org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException;

import java.io.IOException;

public class App {
    public static void main( String[] args ) throws IOException, UnsupportedKerasConfigurationException, InvalidKerasConfigurationException {
        ComputationGraph model = KerasModelImport.importKerasModelAndWeights("/home/keo7/Projects/AgriDoctorAlpha/model/keras/vgg16.h5");
    }
}

```

Throws...

```
Exception in thread "main" java.lang.NoSuchMethodError: org.nd4j.linalg.learning.config.IUpdater.applySchedules(ID)V
	at org.deeplearning4j.nn.conf.layers.LayerValidation.updaterValidation(LayerValidation.java:85)
	at org.deeplearning4j.nn.conf.layers.LayerValidation.updaterValidation(LayerValidation.java:35)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.copyConfigToLayer(NeuralNetConfiguration.java:1378)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.configureLayer(NeuralNetConfiguration.java:1318)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.build(NeuralNetConfiguration.java:1301)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.addLayer(ComputationGraphConfiguration.java:652)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.addLayer(ComputationGraphConfiguration.java:636)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraphConfiguration(KerasModel.java:322)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:375)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:364)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:125)
```

#### Version Information
pom.xml:

```

    <dependencies>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>0.9.2-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>0.9.2-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-zoo</artifactId>
            <version>0.9.2-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-modelimport</artifactId>
            <version>0.9.2-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

```

**Comment by saudet** [comment]
It just sounds like one of your artifacts is out of date. Please try to reclone the repositories and build from source again.

**Comment by maxpumperla** [comment]
@KeironO sorry for the inconvenience, but our snapshot builds are unreliable right now. In your case I think nd4j and dl4j don't align. We run into this and similar other issues time and again.

I'll have to close this for now and ask you to please build from source:
https://deeplearning4j.org/buildinglocally
