### ISSUE TITLE
OutOfMemoryError: Physical memory usage is too high: physicalBytes = 3G > maxPhysicalBytes = 3G

### ISSUE THREAD

**Issue by bernard01** [deeplearning4j/deeplearning4j#4196]
I am using A genetic algorithm to set the weights of a network.

So far so good, but DL4J runs out of memory.

I have been doing this for a while with neuroph, without such problems, but it is too slow so I am hoping to get the speed out of DL4J. Please excuse my ignorance - I haven't had much DL4J experience yet.

The test case is adapted from a DL4J example.

It is uploaded at https://github.com/bernard01/RegressionSumDl4j

From what I have been reading in various papers, using a GA to set network weights is a popular research topic, and it is a valid approach at least for problems that are not differentiable, i.e. where gradient based back propagation does not work.

If you have any ideas that avoids the error with a different approach, that would be highly appreciated.
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.1
* platform information (OS, etc): Windows7, Java 1.8
* CPU, no CUDA, no NVIDIA
#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

In principle yes, but I don't want to waste your time teaching me the native aspects :)

Here is the stack trace, and attached test case, Maven project in zip file:

Exception in thread "main" java.lang.IllegalStateException: Fitness evaluation task execution failed.
	at org.uncommons.watchmaker.framework.AbstractEvolutionEngine.evaluatePopulation(AbstractEvolutionEngine.java:228)
	at org.uncommons.watchmaker.framework.GenerationalEvolutionEngine.nextEvolutionStep(GenerationalEvolutionEngine.java:130)
	at org.uncommons.watchmaker.framework.AbstractEvolutionEngine.evolvePopulation(AbstractEvolutionEngine.java:154)
	at org.uncommons.watchmaker.framework.AbstractEvolutionEngine.evolve(AbstractEvolutionEngine.java:93)
	at org.uncommons.watchmaker.framework.AbstractEvolutionEngine.evolve(AbstractEvolutionEngine.java:78)
	at bt.dl4j.regressionsum.RegressionSumOptimizer.optimizeWeights(RegressionSumOptimizer.java:57)
	at bt.dl4j.regressionsum.RegressionSumOptimizerTest.testOptimizeWeights(RegressionSumOptimizerTest.java:42)
	at bt.dl4j.regressionsum.RegressionSumOptimizerTest.main(RegressionSumOptimizerTest.java:46)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(1): totalBytes = 610M, physicalBytes = 3G
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.uncommons.watchmaker.framework.AbstractEvolutionEngine.evaluatePopulation(AbstractEvolutionEngine.java:223)
	... 7 more
Caused by: java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(1): totalBytes = 610M, physicalBytes = 3G
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:76)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:541)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:61)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:255)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1468)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:260)
	at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:122)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createUninitialized(CpuNDArrayFactory.java:267)
	at org.nd4j.linalg.factory.Nd4j.createUninitialized(Nd4j.java:5054)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.valueArrayOf(BaseNDArrayFactory.java:952)
	at org.nd4j.linalg.factory.Nd4j.valueArrayOf(Nd4j.java:5365)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:289)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.sum(BaseNDArray.java:3909)
	at org.deeplearning4j.eval.RegressionEvaluation.eval(RegressionEvaluation.java:196)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doEvaluation(MultiLayerNetwork.java:2899)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.evaluateRegression(MultiLayerNetwork.java:2832)
	at bt.dl4j.regressionsum.RegressionSumFitnessEvaluator.getFitness(RegressionSumFitnessEvaluator.java:111)
	at bt.dl4j.regressionsum.RegressionSumFitnessEvaluator.getFitness(RegressionSumFitnessEvaluator.java:24)
	at org.uncommons.watchmaker.framework.FitnessEvalutationTask.call(FitnessEvalutationTask.java:52)
	at org.uncommons.watchmaker.framework.FitnessEvalutationTask.call(FitnessEvalutationTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes = 3G > maxPhysicalBytes = 3G
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:576)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
	at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
	... 23 more

[RegressionSum.zip](https://github.com/deeplearning4j/deeplearning4j/files/1404826/RegressionSum.zip)

**Comment by agibsonccc** [comment]
https://deeplearning4j.org/memory
