### ISSUE TITLE
unsupported Keras Model 2d

### ISSUE THREAD

**Issue by MyraBaba** [deeplearning4j/deeplearning4j#4220]
I have below error 👍 

Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.UnsupportedKerasConfigurationException: Unsupported keras layer type Conv2D. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.KerasLayer.getKerasLayerFromConfig(KerasLayer.java:261)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.helperPrepareLayers(KerasModel.java:191)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:99)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:56)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.buildSequential(KerasModel.java:646)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:156)
	at MLPMnistTwoLayerExample$.main(MnistAccrTest.scala:90)
	at MLPMnistTwoLayerExample.main(MnistAccrTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by agibsonccc** [comment]
Your model is 2.0. I mentioned in the previous issue we would put that out next release. For now you have to build from source.

**Comment by ryan7th** [comment]
is the problem solved?  i came the same problem too~

**Comment by agibsonccc** [comment]
@ryan7th Use snapshots: http://deeplearning4j.org/snapshots - we'll be doing a release within a few weeks here.
