### ISSUE TITLE
RL4J A3C Zero length reward stack

### ISSUE THREAD

**Issue by mattbushell** [deeplearning4j/deeplearning4j#4228]
#### Issue Description

Whilst testing an impl of the MDP api I get an Exception
`
org.nd4j.linalg.exception.ND4JIllegalStateException: Invalid shape: Requested INDArray shape [1, 21, 0] contains dimension size values < 1 (all dimensions must be 1 or more)
    at org.nd4j.linalg.factory.Nd4j.checkShapeValues(Nd4j.java:5022)
    at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:5012)
    at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4114)
    at org.deeplearning4j.rl4j.learning.async.a3c.discrete.A3CThreadDiscrete.calcGradient(A3CThreadDiscrete.java:75)
    at org.deeplearning4j.rl4j.learning.async.a3c.discrete.A3CThreadDiscrete.calcGradient(A3CThreadDiscrete.java:28)
    at org.deeplearning4j.rl4j.learning.async.AsyncThreadDiscrete.trainSubEpoch(AsyncThreadDiscrete.java:123)
    at org.deeplearning4j.rl4j.learning.async.AsyncThread.run(AsyncThread.java:82)
`

The 21 number is the size of the ObservationSpace.

The bug i suspect is in AsyncThreadDiscrete.trainSubEpoch which can be 0 if there are no more allowed steps in the epoch but the Global is still running/not finshed training.

AsyncThreadDiscrete.trainSubEpoch:
`while (!getAsyncGlobal().isTrainingComplete() && getAsyncGlobal().isRunning()) {
                int maxSteps = Math.min(getConf().getNstep(), getConf().getMaxEpochStep() - length);
                SubEpochReturn<O> subEpochReturn = trainSubEpoch(obs, maxSteps);`

maxSteps and therefore Stack.size of rewards can be zero whilst Global thread is still running/incomplete when maxEpochSteps - length = 0

I will work on a simple test and attach if i come up with one that reproduces it.

#### Version Information

0.9.1
Win 10

**Comment by mattbushell** [comment]
Not a bug, client MDP code was not resetting from terminal state
