### ISSUE TITLE
NullPointerException in training word2vec on Spark Notebook

### ISSUE THREAD

**Issue by jarutis** [deeplearning4j/deeplearning4j#425]
I get a npe then running 

```scala
val vec = new Word2Vec()
val table = vec.train(feedback)
```

feedback is just an rdd of sentences

and the settings are as follows:

```
SparkDl4jMultiLayer.AVERAGE_EACH_ITERATION=false
Word2VecPerformer.NEGATIVE=0
Word2VecPerformer.VECTOR_LENGTH=300
spark.akka.frameSize=100
```

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 4.0 failed 4 times, most recent failure: Lost task 3.3 in stage 4.0 (TID 28, hz-bd-hdp29): java.lang.NullPointerException
	at org.deeplearning4j.spark.models.embeddings.word2vec.SentenceBatch.iterateSample(SentenceBatch.java:171)
	at org.deeplearning4j.spark.models.embeddings.word2vec.SentenceBatch.skipGram(SentenceBatch.java:97)
	at org.deeplearning4j.spark.models.embeddings.word2vec.SentenceBatch.trainSentence(SentenceBatch.java:71)
	at org.deeplearning4j.spark.models.embeddings.word2vec.SentenceBatch.call(SentenceBatch.java:55)
	at org.deeplearning4j.spark.models.embeddings.word2vec.SentenceBatch.call(SentenceBatch.java:42)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1.apply(JavaPairRDD.scala:1027)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:870)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:870)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
	at org.apache.spark.scheduler.Task.run(Task.scala:70)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by agibsonccc** [comment]
So this is gone now?

**Comment by jarutis** [comment]
I updated to latest master, but, at least in that notebook file it is still here.

**Comment by agibsonccc** [comment]
So we ran this with spark submit with no problems. Wood be curious what a
NON notebook environment would look like. I'll talk to the spark notebook
guys in the meantime.

**Comment by jarutis** [comment]
I'll try with spark submit as well.

**Comment by jarutis** [comment]
Yes, Spark submit on my laptop works fine :+1: . I'll try running spark submit on yarn cluster later.

**Comment by jarutis** [comment]
Spark submit works on yarn as well. So this seems to be related to spark notebook specifically.

**Comment by agibsonccc** [comment]
Thanks for confirming.
ᐧ

**Comment by EronWright** [comment]
It appears that the NPE occurs when the `org.deeplearning4j.scaleout.perform.models.word2vec.negative` configuration setting is != 0.   In that case, the fateful line 171 is executed, yielding a NPE on a null `table` reference.  No surprise - the `table` field is never set by Word2Vec (see [L133](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark-nlp/src/main/java/org/deeplearning4j/spark/models/embeddings/word2vec/Word2Vec.java#L133)).

The Word2Vec unit test sets `negative` to zero, so we're lacking coverage of negative sampling.

@jarutis was the `negative` conf setting set in any of your experiments?

**Comment by jarutis** [comment]
I haven't used the setting anywhere. But if I set it explicitly to 0 in spark conf everything works fine as you said!

**Comment by agibsonccc** [comment]
Will work on a fix for this. Thanks eron.

**Comment by agibsonccc** [comment]
I've set negative to zero for now.
