### ISSUE TITLE
CUBLAS_STATUS_INTERNAL_ERROR when running ml.JavaIrisClassification example

### ISSUE THREAD

**Issue by mikeorzel2** [deeplearning4j/deeplearning4j#429]
Hi,

I am currently getting an error while trying to run the ml.JavaIrisClassification example against a GPU.

Stack trace of error is below
```
15/07/12 09:42:44 INFO MultiLayerNetwork: Training on layer 1 with 181 examples
15/07/12 09:42:44 ERROR Executor: Exception in task 0.0 in stage 6.0 (TID 6)
jcuda.CudaException: CUBLAS_STATUS_INTERNAL_ERROR
	at jcuda.jcublas.JCublas2.checkResult(JCublas2.java:127)
	at jcuda.jcublas.JCublas2.cublasSdot(JCublas2.java:642)
	at org.nd4j.linalg.jcublas.blas.JcublasLevel1.sdot(JcublasLevel1.java:42)
	at org.nd4j.linalg.api.blas.impl.BaseLevel1.dot(BaseLevel1.java:32)
	at org.nd4j.linalg.factory.BaseBlasWrapper.dot(BaseBlasWrapper.java:185)
	at org.deeplearning4j.optimize.solvers.BackTrackLineSearch.optimize(BackTrackLineSearch.java:152)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:173)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:444)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.fit(RBM.java:399)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:216)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1242)
	at org.deeplearning4j.spark.ml.classification.NeuralNetworkClassification$$anonfun$1.apply(MultiLayerNetworkClassification.scala:121)
	at org.deeplearning4j.spark.ml.classification.NeuralNetworkClassification$$anonfun$1.apply(MultiLayerNetworkClassification.scala:108)
	at org.deeplearning4j.spark.ml.nn.ParameterAveragingTrainingStrategy$$anonfun$train$1$$anonfun$apply$mcVI$sp$1.apply(TrainingStrategy.scala:89)
	at org.deeplearning4j.spark.ml.nn.ParameterAveragingTrainingStrategy$$anonfun$train$1$$anonfun$apply$mcVI$sp$1.apply(TrainingStrategy.scala:81)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:878)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:878)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
	at org.apache.spark.scheduler.Task.run(Task.scala:70)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
I have run the nd4j test cases and they pass for jcublas-7.0

Environment is a single node, Titan X GPU, cuda 7.0.28 nvidia 346.46 drivers running in a docker container with the following params
```
docker run -it --privileged=true --device=/dev/nvidia0:/dev/nvidia0 --device=/dev/nvidia1:/dev/nvidia1 --device=/dev/nvidiactl:/dev/nvidiactl --device=/dev/nvidia-uvm:/dev/nvidia-uvm deeplearning4j bash
```
The container is based on ubuntu14.04 and includes all the items for deeplearning4j with it running fine against cpu and jblas.

**Comment by agibsonccc** [comment]
I'm not sure about the stuff with docker. I'm not going to support this (and by that I mean troubleshoot it) with docker atm.

**Comment by EronWright** [comment]
@mikeorzel2 I think some devices and capabilities need to be shared with the container.    I'm keen to figure it out and will update this thread when I have something.

**Comment by EronWright** [comment]
@mikeorzel2 I think you're on the right track with the devices and caps.   I will investigate this but please update this thread if you find a solution.

**Comment by mikeorzel2** [comment]
Thanks, I am going to run a cuda deviceQuery tonight just to confirm the cuda part is relatively happy. Are there any other "shakeout" tests that anyone is aware of that might help confirm all is well other than the nd4j tests I have already run.

Thanks

Mike

**Comment by mikeorzel2** [comment]
Tested deviceQuery and works fine.

./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "Graphics Device"
  CUDA Driver Version / Runtime Version          7.0 / 7.0
  CUDA Capability Major/Minor version number:    5.2
  Total amount of global memory:                 12288 MBytes (12884705280 bytes)
  (24) Multiprocessors, (128) CUDA Cores/MP:     3072 CUDA Cores
  GPU Max Clock rate:                            1088 MHz (1.09 GHz)
  Memory Clock rate:                             3505 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 3145728 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 2 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 7.0, CUDA Runtime Version = 7.0, NumDevs = 1, Device0 = Graphics Device
Result = PASS

**Comment by agibsonccc** [comment]
In the container? We ultimately call the same libs via jni.

**Comment by mikeorzel2** [comment]
Correct, in the container. Also ran bandwidthTest

[CUDA Bandwidth Test] - Starting...
Running on...

 Device 0: Graphics Device
 Quick Mode

 Host to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)	Bandwidth(MB/s)
   33554432			5997.2

 Device to Host Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)	Bandwidth(MB/s)
   33554432			6549.8

 Device to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)	Bandwidth(MB/s)
   33554432			241509.4

Result = PASS

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.

**Comment by mikeorzel2** [comment]
root@cf254cffbc0b:/usr/local/cuda-7.0/samples/7_CUDALibraries/simpleCUBLAS# ./simpleCUBLAS 
GPU Device 0: "Graphics Device" with compute capability 5.2

simpleCUBLAS test running..
simpleCUBLAS test passed.

**Comment by mikeorzel2** [comment]
simpleDevLibCUBLAS test running...
GPU Device 0: "Graphics Device" with compute capability 5.2

Host and device APIs will be tested.
simpleDevLibCUBLAS completed, returned OK

**Comment by mikeorzel2** [comment]
Assuming Cuda is running based on that, is there a higher level test I can run that tests java calling these libraries?

**Comment by agibsonccc** [comment]
Try to play around with jcuda.org directly
We may have to report this upstream

**Comment by mikeorzel2** [comment]
Cool, will give that one a try tommorow evening and let you know. Thanks

**Comment by mikeorzel2** [comment]
Hi Guys, bit more information, JCuda works successfully

root@cf254cffbc0b:/src/JCuda-All-0.7.0a-bin-linux-x86_64# java -cp ".:jcuda-0.7.0a.jar:jcublas-0.7.0a.jar" JCublas2PointerModes
Host call duration: 0.48193 ms
Result: 1000000.0
Device call duration: 0.035952 ms
Device full duration: 0.067223 ms
Result: 1000000.0

This calls the same cublassdot kernel that is failing in the original call. This is within the same container. Example still fails with same message.

**Comment by mikeorzel2** [comment]
Is there a way i can run the nd4j blas level1 tests against cuda easily?

**Comment by mikeorzel2** [comment]
nd4j tests via maven seem to run successfully

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running jcuda.jcublas.context.ContextHolderTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.728 sec
Running jcuda.jcublas.fft.JCudaFftTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.512 sec
Running jcuda.jcublas.kernel.TestMatrixOperations
Running on 1
MMUL took 231
MMUL took 217
MMUL took 236
MMUL took 239
MMUL took 253
MMUL took 268
MMUL took 286
MMUL took 295
MMUL took 301
MMUL took 310
MMUL took 64
MMUL took 65
MMUL took 70
MMUL took 85
MMUL took 64
MMUL took 61
MMUL took 120
MMUL took 60
MMUL took 83
MMUL took 108
MMUL took 90
MMUL took 99
MMUL took 103
MMUL took 84
MMUL took 82
MMUL took 68
MMUL took 144
MMUL took 149
MMUL took 89
MMUL took 68
MMUL took 72
MMUL took 66
MMUL took 92
MMUL took 64
MMUL took 68
MMUL took 77
MMUL took 82
MMUL took 71
MMUL took 65
MMUL took 86
MMUL took 63
MMUL took 128
MMUL took 130
MMUL took 96
MMUL took 66
MMUL took 67
MMUL took 129
MMUL took 69
MMUL took 78
MMUL took 87
MMUL took 62
MMUL took 69
MMUL took 75
MMUL took 90
MMUL took 65
MMUL took 66
MMUL took 63
MMUL took 126
MMUL took 104
MMUL took 130
MMUL took 63
MMUL took 65
MMUL took 103
MMUL took 60
MMUL took 69
MMUL took 72
MMUL took 66
MMUL took 77
MMUL took 66
MMUL took 70
MMUL took 98
MMUL took 111
MMUL took 71
MMUL took 130
MMUL took 165
MMUL took 78
MMUL took 96
MMUL took 73
MMUL took 99
MMUL took 95
MMUL took 89
MMUL took 66
MMUL took 82
MMUL took 69
MMUL took 63
MMUL took 116
MMUL took 122
MMUL took 108
MMUL took 115
MMUL took 59
MMUL took 60
MMUL took 65
MMUL took 42
MMUL took 61
MMUL took 63
MMUL took 40
MMUL took 65
MMUL took 39
MMUL took 62
MMUL took 59
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.301 sec

Results :

Tests run: 7, Failures: 0, Errors: 0, Skipped: 0

**Comment by mikeorzel2** [comment]
Running 

root@cf254cffbc0b:/src/dl4j-0.0.3.3-examples# java -cp target/deeplearning4j-examples-0.0.3.3.3-SNAPSHOT.jar org.deeplearning4j.multilayer.MLPBackpropIrisExample

Gives this output

.....
o.d.m.MLPBackpropIrisExample - Load data....
o.d.m.MLPBackpropIrisExample - Build model....
o.d.m.MLPBackpropIrisExample - Train model....
Exception in thread "main" java.lang.RuntimeException: Could not execute kernel
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.invoke(JCudaExecutioner.java:324)
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.exec(JCudaExecutioner.java:73)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2756)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2736)
	at org.deeplearning4j.optimize.GradientAdjustment.updateGradientAccordingToParams(GradientAdjustment.java:92)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doBackWard(MultiLayerNetwork.java:1102)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1247)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1275)
	at org.deeplearning4j.multilayer.MLPBackpropIrisExample.main(MLPBackpropIrisExample.java:95)
Caused by: java.lang.UnsupportedOperationException
	at org.nd4j.linalg.api.ndarray.LinearViewNDArray.data(LinearViewNDArray.java:154)
	at org.nd4j.linalg.jcublas.CublasPointer.<init>(CublasPointer.java:135)
	at org.nd4j.linalg.jcublas.util.KernelParamsWrapper.<init>(KernelParamsWrapper.java:148)
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.invoke(JCudaExecutioner.java:321)
	... 8 more

**Comment by agibsonccc** [comment]
Not seeing this anymore. Closing

**Comment by mikeorzel2** [comment]
Thanks Adam, works now, getting some strange results gpu vs cpu but will chase that up. Appreciate the help.

**Comment by agibsonccc** [comment]
Try c vs fortran ordering. In the interest of speed we should switch over
to c ordering (faster element wise operations)
ᐧ

**Comment by agibsonccc** [comment]
@mikeorzel2 Could you open another issue with what you're seeing? It'd be great to get a test case. I'd just run thing side by side and see what you get.
