### ISSUE TITLE
Unable to guess input file format.

### ISSUE THREAD

**Issue by TamouzeAssi** [deeplearning4j/deeplearning4j#4293]
Hello,

Any help on how to solve this issue:

    vec = WordVectorSerializer.readWord2VecModel(gModel)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2480)
        at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2266)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
java.lang.RuntimeException: java.lang.RuntimeException: Unable to guess input file format. Please use corresponding loader directly

Thank you

**Comment by agibsonccc** [comment]
@TamouzeAssi we would need more info. Post your word2vec file and a full stack trace please.

**Comment by TamouzeAssi** [comment]
Sir @agibsonccc,

my simple code is (in jython): 

from org.deeplearning4j.models.embeddings.loader import WordVectorSerializer
  
 gModel = File("/gs/project/tws-462-aa/model.bin")

 vec = WordVectorSerializer.readWord2VecModel(gModel)
 weightLookupTable = vec.lookupTable()
 vectors = weightLookupTable.vectors()
 wordVectorMatrix = vec.getWordVectorMatrix("dir")
 wordVectorMatrix1 = vec.getWordVectorMatrix("director")
wordVector = vec.getWordVector("man")
  ##print wordVector
wordVector1 = vec.getWordVector("director")
print wordVector1
from org.nd4j.linalg.ops.transforms.Transforms import cosineSim
from org.nd4j.linalg.api.ndarray.INDArray import addi
cosSim = cosineSim(wordVectorMatrix, wordVectorMatrix1)
print cosSim
  ##output: 0.7704452276229858

**Comment by raver119** [comment]
> Unable to guess input file format. Please use corresponding loader directly

If you're sure that file is accessible via that path, and it has proper format - just use appropriate loader directly.

**Comment by AlexDBlack** [comment]
Closing this due to lack of activity. @TamouzeAssi if there are still issues, post here and we can re-open.
