### ISSUE TITLE
ModelGuesser: can't load Keras models from streams

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4309]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/util/ModelGuesser.java#L158

Simple fix is just to export the stream contents to a file first.

```
04:15:21,837 INFO  ~ java.lang.UnsupportedOperationException: Reading HDF5 files from InputStreams currently unsupported.
04:15:21,837 INFO  ~ 	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:89)
04:15:21,837 INFO  ~ 	at org.deeplearning4j.util.ModelGuesser.loadModelGuess(ModelGuesser.java:177)
```

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4310
