### ISSUE TITLE
Error when building for Android: couldn't find "libjnind4jcpu.so"

### ISSUE THREAD

**Issue by xumengwei** [deeplearning4j/deeplearning4j#4312]
Error message:
```
                                                                      --------- beginning of crash
11-17 01:08:39.067 14562-15101/edu.pku.sei.dlframeworks E/AndroidRuntime: FATAL EXCEPTION: Thread-1361
                                                                          Process: edu.pku.sei.dlframeworks, PID: 14562
                                                                          java.lang.ExceptionInInitializerError
                                                                              at org.nd4j.nativeblas.NativeOpsHolder.getInstance(NativeOpsHolder.java:58)
                                                                              at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:43)
                                                                              at java.lang.Class.newInstance(Native Method)
                                                                              at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5784)
                                                                              at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5694)
                                                                              at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:184)
                                                                              at org.nd4j.linalg.factory.Nd4j.getRandom(Nd4j.java:507)
                                                                              at org.deeplearning4j.nn.conf.MultiLayerConfiguration$Builder.build(MultiLayerConfiguration.java:496)
                                                                              at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:274)
                                                                              at edu.pku.sei.dlframeworks.frameworks.DL4J_fmk.test_createAndUseNetwork(DL4J_fmk.java:54)
                                                                              at edu.pku.sei.dlframeworks.MainActivity.run_DL4J(MainActivity.java:62)
                                                                              at edu.pku.sei.dlframeworks.MainActivity.access$300(MainActivity.java:17)
                                                                              at edu.pku.sei.dlframeworks.MainActivity$1.run(MainActivity.java:46)
                                                                              at java.lang.Thread.run(Thread.java:818)
                                                                           Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
                                                                              at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
                                                                              at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
                                                                              at org.nd4j.nativeblas.NativeOpsHolder.getInstance(NativeOpsHolder.java:58) 
                                                                              at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:43) 
                                                                              at java.lang.Class.newInstance(Native Method) 
                                                                              at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5784) 
                                                                              at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5694) 
                                                                              at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:184) 
                                                                              at org.nd4j.linalg.factory.Nd4j.getRandom(Nd4j.java:507) 
                                                                              at org.deeplearning4j.nn.conf.MultiLayerConfiguration$Builder.build(MultiLayerConfiguration.java:496) 
                                                                              at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:274) 
                                                                              at edu.pku.sei.dlframeworks.frameworks.DL4J_fmk.test_createAndUseNetwork(DL4J_fmk.java:54) 
                                                                              at edu.pku.sei.dlframeworks.MainActivity.run_DL4J(MainActivity.java:62) 
                                                                              at edu.pku.sei.dlframeworks.MainActivity.access$300(MainActivity.java:17) 
                                                                              at edu.pku.sei.dlframeworks.MainActivity$1.run(MainActivity.java:46) 
                                                                              at java.lang.Thread.run(Thread.java:818) 
                                                                           Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/edu.pku.sei.dlframeworks-2/base.apk", zip file "/data/app/edu.pku.sei.dlframeworks-2/split_lib_dependencies_apk.apk", zip file "/data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_0_apk.apk", zip file "/data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_1_apk.apk", zip file "/data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_2_apk.apk", zip file "/data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_3_apk.apk", zip file "/data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_4_apk.apk", zip file "/data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_5_apk.apk", zip file "/data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_6_apk.apk", zip file "/data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_7_apk.apk", zip file "/data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_8_apk.apk", zip file "/data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/edu.pku.sei.dlframeworks-2/lib/arm, /data/app/edu.pku.sei.dlframeworks-2/base.apk!/lib/armeabi-v7a, /data/app/edu.pku.sei.dlframeworks-2/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/edu.pku.sei.dlframeworks-2/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libjnind4jcpu.so"
                                                                              at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                              at java.lang.System.loadLibrary(System.java:1076)
                                                                              at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:963)
                                                                              at org.bytedeco.javacpp.Loader.load(Loader.java:764)
                                                                              at org.bytedeco.javacpp.Loader.load(Loader.java:671)
                                                                              at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10)
                                                                              at java.lang.Class.classForName(Native Method)
                                                                              at java.lang.Class.forName(Class.java:324)
                                                                              at org.bytedeco.javacpp.Loader.load(Loader.java:726)
                                                                              at org.bytedeco.javacpp.Loader.load(Loader.java:671)
                                                                          	at org.nd4j.nativebla
                                                                          
                                                                          --------- beginning of system
```

My gradle file:
```apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.3"
    defaultConfig {
        applicationId "edu.pku.sei.dlframeworks"
        minSdkVersion 21
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            // Specifies the ABI configurations of your native
            // libraries Gradle should build and package with your APK.
            abiFilters 'armeabi-v7a'
        }
        externalNativeBuild {
            cmake {
                cppFlags "-frtti -fexceptions"
                arguments "-DANDROID_TOOLCHAIN=gcc"
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }

    // For DL4J: https://deeplearning4j.org/android#configuring-your-android-studio-project
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/INDEX.LIST'

        exclude 'org/bytedeco/javacpp/windows-x86/msvcp120.dll'
        exclude 'org/bytedeco/javacpp/windows-x86_64/msvcp120.dll'
        exclude 'org/bytedeco/javacpp/windows-x86/msvcr120.dll'
        exclude 'org/bytedeco/javacpp/windows-x86_64/msvcr120.dll'

//        pickFirst 'org/bytedeco/javacpp/windows-x86/msvcp120.dll'
//        pickFirst 'org/bytedeco/javacpp/windows-x86_64/msvcp120.dll'
//        pickFirst 'org/bytedeco/javacpp/windows-x86/msvcr120.dll'
//        pickFirst 'org/bytedeco/javacpp/windows-x86_64/msvcr120.dll'
    }
}

configurations.all {
    resolutionStrategy {
        force 'junit:junit:4.12'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
//    testCompile 'junit:junit:4.12'

    // For DL4J
    compile 'org.deeplearning4j:deeplearning4j-core:0.8.0'
    compile 'org.nd4j:nd4j-native:0.8.0'
//    compile 'org.nd4j:nd4j-native:0.8.0:android-x86'
    compile 'org.nd4j:nd4j-native:0.8.0:android-arm'
//    compile 'org.bytedeco.javacpp-presets:openblas:0.2.19-1.3:android-x86'
    compile 'org.bytedeco.javacpp-presets:openblas:0.2.19-1.3:android-arm'
}
```

I've seen some other guys encountering into the same problem but their solutions seem cannot work on my side. Is there anybody can help?

**Comment by agibsonccc** [comment]
Please use the latest release.

**Comment by xumengwei** [comment]
@agibsonccc Hi I followed the instruction and use version 0.8.0. Is there a newer one?

**Comment by xumengwei** [comment]
@agibsonccc I just tried 0.9.1 and the error remains the same.
