### ISSUE TITLE
an exception when using SequenceRecordReaderDataSetIterator

### ISSUE THREAD

**Issue by cqiaoYc** [deeplearning4j/deeplearning4j#4324]
#### Issue Description
There is only one feature. Each one series one file. The lenghts of series are not same.
An exception was shown when using SequenceRecordReaderDataSetIterator. The code is attached.

![qq 20171122195412](https://user-images.githubusercontent.com/29296200/33155823-cf1c2b6a-d02e-11e7-9fa0-8aa3a12ea5c7.png)

* Deeplearning4j version 0.9.1
[TestModelWithCsvReader.zip](https://github.com/deeplearning4j/deeplearning4j/files/1497843/TestModelWithCsvReader.zip)

**Comment by AlexDBlack** [comment]
I am not able to reproduce this with your code.
If I use the code as-is, I obtain this:
```
Exception in thread "main" java.lang.UnsupportedOperationException: Alignment mode is set to EQUAL_LENGTH but variable length data was encountered. Use AlignmentMode.ALIGN_START or AlignmentMode.ALIGN_END with variable length data
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritablesSequence(RecordReaderMultiDataSetIterator.java:495)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:276)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:234)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:177)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:330)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:309)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:32)
	at org.deeplearning4j.examples.debug4324.TestModelWithCsvReader.train(TestModelWithCsvReader.java:109)
	at org.deeplearning4j.examples.debug4324.TestModelWithCsvReader.main(TestModelWithCsvReader.java:53)
```

If I modify the code to use ```SequenceRecordReaderDataSetIterator.AlignmentMode.ALIGN_START``` in the SequenceRecordReaderDataSetIterator constructor, the code runs without issue (no errors/exceptions).

```
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 8
o.n.n.Nd4jBlas - Number of threads used for BLAS: 8
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [7.1GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: NONE; inference: SEPARATE]
o.d.u.p.PlayUIServer - DL4J UI Server started at http://localhost:9000
o.d.u.p.PlayUIServer - StatsStorage instance attached to UI: InMemoryStatsStorage(uid=b203e4da)
No.0 nEpochs start.
No.1 nEpochs start.

Process finished with exit code 0
```

**Comment by cqiaoYc** [comment]
@AlexDBlack Thank you. My DataSetIterator works fine now and We needn't to spend more time on this problem.
