### ISSUE TITLE
importSequentialModelConfigFromFile : Cannot calculate gradient and score with respect to labels: final layer is not an IOutputLayer

### ISSUE THREAD

**Issue by rainforc** [deeplearning4j/deeplearning4j#4325]
Loading a saved keras model, and attempting to train
I used keras 1.2 and dl4j 0.9.1.
If i just use model.output is ok, but model.fit got this error!
```
o.d.n.m.k.KerasSequentialModel - Model cannot be trained: output layer dense_2 is not an IOutputLayer (no loss function specified)
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: NONE; inference: SEPARATE]
o.d.e.t.ImportKerasIrisModel - *****TRAIN MODEL********
o.d.n.m.MultiLayerNetwork - Warning: final layer isn't output layer. You cannot use backprop without an output layer.
Exception in thread "main" org.deeplearning4j.exception.DL4JException: Cannot calculate gradient and score with respect to labels: final layer is not an IOutputLayer
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2242)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:174)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:60)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:53)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1245)
	at org.deeplearning4j.examples.test.ImportKerasIrisModel.main(ImportKerasIrisModel.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
The dl4j code to load and train model:
https://gist.github.com/rainforc/45785ab4db205ac168e140b3ea38d1a8
the python code:
https://gist.github.com/rainforc/9a3b504fc8e36e2146b26c7da2d87c69
The JSON written:
https://gist.github.com/rainforc/878649dba386e54c07dc75675df7d647

**Comment by saudet** [comment]
It might be easier simply to add an output layer than to try to import it from Keras:
https://deeplearning4j.org/transfer-learning

**Comment by rainforc** [comment]
ok, i will try it.
