### ISSUE TITLE
JsonMappingException  when ModelSerializer.writeModel()

### ISSUE THREAD

**Issue by kepricon** [deeplearning4j/deeplearning4j#4334]
#### Issue Description

Recently, I got a JsonMappingException when writing a model via `ModelSerializerModelSerializer.writeModel()`

Below is an example of this issue
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/util/ModelGuesserTest.java#L75

```
java.lang.RuntimeException: org.nd4j.shade.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.deeplearning4j.nn.conf.MultiLayerConfiguration["confs"]->java.util.ArrayList[2]->org.deeplearning4j.nn.conf.NeuralNetConfiguration["layer"]->org.deeplearning4j.nn.conf.layers.OutputLayer["lossFn"]->org.nd4j.linalg.lossfunctions.impl.LossMSE["outputVertexIds"])

	at org.deeplearning4j.nn.conf.MultiLayerConfiguration.toJson(MultiLayerConfiguration.java:128)
	at org.deeplearning4j.util.ModelSerializer.writeModel(ModelSerializer.java:86)
	at org.deeplearning4j.util.ModelSerializer.writeModel(ModelSerializer.java:54)
	at org.deeplearning4j.util.ModelGuesserTest.testLoadNormalizers(ModelGuesserTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.nd4j.shade.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.deeplearning4j.nn.conf.MultiLayerConfiguration["confs"]->java.util.ArrayList[2]->org.deeplearning4j.nn.conf.NeuralNetConfiguration["layer"]->org.deeplearning4j.nn.conf.layers.OutputLayer["lossFn"]->org.nd4j.linalg.lossfunctions.impl.LossMSE["outputVertexIds"])
	at org.nd4j.shade.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at org.nd4j.shade.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at org.nd4j.shade.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:190)
	at org.nd4j.shade.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:671)
	at org.nd4j.shade.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:549)
	at org.nd4j.shade.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:577)
	at org.nd4j.shade.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:663)
	at org.nd4j.shade.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:549)
	at org.nd4j.shade.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:577)
	at org.nd4j.shade.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:663)
	at org.nd4j.shade.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:156)
	at org.nd4j.shade.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:113)
	at org.nd4j.shade.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:73)
	at org.nd4j.shade.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:19)
	at org.nd4j.shade.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:575)
	at org.nd4j.shade.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:663)
	at org.nd4j.shade.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:156)
	at org.nd4j.shade.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
	at org.nd4j.shade.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3385)
	at org.nd4j.shade.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2779)
	at org.deeplearning4j.nn.conf.MultiLayerConfiguration.toJson(MultiLayerConfiguration.java:126)
	... 25 more
Caused by: java.lang.NullPointerException
	at org.nd4j.autodiff.functions.DifferentialFunction.getVertices(DifferentialFunction.java:190)
	at org.nd4j.autodiff.functions.DifferentialFunction.getOutputVertexIds(DifferentialFunction.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.nd4j.shade.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:536)
	at org.nd4j.shade.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:663)
	... 42 more
```

**Comment by AlexDBlack** [comment]
I'm seeing ModelGuesserTest pass with latest ND4J master. Are you sure you are up to date there?
There was a known issue with JSON + loss functions fixed some days ago

**Comment by kepricon** [comment]
I also saw ModelGuesserTest pass
