### ISSUE TITLE
InputStream used twice, causing a NoSuchElementException

### ISSUE THREAD

**Issue by johanvos** [deeplearning4j/deeplearning4j#4339]
In case data is contained in an InputStream, the following snippet fails:
```
InputStream dataFile = this.getClass().getResourceAsStream("/mydata.csv");
RecordReader recordReader = new CSVRecordReader(0, ",");
recordReader.initialize(new InputStreamInputSplit(dataFile));
DataSetIterator iterator = new RecordReaderDataSetIterator(recordReader, batchSize, labelIndex, numClasses);
DataSet allData = iterator.next();
```

The exception is the following:
```
Exception in thread "Thread-3" java.util.NoSuchElementException: No next elements
        at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:116)
        at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:320)
        at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:409)
        at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:51)
        at com.gluonhq.dlearning.DataRetrievalService.getData(DataRetrievalService.java:92)

```

Looking into the code, it seems the `InputStream` is consumed twice, by 2 different iterators. As a result, the second iterator will return false in its `hasNext()` method.

The first iterator is created in 
`recordReader.initialize(new InputStreamInputSplit(dataFile));
`
The initialize method will set the InputStreamInputSplit, but also create the iterator. I don't see a method on recordReader that sets the InputStreamInputSplit but doesn't initialize the iterator.

Next, the second iterator is created around the same InputStream in `org.datavec.api.records.reader.impl.LineRecordReader` 
when the next method is called:
`
iter = IOUtils.lineIterator(new InputStreamReader(locations[splitIndex].toURL().openStream()));`

**Comment by AlexDBlack** [comment]
Fixed here, will be merged soon: https://github.com/deeplearning4j/deeplearning4j/pull/4345
