### ISSUE TITLE
Some features does not work on Java9

### ISSUE THREAD

**Issue by xvolks** [deeplearning4j/deeplearning4j#4392]
#### Issue Description

Please describe our issue, along with:
- expected behavior
Should run without issue
- encountered behavior
Code throw an Exception
Exception in thread "main" java.lang.NoClassDefFoundError: sun/reflect/ConstantPool
	at net.jodah.typetools.TypeResolver.populateLambdaArgs(TypeResolver.java:308)
	at net.jodah.typetools.TypeResolver.getTypeVariableMap(TypeResolver.java:254)
	at net.jodah.typetools.TypeResolver.resolveRawArguments(TypeResolver.java:162)
	at play.routing.RoutingDsl.with(RoutingDsl.java:182)
	at play.routing.RoutingDsl.access$000(RoutingDsl.java:66)
	at play.routing.RoutingDsl$PathPatternMatcher.build(RoutingDsl.java:362)
	at play.routing.RoutingDsl$PathPatternMatcher.routeTo(RoutingDsl.java:298)
	at org.deeplearning4j.ui.play.PlayUIServer.runMain(PlayUIServer.java:121)
	at org.deeplearning4j.ui.api.UIServer.getInstance(UIServer.java:27)
	at com.xvolks.nn.cniDigits.TrainerKt.statsStorage(Trainer.kt:125)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version : 
0.9.1
* platform information (OS, etc): 
macOS 10.13.2
* CUDA version, if used 
NONE
* NVIDIA driver version, if in use 
NONE
* Java 9.0.1

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!
The issue is here in dependent library, seems fixed one year ago:
https://github.com/jhalterman/typetools/issues/34

**Comment by raver119** [comment]
Sorry to say that, but Java 9 isn't really supported yet.

Please install Java 8.

**Comment by xvolks** [comment]
OK, back to Java 8.
