### ISSUE TITLE
Pooling layers broken

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#4409]
#### Issue Description

All tests related to Pooling2D seem to be broken on master, error message pretty much all look like this:

```
java.lang.NullPointerException
	at org.nd4j.autodiff.functions.DifferentialFunction.<init>(DifferentialFunction.java:127)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.<init>(DynamicCustomOp.java:100)
	at org.nd4j.linalg.api.ops.impl.layers.convolution.Pooling2D.<init>(Pooling2D.java:41)
	at org.nd4j.linalg.api.ops.impl.layers.convolution.Pooling2D$Pooling2DBuilder.build(Pooling2D.java:38)
	at org.nd4j.linalg.convolution.Convolution.pooling2D(Convolution.java:266)
	at org.deeplearning4j.nn.layers.convolution.subsampling.SubsamplingLayer.activate(SubsamplingLayer.java:314)
	at org.deeplearning4j.nn.layers.AbstractLayer.activate(AbstractLayer.java:290)
	at org.deeplearning4j.nn.layers.convolution.SubsamplingLayerTest.testSubSampleMaxActivate(SubsamplingLayerTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/2378

**Comment by kavinwang** [comment]
not fixed yet ? !

**Comment by agibsonccc** [comment]
@kavinwang what are you talking about? I closed the issue. What more do you want exactly? This likely isn't even relevant to you. You probably aren't even using master. Also, if you comment like this again, I will just forbid you from interacting with the repos. Please be professional when commenting.
