### ISSUE TITLE
Exception raised at importSequentialModel

### ISSUE THREAD

**Issue by twmattyoung** [deeplearning4j/deeplearning4j#4413]
#### Issue Description

Please describe our issue, along with:
- Start using 0.9.2-SNAPSHOT because 0.9.1 doesn't support Embedding Layer but when use org.deeplearning4j.nn.modelimport.keras.Model.importSequentialModel("fromPy.json", "fromPy.h5"), enoucnter the following error. It seems still relates to Embedding.
- HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: H5A.c line 436 in H5Aopen(): unable to load attribute info from object header for attribute: 'weight_names'
    major: Attribute
    minor: Unable to initialize object
  #001: H5Oattribute.c line 528 in H5O_attr_open_by_name(): can't locate attribute: 'weight_names'
    major: Attribute
    minor: Object not found
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unknown exception.
        at org.bytedeco.javacpp.hdf5$H5Object.openAttribute(Native Method)
        at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readAttributeAsString(Hdf5Archive.java:127)
        at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:173)
        at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:132)
        at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:60)
        at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:120)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:218)
        at org.deeplearning4j.nn.modelimport.keras.Model.importSequentialModel(Model.java:173)
        at com.area1.DgaKeras.main(DgaKeras.java:7)
        ... 6 more

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j deeplearning4j-modelimport 0.9.2-SNAPSHOT
* OS X 10.3.2 and Ubuntu 16 (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!
Yes, please do guide me if I can help.

**Comment by agibsonccc** [comment]
@twmattyoung this is impossible for us to reproduce without a file. Give us something we can actually use here. Please post your .h5 so we can take a closer look.

**Comment by maxpumperla** [comment]
@twmattyoung at the very least please share your keras model architecture, either python script or model json.

**Comment by twmattyoung** [comment]
@agibsonccc @maxpumperla thanks for the help. The .h5 is quite big so let try to attach the ipython notebook file here and it will take you some time to generate the .h5 and json. If this doesn't work for you, I will figure to send you the .h5.
[dga_cliassifier.ipynb.txt](https://github.com/deeplearning4j/deeplearning4j/files/1559641/dga_cliassifier.ipynb.txt)
