### ISSUE TITLE
MLPBackpropIrisExample Ouput Layer not working

### ISSUE THREAD

**Issue by jyt109** [deeplearning4j/deeplearning4j#442]
Versions

```
 <nd4j.version>0.0.3.5.5.6-SNAPSHOT</nd4j.version>
 <dl4j.version>0.0.3.3.5.alpha2-SNAPSHOT</dl4j.version>
 <canova.version>0.0.0.5-SNAPSHOT</canova.version>
```

`dl4j-0.0.3.3-examples/src/main/java/org/deeplearning4j/multilayer/MLPBackpropIrisExample.java`

```
public class MLPBackpropIrisExample {

    private static Logger log = LoggerFactory.getLogger(MLPBackpropIrisExample.class);

    public static void main(String[] args) throws IOException {
        // Customizing params
        Nd4j.MAX_SLICES_TO_PRINT = 10;
        Nd4j.MAX_ELEMENTS_PER_SLICE = 10;

        final int numInputs = 4;
        int outputNum = 3;
        int numSamples = 150;
        int batchSize = 150;
        int iterations = 10;
        long seed = 6;
        int listenerFreq = iterations/5;

        log.info("Load data....");
        DataSetIterator iter = new IrisDataSetIterator(batchSize, numSamples);

        log.info("Build model....");
        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .layer(new AutoEncoder())
                .nIn(numInputs)
                .nOut(outputNum)
                .seed(seed)
                .iterations(iterations)
                .weightInit(WeightInit.DISTRIBUTION)
                .dist(new NormalDistribution(0, 1e-1))
                .activationFunction("tanh")
                .learningRate(1e-3)
                .regularization(true)
                .l1(0.3)
                .l2(2e-4)
                .constrainGradientToUnitNorm(true)
                .list(3)
                .backward(true)
                .pretrain(false)
                .hiddenLayerSizes(new int[]{3, 2})
                .override(2, new ConfOverride() {
                    @Override
                    public void overrideLayer(int i, NeuralNetConfiguration.Builder builder) {
                        builder.activationFunction("softmax");
                        ##################
                        builder.layer(new OutputLayer()); ###OUTPUT LAYER NOT WORKING HERE
                        ################## 
                        builder.lossFunction(LossFunctions.LossFunction.MCXENT);
                    }
                }).build();

        MultiLayerNetwork model = new MultiLayerNetwork(conf);
        model.init();
        model.setListeners(Collections.singletonList((IterationListener) new ScoreIterationListener(listenerFreq)));

        log.info("Train model....");
        while(iter.hasNext()) {
            DataSet iris = iter.next();
            iris.normalizeZeroMeanZeroUnitVariance();
            model.fit(iris);
        }
        iter.reset();

        log.info("Evaluate weights....");
        for(org.deeplearning4j.nn.api.Layer layer : model.getLayers()) {
            INDArray w = layer.getParam(DefaultParamInitializer.WEIGHT_KEY);
            log.info("Weights: " + w);
        }


        log.info("Evaluate model....");
        Evaluation eval = new Evaluation();
        DataSetIterator iterTest = new IrisDataSetIterator(numSamples, numSamples);
        DataSet test = iterTest.next();
        test.normalizeZeroMeanZeroUnitVariance();
        INDArray output = model.output(test.getFeatureMatrix());
        eval.eval(test.getLabels(), output);
        log.info(eval.stats());
        log.info("****************Example finished********************");

    }
}
```

Stack Trace

```
o.d.m.MLPBackpropIrisExample - Build model....
o.d.m.MLPBackpropIrisExample - Train model....
Exception in thread "main" java.lang.IllegalArgumentException: Unable to get linear index >= 3
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3374)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.apply(DefaultOpExecutioner.java:466)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:52)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2756)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2736)
	at org.deeplearning4j.nn.updater.BaseUpdater.postApply(BaseUpdater.java:34)
	at org.deeplearning4j.nn.updater.BaseUpdater.update(BaseUpdater.java:26)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.updateGradientAccordingToParams(BaseOptimizer.java:260)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doBackWard(MultiLayerNetwork.java:1106)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1242)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1270)
	at org.deeplearning4j.multilayer.MLPBackpropIrisExample.main(MLPBackpropIrisExample.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by nyghtowl** [comment]
#444
