### ISSUE TITLE
Error in spark word2vec example

### ISSUE THREAD

**Issue by jarutis** [deeplearning4j/deeplearning4j#443]
I tried to run the following modified word2vec example code on Spark 1.4 local-mode.

```scala
import org.apache.spark.SparkConf
import org.apache.spark.SparkContext
import org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer
import org.deeplearning4j.spark.models.embeddings.word2vec.Word2Vec
import org.deeplearning4j.spark.models.embeddings.word2vec.Word2VecPerformer
import org.deeplearning4j.util.SerializationUtils

import java.io.File

object Word2VecModel {
  def main(args: Array[String]) {
    val sparkConf = new SparkConf()
      .setMaster("local[4]")
      .set(SparkDl4jMultiLayer.AVERAGE_EACH_ITERATION, "false")
      .set(Word2VecPerformer.NEGATIVE,String.valueOf("0"))
      .set("spark.akka.frameSize", "100")
      .set(Word2VecPerformer.VECTOR_LENGTH,String.valueOf(300))
      .setAppName("Word2Vec Spark")

    System.out.println("Setting up Spark Context...")

    val sc = new SparkContext(sparkConf)

    val rdd = sc.textFile(new File(args(0)).toURI().toString())
    val vec = new Word2Vec()
    val table = vec.train(rdd)

    SerializationUtils.saveObject(table,new File("table.ser"))
    System.out.println("Saved model")
  }
}
```

And got the following error.

```
 java.lang.UnsupportedOperationException: Can't read accumulator value in task                                                                                
        at org.apache.spark.Accumulable.value(Accumulators.scala:97)
        at org.deeplearning4j.spark.models.embeddings.word2vec.Word2Vec$2.call(Word2Vec.java:127)
        at org.deeplearning4j.spark.models.embeddings.word2vec.Word2Vec$2.call(Word2Vec.java:123)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreach$1.apply(JavaRDDLike.scala:327)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreach$1.apply(JavaRDDLike.scala:327)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
        at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:870)
        at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:870)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
        at org.apache.spark.scheduler.Task.run(Task.scala:70)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by jarutis** [comment]
I added a [repo](https://github.com/jarutis/word2vec-spark) with the project which throws this error.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/459
