### ISSUE TITLE
Keras Conv2D is not supported

### ISSUE THREAD

**Issue by olga-gorun** [deeplearning4j/deeplearning4j#4430]
#### Issue Description

KerasModelImport.importKerasModelAndWeights(modelJsonPath, weightsH5Path, false)

I got the following exception when importing Keras inception V3 model to deeplearning4j:

2017-12-18 12:49:59 INFO  KerasInceptionV3Net:52 - Importing Inception model from /home/olga/workspace/edison/KerasWorkshop/imagenet_inception_v3.json
2017-12-18 12:49:59 INFO  KerasInceptionV3Net:53 - Importing Weights model from /home/olga/workspace/edison/KerasWorkshop/imagenet_inception_v3.h5
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.UnsupportedKerasConfigurationException: Unsupported keras layer type Conv2D. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.KerasLayer.getKerasLayerFromConfig(KerasLayer.java:261)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.helperPrepareLayers(KerasModel.java:191)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:165)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:98)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.buildModel(KerasModel.java:641)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:177)
	at edu.usc.irds.dl.dl4j.examples.KerasInceptionV3Net.<init>(KerasInceptionV3Net.java:55)
	at edu.usc.irds.dl.dl4j.examples.KerasInceptionV3Net.main(KerasInceptionV3Net.java:109)

So I raise it here as message states.

#### Version Information

Checked on DeepLearning4j 0.8.0 and 0.9.1.
No Nvidia/CUDA usage

**Comment by raver119** [comment]
It would be strange if could run with 0.9.1. Keras 2 support is available on current master only, and was added after 0.9.1 was released.

**Comment by olga-gorun** [comment]
Thank you. I'll try to look at master
