### ISSUE TITLE
Support Keras Merge layers `Add`, `Concatenate` etc.

### ISSUE THREAD

**Issue by olga-gorun** [deeplearning4j/deeplearning4j#4437]
#### Issue Description

During Keras import I saw two more unsupported Keras layer types: Add and Concatenate (from Keras 2). 

KerasModelImport.importKerasModelAndWeights(modelJsonPath, weightsH5Path, false);

2017-12-19 14:33:59 INFO  KerasInceptionV3Net:51 - Importing Inception model from /home/olga/workspace/edison/KerasWorkshop/imagenet_inception_v3.json
2017-12-19 14:33:59 INFO  KerasInceptionV3Net:52 - Importing Weights model from /home/olga/workspace/edison/KerasWorkshop/imagenet_inception_v3.h5
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Concatenate. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:241)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:190)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:158)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:92)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:115)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:179)
	at edu.usc.irds.dl.dl4j.examples.KerasInceptionV3Net.<init>(KerasInceptionV3Net.java:54)
	at edu.usc.irds.dl.dl4j.examples.KerasInceptionV3Net.main(KerasInceptionV3Net.java:108)

and in a second case:

Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Add. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:241)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:190)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:158)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:92)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:115)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:197)
	at edu.usc.irds.dl.dl4j.examples.KerasImportResNet50.main(KerasImportResNet50.java:40)

#### Version Information

Checked with today's (19.12.2017) build of 9.2-snapshot.

**Comment by AlexDBlack** [comment]
@maxpumperla I believe this was added here, and hence this issue can be closed?
https://github.com/deeplearning4j/deeplearning4j/pull/4457

**Comment by maxpumperla** [comment]
exactly, thanks!

**Comment by olga-gorun** [comment]
Thank you
