### ISSUE TITLE
Model being passed as existing has no syn1/syn1Neg available

### ISSUE THREAD

**Issue by heyongcs** [deeplearning4j/deeplearning4j#4449]
useExistingWordVectors(word2Vec)

Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: Model being passed as existing has no syn1/syn1Neg available
	at org.deeplearning4j.models.paragraphvectors.ParagraphVectors$Builder.useExistingWordVectors(ParagraphVectors.java:709)
	at com.aliyun.ga.batch.SimilarityCase.main(SimilarityCase.java:126)

**Comment by OmSao** [comment]
I also faced same issue. Here is my code, which hit the same issue:

File gModel = new File("GoogleNews-vectors-negative300.bin.gz");
Word2Vec vecGoogle = WordVectorSerializer.readWord2VecModel(gModel);

ParagraphVectors vecGoogleForSentences = new ParagraphVectors.Builder()
            .useExistingWordVectors(vecGoogle)
            .build();

**Comment by raver119** [comment]
This is not a bug.
Exception message says: you can't use model which only has word vectors in.
