### ISSUE TITLE
DL4J expects X and Y dilation but Keras JSON is single-value

### ISSUE THREAD

**Issue by winobes** [deeplearning4j/deeplearning4j#4450]
#### Issue Description

The JSON for Keras's `Conv1D` is a single-value array: `"dilation_rate": [1]` but it appears that DL4J expects two values:

```
java.lang.ArrayIndexOutOfBoundsException: 1
at org.deeplearning4j.util.ConvolutionUtils.effectiveKernelSize(ConvolutionUtils.java:215)
```

Minimal example: https://gist.github.com/winobes/0018867f2563d0b0cd38e70df0b7d42b
(happy to provide H5 if it's helpful but unsure of the best way to do so..)

#### Version Information

Please indicate relevant versions, including, if relevant:

* DL4J: 0.9.2
* Platform: Ubuntu 16.04
* No CUDA

**Comment by winobes** [comment]
Not sure if it's helpful but I'll also note that manually changing the JSON to `"dilation_rate": [1, 1]` does not appear to fix the issue, resulting in the following error:

```
org.deeplearning4j.exception.DL4JInvalidInputException: Invalid input data or configuration: effective kernel height and input height must satisfy 0 < effective kernel height <= input height + 2 * padding height. 
Got effective kernel height = 5, input height = 1 and padding height = 0 which do not satisfy 0 < 5 <= 1
Input size: [numExamples,inputDepth,inputHeight,inputWidth]=[136, 200, 1, 1], inputKernel=[5, 1], strides=[1, 1], padding=[0, 0], dilation=[1, 1]
at org.deeplearning4j.util.ConvolutionUtils.validateShapes(ConvolutionUtils.java:148)
```

I also tried changing the dilation to `[0, 0]` and it makes it run without error but results in an output with shape `[sequence_len, num_classes]` which doesn't make much sense
