### ISSUE TITLE
maven exec plugin hangs on shutdown on very simple nd4j related java code

### ISSUE THREAD

**Issue by pertl** [deeplearning4j/deeplearning4j#4467]
#### Issue Description

I execute some very simple java code via the exec-maven-plugin. however the code seem to wait for very long instead of terminating instantly (as I would expect).

#### Version Information

- issue reproduced on macOS with oracle jdk8
- issue reproduced on ubuntu 17.04 + oracle jdk 8
- using nd4j native platform driver (0.9.1)

#### sample code for reproducing the issue

[link to github repo](https://github.com/pertl/nd4j-terminate)

**Comment by pertl** [comment]
after a delay of 15secs the maven exec plugin dumps this in the console:

`
[0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00]
[WARNING] thread Thread[Workspace deallocator thread,5,sample.TerminateHangs] was interrupted but is still alive after waiting at least 14999msecs
[WARNING] thread Thread[Workspace deallocator thread,5,sample.TerminateHangs] will linger despite being asked to die via interruption
[WARNING] NOTE: 1 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=sample.TerminateHangs,maxpri=10]
java.lang.IllegalThreadStateException
	at java.lang.ThreadGroup.destroy(ThreadGroup.java:778)
	at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:321)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
`

**Comment by pertl** [comment]
this is a screenshot from jvisualvm:

![thread-dump](https://user-images.githubusercontent.com/533830/34543007-20535cee-f0df-11e7-9780-39f6e09ff9c6.JPG)

**Comment by AlexDBlack** [comment]
Interesting - this thread is already a daemon thread, so it should shut down immediately... furthermore, we haven't seen this occur elsewhere...
https://github.com/deeplearning4j/nd4j/blob/9cf558a95b8a670261f21c5bcad2840125c94433/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/memory/provider/BasicWorkspaceManager.java#L246

**Comment by pertl** [comment]
probably the maven plugin uses Thread#interrupt() to terminate the daemon... however, as you can see in the code, all types of exceptions are swallowed by the daemon in an while(true) - loop which includes InterruptedException ... for that reason proper and immediate termination does not happen

**Comment by pertl** [comment]
currently the daemon basically does 

`
while(true)  { 
 try {
   /* clean up stuff */ 
  catch(Exception e) {
   //
  }
}
`

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/nd4j/pull/2464
