### ISSUE TITLE
RecordReader(Multi)DataSetIterator: Provide more informative exceptions for parsing errors

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4484]
Better errors here would help users debug data issues quicker...

From: https://github.com/deeplearning4j/deeplearning4j/issues/4470
```
Caused by: java.lang.NumberFormatException: empty String
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.lang.Double.parseDouble(Double.java:538)
at org.datavec.api.writable.Text.toDouble(Text.java:593)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritables(RecordReaderMultiDataSetIterator.java:419)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:271)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:240)
```

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4714
