### ISSUE TITLE
KerasModel Import issue, 9.2-SNAPSHOT (theano)

### ISSUE THREAD

**Issue by tomthetrainer** [deeplearning4j/deeplearning4j#4505]
Simple Keras Model Import is failing on Snapshots. 

Here is the model. 

https://gist.github.com/tomthetrainer/49b01419b3a14b4b2eb68873d93a0ce4

Here is my environment. 
Keras
```
python -c 'import keras; print(keras.__version__)'

Using Theano backend.
2.1.2
```

Python
```
python --version
Python 3.5.2 :: Continuum Analytics, Inc.
```

h5py

```
python -c 'import h5py; print(h5py.__version__)'
2.7.1
```

For my DL4J import here is my pom.xml
https://gist.github.com/tomthetrainer/0998fcf6f30ddc32d32e600e7571534b

Here is my import code. 

https://gist.github.com/tomthetrainer/cf7127ae695a440bd97bea29d952de09

Here is the error generated. 

Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException: Error when attempting to copy weights from Keras layer dense_1 to DL4J layer dense_1(weights is null). For more information, see http://deeplearning4j.org/model-import-keras.
	at org.deeplearning4j.nn.modelimport.keras.KerasLayer.copyWeightsToLayer(KerasLayer.java:268)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.copyWeightsToModel(KerasModelUtils.java:75)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:226)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:213)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:159)
	at skymind.dsx.Keras2ModelImport.main(Keras2ModelImport.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

I will attach the h5 file to this issue.

**Comment by tomthetrainer** [comment]
The issue does not seem to support adding h5 files, I will mail the file to Max

**Comment by maxpumperla** [comment]
@tomthetrainer I tried the same thing with tensorflow, which works. so, interestingly, this seems to be theano only. will inspect this further. thanks again.

**Comment by tomthetrainer** [comment]
I just thought that perhaps my Keras backend config would be relevant. 

```
less ~/.keras/keras.json
{"image_dim_ordering": "th","epsilon": 1e-07, "floatx": "float32", "backend": "theano"}

```
