### ISSUE TITLE
IllegalStateException: Indexes shouldn't be empty during regression with TBPTT (0.9.2-snapshot)

### ISSUE THREAD

**Issue by reuschling** [deeplearning4j/deeplearning4j#4507]
#### Issue Description

When I switched from 0.9.1 to current master branch version regarding fixed errors, I get a new exception (IllegalStateException: Indexes shouldn't be empty) now, when I make an regression with TBPTT, during net.evaluateRegression(testData); The same code worked with 0.9.1, and also works with different data. The code also works without TBPTT.
Stack trace:

`Exception in thread "main" java.lang.IllegalStateException: Indexes shouldn't be empty
	at org.nd4j.linalg.factory.Nd4j.pullRows(Nd4j.java:5889)
	at org.nd4j.linalg.factory.Nd4j.pullRows(Nd4j.java:5870)
	at org.deeplearning4j.eval.EvaluationUtils.extractNonMaskedTimeSteps(EvaluationUtils.java:188)
	at org.deeplearning4j.eval.BaseEvaluation.evalTimeSeries(BaseEvaluation.java:67)
	at org.deeplearning4j.eval.RegressionEvaluation.eval(RegressionEvaluation.java:159)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doEvaluation(MultiLayerNetwork.java:2992)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.evaluateRegression(MultiLayerNetwork.java:2885)
	at dfki.km.servicefactory.deeplearning.humotion.SequenceRegressionIssue.main(SequenceRegressionIssue.java:106)`

#### Version Information

* 0.9.2-snapshot from 01/14 2018
* Suse Linux 64bit
* no cuda

#### Contributing

I made a gist with a main that throws the error. 4 csv files with features and labels plus one java file: 

https://gist.github.com/reuschling/da5abb057debef5aeb86dd0e483ed676

**Comment by AlexDBlack** [comment]
Fixed here - https://github.com/deeplearning4j/deeplearning4j/pull/4509
thanks for the issue and the code to reproduce it.
