### ISSUE TITLE
Evaluation leaked workspace pointer?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4510]
Reproduce using this test:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/eval/EvalTest.java#L1067-L1093

Not sure why this is happening (other than it being related to the label mask)... perhaps the async iterator workspace is being closed down before the data has been used?

```
org.nd4j.linalg.exception.ND4JIllegalStateException: Op [oldmul] Y argument uses leaked workspace pointer from workspace [ADSI_ITER-96193e26-ebc3-427b-ae40-1c4a8acb4b2a]

	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.checkForWorkspaces(DefaultOpExecutioner.java:443)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.profilingHookIn(DefaultOpExecutioner.java:474)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:689)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:110)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.muli(BaseNDArray.java:3209)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.muli(BaseNDArray.java:3180)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.doColumnWise(BaseNDArray.java:2256)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.muliColumnVector(BaseNDArray.java:2676)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.applyMask(BaseOutputLayer.java:413)
	at org.deeplearning4j.nn.layers.BaseLayer.preOutput(BaseLayer.java:340)
	at org.deeplearning4j.nn.layers.AbstractLayer.preOutput(AbstractLayer.java:277)
	at org.deeplearning4j.nn.layers.recurrent.RnnOutputLayer.preOutput2d(RnnOutputLayer.java:105)
	at org.deeplearning4j.nn.layers.recurrent.RnnOutputLayer.output(RnnOutputLayer.java:137)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.activate(BaseOutputLayer.java:194)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:2708)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doEvaluation(MultiLayerNetwork.java:2989)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.evaluate(MultiLayerNetwork.java:3076)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.evaluate(MultiLayerNetwork.java:3017)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.evaluate(MultiLayerNetwork.java:2876)
	at org.deeplearning4j.eval.EvalTest.testEvalSplitting2(EvalTest.java:1092)
```

**Comment by raver119** [comment]
Interesting.

**Comment by AlexDBlack** [comment]
Probably not a problem - just caused by this - https://github.com/deeplearning4j/nd4j/issues/2577

**Comment by AlexDBlack** [comment]
Confirmed - with this PR (scope panic exclusion for such workspaces), it works fine now.
