### ISSUE TITLE
Support different weight init for LSTM recurrent weights (for Keras model import)

### ISSUE THREAD

**Issue by GrgrLmml** [deeplearning4j/deeplearning4j#4563]
#### Issue Description

I try to load a MultiLayerConfiguration from a Keras model. The Keras model has a custom embedding layer for word2vec embedding (see [model.json](https://gist.github.com/GrgrLmml/1204cd074b571a02279335d2b7a2c3d9) )
- expected behavior:
  MultiLayerConfiguration is successfully loaded.
- encountered behavior:
    Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.UnsupportedKerasConfigurationException: DL4J EmbeddingLayer includes bias but Keras Embedding does not. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
    	at org.deeplearning4j.nn.modelimport.keras.layers.KerasEmbedding.<init>(KerasEmbedding.java:67)
	at org.deeplearning4j.nn.modelimport.keras.KerasLayer.getKerasLayerFromConfig(KerasLayer.java:238)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.helperPrepareLayers(KerasModel.java:191)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:99)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:56)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.buildSequential(KerasModel.java:646)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialConfiguration(KerasModelImport.java:304)

- relevant Java code:

     MultiLayerConfiguration modelConf = KerasModelImport.importKerasSequentialConfiguration("/tmp/model.json");

#### Version Information

* Deeplearning4j version _0.9.1_ (0.9.2-SNAPSHOT produces a different exception)

#### Contributing

If I get guidance I would be happy to help fixing this issue.

**Comment by maxpumperla** [comment]
@GrgrLmml would you please tell me about the problem with 0.9.2-SNAPSHOT?

**Comment by maxpumperla** [comment]
I fixed your issue above by setting the bias term in DL4J to zero (a while back), so I need to know what the current issue seems to be.

**Comment by GrgrLmml** [comment]
@maxpumperla 0.9.2-SNAPSHOTS throws the following exception
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Specifying different initialization for recurrent weights not supported.. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.layers.recurrent.KerasLstm.<init>(KerasLstm.java:134)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:197)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:190)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:99)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:60)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:128)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialConfiguration(KerasModelImport.java:306)

**Comment by maxpumperla** [comment]
@GrgrLmml yeah, this one I'm aware of. Would you mind building a model with an LSTM in which recurrent weights and regular weights are set up with the same initialiser config, like this one:

https://github.com/deeplearning4j/deeplearning4j/blob/55b033f8dc65a9cba006062bdc6f21dc46c5f6e2/deeplearning4j-modelimport/src/test/resources/configs/keras2/imdb_lstm_tf_keras_2_config.json

**Comment by maxpumperla** [comment]
I'll leave this open, because we have to go back and change the DL4J LSTM implementation to support this.

**Comment by GrgrLmml** [comment]
@maxpumperla Using same initializers fix the problem for me, Thanks!

**Comment by AlexDBlack** [comment]
The DL4J functionality (but not the Keras import functionality) has been added here: https://github.com/deeplearning4j/deeplearning4j/pull/4579

**Comment by maxpumperla** [comment]
works on master now (with test) and should be in snapshots soon enough.
