### ISSUE TITLE
MNIST downloader can't handle corrupt local files?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4588]
Files to reproduce:
[MNIST_corrupt.zip](https://github.com/deeplearning4j/deeplearning4j/files/1684079/MNIST_corrupt.zip)

Once a local (incomplete download) corruption occurs, it seems the downloader can't handle this...
i.e., same exception, no matter how many times the test is run.

```
o.d.b.MnistFetcher - Downloading MNIST...

java.io.EOFException: Unexpected end of ZLIB input stream

	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.deeplearning4j.util.ArchiveUtils.unzipFileTo(ArchiveUtils.java:147)
	at org.deeplearning4j.base.MnistFetcher.downloadAndUntar(MnistFetcher.java:159)
	at org.deeplearning4j.base.MnistFetcherTest.testMnistDataFetcher(MnistFetcherTest.java:15)
```

**Comment by AlexDBlack** [comment]
Actually, it's even worse: it's also possible to get into a state where local MNIST files are corrupt, and features end up as all 0s... :(
