### ISSUE TITLE
Serialization of custom loss functions

### ISSUE THREAD

**Issue by tom-adsfund** [deeplearning4j/deeplearning4j#4605]
Trying to serialize/deserialize a model using a custom loss function fails.

Can test with CustomLossL1L2 from examples.

**Comment by tom-adsfund** [comment]
Stack trace:
```
java.lang.RuntimeException: org.nd4j.shade.jackson.databind.JsonMappingException: Could not resolve type id 'CustomLossL1L2' into a subtype of [simple type, class org.nd4j.linalg.lossfunctions.ILossFunction]: known type ids = [BinaryXENT, CosineProximity, FMeasure, Hinge, ILossFunction, KLD, L1, L2, MAE, MAPE, MCXENT, MSE, MSLE, NegativeLogLikelihood, Poisson, SquaredHinge]
 at [Source: {
  "backprop" : true,
  "backpropType" : "Standard",
  "cacheMode" : "NONE",
  "confs" : [ {
    "cacheMode" : "NONE",
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 1.0E-7
    },
    "layer" : {
      "dense" : {
        "activationFn" : {
          "LReLU" : {
            "alpha" : 0.01
          }
        },
        "adamMeanDecay" : 0.9,
        "adamVarDecay" : 0.999,
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "dist" : null,
        "dropOut" : 0.0,
        "epsilon" : 1.0E-8,
        "gradientNormalization" : "None",
        "gradientNormalizationThreshold" : 1.0,
        "iupdater" : {
          "@class" : "org.nd4j.linalg.learning.config.Adam",
          "beta1" : 0.9,
          "beta2" : 0.999,
          "epsilon" : 1.0E-8,
          "learningRate" : 0.01
        },
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 1.0E-7,
        "l2Bias" : 0.0,
        "layerName" : "layer0",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : "NaN",
        "momentumSchedule" : null,
        "nin" : 5,
        "nout" : 7,
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "updater" : "ADAM",
        "weightInit" : "XAVIER"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "None",
    "lrPolicyDecayRate" : "NaN",
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : "NaN",
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 6,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  }, {
    "cacheMode" : "NONE",
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 1.0E-7
    },
    "layer" : {
      "dense" : {
        "activationFn" : {
          "LReLU" : {
            "alpha" : 0.01
          }
        },
        "adamMeanDecay" : 0.9,
        "adamVarDecay" : 0.999,
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "dist" : null,
        "dropOut" : 0.0,
        "epsilon" : 1.0E-8,
        "gradientNormalization" : "None",
        "gradientNormalizationThreshold" : 1.0,
        "iupdater" : {
          "@class" : "org.nd4j.linalg.learning.config.Adam",
          "beta1" : 0.9,
          "beta2" : 0.999,
          "epsilon" : 1.0E-8,
          "learningRate" : 0.01
        },
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 1.0E-7,
        "l2Bias" : 0.0,
        "layerName" : "layer1",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : "NaN",
        "momentumSchedule" : null,
        "nin" : 7,
        "nout" : 7,
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "updater" : "ADAM",
        "weightInit" : "XAVIER"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "None",
    "lrPolicyDecayRate" : "NaN",
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : "NaN",
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 6,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  }, {
    "cacheMode" : "NONE",
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 1.0E-7
    },
    "layer" : {
      "dense" : {
        "activationFn" : {
          "LReLU" : {
            "alpha" : 0.01
          }
        },
        "adamMeanDecay" : 0.9,
        "adamVarDecay" : 0.999,
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "dist" : null,
        "dropOut" : 0.0,
        "epsilon" : 1.0E-8,
        "gradientNormalization" : "None",
        "gradientNormalizationThreshold" : 1.0,
        "iupdater" : {
          "@class" : "org.nd4j.linalg.learning.config.Adam",
          "beta1" : 0.9,
          "beta2" : 0.999,
          "epsilon" : 1.0E-8,
          "learningRate" : 0.01
        },
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 1.0E-7,
        "l2Bias" : 0.0,
        "layerName" : "layer2",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : "NaN",
        "momentumSchedule" : null,
        "nin" : 7,
        "nout" : 3,
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "updater" : "ADAM",
        "weightInit" : "XAVIER"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "None",
    "lrPolicyDecayRate" : "NaN",
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : "NaN",
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 6,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  }, {
    "cacheMode" : "NONE",
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 1.0E-7
    },
    "layer" : {
      "dense" : {
        "activationFn" : {
          "LReLU" : {
            "alpha" : 0.01
          }
        },
        "adamMeanDecay" : 0.9,
        "adamVarDecay" : 0.999,
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "dist" : null,
        "dropOut" : 0.0,
        "epsilon" : 1.0E-8,
        "gradientNormalization" : "None",
        "gradientNormalizationThreshold" : 1.0,
        "iupdater" : {
          "@class" : "org.nd4j.linalg.learning.config.Adam",
          "beta1" : 0.9,
          "beta2" : 0.999,
          "epsilon" : 1.0E-8,
          "learningRate" : 0.01
        },
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 1.0E-7,
        "l2Bias" : 0.0,
        "layerName" : "layer3",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : "NaN",
        "momentumSchedule" : null,
        "nin" : 3,
        "nout" : 3,
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "updater" : "ADAM",
        "weightInit" : "XAVIER"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "None",
    "lrPolicyDecayRate" : "NaN",
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : "NaN",
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 6,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  }, {
    "cacheMode" : "NONE",
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 1.0E-7
    },
    "layer" : {
      "output" : {
        "activationFn" : {
          "Identity" : { }
        },
        "adamMeanDecay" : 0.9,
        "adamVarDecay" : 0.999,
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "dist" : null,
        "dropOut" : 0.0,
        "epsilon" : 1.0E-8,
        "gradientNormalization" : "None",
        "gradientNormalizationThreshold" : 1.0,
        "iupdater" : {
          "@class" : "org.nd4j.linalg.learning.config.Adam",
          "beta1" : 0.9,
          "beta2" : 0.999,
          "epsilon" : 1.0E-8,
          "learningRate" : 0.01
        },
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 1.0E-7,
        "l2Bias" : 0.0,
        "layerName" : "layer4",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "lossFn" : {
          "CustomLossL1L2" : { }
        },
        "lossFunction" : null,
        "momentum" : "NaN",
        "momentumSchedule" : null,
        "nin" : 3,
        "nout" : 1,
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "updater" : "ADAM",
        "weightInit" : "XAVIER"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "None",
    "lrPolicyDecayRate" : "NaN",
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : "NaN",
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 6,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  } ],
  "inferenceWorkspaceMode" : "SINGLE",
  "inputPreProcessors" : { },
  "iterationCount" : 0,
  "pretrain" : false,
  "tbpttBackLength" : 20,
  "tbpttFwdLength" : 20,
  "trainingWorkspaceMode" : "SINGLE"
}
; line: 329, column: 11] (through reference chain: org.deeplearning4j.nn.conf.MultiLayerConfiguration["confs"]->java.util.ArrayList[4]->org.deeplearning4j.nn.conf.NeuralNetConfiguration["layer"]->org.deeplearning4j.nn.conf.layers.OutputLayer["lossFn"])
	at org.deeplearning4j.nn.conf.MultiLayerConfiguration.fromJson(MultiLayerConfiguration.java:141)
	at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:239)
	at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:270)
	at com.tree4pc.app.Main.lame(Main.java:117)
	at com.tree4pc.app.Main.main(Main.java:54)
Caused by: org.nd4j.shade.jackson.databind.JsonMappingException: Could not resolve type id 'CustomLossL1L2' into a subtype of [simple type, class org.nd4j.linalg.lossfunctions.ILossFunction]: known type ids = [BinaryXENT, CosineProximity, FMeasure, Hinge, ILossFunction, KLD, L1, L2, MAE, MAPE, MCXENT, MSE, MSLE, NegativeLogLikelihood, Poisson, SquaredHinge]
 at [Source: {
  "backprop" : true,
  "backpropType" : "Standard",
  "cacheMode" : "NONE",
  "confs" : [ {
    "cacheMode" : "NONE",
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 1.0E-7
    },
    "layer" : {
      "dense" : {
        "activationFn" : {
          "LReLU" : {
            "alpha" : 0.01
          }
        },
        "adamMeanDecay" : 0.9,
        "adamVarDecay" : 0.999,
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "dist" : null,
        "dropOut" : 0.0,
        "epsilon" : 1.0E-8,
        "gradientNormalization" : "None",
        "gradientNormalizationThreshold" : 1.0,
        "iupdater" : {
          "@class" : "org.nd4j.linalg.learning.config.Adam",
          "beta1" : 0.9,
          "beta2" : 0.999,
          "epsilon" : 1.0E-8,
          "learningRate" : 0.01
        },
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 1.0E-7,
        "l2Bias" : 0.0,
        "layerName" : "layer0",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : "NaN",
        "momentumSchedule" : null,
        "nin" : 5,
        "nout" : 7,
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "updater" : "ADAM",
        "weightInit" : "XAVIER"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "None",
    "lrPolicyDecayRate" : "NaN",
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : "NaN",
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 6,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  }, {
    "cacheMode" : "NONE",
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 1.0E-7
    },
    "layer" : {
      "dense" : {
        "activationFn" : {
          "LReLU" : {
            "alpha" : 0.01
          }
        },
        "adamMeanDecay" : 0.9,
        "adamVarDecay" : 0.999,
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "dist" : null,
        "dropOut" : 0.0,
        "epsilon" : 1.0E-8,
        "gradientNormalization" : "None",
        "gradientNormalizationThreshold" : 1.0,
        "iupdater" : {
          "@class" : "org.nd4j.linalg.learning.config.Adam",
          "beta1" : 0.9,
          "beta2" : 0.999,
          "epsilon" : 1.0E-8,
          "learningRate" : 0.01
        },
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 1.0E-7,
        "l2Bias" : 0.0,
        "layerName" : "layer1",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : "NaN",
        "momentumSchedule" : null,
        "nin" : 7,
        "nout" : 7,
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "updater" : "ADAM",
        "weightInit" : "XAVIER"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "None",
    "lrPolicyDecayRate" : "NaN",
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : "NaN",
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 6,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  }, {
    "cacheMode" : "NONE",
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 1.0E-7
    },
    "layer" : {
      "dense" : {
        "activationFn" : {
          "LReLU" : {
            "alpha" : 0.01
          }
        },
        "adamMeanDecay" : 0.9,
        "adamVarDecay" : 0.999,
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "dist" : null,
        "dropOut" : 0.0,
        "epsilon" : 1.0E-8,
        "gradientNormalization" : "None",
        "gradientNormalizationThreshold" : 1.0,
        "iupdater" : {
          "@class" : "org.nd4j.linalg.learning.config.Adam",
          "beta1" : 0.9,
          "beta2" : 0.999,
          "epsilon" : 1.0E-8,
          "learningRate" : 0.01
        },
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 1.0E-7,
        "l2Bias" : 0.0,
        "layerName" : "layer2",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : "NaN",
        "momentumSchedule" : null,
        "nin" : 7,
        "nout" : 3,
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "updater" : "ADAM",
        "weightInit" : "XAVIER"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "None",
    "lrPolicyDecayRate" : "NaN",
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : "NaN",
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 6,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  }, {
    "cacheMode" : "NONE",
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 1.0E-7
    },
    "layer" : {
      "dense" : {
        "activationFn" : {
          "LReLU" : {
            "alpha" : 0.01
          }
        },
        "adamMeanDecay" : 0.9,
        "adamVarDecay" : 0.999,
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "dist" : null,
        "dropOut" : 0.0,
        "epsilon" : 1.0E-8,
        "gradientNormalization" : "None",
        "gradientNormalizationThreshold" : 1.0,
        "iupdater" : {
          "@class" : "org.nd4j.linalg.learning.config.Adam",
          "beta1" : 0.9,
          "beta2" : 0.999,
          "epsilon" : 1.0E-8,
          "learningRate" : 0.01
        },
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 1.0E-7,
        "l2Bias" : 0.0,
        "layerName" : "layer3",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : "NaN",
        "momentumSchedule" : null,
        "nin" : 3,
        "nout" : 3,
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "updater" : "ADAM",
        "weightInit" : "XAVIER"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "None",
    "lrPolicyDecayRate" : "NaN",
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : "NaN",
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 6,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  }, {
    "cacheMode" : "NONE",
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 1.0E-7
    },
    "layer" : {
      "output" : {
        "activationFn" : {
          "Identity" : { }
        },
        "adamMeanDecay" : 0.9,
        "adamVarDecay" : 0.999,
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "dist" : null,
        "dropOut" : 0.0,
        "epsilon" : 1.0E-8,
        "gradientNormalization" : "None",
        "gradientNormalizationThreshold" : 1.0,
        "iupdater" : {
          "@class" : "org.nd4j.linalg.learning.config.Adam",
          "beta1" : 0.9,
          "beta2" : 0.999,
          "epsilon" : 1.0E-8,
          "learningRate" : 0.01
        },
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 1.0E-7,
        "l2Bias" : 0.0,
        "layerName" : "layer4",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "lossFn" : {
          "CustomLossL1L2" : { }
        },
        "lossFunction" : null,
        "momentum" : "NaN",
        "momentumSchedule" : null,
        "nin" : 3,
        "nout" : 1,
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "updater" : "ADAM",
        "weightInit" : "XAVIER"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "None",
    "lrPolicyDecayRate" : "NaN",
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : "NaN",
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 6,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  } ],
  "inferenceWorkspaceMode" : "SINGLE",
  "inputPreProcessors" : { },
  "iterationCount" : 0,
  "pretrain" : false,
  "tbpttBackLength" : 20,
  "tbpttFwdLength" : 20,
  "trainingWorkspaceMode" : "SINGLE"
}
; line: 329, column: 11] (through reference chain: org.deeplearning4j.nn.conf.MultiLayerConfiguration["confs"]->java.util.ArrayList[4]->org.deeplearning4j.nn.conf.NeuralNetConfiguration["layer"]->org.deeplearning4j.nn.conf.layers.OutputLayer["lossFn"])
	at org.nd4j.shade.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at org.nd4j.shade.jackson.databind.DeserializationContext.unknownTypeException(DeserializationContext.java:948)
	at org.nd4j.shade.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:275)
	at org.nd4j.shade.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:162)
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:100)
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:49)
	at org.nd4j.shade.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
	at org.nd4j.shade.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:521)
	at org.nd4j.shade.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at org.nd4j.shade.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:114)
	at org.nd4j.shade.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:49)
	at org.nd4j.shade.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
	at org.nd4j.shade.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:521)
	at org.nd4j.shade.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at org.nd4j.shade.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at org.nd4j.shade.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:240)
	at org.nd4j.shade.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:212)
	at org.nd4j.shade.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at org.nd4j.shade.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at org.nd4j.shade.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at org.nd4j.shade.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at org.nd4j.shade.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at org.deeplearning4j.nn.conf.serde.MultiLayerConfigurationDeserializer.deserialize(MultiLayerConfigurationDeserializer.java:21)
	at org.deeplearning4j.nn.conf.serde.MultiLayerConfigurationDeserializer.deserialize(MultiLayerConfigurationDeserializer.java:12)
	at org.nd4j.shade.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at org.nd4j.shade.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at org.deeplearning4j.nn.conf.MultiLayerConfiguration.fromJson(MultiLayerConfiguration.java:139)
	... 4 more
```

**Comment by treo** [comment]
Add the following to your Application initialization (in the example simply as the first line of the main function) and it should work:
```java
        NeuralNetConfiguration.reinitMapperWithSubtypes(Collections.singletonList(new NamedType(CustomLossL1L2.class)));
```

**Comment by tom-adsfund** [comment]
Yes, this fixes the problem. Thanks!

**Comment by tom-adsfund** [comment]
I don't know if anyone wants to keep this issue open to add this to docs, or something else.

**Comment by AlexDBlack** [comment]
I'll close this - it's a known issue with reflections (which doesn't work properly on android, or certain classpath configurations in intellij for example). I hope to look at that soon-ish.

**Comment by AlexDBlack** [comment]
See also https://github.com/deeplearning4j/deeplearning4j/issues/4562
