### ISSUE TITLE
Masking in `CnnSentenceClassificationExample`

### ISSUE THREAD

**Issue by ekravi** [deeplearning4j/deeplearning4j#4669]
I have a similar iterator to `CnnSentenceDataSetIterator`.
However when I use it with feature masking different that `null` I get the following exception:
```Masked global pooling with on CNN data currently only supports data with h=1 or w=1:
 input activations must have shape [minibatchSize,depth,height=1,width] or [minibatchSize,depth,height,width=1] with  mask array of shape [minibatchSize,width] or [minibatchSize,height]```.

The feature shape is (batch size, 1, word embedding size, number of terms in sentence).
The masking shape is (batch size, number of terms in sentence).

Here is [a link](https://gist.github.com/ekravi/f95ce93ddda82fc33e99ff8f8d6ce3f6) to my datasetiterator gist

**Comment by AlexDBlack** [comment]
Can you provide the complete stack trace, and network configuration? It's difficult to provide any recommendations without those.

**Comment by ekravi** [comment]
Sure,
```Exception in thread "main" java.lang.UnsupportedOperationException: Masked global pooling with on CNN data currently only supports data with h=1 or w=1:
 input activations must have shape [minibatchSize,depth,height=1,width] or [minibatchSize,depth,height,width=1] with  mask array of shape [minibatchSize,width] or [minibatchSize,height] respectively.
 Got 4d activations array (shape [63, 300, 200, 1]) and 2d mask array (shape [63, 24]) (layer name: globalPool, layer index: 5)
	at org.deeplearning4j.nn.layers.pooling.GlobalPoolingLayer.activate(GlobalPoolingLayer.java:158)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:107)
	at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1464)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1296)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:174)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:60)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:53)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:933)
	at classification.deepLearning.learners.BaseTwitterNeuralNetworkLearner.train(BaseTwitterNeuralNetworkLearner.java:103)
	at classification.deepLearning.TweetsNonSequentialClassifier.classify(TweetsNonSequentialClassifier.java:67)
	at classification.deepLearning.TweetsNonSequentialClassifier.main(TweetsNonSequentialClassifier.java:95)```

[Gist of the network](https://gist.github.com/ekravi/9cd2bc68ffe774c6b8396181bc9a7ee6).

Sample input:
`2	@Mando_DaDon you dislike every sign ! Lmao
4	Room with a bunch of Turners and Velasquezs. No big deal. @ The Frick Collection http://t.co/jMN6xqVLXc`

**Comment by AlexDBlack** [comment]
OK, so from the data pipeline, your features have shape: ```[nextBatch.size(), 1, vectorSize, maxLengthInBatch]```, yet your kernels are like ```.kernelSize(3, truncateLength)```... there doesn't seem to be any relationship between those two? (kernel size should match or exceed the max length in the batch).

Second, I think you've got things around the wrong way... activations are [n,c,h,w] format, and you have h=vectorSize... but then you have kernelHeight=3/4/5
In other words, your kernels cover some subset of the time steps, and only 3/4/5 parts of the vectors. That's the transpose of what you want: they should
You do:
[w0-0, w1-0, w2-0, ...]
[w0-1, w1-1, w2-2, ...]
[w0-2, w1-2, w2-2, ...]
[w0-3, w1-3, w2-3, ...]

Where wi-j represents the jth number in the ith word vector.
Your kernels go across the page (i.e., for the [3,truncateLength] kernel you w0-0 to w0-2 in the height dim, and w0-0 to w0-truncateLength in the width dim), when they should go down the page. Or equivalently, your data needs to be transposed in the h/w dimensions if you keep the current kernel sizes.
