### ISSUE TITLE
RecurrentLSTMMnistExample occured when Traing model sequence.

### ISSUE THREAD

**Issue by ckddyd777** [deeplearning4j/deeplearning4j#467]
Hi,

I have run the following from dl4j-0.0.3.3-examples

java -cp target/deeplearning4j-examples-0.0.3.3.3-SNAPSHOT.jar org.deeplearning4j.recurrent.RecurrentLSTMMnistExample

but, I faced a problem as below:
o.d.r.RecurrentLSTMMnistExample - Loading data...
o.d.r.RecurrentLSTMMnistExample - Building model...
o.d.r.RecurrentLSTMMnistExample - Training model...
Exception in thread "main" java.lang.NullPointerException
        at org.deeplearning4j.nn.updater.BaseUpdater.postApply(BaseUpdater.java:48)
        at org.deeplearning4j.nn.updater.BaseUpdater.update(BaseUpdater.java:26)
        at org.deeplearning4j.optimize.solvers.BaseOptimizer.updateGradientAccordingToParams(BaseOptimizer.java:259)
        at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:114)
        at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:128)
        at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
        at org.deeplearning4j.nn.layers.recurrent.LSTM.fit(LSTM.java:531)
        at org.deeplearning4j.recurrent.RecurrentLSTMMnistExample.main(RecurrentLSTMMnistExample.java:63)
-- org.jblas INFO Deleting /tmp/jblas2332603035172796993/libjblas_arch_flavor.so
-- org.jblas INFO Deleting /tmp/jblas2332603035172796993/libjblas.so
-- org.jblas INFO Deleting /tmp/jblas2332603035172796993

Do you have any solution to solve this problem? I faced this problem with windows 7 (32 and 64bits) and, ubuntu 14.04 (64bits).

Thanks.

**Comment by agibsonccc** [comment]
#475
