### ISSUE TITLE
dl4j mvn install encounted with deeplearning4j-ui package issue

### ISSUE THREAD

**Issue by m-final** [deeplearning4j/deeplearning4j#468]
Hi, all

I have run the mvn install command as the tutorial said, and after I fixed many of them, the ui package seems still have something wrong. here is the error info. please help. thanks~~~(I just post the last few lines about the info. using the debug mode)

<configuration>
  <artifact default-value="${project.artifact}"/>
  <attachedArtifacts default-value="${project.attachedArtifacts}"/>
  <createChecksum default-value="false">${createChecksum}</createChecksum>
  <localRepository>${localRepository}</localRepository>
  <packaging default-value="${project.packaging}"/>
  <pomFile default-value="${project.file}"/>
  <skip default-value="false">${maven.install.skip}</skip>
  <updateReleaseInfo default-value="false">${updateReleaseInfo}</updateReleaseInfo>
</configuration>
[DEBUG] =======================================================================
[DEBUG] Using mirror wisers-nexus (http://scmm.wisers.com/nexus/content/groups/public/) for codehaus-nexus-snapshots (https://nexus.codehaus.org/content/repositories/snapshots/).
[DEBUG] Using mirror wisers-nexus (http://scmm.wisers.com/nexus/content/groups/public/) for codehaus.org (http://snapshots.repository.codehaus.org).
[DEBUG] Using mirror wisers-nexus (http://scmm.wisers.com/nexus/content/groups/public/) for java.net (http://download.java.net/maven/2).
[DEBUG] Using mirror wisers-nexus (http://scmm.wisers.com/nexus/content/groups/public/) for m1.java.net (http://download.java.net/maven/1).
[WARNING] The POM for org.apache.hadoop:hadoop-common:jar:2.0.0-cdh4.6.0 is missing, no dependency information available
[WARNING] The POM for org.apache.hadoop:hadoop-yarn-api:jar:2.0.0-cdh4.6.0 is missing, no dependency information available
[WARNING] The POM for org.apache.hadoop:hadoop-yarn-common:jar:2.0.0-cdh4.6.0 is missing, no dependency information available
[WARNING] The POM for org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.0.0-cdh4.6.0 is missing, no dependency information available
[WARNING] The POM for org.apache.hadoop:hadoop-hdfs:jar:2.0.0-cdh4.6.0 is missing, no dependency information available
[WARNING] The POM for org.apache.hadoop:hadoop-hdfs:jar:tests:2.0.0-cdh4.6.0 is missing, no dependency information available
[WARNING] The POM for org.apache.hadoop:hadoop-yarn-server-tests:jar:tests:2.0.0-cdh4.6.0 is missing, no dependency information available
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=85, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=52, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=2, ConflictResolver.conflictItemCount=84, DefaultDependencyCollector.collectTime=437, DefaultDependencyCollector.transformTime=2}
[DEBUG] org.deeplearning4j:cdh4:jar:0.0.3.3.5.alpha2-SNAPSHOT
[DEBUG]    org.deeplearning4j:deeplearning4j-scaleout-api:jar:0.0.3.3.5.alpha2-SNAPSHOT:compile
[DEBUG]       org.deeplearning4j:deeplearning4j-core:jar:0.0.3.3.5.alpha2-SNAPSHOT:compile
[DEBUG]          io.netty:netty-buffer:jar:4.0.28.Final:compile
[DEBUG]             io.netty:netty-common:jar:4.0.28.Final:compile
[DEBUG]          org.nd4j:canova-api:jar:0.0.0.5-SNAPSHOT:compile
[DEBUG]          ch.qos.logback:logback-classic:jar:1.0.6:compile (version managed from 1.1.2 by org.deeplearning4j:deeplearning4j-parent:0.0.3.3.5.alpha2-SNAPSHOT)
[DEBUG]          ch.qos.logback:logback-core:jar:1.0.6:compile (version managed from 1.1.2 by org.deeplearning4j:deeplearning4j-parent:0.0.3.3.5.alpha2-SNAPSHOT)
[DEBUG]          org.apache.commons:commons-math3:jar:3.4.1:compile
[DEBUG]          org.springframework:spring-core:jar:3.2.5.RELEASE:compile
[DEBUG]             commons-logging:commons-logging:jar:1.1.1:compile
[DEBUG]          commons-io:commons-io:jar:1.3.2:compile
[DEBUG]          au.com.bytecode:opencsv:jar:2.4:compile
[DEBUG]          org.apache.commons:commons-compress:jar:1.8:compile
[DEBUG]             org.tukaani:xz:jar:1.5:compile
[DEBUG]          com.google.guava:guava:jar:18.0:compile
[DEBUG]          org.apache.commons:commons-lang3:jar:3.3.1:compile
[DEBUG]          com.fasterxml.jackson.core:jackson-databind:jar:2.5.1:compile
[DEBUG]          com.fasterxml.jackson.core:jackson-annotations:jar:2.5.1:compile
[DEBUG]          org.projectlombok:lombok:jar:1.16.4:compile
[DEBUG]          com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.5.1:compile
[DEBUG]             org.yaml:snakeyaml:jar:1.12:compile
[DEBUG]       org.json:json:jar:20131018:compile
[DEBUG]       com.fasterxml.jackson.core:jackson-core:jar:2.5.1:compile
[DEBUG]    org.apache.avro:avro:jar:1.7.1:compile
[DEBUG]       org.codehaus.jackson:jackson-core-asl:jar:1.8.8:compile
[DEBUG]       org.codehaus.jackson:jackson-mapper-asl:jar:1.8.8:compile
[DEBUG]       com.thoughtworks.paranamer:paranamer:jar:2.3:compile
[DEBUG]       org.xerial.snappy:snappy-java:jar:1.0.4.1:compile
[DEBUG]       org.slf4j:slf4j-api:jar:1.7.12:compile (version managed from 1.6.4 by org.deeplearning4j:deeplearning4j-parent:0.0.3.3.5.alpha2-SNAPSHOT)
[DEBUG]    org.apache.avro:avro-ipc:jar:1.7.1:compile
[DEBUG]       org.mortbay.jetty:jetty:jar:6.1.26:compile
[DEBUG]       org.mortbay.jetty:jetty-util:jar:6.1.26:compile
[DEBUG]       io.netty:netty:jar:3.4.0.Final:compile
[DEBUG]       org.apache.velocity:velocity:jar:1.7:compile
[DEBUG]          commons-collections:commons-collections:jar:3.2.1:compile
[DEBUG]          commons-lang:commons-lang:jar:2.4:compile
[DEBUG]       org.mortbay.jetty:servlet-api:jar:2.5-20081211:compile
[DEBUG]    org.apache.hadoop:hadoop-common:jar:2.0.0-cdh4.6.0:compile
[DEBUG]    org.apache.hadoop:hadoop-yarn-api:jar:2.0.0-cdh4.6.0:provided
[DEBUG]    org.apache.hadoop:hadoop-yarn-common:jar:2.0.0-cdh4.6.0:provided
[DEBUG]    org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.0.0-cdh4.6.0:provided
[DEBUG]    org.apache.hadoop:hadoop-hdfs:jar:2.0.0-cdh4.6.0:compile
[DEBUG]    org.apache.hadoop:hadoop-hdfs:jar:tests:2.0.0-cdh4.6.0:test
[DEBUG]    org.apache.hadoop:hadoop-yarn-server-tests:jar:tests:2.0.0-cdh4.6.0:test
[DEBUG]    org.nd4j:nd4j-jblas:jar:0.0.3.5.5.6-SNAPSHOT:test
[DEBUG]       org.jblas:jblas:jar:1.2.4:test
[DEBUG]       org.nd4j:nd4j-api:jar:0.0.3.5.5.6-SNAPSHOT:compile
[DEBUG]          junit:junit:jar:4.12:test (scope managed from compile by org.deeplearning4j:deeplearning4j-parent:0.0.3.3.5.alpha2-SNAPSHOT) (version managed from 4.11 by org.deeplearning4j:deeplearning4j-parent:0.0.3.3.5.alpha2-SNAPSHOT)
[DEBUG]             org.hamcrest:hamcrest-core:jar:1.3:test
[DEBUG]          org.reflections:reflections:jar:0.9.10:compile
[DEBUG]             org.javassist:javassist:jar:3.19.0-GA:compile
[DEBUG]             com.google.code.findbugs:annotations:jar:2.0.1:compile
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] DeepLearning4j ..................................... SUCCESS [  0.743 s]
[INFO] dl4j-test-resources ................................ SUCCESS [ 39.151 s]
[INFO] deeplearning4j-core ................................ SUCCESS [ 11.841 s]
[INFO] DeepLearning4j-scaleout-parent ..................... SUCCESS [  0.011 s]
[INFO] deeplearning4j-scaleout-api ........................ SUCCESS [  0.763 s]
[INFO] deeplearning4j-scaleout-zookeeper .................. SUCCESS [  0.912 s]
[INFO] deeplearning4j-scaleout-akka ....................... SUCCESS [  2.703 s]
[INFO] deeplearning4j-nlp ................................. SUCCESS [  7.206 s]
[INFO] DeepLearning4j-AWS ................................. SUCCESS [  1.883 s]
[INFO] hadoop-yarn ........................................ SUCCESS [  0.023 s]
[INFO] cdh4 ............................................... FAILURE [  0.460 s]
[INFO] deeplearning4j-nlp-yarn ............................ SKIPPED
[INFO] org.deeplearning4j.spark ........................... SKIPPED
[INFO] dl4j-spark ......................................... SKIPPED
[INFO] dl4j-spark-nlp ..................................... SKIPPED
[INFO] dl4j-spark-ml ...................................... SKIPPED
[INFO] deeplearning4j-cli ................................. SKIPPED
[INFO] deeplearning4j-cli-api ............................. SKIPPED
[INFO] deeplearning4j-ui .................................. SKIPPED
[INFO] dl4j-caffe ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:06 min
[INFO] Finished at: 2015-07-17T18:17:12+08:00
[INFO] Final Memory: 62M/726M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cdh4: Could not resolve dependencies for project org.deeplearning4j:cdh4:jar:0.0.3.3.5.alpha2-SNAPSHOT: The following artifacts could not be resolved: org.apache.hadoop:hadoop-common:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-api:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-common:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-hdfs:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-hdfs:jar:tests:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-server-tests:jar:tests:2.0.0-cdh4.6.0: Failure to find org.apache.hadoop:hadoop-common:jar:2.0.0-cdh4.6.0 in http://scmm.wisers.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of wisers-nexus has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project cdh4: Could not resolve dependencies for project org.deeplearning4j:cdh4:jar:0.0.3.3.5.alpha2-SNAPSHOT: The following artifacts could not be resolved: org.apache.hadoop:hadoop-common:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-api:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-common:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-hdfs:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-hdfs:jar:tests:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-server-tests:jar:tests:2.0.0-cdh4.6.0: Failure to find org.apache.hadoop:hadoop-common:jar:2.0.0-cdh4.6.0 in http://scmm.wisers.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of wisers-nexus has elapsed or updates are forced
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.deeplearning4j:cdh4:jar:0.0.3.3.5.alpha2-SNAPSHOT: The following artifacts could not be resolved: org.apache.hadoop:hadoop-common:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-api:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-common:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-hdfs:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-hdfs:jar:tests:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-server-tests:jar:tests:2.0.0-cdh4.6.0: Failure to find org.apache.hadoop:hadoop-common:jar:2.0.0-cdh4.6.0 in http://scmm.wisers.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of wisers-nexus has elapsed or updates are forced
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.apache.hadoop:hadoop-common:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-api:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-common:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-hdfs:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-hdfs:jar:tests:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-server-tests:jar:tests:2.0.0-cdh4.6.0: Failure to find org.apache.hadoop:hadoop-common:jar:2.0.0-cdh4.6.0 in http://scmm.wisers.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of wisers-nexus has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.apache.hadoop:hadoop-common:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-api:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-common:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-hdfs:jar:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-hdfs:jar:tests:2.0.0-cdh4.6.0, org.apache.hadoop:hadoop-yarn-server-tests:jar:tests:2.0.0-cdh4.6.0: Failure to find org.apache.hadoop:hadoop-common:jar:2.0.0-cdh4.6.0 in http://scmm.wisers.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of wisers-nexus has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.apache.hadoop:hadoop-common:jar:2.0.0-cdh4.6.0 in http://scmm.wisers.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of wisers-nexus has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 27 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cdh4

**Comment by agibsonccc** [comment]
This hasn't happened to me. Did you run the build multiple times?

**Comment by m-final** [comment]
yes, I build that more than one time and same error still here, does that
means I should install the hadoop component to cover that?

2015-07-18 1:54 GMT+08:00 Adam Gibson <notifications@github.com>:

**Comment by agibsonccc** [comment]
Let me walk you through it on gitter in real time:

https://gitter.im/deeplearning4j/deeplearning4j
ᐧ

**Comment by agibsonccc** [comment]
So I need to reiterate this, I have no way of understanding what your issue is. A back and forth will be significantly easier here. I'm going to close this if I don't hear back on this within the next few days.

**Comment by m-final** [comment]
Sorry for not reply immediately. 
First show great thanks to your helping!
For that issue is happened in another computer, so I need to replicate the whole things after I come back to the workplace. Just wait for another 24 hours, please ~

**Comment by agibsonccc** [comment]
This was related to a local configuration issue. Closing.

**Comment by omshanti** [comment]
What was the local config issue?

**Comment by raver119** [comment]
@omshanti i doubt this issue is relevant these days - whole year since original issue raised, and UI was overhauled since that time. 

So if you have any problems there - please open new issue.

**Comment by windowtodata** [comment]
Thanks for the response. It got resolved after I reinstalled my intellij

**Comment by m-final** [comment]
@omshanti  one of my maven's configuration conflicted with the dl4j, problem about remote warehouse address setting. It was irrelevant to dl4j's source codes.
