### ISSUE TITLE
Proper exception handling when run from scala sbt?

### ISSUE THREAD

**Issue by doofin** [deeplearning4j/deeplearning4j#4684]
#### Issue Description

Please describe our issue, along with:
- expected behavior : termination after exception should not interfere with next run
- encountered behavior : java.lang.ExceptionInInitializerError after exception unhandled

after the first exception:
```
[error] (run-main-0) org.deeplearning4j.exception.DL4JInvalidInputException: Input that is not a matrix; expected matrix (rank 2), got rank 4 array with shape [10, 3, 40, 30]. Missing preprocessor or wrong input type? (layer name: layer0, layer index: 0)

```

after I press ctr-c and re-run from sbt again I got 
```
[info] Running Main 
[run-main-1] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
[error] (run-main-1) java.lang.ExceptionInInitializerError
[error] java.lang.ExceptionInInitializerError
[error] 	at org.nd4j.jita.concurrency.CudaAffinityManager.getNumberOfDevices(CudaAffinityManager.java:185)
[error] 	at org.nd4j.jita.constant.ConstantProtector.purgeProtector(ConstantProtector.java:38)
[error] 	at org.nd4j.jita.constant.ConstantProtector.<init>(ConstantProtector.java:31)
[error] 	at org.nd4j.jita.constant.ConstantProtector.<clinit>(ConstantProtector.java:20)
[error] 	at org.nd4j.jita.constant.ProtectedCudaConstantHandler.<clinit>(ProtectedCudaConstantHandler.java:48)
[error] 	at org.nd4j.jita.constant.CudaConstantHandler.<clinit>(CudaConstantHandler.java:17)

```
#### Version Information

Please indicate relevant versions, including, if relevant:
```
      "org.deeplearning4j" % "deeplearning4j-core" % "0.9.1",
      "org.nd4j" % "nd4j-cuda-8.0-platform" % "0.9.1",
      "org.nd4j" % "nd4j-cuda-8.0" % "0.9.1"

os : ubuntu 16.04
scala version: 2.12.4
sbt version : 1.1.0
```
#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
Closing this issue as stalled.

Feel free to reopen this issue if you'll have any updates.
