### ISSUE TITLE
keras import error when having a flatten layer append to a embedding layer

### ISSUE THREAD

**Issue by muyinanhai** [deeplearning4j/deeplearning4j#4701]
### keras import error when having a flatten layer 
model

![image](https://user-images.githubusercontent.com/13764547/36586294-30355c20-18bc-11e8-891d-0bcb9795becc.png)

Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Layer flatten_1 could not be mapped to Layer, Vertex, or InputPreProcessor. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraphConfiguration(KerasModel.java:335)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:374)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:363)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:198)
#### Version Information
* 0.9.2-SNAPSHOT
* mac os high sierra

**Comment by maxpumperla** [comment]
@muyinanhai I fixed this for you, see: https://github.com/deeplearning4j/deeplearning4j/pull/4703

btw, next time opening one issue is enough ;) also, would you please consider using a gist for json etc., so we don't clutter the issue? thanks
