### ISSUE TITLE
Illegal concatenation in CpuNDArrayFactory getting single output from yolo9000

### ISSUE THREAD

**Issue by nlebreton** [deeplearning4j/deeplearning4j#4712]
Hi, 

The following exception is thrown while calling outputSingle(..) on a yolo9000 model imported from Keras. The code reproducing this issue can be found on https://gist.github.com/nlebreton/63814df50db15cee36f9f26765f9bfaf. This isssue cannot be reproduced with TinyYolo. I'm using the very last version of dl4j 0.9.2-SNAPSHOT.

Exception in thread "main" java.lang.IllegalArgumentException: Illegal concatenation at array 1 and shape element 3
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.concat(CpuNDArrayFactory.java:682)
	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:5934)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.hstack(BaseNDArrayFactory.java:1212)
	at org.nd4j.linalg.factory.Nd4j.hstack(Nd4j.java:5714)
	at org.deeplearning4j.nn.graph.vertex.impl.MergeVertex.doForward(MergeVertex.java:156)
	at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1675)
	at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1561)
	at org.deeplearning4j.nn.graph.ComputationGraph.silentOutput(ComputationGraph.java:1830)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1890)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1863)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1849)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1767)
	at nlb.ai.deeplearning.dl4j.YoloIssue.main(YoloIssue.java:30)

**Comment by nlebreton** [comment]
MergeVertex has 2 inputs from space_to_depth_x2 and leaky_re_lu_20. Their output shapes are (h=13,w=13,d=256) and (h=13,w=13,d=1024).

**Comment by nlebreton** [comment]
MergeVertex has 2 inputs from space_to_depth_x2 and leaky_re_lu_20. Their output shapes are (h=13,w=13,d=256) and (h=13,w=13,d=1024).

**Comment by maxpumperla** [comment]
@nlebreton I found the root cause for this. Fix inbound

**Comment by maxpumperla** [comment]
@nlebreton let me know if something else happens ;)
