### ISSUE TITLE
computationgraph with mixed CNN and extra indicators

### ISSUE THREAD

**Issue by marioarrigonineri** [deeplearning4j/deeplearning4j#4713]
#### Issue Description

I developed a computationgraph with:
-one image input
-one flat input
-one two classes classification output

when training starts an exception is thrown:
java.lang.UnsupportedOperationException: Cannot use batched operations on entire reader with multiple writables
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritablesBatched(RecordReaderMultiDataSetIterator.java:293)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:267)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:234)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:177)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:102)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:59)
	at org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer.fit(BaseEarlyStoppingTrainer.java:111)

* Deeplearning4j version 0.9.1
* platform information (OS, etc) Windows10 
* CUDA version 8.0
* NVIDIA GTX 1070

**Comment by AlexDBlack** [comment]
OK, so I've finally got this code down to something I can actually run (for future reference, please provide something runnable in isolation).

The relevant code:

```
ImageRecordReader imgReader = new ImageRecordReader(256, 256, 1, new CWPathLabelGenerator());
```
```
        MultiDataSetIterator iterator = new RecordReaderMultiDataSetIterator.Builder(batchSize)
            .addReader("patch", imgReader)
            .addReader("indicators", dataReader)
            .addReader("output", labelReader)
            .addInput("patch")
            .addInput("indicators")
            .addOutput("output").build();
```

Specifically: ```.addInput("patch")```
Javadoc for this addInput method: 
> Set as an input, the entire contents (all columns) of the RecordReader or SequenceRecordReader

In other words, you are basically saying "I want to use the entire contents of the reader - the image INDArray, and the labels (from CWPathLabelGenerator) as the one input feature array to my network". Clearly, you can't (and probably don't want to) concatenate an image and the this label for said image. Based on your network configuration you seem to want to feed this "patch" input into a CNN layer.

To specify the image feature only, you can use .addInput("patch",0,0)... then if you want to feed that "label" in as another separate feature array (to say a dense layer later in the net), you can use .addInput("patch2",1,1) to get the extra "label" subset as a feature.

I'll close this - but feel free to comment in case I've misunderstood what you are trying to achieve here.
