### ISSUE TITLE
 Multiple dex files define Lpl/edu/icm/jlargearrays/LargeArrayUtils$9

### ISSUE THREAD

**Issue by Ngosti2000** [deeplearning4j/deeplearning4j#4718]
Upon building a project in Android i get the following error 

```
Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
Caused by: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:72)
	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Caused by: com.android.dex.DexException: Multiple dex files define Lpl/edu/icm/jlargearrays/LargeArrayUtils$9;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
	... 1 more

* Deeplearning4j version:0.9.2-SNAPSHOT
* platform information (OS, etc):Android mashmallow,

**Comment by treo** [comment]
Dependency on JLargeArrays was introduced through https://github.com/deeplearning4j/DataVec/pull/508

**Comment by Ngosti2000** [comment]
i have excluded the JTransforms module in android and how now compiled successfully... Will this be corrected before next release?

**Comment by saudet** [comment]
Yes, the pull request has been merged. Sorry for the trouble! And thanks for reporting.
