### ISSUE TITLE
 need extra setting in windows8 and eclipse for use jcublas?

### ISSUE THREAD

**Issue by SmokedSalmonSushi** [deeplearning4j/deeplearning4j#474]
o.n.l.j.k.KernelFunctionLoader - outputMessage:
std_strided.cu
 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<init>(JCudaExecutioner.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4256)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4207)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:132)
	at org.deeplearning4j.deepbelief.DBNIrisExample.main(DBNIrisExample.java:49)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Could not create .ptx file: c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(877) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(1850) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(2728) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(3651) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(4595) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(5521) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(6421) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(7314) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(8227) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\device_functions.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\device_functions.h(775) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\device_functions.h(1632) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\device_double_functions.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
Catastrophic error: cannot open source file "C:/windows/TEMP/tmpxft_00001af8_00000000-288_std_strided.cpp1.ii": not a regular file
 
1 catastrophic error detected in the compilation of "C:/windows/TEMP/tmpxft_00001af8_00000000-288_std_strided.cpp1.ii".
Compilation terminated.
 
	at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:67)
	... 10 more
Caused by: java.lang.RuntimeException: java.io.IOException: Could not create .ptx file: c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(877) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(1850) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(2728) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(3651) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(4595) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(5521) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(6421) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(7314) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(8227) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\device_functions.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\device_functions.h(775) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\device_functions.h(1632) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\device_double_functions.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
Catastrophic error: cannot open source file "C:/windows/TEMP/tmpxft_00001af8_00000000-288_std_strided.cpp1.ii": not a regular file
 
1 catastrophic error detected in the compilation of "C:/windows/TEMP/tmpxft_00001af8_00000000-288_std_strided.cpp1.ii".
Compilation terminated.
 
	at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:112)
	at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:65)
	... 10 more
Caused by: java.io.IOException: Could not create .ptx file: c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(877) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(1850) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(2728) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(3651) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(4595) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(5521) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(6421) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(7314) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\math_functions.h(8227) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\device_functions.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\device_functions.h(775) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\device_functions.h(1632) : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
c:\program files\nvidia gpu computing toolkit\cuda\v7.0\include\device_double_functions.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
Catastrophic error: cannot open source file "C:/windows/TEMP/tmpxft_00001af8_00000000-288_std_strided.cpp1.ii": not a regular file
 
1 catastrophic error detected in the compilation of "C:/windows/TEMP/tmpxft_00001af8_00000000-288_std_strided.cpp1.ii".
Compilation terminated.
 
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:282)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:317)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:194)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.load(KernelFunctionLoader.java:160)
	at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:110)
	... 11 more

**Comment by agibsonccc** [comment]
First time I've seen this. We don't have a cuda windows machine, not sure what the issue would be here.

**Comment by agibsonccc** [comment]
Closing due to lack of activity.
