### ISSUE TITLE
InvalidInputTypeException when loading Keras model

### ISSUE THREAD

**Issue by puqugithub** [deeplearning4j/deeplearning4j#4743]
when loading keras model in deeplearning-core 0.9.2-SNAPSHOT, I am getting the following exception: 

org.deeplearning4j.nn.conf.inputs.InvalidInputTypeException: Invalid input: MergeVertex cannot merge activations of different types: first type = FF, input type 2 = RNN. 

Detailed java code, java exception and kears model json/hdf5 are as follows: 

1. Java code
`ComputationGraph computationGraph = KerasModelImport.importKerasModelAndWeights(modelHdf5Filename, false);`

2. Keras model  ("keras_version": "2.1.3")
Both json and hdf5 model are in following attachments 
[model_json_hdf5.zip](https://github.com/deeplearning4j/deeplearning4j/files/1769493/model_json_hdf5.zip)

3. java exceptions
`org.deeplearning4j.nn.conf.inputs.InvalidInputTypeException: Invalid input: MergeVertex cannot merge activations of different types: first type = FF, input type 2 = RNN
	at org.deeplearning4j.nn.conf.graph.MergeVertex.getOutputType(MergeVertex.java:101)
	at org.deeplearning4j.nn.modelimport.keras.layers.core.KerasMerge.getOutputType(KerasMerge.java:137)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.inferOutputTypes(KerasModel.java:262)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:165)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:92)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:123)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:106)`

Could someone provide some suggestions? ;)  thanks~~

@maxpumperla

**Comment by maxpumperla** [comment]
@puqugithub sorry for the delay. so this one is a little tricky to resolve. Let me explain:

The output of a DL4J Embedding layer is 2D by default, in Keras it is 3D. This has been the source of many issues. In general we can map this, since, if your input is of 3D shape, DL4J will automatically process it correctly to spit out 3D _eventually_. But this 2D to 3D processing only takes place if the layer after the embedding layer is another "regular" layer, like an LSTM or Conv1D (in which case DL4J attaches a _preprocessor_ to this next layer to get the input into 3D shape).

What you do here is directly connect it to a Merge layer. In Keras that's no problem, but DL4J doesn't know how to merge 2D embedding output with the other 3D input. I'll keep investigating this and keep you updated. One thing you could try is to add a trivial `Reshape` layer after the `Embedding` layer.

@AlexDBlack Any ideas on this? How would one implement this in plain DL4J, i.e. how to Merge embedding outputs and RNN data. It seems `MergeVertex` does not pick up on input preprocessors / automagic shape inference.

**Comment by maxpumperla** [comment]
@puqugithub that should be fixed now, we introduced a new layer type that mimics keras' embedding layer.
