### ISSUE TITLE
Could not read abnormally long HDF5 attribute (0.9.2-SNAPSHOT)

### ISSUE THREAD

**Issue by blackredscarf** [deeplearning4j/deeplearning4j#4744]
when I import a keras model, 
```
val net: ComputationGraph = KerasModelImport
  .importKerasModelAndWeights("update.h5")
```
throw this error:
```
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Could not read abnormally long HDF5 attribute. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readAttributeAsJson(Hdf5Archive.java:303)
	at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readAttributeAsJson(Hdf5Archive.java:107)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.modelHdf5Filename(KerasModelBuilder.java:90)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:123)
	at pers.zjw.dl4j.snapshot.keras2.InceptionRest$.main(InceptionRest.scala:19)
	at pers.zjw.dl4j.snapshot.keras2.InceptionRest.main(InceptionRest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by raver119** [comment]
Could you please add your .h5 model file as well? Without it it's impossible to tell/do something here.

**Comment by blackredscarf** [comment]
@raver119 
my h5 model: [model](https://drive.google.com/open?id=1PZ_6Zsy1Vb0s0JmjEmVd8FS99zoMCiN1)

**Comment by blackredscarf** [comment]
@raver119 
Do you find the reason?

**Comment by raver119** [comment]
cc @saudet @maxpumperla

**Comment by maxpumperla** [comment]
thanks @raver119, @blackredscarf I know what part throws this error and can have a look starting next week.

**Comment by maxpumperla** [comment]
Summoning @saudet :) this comes from our `Hdf5Archive` here:

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/Hdf5Archive.java#L321-L323

Do you recall why we chose `100` here. It seems @blackredscarf has the problem or luxury of dealing with a very large HDF5 group. @saudet  Any intuition on what a good new upper bound could be?

**Comment by maxpumperla** [comment]
or better yet: an idea how to handle this a little more reliably (or even elegantly)?!

**Comment by saudet** [comment]
Actually that's from @turambar. I guess we can try to increase that to a 1000 maybe? :)

**Comment by maxpumperla** [comment]
haha, good number, good number. I'll test it

**Comment by maxpumperla** [comment]
@blackredscarf I've increased the HDF5 buffer limit, your problem is gone.

but: your model now complains that Lambda layers aren't supported (which is correct, see: #4704 )
