### ISSUE TITLE
Error to update Maven

### ISSUE THREAD

**Issue by bigboca5** [deeplearning4j/deeplearning4j#4750]
Hello.

I have some problems to update the maven reference for my project. To update my project to the last version of DL4J, this return the next error to run mi code:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6185)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	at org.datavec.image.loader.NativeImageLoader.transformImage(NativeImageLoader.java:470)
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:397)
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:211)
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:195)
	at org.datavec.image.recordreader.BaseImageRecordReader.next(BaseImageRecordReader.java:199)
	at org.datavec.image.recordreader.BaseImageRecordReader.nextRecord(BaseImageRecordReader.java:378)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:300)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:393)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:51)
	at testFitCNN2.testFitCNN2.App.main(App.java:55)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
	... 19 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:777)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:739)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.<clinit>(Nd4jCpu.java:63)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:29)
	... 20 more
Caused by: java.lang.UnsatisfiedLinkError: no nd4jcpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:765)
	... 30 more

```

The pom file used in this case is the next:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>testFitCNN2</groupId>
	<artifactId>testFitCNN2</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>testFitCNN2</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-core</artifactId>
			<version>0.9.1</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native-platform</artifactId>
			<version>0.9.1</version>
			
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.5</version>
		</dependency>
	</dependencies>
</project>
```

I read the url returned in the error an another post over this mistake, the solution proposed is add the tag classifier in nd4j reference. I try this, but now a new error in the pom is showed saying 

> Missing artifact org.nd4j:nd4j-native-platform:jar:macosx-x86_64-avx2:0.9.1

The pom dependencies used in this case is:
```
<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-core</artifactId>
			<version>0.9.1</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native-platform</artifactId>
			<version>0.9.1</version>
			<classifier>macosx-x86_64-avx2</classifier>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.5</version>
		</dependency>
	</dependencies>

```

I'm try the DL4J examples from gitHub and the same error is returned

If I change the dependencies to old version as version 0.7.2, the project run fine. The pom dependencies used in this case is:

```
<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-core</artifactId>
			<version>0.7.2</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native-platform</artifactId>
			<version>0.7.2</version>
			
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.5</version>
		</dependency>
	</dependencies>
```

I am using eclipse neon.2 and MacOs hight sierra. 

Any clues of this error.

Thanks so much.
Mario Rivas.

**Comment by AlexDBlack** [comment]
> I'm try the DL4J examples from gitHub and the same error is returned

To confirm: you clone and run the examples (without modification) on your system, and get the exact same error? How are you running the examples - just through Eclipse?

For the examples, I can suggest trying the following (which will help us determine if it's a problem with your computer, or just an IDE or similar issue)
```
mvn package -DskipTests
cd dl4j-examples/target
java -cp dl4j-examples-0.9.1-bin.jar org.deeplearning4j.examples.convolution.LenetMnistExample
```
Let us know if that works, or produces the same error.

One final thing you can try is delete the /.javacpp/cache directory (usually in your user home directory) and try running again.

Note that when using Maven, you should *not* have to manually add the classifiers, like ```<classifier>macosx-x86_64-avx2</classifier>```.

**Comment by bigboca5** [comment]
Hi @AlexDBlack , Thanks a lot for your response.

> To confirm: you clone and run the examples (without modification) on your system, and get the exact same error? How are you running the examples - just through Eclipse?

I run the example on my system without modification. I have clone and import the examples on eclipse using File -> Import -> Existing Maven Project. To continue I go to org.deeplearning4j.examples.convolution -> LenetMnistExample and click in run. The output obtained is:

```
23:22:05,146 INFO  ~ Load data....
23:22:05,153 INFO  ~ Downloading MNIST...
23:22:13,164 INFO  ~ Build model....
23:22:13,224 INFO  ~ Loaded [CpuBackend] backend
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6185)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:777)
	at org.deeplearning4j.examples.convolution.LenetMnistExample.main(LenetMnistExample.java:64)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
	... 11 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:777)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:739)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.<clinit>(Nd4jCpu.java:63)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:29)
	... 12 more
Caused by: java.lang.UnsatisfiedLinkError: no nd4jcpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:765)
	... 22 more
```

I try your recommendation and the result obtained by `mvn package -DskipTests` is:
```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.deeplearning4j:nd4j-examples:jar:0.9.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ org.deeplearning4j:nd4j-examples:[unknown-version], /Users/Mario/Downloads/dl4j-examples-master/nd4j-examples/pom.xml, line 15, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 

….
[ERROR] error reading /Users/Mario/.m2/repository/org/nd4j/nd4j-native/0.9.1/nd4j-native-0.9.1-macosx-x86_64.jar; invalid LOC header (bad signature)
…
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] DeepLearning4j Examples Parent ..................... SUCCESS [  2.421 s]
[INFO] DeepLearning4j Examples ............................ FAILURE [01:15 min]
[INFO] dl4j-spark-examples ................................ SKIPPED
[INFO] dl4j-spark ......................................... SKIPPED
[INFO] datavec-examples ................................... SKIPPED
[INFO] DeepLearning4j CUDA special examples ............... SKIPPED
[INFO] nd4j-examples ...................................... SKIPPED
[INFO] Reinforcement Learning4j Examples .................. SKIPPED
[INFO] lstm-hdfs .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:18 min
[INFO] Finished at: 2018-03-02T23:27:26+01:00
[INFO] Final Memory: 58M/807M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.4.3:shade (default) on project dl4j-examples: Error creating shaded jar: invalid LOC header (bad signature) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dl4j-examples
```

To run `java -cp dl4j-examples-0.9.1-bin.jar org.deeplearning4j.examples.convolution.LenetMnistExample` the output obtained is:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/deeplearning4j/nn/conf/layers/Layer
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.deeplearning4j.nn.conf.layers.Layer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```
Finally, I remove the directory /.javacpp/cache and repeat the process but the result obtained is the same.

Thanks so much.
Mario Rivas.

**Comment by saudet** [comment]
It says  
> [ERROR] error reading /Users/Mario/.m2/repository/org/nd4j/nd4j-native/0.9.1/nd4j-native-0.9.1-macosx-x86_64.jar; invalid LOC header (bad signature)

So you'll need to remove that file and then it should be fine.

**Comment by bigboca5** [comment]
Hi @saudet 

I remove the file and run fine. Now also run fine on Eclipse.

Thanks.
Mario Rivas.
