### ISSUE TITLE
failed to load the googlenews mode in deeplearning4j

### ISSUE THREAD

**Issue by jituumakanta** [deeplearning4j/deeplearning4j#4754]
public static void main(String[] args) throws Exception {

        File gModel = new File("D:/tutorials/mechine learning/GoogleNews-vectors-negative300.bin/GoogleNews-vectors-negative300.bin");
        Word2Vec word2Vec1=WordVectorSerializer.loadGoogleModel(gModel,true);
        //String filePath1 = new ClassPathResource("googlenews.txt").getFile().getAbsolutePath();
        //Word2Vec word2Vec = WordVectorSerializer.readWord2VecModel(filePath1);

        Collection<String> lst = word2Vec1.wordsNearestSum("day", 10);
        System.out.println(lst);
        

    }

i am facing the issue of 
----------------------------------------------------------------------------------------------------
Exception in thread "main" java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(900000000): totalBytes = 1, physicalBytes = 144M
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:76)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:541)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:61)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:255)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1468)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1442)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:247)
	at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:109)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:262)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:5014)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4965)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4093)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readBinaryModel(WordVectorSerializer.java:247)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadGoogleModel(WordVectorSerializer.java:135)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadGoogleModel(WordVectorSerializer.java:113)
	at Word2VecRawTextExample.main(Word2VecRawTextExample.java:35)
Caused by: java.lang.OutOfMemoryError: Failed to allocate memory within limits: totalBytes = 1 + 3G > maxBytes = 1G
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:572)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
	at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
	... 15 more
------------------------------------------------------------------------------------------------------------------

**Comment by saudet** [comment]
Increase memory available to Java either with the -Xmx command line option
or any other means.
