### ISSUE TITLE
NaN Panic with UI

### ISSUE THREAD

**Issue by emmx** [deeplearning4j/deeplearning4j#4791]
There's a bug in the UI stats it seems, I'm getting a NaN panic as shown below. The line in my code is network.train(datasetIterator).

DL4j and ND4j version 0.9.1, Cuda 8.0, OS Debian

```
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: P.A.N.I.C.! Op.Z() contains 1 NaN value(s): 
	at org.nd4j.linalg.api.ops.executioner.OpExecutionerUtil.checkForNaN(OpExecutionerUtil.java:71)
	at org.nd4j.linalg.api.ops.executioner.OpExecutionerUtil.checkForNaN(OpExecutionerUtil.java:109)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.profilingHookOut(DefaultOpExecutioner.java:477)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.invoke(CudaExecutioner.java:1378)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.pushToGrid(CudaGridExecutioner.java:245)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.processAsGridOp(CudaGridExecutioner.java:346)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:112)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:3296)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.naiveExec(CudaExecutioner.java:379)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:609)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:671)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.std(BaseNDArray.java:3969)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.stdNumber(BaseNDArray.java:1127)
	at org.deeplearning4j.ui.stats.BaseStatsListener.calculateSummaryStats(BaseStatsListener.java:731)
	at org.deeplearning4j.ui.stats.BaseStatsListener.iterationDone(BaseStatsListener.java:515)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:90)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:53)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doTruncatedBPTT(MultiLayerNetwork.java:1468)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1227)
	at com.trader.optimizer.model.Model.trainModel(Model.java:385)
        ...
```

**Comment by AlexDBlack** [comment]
Hm, I'm not inclined to call this a bug per-se - NaN panic is *not* enabled by default. It's something you must be enabling yourself manually. And if it's not enabled, things should run fine.

That said, it might be worth looking into more. But I have no way of reproducing this based on the information provided - can you provide more information? What's the network configuration and data being used here?

**Comment by raver119** [comment]
@AlexDBlack i just think we should physically exclude everything that's not training from panics. What would you say, if we'll do that?

**Comment by AlexDBlack** [comment]
> i just think we should physically exclude everything that's not training from panics.

It's certainly an option. Seems like low priority/RoI to me though - given NaN panic is disabled by default, this simply doesn't come up enough to be a problem much in practice... and when it *does* happen outside of training, sometimes you do want it be triggered anyway for debugging.

**Comment by xttam** [comment]
Agree with @raver119. In this case disabling the UI temporarily was enough for me, it wasn't a big deal.

**Comment by AlexDBlack** [comment]
I'm going to close this - it's a pretty uncommon edge case (UI + 0 stdev + NaN panic enabled) - not sure it has high enough ROI to implement and validate a fix for.
