### ISSUE TITLE
How to handle a very high dimensional dataset (~20K columnns)

### ISSUE THREAD

**Issue by rezacsedu** [deeplearning4j/deeplearning4j#4803]
#### Issue Description
Seems DeepLearning4j cannot handle a very high dimensional dataset. For example, I have a cancer genomics dataset having 20532 columns (20531 features, 1 label). When I tried to feet this data into MLP, I encountered the following exception: 

```
18/03/14 12:42:29 ERROR Executor: Exception in task 0.0 in stage 14.0 (TID 98)
java.lang.NullPointerException
	at org.deeplearning4j.spark.impl.multilayer.evaluation.IEvaluationReduceFunction.call(IEvaluationReduceFunction.java:19)
	at org.deeplearning4j.spark.impl.multilayer.evaluation.IEvaluationReduceFunction.call(IEvaluationReduceFunction.java:13)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction2$1.apply(JavaPairRDD.scala:1037)
	at org.apache.spark.util.collection.ExternalAppendOnlyMap$$anonfun$3.apply(ExternalAppendOnlyMap.scala:151)
	at org.apache.spark.util.collection.ExternalAppendOnlyMap$$anonfun$3.apply(ExternalAppendOnlyMap.scala:150)
	at org.apache.spark.util.collection.AppendOnlyMap.changeValue(AppendOnlyMap.scala:150)
	at org.apache.spark.util.collection.SizeTrackingAppendOnlyMap.changeValue(SizeTrackingAppendOnlyMap.scala:32)
	at org.apache.spark.util.collection.ExternalAppendOnlyMap.insertAll(ExternalAppendOnlyMap.scala:163)
	at org.apache.spark.Aggregator.combineCombinersByKey(Aggregator.scala:50)
	at org.apache.spark.shuffle.BlockStoreShuffleReader.read(BlockStoreShuffleReader.scala:84)
	at org.apache.spark.rdd.ShuffledRDD.compute(ShuffledRDD.scala:105)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
62689 [Executor task launch worker for task 98] ERROR org.apache.spark.executor.Executor  - Exception in task 0.0 in stage 14.0 (TID 98)
java.lang.NullPointerException
	at org.deeplearning4j.spark.impl.multilayer.evaluation.IEvaluationReduceFunction.call(IEvaluationReduceFunction.java:19)
	at org.deeplearning4j.spark.impl.multilayer.evaluation.IEvaluationReduceFunction.call(IEvaluationReduceFunction.java:13)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction2$1.apply(JavaPairRDD.scala:1037)
	at org.apache.spark.util.collection.ExternalAppendOnlyMap$$anonfun$3.apply(ExternalAppendOnlyMap.scala:151)
	at org.apache.spark.util.collection.ExternalAppendOnlyMap$$anonfun$3.apply(ExternalAppendOnlyMap.scala:150)
	at org.apache.spark.util.collection.AppendOnlyMap.changeValue(AppendOnlyMap.scala:150)
	at org.apache.spark.util.collection.SizeTrackingAppendOnlyMap.changeValue(SizeTrackingAppendOnlyMap.scala:32)
	at org.apache.spark.util.collection.ExternalAppendOnlyMap.insertAll(ExternalAppendOnlyMap.scala:163)
	at org.apache.spark.Aggregator.combineCombinersByKey(Aggregator.scala:50)
	at org.apache.spark.shuffle.BlockStoreShuffleReader.read(BlockStoreShuffleReader.scala:84)
	at org.apache.spark.rdd.ShuffledRDD.compute(ShuffledRDD.scala:105)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
18/03/14 12:42:29 ERROR Executor: Exception in task 1.0 in stage 14.0 (TID 99)
```

Here's a code segment used in my application: 

```
// ----------------------------------
		// Create network configuration and conduct network training
		MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder().seed(12345)
				.optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT).iterations(1)
				.activation(Activation.LEAKYRELU).weightInit(WeightInit.XAVIER).learningRate(0.1)
				.updater(Updater.NESTEROVS)// To configure: .updater(Nesterovs.builder().momentum(0.9).build())
				.regularization(true).l2(1e-4).list()
				.layer(0, new DenseLayer.Builder().nIn(labelIndex).nOut(128).build())
				.layer(1, new DenseLayer.Builder().nIn(128).nOut(64).build())
				.layer(2,
						new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
								.activation(Activation.SOFTMAX).nIn(64).nOut(numClasses).build())
				.pretrain(false).backprop(true).build();

		// Configuration for Spark training: see http://deeplearning4j.org/spark for
		// explanation of these configuration options
		int examplesPerDataSetObject = 1;
		ParameterAveragingTrainingMaster  tm = new ParameterAveragingTrainingMaster
				.Builder(examplesPerDataSetObject) 
				.averagingFrequency(3)
				.workerPrefetchNumBatches(2) // Async prefetching: 2 examples per worker
				.batchSizePerWorker(batchSizePerWorker)
				.build();
		// Create the Spark network
		SparkDl4jMultiLayer sparkNet = new SparkDl4jMultiLayer(sc, conf, tm);
		//sparkNet.setListeners(Collections.<IterationListener>singletonList(new ScoreIterationListener(1)));

		// Execute training:
		for (int i = 0; i < numEpochs; i++) {
			sparkNet.fit(trainData);
			log.info("Completed Epoch {}", i);
		}			
			 Evaluation eval = sparkNet.evaluate(testData);
		        log.info("Eval stats BEFORE fit.....");
		        log.info(eval.stats()+"\n");
		        testDataIt.reset();

		// Perform evaluation (distributed)
		// Evaluation evaluation = sparkNet.evaluate(testData);
		Evaluation evaluation = sparkNet.doEvaluation(testData, 128, new Evaluation(numClasses))[0]; // Work-around for
																
```											
Am I doing something wrong? Any help or pointer would be appreciated. 

#### Version Information
* Deeplearning4j version: 0.9.1
* DL4j version: 0.9.1
* platform information (OS, etc): Windows 10 and Ubuntu 16.04 LTS 64-bit
* Scala binary version: 2.12.2
* Java (JDK): 1.8.0_162 (64-bit)
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

**Comment by rezacsedu** [comment]
@treo Well, I changed the issue title to avoid further confusion. It works for low dimension. Say when I randomly pick 100 columns out of the original input, it works perfectly.

**Comment by treo** [comment]
The linked bug report also contains a way to work around that problem, as the bugfix is only available on SNAPSHOT versions at the moment. So you should try that first.

In general DL4J can easily handle high dimensional data, as long as you have enough memory for it. I've used more than 200k columns as input vectors, and there isn't anything special that you have to do there.

**Comment by rezacsedu** [comment]
@treo, yes my machine has enough computing power (64GB RAM, 16 CPU cores etc.). Thanks, I will definitely try with the SNAPSHOT version.
