### ISSUE TITLE
DL4J Spark training: handle corrupted datasets due to flaky HDFS etc

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4805]
Looking at the logs for a client's code: they are running into issues where DataSet loading on spark is failing.

```
java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.nd4j.linalg.dataset.DataSet.load(DataSet.java:391)
```

Running hypothesis is that an executor crashes and/or flaky HDFS writing during preprocessing is lead to a small number of incomplete/corrupted DataSets.

It would be nice to be able to handle a small number of DataSet loading errors during network training, rather than propagating an exception back out and (with sufficient task failures) potentially crashing an executor...

**Comment by AlexDBlack** [comment]
On reflection: I've decided to simply improve the errors and refer users to the newly added Spark data validation: https://github.com/deeplearning4j/deeplearning4j/pull/4808
