### ISSUE TITLE
"java.util.zip.ZipException: zip file is empty" exception when loading normalizer from stream

### ISSUE THREAD

**Issue by svkap** [deeplearning4j/deeplearning4j#4825]
#### Issue Description

Loading normalizer from file works ok but loading normalizer from stream throws the following exception (loading model from stream works as well):

`		Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: zip file is empty
			at org.deeplearning4j.util.ModelSerializer.restoreNormalizerFromFileDeprecated(ModelSerializer.java:663)
			at org.deeplearning4j.util.ModelSerializer.restoreNormalizerFromFile(ModelSerializer.java:611)
			at org.deeplearning4j.util.ModelSerializer.restoreNormalizerFromInputStream(ModelSerializer.java:634)
			at com.goodlight.forex.brain.test.SimpleRNNRecordReaderTest.loadModel(SimpleRNNRecordReaderTest.java:208)
			at com.goodlight.forex.brain.test.SimpleRNNRecordReaderTest.main(SimpleRNNRecordReaderTest.java:164)
		Caused by: java.util.zip.ZipException: zip file is empty
			at java.util.zip.ZipFile.open(Native Method)
			at java.util.zip.ZipFile.<init>(ZipFile.java:225)
			at java.util.zip.ZipFile.<init>(ZipFile.java:155)
			at java.util.zip.ZipFile.<init>(ZipFile.java:169)
			at org.deeplearning4j.util.ModelSerializer.restoreNormalizerFromFileDeprecated(ModelSerializer.java:646)
			... 4 more`

You can find sample code here: https://gist.github.com/svkap/566da5b82e7cc0fd627db57ece8ef636
Please comment out lines 120 and 136 because Evaluation throws exception also.

#### Version Information

* Deeplearning4j 0.9.1
* platform information - Ubuntu 16.04
* CUDA version - no CUDA

**Comment by AlexDBlack** [comment]
OK, so here's what's going on:
```
            this.net = ModelSerializer.restoreComputationGraph(stream);
            this.normalizer = ModelSerializer.restoreNormalizerFromInputStream(stream);
```

We can't read a zip file directly from a stream - so we copy it entirely to a temp file, then read from the temp file.
Input streams can't in general be reset (the .reset() method doesn't count), so it's in practice only possible to read from them once. The restore method closes the stream.
When you try to restore the normalizer, it *should* give you an exception when it tries to read from the closed stream; instead, it just creates an empty file and copies nothing to it (0 bytes available). Hence the exception you are getting.

Here's what I'll do:
1. Improve the javadoc to clarify behaviour when loading from streams
2. Add checks for the closed stream and "no data available from stream" cases
3. Add some "restore model and normalizer" methods

Workarounds for you:
1. Use the file methods, not the stream methods
2. If you want to use the stream methods, create a new stream for each restore call

**Comment by AlexDBlack** [comment]
Given the explaination given above, and the updates in the following PR - I'm closing this.
https://github.com/deeplearning4j/deeplearning4j/pull/4827
