### ISSUE TITLE
Build error is occurred when building deeplearning4j-nlp

### ISSUE THREAD

**Issue by ckddyd777** [deeplearning4j/deeplearning4j#484]
Hi,
Thanks for #467 
But, I faced error again when build deeplearning4j.
I've try to fix the RNTN.java file, but I don't know why it does not work.

Error message as below:

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/chhome/deeplearning/deeplearning4j/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/rntn/RNTN.java:[82,8] org.deeplearning4j.models.rntn.RNTN is not abstract and does not override abstract method l1Magnitude() in org.deeplearning4j.nn.api.Layer
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] deeplearning4j-nlp ................................ FAILURE [4.643s]
[INFO] DeepLearning4j-AWS ................................ SKIPPED
[INFO] hadoop-yarn ....................................... SKIPPED
[INFO] cdh4 .............................................. SKIPPED
[INFO] deeplearning4j-nlp-yarn ........................... SKIPPED
[INFO] org.deeplearning4j.spark .......................... SKIPPED
[INFO] dl4j-spark ........................................ SKIPPED
[INFO] dl4j-spark-nlp .................................... SKIPPED
[INFO] dl4j-spark-ml ..................................... SKIPPED
[INFO] deeplearning4j-cli ................................ SKIPPED
[INFO] deeplearning4j-cli-api ............................ SKIPPED
[INFO] deeplearning4j-ui ................................. SKIPPED
[INFO] dl4j-caffe ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.178s
[INFO] Finished at: Mon Jul 20 08:51:24 KST 2015
[INFO] Final Memory: 35M/506M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project deeplearning4j-nlp: Compilation failure
[ERROR] /home/chhome/deeplearning/deeplearning4j/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/rntn/RNTN.java:[82,8] org.deeplearning4j.models.rntn.RNTN is not abstract and does not override abstract method l1Magnitude() in org.deeplearning4j.nn.api.Layer
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project deeplearning4j-nlp: Compilation failure
/home/chhome/deeplearning/deeplearning4j/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/rntn/RNTN.java:[82,8] org.deeplearning4j.models.rntn.RNTN is not abstract and does not override abstract method l1Magnitude() in org.deeplearning4j.nn.api.Layer

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/home/chhome/deeplearning/deeplearning4j/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/rntn/RNTN.java:[82,8] org.deeplearning4j.models.rntn.RNTN is not abstract and does not override abstract method l1Magnitude() in org.deeplearning4j.nn.api.Layer

        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:858)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by agibsonccc** [comment]
Fixed.
