### ISSUE TITLE
Resource 'TicTacToe' cannot be found.

### ISSUE THREAD

**Issue by rodentooth** [deeplearning4j/deeplearning4j#4854]
Running the TicTacToe example doesn't work out of the box. It gives me the following error:

```
FilePathExceptionjava.lang.IllegalStateException: Resource 'TicTacToe' cannot be found.
Exception in thread "Thread-1" java.lang.IllegalMonitorStateException
java.io.FileNotFoundException: 
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at org.deeplearning4j.examples.tictactoe.TicTacToePlayer.readStateAndRewardFromFile(TicTacToePlayer.java:312)
	at org.deeplearning4j.examples.tictactoe.TicTacToePlayer.run(TicTacToePlayer.java:60)
	at java.lang.Thread.run(Thread.java:748)

Process finished with exit code 0

```

**Comment by saraswat40** [comment]
Hello,

I have a patch here. Can you give it a try? 

Thanks

diff --git a/dl4j-examples/src/main/java/org/deeplearning4j/examples/tictactoe/PlayTicTacToe.java b/dl4j-examples/src/main/java/org/deeplearning4j/examples/tictactoe/PlayTicTacToe.java
index a3a5945..9c223d7 100644
--- a/dl4j-examples/src/main/java/org/deeplearning4j/examples/tictactoe/PlayTicTacToe.java
+++ b/dl4j-examples/src/main/java/org/deeplearning4j/examples/tictactoe/PlayTicTacToe.java
@@ -36,7 +36,7 @@ public class PlayTicTacToe extends JFrame {
     public PlayTicTacToe() throws HeadlessException {
         String filePath = "";
         try {
-            filePath = new ClassPathResource("TicTacToe").getFile().getAbsolutePath() + File.separator + "AllMoveWithReward.txt";
+            filePath = new ClassPathResource("AllMoveWithReward.txt").getFile().getAbsolutePath();
         } catch (Exception e) {
             System.out.println("FilePathException" + e.toString());
         }
diff --git a/dl4j-examples/src/main/java/org/deeplearning4j/examples/tictactoe/TicTacToeData.java b/dl4j-examples/src/main/java/org/deeplearning4j/examples/tictactoe/TicTacToeData.java
index b52b69e..d589764 100644
--- a/dl4j-examples/src/main/java/org/deeplearning4j/examples/tictactoe/TicTacToeData.java
+++ b/dl4j-examples/src/main/java/org/deeplearning4j/examples/tictactoe/TicTacToeData.java
@@ -44,8 +44,8 @@ public class TicTacToeData {
      */
     public static void main(String[] args) throws Exception {
 
-        String filePath = new ClassPathResource("TicTacToe").getFile().getAbsolutePath() + File.separator + "AllMoveWithReward.txt";
-
+        String filePath = new ClassPathResource("AllMoveWithReward.txt").getFile().getAbsolutePath();
+        
         TicTacToeData data = new TicTacToeData();
 
 
diff --git a/dl4j-examples/src/main/resources/AllMoveWithReward.txt b/dl4j-examples/src/main/resources/AllMoveWithReward.txt
index e69de29..0519ecb 100644
--- a/dl4j-examples/src/main/resources/AllMoveWithReward.txt
+++ b/dl4j-examples/src/main/resources/AllMoveWithReward.txt
@@ -0,0 +1 @@
+ 
\ No newline at end of file

**Comment by saraswat40** [comment]
You will also need to run TicTacToeData to generate AllMoveWithReward.txt before running PlayTicTacToe

**Comment by saudet** [comment]
@saraswat40 Please send your patch with a pull request! Thanks
