### ISSUE TITLE
SeparableConvolution2D execution fails with CuDNN

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4862]
Running the following gradient check with CuDNN results in an exception:

https://github.com/deeplearning4j/deeplearning4j/blob/8128ef586ba7bcf717dbcb1923725be3161ef317/deeplearning4j-core/src/test/java/org/deeplearning4j/gradientcheck/CNNGradientCheckTest.java#L908-L981

```
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
o.n.n.Nd4jBlas - Number of threads used for BLAS: 0
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [7.1GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.o.e.CudaExecutioner - Device opName: [TITAN X (Pascal)]; CC: [6.1]; Total/free memory: [12884901888]
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: SEPARATE; inference: SEPARATE]
o.d.n.l.c.ConvolutionLayer - CudnnConvolutionHelper successfully initialized
nParams, layer 0: 29
nParams, layer 1: 258
 - mb=1, k=1, s=1, d=1, cm=Truncate
o.d.g.GradientCheckUtil - Setting softmax clipping epsilon to 0.0 for class org.nd4j.linalg.lossfunctions.impl.LossMCXENT loss function to avoid spurious gradient check failures

java.lang.IllegalStateException: Invalid input array: expected shape [minibatch, channels, height, width] = [minibatch, 2, 8, 8] - got [1, 3, 8, 8]

	at org.deeplearning4j.nn.conf.preprocessor.CnnToFeedForwardPreProcessor.preProcess(CnnToFeedForwardPreProcessor.java:88)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2404)
	at org.deeplearning4j.gradientcheck.GradientCheckUtil.checkGradients(GradientCheckUtil.java:186)
	at org.deeplearning4j.gradientcheck.GradientCheckUtil.checkGradients(GradientCheckUtil.java:117)
	at org.deeplearning4j.gradientcheck.GradientCheckUtil.checkGradients(GradientCheckUtil.java:111)
	at org.deeplearning4j.gradientcheck.CNNGradientCheckTest.testSeparableConv2D(CNNGradientCheckTest.java:974)
```

**Comment by vascokk** [comment]
Related to this issue, I guess - the number of output channels from SeparableConvolution2D is equal to the depthMultiplier, instead the nOut value, which is not the supposed behavior.
