### ISSUE TITLE
Problems with readWord2Vec in Google App Engine

### ISSUE THREAD

**Issue by jasonsian** [deeplearning4j/deeplearning4j#4894]
Hi,

I had currently moved our environment to Google App Engine but faced issue while calling the method readParagraphVectors in org.deeplearning4j.models.embeddings.loader.WordVectorSerializer. I would really need some advice on what may go wrong as this piece of code is running perfectly fine in our local environment. You can see my error message below:
```

java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2Vec(WordVectorSerializer.java:882) ~[deeplearning4j-nlp-0.8.0.jar!/:na] 
at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readParagraphVectors(WordVectorSerializer.java:829) ~[deeplearning4j-nlp-0.8.0.jar!/:na] 
at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readParagraphVectors(WordVectorSerializer.java:986) ~[deeplearning4j-nlp-0.8.0.jar!/:na]  
```

The piece of code at line 882 is as below:
```

 public static Word2Vec readWord2Vec(File file) throws IOException {
        File tmpFileSyn0 = File.createTempFile("word2vec", "0");
        File tmpFileSyn1 = File.createTempFile("word2vec", "1");
        File tmpFileC = File.createTempFile("word2vec", "c");
        File tmpFileH = File.createTempFile("word2vec", "h");
        File tmpFileF = File.createTempFile("word2vec", "f");

        tmpFileSyn0.deleteOnExit();
        tmpFileSyn1.deleteOnExit();
        tmpFileH.deleteOnExit();
        tmpFileC.deleteOnExit();
        tmpFileF.deleteOnExit();

        int originalFreq = Nd4j.getMemoryManager().getOccasionalGcFrequency(); //This is line 882
        boolean originalPeriodic = Nd4j.getMemoryManager().isPeriodicGcActive();

        if (originalPeriodic)
            Nd4j.getMemoryManager().togglePeriodicGc(false);

        Nd4j.getMemoryManager().setOccasionalGcFrequency(50000);

        try {


            ZipFile zipFile = new ZipFile(file);
            ZipEntry syn0 = zipFile.getEntry("syn0.txt");
            InputStream stream = zipFile.getInputStream(syn0);

            Files.copy(stream, Paths.get(tmpFileSyn0.getAbsolutePath()), StandardCopyOption.REPLACE_EXISTING);

            ZipEntry syn1 = zipFile.getEntry("syn1.txt");
            stream = zipFile.getInputStream(syn1);

            Files.copy(stream, Paths.get(tmpFileSyn1.getAbsolutePath()), StandardCopyOption.REPLACE_EXISTING);

            ZipEntry codes = zipFile.getEntry("codes.txt");
            stream = zipFile.getInputStream(codes);

            Files.copy(stream, Paths.get(tmpFileC.getAbsolutePath()), StandardCopyOption.REPLACE_EXISTING);

            ZipEntry huffman = zipFile.getEntry("huffman.txt");
            stream = zipFile.getInputStream(huffman);

            Files.copy(stream, Paths.get(tmpFileH.getAbsolutePath()), StandardCopyOption.REPLACE_EXISTING);

            ZipEntry config = zipFile.getEntry("config.json");
            stream = zipFile.getInputStream(config);
            StringBuilder builder = new StringBuilder();
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(stream))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    builder.append(line);
                }
            }

            VectorsConfiguration configuration = VectorsConfiguration.fromJson(builder.toString().trim());

            // we read first 4 files as w2v model
            Word2Vec w2v = readWord2VecFromText(tmpFileSyn0, tmpFileSyn1, tmpFileC, tmpFileH, configuration);

            // we read frequencies from frequencies.txt, however it's possible that we might not have this file
            ZipEntry frequencies = zipFile.getEntry("frequencies.txt");
            if (frequencies != null) {
                stream = zipFile.getInputStream(frequencies);
                try (BufferedReader reader = new BufferedReader(new InputStreamReader(stream))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        String[] split = line.split(" ");
                        VocabWord word = w2v.getVocab().tokenFor(decodeB64(split[0]));
                        word.setElementFrequency((long) Double.parseDouble(split[1]));
                        word.setSequencesCount((long) Double.parseDouble(split[2]));
                    }
                }
            }


            ZipEntry zsyn1Neg = zipFile.getEntry("syn1Neg.txt");
            if (zsyn1Neg != null) {
                stream = zipFile.getInputStream(zsyn1Neg);

                try (InputStreamReader isr = new InputStreamReader(stream); BufferedReader reader = new BufferedReader(isr)) {
                    String line = null;
                    List<INDArray> rows = new ArrayList<>();
                    while ((line = reader.readLine()) != null) {
                        String[] split = line.split(" ");
                        double array[] = new double[split.length];
                        for (int i = 0; i < split.length; i++) {
                            array[i] = Double.parseDouble(split[i]);
                        }
                        rows.add(Nd4j.create(array));
                    }

                    // it's possible to have full model without syn1Neg
                    if (rows.size() > 0) {
                        INDArray syn1Neg = Nd4j.vstack(rows);
                        ((InMemoryLookupTable) w2v.getLookupTable()).setSyn1Neg(syn1Neg);
                    }
                }
            }

            return w2v;
        } finally {
            if (originalPeriodic)
                Nd4j.getMemoryManager().togglePeriodicGc(true);

            Nd4j.getMemoryManager().setOccasionalGcFrequency(originalFreq);
        }
    }

```

Below is my pom.xml file.
```

	<properties>
		<nd4j.backend>nd4j-native-platform</nd4j.backend>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<shadedClassifier>bin</shadedClassifier>


		<java.version>1.8</java.version>
		<nd4j.version>0.8.0</nd4j.version>
		<dl4j.version>0.8.0</dl4j.version>
		<datavec.version>0.8.0</datavec.version>
		<arbiter.version>0.8.0</arbiter.version>
		<rl4j.version>0.8.0</rl4j.version>

		<dl4j.spark.version>0.8.0_spark_1</dl4j.spark.version>
		<datavec.spark.version>0.8.0_spark_1</datavec.spark.version>
		<scala.binary.version>2.11</scala.binary.version>

		<guava.version>19.0</guava.version>
		<logback.version>1.1.7</logback.version>
		<jfreechart.version>1.0.13</jfreechart.version>
		<jcommon.version>1.0.23</jcommon.version>
		<maven-shade-plugin.version>2.4.3</maven-shade-plugin.version>
		<maven-compiler-plugin.version>3.6.1</maven-compiler-plugin.version>
		<exec-maven-plugin.version>1.4.0</exec-maven-plugin.version>
		<maven.minimum.version>3.3.1</maven.minimum.version>
		<javafx.version>2.2.3</javafx.version>
		<aws.sdk.version>1.11.109</aws.sdk.version>
		<jackson.version>2.6.6</jackson.version>
		<scala.plugin.version>3.2.2</scala.plugin.version>
		<appengine.target.version>[1.8.9,2.0)</appengine.target.version>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.nd4j</groupId>
				<artifactId>nd4j-native-platform</artifactId>
				<version>${nd4j.version}</version>
			</dependency>
			<dependency>
				<groupId>org.nd4j</groupId>
				<artifactId>nd4j-cuda-7.5-platform</artifactId>
				<version>${nd4j.version}</version>
			</dependency>
			<dependency>
				<groupId>org.nd4j</groupId>
				<artifactId>nd4j-cuda-8.0-platform</artifactId>
				<version>${nd4j.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>${nd4j.backend}</artifactId>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-core</artifactId>
			<version>${dl4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-nlp</artifactId>
			<version>${dl4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-ui_${scala.binary.version}</artifactId>
			<version>${dl4j.version}</version>
		</dependency>
	</dependencies>


```

It would be great if anyone can shed some light on how we can debug the problem. Thanks in advance.

**Comment by raver119** [comment]
1) Please upgrade to 0.9.1 version for nd4j/dl4j/datavec
2) Please show full exception after that, if you'll still have it.

**Comment by jasonsian** [comment]
Hi Raver,

Thanks for the reply. After updrading the version from 0.8 to 0.9.1. I'm still hitting the same error.

`java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2Vec(WordVectorSerializer.java:878) ~[deeplearning4j-nlp-0.9.1.jar!/:na] at 
org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readParagraphVectors(WordVectorSerializer.java:825) ~[deeplearning4j-nlp-0.9.1.jar!/:na] at 
org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readParagraphVectors(WordVectorSerializer.java:983) ~[deeplearning4j-nlp-0.9.1.jar!/:na]`

I might have limited log access to Google App Engine hence that's all I can see from the logging. Is there any recommendation on how to get more detailed logs? I had tried a few methods but still failed to get it work. Thanks in advance.

**Comment by jasonsian** [comment]
An update to the problem. After going through the detailed logs, I had traced this below error. This happens every time after a new deployment/restart, After hitting this error, the following errors will be the NoClassDefFoundError which I had mentioned earlier.

`java.nio.channels.OverlappingFileLockException: null at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255) ~[na:1.8.0_131] 
at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152) ~[na:1.8.0_131] 
at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1063) ~[na:1.8.0_131] 
at java.nio.channels.FileChannel.lock(FileChannel.java:1053) ~[na:1.8.0_131] 
at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:429) ~[javacpp-1.3.3.jar!/:1.3.3] 
at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:944) ~[javacpp-1.3.3.jar!/:1.3.3] 
at org.bytedeco.javacpp.Loader.load(Loader.java:765) ~[javacpp-1.3.3.jar!/:1.3.3] 
at org.bytedeco.javacpp.Loader.load(Loader.java:684) ~[javacpp-1.3.3.jar!/:1.3.3] 
at org.bytedeco.javacpp.openblas.<clinit>(openblas.java:10) ~[openblas-0.2.19-1.3.jar!/:1.3.3] 
at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.setMaxThreads(CpuBlas.java:117) ~[nd4j-native-0.9.1.jar!/:na] 
at org.nd4j.nativeblas.Nd4jBlas.<init>(Nd4jBlas.java:35) ~[nd4j-native-api-0.9.1.jar!/:na] 
at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.<init>(CpuBlas.java:12) ~[nd4j-native-0.9.1.jar!/:na] 
at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createBlas(CpuNDArrayFactory.java:89) ~[nd4j-native-0.9.1.jar!/:na] at org.nd4j.linalg.factory.BaseNDArrayFactory.blas(BaseNDArrayFactory.java:67) ~[nd4j-api-0.9.1.jar!/:0.9.1] 
at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.getEnvironmentInformation(NativeOpExecutioner.java:1176) ~[nd4j-native-0.9.1.jar!/:na] 
at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.printEnvironmentInformation(DefaultOpExecutioner.java:562) ~[nd4j-api-0.9.1.jar!/:0.9.1] 
at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6210) ~[nd4j-api-0.9.1.jar!/:0.9.1] 
at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087) ~[nd4j-api-0.9.1.jar!/:0.9.1] 
at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201) ~[nd4j-api-0.9.1.jar!/:0.9.1]`

I'm not sure whether this is the root cause of the problem but I'm just hoping the more information I provide the easier anyone can provide me with some help/suggestions. Thanks.
