### ISSUE TITLE
Keras import: shape issue with Embedding layer

### ISSUE THREAD

**Issue by fincken** [deeplearning4j/deeplearning4j#4899]
Hi.

I've got a model trained in keras that I'd like to use in DL4J, but I'm getting this error message when trying to import:
`Exception in thread "main" java.lang.IllegalStateException: Mis matched lengths: [4096] != [385024] - Array 1 shape: [32, 128], array 2 shape: [3008, 128]
	at org.nd4j.linalg.util.LinAlgExceptions.assertSameLength(LinAlgExceptions.java:42)
	at org.nd4j.linalg.api.ops.BaseTransformOp.<init>(BaseTransformOp.java:174)
	at org.nd4j.linalg.api.ops.impl.transforms.Set.<init>(Set.java:43)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:1274)
	at org.deeplearning4j.nn.layers.BaseLayer.setParam(BaseLayer.java:204)
	at org.deeplearning4j.nn.modelimport.keras.KerasLayer.copyWeightsToLayer(KerasLayer.java:296)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.copyWeightsToModel(KerasModelUtils.java:76)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:228)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:215)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:142)
	at test.KerasImportTestClass.main(KerasImportTestClass.java:12)`

[Here's the model](https://gist.github.com/fincken/b1dbae489bed2e6fbf5d90aedbfc3cf8)

The code running is just the import statement:
[GIST](https://gist.github.com/fincken/76cfc73d0edc3cb9f58fc7189840fa7c)

I'm running the most recent 1.0.0-alpha build of dl4j.

**Comment by maxpumperla** [comment]
@fincken thanks for reporting this. that is due to improper handling of the `input_length` argument for keras embedding layers upon import. this causes the shape mismatch

4096 != 4096 * 94 and 32 != 32 * 94 when setting weights for the imported layer.

Thanks for providing the model as well, should make for a good unit test. I'll let you know about progress on this.

**Comment by fincken** [comment]
I tried doing the embedding beforehand, turning the input into (20,100) shapes. It still failes to load even without the Embedding layer, so there might be an improper handling on several layertypes.

`Exception in thread "main" java.lang.IllegalStateException: Mis matched lengths: [4096] != [57344] - Array 1 shape: [32, 128], array 2 shape: [448, 128]
	at org.nd4j.linalg.util.LinAlgExceptions.assertSameLength(LinAlgExceptions.java:42)
	at org.nd4j.linalg.api.ops.BaseTransformOp.<init>(BaseTransformOp.java:174)
	at org.nd4j.linalg.api.ops.impl.transforms.Set.<init>(Set.java:43)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:1274)
	at org.deeplearning4j.nn.layers.BaseLayer.setParam(BaseLayer.java:204)
	at org.deeplearning4j.nn.modelimport.keras.KerasLayer.copyWeightsToLayer(KerasLayer.java:296)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.copyWeightsToModel(KerasModelUtils.java:76)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:228)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:215)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:142)
	at test.KerasImportTestClass.main(KerasImportTestClass.java:12)`

current model that fails supplied here:
[GIST](https://gist.github.com/fincken/28116f33f37ac630848774bcaf8a12ab)

**Comment by maxpumperla** [comment]
@fincken yes, handling reshaping properly is a bit tricky. If you don't mind I open another ticket for the non-embedding case and rename this slightly. I don't want to mix too many things in one issue, otherwise we risk forgetting about a case. thanks.

**Comment by maxpumperla** [comment]
I've addressed this on master. There's a unit test that uses the exact same model you provided:

https://github.com/deeplearning4j/deeplearning4j/blob/4f2079cfcc86dd5b74a9cfcf0ea022691969a471/deeplearning4j-modelimport/src/test/java/org/deeplearning4j/nn/modelimport/keras/weights/KerasWeightSettingTests.java#L52-L56
