### ISSUE TITLE
vgg16 import as a single file

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/deeplearning4j#4916]
Issue originally came from a skil ce use who wanted to import vgg16.

The original poster was following this gist:
https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3

In skil ce we only allow one file for import so it has to be the combined model config+weights in the same file. I generated that by writing out model.save after the model.compile line in the gist above.
Here is the link to the model I wrote out uploaded to gdrive:

https://drive.google.com/file/d/1oCMD50eF99djU9ZzLNRBd79ni8XbFbj0/view?usp=sharing

This model loads in keras 1.2.0 and gives me predictions. But errors out in dl4j with the following:

```
14:39:42,205 INFO  ~ Unexpected end-of-input: was expecting closing '"' for name
 at [Source: {"class_name": "Sequential", "config": [{"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "batch_input_shape": [null, 3, 224, 224], "trainable": true, "name": "zeropadding2d_1", "input_dtype": "float32"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_1", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 64, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_2"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_2", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 64, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "MaxPooling2D", "config": {"name": "maxpooling2d_1", "trainable": true, "dim_ordering": "th", "pool_size": [2, 2], "strides": [2, 2], "border_mode": "valid"}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_3"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_3", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 128, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_4"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_4", "activity_reg; line: 1, column: 4001]
14:39:42,208 INFO  ~ Unexpected end-of-input within/between OBJECT entries
 at [Source: {"class_name": "Sequential", "config": [{"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "batch_input_shape": [null, 3, 224, 224], "trainable": true, "name": "zeropadding2d_1", "input_dtype": "float32"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_1", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 64, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_2"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_2", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 64, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "MaxPooling2D", "config": {"name": "maxpooling2d_1", "trainable": true, "dim_ordering": "th", "pool_size": [2, 2], "strides": [2, 2], "border_mode": "valid"}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_3"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_3", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 128, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_4"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_4", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 128, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "MaxPooling2D", "config": {"name": "maxpooling2d_2", "trainable": true, "dim_ordering": "th", "pool_size": [2, 2], "strides": [2, 2], "border_mode": "valid"}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_5"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_5", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 256, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_6"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_6", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 256, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_7"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_7", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 256, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "MaxPooling2D", "config": {"name": "maxpooling2d_3", "trainable": true,; line: 1, column: 8001]
14:39:42,211 INFO  ~ Unrecognized token 'nu': was expecting 'null', 'true', 'false' or NaN
 at [Source: {"class_name": "Sequential", "config": [{"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "batch_input_shape": [null, 3, 224, 224], "trainable": true, "name": "zeropadding2d_1", "input_dtype": "float32"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_1", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 64, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_2"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_2", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 64, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "MaxPooling2D", "config": {"name": "maxpooling2d_1", "trainable": true, "dim_ordering": "th", "pool_size": [2, 2], "strides": [2, 2], "border_mode": "valid"}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_3"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_3", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 128, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_4"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_4", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 128, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "MaxPooling2D", "config": {"name": "maxpooling2d_2", "trainable": true, "dim_ordering": "th", "pool_size": [2, 2], "strides": [2, 2], "border_mode": "valid"}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_5"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_5", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 256, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_6"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_6", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 256, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_7"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_7", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 256, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "MaxPooling2D", "config": {"name": "maxpooling2d_3", "trainable": true, "dim_ordering": "th", "pool_size": [2, 2], "strides": [2, 2], "border_mode": "valid"}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_8"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_8", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 512, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_9"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_9", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 512, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_10"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_10", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 512, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "MaxPooling2D", "config": {"name": "maxpooling2d_4", "trainable": true, "dim_ordering": "th", "pool_size": [2, 2], "strides": [2, 2], "border_mode": "valid"}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_11"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_11", "activity_regularizer": nu; line: 1, column: 18001]
14:39:42,216 INFO  ~ Unexpected end-of-input: was expecting closing '"' for name
 at [Source: {"class_name": "Sequential", "config": [{"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "batch_input_shape": [null, 3, 224, 224], "trainable": true, "name": "zeropadding2d_1", "input_dtype": "float32"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_1", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 64, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_2"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_2", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 64, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "MaxPooling2D", "config": {"name": "maxpooling2d_1", "trainable": true, "dim_ordering": "th", "pool_size": [2, 2], "strides": [2, 2], "border_mode": "valid"}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_3"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_3", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 128, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_4"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_4", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 128, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "MaxPooling2D", "config": {"name": "maxpooling2d_2", "trainable": true, "dim_ordering": "th", "pool_size": [2, 2], "strides": [2, 2], "border_mode": "valid"}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_5"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_5", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 256, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_6"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_6", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 256, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_7"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_7", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 256, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "MaxPooling2D", "config": {"name": "maxpooling2d_3", "trainable": true, "dim_ordering": "th", "pool_size": [2, 2], "strides": [2, 2], "border_mode": "valid"}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_8"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_8", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 512, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_9"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_9", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 512, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_10"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_10", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 512, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "MaxPooling2D", "config": {"name": "maxpooling2d_4", "trainable": true, "dim_ordering": "th", "pool_size": [2, 2], "strides": [2, 2], "border_mode": "valid"}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_11"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_11", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 512, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_12"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_12", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 512, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "ZeroPadding2D", "config": {"padding": [1, 1], "trainable": true, "name": "zeropadding2d_13"}}, {"class_name": "Convolution2D", "config": {"W_constraint": null, "b_constraint": null, "name": "convolution2d_13", "activity_regularizer": null, "trainable": true, "dim_ordering": "th", "nb_col": 3, "subsample": [1, 1], "init": "glorot_uniform", "bias": true, "nb_filter": 512, "border_mode": "valid", "b_regularizer": null, "W_regularizer": null, "activation": "relu", "nb_row": 3}}, {"class_name": "MaxPooling2D", "config": {"name": "maxpooling2d_5", "trainable": true, "dim_ordering": "th", "pool_size": [2, 2], "strides": [2, 2], "border_mode": "valid"}}, {"class_name": "Flatten", "config": {"trainable": true, "name": "flatten_1"}}, {"class_name": "Dense", "config": {"W_constraint": null, "b_constraint": null, "name": "dense_1", "output_dim": 4096, "activity_regularizer": null, "trainable": true, "init": "glorot_uniform", "bias": true, "input_dtype": "float32", "input_dim": 25088, "b_regularizer": null, "W_regularizer": null, "activation": "relu", "batch_input_shape": [null, 25088]}}, {"class_name": "Dropout", "config": {"p": 0.5, "trainable": true, "name": "dropout_1"}}, {"class_name": "Dense", "config": {"W_constraint": null, "b_co; line: 1, column: 16001]
14:39:42,348 WARN  ~ Could not read keras backend used (no backend field found) 

Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: 3D (convolutional) inputs with unknown dimension ordering NONE are not supported.. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.layers.KerasInput.getOutputType(KerasInput.java:123)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.inferOutputTypes(KerasModel.java:254)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:129)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:60)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:135)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:156)
	at org.deeplearning4j.examples.misc.presave.ImportKerasModel.main(ImportKerasModel.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by eraly** [comment]
cc @wmeddie

**Comment by maxpumperla** [comment]
@eraly @wmeddie this is for safety purposes. In this old model there's pretty much no way of finding out what Keras backend was used (at least the code and my manual inspection suggest so).

This wouldn't happen in keras 2, but I see why we need this. Two options:

- for keras 1.x models we _assume_ theano is the model backend, as it was the default back then. doesn't make me very happy, though.
- we extend the model import API by allowing folks to _specify_ the used backend.

How urgent is this? seems to be needed for skil?!

**Comment by wmeddie** [comment]
Well a potential customer saw that we support Keras models, found one, deployed it and it failed.  Whatever we could do to make that just work the better.  Especially if it's something small we can add to the final release of 1.0.0 and SKIL.

**Comment by melchisadeck** [comment]
Thanks all for your engagement on this.

I downloaded vgg16_compiled.h5 provided by @eraly at the link above and attempted to import - after about 25 seconds I received the "upload failed try again" message, exactly as before.

Then, just to see what happens, I attempted to import another random file from my Downloads folder - an Acrobat PDF file of 5.7Mb.

The "upload failed" message persisted and above it I received an "Imported Model Successfully Imported Model" message and the model appears to be imported, startable, stopable, etc. - screen shot attached.

I've tried this with a .pdf file of 5.7MB, a .png file of 2.3MB and an .m3u file of 94 bytes, stopping and starting docker between each model import - random .pdf/.png/.m3u import attempt and each time the vgg16_compiled.h5 import appears to complete successfully.

I haven't attempted to send data to the imported/running model but I thought this observation may help.

Regards,
Mel

![screen shot 2018-04-12 at 07 56 47](https://user-images.githubusercontent.com/3584036/38661412-ade0d262-3e28-11e8-8796-bc4e3cf194a9.png)

**Comment by maxpumperla** [comment]
@melchisadeck yeah, so since this issue has been closed on DL4J side, once a new SKIL release comes out that reflects these changes, you should be good to go.

**Comment by melchisadeck** [comment]
Great - thanks @maxpumperla and everyone.

Regards,
Mel

**Comment by eraly** [comment]
@maxpumperla 🎉 
@melchisadeck Thanks for the feedback. Appreciate it much.
