### ISSUE TITLE
File, tiny-yolo-voc_dl4j_inference.v1.zip, failed checksum.

### ISSUE THREAD

**Issue by ZhangYimeng** [deeplearning4j/deeplearning4j#4930]
#### Issue Description
I was running HouseNumberDetection.java, but after tiny-yolo-voc_dl4j_inference.v1.zip was downloaded, it failed checksum.

Please describe our issue, along with:
- expected behavior
Checksum local is equal to expecting value.

- encountered behavior
Verifying download...
Checksum local is 3584630181, expecting 2004171617

#### Version Information
* Java version: 1.8.0_112
* Deeplearning4j version: 1.0.0-alpha
* platform information: MacOS High Sierra 10.13.2
* CUDA version: Null
* NVIDIA driver version: Null

**Comment by ZhangYimeng** [comment]
The exception stack is:
[main] INFO person.mochi.goblin.ModelZooTest - Load data...
[main] INFO person.mochi.goblin.ModelZooTest - Build model...
[main] INFO org.deeplearning4j.zoo.ZooModel - Downloading model to /Users/zhangyimeng/.deeplearning4j/tiny-yolo-voc_dl4j_inference.v1.zip
[main] INFO org.deeplearning4j.zoo.ZooModel - Verifying download...
[main] INFO org.deeplearning4j.zoo.ZooModel - Checksum local is 3584630181, expecting 2004171617
[main] ERROR org.deeplearning4j.zoo.ZooModel - Checksums do not match. Cleaning up files and failing...
Exception in thread "main" java.lang.IllegalStateException: Pretrained model file failed checksum. If this error persists, please open an issue at https://github.com/deeplearning4j/deeplearning4j.
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:80)
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:41)
	at person.mochi.goblin.ModelZooTest.main(ModelZooTest.java:122)
