### ISSUE TITLE
Invalid input name exception in TransferLearningHelper

### ISSUE THREAD

**Issue by ospavel** [deeplearning4j/deeplearning4j#4933]
DL4J 1.0.0-alpha, Windows 7, Native CPU

The code
```
        NeuralNetConfiguration.ListBuilder listBuilder = new NeuralNetConfiguration.Builder()
                .seed(12345)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .updater(new Adam.Builder().learningRate(0.01).build())
                .l2(1e-5)
                .activation(Activation.TANH)
                .weightInit(WeightInit.XAVIER)
                .list()
                .layer(0, new GravesLSTM.Builder().nIn(43).nOut(8).build())
                .layer(1, new GravesLSTM.Builder().nIn(8).nOut(8).build())
                .layer(2, new RnnOutputLayer.Builder(LossFunctions.LossFunction.MCXENT).activation(Activation.SOFTMAX).nIn(8).nOut(2).build());
        MultiLayerNetwork model1 = new MultiLayerNetwork(listBuilder.pretrain(false).backprop(true).build());
        model1.init();

        FineTuneConfiguration fineTuneConf = new FineTuneConfiguration.Builder()
                .seed(67890)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .updater(new Adam.Builder().learningRate(0.01).build())
                .l2(1e-5)
                .activation(Activation.TANH)
                .weightInit(WeightInit.XAVIER)
                .build();

        ComputationGraph graph1 = model1.toComputationGraph();

        ComputationGraph graph = new TransferLearning.GraphBuilder(graph1)
                .fineTuneConfiguration(fineTuneConf)
                .setFeatureExtractor("1")
                .removeVertexKeepConnections("2")
                .addInputs("SIn")
                .addLayer("S0", new GravesLSTM.Builder().nIn(43).nOut(8).build(), "SIn")
                .addLayer("S1", new GravesLSTM.Builder().nIn(8).nOut(8).build(), "S0")
                .addVertex("M1", new LastTimeStepVertex("in"), "1")
                .addVertex("M2", new LastTimeStepVertex("SIn"), "S1")
                .addLayer("Dense", new DenseLayer.Builder().nIn(16).nOut(4).build(), "M1", "M2")
                .addLayer("Output", new OutputLayer.Builder(LossFunctions.LossFunction.MCXENT).activation(Activation.SOFTMAX).weightInit(WeightInit.XAVIER).nIn(4).nOut(2).build(), "Dense")
                .setOutputs("Output")
                .build();

        TransferLearningHelper transferLearningHelper = new TransferLearningHelper(graph);
        // java.lang.IllegalArgumentException: Invalid input name: "in" not found in list of network inputs ([1, SIn])
```

raises exception:

```
Caused by: java.lang.IllegalArgumentException: Invalid input name: "in" not found in list of network inputs ([1, SIn])
	at org.deeplearning4j.nn.graph.vertex.impl.rnn.LastTimeStepVertex.<init>(LastTimeStepVertex.java:63)
	at org.deeplearning4j.nn.graph.vertex.impl.rnn.LastTimeStepVertex.<init>(LastTimeStepVertex.java:52)
	at org.deeplearning4j.nn.conf.graph.rnn.LastTimeStepVertex.instantiate(LastTimeStepVertex.java:94)
	at org.deeplearning4j.nn.conf.graph.rnn.LastTimeStepVertex.instantiate(LastTimeStepVertex.java:40)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:488)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:378)
	at org.deeplearning4j.nn.transferlearning.TransferLearning$GraphBuilder.build(TransferLearning.java:755)
	at org.deeplearning4j.nn.transferlearning.TransferLearningHelper.initHelperGraph(TransferLearningHelper.java:252)
	at org.deeplearning4j.nn.transferlearning.TransferLearningHelper.<init>(TransferLearningHelper.java:66)
	at frontend.Testing.testDL4JTransfer(Testing.java:794)
```

The model inputs are "in" and "SIn".

**Comment by AlexDBlack** [comment]
OK, after looking at this: here's what I think is happening.
First: LastTimeStep vertex requires the name of a network input. TransferLearningHelper removes the frozen layers (including that input) but doesn't update the LastTimeStepVertex input name. Indeed, I don't think there is a robust way to do that in general anyway.

Workaround: use LastTimeStep wrapper layer instead:
```
                .addLayer("S0", new LastTimeStep(new GravesLSTM.Builder().nIn(43).nOut(8).build()), "SIn")
                .addLayer("S1", new LastTimeStep(new GravesLSTM.Builder().nIn(8).nOut(8).build()), "S0")
```

Given the workaround, and some of the refactoring plans we have (that will make this irrelevant) I'm inclined to mark it as a "won't fix" for now.

**Comment by ospavel** [comment]
@AlexDBlack , ok. I replaced vertexes with LastTimeStep layer of last GravesLSTMs:
```
        GravesLSTM lastLayer2;
        ComputationGraph graph = new TransferLearning.GraphBuilder(graph1)
                .fineTuneConfiguration(fineTuneConf)
                .setFeatureExtractor("1")
                .removeVertexKeepConnections("2")
                .addInputs("SIn")
                .addLayer("S0", new GravesLSTM.Builder().nIn(43).nOut(8).build(), "SIn")
                .addLayer("S1", lastLayer2 = new GravesLSTM.Builder().nIn(8).nOut(8).build(), "S0")
                .addLayer("M1", new LastTimeStep(((org.deeplearning4j.nn.layers.recurrent.GravesLSTM)graph1.getLayers()[graph1.getLayers().length - 2]).layerConf()), "1")
                .addLayer("M2", new LastTimeStep(lastLayer2), "S1")
                .addLayer("Dense", new DenseLayer.Builder().nIn(16).nOut(4).build(), "M1", "M2")
                .addLayer("Output", new OutputLayer.Builder(LossFunctions.LossFunction.MCXENT).activation(Activation.SOFTMAX).weightInit(WeightInit.XAVIER).nIn(4).nOut(2).build(), "Dense")
                .setOutputs("Output")
                .build();
```
"TransferLearningHelper transferLearningHelper = new TransferLearningHelper(graph)" ok, but next "transferLearningHelper.fitFeaturized(trainIterator)" throws exception on frozen branch:
```
org.deeplearning4j.exception.DL4JInvalidInputException: Received input with size(1) = 43 (input array shape = [128, 43, 5]); input.size(1) must match layer nIn size (nIn = 8)
	at org.deeplearning4j.nn.layers.recurrent.LSTMHelpers.activateHelper(LSTMHelpers.java:164)
	at org.deeplearning4j.nn.layers.recurrent.GravesLSTM.activateHelper(GravesLSTM.java:159)
	at org.deeplearning4j.nn.layers.recurrent.GravesLSTM.activate(GravesLSTM.java:133)
	at org.deeplearning4j.nn.layers.recurrent.LastTimeStepLayer.activate(LastTimeStepLayer.java:88)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:105)
	at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1680)
	at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1566)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1349)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:173)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:59)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:53)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1075)
	at org.deeplearning4j.nn.transferlearning.TransferLearningHelper.fitFeaturized(TransferLearningHelper.java:375)
```
At the LastTimeStepLayer input after two GravesLSTM should be 8 (output of layer "1"), but it equals to initial 43 and throws exception. 

I tried don't use TransferLearningHelper and just made "computationGraph.fit(trainIterator);", then I got another exception:
```
java.lang.NullPointerException: null
	at org.deeplearning4j.nn.updater.BaseMultiLayerUpdater.preApply(BaseMultiLayerUpdater.java:324)
	at org.deeplearning4j.nn.updater.BaseMultiLayerUpdater.update(BaseMultiLayerUpdater.java:261)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.updateGradientAccordingToParams(BaseOptimizer.java:326)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:187)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:59)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:53)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1075)
```

I just want to freeze RNN model1, then take output of last GravesLSTM layer into Dense (with LastTimeStep). (Dense joins it with output of last GravesLSTM layer of another model). 
How I can do this? There is mistakes?
![Model](http://oi67.tinypic.com/w1ftlg.jpg)

**Comment by treo** [comment]
As answered in gitter:
From the [javadoc](https://deeplearning4j.org/doc/org/deeplearning4j/nn/transferlearning/TransferLearningHelper.html):
> Often times transfer learning models have "frozen" layers where parameters are held constant during training For ease of training and quick turn around times, the dataset to be trained on can be featurized and saved to disk. Featurizing in this case refers to conducting a forward pass on the network and saving the activations from the output of the frozen layers. During training the forward pass and the backward pass through the frozen layers can be skipped entirely and the "featurized" dataset can be fit with the smaller unfrozen part of the computation graph

if you use the helper and use fitFeaturized, you are saying, don't go through the frozen layers, instead use this data which has moved through them already
so you have to provide input of size 8 instead of 43, as that is what the input of your unfrozen layers is
