### ISSUE TITLE
Keras import: Reshape issue with conv1d - flatten - dense - lstm - dense

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#4934]
From #4899 reported by @fincken on 1.0.0-alpha:

I tried doing the embedding beforehand, turning the input into (20,100) shapes. It still failes to load even without the Embedding layer, so there might be an improper handling on several layertypes.

Exception in thread "main" java.lang.IllegalStateException: Mis matched lengths: [4096] != [57344] - Array 1 shape: [32, 128], array 2 shape: [448, 128] at org.nd4j.linalg.util.LinAlgExceptions.assertSameLength(LinAlgExceptions.java:42) at org.nd4j.linalg.api.ops.BaseTransformOp.<init>(BaseTransformOp.java:174) at org.nd4j.linalg.api.ops.impl.transforms.Set.<init>(Set.java:43) at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:1274) at org.deeplearning4j.nn.layers.BaseLayer.setParam(BaseLayer.java:204) at org.deeplearning4j.nn.modelimport.keras.KerasLayer.copyWeightsToLayer(KerasLayer.java:296) at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.copyWeightsToModel(KerasModelUtils.java:76) at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:228) at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:215) at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:142) at test.KerasImportTestClass.main(KerasImportTestClass.java:12)

current model that fails supplied here:
[GIST](https://gist.github.com/fincken/28116f33f37ac630848774bcaf8a12ab)

**Comment by maxpumperla** [comment]
@fincken this is on master now
