### ISSUE TITLE
problem about integration with spark

### ISSUE THREAD

**Issue by qihuagao** [deeplearning4j/deeplearning4j#4943]
#### Issue Description
The issue:
I use SparkDl4jMultiLayer of deeplearning4j to train a bulk of data, and encountered crash problem (forgive me if the question is naive, I am really new to deeplearning4j)
  Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 28.0 failed 1 times, most recent failure: Lost task 0.0 in stage 28.0 (TID 710, localhost, executor driver): TaskResultLost (result lost from block manager)
the main code likes the followings, it's quite simple:
```
   val trainData = durTs.groupByKey(row => row.getString(0)).mapGroups((key, rows) => {
      getDataSetByRow(rows)
    })(Encoders.kryo[DataSet]).toJavaRDD
```
I tried to dump trainData by trainData.saveAsTextFile("data"). while the content in data likes:
===========INPUT===================
[[[         0,         0,         0  ...  128.1347  131.8781,  127.0842], 
  [         0,         0,         0  ...  130.0474  130.0808,  130.4081], 
  [         0,    0.0724,    0.0751  ...   11.1999   11.2056,   11.2001], 
   ..., 
  [         0,         0,         0  ...    1.7313    1.7313,    1.7314], 
  [         0,  -30.8471,  -30.8427  ...    9.9171    9.9115,    9.8909], 
  [         0,   -0.0238,   -0.1001  ...    2.3627    2.4796,    2.9993]]]
=================OUTPUT==================
===========INPUT MASK===================
===========OUTPUT MASK===================

I really don't understand why  "..." exists either,  I suppose It should be some numbers.

#### Version Information
  "org.apache.spark" %% "spark-mllib" % "2.2.0",
  "org.nd4j" % "nd4j-native-platform" % "1.0.0-alpha",
  "org.deeplearning4j" % "deeplearning4j-core" % "1.0.0-alpha",
  "org.deeplearning4j" % "deeplearning4j-nlp" % "1.0.0-alpha",
  "org.deeplearning4j" %% "dl4j-spark" % "1.0.0-alpha_spark_2"

OS: both centos7 and mac show this error.

**Comment by qihuagao** [comment]
About the output of trainData.saveAsTextFile,  I figured it out after searching. When writing the RDD as text file it won't use Java serialization but only call toString on every record. 
After some research, TaskResultLost may be related with memory assignment problem, 
My input feature is about 5000(example)* 25(dimension)*500. I suppose its not quite a lot.
Environment:
local spark environment. 
java heap and off-heap size:
sbt -J-Xmx16g -J-Dorg.bytedeco.javacpp.maxbytes=8000000000 run

Full stack message
```
18/04/18 21:51:11 INFO ScoreIterationListener: Score at iteration 0 is 18.001587272762368
18/04/18 21:51:11 INFO ScoreIterationListener: Score at iteration 0 is 9.338891388057778
18/04/18 21:51:13 INFO ScoreIterationListener: Score at iteration 1 is 127.68445798874217
18/04/18 21:51:14 INFO ScoreIterationListener: Score at iteration 1 is 0.01943123239870225
18/04/18 21:51:16 INFO ScoreIterationListener: Score at iteration 2 is 64.13182995287784
18/04/18 21:51:16 INFO MemoryStore: Block taskresult_1445 stored as bytes in memory (estimated size 1145.7 KB, free 909.6 MB)
18/04/18 21:51:16 INFO BlockManagerInfo: Added taskresult_1445 in memory on 10.2.2.8:38461 (size: 1145.7 KB, free: 927.2 MB)
18/04/18 21:51:16 INFO Executor: Finished task 1.0 in stage 12.0 (TID 1445). 1173220 bytes result sent via BlockManager)
18/04/18 21:51:17 ERROR RetryingBlockFetcher: Exception while beginning fetch of 1 outstanding blocks 
java.io.IOException: Failed to connect to /10.2.2.8:38461
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:232)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:182)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$1.createAndStart(NettyBlockTransferService.scala:98)
	at org.apache.spark.network.shuffle.RetryingBlockFetcher.fetchAllOutstanding(RetryingBlockFetcher.java:141)
	at org.apache.spark.network.shuffle.RetryingBlockFetcher.start(RetryingBlockFetcher.java:121)
	at org.apache.spark.network.netty.NettyBlockTransferService.fetchBlocks(NettyBlockTransferService.scala:108)
	at org.apache.spark.network.BlockTransferService.fetchBlockSync(BlockTransferService.scala:93)
	at org.apache.spark.storage.BlockManager.getRemoteBytes(BlockManager.scala:642)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$1.apply$mcV$sp(TaskResultGetter.scala:82)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$1.apply(TaskResultGetter.scala:63)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$1.apply(TaskResultGetter.scala:63)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1954)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3.run(TaskResultGetter.scala:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /10.2.2.8:38461
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:257)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:291)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:631)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	... 1 more
```

**Comment by agibsonccc** [comment]
This has nothing to do with dl4j. Everything in your job ranging from your cluster to your spark job is wrong here. Double check your basic spark job first.

**Comment by qihuagao** [comment]
@agibsonccc  Sorry,  I didn't catch what you mean
The basic spark job can output right content while dl4j not.
Could you elaborate a little, thank you very much for your time, I am really trapped here.

**Comment by agibsonccc** [comment]
It says right in the exception that you are getting a connection refused. That is not a dl4j error. That is a plain old java connection error.

**Comment by qihuagao** [comment]
Thank @agibsonccc @AlexDBlack for your time.  Enlightened  by agibsonccc,  I changed code to use JavaSparkContext, it worked, I use SparkSession originally. It's a little weird why cannot use SparkSession.

**Comment by qihuagao** [comment]
@AlexDBlack Yeah, DataSetExportFunction is great to use, thank you for sharing.
