### ISSUE TITLE
java.util.ArrayList cannot be cast to org.datavec.api.writable.Writable

### ISSUE THREAD

**Issue by Yu-Hang** [deeplearning4j/deeplearning4j#4963]
#### Issue Description

Hi, I'm trying MnistImagePipelineExample.java on my own dataset, but I'm getting error

at line: 

`DataSet ds = dataIter.next();`

```
Exception in thread "main" java.lang.ClassCastException: java.util.ArrayList cannot be cast to org.datavec.api.writable.Writable
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:207)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:193)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:367)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:458)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:85)
	at org.dp.importK.malairaModel.main(malairaModel.java:75)


```

My code here:

```
public static void main(String[] args) {

        int height = 44;
        int width = 44;
        int channels = 3;
        int rngseed = 123;
        Random randNumGen = new Random(rngseed);
        int batchSize = 1;
        int outputNum = 10;

        String data_path = "C:/Users/yuh5/Desktop/Thick_test/train_f1";

        // Define the File Paths
        File trainData = new File(data_path);

        // Define the FileSplit(PATH, ALLOWED FORMATS,random)
        FileSplit train = new FileSplit(trainData, NativeImageLoader.ALLOWED_FORMATS, randNumGen);

        // Extract the parent path as the image label
        ParentPathLabelGenerator labelMaker = new ParentPathLabelGenerator();

        ImageRecordReader recordReader = new ImageRecordReader(height, width, channels, labelMaker);

        // Initialize the record reader
        // add a listener, to extract the name
        try {
            recordReader.initialize(train);
        } catch (IOException e) {
            e.printStackTrace();
        }

        // The LogRecordListener will log the path of each image read
        // used here for information purposes,
        // If the whole dataset was ingested this would place 60,000
        // lines in our logs
        // It will show up in the output with this format
        // o.d.a.r.l.i.LogRecordListener - Reading /tmp/mnist_png/training/4/36384.png
        recordReader.setListeners(new LogRecordListener());

        // DataSet Iterator
        DataSetIterator dataIter = new RecordReaderDataSetIterator(recordReader, batchSize, 1, outputNum);

        // Scale pixel values to 0-1
        DataNormalization scaler = new ImagePreProcessingScaler(0, 1);
        scaler.fit(dataIter);
        dataIter.setPreProcessor(scaler);

        // In production you would loop through all the data
        // in this example the loop is just through 3
        // images for demonstration purposes
        for (int i = 1; i < 3; i++) {
            DataSet ds = dataIter.next();
            log.info("matrix: " + ds.toString());
            log.info("label: " + dataIter.getLabels().toString());
        }
    }
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.2-SNAPSHOT
* platform information (OS, etc): IntelliJ IDEA on Windows
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by saudet** [comment]
Please try again with Deeplearning4j 1.0.0-alpha!

**Comment by AlexDBlack** [comment]
Yeah, I can run the MnistImagePipelineExample on 1.0.0-alpha without issue (and the source dataset shouldn't matter for an issue like this).

Given the stack trace, it looks like you might have got an old snapshot right when one of the ImageRecordReader methods was refactored in DataVec.
At any rate, 0.9.2-SNAPSHOT should no longer be used.

We can re-open if this occurs on 1.0.0-alpha.
