### ISSUE TITLE
Support Keras Permute layer

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#5021]
#### Issue Description

Attempted to convert the weights from https://github.com/orobix/retina-unet/blob/master/test/test_best_weights.h5

But got the following error:
```
org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Permute. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.

	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:275)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:190)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:158)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:91)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:134)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:233)
	at org.deeplearning4j.nn.modelimport.keras.configurations.KerasModelImportTest.test2(KerasModelImportTest.java:94)
```

Keras layer is https://keras.io/layers/core/#permute.

#### Version Information

Please indicate relevant versions, including, if relevant:

v1 snapshot

**Comment by crockpotveggies** [comment]
Sorry I missed this in my inbox. Did you still need it?
