### ISSUE TITLE
Unsupported keras layer type UpsampleLike

### ISSUE THREAD

**Issue by eduramiba** [deeplearning4j/deeplearning4j#5028]
#### Issue Description

I am trying to load a keras model and getting this exception.

```
org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type UpsampleLike. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
        at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:271)
        at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:189)
        at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:157)
        at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:91)
        at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:128)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:107)
```

#### Version Information

* Deeplearning4j version 1.0.0-alpha
* platform information (OS, etc): Windows
* CUDA version, if used: N/A

Thanks!

**Comment by maxpumperla** [comment]
@eduramiba is this a new Keras layer? I've never seen this before. Which keras version are you using?

**Comment by maxpumperla** [comment]
@eduramiba googled a little, this is a custom layer. likely from here: https://github.com/fizyr/keras-retinanet, correct?

If so, we have a mechanism to register custom layers, but you have to provide the Java import side yourself (otherwise we can't know what to map this layer to!). Check this out:

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/test/java/org/deeplearning4j/nn/modelimport/keras/e2e/KerasCustomLayerTest.java#L53-L54

I'm closing this for now, since we can't add support for every layer out there.

**Comment by eduramiba** [comment]
Oh right, I didn't realize it was a custom layer, thank you very much!

**Comment by maxpumperla** [comment]
np, let me know if there's anything else. :+1:
