### ISSUE TITLE
OutOfMemoryError for Orthogonal init (Keras 2)

### ISSUE THREAD

**Issue by s78154** [deeplearning4j/deeplearning4j#5051]
#### Issue Description

Hi, I am working on a research project at my university. My task at the moment is to get the keras model importer working. My docent gave me two files created in python with keras version 2: 
- .json file ([json.txt](https://github.com/deeplearning4j/deeplearning4j/files/1974393/json.txt)) file as model and
- .h5 weightsArchive

My programming example is:

```java
public void LoadFromFileSystem() {
	File modelJsonFile = new File(kerasJsonSource);
	File modelWeightFile = new File(kerasH5Source);

	MultiLayerNetwork network = null;
	try {
		network = KerasModelImport.importKerasSequentialModelAndWeights(modelJsonFile.getAbsolutePath(), modelWeightFile.getAbsolutePath(), false);
		} catch (IOException e) {
			System.err.println(e.getMessage());
			e.printStackTrace();
		} catch (InvalidKerasConfigurationException e) {
			System.err.println(e.getMessage());
			e.printStackTrace();
		} catch (UnsupportedKerasConfigurationException e) {
			System.err.println(e.getMessage());
			e.printStackTrace();
		} 
	}
}
```

Always running the application I get an OutOfMemoryError:

```java
Exception in thread "main" java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(25600000000): totalBytes = 85M, physicalBytes = 299M 	
at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:76) 
at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:567) 
at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:61) at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:252) 	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1478) 
at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1452)
at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:253)
at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:109)
at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:275)
at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:5043)
at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4997)
at org.nd4j.linalg.api.rng.distribution.impl.OrthogonalDistribution.sample(OrthogonalDistribution.java:234) 	at org.nd4j.linalg.api.rng.distribution.impl.OrthogonalDistribution.sample(OrthogonalDistribution.java:251) 
at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:68) 
at org.deeplearning4j.nn.weights.WeightInitUtil.initWeights(WeightInitUtil.java:61) 
at org.deeplearning4j.nn.params.LSTMParamInitializer.init(LSTMParamInitializer.java:151) 
at org.deeplearning4j.nn.conf.layers.LSTM.instantiate(LSTM.java:84) 
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:635) 
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:550) 
at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:226) 
at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:215) 
at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:214) 
at api_import.KerasModelImporter.LoadFromFileSystem(KerasModelImporter.java:56) 
at api_import.KerasModelImporter.main(KerasModelImporter.java:75) 

Caused by: java.lang.OutOfMemoryError: Native allocator returned address == 0 
at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:70) 	... 23 more 
```

After debugging the project I came to the result that the `KerasSequentialModel` is created successfully. But while processing the method `kerasModel.getMultiLayerNetwork()` in class `KerasModelImport` Nd4j tries to allocate an array with 25600000000 elements.

Can anyone tell me how to fix this issue? I have already tried to increase the heap space via the VM arguments in Eclipse. But the problem is still the same.

#### Version Information

* DL4J dependencies via gradle:
deeplearning4j-core:1.0.0-alpha
nd4j-native-platform:1.0.0-alpha
* platform information
OS: Windows 10, 64 Bit
RAM: 8 GB
IDE: Eclipse Oxygen, Version 4.7.3a

**Comment by maxpumperla** [comment]
@s78154 thanks for reporting this, I've seen this recently as well on a larger model. My first guess is that something changed to the implementation (or something underlying) `Orthogonal`. @raver119 are you aware of any changes down stream?

@s78154 can you try to set the recurrent initialiser of your LSTMs to something else? I want to narrow this down and see if it's really just orthogonal that's causing the issue.

**Comment by s78154** [comment]
I changed the initializer in the JSON file to RandomNormal. There are no errors anymore. But I also get no information about starting the neural network and the application terminates after import.

Does it change anything for me, when I import the weights archive with the RandomNormal initializer? It would be nice if you can fix the issue.

**Comment by maxpumperla** [comment]
@s78154 by "starting" I presume you mean training the model? If so, you need to do this:

a) save model config and weights in one `h5` file after compiling the keras model. you do this with `model.save("foo.h5"). this way the keras training configuration is also stored. If you do it separately, it isn't.
b) use `enforceTrainingConfig=true` to load the model.

Here's an example:

https://github.com/deeplearning4j/deeplearning4j/blob/4f058e80f1f9cf14d80b2700f3cb66bdb3965f37/deeplearning4j-modelimport/src/test/java/org/deeplearning4j/nn/modelimport/keras/e2e/KerasModelEndToEndTest.java#L301-L311

re: orthogonal, we're working on this. no worries!
