### ISSUE TITLE
error in transfer learning

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#5064]
#### Issue Description
After restore yolo2_dl4j_inference.v1.zip and build the model, exception thrown when call fit() to train. 

The block size should be assigned to avoid using init value zero.

#### Version Information
* Deeplearning4j version
1.0.0-alpha

* platform information (OS, etc)
win7

* CUDA version, if used
not used

* NVIDIA driver version, if in use
not used

#### exception stack
java.lang.ArithmeticException: / by zero
at org.deeplearning4j.nn.layers.convolution.SpaceToDepth.preOutput(SpaceToDepth.java:135)
at org.deeplearning4j.nn.layers.convolution.SpaceToDepth.preOutput(SpaceToDepth.java:111)
at org.deeplearning4j.nn.layers.convolution.SpaceToDepth.activate(SpaceToDepth.java:160)
at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:105)
at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1680)
at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1566)
at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1349)
at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:173)
at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:59)
at org.deeplearning4j.optimize.Solver.optimize(Solver.java:53)
at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1194)
at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1140)
at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:875)

**Comment by AlexDBlack** [comment]
This isn't related to transfer learning - but rather, there was a model configuration/format change for SpaceToDepth - the model wasn't unfortunately fixed to account for this change.

I believe this has already been fixed on this branch, which should be merged to master soon: https://github.com/deeplearning4j/deeplearning4j/pull/4985

As for workarounds: the simplest would be to set the SpaceToDepth block size manually (should have value 2, if memory serves me)

I'll leave this issue open until the PR is actually merged.

**Comment by AlexDBlack** [comment]
Fixed long ago, should have been cloned earlier.
