### ISSUE TITLE
Keras enforceTrainingConfig

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#5100]
#### Issue Description

Experiencing a minor issue when trying to import this model config for U-Net here: https://github.com/orobix/retina-unet/blob/master/test/test_architecture.json

```
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: If enforceTrainingConfig is true, a training configuration object (JSON) has to be provided.. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:164)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:91)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:139)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelConfiguration(KerasModelImport.java:305)
	at org.deeplearning4j.nn.modelimport.keras.KerasConverter.convertKerasFunctional(KerasConverter.java:21)
	at org.deeplearning4j.nn.modelimport.keras.KerasConverter.main(KerasConverter.java:29)
```

Using `KerasModelImport.importKerasModelConfiguration(configPath);`.

#### Version Information

snapshot

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by crockpotveggies** [comment]
Solved in DM conversation. Will need to re-export model.
