### ISSUE TITLE
Support DepthwiseConv2D

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#5116]
#### Issue Description

AFAIK we haven't yet supported DepthwiseConv2D, but we will need it to support MobileNet. Creating this issue since I think it was forgotten.

```
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type DepthwiseConv2D. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:285)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:196)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:158)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:91)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:135)
	at org.deeplearning4j.KerasConverter.importFunctionalModelH5(KerasConverter.java:43)
	at org.deeplearning4j.KerasConverter.convertKerasFunctional(KerasConverter.java:23)
	at org.deeplearning4j.KerasConverter.main(KerasConverter.java:49)
```

There's a test in Keras model import that currently fails with a TODO.

#### Version Information

snapshot

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
I'm pretty sure we have this op at C++ level. So, probably just a mapping issue.

**Comment by maxpumperla** [comment]
@crockpotveggies yeah, I was aware of this, but thanks for creating an issue. @raver119  yes, it's available in libnd4j, should be easy enough to create the respective dl4j layer + keras support.
