### ISSUE TITLE
Regular LSTM does not work with MultiLayerNetwork

### ISSUE THREAD

**Issue by jadams5** [deeplearning4j/deeplearning4j#515]
Gist:  https://gist.github.com/jadams5/e32cd927e8ec6ff3631a

Throws:

```
Exception in thread "main" java.lang.NullPointerException
at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:355)
at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:362)
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:482)
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:366)
at com.tsi.DL4JTest.main(DL4JTest.java:66)
```

**Comment by EronWright** [comment]
Thanks for the report, the library is stabilizing now and we'll re-test with your sample.

**Comment by nyghtowl** [comment]
We are shifting directions with LSTM. We have a Graves version and soon a GRU version should up and running. We are renaming original LSTM to ImageLSTM because its based on the image RNNs and action model approaches that exist. Our current api doesn't fully lend itself to this model. So we are reprioritizing getting this one up and running to a later release. Checkout the other LSTM models for now. I'm closing this issue and opening a new one to track our work on the image RNN.
