### ISSUE TITLE
Batch norm NPE with transfer learning?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5152]
Train model with batch norm -> transfer learning -> NPE

```
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: SEPARATE; inference: SEPARATE], cacheMode set to [NONE]
Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.nn.params.BatchNormalizationParamInitializer.init(BatchNormalizationParamInitializer.java:100)
	at org.deeplearning4j.nn.conf.layers.BatchNormalization.instantiate(BatchNormalization.java:66)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:587)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:500)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.<init>(MultiLayerNetwork.java:247)
	at org.deeplearning4j.nn.transferlearning.TransferLearning$Builder.build(TransferLearning.java:278)
```

Edit: Unable to reproduce with this config:
https://gist.github.com/AlexDBlack/953004733e8b3756d9cf29f3c68823a5

**Comment by AlexDBlack** [comment]
I believe this was eventually tracked down to a lack on input validation for nIn=nOut=0 case.
