### ISSUE TITLE
Can't train a VGG-based TransferLearning model

### ISSUE THREAD

**Issue by yquemener** [deeplearning4j/deeplearning4j#5167]
#### Issue Description

I use the following program to train a transfer-learning model based on VGG16. I use the latest SNAPSHOT-1.0.0 version (tagged at the 2018-05-15 date)

```
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.graph.ComputationGraph;
import org.deeplearning4j.nn.transferlearning.TransferLearning;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.zoo.PretrainedType;
import org.deeplearning4j.zoo.model.VGG16;
import org.nd4j.linalg.activations.Activation;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.lossfunctions.LossFunctions;

import java.io.File;


public class TransferModelDebug {
    public static void main(String... args) throws Exception {
        DataSet ds = new DataSet();
        ds.load(new File("/tmp/sample-dataset"));
        System.out.println("Loading");

        ComputationGraph model = (ComputationGraph)(
                VGG16.builder().build()
                        .initPretrained(PretrainedType.IMAGENET));
        System.out.println(model.summary());

        ComputationGraph transferModel = new TransferLearning.GraphBuilder(model)
                .setFeatureExtractor("fc2")
                .removeVertexKeepConnections("predictions")
                .addLayer("predictions",
                        new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
                                .nIn(4096).nOut(2)
                                .weightInit(WeightInit.XAVIER)
                                .activation(Activation.SOFTMAX).build(), "fc2")
                .build();
        System.out.println("Fitting");
        transferModel.fit(ds);
    }
}
```

It fails with this error:

```
Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.nn.conf.preprocessor.CnnToFeedForwardPreProcessor.backprop(CnnToFeedForwardPreProcessor.java:107)
	at org.deeplearning4j.nn.graph.vertex.impl.PreprocessorVertex.doBackward(PreprocessorVertex.java:67)
	at org.deeplearning4j.nn.graph.ComputationGraph.calcBackpropGradients(ComputationGraph.java:2426)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1318)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1279)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:178)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:60)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:54)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1103)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1049)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:943)
	at org.dl4j.sandbox.TransferModelDebug.main(TransferModelDebug.java:37)
```

**Comment by yquemener** [comment]
It turns out that changing 
`.setFeatureExtractor("fc2")` 
to 
`.setFeatureExtractor("fc1")`

removes the error message.
