### ISSUE TITLE
DataVec: OutOfMemoryError when processing CSV using LocalTransformExecutor

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5216]
https://github.com/deeplearning4j/DataVec/issues/562

> #### Issue Description
> Getting OutOfMemoryError when trying to transform a 80mb CSV file(~320k records with 45 columns) using LocalTransformExecutor as explained in (/org/datavec/transform/basic/)BasicDataVecExampleLocal.java. Processing is taking more than 4gb of memory. 

> Only transformation applied is CategoricalToIntegerTransform to transform about 40 columns.

> Please describe your issue, along with:
Expected behavior -
> - A transformed file with Categorical data converted into Interger
Encountered behavior -
`java.lang.OutOfMemoryError: Java heap space
        at java.util.ArrayList.<init>(ArrayList.java:153) ~[na:1.8.0_151]
        at org.datavec.api.transform.transform.categorical.CategoricalToIntegerTransform.map(CategoricalToIntegerTransform.java:103) ~[datavec-api-1.0.0-alpha.jar:na]
`

> #### Version Information
> Please indicate relevant versions, including, if relevant:
> * Datavec version - 1.0.0-alpha
> * Deeplearning4j version - NA
> * platform information (OS, etc) - Windows
> * CUDA version, if used
> * NVIDIA driver version, if in use

> #### Contributing

> If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by agibsonccc** [comment]
Closing — references a removed/rewritten subsystem (DataVec, NLP/Word2Vec, Model Zoo, Spark, UI, or Arbiter). These have been fundamentally rewritten or removed in the upcoming release. Please open a new issue if you experience similar problems with the new version.
