### ISSUE TITLE
Not able to import Keras model into DL4J - HDF5-DIAG: Error detected in HDF5

### ISSUE THREAD

**Issue by rahul-raj** [deeplearning4j/deeplearning4j#5301]
Here is my code block that performs keras import:
```
MultiLayerNetwork multiLayerNetwork = KerasModelImport
                .importKerasSequentialModelAndWeights("C:/Users/Rahul/Downloads/Artificial_Neural_Networks/Artificial_Neural_Networks/ANN/ann_model_json",
                        "C:/Users/Rahul/Downloads/Artificial_Neural_Networks/Artificial_Neural_Networks/ANN/ann_model");
        Evaluation evaluation = new Evaluation(1);
        INDArray output = multiLayerNetwork.output(testSet.getFeatureMatrix());
        output = output.cond(new AbsValueGreaterThan(0.50));
        evaluation.eval(testSet.getLabels(),output);
        System.out.println("args = [" + evaluation.stats() + "]");
```

And I get this exception on console when I run it:
```
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: C:\autotest\hdf5110-StdRelease-code-10vs14\build\hdfsrc\src\H5G.c line 472 in H5Gopen2(): unable to open group
    major: Symbol table
    minor: Can't open object
  #001: C:\autotest\hdf5110-StdRelease-code-10vs14\build\hdfsrc\src\H5Gint.c line 287 in H5G__open_name(): group not found
    major: Symbol table
    minor: Object not found
  #002: C:\autotest\hdf5110-StdRelease-code-10vs14\build\hdfsrc\src\H5Gloc.c line 428 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: C:\autotest\hdf5110-StdRelease-code-10vs14\build\hdfsrc\src\H5Gtraverse.c line 867 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: C:\autotest\hdf5110-StdRelease-code-10vs14\build\hdfsrc\src\H5Gtraverse.c line 639 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: C:\autotest\hdf5110-StdRelease-code-10vs14\build\hdfsrc\src\H5Gloc.c line 383 in H5G_loc_find_cb(): object 'model_weights' doesn't exist
    major: Symbol table
    minor: Object not found
Exception in thread "main" java.lang.RuntimeException: Unknown exception.
	at org.bytedeco.javacpp.hdf5$H5Location.openGroup(Native Method)
	at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.openGroups(Hdf5Archive.java:72)
	at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.getGroups(Hdf5Archive.java:190)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:181)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:139)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:60)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:147)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:271)
	at Test.main(Test.java:104)
```

I verified the directory in which keras models are present. Filing an issue since it seems like this issue is reported earlier ([https://github.com/deeplearning4j/deeplearning4j/issues/5029#issuecomment-387030566](https://github.com/deeplearning4j/deeplearning4j/issues/5029#issuecomment-387030566)) and was told to be resolved by beta version release.

My dl4j version is `1.0.0-beta` 

@maxpumperla, can you please have a look at it? Thank you!

**Comment by rahul-raj** [comment]
Attaching models exported from keras (both json & hdf5).
[model.zip](https://github.com/deeplearning4j/deeplearning4j/files/2030588/model.zip)

**Comment by rahul-raj** [comment]
Closing the ticket since I figured out the issue.
I was doing `model.save_weights` instead of `model.save`.
So there was only `weights` available in the imported model.
While `importKerasSequentialModelAndWeights` in dl4j expects both model and weights from exported model.

**Comment by treo** [comment]
@maxpumperla Maybe the error message in that case should be improved?

**Comment by maxpumperla** [comment]
@treo we could improve the docs, but this error could have been anything, so it's difficult to log something more meaningful. literally the h5 group for weights is missing
