### ISSUE TITLE
No tensorflow op found

### ISSUE THREAD

**Issue by Robert114** [deeplearning4j/deeplearning4j#5310]
i modify some based on [example ](https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/modelimport/tensorflow/LoadTensorFlowMNISTMLP.java) to import another tensorflow model,And i get some error:

`org.nd4j.linalg.exception.ND4JIllegalStateException: No tensorflow op found for Iterator possibly missing operation class?
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.mapNodeType(TFGraphMapper.java:495)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.mapNodeType(TFGraphMapper.java:36)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:219)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:69)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:107)
	at org.deeplearning4j.examples.modelimport.tensorflow.LoadTensorFlowMNISTMLP.main(LoadTensorFlowMNISTMLP.java:51)
`

`org.nd4j.linalg.exception.ND4JIllegalStateException: No tensorflow op found for MirrorPad possibly missing operation class?
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.mapNodeType(TFGraphMapper.java:495)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.mapNodeType(TFGraphMapper.java:36)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:219)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:69)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:107)
	at org.deeplearning4j.examples.modelimport.tensorflow.LoadTensorFlowMNISTMLP.main(LoadTensorFlowMNISTMLP.java:51)`

**Comment by agibsonccc** [comment]
@Robert114 mind posting your graph please?

**Comment by raver119** [comment]
`MirrorPad`

**Comment by AlexDBlack** [comment]
We now have MirrorPad - this can be closed?
https://github.com/deeplearning4j/deeplearning4j/blob/97555d548ebc337d3fdad57f046bf04138f935d7/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/transforms/MirrorPad.java
