### ISSUE TITLE
"Expected no workspace active" exception during evaluation

### ISSUE THREAD

**Issue by turambar** [deeplearning4j/deeplearning4j#5351]
Training a simple MLP on MNIST with an EvaluativeListener, I get the following workspace-related exception: `Exception in thread "main" org.nd4j.linalg.workspace.ND4JWorkspaceException: Expected no workspace active in outputOfLayerDetached - Open/active workspaces: [WS_ALL_LAYERS_ACT]`

It happens on the first call to `doEvaluation(...)` inside of the listener, so it likely has to do with the inference workspace mode...?

Here's a full stack trace for the exception:
```
Exception in thread "main" org.nd4j.linalg.workspace.ND4JWorkspaceException: Expected no workspace active in outputOfLayerDetached - Open/active workspaces: [WS_ALL_LAYERS_ACT]
	at org.nd4j.linalg.workspace.WorkspaceUtils.assertNoWorkspacesOpen(WorkspaceUtils.java:38)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1030)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doEvaluation(MultiLayerNetwork.java:3052)
	at org.deeplearning4j.optimize.listeners.EvaluativeListener.invokeListener(EvaluativeListener.java:211)
	at org.deeplearning4j.optimize.listeners.EvaluativeListener.onBackwardPass(EvaluativeListener.java:188)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2460)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2395)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:178)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:60)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:54)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1459)
	at org.deeplearning4j.distributed.BasicTrainingExperimentDriver.entryPoint(BasicTrainingExperimentDriver.java:127)
	at org.deeplearning4j.distributed.BasicTrainingExperimentDriver.main(BasicTrainingExperimentDriver.java:58)
```

**Comment by turambar** [comment]
Scratch that, it must be the **training workspace mode** -- setting training workspace mode to `NONE` eliminated the exception.

**Comment by AlexDBlack** [comment]
> It happens on the first call to doEvaluation(...) inside of the listener,

> Proposed fix above is just to scope internal evaluation call out of workspaces.

That won't work: currently (to detect bugs) we expect no workspace to be active external to that forward pass method. Even if we scope out eval, the outer WS will still be open and we'll still fail validation.

So we need to mess with the validation conditions, or mess with the listener.
I'm inclined to do the latter - probably switch from onBackwardPas to iterationDone
(which makes more sense for memory use anyway)
https://github.com/deeplearning4j/deeplearning4j/blob/74bd70162979bace33cf28b160aeb61131e13bcc/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/optimize/listeners/EvaluativeListener.java#L186-L189
