### ISSUE TITLE
Java heap space issue when running LoadGoogleModel with Google Data

### ISSUE THREAD

**Issue by seanpmac** [deeplearning4j/deeplearning4j#537]
Loading and running the Google model causes memory issues

Example:
File gModel = new File("/Developer/Vector Models/GoogleNews-vectors-negative300.bin.gz");
        Word2Vec vec = WordVectorSerializer.loadGoogleModel(gModel, true);

        InMemoryLookupTable table = (InMemoryLookupTable) vec.lookupTable();
        table.getSyn0().diviRowVector(table.getSyn0().norm2(0));

        log.info("Evaluate model....");
        String a = "rock"; String b = "alternative"; double sim = vec.similarity(a, b);
        Collection<String> similarA = vec.wordsNearest(a, 10); Collection<String> similarB = vec.wordsNearest(b, 10);
        log.info("Similarity between " + a + " and " + b + ": " + sim);
        log.info("Similar words to " + a  + ": " + similarA);
        log.info("Similar words to " + b  + ": " + similarB);

Error:
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:194)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:39)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:42)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:871)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:194)
	at org.nd4j.linalg.jblas.NDArray.<init>(NDArray.java:103)
	at org.nd4j.linalg.jblas.JblasNDArrayFactory.create(JblasNDArrayFactory.java:219)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3531)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3500)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2774)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readBinaryModel(WordVectorSerializer.java:185)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadGoogleModel(WordVectorSerializer.java:100)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadGoogleModel(WordVectorSerializer.java:79)
	at org.deeplearning4j.word2vec.Word2VecRawTextExample.main(Word2VecRawTextExample.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Configuration:
Macbook Pro 2.3 i7 with 16GB RAM
Mac OS 10.10.4
IntelliJ Community 14
~/Library/Preferences/IntelliJ IDEA14/idea.vmoptions is set to -Xmx12288m 
Java Compiler is set to -Xmx12288m

![intellij preferences](https://cloud.githubusercontent.com/assets/13562934/9122375/e00f297e-3c45-11e5-85fc-36eff8d0f639.png)
![java heap space](https://cloud.githubusercontent.com/assets/13562934/9122377/e02c7510-3c45-11e5-90c4-61aa4d4a8b49.png)

**Comment by tmbo** [comment]
Might be related to https://github.com/deeplearning4j/nd4j/issues/278

**Comment by agibsonccc** [comment]
Fixed.
