### ISSUE TITLE
SameDiff: DynamicStitch, DynamicPartition backprop failing

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5374]
Edit: still occuring as of 03/07/2018

**Dynamic Stitch**
Reproducable using: GradCheckTransforms.testDynamicStitch()
Edit: previous issue is now fixed: https://github.com/deeplearning4j/deeplearning4j/pull/5435

Now we have
```
java.lang.RuntimeException: Error populating inputs and outputs for function "dynamic_partition" of type org.nd4j.linalg.api.ops.impl.transforms.DynamicPartition

	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:6264)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:5336)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:5369)
	at org.nd4j.autodiff.gradcheck.GradCheckUtil.checkGradients(GradCheckUtil.java:349)
	at org.nd4j.autodiff.gradcheck.GradCheckUtil.checkGradients(GradCheckUtil.java:298)
	at org.nd4j.autodiff.gradcheck.GradCheckUtil.checkGradients(GradCheckUtil.java:292)
	at org.nd4j.autodiff.gradcheck.GradCheckUtil.checkGradients(GradCheckUtil.java:278)
	at org.nd4j.autodiff.gradcheck.GradCheckTransforms.testDynamicStitch(GradCheckTransforms.java:310)
Caused by: org.nd4j.linalg.exception.ND4JIllegalStateException: Unable to allocate new array. No shape found for variable index1-grad
	at org.nd4j.autodiff.samediff.SDVariable.storeAndAllocateNewArray(SDVariable.java:154)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.attemptToGetOrCreateArrForVar(DynamicCustomOp.java:227)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:207)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:146)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.populateInputsAndOutputsFromSameDiff(DynamicCustomOp.java:597)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:6261)
```

---
---

**DynamicPartition**
GradCheckTransforms.testDynamicPartition

```
Bad number of bytes requested for allocation: 0
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute. Please see above message (printed out from c++) for a possible cause of error.

java.lang.RuntimeException: Number of bytes for allocation should be positive

	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOpDouble(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1734)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:5965)
	at org.nd4j.autodiff.gradcheck.GradCheckTransforms.testDynamicPartition(GradCheckTransforms.java:297)
```

**Comment by AlexDBlack** [comment]
Confirmed passing on my branch.
