### ISSUE TITLE
DL4J - Keras import: detect if File is in JAR and either through useful exception or handle quietly

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5379]
Unsurprisingly, the HDF5 native libraries can't handle reading Files from within a JAR (unless you use a stream, of course)...

```
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: H5F.c line 586 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1236 in H5F_open(): unable to open file: time = Tue May 29 14:09:46 2018
, name = 'com/example/itayefraim/prolneural/prol1recognize-02-val_acc-1.00.hdf5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 809 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = 'com/example/itayefraim/prolneural/prol1recognize-02-val_acc-1.00.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
Exception in thread "main" java.lang.RuntimeException: Unknown exception.
	at org.bytedeco.javacpp.hdf5$H5File.allocate(Native Method)
	at org.bytedeco.javacpp.hdf5$H5File.<init>(hdf5.java:13084)
	at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.<init>(Hdf5Archive.java:63)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.modelHdf5Filename(KerasModelBuilder.java:92)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:195)
```

**Comment by saudet** [comment]
I don't think KerasModelImport is supposed to support URLs anyway, and since there is no way to specify a file inside a JAR file with just a system file path, I'm not sure this is a bug...

**Comment by AlexDBlack** [comment]
Ah, I had assumed we were using Java File objects as part of the API, which can handle Files in JARs OK - but apparently not...
https://github.com/deeplearning4j/deeplearning4j/blob/74bd70162979bace33cf28b160aeb61131e13bcc/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/KerasModelImport.java

So instead, we probably want to have a check at the Java level to see if the file actually actually exists... I'm not seeing that sort of check at present.

**Comment by saudet** [comment]
Well, maybe there's a way to pass the messages from exceptions thrown by HDF5. I'll check that up.

**Comment by saudet** [comment]
With commit https://github.com/bytedeco/javacpp-presets/commit/f463f4ff510d91da07417f9f278e8818c244d48c it's a bit better than "Unknown exception", but not much more, unfortunately:
```
HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 0:
  #000: H5F.c line 511 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1450 in H5F_open(): unable to open file: time = Wed May 30 20:11:06 2018
, name = '/path/to/nowhere', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 733 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = '/path/to/nowhere', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
Exception in thread "main" java.lang.RuntimeException: H5Fopen failed
	at org.bytedeco.javacpp.hdf5$H5File.allocate(Native Method)
	at org.bytedeco.javacpp.hdf5$H5File.<init>(hdf5.java:13422)
```
