### ISSUE TITLE
Can't calculate gradients of a ComputationGraphConfiguration network

### ISSUE THREAD

**Issue by DavidBecht** [deeplearning4j/deeplearning4j#5382]
https://gist.github.com/DavidBecht/8281fb0fb99bdec06344fc8d91d671f1

java.lang.NullPointerException
	at org.nd4j.linalg.lossfunctions.impl.LossL2.computeGradient(LossL2.java:110)
	at org.nd4j.linalg.lossfunctions.impl.LossMSE.computeGradient(LossMSE.java:56)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.getGradientsAndDelta(BaseOutputLayer.java:183)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.backpropGradient(BaseOutputLayer.java:156)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doBackward(LayerVertex.java:143)
	at org.deeplearning4j.nn.graph.ComputationGraph.calcBackpropGradients(ComputationGraph.java:2427)
	at org.deeplearning4j.nn.graph.ComputationGraph.backpropGradient(ComputationGraph.java:2247)

**Comment by AlexDBlack** [comment]
What you are doing is invalid - you can't calculate gradients based on an external error with an output layer... output layers calculate errors from labels. In fact, I don't know why you aren't getting an exception for that configuration (I thought we already checked for trying to do that).
You probably want to replace that OutputLayer with a DenseLayer.

So from the perspective of DL4J, the only issue here I think is a lack of validation/lack of a useful exception.

**Comment by AlexDBlack** [comment]
I've added additional validation to throw a useful exception for this case here: https://github.com/deeplearning4j/deeplearning4j/pull/5391
