### ISSUE TITLE
Can't train with GPU

### ISSUE THREAD

**Issue by Yu-Hang** [deeplearning4j/deeplearning4j#5392]
Hi, 
I'm trying to train with GPU using dl4j with IntelliJ IDE.

Here is my POM file:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.dp</groupId>
    <artifactId>importK</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <nd4j.backend>nd4j-cuda-9.1-platform</nd4j.backend>
        <dl4j.version>1.0.0-alpha</dl4j.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.datavec</groupId>
            <artifactId>datavec-api</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-modelimport</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-jdk14</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-ui_2.10</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>


</project>
```

When I go to Deeplearning4j UI, under System, it says I'm using CPU instead of GPU. Please let me know what I need to do to switch to GPU.

Thanks,
Hang

**Comment by raver119** [comment]
instead of 

```
<dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
```

you should use another dependency, i.e. `nd4j-cuda-9.1-platform`.

Also, please make sure version matches installed CUDA Toolkit version

**Comment by Yu-Hang** [comment]
@raver119 is the CUDA Toolkit something I need to install separately? Or is it something I need to add in dependencies?

**Comment by Yu-Hang** [comment]
So, I just added: 

```
 <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-cuda-8.0-platform</artifactId>
            <version>1.0.0-alpha</version>
        </dependency>
```

But I'm getting error:

```
May 30, 2018 3:51:28 PM org.nd4j.linalg.factory.Nd4jBackend load
WARNING: Skipped [JCublasBackend] backend (unavailable): java.lang.UnsatisfiedLinkError: C:\Users\yuh5\.javacpp\cache\cuda-8.0-6.0-1.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jnicuda.dll: Can't find dependent libraries
May 30, 2018 3:51:29 PM org.reflections.Reflections scan
INFO: Reflections took 312 ms to scan 12 urls, producing 488 keys and 2422 values 
May 30, 2018 3:51:29 PM org.nd4j.linalg.factory.Nd4jBackend load
WARNING: Skipped [JCublasBackend] backend (unavailable): java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.cuda
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:786)
	at org.dp.importK.malariaModel.Model2(malariaModel.java:197)
	at org.dp.importK.malariaModel.run(malariaModel.java:112)
	at org.dp.importK.malariaModel.main(malariaModel.java:56)
Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6230)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:207)
	... 4 more
Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:259)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6227)
	... 5 more
```

**Comment by raver119** [comment]
Perfect! 

Show me output of `nvcc --version` please

**Comment by Yu-Hang** [comment]
C:\Users\yuh5>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Mon_Jan__9_17:32:33_CST_2017
Cuda compilation tools, release 8.0, V8.0.60

**Comment by raver119** [comment]
When you've installed CUDA Toolkit? Was computer restarted after that?

**Comment by Yu-Hang** [comment]
@raver119 Thanks. Reboot did the trick

**Comment by raver119** [comment]
Perfect!
