### ISSUE TITLE
SameDiff: Can't handle ops with variable number of output variables

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5424]
It relies on the descriptor to get the number of outputs, which may return -1 for variable outputs.

Of course, it's probably possible to override outputVariables(String) in DynamicCustomOp, but there is probably a better solution...

```
org.nd4j.linalg.exception.ND4JIllegalStateException: No output variables found!
	at org.nd4j.autodiff.samediff.SameDiff.generateOutputVariableForOp(SameDiff.java:4913)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:164)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:146)
	at org.nd4j.linalg.api.ops.impl.shape.Concat.doDiff(Concat.java:195)
	at org.nd4j.autodiff.functions.DifferentialFunction.diff(DifferentialFunction.java:536)
	at org.nd4j.autodiff.samediff.SameDiff$3.define(SameDiff.java:5466)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:5296)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:5280)
	at org.nd4j.autodiff.samediff.SameDiff.createGradFunction(SameDiff.java:5378)
	at org.nd4j.autodiff.gradcheck.GradCheckUtil.validateInternalState(GradCheckUtil.java:529)
	at org.nd4j.autodiff.gradcheck.GradCheckUtil.checkGradients(GradCheckUtil.java:282)
	at org.nd4j.autodiff.gradcheck.GradCheckUtil.checkGradients(GradCheckUtil.java:266)
	at org.nd4j.autodiff.gradcheck.GradCheckUtil.checkGradients(GradCheckUtil.java:260)
	at org.nd4j.autodiff.gradcheck.GradCheckUtil.checkGradients(GradCheckUtil.java:246)
	at org.nd4j.autodiff.gradcheck.BaseGradCheck.check(BaseGradCheck.java:47)
	at org.nd4j.autodiff.gradcheck.GradCheckMisc.testConcat(GradCheckMisc.java:74)
```

**Comment by AlexDBlack** [comment]
Actually, nevermind - there is a way to override it, it's just not documented - and the exception doesn't mention it :)
