### ISSUE TITLE
No VGGFACE Weights available for FaceNetNN4Small2 zoo model 

### ISSUE THREAD

**Issue by Haitamz** [deeplearning4j/deeplearning4j#5443]
Exception in thread "main" java.lang.UnsupportedOperationException: Pretrained VGGFACE weights are not available for this model.
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:54)
	at org.deeplearning4j.examples.dataexamples.ImportFaceNet.main(ImportFaceNet.java:11)

**Comment by crockpotveggies** [comment]
Hi there, these weights are available for VGG16 model, not the FaceNet variant model.

**Comment by crockpotveggies** [comment]
https://github.com/deeplearning4j/deeplearning4j/blob/883f23cb4f3bcbd23387e79b4aaa48313f2ec963/deeplearning4j/deeplearning4j-zoo/src/main/java/org/deeplearning4j/zoo/model/VGG16.java#L58
