### ISSUE TITLE
DL4J: Benchmarks, resnet50: can't run batch size 16, can run batch 32

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5461]
I believe this is related to how CuDNN is configured... this particular model is set to ```ConvolutionLayer.AlgoMode.PREFER_FASTEST```; I suspect it's the CuDNN mode internally that is the reason (i.e., batch size 32 uses a different mode that requires less memory).

Now, CuDNN (or at least some of the more recent versions?) does support specifying a maximum workspace size. We may be able to inspect the amount of available memory, and have CuDNN base it's algorithm selection on that.
Alternatively, if we detect an OOM, we might be able to enforce use of a less memory-intensive algorithm rather than failing outright.

```
Running test: v100beta_cuda91-cudnn, batch size 16
Exception in thread "main" java.lang.OutOfMemoryError: Failed to allocate memory within limits: totalBytes = 9G + 9G > maxBytes = 12G
        at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:572)
        at org.deeplearning4j.nn.layers.BaseCudnnHelper$DataCache.<init>(BaseCudnnHelper.java:123)
        at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper.preOutput(CudnnConvolutionHelper.java:444)
        at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:323)
        at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.activate(ConvolutionLayer.java:392)
        at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:105)
        at org.deeplearning4j.nn.graph.ComputationGraph.ffToLayerActivationsInWS(ComputationGraph.java:1946)
        at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1310)
        at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1280)
        at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:178)
        at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:60)
        at org.deeplearning4j.optimize.Solver.optimize(Solver.java:54)
        at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1104)
        at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1036)
        at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:978)
        at org.deeplearning4j.benchmarks.BaseBenchmark.benchmark(BaseBenchmark.java:103)
        at org.deeplearning4j.benchmarks.BaseBenchmark$Benchmark.execute(BaseBenchmark.java:40)
        at org.deeplearning4j.benchmarks.BenchmarkCnn.run(BenchmarkCnn.java:103)
        at org.deeplearning4j.benchmarks.BenchmarkCnn.main(BenchmarkCnn.java:118)
Running test: v100beta_cuda91-cudnn, batch size 32
```

**Comment by saudet** [comment]
We can set `ConvolutionLayer.AlgoMode.NO_WORKSPACE` though.

**Comment by AlexDBlack** [comment]
@saudet That's not a good solution IMO - we want as fast as possible within the constraints of the available memory.
NO_WORKSPACE minimizes the memory, but will have a performance impact.

**Comment by AlexDBlack** [comment]
Fixed in previous optimization PRs; now can run batch sizes up to 192 on that machine.
