### ISSUE TITLE
DL4J: DataSetIteratorSplitter getLabels should return labels from underlying

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5521]
```
java.lang.UnsupportedOperationException: null
	at org.deeplearning4j.datasets.iterator.DataSetIteratorSplitter$2.getLabels(DataSetIteratorSplitter.java:188) ~[deeplearning4j-utility-iterators-1.0.0-beta.jar:na]
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.evaluate(MultiLayerNetwork.java:3181) ~[deeplearning4j-nn-1.0.0-beta.jar:na]
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.evaluate(MultiLayerNetwork.java:3102) ~[deeplearning4j-nn-1.0.0-beta.jar:na]
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.evaluate(MultiLayerNetwork.java:2958) ~[deeplearning4j-nn-1.0.0-beta.jar:na]
	at org.deeplearning4j.arbiter.scoring.impl.EvaluationScoreFunction.score(EvaluationScoreFunction.java:38) ~[arbiter-deeplearning4j-1.0.0-beta.jar:na]
	at org.deeplearning4j.arbiter.scoring.impl.BaseNetScoreFunction.score(BaseNetScoreFunction.java:28) ~[arbiter-deeplearning4j-1.0.0-beta.jar:na]
	at org.deeplearning4j.arbiter.task.MultiLayerNetworkTaskCreator$DL4JLearningTask.callHelper(MultiLayerNetworkTaskCreator.java:207) [arbiter-deeplearning4j-1.0.0-beta.jar:na]
	at org.deeplearning4j.arbiter.task.MultiLayerNetworkTaskCreator$DL4JLearningTask.call(MultiLayerNetworkTaskCreator.java:114) [arbiter-deeplearning4j-1.0.0-beta.jar:na]
	at org.deeplearning4j.arbiter.task.MultiLayerNetworkTaskCreator$DL4JLearningTask.call(MultiLayerNetworkTaskCreator.java:85) [arbiter-deeplearning4j-1.0.0-beta.jar:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:na]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

Evaluate should probably also have a try/catch for exceptions here too.

**Comment by rahul-raj** [comment]
Whether these fixes are only in snapshot mode, is it planned to be released on next release?
I'm referring to this -> https://github.com/deeplearning4j/deeplearning4j/issues/5445
I as getting the same error and would like to test for the same.

**Comment by AlexDBlack** [comment]
Yes, the fix is currently only available on snapshots.
As to the next release: We don't have a date yet. But I think it's unlikely to be in the next couple of weeks. Can't say more specifically than that, at this point.
Other than using snapshots, another workaround is simply copying the updated class to your project and using that instead.

**Comment by rahul-raj** [comment]
Can you confirm what all files to be copied?
Is it only `DataSetIteratorSplitter.java` or
all the files in here too? 
https://github.com/deeplearning4j/deeplearning4j/commit/e21fe4799a767fe83705bd0c42e492aba96284dc#diff-a4098e408c8a13d8d6b86828a975c89e

Because when I just copy paste the class (`DataSetIteratorSplitter.java`) into my workspace, multiple errors were shown. I'm just suspecting that other changes are also need to copy here?

I copied both 
https://raw.githubusercontent.com/deeplearning4j/deeplearning4j/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/api/iterator/DataSetIterator.java 
&
https://raw.githubusercontent.com/deeplearning4j/deeplearning4j/15497a254859fc56e7edfcbe5a06dc1c670da56e/deeplearning4j/deeplearning4j-data/deeplearning4j-utility-iterators/src/main/java/org/deeplearning4j/datasets/iterator/DataSetIteratorSplitter.java

**Comment by AlexDBlack** [comment]
Oh, I think it'll be missing a few methods for DataSetIterator (we cleaned up the API a bit).
You can just add those methods (your IDE should tell you which) and throw UnsupportedOperationException for them.

**Comment by rahul-raj** [comment]
Just added methods to be implemented, but most of them looks like this:
![image](https://user-images.githubusercontent.com/517415/41806320-5c80a70a-76d9-11e8-8506-b8340ec6c5a5.png)

**Comment by AlexDBlack** [comment]
Looks like you are missing the project lombok intellij plugin. Install that (via intellij plugins), and you should be fine.
https://projectlombok.org/

**Comment by AlexDBlack** [comment]
Looks like you don't have logging configured, so you're probably not seeing the underlying cause of this.
My guess is that all models are failing and hence there is no best model.

**Comment by rahul-raj** [comment]
@AlexDBlack 
Just reimported all dependencies and logging was back to function. 
I'm seeing:  `INFO  o.d.a.o.r.BaseOptimizationRunner - Task 28 failed during execution: java.lang.UnsupportedOperationException`  . 

Here is the gist:
https://gist.github.com/rahul-raj/05df746f764287812fd835a835710ca3

**Comment by AlexDBlack** [comment]
> java.lang.UnsupportedOperationException: null
	at org.deeplearning4j.datasets.iterator.DataSetIteratorSplitter$2.getLabels(DataSetIteratorSplitter.java:188) ~[deeplearning4j-utility-iterators-1.0.0-beta.jar:na]

Looks like you're still using the old version from 1.0.0-beta.
If you've copied the class to your project, you'll need to change the import for it also.

**Comment by rahul-raj** [comment]
![image](https://user-images.githubusercontent.com/517415/41849249-da081d8c-789d-11e8-9f35-af0ddd157ef8.png)
![image](https://user-images.githubusercontent.com/517415/41849272-eda35640-789d-11e8-8bac-89b439fb068f.png)

I just re-arranged as you mentioned, but why this error comes? Just verified that both the files are referring to local versions.

**Comment by AlexDBlack** [comment]
That's a java type error, and (if I'm correct about the cause) it's legitimate.

Your local copy of ```DataSetIteratorSplitter``` should extend the DL4J version of DataSetIterator - my guess is you have copied DataSetIterator interface also (which you don't want to do).

**Comment by rahul-raj** [comment]
Ahh I thought I should copy both of them since both of them have changes included for the fix. So, Now I'm going to run them with just the local copy of  `DataSetIteratorSplitter` alone.
