### ISSUE TITLE
need help about running YOLO2

### ISSUE THREAD

**Issue by muxiangwei** [deeplearning4j/deeplearning4j#5556]
code ：
```
public static void main(String[] args) throws Exception {
        // parameters for model;
        int width = 480;
        int height = 300;
        int nChannels = 3;
        int gridWidth = 15;
        int gridHeight = 10;

        //class
        int nClasses = 5;

        // parameters for the Yolo2OutputLayer
        int nBoxes = 5;
        double lambdaNoObj = 0.5;
        double lambdaCoord = 1.0;
        double[][] priorBoxes = {{2, 5}, {2.5, 6}, {3, 7}, {3.5, 8}, {4, 9}};
        double detectionThreshold= 0.8;

        // parameters for the training phase
        int batchSize = 20;
        int nEpochs = 500;
        double learningRate = 1e-4;
        double lrMomentum = 0.9;

        log.info("Load data...");

        String dataDir = "F:\\java projects\\DLPro\\src\\main\\resources\\surface_data\\train";
        File imageDir = new File(dataDir, "JPEGImages");

        int seed = 123;
        Random rng = new Random(seed);
        RandomPathFilter pathFilter = new RandomPathFilter(rng) {
            protected boolean accept(String name) {
                name = name.replace("/JPEGImages/", "/Annotations/").replace(".jpg", ".xml");
                try {
                    return new File(new URI(name)).exists();
                } catch (URISyntaxException ex) {
                    throw new RuntimeException(ex);
                }
            }
        };

        InputSplit[] data = new FileSplit(imageDir, NativeImageLoader.ALLOWED_FORMATS, rng).sample(pathFilter, 0.8, 0.2);
        InputSplit trainData = data[0];
        InputSplit testData = data[1];


        ObjectDetectionRecordReader recordReaderTrain = new ObjectDetectionRecordReader(height, width, nChannels,
                gridHeight, gridWidth, new VocLabelProvider(dataDir));
        recordReaderTrain.initialize(trainData);


        ObjectDetectionRecordReader recordReaderTest = new ObjectDetectionRecordReader(height, width, nChannels,
                gridHeight, gridWidth, new VocLabelProvider(dataDir));
        recordReaderTest.initialize(testData);


        // ObjectDetectionRecordReader performs regression, so we need to specify it here
        RecordReaderDataSetIterator train = new RecordReaderDataSetIterator(recordReaderTrain, batchSize, 1, 1, true);
        train.setPreProcessor(new ImagePreProcessingScaler(0, 1));

        RecordReaderDataSetIterator test = new RecordReaderDataSetIterator(recordReaderTest, 1, 1, 1, true);
        test.setPreProcessor(new ImagePreProcessingScaler(0, 1));

        ComputationGraph model;
        String modelFilename = "model_surface_YOLO2.zip";


        if (new File(modelFilename).exists()) {
            log.info("Load model...");
            model = ModelSerializer.restoreComputationGraph(modelFilename);
        } else {
            log.info("Build model...");
            ComputationGraph graph =  (ComputationGraph) YOLO2.builder().build().initPretrained();
            INDArray priors = Nd4j.create(priorBoxes);

            FineTuneConfiguration fineTuneConf = new FineTuneConfiguration.Builder()
                    .seed(seed)
                    .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                    .gradientNormalization(GradientNormalization.RenormalizeL2PerLayer)
                    .gradientNormalizationThreshold(1.0)
                    .updater(new Adam.Builder().learningRate(1e-3).build())
                    .l2(0.00001)
                    .activation(Activation.IDENTITY)
                    .trainingWorkspaceMode(WorkspaceMode.SEPARATE)
                    .inferenceWorkspaceMode(WorkspaceMode.SEPARATE)
                    .build();

            model = new TransferLearning.GraphBuilder(graph)
                    .fineTuneConfiguration(fineTuneConf)
                    .addLayer("outputs", new Yolo2OutputLayer.Builder()
                                    .boundingBoxPriors(priors)
                                    .build(),
                            "conv2d_23")
                    .setOutputs("outputs")
                    .build();

           System.out.println(model.summary(InputType.convolutional(height, width, nChannels)));

            log.info("Train model...");
            model.setListeners(new ScoreIterationListener(1));
            for (int i = 0; i < nEpochs; i++) {
                train.reset();
                while (train.hasNext()) {
                    model.fit(train.next());
                }
                log.info("*** Completed epoch {} ***", i);
            }
            ModelSerializer.writeModel(model, modelFilename, true);
        } }}
```

the exception like this：
```
Exception in thread "main" org.deeplearning4j.nn.conf.inputs.InvalidInputTypeException: Invalid input: MergeVertex cannot merge CNN activations of different width/heights:first [channels,width,height] = [256,15,9], input 1 = [1024,15,10]
	at org.deeplearning4j.nn.conf.graph.MergeVertex.getOutputType(MergeVertex.java:165)
	at org.deeplearning4j.nn.graph.ComputationGraph.summary(ComputationGraph.java:3943)
	at SurfaceObjectDetectionByYOLO2.main(SurfaceObjectDetectionByYOLO2.java:148)

```
The Exception occurs in this line：
“System.out.println(model.summary(InputType.convolutional(height, width, nChannels)));”

How to fix it or any suggestion？
thanks！

**Comment by AlexDBlack** [comment]
Looks like this is simply due to using invalid input sizes.
Basically, your input dimensions need to be a multiple of 32 - because the YOLO2 net does down-sampling by a factor of 32x between the input and the output.
If I switch the input dimension to [480,320] from [480,300] I can run the model using your code, without issue.
