### ISSUE TITLE
fine tuning error after update to 1.0-alpha

### ISSUE THREAD

**Issue by fmorbinitc** [deeplearning4j/deeplearning4j#5571]
After updating the 1.0-alpha and changing the code to:

`    currentBest = new TransferLearning.GraphBuilder(currentBest)
        .fineTuneConfiguration(FineTuneConfiguration.builder().updater(new Adam(0.001))
            .build())
        .build();
`
where currentBest is a ComputationGraph obtained by cloning the current trained network.
Running that line causes this exception: (was working in 0.8)

`java.lang.IllegalArgumentException: Unknown parameter name: "ffW"
	at org.deeplearning4j.nn.conf.layers.AbstractLSTM.getL1ByParam(AbstractLSTM.java:56)
	at org.deeplearning4j.nn.conf.layers.recurrent.Bidirectional.getL1ByParam(Bidirectional.java:159)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration.setLayerParamLR(NeuralNetConfiguration.java:182)
	at org.deeplearning4j.nn.transferlearning.FineTuneConfiguration.applyToNeuralNetConfiguration(FineTuneConfiguration.java:395)
	at org.deeplearning4j.nn.transferlearning.TransferLearning$GraphBuilder.fineTuneConfiguration(TransferLearning.java:484)
`
please let me know if i should further change the finetuning  configuration to make it work on 1.0-alpha.

**Comment by AlexDBlack** [comment]
Mind trying again with 1.0.0-beta (and if that doesn't work - snapshots - https://deeplearning4j.org/snapshots)?

I have a feeling this has already been fixed.

**Comment by fmorbinitc** [comment]
Hi, i cannot test. I tried switching to beta but i get other errors, including:
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1335)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1280)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:178)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:60)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:54)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1104)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1036)
`
during retraining (As format is changed and i wanted to test training fresh with beta before trying adaptation). I'll need more time figuring out what has changed to cause that out of bound exception.

**Comment by AlexDBlack** [comment]
Post your full code in a a gist (https://gist.github.com/) and then paste link here.
Those sorts of exceptions are usually due to some sort of incorrect use of ComputationGraph, but it's not possible to say for sure without seeing exactly what you are doing.

**Comment by fmorbinitc** [comment]
here is the training code i was trying that was working with 0.8 and alpha: https://gist.github.com/fmorbinitc/4d8b8df606bb18b46faf61f08371232b

**Comment by AlexDBlack** [comment]
I'm still not able to reproduce this.
I created a cut-down version of your code (because, obviously I can't run that) - and it runs fine.
https://gist.github.com/AlexDBlack/0b3a2bed6e9cae9c8147fe4e3308cdb8
Can you provide a minimal example that I can run to reproduce this issue?

**Comment by AlexDBlack** [comment]
Closing this due to inactivity and being unable to reproduce.
@fmorbinitc If you are still having problems here, I'd be happy to look into this further - but I'll need a minimal example to reproduce this locally first.
