### ISSUE TITLE
Exception in RL4J when learning with DQN with convolutional net and 4 channels

### ISSUE THREAD

**Issue by borkox** [deeplearning4j/deeplearning4j#5612]
Hi,
I just stuck with exception which doesn't allow me to make my learning correct.
org.nd4j.linalg.exception.ND4JIllegalStateException: X, Y and Z arguments should have the same length for PairwiseTransform. x: length 600, shape [12, 50]; y: 2400, shape [4, 12, 50]; z: 600, shape [12, 50]
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:802)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:121)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:1454)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.put(BaseNDArray.java:2543)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscrete.setTarget(QLearningDiscrete.java:201)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscrete.trainStep(QLearningDiscrete.java:163)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.QLearning.trainEpoch(QLearning.java:93)
	at org.deeplearning4j.rl4j.learning.sync.SyncLearning.train(SyncLearning.java:38)
	at com.rltrader.rl.dqn.LearnerDQN.startLearn(LearnerDQN.java:91)
	at com.rltrader.App.run(App.java:48)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:797)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at com.rltrader.App.main(App.java:37)

A Little context about the problem:
I have convolutional net which receives 12 rows with width of 50. For each one I have 4 channels(Depth).
The same configuration is running with AsyncLearning and computation graph. When I tried to make this with DQN and QLearning I stuck with this exception. I will provide some code how I build my network:
```

package com.rltrader.rl.dqn;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Value;
import lombok.extern.slf4j.Slf4j;
import org.deeplearning4j.nn.api.OptimizationAlgorithm;
import org.deeplearning4j.nn.conf.*;
import org.deeplearning4j.nn.conf.inputs.InputType;
import org.deeplearning4j.nn.conf.layers.*;
import org.deeplearning4j.nn.conf.preprocessor.CnnToFeedForwardPreProcessor;
import org.deeplearning4j.nn.conf.preprocessor.FeedForwardToRnnPreProcessor;
import org.deeplearning4j.nn.conf.preprocessor.RnnToCnnPreProcessor;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.optimize.api.TrainingListener;
import org.deeplearning4j.optimize.listeners.ScoreIterationListener;
import org.deeplearning4j.rl4j.network.ac.ActorCriticLoss;
import org.deeplearning4j.rl4j.network.dqn.DQN;
import org.deeplearning4j.rl4j.network.dqn.DQNFactory;
import org.deeplearning4j.rl4j.util.Constants;
import org.nd4j.linalg.activations.Activation;
import org.nd4j.linalg.learning.config.*;
import org.nd4j.linalg.lossfunctions.LossFunctions;

@Value
@Slf4j
public class DQNFactoryConvolution implements DQNFactory {


    Configuration conf;

    public DQN buildDQN(int shapeInputs[], int numOutputs) {
        if (shapeInputs.length == 1)
            throw new AssertionError("Impossible to apply convolutional layer on a shape == 1");

        int h = (((shapeInputs[1] - 1) / 1 + 1) - 1) / 1 + 1;
        int w = (((shapeInputs[2] - 4) / 2 + 1) - 3) / 3 + 1;

        log.info("Output from convolution layers: h:{}, w:{}", h, w);

        NeuralNetConfiguration.ListBuilder confB =
                new NeuralNetConfiguration.Builder().seed(Constants.NEURAL_NET_SEED)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .l2(conf.getL2())
                .updater(conf.getUpdater() != null ? conf.getUpdater() : new Adam(conf.learningRate))
                .weightInit(WeightInit.XAVIER)
                        .l2(conf.getL2())
                        .list();

        confB.layer(0, new ConvolutionLayer
                .Builder(1, 4)
                .nIn(shapeInputs[0])
                .nOut(16)
                .stride(1, 2)
                .activation(Activation.RELU).build());


        confB.layer(1, new ConvolutionLayer
                .Builder(1, 3)
                .nOut(32)
                .stride(1, 3)
                .activation(Activation.RELU)
                .build());

        confB.layer(2, new DenseLayer
                .Builder()
                .nOut(256)
                .activation(Activation.RELU)
                .build());

        confB.layer(3, new OutputLayer.Builder(LossFunctions.LossFunction.MSE)
                .activation(Activation.IDENTITY)
                .nOut(numOutputs)
                .build());

        confB.setInputType(InputType.convolutional(shapeInputs[1], shapeInputs[2], shapeInputs[0]));
        MultiLayerConfiguration mlnconf = confB.pretrain(false).backprop(true).build();
        MultiLayerNetwork model = new MultiLayerNetwork(mlnconf);
        model.init();
        if (conf.getListeners() != null) {
            model.setListeners(conf.getListeners());
        } else {
            model.setListeners(new ScoreIterationListener(Constants.NEURAL_NET_ITERATION_LISTENER));
        }

        return new DQN(model);
    }


    @AllArgsConstructor
    @Builder
    @Value
    public static class Configuration {

        IUpdater updater;
        double l2;
        TrainingListener[] listeners;
        double learningRate;

    }

}

```

**Comment by borkox** [comment]
Versions I am using are:
        <nd4j.version>1.0.0-SNAPSHOT</nd4j.version>
        <nd4j.backend>nd4j-native</nd4j.backend>
        <rl4j.version>1.0.0-SNAPSHOT</rl4j.version>
        <dl4j.version>1.0.0-SNAPSHOT</dl4j.version>
        <scala.binary.version>2.11</scala.binary.version>

**Comment by borkox** [comment]
![image](https://user-images.githubusercontent.com/21053237/41498245-46744510-7171-11e8-9fc8-056084aba344.png)
I hope that helps

**Comment by saudet** [comment]
Are you saying it works with 3 channels, but not 4 channels?

**Comment by borkox** [comment]
It doesn't work (or I don't know how to make it work) with channels at all. I am talking for QLearning in RL4J package.

**Comment by saudet** [comment]
The ALE.java example uses 3 channels with QLearning and it works fine for me.
Are you getting an error with that example as well?

**Comment by borkox** [comment]
Ok, I am not sure why ALE is running, while watching the code I am thinking that as first input to CNN you are using HistoryProcessor.getShape()[0] which is 4 and maybe your colours are lost while resizing in HistoryProcessor. But I am looking that you are creating the network with shape:

```
public int[] getShape() {
            return new int[] {getHistoryLength(), getCroppingHeight(), getCroppingWidth()};
        }
```
Maybe you are thinking you are using channels, but instead you are using the history. Can you please place a breakpoint in DQNFactoryStdConv line 34 and tell me with what shape the network is created? If ALE is using history of 4 and 3 channels and cropW = 84 and cropH = 84 what is the shape of ALE network?

**Comment by saudet** [comment]
So, you're saying that the ALE example is also running fine for you? Ok, good. Could you please create a small example like that, but that doesn't work? I'll take a look into what's not working on that example. Thanks!

**Comment by saudet** [comment]
Though it does look like all images are converted into grayscale, and that the dimension typically used for image channels is used by a series of image in time. I suppose it doesn't support channels within an image. @rubenfiszel Is this how you designed it?

**Comment by borkox** [comment]
I didn't run the ALE example but I study the code pretty well. So probably the rl4j is not designed to run with history and channels together.

**Comment by rubenfiszel** [comment]
Hello. This seems likely although a refactor of the codebase where grayscale is 1 channel shouldn't be too hard. You would need to check the size of the dimension. I'm pretty sure I already did it to check if the input was 1 dimensional. Now you need to check if it's 3 dimensional.

**Comment by saudet** [comment]
I suppose we could also generalize that a bit by stacking all image channels together in the HistoryProcessor and end up with say 9 channels for 3 original images with 3 channels, right? 

@borkox Sounds like something you could work on?

**Comment by agibsonccc** [comment]
Closing — references a removed/rewritten subsystem (DataVec, NLP/Word2Vec, Model Zoo, Spark, UI, or Arbiter). These have been fundamentally rewritten or removed in the upcoming release. Please open a new issue if you experience similar problems with the new version.
