### ISSUE TITLE
Saved model JSON is not a valid ComputationGraphConfiguration

### ISSUE THREAD

**Issue by acs254** [deeplearning4j/deeplearning4j#5615]
I get the following Exception when trying to restore a zipped CNN model using DL4J 1.0.0-alpha:

```
Exception in thread "main" java.lang.RuntimeException: Error deserializing JSON ComputationGraphConfiguration. Saved model JSON is not a valid ComputationGraphConfiguration
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:605)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:464)
	at com.amazon.lola.category.categories.GeneralCNN.<init>(GeneralCNN.java:39)
	at com.amazon.lola.scorer.Scorer.<init>(Scorer.java:35)
	at com.amazon.lola.scorer.Scorer.main(Scorer.java:71)
```

My code is very simple: 

```
File graph = new File("/home/.../LolaCNN-2.zip");
ComputationGraph restored = ModelSerializer.restoreComputationGraph(graph)
```

You can see my model [here](https://s3-us-west-2.amazonaws.com/public-lola-files/LolaCNN-2.zip). I have confirmed that this model is re-loadable as a ComputationGraph using 0.9.1.

**Comment by AlexDBlack** [comment]
What version of DL4J was this model created with?

**Comment by acs254** [comment]
Version 0.9.1

**Comment by AlexDBlack** [comment]
I can load this model fine in 1.0.0-beta.
Try with 1.0.0-beta, and if you still have trouble, we can re-open this.

**Comment by acs254** [comment]
Any reason why it might work w/ 1.0.0-beta and not alpha?

**Comment by acs254** [comment]
Do you recommend upgrading every library to 1.0.0-beta, or can I get away with upgrading only one (or a few) of the libraries? I ask because due to corporate policies, it's fairly arduous to upgrade 3P libraries.

**Comment by AlexDBlack** [comment]
We release all libraries at once, and don't intend for users to mix versions. The reason for that is that, apart from API changes, we often add new ops/functionality into ND4J for use in DL4J, for example.
So unfortunately you'll have to upgrade all versions.
