### ISSUE TITLE
Wrong mask length in GlobalPoolingLayer

### ISSUE THREAD

**Issue by shaulz** [deeplearning4j/deeplearning4j#5624]
I have made a small modification to CnnSentenceClassificationExample by adding SubsamplingLayer after each convolutional layer.
The SubsamplingLayer has a stride of 2, so the input length is decreased from 256 to 128.
It seems that the input mask to the GlobalPoolingLayer is not updated and execution gives the following error:

Exception in thread "main" java.lang.UnsupportedOperationException: Masked global pooling with on CNN data currently only supports data with h=1 or w=1:
 input activations must have shape [minibatchSize,channels,height=1,width] or [minibatchSize,channels,height,width=1] with  mask array of shape [minibatchSize,width] or [minibatchSize,height] respectively.
 Got 4d activations array (shape [8, 300, 128, 1]) and 2d mask array (shape [8, 256]) (layer name: globalPool, layer index: 8, layer type: GlobalPoolingLayer)
	at org.deeplearning4j.nn.layers.pooling.GlobalPoolingLayer.activate(GlobalPoolingLayer.java:158)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:105)
	at org.deeplearning4j.nn.graph.ComputationGraph.ffToLayerActivationsInWS(ComputationGraph.java:1946)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1310)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1280)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:178)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:60)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:54)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1104)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1036)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:978)
	at org.deeplearning4j.examples.convolution.sentenceclassification.CnnSentenceClassificationExample.main(CnnSentenceClassificationExample.java:142)

Here is the modified network from CnnSentenceClassificationExample.java

`ComputationGraphConfiguration config = new NeuralNetConfiguration.Builder()
            .trainingWorkspaceMode(WorkspaceMode.SINGLE).inferenceWorkspaceMode(WorkspaceMode.SINGLE)
            .weightInit(WeightInit.RELU)
            .activation(Activation.LEAKYRELU)
            .updater(new Adam(0.01))
            .convolutionMode(ConvolutionMode.Same)      //This is important so we can 'stack' the results later
            .l2(0.0001)
            .graphBuilder()
            .addInputs("input")
            .addLayer("cnn3", new ConvolutionLayer.Builder()
                .kernelSize(3,vectorSize)
                .stride(1,vectorSize)
                .nIn(1)
                .nOut(cnnLayerFeatureMaps)
                .build(), "input")
             .addLayer("cnn3Pool", new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.MAX)
                .kernelSize(2, 1)
                .stride(2, 1)
                .build(), "cnn3")
            .addLayer("cnn4", new ConvolutionLayer.Builder()
                .kernelSize(4,vectorSize)
                .stride(1,vectorSize)
                .nIn(1)
                .nOut(cnnLayerFeatureMaps)
                .build(), "input")
             .addLayer("cnn4Pool", new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.MAX)
                .kernelSize(2, 1)
                .stride(2, 1)
                .build(), "cnn4")
            .addLayer("cnn5", new ConvolutionLayer.Builder()
                .kernelSize(5,vectorSize)
                .stride(1,vectorSize)
                .nIn(1)
                .nOut(cnnLayerFeatureMaps)
                .build(), "input")
            .addLayer("cnn5Pool", new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.MAX)
                .kernelSize(2, 1)
                .stride(2, 1)
                .build(), "cnn5")
            .addVertex("merge", new MergeVertex(), "cnn3Pool", "cnn4Pool", "cnn5Pool")      //Perform depth concatenation
            .addLayer("globalPool", new GlobalPoolingLayer.Builder()
                .poolingType(globalPoolingType)
                .dropOut(0.5)
                .build(), "merge")
            .addLayer("out", new OutputLayer.Builder()
                .lossFunction(LossFunctions.LossFunction.MCXENT)
                .activation(Activation.SOFTMAX)
                .nIn(3*cnnLayerFeatureMaps)
                .nOut(2)    //2 classes: positive or negative
                .build(), "globalPool")
            .setOutputs("out")
            .build();`

**Comment by shaulz** [comment]
[CnnSentenceClassificationExample.zip](https://github.com/deeplearning4j/deeplearning4j/files/2110626/CnnSentenceClassificationExample.zip)

**Comment by AlexDBlack** [comment]
Thanks for reporting: confirmed fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/5942
