### ISSUE TITLE
NeuralNetConfigurationTest::testNeuralNetConfigAPI - convType mismatch

### ISSUE THREAD

**Issue by EronWright** [deeplearning4j/deeplearning4j#567]
Stack trace:
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.deeplearning4j.nn.conf.NeuralNetConfLayerBuilderTest.testNeuralNetConfigAPI(NeuralNetConfLayerBuilderTest.java:96)
```

Line 96:
```
assertTrue(conv.conf().getConvolutionType().equals(newConvType));
```

A similar manifestation:
```
testLayerBuilderAPI(org.deeplearning4j.nn.layers.LayerBuilderTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.deeplearning4j.nn.layers.LayerBuilderTest.testLayerBuilderAPI(LayerBuilderTest.java:51)

```
Line 51:
```
assertTrue(conv.getConvolutionType() == convType);
```

**Comment by EronWright** [comment]
This might relate to #535
