### ISSUE TITLE
CNNProcessorTest::testCNNInputPreProcessorMnist - SubsamplingLayer params

### ISSUE THREAD

**Issue by EronWright** [deeplearning4j/deeplearning4j#568]
The test uses SubsamplingLayer, and hits an UnsupportedOperationException during initialization because the layer doesn't support `params()`.
```
java.lang.UnsupportedOperationException: null
	at org.deeplearning4j.nn.layers.convolution.subsampling.SubsamplingLayer.params(SubsamplingLayer.java:230)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.params(MultiLayerNetwork.java:797)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pack(MultiLayerNetwork.java:842)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.initMask(MultiLayerNetwork.java:1490)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:353)
	at org.deeplearning4j.nn.conf.preprocessor.CNNProcessorTest.testCNNInputPreProcessorMnist(CNNProcessorTest.java:105)
```

**Comment by EronWright** [comment]
Would you kindly mention the issue number in the commit and/or PR comments.  The issue then will link to the commits that fixed it, making for a better paper trail.

**Comment by nyghtowl** [comment]
Adam fixed this so I don't have that. Agree that a paper trail is needed and I do that when I have the fix.

**Comment by EronWright** [comment]
Thanks

**Comment by nyghtowl** [comment]
Fix unknown - resolved between my layer merge and Adam's fixes since 8/7
