### ISSUE TITLE
Bad initialization of weight parameter matrix

### ISSUE THREAD

**Issue by EronWright** [deeplearning4j/deeplearning4j#569]
There seems to be a problem with how a given layer's weight parameters are initialized.   The array is sometimes null and more often of shape [0,0].

In one manifestion, a null weight parameter is passed to nd4j, causing an NPE.
```
testRecursiveAutoEncoderScores(org.deeplearning4j.nn.layers.BaseLayerTest)  Time elapsed: 0.023 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2366)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:345)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:352)
	at org.deeplearning4j.nn.layers.feedforward.autoencoder.recursive.RecursiveAutoEncoder.gradient(RecursiveAutoEncoder.java:112)
	at org.deeplearning4j.nn.layers.feedforward.autoencoder.recursive.RecursiveAutoEncoder.computeGradientAndScore(RecursiveAutoEncoder.java:68)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:117)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:135)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:480)
	at org.deeplearning4j.nn.layers.BaseLayerTest.testRecursiveAutoEncoderScores(BaseLayerTest.java:70)
```

In this case the weight matrix has shape [0,0].
```
testWeightsDifferent(org.deeplearning4j.nn.layers.OutputLayerTest)  Time elapsed: 0.009 sec  <<< ERROR!
java.lang.IllegalStateException: Column of left array 4 != rows of right 0 or rows of left array 120 != columns of right 0
	at org.nd4j.linalg.util.LinAlgExceptions.assertMultiplies(LinAlgExceptions.java:76)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2514)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2368)
	at org.deeplearning4j.nn.layers.BaseLayer.preOutput(BaseLayer.java:333)
	at org.deeplearning4j.nn.layers.OutputLayer.output(OutputLayer.java:215)
	at org.deeplearning4j.nn.layers.OutputLayer.output(OutputLayer.java:199)
	at org.deeplearning4j.nn.layers.OutputLayer.computeGradientAndScore(OutputLayer.java:85)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:117)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.layers.OutputLayer.fit(OutputLayer.java:316)
	at org.deeplearning4j.nn.layers.OutputLayer.fit(OutputLayer.java:326)
	at org.deeplearning4j.nn.layers.OutputLayerTest.testWeightsDifferent(OutputLayerTest.java:110)
```

And another related one:
```
testPlotter(org.deeplearning4j.plot.RenderTest)  Time elapsed: 0.083 sec  <<< ERROR!
java.lang.IllegalStateException: Column of left array 784 != rows of right 0 or rows of left array 10 != columns of right 0
	at org.nd4j.linalg.util.LinAlgExceptions.assertMultiplies(LinAlgExceptions.java:76)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2514)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2368)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.propUp(RBM.java:320)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.sampleHiddenGivenVisible(RBM.java:215)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.computeGradientAndScore(RBM.java:112)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:117)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:135)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:480)
	at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.fit(RBM.java:392)
	at org.deeplearning4j.plot.RenderTest.testPlotter(RenderTest.java:70)
```

**Comment by agibsonccc** [comment]
Closing this. I believe it was related to the conf issues.

**Comment by vipinn123** [comment]
Hello,

I have run into this issue while trying to train my MLPFeedforward network. The code is exactly similar to the example code for MLPClassifierLinear.java. However I am trying to use my own dataset instead of 'src/main/resources/classification/linear_data_train.csv' . Not sure if I am getting this error because of some issue with my dataset or because of some other reason.

Could you please let me know how this issue was resolved in your case?

Thanks,
Vipin

**Comment by AlexDBlack** [comment]
@vipinn123 please open a new issue with your full stack trace and details.
