### ISSUE TITLE
ConvolutionLayerTest::testSubSampleLayerNoneBackprop fails - layer input not initialized

### ISSUE THREAD

**Issue by EronWright** [deeplearning4j/deeplearning4j#570]
The `input` array is evidently null within the layer when `backpropGradient` is called.
```
testSubSampleLayerNoneBackprop(org.deeplearning4j.nn.layers.convolution.ConvolutionLayerTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.backpropGradient(ConvolutionLayer.java:85)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayerTest.testSubSampleLayerNoneBackprop(ConvolutionLayerTest.java:150)
```

**Comment by nyghtowl** [comment]
Fix unknown - resolved between my layer merge and Adam's fixes since 8/7
