### ISSUE TITLE
code=30(cudaErrorUnknown) "result" on Windows Server 2016

### ISSUE THREAD

**Issue by mtothak** [deeplearning4j/deeplearning4j#5708]
Hi!

I made a checkout of the dl4j-examples master and the compile was fine, setting
<nd4j.backend>nd4j-cuda-9.0-platform</nd4j.backend>
in the parent pom (deeplearning4j-examples-parent).

<java.version>1.8</java.version>
<nd4j.version>1.0.0-beta</nd4j.version>
<dl4j.version>1.0.0-beta</dl4j.version>
<datavec.version>1.0.0-beta</datavec.version>
<arbiter.version>1.0.0-beta</arbiter.version>
<rl4j.version>1.0.0-beta</rl4j.version>

Nevertheless I got the following error trying to run MLPMnistTwoLayerExample:

java -cp target/dl4j-examples-1.0.0-beta-bin.jar org.deeplearning4j.examples.feedforward.mnist.MLPMnistTwoLayerExample

08:43:22,641 INFO  ~ Build model....
08:43:23,520 INFO  ~ Loaded [JCublasBackend] backend
08:43:31,976 INFO  ~ Number of threads used for NativeOps: 32
08:43:33,346 INFO  ~ Number of threads used for BLAS: 0
08:43:33,366 INFO  ~ Backend used: [CUDA]; OS: [Windows Server 2016]
08:43:33,366 INFO  ~ Cores: [12]; Memory: [21,3GB];
08:43:33,369 INFO  ~ Blas vendor: [CUBLAS]
08:43:33,370 INFO  ~ Device Name: [TITAN V]; CC: [7.0]; Total/free memory: [12884901888]
08:43:33,923 INFO  ~ Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
CUDA error at D:/jenkins/workspace/libnd4j_latest_release_windows-x86_64-cuda-9.0/libnd4j/blas/cuda/NativeOps.cu:4342 code=30(cudaErrorUnknown) "result"
Exception in thread "main" java.lang.RuntimeException: cudaStreamSynchronize(...) failed
        at org.nd4j.nativeblas.Nd4jCuda$NativeOps.streamSynchronize(Native Method)
        at org.nd4j.jita.allocator.pointers.cuda.cudaStream_t.synchronize(cudaStream_t.java:22)
        at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:315)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:473)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:399)
        at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:224)
        at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:336)
        at org.nd4j.linalg.jcublas.buffer.CudaIntDataBuffer.<init>(CudaIntDataBuffer.java:53)
        at org.nd4j.linalg.jcublas.buffer.CudaIntDataBuffer.<init>(CudaIntDataBuffer.java:81)
        at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createInt(CudaDataBufferFactory.java:353)
        at org.nd4j.linalg.factory.Nd4j.createBufferDetached(Nd4j.java:1443)
        at org.nd4j.linalg.api.shape.Shape.createShapeInformation(Shape.java:2355)
        at org.nd4j.linalg.api.ndarray.BaseShapeInfoProvider.createShapeInformation(BaseShapeInfoProvider.java:49)
        at org.nd4j.jita.constant.ProtectedCudaShapeInfoProvider.createShapeInformation(ProtectedCudaShapeInfoProvider.java:64)
        at org.nd4j.linalg.jcublas.CachedShapeInfoProvider.createShapeInformation(CachedShapeInfoProvider.java:26)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:173)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:261)
        at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:113)
        at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.createUninitialized(JCublasNDArrayFactory.java:262)
        at org.nd4j.linalg.factory.Nd4j.createUninitialized(Nd4j.java:5128)
        at org.nd4j.linalg.factory.BaseNDArrayFactory.valueArrayOf(BaseNDArrayFactory.java:953)
        at org.nd4j.linalg.factory.Nd4j.valueArrayOf(Nd4j.java:5560)
        at org.deeplearning4j.nn.params.DefaultParamInitializer.createBias(DefaultParamInitializer.java:162)
        at org.deeplearning4j.nn.params.DefaultParamInitializer.createBias(DefaultParamInitializer.java:157)
        at org.deeplearning4j.nn.params.DefaultParamInitializer.init(DefaultParamInitializer.java:123)
        at org.deeplearning4j.nn.conf.layers.DenseLayer.instantiate(DenseLayer.java:64)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:596)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:500)
        at org.deeplearning4j.examples.feedforward.mnist.MLPMnistTwoLayerExample.main(MLPMnistTwoLayerExample.java:88)

Further information:
nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:32_Central_Daylight_Time_2017
Cuda compilation tools, release 9.0, V9.0.176

Any help very appreciated!
Thank you!

lg Markus

**Comment by raver119** [comment]
Please consider using snapshot version for now. There were few nvcc-related issues with V architecture you might be facing there.

**Comment by raver119** [comment]
p.s. feel free to reopen issue, if you'll manage to reproduce your problem with latest snapshots.
