### ISSUE TITLE
ConvolutionLayerTest::testCalculateDelta - bad tensor multiply

### ISSUE THREAD

**Issue by EronWright** [deeplearning4j/deeplearning4j#571]
```
java.lang.IllegalArgumentException: a and b must be same rank
	at org.nd4j.linalg.factory.Nd4j.tensorMmul(Nd4j.java:567)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:125)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.calculateDelta(ConvolutionLayer.java:75)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayerTest.testCalculateDelta(ConvolutionLayerTest.java:199)
```

**Comment by nyghtowl** [comment]
Fix unknown - resolved between my layer merge and Adam's fixes since 8/7
