### ISSUE TITLE
AutoEncoderTest::testBackProp - encode fails with bad mmul

### ISSUE THREAD

**Issue by EronWright** [deeplearning4j/deeplearning4j#572]
```
java.lang.IllegalStateException: Column of left array 784 != rows of right 0 or rows of left array 100 != columns of right 0
	at org.nd4j.linalg.util.LinAlgExceptions.assertMultiplies(LinAlgExceptions.java:76)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2514)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2368)
	at org.deeplearning4j.nn.layers.feedforward.autoencoder.AutoEncoder.encode(AutoEncoder.java:77)
	at org.deeplearning4j.nn.layers.feedforward.autoencoder.AutoEncoder.activate(AutoEncoder.java:103)
	at org.deeplearning4j.nn.layers.feedforward.autoencoder.AutoEncoderTest.testBackProp(AutoEncoderTest.java:92)
```

**Comment by EronWright** [comment]
This is a dup of #569
