### ISSUE TITLE
SameDiff: Gather op test failing

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5736]
I believe this is a java side failure due to Gather.doDiff()
```
o.n.l.a.o.DynamicCustomOp - Populating inputs and outputs for op null: Successful
Error at [D:/jenkins/ws/dl4j-master-windows-x86_64-cpu/libnd4j/include/ops/declarable/generic/helpers/ScatterHelper.h:53:0]:
scatter_add: updates shapes should match
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute op scatter_add. Attempted to execute with 3 inputs, 1 outputs, 0 targs and 0 iargs. Please see above message (printed out from c++) for a possible cause of error.

java.lang.IllegalStateException: Exception encountered during gradient check
	at org.nd4j.autodiff.validation.OpValidation.validateHelper(OpValidation.java:150)
	at org.nd4j.autodiff.validation.OpValidation.validate(OpValidation.java:92)
	at org.nd4j.autodiff.validation.OpValidation.validate(OpValidation.java:87)
	at org.nd4j.autodiff.opvalidation.ShapeOpValidation.testGather(ShapeOpValidation.java:1238)
Caused by: java.lang.RuntimeException: Op validation failed
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOpDouble(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1732)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:7406)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:6295)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:6333)
	at org.nd4j.autodiff.validation.GradCheckUtil.checkGradients(GradCheckUtil.java:239)
	at org.nd4j.autodiff.validation.GradCheckUtil.checkGradients(GradCheckUtil.java:166)
	at org.nd4j.autodiff.validation.OpValidation.validateHelper(OpValidation.java:148)
	... 35 more
```

```
    @Test
    public void testGather(){
        OpValidationSuite.ignoreFailing();  //Exception during gradient check
        List<INDArray> inArrs = new ArrayList<>();
        List<Integer> axis = new ArrayList<>();
        List<INDArray> indices = new ArrayList<>();

        inArrs.add(Nd4j.linspace(1,48,48).reshape(2,4,3,2));
        indices.add(Nd4j.trueVector(new double[]{1,0}));
        axis.add(-2);

        for( int i=0; i<inArrs.size(); i++ ){

            INDArray in = inArrs.get(i);
            INDArray idx = indices.get(i);
            int a = axis.get(i);
            int aNorm = (a >= 0 ? a : a + in.rank());

            INDArray expOut;
            if(idx.rank() == 0){
                INDArrayIndex[] get = new INDArrayIndex[in.rank()];
                for( int j=0; j<aNorm; j++ ){
                    get[j] = NDArrayIndex.all();
                }
                get[aNorm] = NDArrayIndex.point(idx.getInt(0));
                for( int j=aNorm+1; j<in.rank(); j++ ){
                    get[j] = NDArrayIndex.all();
                }
                expOut = in.get(get);
            } else if (idx.rank() == 1){
                long[] shape = in.shape().clone();
                shape[aNorm] = idx.length();
                expOut = Nd4j.create(shape);

                INDArrayIndex[] get = new INDArrayIndex[in.rank()];
                INDArrayIndex[] put = new INDArrayIndex[in.rank()];
                for( int j=0; j<aNorm; j++ ){
                    get[j] = NDArrayIndex.all();
                    put[j] = NDArrayIndex.all();
                }
                for( int j=aNorm+1; j<in.rank(); j++ ){
                    get[j] = NDArrayIndex.all();
                    put[j] = NDArrayIndex.all();
                }

                for(int j=0; j<idx.length(); j++ ){
                    get[aNorm] = NDArrayIndex.point(idx.getInt(j));
                    put[aNorm] = NDArrayIndex.point(j);
                    expOut.put(put, in.get(get));
                }
            } else {
                throw new RuntimeException("Rank 2+ tests not yet implemented");
            }


            SameDiff sd = SameDiff.create();
            SDVariable sdIn = sd.var("in", in);
            SDVariable sdIdx = sd.var("idx", idx);
            SDVariable gather = sd.gather(sdIn, sdIdx, a);

            SDVariable loss = gather.std(true);

            String err = OpValidation.validate(new TestCase(sd)
                    .expected(gather, expOut)
                    .gradCheckSkipVariables("idx"));

            assertNull(err);
        }
    }
```

**Comment by farizrahman4u** [comment]
#5740

**Comment by AlexDBlack** [comment]
@farizrahman4u Thanks 👍 :)
