### ISSUE TITLE
Mis matched shapes in  ShuffleNet  implementation

### ISSUE THREAD

**Issue by antidodo** [deeplearning4j/deeplearning4j#5748]
I tried to implement a SchuffleNet for evaluating chess configurations in 
Shape (8,8,24) and  8  additional values  that get added  in the last 2 dens layers (that part works in a simpler network)  
here is the code for the GraphBuilder https://gist.github.com/antidodo/23169ab0ed68789a0b5432f338d97611
and that is the resulting 
https://gist.github.com/antidodo/bd4e0b987cd2a2fca2ce6a7348a2524d
and hear the entirety of the Training file
https://gist.github.com/antidodo/7deaff74abe59ca75690f01d90ea6ef3
I tried also to give all MergeVertex() multiple Identical inputs (BlockID+"_Split_00") to check if the SubsetVertex return different shapes but the error message is the same.

**Comment by antidodo** [comment]
I am using the version  0.9.1.

**Comment by AlexDBlack** [comment]
Can you try upgrading to version 1.0.0-beta? The version you are using was released nearly 11 months ago... there have been a lot of fixes in the versions since.

**Comment by antidodo** [comment]
I upgraded to 1.0.0-beta  but now ther is a new Error 
`Exception in thread "main" java.lang.NoSuchMethodError: org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(I)Lorg/deeplearning4j/nn/conf/NeuralNetConfiguration$Builder;
	at de.multichess.players.david.createModel.createGrath(createModel.java:293)
	at de.multichess.players.david.createModel.<init>(createModel.java:122)
	at de.multichess.test.NNTrain.main(NNTrain.java:37)`
with the new GraphBuilder inzilation like in your Zoo implementation of ResNet50

`GraphBuilder graph= new NeuralNetConfiguration.Builder()
				.seed(1)
				.activation(Activation.IDENTITY)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .updater( new Adam(0.01))
                .weightInit(WeightInit.DISTRIBUTION)
                .dist(new TruncatedNormalDistribution(0.0, 0.5))
                .l1(1e-7)
                .l2(5e-5)
                .miniBatch(true)
                .cacheMode( CacheMode.NONE)
                .trainingWorkspaceMode(WorkspaceMode.ENABLED)
                .inferenceWorkspaceMode(WorkspaceMode.ENABLED)
                .cudnnAlgoMode(ConvolutionLayer.AlgoMode.PREFER_FASTEST)
                .convolutionMode(ConvolutionMode.Truncate)
                .graphBuilder();`

**Comment by AlexDBlack** [comment]
> Exception in thread "main" java.lang.NoSuchMethodError: 

That means that you didn't upgrade the dependencies properly. ND4J, DL4J, DataVec etc all need to be at version 1.0.0-beta. You have mixed 0.9.1 and 1.0.0-beta versions on your classpath.

**Comment by antidodo** [comment]
are there any new Dependencies this is mine configuration.

<dependencies>


		
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-cuda-9.1-platform</artifactId>
			<version>1.0.0-beta</version>

		</dependency>
		

		
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-core</artifactId>
			<version>1.0.0-beta</version>
		</dependency>
		
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-ui_2.10</artifactId>
			<version>1.0.0-beta</version>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>rl4j-api</artifactId>
			<version>1.0.0-beta</version>
		</dependency>


		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-nlp</artifactId>
			<version>1.0.0-beta</version>
		</dependency>

		
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-ui_2.11</artifactId>
			<version>1.0.0-beta</version>
		</dependency>

		
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>23.0</version>
		</dependency>

		
		<dependency>
			<artifactId>datavec-data-codec</artifactId>
			<groupId>org.datavec</groupId>
			<version>1.0.0-beta</version>
		</dependency>

		

		<dependency>
			<groupId>org.jfree</groupId>
			<artifactId>jcommon</artifactId>
			<version>1.0.23</version>
		</dependency>

		
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.5</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.9.5</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.9.5</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>2.9.4</version>
		</dependency>

**Comment by antidodo** [comment]
yes I use Eclipse

**Comment by AlexDBlack** [comment]
I tried to reproduce the issue using the following code: https://gist.github.com/AlexDBlack/9905127edadc312fdc8aea9a933d69fa

I'm getting the following:
```
Exception in thread "main" java.lang.IllegalStateException: Invalid configuration: disconnected vertices found - [block00_Gconv_22, block00_Gconv_3, block00_Gconv_5, block00_Gconv_4, block00out, block00_Gconv_7, block00_Gconv_6]. Disconnected vertices are those that do not connect to either another vertex, and are also not a network output. To disable this error (i.e., allow network configurations with disconnected vertices) use GraphBuilder.allowDisconnected(true)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.validate(ComputationGraphConfiguration.java:346)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.build(ComputationGraphConfiguration.java:1033)
	at org.deeplearning4j.Temp.createGrath(Temp.java:105)
	at org.deeplearning4j.Temp.main(Temp.java:26)
```

I note that you have added allowDisconnected(true) - that's bad, you shouldn't be using that unless you have a *very* good reason to do so - as if you need it, it means your configuration is invalid.

Anyway, can you give me something complete that I can just click 'run' on to reproduce this? I'm not sure I can help much (other than telling you your config is probably invalid) without that.

**Comment by agibsonccc** [comment]
Closing — references a removed/rewritten subsystem (DataVec, NLP/Word2Vec, Model Zoo, Spark, UI, or Arbiter). These have been fundamentally rewritten or removed in the upcoming release. Please open a new issue if you experience similar problems with the new version.
