### ISSUE TITLE
DL4j Spark: Aeron log error

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5814]
The error below is reasonably straightforward, but I think there could be improved usability for users:
1. Is there a way to reduce memory requirements?
2. Is there a way to use a different location?

A more useful exception would help the user understand what they can do next.

```
Exception in thread "VoidParameterServer messages handling thread" java.lang.RuntimeException: io.aeron.exceptions.RegistrationException: Insufficient usable storage for new log of length=805306816 in /dev/shm (tmpfs)
        at org.nd4j.parameterserver.distributed.VoidParameterServer.lambda$init$0(VoidParameterServer.java:276)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.aeron.exceptions.RegistrationException: Insufficient usable storage for new log of length=805306816 in /dev/shm (tmpfs)
        at io.aeron.ClientConductor.onError(ClientConductor.java:264)
        at io.aeron.DriverListenerAdapter.onMessage(DriverListenerAdapter.java:141)
        at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:99)
        at io.aeron.DriverListenerAdapter.pollMessage(DriverListenerAdapter.java:59)
        at io.aeron.ClientConductor.doWork(ClientConductor.java:331)
        at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:350)
        at io.aeron.ClientConductor.addPublication(ClientConductor.java:166)
        at io.aeron.Aeron.addPublication(Aeron.java:178)
        at org.nd4j.parameterserver.distributed.transport.RoutedTransport.addClient(RoutedTransport.java:623)
        at org.nd4j.parameterserver.distributed.messages.requests.IntroductionRequestMessage.processMessage(IntroductionRequestMessage.java:31)
        at org.nd4j.parameterserver.distributed.VoidParameterServer.handleMessage(VoidParameterServer.java:430)
        at org.nd4j.parameterserver.distributed.VoidParameterServer.lambda$init$0(VoidParameterServer.java:271)
        ... 1 more
```

**Comment by AlexDBlack** [comment]
Looks like this is related to aeron config, and (possibly, unconfirmed) non-releasing of memory.
Hopefully once those are fixed, users won't run into this; I'll open more specific issues if/when I've confirmed the memory issue.

**Comment by TristanMeng** [comment]
how to solve?

**Comment by AlexDBlack** [comment]
@TristanMeng please don't post on old issues with zero detail of your problem
If you have a problem, open a new issue will full details - exception stack trace, code, network configuration, etc.
