### ISSUE TITLE
Add inceptionv4 to zoo

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#5838]
Recently users have requested that Inception V4 be added to the zoo. Weights are available, need to get the configuration in our API.

**Comment by crockpotveggies** [comment]
@maxpumperla I'm getting the following error when trying to import the file here to DL4J: http://blob.deeplearning4j.org/models/inceptionv4_keras_imagenet_weightsandconfig.h5

```
Exception in thread "main" java.lang.NullPointerException
	at org.nd4j.linalg.factory.Nd4j.onesLike(Nd4j.java:5624)
	at org.deeplearning4j.nn.modelimport.keras.layers.normalization.KerasBatchNormalization.setWeights(KerasBatchNormalization.java:184)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:309)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:177)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:93)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:140)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:145)
	at org.deeplearning4j.ConvertKeras.run(ConvertKeras.java:34)
	at org.deeplearning4j.ConvertKeras.main(ConvertKeras.java:44)
```

**Comment by crockpotveggies** [comment]
@maxpumperla good news this was a beta bug. Import works on snapshots.

**Comment by crockpotveggies** [comment]
Inception V4 weights now available at http://blob.deeplearning4j.org/models/inceptionv4_dl4j_inference_imagenet.v1.zip

**Comment by maxpumperla** [comment]
@crockpotveggies I'll add this to DL4J import unit tests as well

**Comment by raver119** [comment]
Looks like we can close this issue now.
