### ISSUE TITLE
Import keras model with disconnected layers

### ISSUE THREAD

**Issue by xiptos** [deeplearning4j/deeplearning4j#5861]
Importing keras model with disconnected layers fails with an error message regarding the existence of disconnected layers. I used the following model.
![model](https://user-images.githubusercontent.com/1430594/42446063-f181a896-836c-11e8-99b1-c64f9b2465dd.png)
https://we.tl/OSNGdhfsSy

The exception is the following:
Exception in thread "main" java.lang.IllegalStateException: Invalid configuration: disconnected vertices found - [conv2d_59, conv2d_67]. Disconnected vertices are those that do not connect to either another vertex, and are also not a network output. To disable this error (i.e., allow network configurations with disconnected vertices) use GraphBuilder.allowDisconnected(true)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.validate(ComputationGraphConfiguration.java:346)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.build(ComputationGraphConfiguration.java:1033)
	at org.deeplearning4j.nn.transferlearning.TransferLearning$GraphBuilder.build(TransferLearning.java:753)
	at pt.ipb.yolo.YoloConverter.main(YoloConverter.java:57)

-------

$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

------

Running DL4J 1.0.0-beta on macOS 10.13.5

**Comment by maxpumperla** [comment]
@xiptos We're now allowing disconnected vertices/layers for Keras model import. It's a little unsafe to do this, which is why we generally disallow it in DL4J, but for model import it makes sense to have.
