### ISSUE TITLE
LSTM - backprop - shape problem

### ISSUE THREAD

**Issue by liweigu** [deeplearning4j/deeplearning4j#5888]
Enviroment:
  Dl4j versoin: 1.0.0-SNAPSHOT
  Linux

The code is fine in dl4j 1.0.0-beta(using GravesLSTM), but got error in 1.0.0-SNAPSHOT(using LSTM).

Error:
java.lang.IllegalStateException: Shapes must be equal during backprop: in.shape{} = [31, 100, 12, 12], epsilon.shape() = [31, 1, 120, 120]
	at org.nd4j.linalg.activations.BaseActivationFunction.assertShape(BaseActivationFunction.java:42)
	at org.nd4j.linalg.activations.impl.ActivationReLU.backprop(ActivationReLU.java:27)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.backpropGradient(ConvolutionLayer.java:147)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doBackward(LayerVertex.java:150)
	at org.deeplearning4j.nn.graph.ComputationGraph.calcBackpropGradients(ComputationGraph.java:2572)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1417)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1377)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:162)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:53)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:54)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1200)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1149)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1136)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1016)
	at com.liweigu.dls.competition.srad.RadLSTM.run(RadLSTM.java:103)

Code:
		int cnn1Stride = 4;
		int lstmHiddenCount = 100;
		int channels = 1;
		int kernelSize = 3;
		Map<String, InputPreProcessor> inputPreProcessors = new HashMap<String, InputPreProcessor>();
		inputPreProcessors.put("cnn1", new RnnToCnnPreProcessor(501, 501, channels));
		inputPreProcessors.put("lstm1", new CnnToRnnPreProcessor(120, 120, channels)); // 120 = Math.pow(14400, 0.5)
		GraphBuilder graphBuilder = builder.graphBuilder().pretrain(false).backprop(true)
				.backpropType(BackpropType.Standard)
	            .addInputs("inputs")
	            .addLayer("cnn1", new ConvolutionLayer.Builder(new int[] { kernelSize, kernelSize }, new int[] { cnn1Stride, cnn1Stride }, new int[] { 0, 0 })
	    				.nIn(channels).nOut(50).activation(Activation.RELU).weightInit(WeightInit.RELU).build(), "inputs")
	            // Output: (501 - kernelSize + 0) / cnn1Stride + 1 = 125 --> 125 * 125 * 50 = 781250
				.addLayer("cnn2", new SubsamplingLayer.Builder(new int[] { 2, 2 }, new int[] { 2, 2 }).build(), "cnn1")
				// (125-2+0)/2+1 = 62
				.addLayer("cnn3",
						new ConvolutionLayer.Builder(new int[] { kernelSize, kernelSize }, new int[] { 5, 5 }, new int[] { 0, 0 })
						.nIn(50).nOut(100).activation(Activation.RELU).weightInit(WeightInit.RELU).build(), "cnn2")
				// Output: (62 - kernelSize + 0) / 5 + 1 = 12 --> 12 * 12 * 100 = 14400
				.addLayer("lstm1", new LSTM.Builder().activation(Activation.SOFTSIGN)
						.nIn(14400).nOut(lstmHiddenCount).build(), "cnn3")
	            .addLayer("lstm2", new LSTM.Builder().activation(Activation.SOFTSIGN)
	            		.nIn(lstmHiddenCount).nOut(lstmHiddenCount).build(), "lstm1")
	            .addVertex("thoughtVector", new LastTimeStepVertex("inputs"), "lstm2")
	            .addLayer("output", new OutputLayer
	            		.Builder(LossFunctions.LossFunction.MSE) // MSE, MEAN_ABSOLUTE_ERROR
	    				.activation(Activation.IDENTITY)
	    				.nIn(lstmHiddenCount)
	    				.nOut(501 * 501).build(), "thoughtVector")
				.setOutputs("output");
		graphBuilder.setInputPreProcessors(inputPreProcessors);

**Comment by liweigu** [comment]
The program can run after replacing the line:
inputPreProcessors.put("lstm1", new CnnToRnnPreProcessor(120, 120, channels)); // 120 = Math.pow(14400, 0.5)
by this line:
inputPreProcessors.put("lstm1", new CnnToRnnPreProcessor(12, 12, channels * 100));
And i think the new(1.0.0-snapshot) parameter values are more reasonable than before(1.0.0-beta).
