### ISSUE TITLE
InvalidClassException on spark training

### ISSUE THREAD

**Issue by liweigu** [deeplearning4j/deeplearning4j#5948]
Dl4j versoin: 1.0.0_SNAPSHOT
ENV: Linux, jdk 8, spark 2.1.1

Error Info (Occurs at the code 'sparkDl4jMultiLayer.fit(trainingData)') :
10:57:43.861 [task-result-getter-3] INFO  o.a.spark.scheduler.TaskSetManager - Lost task 0.3 in stage 4.0 (TID 13) on 10.47.160.4, executor 0: java.io.InvalidClassException (org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingWorker; local class incompatible: stream classdesc serialVersionUID = 8579840298117644318, local class serialVersionUID = 4734621281114494807) [duplicate 5]
10:57:43.862 [task-result-getter-3] ERROR o.a.spark.scheduler.TaskSetManager - Task 0 in stage 4.0 failed 4 times; aborting job
10:57:43.863 [task-result-getter-3] INFO  o.a.s.scheduler.TaskSchedulerImpl - Removed TaskSet 4.0, whose tasks have all completed, from pool 
10:57:43.864 [task-result-getter-1] INFO  o.a.spark.scheduler.TaskSetManager - Lost task 1.2 in stage 4.0 (TID 12) on 10.47.160.4, executor 0: java.io.InvalidClassException (org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingWorker; local class incompatible: stream classdesc serialVersionUID = 8579840298117644318, local class serialVersionUID = 4734621281114494807) [duplicate 6]
10:57:43.864 [task-result-getter-1] INFO  o.a.s.scheduler.TaskSchedulerImpl - Removed TaskSet 4.0, whose tasks have all completed, from pool 
10:57:43.868 [dag-scheduler-event-loop] INFO  o.a.s.scheduler.TaskSchedulerImpl - Cancelling stage 4
10:57:43.869 [dag-scheduler-event-loop] INFO  o.a.spark.scheduler.DAGScheduler - ResultStage 4 (treeAggregate at ParameterAveragingTrainingMaster.java:658) failed in 0.184 s due to Job aborted due to stage failure: Task 0 in stage 4.0 failed 4 times, most recent failure: Lost task 0.3 in stage 4.0 (TID 13, 10.47.160.4, executor 0): java.io.InvalidClassException: org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingWorker; local class incompatible: stream classdesc serialVersionUID = 8579840298117644318, local class serialVersionUID = 4734621281114494807
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:616)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1843)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
[error log.txt](https://github.com/deeplearning4j/deeplearning4j/files/2218035/error.log.txt)

Key Code:
		TrainingMaster trainingMaster = new ParameterAveragingTrainingMaster
				.Builder(1)
				.storageLevel(StorageLevel.MEMORY_ONLY_SER())
				.rddTrainingApproach(RDDTrainingApproach.Direct)
				.build();

		MultiLayerNetwork net = new MultiLayerNetwork(new NeuralNetConfiguration.Builder()
				.seed(seed)
				.optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
				.weightInit(WeightInit.XAVIER)
				.updater(new Nesterovs(learningRate, 0.9)).list()
				.layer(0, new DenseLayer.Builder()
						.nIn(numInput).nOut(nHidden).activation(Activation.TANH).build())
				.layer(1, new OutputLayer.Builder(LossFunctions.LossFunction.MSE)
						.activation(Activation.IDENTITY)
						.nIn(nHidden)
						.nOut(numOutputs).build())
				.pretrain(false)
				.backprop(true).build());
		net.init();

		SparkConf conf = new SparkConf()
				.setAppName("sum")
				.setMaster("spark://10.46.230.46:7077")
				.setJars(jars)
				.set("spark.cores.max", "2");
		JavaSparkContext sc = new JavaSparkContext(conf);
		SparkDl4jMultiLayer sparkDl4jMultiLayer = new SparkDl4jMultiLayer(sc, net, trainingMaster);

		for (int i = 0; i < nEpochs; i++) {
			iterator.reset();
			while (iterator.hasNext()) {
				DataSet ds = iterator.next();
				JavaRDD<DataSet> trainingData = sc.parallelize(Collections.singletonList(ds));
				sparkDl4jMultiLayer.fit(trainingData);
			}
		}

**Comment by AlexDBlack** [comment]
> executor 0: java.io.InvalidClassException (org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingWorker; local class incompatible: stream classdesc serialVersionUID = 8579840298117644318, local class serialVersionUID = 4734621281114494807) [duplicate 6]

This looks a *lot* like a classpath issue. Specifically, multiple versions of DL4J on the classpath (perhaps different versions on the driver vs. executors). In other words, something to do with your project/cluster setup, and not an issue with DL4J.

Can you run this via spark submit instead of whatever you are doing here?

**Comment by liweigu** [comment]
Your suggest is useful, I shall cleanup and re-download all jars by maven to see if it works.

**Comment by liweigu** [comment]
After re-download all the jars, the error info is changed to:
15:48:03.886 [map-output-dispatcher-0] INFO  o.a.spark.MapOutputTrackerMaster - Size of output statuses for shuffle 0 is 151 bytes
15:48:04.167 [dispatcher-event-loop-1] DEBUG o.a.s.scheduler.TaskSchedulerImpl - parentName: , name: TaskSet_4.0, runningTasks: 2
15:48:04.298 [shuffle-server-6-2] DEBUG o.apache.spark.storage.BlockManager - Getting local block broadcast_3_piece0 as bytes
15:48:04.298 [shuffle-server-6-2] DEBUG o.apache.spark.storage.BlockManager - Level for block broadcast_3_piece0 is StorageLevel(disk, memory, 1 replicas)
15:48:04.306 [dispatcher-event-loop-0] INFO  o.a.spark.storage.BlockManagerInfo - Added broadcast_3_piece0 in memory on 10.47.160.4:36311 (size: 2.6 KB, free: 366.3 MB)
15:48:04.335 [dispatcher-event-loop-2] DEBUG o.a.s.scheduler.TaskSchedulerImpl - parentName: , name: TaskSet_4.0, runningTasks: 1
15:48:04.352 [task-result-getter-2] WARN  o.a.spark.scheduler.TaskSetManager - Lost task 1.0 in stage 4.0 (TID 8, 10.47.160.4, executor 0): java.lang.NullPointerException
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2028)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2028)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

15:48:04.354 [dispatcher-event-loop-1] DEBUG o.a.s.scheduler.TaskSchedulerImpl - parentName: , name: TaskSet_4.0, runningTasks: 1
15:48:04.355 [dispatcher-event-loop-1] INFO  o.a.spark.scheduler.TaskSetManager - Starting task 1.1 in stage 4.0 (TID 9, 10.47.160.4, executor 0, partition 1, PROCESS_LOCAL, 31422 bytes)
15:48:04.356 [dispatcher-event-loop-1] DEBUG o.a.s.s.c.CoarseGrainedSchedulerBackend$DriverEndpoint - Launching task 9 on executor id: 0 hostname: 10.47.160.4.
15:48:04.485 [dispatcher-event-loop-0] DEBUG o.a.s.scheduler.TaskSchedulerImpl - parentName: , name: TaskSet_4.0, runningTasks: 1
15:48:04.487 [task-result-getter-0] INFO  o.a.spark.scheduler.TaskSetManager - Lost task 1.1 in stage 4.0 (TID 9) on 10.47.160.4, executor 0: java.lang.NullPointerException (null) [duplicate 1]
15:48:04.488 [dispatcher-event-loop-2] DEBUG o.a.s.scheduler.TaskSchedulerImpl - parentName: , name: TaskSet_4.0, runningTasks: 1
15:48:04.489 [dispatcher-event-loop-2] INFO  o.a.spark.scheduler.TaskSetManager - Starting task 1.2 in stage 4.0 (TID 10, 10.47.160.4, executor 0, partition 1, PROCESS_LOCAL, 31422 bytes)
15:48:04.489 [dispatcher-event-loop-2] DEBUG o.a.s.s.c.CoarseGrainedSchedulerBackend$DriverEndpoint - Launching task 10 on executor id: 0 hostname: 10.47.160.4.
15:48:04.524 [dispatcher-event-loop-3] DEBUG o.a.s.scheduler.TaskSchedulerImpl - parentName: , name: TaskSet_4.0, runningTasks: 1
15:48:04.524 [task-result-getter-1] INFO  o.a.spark.scheduler.TaskSetManager - Lost task 1.2 in stage 4.0 (TID 10) on 10.47.160.4, executor 0: java.lang.NullPointerException (null) [duplicate 2]
15:48:04.525 [dispatcher-event-loop-0] DEBUG o.a.s.scheduler.TaskSchedulerImpl - parentName: , name: TaskSet_4.0, runningTasks: 1
15:48:04.527 [dispatcher-event-loop-0] INFO  o.a.spark.scheduler.TaskSetManager - Starting task 1.3 in stage 4.0 (TID 11, 10.47.160.4, executor 0, partition 1, PROCESS_LOCAL, 31422 bytes)
15:48:04.527 [dispatcher-event-loop-0] DEBUG o.a.s.s.c.CoarseGrainedSchedulerBackend$DriverEndpoint - Launching task 11 on executor id: 0 hostname: 10.47.160.4.
15:48:04.579 [dispatcher-event-loop-1] DEBUG o.a.s.scheduler.TaskSchedulerImpl - parentName: , name: TaskSet_4.0, runningTasks: 1
15:48:04.579 [task-result-getter-3] INFO  o.a.spark.scheduler.TaskSetManager - Lost task 1.3 in stage 4.0 (TID 11) on 10.47.160.4, executor 0: java.lang.NullPointerException (null) [duplicate 3]
15:48:04.581 [task-result-getter-3] ERROR o.a.spark.scheduler.TaskSetManager - Task 1 in stage 4.0 failed 4 times; aborting job
15:48:04.590 [dag-scheduler-event-loop] INFO  o.a.s.scheduler.TaskSchedulerImpl - Cancelling stage 4
15:48:04.596 [dag-scheduler-event-loop] INFO  o.a.s.scheduler.TaskSchedulerImpl - Stage 4 was cancelled
15:48:04.597 [dag-scheduler-event-loop] INFO  o.a.spark.scheduler.DAGScheduler - ResultStage 4 (treeAggregate at ParameterAveragingTrainingMaster.java:658) failed in 1.801 s due to Job aborted due to stage failure: Task 1 in stage 4.0 failed 4 times, most recent failure: Lost task 1.3 in stage 4.0 (TID 11, 10.47.160.4, executor 0): java.lang.NullPointerException
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2028)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2028)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
15:48:04.598 [dag-scheduler-event-loop] DEBUG o.a.spark.scheduler.DAGScheduler - After removal of stage 4, remaining stages = 1
15:48:04.598 [dag-scheduler-event-loop] DEBUG o.a.spark.scheduler.DAGScheduler - After removal of stage 3, remaining stages = 0
15:48:04.599 [main] INFO  o.a.spark.scheduler.DAGScheduler - Job 3 failed: treeAggregate at ParameterAveragingTrainingMaster.java:658, took 2.095814 s
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 27.428 sec <<< FAILURE! - in com.liweigu.dls.offical.RegressionSumTest
testSum(com.liweigu.dls.offical.RegressionSumTest)  Time elapsed: 27.427 sec  <<< ERROR!
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 4.0 failed 4 times, most recent failure: Lost task 1.3 in stage 4.0 (TID 11, 10.47.160.4, executor 0): java.lang.NullPointerException
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2028)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2028)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1918)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1981)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1025)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1007)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1.apply(RDD.scala:1150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.treeAggregate(RDD.scala:1127)
	at org.apache.spark.api.java.JavaRDDLike$class.treeAggregate(JavaRDDLike.scala:439)
	at org.apache.spark.api.java.AbstractJavaRDDLike.treeAggregate(JavaRDDLike.scala:45)
	at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster.processResults(ParameterAveragingTrainingMaster.java:658)
	at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster.doIteration(ParameterAveragingTrainingMaster.java:528)
	at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster.executeTrainingDirect(ParameterAveragingTrainingMaster.java:391)
	at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster.executeTraining(ParameterAveragingTrainingMaster.java:333)
	at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.fit(SparkDl4jMultiLayer.java:250)
	at com.liweigu.dls.offical.RegressionSum.test(RegressionSum.java:196)
	at com.liweigu.dls.offical.RegressionSumTest.testSum(RegressionSumTest.java:10)
Caused by: java.lang.NullPointerException
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2028)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2028)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

15:48:04.611 [Thread-3] INFO  org.apache.spark.SparkContext - Invoking stop() from shutdown hook

**Comment by liweigu** [comment]
After I replace the spark (server) V2.1.1 by V2.1.0, the error disappeared.

**Comment by AlexDBlack** [comment]
OK, sounds like this was just an issue of mismatched versions - I'll close this.
