### ISSUE TITLE
DL4J: Unit test failures on CUDA

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5955]
2 failures on CUDA - passing on CPU:

CNN1DGradientCheckTest.testCnn1DWithLocallyConnected1D and testCnnLocallyConnected2D

```
o.d.g.GradientCheckUtil - Setting softmax clipping epsilon to 0.0 for class org.nd4j.linalg.lossfunctions.impl.LossMCXENT loss function to avoid spurious gradient check failures
Error at [/repos/deeplearning4j/libnd4j/include/ops/declarable/generic/transforms/concat.cpp:121:0]:
CONCAT op: at least one input array must be non-empty!

java.lang.RuntimeException: Op validation failed

	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.calculateOutputShapesDouble(Native Method)
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.calculateOutputShapesDouble(Nd4jCuda.java:402)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.calculateOutputShape(CudaExecutioner.java:2552)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.calculateOutputShape(DynamicCustomOp.java:555)
	at org.nd4j.autodiff.samediff.SameDiff.generateOutputVariableForOp(SameDiff.java:8684)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:193)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:175)
	at org.nd4j.autodiff.functions.DifferentialFunction.outputVariable(DifferentialFunction.java:401)
	at org.nd4j.autodiff.functions.DifferentialFunctionFactory.concat(DifferentialFunctionFactory.java:1250)
	at org.nd4j.autodiff.samediff.SameDiff.concat(SameDiff.java:7149)
	at org.nd4j.autodiff.samediff.SameDiff.concat(SameDiff.java:7134)
	at org.deeplearning4j.nn.conf.layers.LocallyConnected1D.defineLayer(LocallyConnected1D.java:189)
	at org.deeplearning4j.nn.layers.samediff.SameDiffLayer.doInit(SameDiffLayer.java:221)
	at org.deeplearning4j.nn.layers.samediff.SameDiffLayer.activate(SameDiffLayer.java:79)
	at org.deeplearning4j.nn.layers.AbstractLayer.activate(AbstractLayer.java:267)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.ffToLayerActivationsInWs(MultiLayerNetwork.java:1045)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2592)
	at org.deeplearning4j.gradientcheck.GradientCheckUtil.checkGradients(GradientCheckUtil.java:245)
	at org.deeplearning4j.gradientcheck.GradientCheckUtil.checkGradients(GradientCheckUtil.java:152)
	at org.deeplearning4j.gradientcheck.GradientCheckUtil.checkGradients(GradientCheckUtil.java:144)
	at org.deeplearning4j.gradientcheck.GradientCheckUtil.checkGradients(GradientCheckUtil.java:136)
	at org.deeplearning4j.gradientcheck.GradientCheckUtil.checkGradients(GradientCheckUtil.java:130)
	at org.deeplearning4j.gradientcheck.CNN1DGradientCheckTest.testCnn1DWithLocallyConnected1D(CNN1DGradientCheckTest.java:117)
```

**Comment by raver119** [comment]
Fixes were merged to master. Please confirm problem solved.
