### ISSUE TITLE
KerasModelImport fails when importing weights

### ISSUE THREAD

**Issue by alrutten** [deeplearning4j/deeplearning4j#5964]
version 1.0.0-SNAPSHOT

this line of code returned a MultiLayerNetwork yesterday, but runs into an error today:

`KerasModelImport.importKerasSequentialModelAndWeights(MultiJson,MultiWeights, false)`
```
18/07/25 11:32:45 INFO Nd4jBackend: Loaded [CpuBackend] backend
18/07/25 11:32:45 INFO NativeOpsHolder: Number of threads used for NativeOps: 4
18/07/25 11:32:46 INFO Nd4jBlas: Number of threads used for BLAS: 4
18/07/25 11:32:46 INFO DefaultOpExecutioner: Backend used: [CPU]; OS: [Linux]
18/07/25 11:32:46 INFO DefaultOpExecutioner: Cores: [8]; Memory: [3.4GB];
18/07/25 11:32:46 INFO DefaultOpExecutioner: Blas vendor: [OPENBLAS]
Exception in thread "main" java.lang.NoSuchMethodError: org.nd4j.linalg.api.shape.ShapeDescriptor.<init>([I[IJIC)V
	at org.nd4j.linalg.cpu.nativecpu.DirectShapeInfoProvider.createShapeInformation(DirectShapeInfoProvider.java:31)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:175)
	at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:71)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:327)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1031)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3921)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3788)
	at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readDataSet(Hdf5Archive.java:255)
	at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readDataSet(Hdf5Archive.java:95)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:278)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:141)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:61)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:320)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:255)
  ```
  
  loading just the configuration from json works as before, it's importing the weights that fails:
  ```
  val modelGraphConf = KerasModelImport.importKerasSequentialConfiguration(MultiJson)
  println(modelGraph.summary())
  
  ```
  ```
  {
  "backprop" : true,
  "backpropType" : "Standard",
  "cacheMode" : "NONE",
  "confs" : [ {
    "cacheMode" : "NONE",
    "epochCount" : 0,
    "iterationCount" : 0,
    "l1ByParam" : { },
    "l2ByParam" : { },
    "layer" : {
      "@class" : "org.deeplearning4j.nn.conf.layers.EmbeddingSequenceLayer",
      "activationFn" : {
        "@class" : "org.nd4j.linalg.activations.impl.ActivationIdentity"
      },
      "biasInit" : 0.0,
      "biasUpdater" : null,
      "constraints" : null,
      "dist" : {
        "type" : "org.deeplearning4j.nn.conf.distribution.UniformDistribution",
        "lower" : -0.05,
        "upper" : 0.05
      },
      "gradientNormalization" : "None",
      "gradientNormalizationThreshold" : 1.0,
      "hasBias" : false,
      "idropout" : {
        "@class" : "org.deeplearning4j.nn.conf.dropout.Dropout",
        "p" : 1.0,
        "pschedule" : null
      },
      "inferInputLength" : false,
      "inputLength" : 50,
      "iupdater" : {
        "@class" : "org.nd4j.linalg.learning.config.Sgd",
        "learningRate" : 0.001
      },
      "l1" : 0.0,
      "l1Bias" : 0.0,
      "l2" : 0.0,
      "l2Bias" : 0.0,
      "layerName" : "embedding_2",
      "nin" : 2935,
      "nout" : 50,
      "pretrain" : false,
      "weightInit" : "DISTRIBUTION",
      "weightNoise" : null
    },
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : true,
    "minimize" : true,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 1532511512519,
    "stepFunction" : null,
    "variables" : [ ]
  }, {
    "cacheMode" : "NONE",
    "epochCount" : 0,
    "iterationCount" : 0,
    "l1ByParam" : { },
    "l2ByParam" : { },
    "layer" : {
      "@class" : "org.deeplearning4j.nn.conf.layers.recurrent.Bidirectional",
      "bwd" : {
        "@class" : "org.deeplearning4j.nn.conf.layers.recurrent.LastTimeStep",
        "constraints" : null,
        "gradientNormalization" : null,
        "gradientNormalizationThreshold" : "NaN",
        "idropout" : null,
        "layerName" : "bidirectional_2",
        "pretrain" : false,
        "underlying" : {
          "@class" : "org.deeplearning4j.nn.conf.layers.LSTM",
          "activationFn" : {
            "@class" : "org.nd4j.linalg.activations.impl.ActivationTanH"
          },
          "biasInit" : 0.0,
          "biasUpdater" : null,
          "constraints" : null,
          "dist" : null,
          "distRecurrent" : {
            "type" : "org.deeplearning4j.nn.conf.distribution.OrthogonalDistribution",
            "gain" : 1.0
          },
          "forgetGateBiasInit" : 1.0,
          "gateActivationFn" : {
            "@class" : "org.nd4j.linalg.activations.impl.ActivationHardSigmoid"
          },
          "gradientNormalization" : null,
          "gradientNormalizationThreshold" : "NaN",
          "idropout" : {
            "@class" : "org.deeplearning4j.nn.conf.dropout.Dropout",
            "p" : 1.0,
            "pschedule" : null
          },
          "iupdater" : null,
          "l1" : 0.0,
          "l1Bias" : "NaN",
          "l2" : 0.0,
          "l2Bias" : "NaN",
          "layerName" : "bidirectional_2",
          "nin" : 50,
          "nout" : 100,
          "pretrain" : false,
          "weightInit" : "VAR_SCALING_UNIFORM_FAN_AVG",
          "weightInitRecurrent" : "DISTRIBUTION",
          "weightNoise" : null
        }
      },
      "constraints" : null,
      "fwd" : {
        "@class" : "org.deeplearning4j.nn.conf.layers.recurrent.LastTimeStep",
        "constraints" : null,
        "gradientNormalization" : null,
        "gradientNormalizationThreshold" : "NaN",
        "idropout" : null,
        "layerName" : "bidirectional_2",
        "pretrain" : false,
        "underlying" : {
          "@class" : "org.deeplearning4j.nn.conf.layers.LSTM",
          "activationFn" : {
            "@class" : "org.nd4j.linalg.activations.impl.ActivationTanH"
          },
          "biasInit" : 0.0,
          "biasUpdater" : null,
          "constraints" : null,
          "dist" : null,
          "distRecurrent" : {
            "type" : "org.deeplearning4j.nn.conf.distribution.OrthogonalDistribution",
            "gain" : 1.0
          },
          "forgetGateBiasInit" : 1.0,
          "gateActivationFn" : {
            "@class" : "org.nd4j.linalg.activations.impl.ActivationHardSigmoid"
          },
          "gradientNormalization" : null,
          "gradientNormalizationThreshold" : "NaN",
          "idropout" : {
            "@class" : "org.deeplearning4j.nn.conf.dropout.Dropout",
            "p" : 1.0,
            "pschedule" : null
          },
          "iupdater" : null,
          "l1" : 0.0,
          "l1Bias" : "NaN",
          "l2" : 0.0,
          "l2Bias" : "NaN",
          "layerName" : "bidirectional_2",
          "nin" : 50,
          "nout" : 100,
          "pretrain" : false,
          "weightInit" : "VAR_SCALING_UNIFORM_FAN_AVG",
          "weightInitRecurrent" : "DISTRIBUTION",
          "weightNoise" : null
        }
      },
      "gradientNormalization" : null,
      "gradientNormalizationThreshold" : "NaN",
      "idropout" : null,
      "layerName" : "bidirectional_2",
      "mode" : "CONCAT",
      "nin" : 50,
      "nout" : 100,
      "pretrain" : false
    },
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : true,
    "minimize" : true,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 1532511512519,
    "stepFunction" : null,
    "variables" : [ ]
  }, {
    "cacheMode" : "NONE",
    "epochCount" : 0,
    "iterationCount" : 0,
    "l1ByParam" : { },
    "l2ByParam" : { },
    "layer" : {
      "@class" : "org.deeplearning4j.nn.conf.layers.DenseLayer",
      "activationFn" : {
        "@class" : "org.nd4j.linalg.activations.impl.ActivationReLU"
      },
      "biasInit" : 0.0,
      "biasUpdater" : null,
      "constraints" : null,
      "dist" : null,
      "gradientNormalization" : "None",
      "gradientNormalizationThreshold" : 1.0,
      "hasBias" : true,
      "idropout" : {
        "@class" : "org.deeplearning4j.nn.conf.dropout.Dropout",
        "p" : 1.0,
        "pschedule" : null
      },
      "iupdater" : {
        "@class" : "org.nd4j.linalg.learning.config.Sgd",
        "learningRate" : 0.001
      },
      "l1" : 0.0,
      "l1Bias" : 0.0,
      "l2" : 0.0,
      "l2Bias" : 0.0,
      "layerName" : "dense_3",
      "nin" : 200,
      "nout" : 25,
      "pretrain" : false,
      "weightInit" : "VAR_SCALING_UNIFORM_FAN_AVG",
      "weightNoise" : null
    },
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : true,
    "minimize" : true,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 1532511512519,
    "stepFunction" : null,
    "variables" : [ ]
  }, {
    "cacheMode" : "NONE",
    "epochCount" : 0,
    "iterationCount" : 0,
    "l1ByParam" : { },
    "l2ByParam" : { },
    "layer" : {
      "@class" : "org.deeplearning4j.nn.conf.layers.DenseLayer",
      "activationFn" : {
        "@class" : "org.nd4j.linalg.activations.impl.ActivationSoftmax"
      },
      "biasInit" : 0.0,
      "biasUpdater" : null,
      "constraints" : null,
      "dist" : null,
      "gradientNormalization" : "None",
      "gradientNormalizationThreshold" : 1.0,
      "hasBias" : true,
      "idropout" : {
        "@class" : "org.deeplearning4j.nn.conf.dropout.Dropout",
        "p" : 1.0,
        "pschedule" : null
      },
      "iupdater" : {
        "@class" : "org.nd4j.linalg.learning.config.Sgd",
        "learningRate" : 0.001
      },
      "l1" : 0.0,
      "l1Bias" : 0.0,
      "l2" : 0.0,
      "l2Bias" : 0.0,
      "layerName" : "dense_4",
      "nin" : 25,
      "nout" : 14,
      "pretrain" : false,
      "weightInit" : "VAR_SCALING_UNIFORM_FAN_AVG",
      "weightNoise" : null
    },
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : true,
    "minimize" : true,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 1532511512519,
    "stepFunction" : null,
    "variables" : [ ]
  } ],
  "epochCount" : 0,
  "inferenceWorkspaceMode" : "ENABLED",
  "inputPreProcessors" : { },
  "iterationCount" : 0,
  "pretrain" : false,
  "tbpttBackLength" : 20,
  "tbpttFwdLength" : 20,
  "trainingWorkspaceMode" : "ENABLED"
}

Process finished with exit code 0
```

**Comment by alrutten** [comment]
ok i needed to sbt reload/clean/update, sorry.
