### ISSUE TITLE
ND4J: Subtraction INDArray.sub(INDArrayScalar) throws error

### ISSUE THREAD

**Issue by snoop247** [deeplearning4j/deeplearning4j#6000]
Hello.

I wanted to use a normalizer `class` from a colleague, which worked before April/May 2018. Now calling the `sub` method of an `INDArray` with an `INDArray` - containing a scalar - as parameter in this `class` and anywhere else throws the error below. I tried to check the called lines in `BaseNDArray` etc. and to me it looks like the methods for subtracting a scalar are called, but I did not get, why it falls apart. This only happened with `sub`. `add`, `mul` and `div` do not throw errors. I replaced the `INDArray` - containing a scalar - with an actual `double` scalar and it works fine now, but I thought, `sub` should work with a scalar `INDArray` nonetheless. 

Best regards
Daniel

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
...
Caused by: org.nd4j.linalg.exception.ND4JIllegalStateException: op.X length should be equal to op.Z length: [[2, 1093, 1, 28, 1, 0, 28, 99]] != [[2, 1, 1, 1, 1, 0, 1, 99]]
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:630) ~[nd4j-native-1.0.0-beta.jar:na]
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:114) ~[nd4j-native-1.0.0-beta.jar:na]
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:1706) ~[nd4j-api-1.0.0-beta.jar:1.0.0-beta]
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:3670) ~[nd4j-api-1.0.0-beta.jar:1.0.0-beta]
	at org.nd4j.linalg.api.ndarray.BaseNDArray.sub(BaseNDArray.java:3368) ~[nd4j-api-1.0.0-beta.jar:1.0.0-beta]
	at net.xxx.applications.xxx.training.esn.Normalizer.minMaxScaling(Normalizer.java:29) ~[classes/:na]
```

An example method throwing error in line `col = col.sub(minimu).div ...`:

```
public INDArray minMaxScaling(INDArray x, double min, double max)
    {
        for (int i=0; i<x.columns(); i++)
        {
            INDArray col = x.getColumn(i);
            INDArray minimum = Nd4j.min(col);
            INDArray maximum = Nd4j.max(col);
            // Scaling from 0 to 1
            System.out.println(minimum);
            System.out.println(maximum);
            col = col.sub(minimum).div(maximum.sub(minimum));
            // Scaling to defined interval
            col = col.mul(max-min).add(min);
            // Write to x
            x.putColumn(i, col);
        }
        return x;
    }
```

**Comment by raver119** [comment]
Could you please provide self-containing test that fails?

**Comment by snoop247** [comment]
@raver119 
I am sorry, I am very new to the java world and particularly to testing. Do you need a piece of code, that you can run, that fails, or do you need a special test (junit or similar).

**Comment by raver119** [comment]
Nevermind, it's reproducible for me too 😄

**Comment by snoop247** [comment]
@raver119 
Would have been no problem, was already working on a piece of code for you. :)

**Comment by raver119** [comment]
Thanks for highlighting this problem. It's fixed in my PR.
