### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: org.nd4j.linalg.api.ndarray.INDArray.shape()

### ISSUE THREAD

**Issue by alei76** [deeplearning4j/deeplearning4j#6012]
Word2VecRawTextExample 
1.0.0-beta 
Exception in thread "main" java.lang.NoSuchMethodError: org.nd4j.linalg.api.ndarray.INDArray.shape()[J
	at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable.resetWeights(InMemoryLookupTable.java:147)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.fit(SequenceVectors.java:245)
	at org.deeplearning4j.examples.nlp.word2vec.Word2VecRawTextExample.main(Word2VecRawTextExample.java:56)

**Comment by raver119** [comment]
Show your pom.xml please. You have versions clash somewhere

**Comment by alei76** [comment]
thanks！
