### ISSUE TITLE
Exception in CnnToFeedForwardPreProcessor 

### ISSUE THREAD

**Issue by borkox** [deeplearning4j/deeplearning4j#6046]
Hi,
Yesterday my code was working with SNAPSHOT versions, I did nothing more and today after I fetched some maven artefacts (because it is SNAPSHOT) I have this exception:
```
Caused by: java.lang.IllegalStateException: Invalid input array: expected shape [minibatch, channels, height, width] = [minibatch, 32, 5, 19] - got [1, 32, 5, 20]
	at org.deeplearning4j.nn.conf.preprocessor.CnnToFeedForwardPreProcessor.preProcess(CnnToFeedForwardPreProcessor.java:89)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.applyPreprocessorAndSetInput(LayerVertex.java:117)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.setInput(LayerVertex.java:169)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputOfLayersDetached(ComputationGraph.java:2317)
	at org.deeplearning4j.nn.graph.ComputationGraph.rnnTimeStepHelper(ComputationGraph.java:3367)
	at org.deeplearning4j.nn.graph.ComputationGraph.rnnTimeStep(ComputationGraph.java:3351)
	at org.deeplearning4j.rl4j.network.ac.ActorCriticCompGraph.outputAll(ActorCriticCompGraph.java:70)
	at org.deeplearning4j.rl4j.policy.ACPolicy.nextAction(ACPolicy.java:77)
	at org.deeplearning4j.rl4j.policy.ACPolicy.nextAction(ACPolicy.java:39)
	at org.deeplearning4j.rl4j.policy.Policy.play(Policy.java:97)
	at org.deeplearning4j.rl4j.policy.Policy.play(Policy.java:45)
	at com.rltrader.rl.a3c.EvaluatorA3C.evaluateExperiments(EvaluatorA3C.java:52)
	at com.rltrader.rl.a3c.LearnerA3C.startLearn(LearnerA3C.java:119)
	at com.rltrader.App.run(App.java:41)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:797)
```

I will paste the code with the network:
```
package com.rltrader.rl.a3c;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Value;
import lombok.extern.slf4j.Slf4j;
import org.deeplearning4j.nn.api.OptimizationAlgorithm;
import org.deeplearning4j.nn.conf.ComputationGraphConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.inputs.InputType;
import org.deeplearning4j.nn.conf.layers.*;
import org.deeplearning4j.nn.conf.preprocessor.CnnToFeedForwardPreProcessor;
import org.deeplearning4j.nn.conf.preprocessor.FeedForwardToRnnPreProcessor;
import org.deeplearning4j.nn.conf.preprocessor.RnnToCnnPreProcessor;
import org.deeplearning4j.nn.graph.ComputationGraph;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.optimize.api.TrainingListener;
import org.deeplearning4j.optimize.listeners.ScoreIterationListener;
import org.deeplearning4j.rl4j.network.ac.ActorCriticCompGraph;
import org.deeplearning4j.rl4j.network.ac.ActorCriticFactoryCompGraph;
import org.deeplearning4j.rl4j.network.ac.ActorCriticLoss;
import org.deeplearning4j.rl4j.util.Constants;
import org.nd4j.linalg.activations.Activation;
import org.nd4j.linalg.learning.config.Adam;
import org.nd4j.linalg.learning.config.IUpdater;
import org.nd4j.linalg.lossfunctions.LossFunctions;


@Value
@Slf4j
public class ActorCriticFactory implements ActorCriticFactoryCompGraph {


    Configuration conf;

    public ActorCriticCompGraph buildActorCritic(int shapeInputs[], int numOutputs) {

        if (shapeInputs.length == 1)
            throw new AssertionError("Impossible to apply convolutional layer on a shape == 1");

        int h = (((shapeInputs[1] - 1) / 1 + 1) - 1) / 1 + 1;
        int w = (((shapeInputs[2] - 3) / 2 + 1) - 3) / 2 + 1;

        log.info("Output from convolution layers: h:{}, w:{}", h, w);
        ComputationGraphConfiguration.GraphBuilder confB =
                new NeuralNetConfiguration.Builder()
                        .seed(Constants.NEURAL_NET_SEED)
                        .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                        .updater(conf.getUpdater() != null ? conf.getUpdater() : new Adam())
                        .weightInit(WeightInit.XAVIER)
                        .l2(conf.getL2())
                        .graphBuilder()
                        .addInputs("input");

        confB.addLayer("0", new ConvolutionLayer
                .Builder(1, 3)
                .nIn(shapeInputs[0])
                .nOut(16)
                .stride(1, 2)
                .activation(Activation.LEAKYRELU)
                .build(), "input");

        confB.addLayer("1", new ConvolutionLayer
                .Builder(1, 3)
                .nIn(16)
                .nOut(32)
                .stride(1, 2)
                .activation(Activation.LEAKYRELU)
                .build(), "0");

        confB.addLayer("2", new DenseLayer
                .Builder()
                .nIn(w * h * 32)
                .nOut(32)
                .activation(Activation.LEAKYRELU)
                .build(), "1");

        if (conf.isUseLSTM()) {
            confB.addLayer("3", new LSTM
                    .Builder()
                    .nIn(32)
                    .nOut(64)
                    .activation(Activation.TANH)
                    .build(), "2");
//            confB.addLayer("3a", new LSTM
//                    .Builder()
//                    .nIn(96)
//                    .nOut(96)
//                    .activation(Activation.LEAKYRELU)
//                    .build(), "3");

            confB.addLayer("value", new RnnOutputLayer
                    .Builder(LossFunctions.LossFunction.MSE)
                    .activation(Activation.IDENTITY)
                    .nIn(64)
                    .nOut(1)
                    .build(), "3");

            confB.addLayer("softmax", new RnnOutputLayer
                    .Builder(new ActorCriticLoss())
                    .activation(Activation.SOFTMAX)
                    .nIn(64)
                    .nOut(numOutputs)
                    .build(), "3");
        } else {
            confB.addLayer("value", new OutputLayer.Builder(LossFunctions.LossFunction.MSE).activation(Activation.IDENTITY)
                    .nIn(32).nOut(1).build(), "2");

            confB.addLayer("softmax", new OutputLayer.Builder(new ActorCriticLoss()).activation(Activation.SOFTMAX)
                    .nIn(32).nOut(numOutputs).build(), "2");
        }

        confB.setOutputs("value", "softmax");

        if (conf.isUseLSTM()) {
            confB.inputPreProcessor("0", new RnnToCnnPreProcessor(shapeInputs[1], shapeInputs[2], shapeInputs[0]));
            confB.inputPreProcessor("2", new CnnToFeedForwardPreProcessor(h, w, 32));
            confB.inputPreProcessor("3", new FeedForwardToRnnPreProcessor());
        } else {
            confB.setInputTypes(InputType.convolutional(shapeInputs[1], shapeInputs[2], shapeInputs[0]));
        }

        ComputationGraphConfiguration cgconf = confB
                .pretrain(false)
                .backprop(true)
                .build();
        ComputationGraph model = new ComputationGraph(cgconf);
        model.init();
        if (conf.getListeners() != null) {
            model.setListeners(conf.getListeners());
        } else {
            model.setListeners(new ScoreIterationListener(Constants.NEURAL_NET_ITERATION_LISTENER));
        }

        return new ActorCriticCompGraph(model);
    }


    @AllArgsConstructor
    @Builder
    @Value
    public static class Configuration {

        double l2;
        IUpdater updater;
        TrainingListener[] listeners;
        boolean useLSTM;
    }

}

```
I am usng the RL4J packae.

**Comment by AlexDBlack** [comment]
This was a temporary (unintentional) change to the default conovlution mode. A fix has already been merged to master, and new snapshots should be going out soon.
In the mean time, you can explicitly set the convolution mode for your network as a workaround.

**Comment by borkox** [comment]
thank you Alex
