### ISSUE TITLE
libnd4j: edge case shape issue with broadcastable ops

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6071]
First arg is a true scalar. Second arg is a rank 1 or 2 scalar.
It expects a true scalar out - but actually it should be the same shape as the second arg.

If the second op is not a scalar, it seems to work fine

```
    @Test
    public void testMulEdgeCase(){

        INDArray in1 = Nd4j.trueScalar(1.0);
        INDArray in2 = Nd4j.valueArrayOf(new long[]{1}, 2.0);
        INDArray out = Nd4j.create(new long[]{1});
        DynamicCustomOp d = DynamicCustomOp.builder("multiply")
                .addInputs(in1, in2)
                .addOutputs(out)
                .build();

        Nd4j.getExecutioner().exec(d);
        assertEquals(Nd4j.valueArrayOf(new long[]{1}, 2.0), out);
    }

    @Test
    public void testAddEdgeCase(){

        INDArray in1 = Nd4j.trueScalar(1.0);
        INDArray in2 = Nd4j.valueArrayOf(new long[]{1}, 2.0);
        INDArray out = Nd4j.create(new long[]{1});
        DynamicCustomOp d = DynamicCustomOp.builder("add")
                .addInputs(in1, in2)
                .addOutputs(out)
                .build();

        Nd4j.getExecutioner().exec(d);
        assertEquals(Nd4j.valueArrayOf(new long[]{1}, 3.0), out);
    }

    @Test
    public void testMulEdgeCase2(){

        INDArray in1 = Nd4j.trueScalar(1.0);
        INDArray in2 = Nd4j.valueArrayOf(new long[]{1,1}, 2.0);
        INDArray out = Nd4j.create(new long[]{1,1});
        DynamicCustomOp d = DynamicCustomOp.builder("multiply")
                .addInputs(in1, in2)
                .addOutputs(out)
                .build();

        Nd4j.getExecutioner().exec(d);
        assertEquals(Nd4j.valueArrayOf(new long[]{1,1}, 2.0), out);
    }
```

```
Expected vs provided shapes mismatch: [] vs [1]
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute op multiply. Attempted to execute with 2 inputs, 1 outputs, 0 targs and 0 iargs. Please see above message (printed out from c++) for a possible cause of error.

java.lang.RuntimeException: Expected vs provided shapes mismatch

	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOpDouble(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1729)
	at org.nd4j.autodiff.opvalidation.ShapeOpValidation.testMulEdgeCase(ShapeOpValidation.java:1213)
```

**Comment by raver119** [comment]
I wouldn't call that a bug, it's more like one of ancient agreements 😄 
I've changed behaviour now, so issue should be fixed.
