### ISSUE TITLE
ND4j: No tensorflow op found for Assert possibly missing operation class?

### ISSUE THREAD

**Issue by chengqiangboy** [deeplearning4j/deeplearning4j#6082]
I used nd4j to load tensorflow model file, but failed with an exception.

org.nd4j.linalg.exception.ND4JIllegalStateException: No tensorflow op found for Assert possibly missing operation class?
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.mapNodeType(TFGraphMapper.java:495)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.mapNodeType(TFGraphMapper.java:36)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:219)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:69)
	at org.nd4j.imports.graphmapper.BaseGraphMapper.importGraph(BaseGraphMapper.java:107)

**Comment by agibsonccc** [comment]
@chengqiangboy did you freeze your graph properly?

**Comment by raver119** [comment]
@chengqiangboy can you please post your model?

**Comment by chengqiangboy** [comment]
@agibsonccc yes, I has freezed my graph. And it's ok to use tf java api to load pb file. I tried to debug, found the member `tensorFlowNames` of `DifferentialFunctionClassHolder` has no entry which key equals `assert`.

**Comment by chengqiangboy** [comment]
@raver119  i am sorry, but i could not upload my model file.

**Comment by agibsonccc** [comment]
@chengqiangboy assertion isn't something we have seen in the graphs we've tested so far for model import. We'd really need to see a copy of your graph. I'm not sure why you "can't" upload your model file. We don't want your secrets. We want something that reproduces the problem. We don't care what it is.

**Comment by chengqiangboy** [comment]
<img width="960" alt="20180804184642" src="https://user-images.githubusercontent.com/14273620/43675700-e588bcd2-9816-11e8-9e73-22583f19ac85.png">

@agibsonccc  i understand you, but is there an other way to help to solve this issue?


i had find a similar issue:
https://github.com/tensorflow/tfjs/issues/55

**Comment by agibsonccc** [comment]
@chengqiangboy again, please post a version of this we can reproduce. The fact it's an issue on another repo, might mean that assert is just not an op that should be output as part of being frozen. We would need to run something to really know.

**Comment by agibsonccc** [comment]
@chengqiangboy thanks for sending the file, we'll take a look.

**Comment by chengqiangboy** [comment]
@agibsonccc  since the model file is larger than 10MB, i send an email with model file to you.
after remove `Assert` nodes, there is a similar issue `No tensorflow op found for ArgMax possibly missing operation class?`.

**Comment by raver119** [comment]
@chengqiangboy ArgMax is an easy fix. Can you please tell me what input dimensionality your test model expects, so i could check if it actually runs with fix provided?

**Comment by raver119** [comment]
@chengqiangboy nevermind. ArgMax issue is resolved now, and i'm definitely able to import your graph now.

Thanks for highlighting this problem.

**Comment by chengqiangboy** [comment]
@raver119  @agibsonccc 
in my other model, `assert` op is produced by tf's api `rnn cell(LSTM)`, `assert` cannot be remove, could you help me？

**Comment by raver119** [comment]
You know answer i think: send me a model, and i'll take a look.

But once again, it's strange: we have rnn models in tests, and i'm yet to see any single assert use there.
