### ISSUE TITLE
DL4J: TestSameDiffOutput issues on CUDA

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6097]
No JVM crash log - just this on TestOutputMSELossLayer:
```
Process finished with exit code -1073740940 (0xC0000374)
```

TestMSEOutputLayer gives the following:
```
Mismatched shape: [1, 2, 1, 0, 1, 99]
Shape requested: : {1, 5}

java.lang.RuntimeException: Bad shape!

	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.execCustomOpDouble(Native Method)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2869)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:10484)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:9374)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:9413)
```

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/layers/samediff/TestSameDiffOutput.java

**Comment by AlexDBlack** [comment]
OK, so I've isolated it to this:
```
    @Test
    public void test6097() throws Exception {
//        Nd4j.setDataType(DataBuffer.Type.FLOAT);  //PASSES on FP32
        Nd4j.setDataType(DataBuffer.Type.DOUBLE);   //CRASHES on FP64

        INDArray in1 = Nd4j.create(new long[]{2,5});
        INDArray in2 = Nd4j.create(new long[]{2});
        INDArray out = Nd4j.create(new long[]{2,5});

        MeanBp op = new MeanBp(in1, in2, out, false, 1);

        Nd4j.getExecutioner().exec(op);
    }
```

**Comment by raver119** [comment]
Fixed now.
