### ISSUE TITLE
Datavec: JDBC - NullPointerException when column value in db is Null

### ISSUE THREAD

**Issue by acampesino** [deeplearning4j/deeplearning4j#6112]
JDBCRecordReader throws a NullPointerException if there are records in the db that does not have a value for some of the columns (Null):

java.lang.NullPointerException
	at org.datavec.api.util.jdbc.JdbcWritableConverter.convert(JdbcWritableConverter.java:50)
	at org.datavec.api.records.reader.impl.jdbc.JDBCRecordReader.toWritable(JDBCRecordReader.java:204)
	at org.datavec.api.records.reader.impl.jdbc.JDBCRecordReader.nextRecord(JDBCRecordReader.java:266)
	at org.acr.deeplearning.trav.core.dl.JDBCJoinFlatRecordReader.nextRecord(JDBCJoinFlatRecordReader.java:110)
	at org.acr.deeplearning.trav.core.dl.JDBCDataSetProvider.main(JDBCDataSetProvider.java:57)

**Comment by raver119** [comment]
Should be fixed now i think.
