### ISSUE TITLE
Issue with DataSetIterator under hdfs?

### ISSUE THREAD

**Issue by new2scala** [deeplearning4j/deeplearning4j#6126]
I ran into following Exception with **MnistMLPExample** (as well as **SparkLSTMCharacterExample**) using spark cluster on AWS with Hadoop
`2018-08-10 10:49:01 WARN  TaskSetManager:66 - Lost task 3.3 in stage 5.0 (TID 543, 172.16.1.98, executor 2): java.lang.RuntimeException: Error loading DataSet at path /tmp/dbg11/1533890930955_52db26fe/1/data/dataset_352db26fe_5.bin - DataSet may be corrupt or invalid. Spark DataSets can be validated using org.deeplearning4j.spark.util.data.SparkDataValidation
	at org.deeplearning4j.spark.iterator.PathSparkDataSetIterator.load(PathSparkDataSetIterator.java:73)
	at org.deeplearning4j.spark.iterator.PathSparkDataSetIterator.next(PathSparkDataSetIterator.java:48)
	at org.deeplearning4j.spark.iterator.PathSparkDataSetIterator.next(PathSparkDataSetIterator.java:21)
	at org.deeplearning4j.datasets.iterator.IteratorDataSetIterator.next(IteratorDataSetIterator.java:59)
	at org.deeplearning4j.datasets.iterator.IteratorDataSetIterator.next(IteratorDataSetIterator.java:44)
	at org.deeplearning4j.datasets.iterator.IteratorDataSetIterator.next(IteratorDataSetIterator.java:18)
	at org.deeplearning4j.spark.api.worker.ExecuteWorkerFlatMapAdapter.call(ExecuteWorkerFlatMap.java:99)
	at org.deeplearning4j.spark.api.worker.ExecuteWorkerFlatMapAdapter.call(ExecuteWorkerFlatMap.java:42)
	at org.deeplearning4j.spark.api.worker.ExecuteWorkerPathFlatMapAdapter.call(ExecuteWorkerPathFlatMap.java:71)
	at org.deeplearning4j.spark.api.worker.ExecuteWorkerPathFlatMapAdapter.call(ExecuteWorkerPathFlatMap.java:38)
	at org.datavec.spark.transform.BaseFlatMapFunctionAdaptee.call(BaseFlatMapFunctionAdaptee.java:24)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:800)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:800)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: File /tmp/dbg11/1533890930955_52db26fe/1/data/dataset_352db26fe_5.bin does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:611)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:824)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:601)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:421)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:142)
	at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:346)
	at org.deeplearning4j.spark.iterator.PathSparkDataSetIterator.load(PathSparkDataSetIterator.java:70)
	... 30 more
`
I checked the file `/tmp/dbg11/1533890930955_52db26fe/1/data/dataset_352db26fe_5.bin` is present in hdfs. The `PathSparkDataSetIterator` seems to have tried to read the file on the local file system, and thus ended with `**FileNotFoundException**`.

dl4j version details
`        <nd4j.backend>nd4j-native-platform</nd4j.backend>

        <nd4j.version>1.0.0-beta</nd4j.version>
        <dl4j.version>1.0.0-beta</dl4j.version>
        <datavec.version>1.0.0-beta</datavec.version>
        <dl4j.spark.version>1.0.0-beta_spark_2</dl4j.spark.version>
        <scala.binary.version>2.11</scala.binary.version>`

Is this a bug? Any suggested fixes/workarounds?

**Comment by new2scala** [comment]
Found a workaround (in case you run into the same issue on cluster with hdfs): add the following config to the `TrainingMaster`
`.rddTrainingApproach(RDDTrainingApproach.Direct)`

**Comment by agibsonccc** [comment]
Closing: Spark is no longer supported in DL4J.
