### ISSUE TITLE
UNet bug

### ISSUE THREAD

**Issue by AemonAlgiz** [deeplearning4j/deeplearning4j#6135]
Calling init() on UNet throws the following:

Exception in thread "main" java.lang.IllegalStateException: Invalid configuration: disconnected vertices found - [up9-1]. Disconnected vertices are those that do not connect to either another vertex, and are also not a network output. To disable this error (i.e., allow network configurations with disconnected vertices) use GraphBuilder.allowDisconnected(true)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.validate(ComputationGraphConfiguration.java:346)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.build(ComputationGraphConfiguration.java:1033)
	at org.deeplearning4j.zoo.model.UNet.init(UNet.java:76)
	at org.deeplearning4j.zoo.model.UNet.init(UNet.java:34)
	at com.asinm.pix2net.neuralnetwok.Main.main(Main.java:23)

**Comment by raver119** [comment]
cc @crockpotveggies

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/6653
