### ISSUE TITLE
 execSSReduceScalarFloat(...) failedError code [4]

### ISSUE THREAD

**Issue by longzhendong** [deeplearning4j/deeplearning4j#6140]
Exception in thread "main" java.lang.RuntimeException: execSSReduceScalarFloat(...) failedError code [4]
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.execSummaryStatsScalarFloat(Native Method)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.naiveExec(CudaExecutioner.java:386)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:647)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.exec(CudaGridExecutioner.java:695)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.std(BaseNDArray.java:4765)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.stdNumber(BaseNDArray.java:1288)
	at org.deeplearning4j.ui.stats.BaseStatsListener.calculateSummaryStats(BaseStatsListener.java:757)
	at org.deeplearning4j.ui.stats.BaseStatsListener.onForwardPass(BaseStatsListener.java:273)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1362)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1326)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:160)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:51)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1149)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1098)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1065)
	at CnnWeatherEncoderDecoderFromModel.main(CnnWeatherEncoderDecoderFromModel.java:80)
	Suppressed: java.lang.RuntimeException: cudaStreamSynchronize(...) failed
		at org.nd4j.nativeblas.Nd4jCuda$NativeOps.streamSynchronize(Native Method)
		at org.nd4j.linalg.jcublas.context.CudaContext.syncSpecialStream(CudaContext.java:112)
		at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.flushQueueBlocking(CudaGridExecutioner.java:959)
		at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.commit(CudaGridExecutioner.java:1087)
		at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:594)
		at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1402)
		... 8 more
Exception in thread "UniGC thread 2" Exception in thread "UniGC thread 1" java.lang.RuntimeException: cudaEventSynchronize(...) failed
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.eventSynchronize(Native Method)
	at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.synchronize(cudaEvent_t.java:69)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillFinished(SynchronousFlowController.java:132)
	at org.nd4j.jita.flow.impl.GridFlowController.waitTillFinished(GridFlowController.java:63)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillReleased(SynchronousFlowController.java:229)
	at org.nd4j.jita.flow.impl.GridFlowController.waitTillReleased(GridFlowController.java:78)
	at org.nd4j.jita.allocator.impl.AtomicAllocator$UnifiedGarbageCollectorThread.run(AtomicAllocator.java:716)
Exception in thread "UniGC thread 4" Exception in thread "UniGC thread 3" java.lang.RuntimeException: cudaEventSynchronize(...) failed
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.eventSynchronize(Native Method)
	at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.synchronize(cudaEvent_t.java:69)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillFinished(SynchronousFlowController.java:132)
	at org.nd4j.jita.flow.impl.GridFlowController.waitTillFinished(GridFlowController.java:63)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillReleased(SynchronousFlowController.java:229)
	at org.nd4j.jita.flow.impl.GridFlowController.waitTillReleased(GridFlowController.java:78)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.purgeDeviceObject(CudaZeroHandler.java:1152)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.purgeDeviceObject(AtomicAllocator.java:535)
	at org.nd4j.jita.allocator.impl.AtomicAllocator$UnifiedGarbageCollectorThread.run(AtomicAllocator.java:734)
Exception in thread "UniGC thread 5" java.lang.RuntimeException: cudaEventSynchronize(...) failed
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.eventSynchronize(Native Method)
	at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.synchronize(cudaEvent_t.java:69)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillFinished(SynchronousFlowController.java:132)
	at org.nd4j.jita.flow.impl.GridFlowController.waitTillFinished(GridFlowController.java:63)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillReleased(SynchronousFlowController.java:229)
	at org.nd4j.jita.flow.impl.GridFlowController.waitTillReleased(GridFlowController.java:78)
	at org.nd4j.jita.allocator.impl.AtomicAllocator$UnifiedGarbageCollectorThread.run(AtomicAllocator.java:716)

**Comment by agibsonccc** [comment]
Please add more information next time. Don't just post a stack trace. We don't have any context.

**Comment by modianor** [comment]
hi , buddy. how do you fix this problem??it has confused me for a very long time

**Comment by longzhendong** [comment]
@modianor 
Later, I found that this problem occurs when the network structure is large and the gpu is short of memor

**Comment by longzhendong** [comment]
@modianor GPU内存不足的时候

**Comment by modianor** [comment]
Maybe the performance of my gpu is too poor.That is to say,i have to train this network by  cpu or pass it.Thank you,buddy.

**Comment by raver119** [comment]
@modianor last thing you should do is posting in closed topics. Please, file new issue and post your problems there, so we could take a look and help.
