### ISSUE TITLE
Datavec-api | JacksonLineRecordReaderTest.testJacksonLineSequenceRecordReader test failure

### ISSUE THREAD

**Issue by sshepel** [deeplearning4j/deeplearning4j#6141]
Platform: linux-x86_64
Backend: CPU
More details: http://master-jenkins.skymind.io:8080/blue/organizations/jenkins/deeplearning4j%2Fdeeplearning4j/detail/PR-6139/2/pipeline/55/
Error logs:
```
--------------------------------

java.lang.RuntimeException: Error during LineRecordReader reset

	at org.datavec.api.records.reader.impl.LineRecordReader.reset(LineRecordReader.java:160)

	at org.datavec.api.records.reader.impl.csv.CSVRecordReader.reset(CSVRecordReader.java:227)

	at org.datavec.api.records.reader.impl.CSVRecordReaderTest.testStreamReset(CSVRecordReaderTest.java:311)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)

	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)

	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)

	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)

	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)

	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)

	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

Caused by: java.lang.UnsupportedOperationException: Reset not supported from streams

	at org.datavec.api.split.InputStreamInputSplit.reset(InputStreamInputSplit.java:143)

	at org.datavec.api.records.reader.impl.LineRecordReader.reset(LineRecordReader.java:156)

	... 26 more

Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.293 sec - in org.datavec.api.records.reader.impl.CSVRecordReaderTest

Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/home/jenkins/workspace/deeplearning4j-PR-6139-linux-x86_64-cpu@tmp/withMaven6d05533b/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/home/jenkins/workspace/deeplearning4j-PR-6139-linux-x86_64-cpu@tmp/withMaven6d05533b" 

Running org.datavec.api.records.reader.impl.TestConcatenatingRecordReader

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.2 sec - in org.datavec.api.records.reader.impl.TestConcatenatingRecordReader

Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/home/jenkins/workspace/deeplearning4j-PR-6139-linux-x86_64-cpu@tmp/withMaven6d05533b/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/home/jenkins/workspace/deeplearning4j-PR-6139-linux-x86_64-cpu@tmp/withMaven6d05533b" 

Running org.datavec.api.records.reader.impl.CSVVariableSlidingWindowRecordReaderTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.224 sec - in org.datavec.api.records.reader.impl.CSVVariableSlidingWindowRecordReaderTest

Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/home/jenkins/workspace/deeplearning4j-PR-6139-linux-x86_64-cpu@tmp/withMaven6d05533b/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/home/jenkins/workspace/deeplearning4j-PR-6139-linux-x86_64-cpu@tmp/withMaven6d05533b" 

Running org.datavec.api.records.reader.impl.JacksonLineRecordReaderTest

Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.42 sec <<< FAILURE! - in org.datavec.api.records.reader.impl.JacksonLineRecordReaderTest

testJacksonLineSequenceRecordReader(org.datavec.api.records.reader.impl.JacksonLineRecordReaderTest)  Time elapsed: 0.271 sec  <<< FAILURE!

java.lang.AssertionError: expected:<[[aValue0, bValue0, cxValue0], [aValue1, MISSING_B, cxValue1], [aValue2, bValue2, MISSING_CX]]> but was:<[[aValue3, bValue3, cxValue3]]>

	at org.datavec.api.records.reader.impl.JacksonLineRecordReaderTest.testJacksonLineSequenceRecordReader(JacksonLineRecordReaderTest.java:103)


Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/home/jenkins/workspace/deeplearning4j-PR-6139-linux-x86_64-cpu@tmp/withMaven6d05533b/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/home/jenkins/workspace/deeplearning4j-PR-6139-linux-x86_64-cpu@tmp/withMaven6d05533b" 

Running org.datavec.api.records.reader.impl.TestCollectionRecordReaders

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.095 sec - in org.datavec.api.records.reader.impl.TestCollectionRecordReaders

Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/home/jenkins/workspace/deeplearning4j-PR-6139-linux-x86_64-cpu@tmp/withMaven6d05533b/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/home/jenkins/workspace/deeplearning4j-PR-6139-linux-x86_64-cpu@tmp/withMaven6d05533b" 

Running org.datavec.api.records.reader.impl.CSVNLinesSequenceRecordReaderTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.228 sec - in org.datavec.api.records.reader.impl.CSVNLinesSequenceRecordReaderTest

Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/home/jenkins/workspace/deeplearning4j-PR-6139-linux-x86_64-cpu@tmp/withMaven6d05533b/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/home/jenkins/workspace/deeplearning4j-PR-6139-linux-x86_64-cpu@tmp/withMaven6d05533b" 

Running org.datavec.api.split.FileSplitTest

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.107 sec - in org.datavec.api.split.FileSplitTest

Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/home/jenkins/workspace/deeplearning4j-PR-6139-linux-x86_64-cpu@tmp/withMaven6d05533b/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/home/jenkins/workspace/deeplearning4j-PR-6139-linux-x86_64-cpu@tmp/withMaven6d05533b" 

Running org.datavec.api.split.TransformSplitTest

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.103 sec - in org.datavec.api.split.TransformSplitTest

Results :

Failed tests: 

  JacksonLineRecordReaderTest.testJacksonLineSequenceRecordReader:103 expected:<[[aValue0, bValue0, cxValue0], [aValue1, MISSING_B, cxValue1], [aValue2, bValue2, MISSING_CX]]> but was:<[[aValue3, bValue3, cxValue3]]>
```

**Comment by sshepel** [comment]
Fixed in #6144 by @AlexDBlack, thanks!
