### ISSUE TITLE
UI/Nd4j possible issue? 

### ISSUE THREAD

**Issue by sandgrules** [deeplearning4j/deeplearning4j#6147]
I'm working a scala/maven/intellij/DL4J project. I have a ComputationGraph that I'm training over an array of MultiDataSets, with backend set to nd4j-native-platform. It appears to train fine until I try to use the Training UI. My relevant code snip: 
    import org.deeplearning4j.ui.api.UIServer
    val uiServer = UIServer.getInstance
    val statsStorage = new InMemoryStatsStorage()
    uiServer.attach(statsStorage)
    val localModel = myDualModel.getNetwork
    localModel.setListeners(new StatsListener(statsStorage))
    var count = 0
    while (count < nEpochs){
      val myTrianingData = dataAE.toIterator
      while (myTrianingData.hasNext){
        localModel.fit(myTrianingData.next())
      }
      count+=1
    }

myDualModel is a SparkComputationGraph that I'm getting to a non-distributed network for testing. If I comment out the line "localModel.setListeners(new StatsListener(statsStorage))" it appears to run fine. However, when I try and run it as-is I get the following error: 
07:14:53.380 [main] INFO  play.api.Play - Application started (Prod)
07:14:53.538 [main] INFO  play.core.server.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
07:14:53.539 [main] INFO  o.d.ui.play.PlayUIServer - DL4J UI Server started at http://localhost:9000
07:14:53.541 [main] INFO  o.d.ui.play.PlayUIServer - StatsStorage instance attached to UI: InMemoryStatsStorage(uid=09434de0)
Exception in thread "main" java.lang.NoSuchMethodError: org.nd4j.linalg.api.ndarray.INDArray.length()J
	at org.deeplearning4j.ui.stats.BaseStatsListener.getHistograms(BaseStatsListener.java:784)
	at org.deeplearning4j.ui.stats.BaseStatsListener.onForwardPass(BaseStatsListener.java:267)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1315)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1280)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:178)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:60)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:54)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1104)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:985)

Dependency in POM: 
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-ui_2.10</artifactId>
            <version>1.0.0-beta2</version>
        </dependency>

**Comment by raver119** [comment]
You have versions class somewhere in your pom.xml. Mixing different dl4j/nd4j versions.

**Comment by sandgrules** [comment]
@raver119 :+1: 

I had dl4j/nd4j 1.0.0-beta. Once I switched ui from beta2 to beta it started working.

**Comment by raver119** [comment]
you should go in opposite direction: use beta2 everywhere 😊
пн, 13 авг. 2018 г. в 14:40, sandgrules <notifications@github.com>:
