### ISSUE TITLE
Libnd4j: pad op issues

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6172]
https://www.tensorflow.org/api_docs/python/tf/pad

Some issues here:
1. There's no way set the contant value for constant mode (always 0?)
2. I'm getting "Bad size index requested" for the rank 1 input case during execution:

```
    @Test
    public void testPadRank1(){

        INDArray in = Nd4j.valueArrayOf(new long[]{5}, 1.0);
        INDArray pad = Nd4j.create(new double[]{1,1}, new long[]{1,2});
        INDArray value = Nd4j.trueScalar(10.0);

        INDArray out = Nd4j.create(new long[]{7});

        DynamicCustomOp op = DynamicCustomOp.builder("pad")
                .addInputs(in, pad, value)
                //.addInputs(in, pad) //Also doesn't work
                .addOutputs(out)
                .addIntegerArguments(0) //0 = CONSTANT
                .build();

        Nd4j.getExecutioner().exec(op);

        INDArray exp = Nd4j.trueVector(new double[]{10, 1, 1, 1, 1, 1, 10});
        assertEquals(exp, out);
    }
```

```
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 8
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute op pad. Attempted to execute with 2 inputs, 1 outputs, 0 targs and 1 iargs. Please see above message (printed out from c++) for a possible cause of error.

java.lang.RuntimeException: Bad size index requested
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOpDouble(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1729)
	at org.nd4j.autodiff.opvalidation.TransformOpValidation.testPad(TransformOpValidation.java:1513)
```

**Comment by AlexDBlack** [comment]
Also crash on mirror pad:

```
    @Test
    public void testMirrorPad(){

        INDArray in = Nd4j.valueArrayOf(new long[]{5}, 1.0);
        INDArray pad = Nd4j.create(new double[]{1,1}, new long[]{1,2});

        INDArray out = Nd4j.create(new long[]{7});

        DynamicCustomOp op = DynamicCustomOp.builder("mirror_pad")
                .addInputs(in, pad)
                .addOutputs(out)
                .addIntegerArguments(0) //0=reflect, 1=symmetric
                .build();

        Nd4j.getExecutioner().exec(op);

        INDArray exp = Nd4j.trueVector(new double[]{1, 1, 1, 1, 1, 1, 1});
        assertEquals(exp, out);
    }
```

```
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 8

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'std::invalid_argument'
  what():  NDArray::operator(i): dinput index is out of array length !

Process finished with exit code 3
```

**Comment by AlexDBlack** [comment]
Reopening this: Neither of the above test cases are passing.

The ability to specify the constant value is still not implemented.
The mirror pad test case above still crashes the JVM.
