### ISSUE TITLE
CUDNN_STATUS_MAPPING_ERROR with batchSize of 1

### ISSUE THREAD

**Issue by maclema** [deeplearning4j/deeplearning4j#6206]
A CUDNN_STATUS_MAPPING_ERROR exception is thrown when calling fit() on a LSTM network when the batchSize is 1. If the batch size is greater than one everything works as expected.

Environment:
```
OS: Ubuntu 18.04
CUDA: 9.2, V9.2.88
cuDNN: 7.2.1
DL4J: 1.0.0-beta2
ND4j Backend: nd4j-cuda-9.2-platform
```

Model:
```
int hiddenSize = 256;
int numFeatures = 1280;

NeuralNetConfiguration.Builder builder = new NeuralNetConfiguration.Builder();
builder.seed( 123 );
builder.biasInit( 0 );
builder.updater( new Adam( 0.001 ) );
builder.weightInit( WeightInit.XAVIER );
builder.miniBatch( true );

MultiLayerConfiguration conf = builder.list() //
	.layer( new LSTM.Builder().activation( Activation.TANH ).nIn( numFeatures ).nOut( hiddenSize ).build() ) //
	.layer( new LSTM.Builder().activation( Activation.TANH ).nOut( hiddenSize ).build() ) //
	.layer( new LSTM.Builder().activation( Activation.TANH ).nOut( hiddenSize ).build() ) //
	.layer( new RnnOutputLayer.Builder( LossFunction.MSE ).activation( Activation.IDENTITY ).nOut( numFeatures ).build() ) //
	.backpropType( BackpropType.TruncatedBPTT ).tBPTTBackwardLength( 7 ) //
	.build();

MultiLayerNetwork net = new MultiLayerNetwork( conf );
net.init();
return net;
```

Training array shape: [1, 1280, 120]

Exception:
```
Exception in thread "Thread-19" java.lang.RuntimeException: cuDNN status = 7: CUDNN_STATUS_MAPPING_ERROR
	at org.deeplearning4j.nn.layers.BaseCudnnHelper.checkCudnn(BaseCudnnHelper.java:44)
	at org.deeplearning4j.nn.layers.recurrent.CudnnLSTMHelper.activate(CudnnLSTMHelper.java:528)
	at org.deeplearning4j.nn.layers.recurrent.LSTMHelpers.activateHelper(LSTMHelpers.java:206)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.activateHelper(LSTM.java:163)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.activate(LSTM.java:135)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.ffToLayerActivationsInWs(MultiLayerNetwork.java:1038)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2579)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2545)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:160)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:51)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fitHelper(MultiLayerNetwork.java:2148)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:2105)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:2170)
```

**Comment by maclema** [comment]
Hmm. For some reason my code seems to be working as expected today. I'll keep any eye out for this error again and open a new issue with full example if I come across it. 

Thanks

**Comment by AlexDBlack** [comment]
Ok, thanks for letting me know.
I'm happy to take a look if you do run into it again.
