### ISSUE TITLE
Errors in 1.0.0-beta2 when loading w2v model built in 1.0.0-alpha

### ISSUE THREAD

**Issue by xinxu75** [deeplearning4j/deeplearning4j#6215]
When I tried to use run a code and  load w2v models built in 1.0.0-alpha, I got the following error. The code triggering this error is a simple WordVectorSerializer.readWord2VecModel("...")

Exception in thread "main" java.lang.AbstractMethodError: org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createFloat(FF)Lorg/nd4j/linalg/api/complex/IComplexFloat;
	at org.nd4j.linalg.factory.Nd4j.createFloat(Nd4j.java:2786)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6344)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6228)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:207)
	at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable.<init>(InMemoryLookupTable.java:62)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2198)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2150)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2166)
	at text_pred.SINA_WV.load_wv(SINA_WV.java:54)

**Comment by raver119** [comment]
Show your pom.xml, you probably have 1.0.0-alpha dependencies there.

**Comment by xinxu75** [comment]
few hours ago, I just git clone https://github.com/deeplearning4j/dl4j-examples.git, and got everything updated
My code depends on this new project (removed the old dl4j-examples in 1.0.0-alpha)

**Comment by xinxu75** [comment]
Just checked pom.xml in the new project, and it shows 1.0.0-beta2

**Comment by raver119** [comment]
Show it to me please. And show your source code that reproduces this behavior.

**Comment by AlexDBlack** [comment]
@xinxu75 The other common cause: are you using Eclipse IDE by any chance?
It's notorious for not updating dependencies/classpath when you update your pom.xml

**Comment by xinxu75** [comment]
yes I'm using Eclipse, and I found my project accidentally includes a few .jar files of 1.0.0-alpha. Do I need to remove them as well?

**Comment by raver119** [comment]
Yes.
