### ISSUE TITLE
Invalid configuration of layer

### ISSUE THREAD

**Issue by xiptos** [deeplearning4j/deeplearning4j#6218]
Sorry if this is not relevant, but I'm getting the following exception when importing a keras model.

```
[main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
[main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 2
[main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 2
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Mac OS X]
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [4]; Memory: [1.8GB];
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [MKL]
[main] WARN org.deeplearning4j.nn.modelimport.keras.KerasModel - If enforceTrainingConfig is true, a training configuration object has to be provided. Usually the only practical way to do this is to store your keras model with `model.save('model_path.h5'. If you store model config and weights separately no training configuration is attached.
Exception in thread "main" org.deeplearning4j.exception.DL4JInvalidConfigException: Invalid configuration for layer (idx=-1, name=conv1, type=ConvolutionLayer) for height dimension:  Invalid input configuration for kernel height. Require 0 < kH <= inHeight + 2*padH; got (kH=3, inHeight=0, padH=0)
Input type = InputTypeConvolutional(h=0,w=0,c=3), kernel = [3, 3], strides = [1, 1], padding = [0, 0], layer size (output channels) = 10, convolution mode = Truncate
	at org.deeplearning4j.nn.conf.layers.InputTypeUtil.getOutputTypeCnnLayers(InputTypeUtil.java:342)
	at org.deeplearning4j.nn.conf.layers.ConvolutionLayer.getOutputType(ConvolutionLayer.java:181)
	at org.deeplearning4j.nn.modelimport.keras.layers.convolutional.KerasConvolution2D.getOutputType(KerasConvolution2D.java:150)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.inferOutputTypes(KerasModel.java:306)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:181)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:98)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:305)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:234)
	at pt.ipb.face.Mtcnn2Dl4j.main(Mtcnn2Dl4j.java:16)
```

I'm using macOS High Sierra and java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

The model and source code is in attach.

Thanks!
[Mtcnn2Dl4j.java.zip](https://github.com/deeplearning4j/deeplearning4j/files/2302923/Mtcnn2Dl4j.java.zip)
[model.zip](https://github.com/deeplearning4j/deeplearning4j/files/2302924/model.zip)

**Comment by maxpumperla** [comment]
@xiptos I closed your other one, let me have a look at this tomorrow

**Comment by maxpumperla** [comment]
@xiptos the magic sauce here is to provide input shape like this:

```
    @Test
    public void importMTCNN2D() throws Exception {
        ComputationGraph model = importFunctionalModelH5Test("modelimport/keras/examples/12net.h5",
                new int[] {24, 24, 3}, false);
        INDArray input = Nd4j.create(10, 3, 24, 24);
        model.output(input);
    }
```

If you don't, DL4J can't infer input shapes and shape validation for e.g. conv2d layers fails (in your case the net thinks height and width are 0). Whenever you see this error this is likely the solution
