### ISSUE TITLE
ND4J: Empty NDArray has length 1 shape info

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6235]
![image](https://user-images.githubusercontent.com/2360237/44401255-5df55400-a591-11e8-9c53-35de8c657e1e.png)

https://github.com/deeplearning4j/deeplearning4j/blob/c44ce4c209c1dc4c5ac263e7d967aad073b1ce19/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/linalg/cpu/nativecpu/CpuNDArrayFactory.java#L364-L369

Not sure how we want to handle this...

Some other observations:
- toString is broken on empty arrays currently (throws exception
- why is JvmShapeInfo mutable? can these fields be final?

```
ava.lang.IllegalArgumentException: Invalid size: cannot get size of dimension 0 for rank 0 NDArray (array shape: [])

	at org.nd4j.linalg.api.ndarray.BaseNDArray.size(BaseNDArray.java:5247)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.slices(BaseNDArray.java:2545)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:178)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:142)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:121)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:5722)
```

**Comment by alexanderst** [comment]
toString is working for empty arrays now.

Size of empty array and mutability is fixed and will be merged today later.
