### ISSUE TITLE
A question about run Rl4j example

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#6275]
I download gym-http-api, start gym_http_server.py,
run its own example "example_agent.py", it's okay!

I run the Rl4j example "org.deeplearning4j.examples.rl4j.Cartpole", don't work.
And get some error message on server console:

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[2018-08-25 20:16:26,252] ERROR in app: Exception on /v1/envs/d1849c63/observation_space/ [GET]
Traceback (most recent call last):
  File "/apps/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/apps/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/apps/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/apps/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/apps/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/apps/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "gym_http_server.py", line 340, in env_observation_space_info
    return jsonify(info = info)
  File "/apps/anaconda3/lib/python3.6/site-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "/apps/anaconda3/lib/python3.6/site-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/apps/anaconda3/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/apps/anaconda3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/apps/anaconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/apps/anaconda3/lib/python3.6/site-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "/apps/anaconda3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'float32' is not JSON serializable

I dont' know it's a gym-http-api side question, or a Rl4j question?
How I resolve this?

**Comment by saudet** [comment]
Try Python 2.7. I don't think it supports Python 3 too well...

**Comment by Charele** [comment]
Thanks,I will test Python2

**Comment by Charele** [comment]
Hi,Mr saudet, bug is same:-(

  File "/apps/anaconda2/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/apps/anaconda2/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/apps/anaconda2/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/apps/anaconda2/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/apps/anaconda2/lib/python2.7/site-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "/apps/anaconda2/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 4.8 is not JSON serializable

**Comment by saudet** [comment]
Strange, that never happened here. Instead of using Anaconda, have you tried to install the recommended versions of each package?

**Comment by Charele** [comment]
I am not familiar with Python,so I use Anaconda.
And I will try by your step :-)

**Comment by Charele** [comment]
Okay,it works.
When I use "pip install" command, it always install the newest package, I think it's the reason
I read the READMe.md, and I execute the "pip install -r requirements.txt",
It works.

**Comment by Charele** [comment]
八月 28, 2018 8:07:29 下午 org.apache.http.impl.execchain.RetryExec execute
信息: I/O exception (java.net.SocketException) caught when processing request to {}->http://127.0.0.1:5000: No buffer space available (maximum connections reached?): connect
八月 28, 2018 8:07:29 下午 org.apache.http.impl.execchain.RetryExec execute
信息: Retrying request to {}->http://127.0.0.1:5000
八月 28, 2018 8:07:29 下午 org.apache.http.impl.execchain.RetryExec execute
信息: I/O exception (java.net.SocketException) caught when processing request to {}->http://127.0.0.1:5000: No buffer space available (maximum connections reached?): connect
八月 28, 2018 8:07:29 下午 org.apache.http.impl.execchain.RetryExec execute
信息: Retrying request to {}->http://127.0.0.1:5000
八月 28, 2018 8:07:29 下午 org.apache.http.impl.execchain.RetryExec execute
信息: I/O exception (java.net.SocketException) caught when processing request to {}->http://127.0.0.1:5000: No buffer space available (maximum connections reached?): connect
八月 28, 2018 8:07:29 下午 org.apache.http.impl.execchain.RetryExec execute
信息: Retrying request to {}->http://127.0.0.1:5000
Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.gym.ClientUtils.unirestCrash(ClientUtils.java:68)
	at org.deeplearning4j.gym.ClientUtils.post(ClientUtils.java:39)
	at org.deeplearning4j.gym.ClientFactory.build(ClientFactory.java:40)
	at org.deeplearning4j.gym.ClientFactory.build(ClientFactory.java:58)
	at org.deeplearning4j.rl4j.mdp.gym.GymEnv.<init>(GymEnv.java:46)
	at org.deeplearning4j.examples.rl4j.Cartpole.loadCartpole(Cartpole.java:88)
	at org.deeplearning4j.examples.rl4j.Cartpole.main(Cartpole.java:49)

"maximum connections reached?"
How many this Cartpole example need? 
or How can I increase maximun connect number of gym-http?

**Comment by saudet** [comment]
That's an issue with gym-http-api:
https://github.com/deeplearning4j/gym-java-client#gym-java-client
