### ISSUE TITLE
ND4J:  The Nd4j.where() throws exception when the conditions mask is zeros 

### ISSUE THREAD

**Issue by tzolov** [deeplearning4j/deeplearning4j#6305]
Following test reproduces the problem:

```java
	@Test
	public void whereWithEmptyMask() {
		INDArray inArray = Nd4j.zeros(2, 3);
		inArray.putScalar(0, 0, 10.0f);
		inArray.putScalar(1, 2, 10.0f);

		INDArray mask1 = inArray.match(1, Conditions.greaterThanOrEqual(1));

		Assert.assertTrue(mask1.maxNumber().intValue() == 1); // ! Not Empty Match

		INDArray[] matchIndexes = Nd4j.where(mask1, null, null);

		Assert.assertArrayEquals(new int[] {0, 1}, matchIndexes[0].toIntVector());
		Assert.assertArrayEquals(new int[] {0, 2}, matchIndexes[1].toIntVector());

		INDArray mask2 = inArray.match(1, Conditions.greaterThanOrEqual(11));

		Assert.assertTrue(mask2.maxNumber().intValue() == 0);
                 // PROBLEM !!
		INDArray[] matchIndexes2 = Nd4j.where(mask2, null, null);
	}
```

The Nd4j.where with condition mask of zeros throws: 
```
org.nd4j.linalg.exception.ND4JIllegalStateException: Invalid shape: Requested INDArray shape [0] contains dimension size values < 1 (all dimensions must be 1 or more)

	at org.nd4j.linalg.factory.Nd4j.checkShapeValues(Nd4j.java:4378)
	at org.nd4j.linalg.factory.Nd4j.createUninitialized(Nd4j.java:4522)
	at org.nd4j.linalg.factory.Nd4j.where(Nd4j.java:6034)
	at org.springframework.cloud.stream.app.face.detection.mtcnn.processor.IndexWhereTest.whereWithEmptyMask(IndexWhereTest.java:35)
```

IMO the response for empty/zero condition mask should be an empty INDArray[0] rather then exception.

**Comment by raver119** [comment]
Right. We have empty arrays now, so it should return empty NDArray
