### ISSUE TITLE
libnd4j: split op throws exception for negative axis arg

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6313]
Works fine for axis=0 in first case, and axis=1 for second, which should be equivalent

```
    @Test
    public void testDebugSplit(){
        INDArray in = Nd4j.linspace(1,10,10).reshape(10);
        INDArray axis = Nd4j.trueScalar(-1);

        INDArray out1 = Nd4j.create(new long[]{5});
        INDArray out2 = Nd4j.create(new long[]{5});

        Nd4j.getExecutioner().exec(DynamicCustomOp.builder("split")
                .addInputs(axis, in)
                .addOutputs(out1, out2)
                .addIntegerArguments(2)
                .build());

        INDArray exp1 = in.get(NDArrayIndex.interval(0,5));
        INDArray exp2 = in.get(NDArrayIndex.interval(5,10));
        assertEquals(exp1, out1);
        assertEquals(exp2, out2);
    }

    @Test
    public void testDebugSplit2(){
        INDArray in = Nd4j.linspace(1,24,24).reshape(3,8);
        INDArray axis = Nd4j.trueScalar(-1);

        INDArray out1 = Nd4j.create(new long[]{3,4});
        INDArray out2 = Nd4j.create(new long[]{3,4});

        Nd4j.getExecutioner().exec(DynamicCustomOp.builder("split")
                .addInputs(axis, in)
                .addOutputs(out1, out2)
                .addIntegerArguments(2)
                .build());

        INDArray exp1 = in.get(NDArrayIndex.all(), NDArrayIndex.interval(0,4));
        INDArray exp2 = in.get(NDArrayIndex.all(), NDArrayIndex.interval(4,8));
        assertEquals(exp1, out1);
        assertEquals(exp2, out2);
    }
```

```
Can't assign new value to the array: this shape [5]; other shape: [10]

java.lang.RuntimeException: Lengths of arrays are mismatched
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOpFloat(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1718)
	at org.nd4j.imports.TestDebug.testDebugSplit(TestDebug.java:21)
```

```
Can't assign new value to the array: this shape [3, 4]; other shape: [3, 8]

java.lang.RuntimeException: Lengths of arrays are mismatched
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOpFloat(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1718)
	at org.nd4j.imports.TestDebug.testDebugSplit2(TestDebug.java:41)
```

**Comment by shyrma** [comment]
Fixed, should be merged by raver tomorrow

**Comment by AlexDBlack** [comment]
Confirmed fixed and passing. Thanks!
