### ISSUE TITLE
libnd4j: broadcast_dynamic_shape bugs

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6322]
First issue: rank 1, length 1 are not considered vectors hence fail op validation
```
    @Test
    public void testBroadcastDynamicShape1(){

        //Test case: [2,1] and [4]: expect [2,4]
        INDArray out = Nd4j.create(new long[]{2});
        DynamicCustomOp op = DynamicCustomOp.builder("broadcast_dynamic_shape")
                .addInputs(Nd4j.trueVector(new double[]{2,1}), Nd4j.trueVector(new double[]{4}))
                .addOutputs(out)
                .build();
        Nd4j.getExecutioner().exec(op);
        assertEquals(Nd4j.trueVector(new double[]{2,4}), out);

        //Same thing, reversed input order (expect same output)
        op = DynamicCustomOp.builder("broadcast_dynamic_shape")
                .addInputs(Nd4j.trueVector(new double[]{4}), Nd4j.trueVector(new double[]{2,1}))
                .addOutputs(out)
                .build();
        Nd4j.getExecutioner().exec(op);
        assertEquals(Nd4j.trueVector(new double[]{2,4}), out);
    }
```

```
Error at [C:/DL4J/Git/deeplearning4j/libnd4j/include/ops/declarable/generic/parity_ops/broadcast_dynamic_shape.cpp:36:0]:
broadcast_dynamic_shape: The second argument should be a vector

java.lang.RuntimeException: Op validation failed

	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOpFloat(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1718)
```

Second issue: shape is wrong for both of the following cases:
```
    @Test
    public void testBroadcastDynamicShape2(){

        //Test case: [2,1,4] and [2,2,4]: expect [2,2,4]
        INDArray out = Nd4j.create(new long[]{3});
        DynamicCustomOp op = DynamicCustomOp.builder("broadcast_dynamic_shape")
                .addInputs(Nd4j.trueVector(new double[]{2,1,4}), Nd4j.trueVector(new double[]{2,2,4}))
                .addOutputs(out)
                .build();
        Nd4j.getExecutioner().exec(op);
        assertEquals(Nd4j.trueVector(new double[]{2,2,4}), out);

        //Test case: [1,1,3] and [2,4,1]: expect [2,4,3]
        out = Nd4j.create(new long[]{3});
        op = DynamicCustomOp.builder("broadcast_dynamic_shape")
                .addInputs(Nd4j.trueVector(new double[]{1,1,3}), Nd4j.trueVector(new double[]{2,4,1}))
                .addOutputs(out)
                .build();
        Nd4j.getExecutioner().exec(op);
        assertEquals(Nd4j.trueVector(new double[]{2,4,3}), out);
    }
```

```
java.lang.AssertionError: 
Expected :[    2.0000,    2.0000,    4.0000]
Actual   :[    2.0000,    2.0000,         0]

java.lang.AssertionError: 
Expected :[    2.0000,    4.0000,    3.0000]
Actual   :[    2.0000,         0,         0]
```

**Comment by AlexDBlack** [comment]
The first test case is confirmed as passing.
The second set case is still failing an current master with the same output as before.

**Comment by AlexDBlack** [comment]
Update 2019/01/08: both test cases are now failing. First one returns wrong result, second one gives an exception.

```
    @Test
    public void testBroadcastDynamicShape1(){

        //Test case: [2,1] and [4]: expect [2,4]
        INDArray out = Nd4j.create(DataType.INT, 2);
        DynamicCustomOp op = DynamicCustomOp.builder("broadcast_dynamic_shape")
                .addInputs(Nd4j.createFromArray(new int[]{2,1}), Nd4j.createFromArray(new int[]{4}))
                .addOutputs(out)
                .build();
        Nd4j.getExecutioner().exec(op);
        assertEquals(Nd4j.createFromArray(new int[]{2,4}), out);

        //Same thing, reversed input order (expect same output)
        op = DynamicCustomOp.builder("broadcast_dynamic_shape")
                .addInputs(Nd4j.createFromArray(new int[]{4}), Nd4j.createFromArray(new int[]{2,1}))
                .addOutputs(out)
                .build();
        Nd4j.getExecutioner().exec(op);
        assertEquals(Nd4j.createFromArray(new int[]{2,4}), out);
    }

    @Test
    public void testBroadcastDynamicShape2(){

        //Test case: [2,1,4] and [2,2,4]: expect [2,2,4]
        INDArray out = Nd4j.create(DataType.INT, 3);
        DynamicCustomOp op = DynamicCustomOp.builder("broadcast_dynamic_shape")
                .addInputs(Nd4j.createFromArray(new int[]{2,1,4}), Nd4j.createFromArray(new int[]{2,2,4}))
                .addOutputs(out)
                .build();
        Nd4j.getExecutioner().exec(op);
        assertEquals(Nd4j.createFromArray(new int[]{2,2,4}), out);

        //Test case: [1,1,3] and [2,4,1]: expect [2,4,3]
        out = Nd4j.create(DataType.DOUBLE, 3);
        op = DynamicCustomOp.builder("broadcast_dynamic_shape")
                .addInputs(Nd4j.createFromArray(new int[]{1,1,3}), Nd4j.createFromArray(new int[]{2,4,1}))
                .addOutputs(out)
                .build();
        Nd4j.getExecutioner().exec(op);
        assertEquals(Nd4j.createFromArray(new int[]{2,4,3}), out);
    }
```

```
java.lang.AssertionError: 
Expected :[         2,         4]
Actual   :[         2,         1]
```

```
broadcast_dynamic_shape: Input shapes should be compatible, but 0.000000 and 2.000000 were given.BDS validation failed!
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute op broadcast_dynamic_shape. Attempted to execute with 2 inputs, 1 outputs, 0 targs and 0 iargs. Inputs: [(INT,[3],c), (INT,[3],c)]. Outputs: [(INT,[3],c)] - Please see above message (printed out from c++) for a possible cause of error.

org.nd4j.linalg.exception.ND4JIllegalStateException: Failed to execute op [broadcast_dynamic_shape] with error code [ND4J_STATUS_VALIDATION]
```

**Comment by shugeo** [comment]
This operation requires int arguments and output. But test used double as output.

**Comment by AlexDBlack** [comment]
The tests in the original issue were pre-datatypes changes.
One of the tests here should have been DataType.INT instead of DOUBLE: https://github.com/deeplearning4j/deeplearning4j/issues/6322#issuecomment-452224596

At any rate - both are more recent tests are now passing, thanks. I'll close this.
