### ISSUE TITLE
SameDiff: Import issue for strided slice op?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6346]
Not sure exactly what's up here yet (opening this so I don't forget to look into it later), but boolean_mask tests are failing with the following:

```
java.lang.RuntimeException: Error populating inputs and outputs for function "boolean_mask/strided_slice_1" of type org.nd4j.linalg.api.ops.impl.shape.StridedSlice

	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:10502)
	at org.nd4j.autodiff.samediff.SameDiff.execAndEndResults(SameDiff.java:9156)
	at org.nd4j.imports.TFGraphs.TFGraphTestAllHelper.getGraphAfterExec(TFGraphTestAllHelper.java:218)
	at org.nd4j.imports.TFGraphs.TFGraphTestAllHelper.checkOnlyOutput(TFGraphTestAllHelper.java:131)
	at org.nd4j.imports.TFGraphs.TFGraphTestAllHelper.checkOnlyOutput(TFGraphTestAllHelper.java:125)
	at org.nd4j.imports.TFGraphs.TFGraphTestAllSameDiff.testOutputOnly(TFGraphTestAllSameDiff.java:177)
...
Caused by: org.nd4j.linalg.exception.ND4JIllegalStateException: Unable to allocate new array. No shape found for variable boolean_mask/strided_slice_1
	at org.nd4j.autodiff.samediff.SDVariable.storeAndAllocateNewArray(SDVariable.java:177)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.attemptToGetOrCreateArrForVar(DynamicCustomOp.java:283)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:259)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:179)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.populateInputsAndOutputsFromSameDiff(DynamicCustomOp.java:626)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:10499)
```

**Comment by AlexDBlack** [comment]
No longer applicable after recent execution changes.
