### ISSUE TITLE
DL4J: CuDNN NPE on style transfer

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6358]
https://gist.github.com/tvanh/25f4f8586d9da3f2caaa63e54c1f43c8

```
09:26:24.498 [main] WARN org.deeplearning4j.nn.layers.convolution.ConvolutionLayer - CuDNN execution failed - falling back on built-in implementation
java.lang.NullPointerException: null
at org.deeplearning4j.nn.workspace.LayerWorkspaceMgr.getHelperWorkspace(LayerWorkspaceMgr.java:99)
at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper.preOutput(CudnnConvolutionHelper.java:460)
at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:342)
at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput4d(ConvolutionLayer.java:246)
at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.backpropGradient(ConvolutionLayer.java:146)
at anhtv.ai.dl.NeuralStyleTransfer.backPropagate(NeuralStyleTransfer.java:265)
at anhtv.ai.dl.NeuralStyleTransfer.backPropagateStyles(NeuralStyleTransfer.java:143)
at anhtv.ai.dl.NeuralStyleTransfer.transferStyle(NeuralStyleTransfer.java:118)
at anhtv.ai.dl.NeuralStyleTransfer.main(NeuralStyleTransfer.java:99)
```

**Comment by AlexDBlack** [comment]
@tvanh Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/6370

**Comment by tvanh** [comment]
Tyvm
