### ISSUE TITLE
problem with linear regression

### ISSUE THREAD

**Issue by jakonn** [deeplearning4j/deeplearning4j#639]
I get such exception durring training phase (whole log )
```
o.d.e.d.CustomDbn - Load data....
o.d.e.d.CustomDbn - Split data....
o.d.e.d.CustomDbn - Build model....
o.d.e.d.CustomDbn - Train model....
o.d.n.m.MultiLayerNetwork - Training on layer 1 with 8 examples
o.d.o.s.BaseOptimizer - Objective function automatically set to minimize. Set stepFunction in neural net configuration to change default settings.
o.d.o.s.BaseOptimizer - Objective function automatically set to minimize. Set stepFunction in neural net configuration to change default settings.
sie 28, 2015 1:52:14 PM com.github.fommil.netlib.BLAS <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
sie 28, 2015 1:52:15 PM com.github.fommil.jni.JniLoader liberalLoad
INFO: successfully loaded C:\Users\jakonn\AppData\Local\Temp\jniloader1547981043749067293netlib-native_ref-win-x86_64.dll
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 6.934321403503418
o.d.o.l.ScoreIterationListener - Score at iteration 1 is 5.793976306915283
o.d.o.l.ScoreIterationListener - Score at iteration 2 is 11.756606101989746
o.d.o.l.ScoreIterationListener - Score at iteration 3 is 9.595345497131348
o.d.n.m.MultiLayerNetwork - Training on layer 2 with 8 examples
o.d.o.s.BaseOptimizer - Objective function automatically set to minimize. Set stepFunction in neural net configuration to change default settings.
o.d.o.s.BaseOptimizer - Objective function automatically set to minimize. Set stepFunction in neural net configuration to change default settings.
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 4.514941692352295
o.d.o.l.ScoreIterationListener - Score at iteration 1 is 4.012391090393066
o.d.o.l.ScoreIterationListener - Score at iteration 2 is 2.7688183784484863
o.d.o.l.ScoreIterationListener - Score at iteration 3 is 3.825308322906494
o.d.n.m.MultiLayerNetwork - Training on layer 3 with 8 examples
o.d.o.s.BaseOptimizer - Objective function automatically set to minimize. Set stepFunction in neural net configuration to change default settings.
o.d.o.s.BaseOptimizer - Objective function automatically set to minimize. Set stepFunction in neural net configuration to change default settings.
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 3.1656055450439453
o.d.o.l.ScoreIterationListener - Score at iteration 1 is 3.4249801635742188
o.d.o.l.ScoreIterationListener - Score at iteration 2 is 4.135288238525391
o.d.o.l.ScoreIterationListener - Score at iteration 3 is 5.206275463104248
o.d.n.m.MultiLayerNetwork - Finetune phase
o.d.o.s.BaseOptimizer - Objective function automatically set to minimize. Set stepFunction in neural net configuration to change default settings.
Exception in thread "main" java.lang.IllegalArgumentException: Unable to get linear index >= 8
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3182)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.apply(DefaultOpExecutioner.java:549)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:59)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2684)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2664)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.sub(BaseNDArray.java:2443)
	at org.nd4j.linalg.lossfunctions.LossCalculation.score(LossCalculation.java:53)
	at org.deeplearning4j.nn.layers.OutputLayer.setScoreWithZ(OutputLayer.java:109)
	at org.deeplearning4j.nn.layers.OutputLayer.computeGradientAndScore(OutputLayer.java:93)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:117)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:135)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.layers.OutputLayer.fit(OutputLayer.java:328)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.finetune(MultiLayerNetwork.java:1169)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1221)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1261)
	at org.deeplearning4j.examples.deepbelief.CustomDbn.main(CustomDbn.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

I used Iris.txt resource from dl4j examples and my custom DBN. 

U can find it here/: https://gist.github.com/jakonn/0ddca24a64c4afabbf2b . Can u tell me what I am doing wrong? I am trying to set linear regression instead of classification of that records :) ...

**Comment by agibsonccc** [comment]
So we are able to load data for regression: it looks like it was the way you setup your iterator.
