### ISSUE TITLE
InvalidKerasConfigurationException for Time Distributed Dense

### ISSUE THREAD

**Issue by Tshimanga** [deeplearning4j/deeplearning4j#6390]
I have a trained Keras Model defined as 2xbiLSTM + TimeDistributed Dense. Trying to import the network into DL4J resulted in the following error (+ stack trace):

```
org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException: Found weights for layer not in model (named time_distributed_1). For more information, see http://deeplearning4j.org/model-import-keras.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:258)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:141)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:61)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:320)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:195)
```

Did I do something wrong or does this mean I can't import Keras models with time distributed layers?

**Comment by maxpumperla** [comment]
thanks, time distributed layers are on our list, will be added soon. I'm closing this as duplicate, we already have an issue for that.

**Comment by maxpumperla** [comment]
I'll add deconv3d and GRU support before that and have a ton of Python stuff on my hands as well, so don't expect this before October.

**Comment by Tshimanga** [comment]
Understood. Thanks for the information and I appreciate the quick responses! Happy developing! 👋
