### ISSUE TITLE
libnd4j: bug in conv2d op shape calculation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6440]
I'm pretty sure the input is correct here, but I'm getting failed validaiton...
Looking at the error, it seems like it's incorrectly taking inChannels=5 from position 3 of input (like NHWC), instead of from position 1 of input for NCHW case?

```
    @Test
    public void testShapeConv2d(){
        INDArray inNCHW = Nd4j.create(1, 2, 5, 5);
        INDArray inW = Nd4j.create(2,2,2,3);        //kH, kW, iC, oC
        DynamicCustomOp op = DynamicCustomOp.builder("conv2d")
                .addInputs(inNCHW, inW)
                .addIntegerArguments(
                        2,2,  //Kernel
                        2,2,  //Stride
                        0,0,  //Padding
                        1,1,  //Dilation
                        1,      //Same
                        1       //1=NCHW
                ).build();
        List<long[]> outShape = Nd4j.getExecutioner().calculateOutputShape(op);
        System.out.println(Arrays.toString(outShape.get(0)));

        //same mode: output dimensions are ceil(inputSize / stride) = ceil(5/2) = 3
        long[] shapeExp = new long[]{1, 3, 3, 3};       //nchw
        assertArrayEquals(shapeExp, outShape.get(0));
    }
```

```
Error at [C:/DL4J/Git/deeplearning4j/libnd4j/include/ops/declarable/generic/convo/conv2d.cpp:129:0]:
CUSTOM CONV2D OP: wrong shape of weights array, expected is [2, 2, 5, 3], but got [2, 2, 2, 3] instead !

java.lang.RuntimeException: Op validation failed
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.calculateOutputShapesFloat(Native Method)
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.calculateOutputShapesFloat(Nd4jCpu.java:1606)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.calculateOutputShape(NativeOpExecutioner.java:1821)
```

**Comment by AlexDBlack** [comment]
Same thing for Conv1d:

```
    @Test
    public void testShapeConv1d(){
        INDArray inNCW = Nd4j.create(1, 2, 5);
        INDArray inW = Nd4j.create(2,2,3);        //kW, iC, oC
        DynamicCustomOp op = DynamicCustomOp.builder("conv1d")
                .addInputs(inNCW, inW)
                .addIntegerArguments(
                        2,  //Kernel
                        2,  //Stride
                        0,  //Padding
                        1,      //1=Same
                        1       //1=NCW
                ).build();
        List<long[]> outShape = Nd4j.getExecutioner().calculateOutputShape(op);
        System.out.println(Arrays.toString(outShape.get(0)));

        //same mode: output dimensions are ceil(inputSize / stride) = ceil(5/2) = 3
        long[] shapeExp = new long[]{1, 3, 3};       //ncw
        assertArrayEquals(shapeExp, outShape.get(0));
    }
```

```
Error at [C:/DL4J/Git/deeplearning4j/libnd4j/include/ops/declarable/generic/convo/conv1d.cpp:122:0]:
CUSTOM CONV1D OP: wrong shape of weights array, expected is [2, 5, 3], but got [2, 2, 3] instead !
java.lang.RuntimeException: Op validation failed
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.calculateOutputShapesFloat(Native Method)
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.calculateOutputShapesFloat(Nd4jCpu.java:1606)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.calculateOutputShape(NativeOpExecutioner.java:1821)
```

**Comment by shyrma** [comment]
Hi, Alex

This is because we should use zero for NCHW, not unity

**Comment by AlexDBlack** [comment]
> This is because we should use zero for NCHW, not unity

The code/comments are ambiguous on this point: 
Comments say ```1-NCHW,  0-NHWC``` (which can only reasonably refer to the integer iarg not the boolean isNCHW) yet ```bool isNCHW = !INT_ARG(9)``` which implies iarg(9) has meaning 0=nchw, 1=nhwc as you say.

https://github.com/deeplearning4j/deeplearning4j/blob/0a800767e8a8e567fff9a296c2d8389aa2fcdf6f/libnd4j/include/ops/declarable/generic/convo/conv2d.cpp#L52

Conv1d is also ambiguous here: given the user-provided arg is negated, does the comment refer to the iarg value, or the post-negated isNCW value?
https://github.com/deeplearning4j/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/convo/conv1d.cpp#L44

Can we get these comments cleaned up? Wrong/ambiguous comments are worse than no comments.

**Comment by shyrma** [comment]
This wrong comment/notation remains there due to some historical reason which goes back to early implementation of this op by raver :-)
Ok, I'll correct that

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/6449
