### ISSUE TITLE
Problem with data for linear regression

### ISSUE THREAD

**Issue by jakonn** [deeplearning4j/deeplearning4j#645]
I am trying to load data for regression. I need then only 1 label.
I load my data(sample):
```
2053.54,2112.09,2049.22,2070.56,0.07
2139.45,2139.45,2014.69,2056.38,-0.57
2181.55,2196.2,2167.62,2179.73,-0.10
```
and use modified a bit code from CsvExample from dl4j- examples

```java
        RecordReader recordReader = new CSVRecordReader(0, ",");
        recordReader.initialize(new FileSplit(new ClassPathResource("noweDaneCsv1.txt").getFile()));
        //reader,label index,number of possible labels
        DataSetIterator iterator = new RecordReaderDataSetIterator(recordReader, 0, 1);
        //get the dataset using the record reader. The datasetiterator handles vectorization
        DataSet next = iterator.next();
```

I am getting such error.
```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2053
	at org.nd4j.linalg.util.FeatureUtil.toOutcomeVector(FeatureUtil.java:38)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.getDataSet(RecordReaderDataSetIterator.java:194)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:134)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:277)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:45)
	at org.deeplearning4j.examples.deepbelief.CustomDbn.main(CustomDbn.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by agibsonccc** [comment]
This was due to the configuration of the iterator. Closing.
