### ISSUE TITLE
Implement Backwards Compatible FileSplit

### ISSUE THREAD

**Issue by Barend13** [deeplearning4j/deeplearning4j#6457]
I am trying to develop an application that can train using images on an android phone, however the device has API level 22. The FileSplit implementation uses the .toPath() method and Path Object that was only introduced in Android API 26, so when creating a FileSplit the following error occurs. (At least I believe that to be the cause).
```
java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-libart.jar)
        at org.datavec.api.split.FileSplit.initialize(FileSplit.java:108)
        at org.datavec.api.split.FileSplit.<init>(FileSplit.java:58)
        at org.datavec.api.split.FileSplit.<init>(FileSplit.java:74)
```

Would it possible to create an implementation of FileSplit that is backwards compatible with versions of Android < 26? If not, how would I go about creating an implementation that does support this?

Thanks

**Comment by AlexDBlack** [comment]
In principle, sure - I think the only place this method is used is for recursively listing of files here:
https://github.com/deeplearning4j/deeplearning4j/blob/master/datavec/datavec-api/src/main/java/org/datavec/api/split/FileSplit.java#L108
https://github.com/deeplearning4j/deeplearning4j/blob/master/datavec/datavec-api/src/main/java/org/datavec/api/split/FileSplit.java#L229-L256

Changing this should be relatively straightforward - feel free to send us a pull request with a fix - or I'll try to take a look later in the week.

**Comment by Barend13** [comment]
Thanks Alex,

I'm not sure I'd be able to fix this myself, so I would really appreciate it if you could take a look please.
