### ISSUE TITLE
ND4J: INDArray serialization bug?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6482]
Key point here is that the model (in older format - pre 1.0.0-beta I think) is loaded, saved, and loaded again. When that occurs, it fails on the second loading.

```
        String s = "C:\\Users\\Alex\\.deeplearning4j\\models\\vgg16\\vgg16_dl4j_inference.zip";
        ComputationGraph cg = ModelSerializer.restoreComputationGraph(new File(s));
        File out = new File("test.zip");
        ModelSerializer.writeModel(cg, out, true);
        cg = ModelSerializer.restoreComputationGraph(out);     //Exception here
```

```
java.lang.RuntimeException: java.io.UTFDataFormatException: malformed input around byte 13

	at org.nd4j.linalg.api.buffer.BaseDataBuffer.read(BaseDataBuffer.java:1490)
	at org.nd4j.linalg.compression.CompressedDataBuffer.readUnknown(CompressedDataBuffer.java:97)
	at org.nd4j.linalg.factory.Nd4j.read(Nd4j.java:2435)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:579)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:492)
	at org.deeplearning4j.Debug.test(Debug.java:43)
...
Caused by: java.io.UTFDataFormatException: malformed input around byte 13
	at java.io.DataInputStream.readUTF(DataInputStream.java:648)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.read(BaseDataBuffer.java:1431)
```

**Comment by raver119** [comment]
Fixed
