### ISSUE TITLE
Keras import Permute layer error

### ISSUE THREAD

**Issue by ilyaivensky** [deeplearning4j/deeplearning4j#6489]
I got the following error in the import:
> Error deserializing JSON ComputationGraphConfiguration. Saved model JSON is not a valid ComputationGraphConfiguration
java.lang.RuntimeException: Error deserializing JSON ComputationGraphConfiguration. Saved model JSON is not a valid ComputationGraphConfiguration

when added this code in Keras:
```
    x = Permute((2, 1))(x)
    x = Flatten()(x)
    x = RepeatVector(64)(x)
    x = Permute((2, 1))(x)
``` 
That effectively blocks the import of Attention mechanism

_Originally posted by @ilyaivensky in https://github.com/deeplearning4j/deeplearning4j/issues/6488#issuecomment-424408666_

**Comment by ilyaivensky** [comment]
More details:

> Caused by: java.lang.RuntimeException: org.nd4j.shade.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class org.deeplearning4j.nn.modelimport.keras.preprocessors.PermutePreprocessor]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: java.io.StringReader@4587675c; line: 937, column: 95] (through reference chain: org.deeplearning4j.nn.conf.ComputationGraphConfiguration["vertices"]->java.util.LinkedHashMap["permute_1"]->org.deeplearning4j.nn.conf.graph.PreprocessorVertex["preProcessor"])
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.fromJson(ComputationGraphConfiguration.java:174)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:622)

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/6504
Thanks for reporting
