### ISSUE TITLE
squeezenet bug

### ISSUE THREAD

**Issue by fradino** [deeplearning4j/deeplearning4j#6500]
Exception in thread "main" java.lang.IllegalStateException: Invalid configuration: Vertex "fire2_relu_exp1x1" has input "fire2_exp1x1" that does not exist
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.validate(ComputationGraphConfiguration.java:314)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.build(ComputationGraphConfiguration.java:1033)
	at org.deeplearning4j.zoo.model.SqueezeNet.init(SqueezeNet.java:78)
	at org.deeplearning4j.zoo.model.SqueezeNet.init(SqueezeNet.java:36)

**Comment by Charele** [comment]
I check the code, some typos here:
1>.addLayer(prefix+"exp1x1", new ConvolutionLayer.Builder(1, 1).nOut(expand)
                        .cudnnAlgoMode(cudnnAlgoMode).build(), prefix+"_relu_sq1x1")
the "exp1x1" shoud be "_exp1x1"

2> .addLayer("conv10", new ConvolutionLayer.Builder(1,1).nOut(numClasses)
                        .cudnnAlgoMode(cudnnAlgoMode).build(), "input")
I think the "conv10" should connect to "drop9"?

3> 
.addLayer(prefix+"exp1x1", new ConvolutionLayer.Builder(1, 1).nOut(expand)
                        .cudnnAlgoMode(cudnnAlgoMode).build(), prefix+"_relu_sq1x1")
                .addLayer(prefix+"_relu_exp1x1", new ActivationLayer(Activation.RELU), prefix+"_exp1x1")

                .addLayer(prefix+"_exp3x3", new ConvolutionLayer.Builder(3,3).nOut(expand)
                        .cudnnAlgoMode(cudnnAlgoMode).build(), prefix+"_relu_sq1x1")
                .addLayer(prefix+"_relu_exp3x3", new ActivationLayer(Activation.RELU), prefix+"_exp3x3")

                .addVertex(prefix, new MergeVertex(), prefix+"_relu_exp1x1", prefix+"_relu_exp3x3");
The "..._relu_exp1x1" and "..._relu_exp3x3" have different shape, they cann't be mere,
I think above two new ConvolutionLayer.Builder() should have same kernelSize,,,my option

**Comment by AlexDBlack** [comment]
As per here: https://github.com/deeplearning4j/deeplearning4j/issues/6501#issuecomment-425761187

Again, try on 1.0.0-beta2.
And if it still occurs, please give us some code to reproduce this. We can't do much without knowing exactly what you are doing.

**Comment by fradino** [comment]
now，I use 1.0.0-beta2
the code I write is just
“
ZooModel zooModel = SqueezeNet.builder().build();
ComputationGraph sqnet = zooModel.init();
log.info(sqnet.summary());
”
still has this problem

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/6504

Once it's merged, you can get the fix using snapshots: https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots

Or, in this case, you can probably just copy the updated model code to a local project (as the changes are isolated to the zoo model class) - https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots
