### ISSUE TITLE
XceptionNet bug

### ISSUE THREAD

**Issue by fradino** [deeplearning4j/deeplearning4j#6501]
Exception in thread "main" java.lang.IllegalStateException: Invalid configuration: disconnected vertices found - [block1_conv2_bn, block12_sepconv3_bn, block14_sepconv1_act]. Disconnected vertices are those that do not connect to either another vertex, and are also not a network output. To disable this error (i.e., allow network configurations with disconnected vertices) use GraphBuilder.allowDisconnected(true)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.validate(ComputationGraphConfiguration.java:346)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.build(ComputationGraphConfiguration.java:1033)
	at org.deeplearning4j.zoo.model.Xception.init(Xception.java:78)
	at org.deeplearning4j.zoo.model.Xception.init(Xception.java:36)

**Comment by maxpumperla** [comment]
disconnected vertices have been allowed for keras import a while ago (which seems to be the underlying issue here). can you please share which DL4J version you're using?

**Comment by fradino** [comment]
<dl4j.version>1.0.0-beta</dl4j.version>
Btw, I'm not using keras import, just XceptionNet in org.deeplearning4j.zoo.model

**Comment by AlexDBlack** [comment]
We do have tests for instantiating xception here:
https://github.com/deeplearning4j/deeplearning4j/blob/451dd76b50355358dc176f2b704e98c43423c5b8/deeplearning4j/deeplearning4j-zoo/src/test/java/org/deeplearning4j/zoo/TestInstantiation.java#L191-L196

Maybe try on the latest version - 1.0.0-beta2. If it still occurs there, can you share the exact code you are using to produce this issue?

**Comment by fradino** [comment]
I use 1.0.0-beta2
and the code i write is
"
ZooModel zooModel = Xception.builder().build();
ComputationGraph sqnet = zooModel.init();
log.info(sqnet.summary());
"
still has this problem

**Comment by AlexDBlack** [comment]
OK, thanks for the code. It looks like this issue is limited to the non-pretrained models.
Pretrained models (via initPretrained()) as per what I linked in my previous post, are OK.

If you want the pretrained model, use initPretrained(). Otherwise (for non-pretrained) it looks like the config needs to be fixed.

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/6504

Once it's merged, you can get the fix using snapshots: https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots

Or, in this case, you can probably just copy the updated model code to a local project (as the changes are isolated to the zoo model class) - https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots
