### ISSUE TITLE
setLearningRate(double LR) throws Null Pointer Exception

### ISSUE THREAD

**Issue by andlyu** [deeplearning4j/deeplearning4j#6520]
I'm using the setLearningRate() for an LSTM graph, and I get the following errors:
Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.nn.updater.BaseMultiLayerUpdater.setStateViewArray(BaseMultiLayerUpdater.java:192)
	at org.deeplearning4j.util.NetworkUtils.refreshUpdater(NetworkUtils.java:255)
	at org.deeplearning4j.util.NetworkUtils.setLearningRate(NetworkUtils.java:196)
	at org.deeplearning4j.util.NetworkUtils.setLearningRate(NetworkUtils.java:176)
	at org.deeplearning4j.nn.graph.ComputationGraph.setLearningRate(ComputationGraph.java:4059)
	at org.deeplearning4j.examples.recurrent.character.CompGraphLSTMExample2.main(CompGraphLSTMExample2.java:303)

**Comment by AlexDBlack** [comment]
Can you provide some more information here?
Is the configuration identical to the LSTM character example, or have you made changes?
Is this before or after training?

Better yet, some code I can run would help a lot here.

**Comment by andlyu** [comment]
I attached a zip with the files that are in recurrent. Here is the directory
deep4j\dl4j-examples\dl4j-examples\src\main\java\org\deeplearning4j\examples\recurrent\character
In there I included the model and the text that I train it on.
Instead of using characters, I am iterating through words, but that should
not cause an issue.
I'll try changing the learning rate on the sample character Graph, and I
will let you know if it works.
Thanks for this project.
 character.zip
<https://drive.google.com/file/d/1BIjiWM8C4eOg08_5xsp33jk9QebX2d7E/view?usp=drive_web>
