### ISSUE TITLE
IllegalArgumentException while running DeepAutoEncoderExample

### ISSUE THREAD

**Issue by sanity** [deeplearning4j/deeplearning4j#659]
I'm trying to get [DeepAutoEncoderExample](https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/src/main/java/org/deeplearning4j/examples/deepbelief/DeepAutoEncoderExample.java) to work, however it terminates with the following exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unable to get linear index >= 2878514
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3182)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.apply(DefaultOpExecutioner.java:549)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:59)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2684)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2664)
	at org.deeplearning4j.optimize.stepfunctions.NegativeGradientStepFunction.step(NegativeGradientStepFunction.java:37)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:59)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1232)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1261)
	at AutoEncTest.main(AutoEncTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

[Here](https://gist.github.com/sanity/c708ca8e8d2468f6af7d) is the complete output.

**Comment by agibsonccc** [comment]
@sanity Please do a git pull and of note here: https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/src/main/java/org/deeplearning4j/examples/deepbelief/DeepAutoEncoderExample.java#L67-67
