### ISSUE TITLE
Integer overflow on large number of parameters

### ISSUE THREAD

**Issue by DanielWieczorek** [deeplearning4j/deeplearning4j#6611]
While experimenting with my NN configuration, I stumbled over a NullPointerException during initialization of the MultiLayerNetwork:

```
java.lang.NullPointerException: null
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:621) ~[deeplearning4j-nn-1.0.0-beta2.jar:?]
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:530) ~[deeplearning4j-nn-1.0.0-beta2.jar:?]
	at de.wieczorek.rss.advisor.business.TradingNeuralNetwork.buildNetwork(TradingNeuralNetwork.java:123) ~[classes/:?]
	at de.wieczorek.nn.AbstractNeuralNetwork.train(AbstractNeuralNetwork.java:31) ~[classes/:?]
	at de.wieczorek.rss.advisor.business.TradingNeuralNetwork$Proxy$_$$_WeldClientProxy.train(Unknown Source) ~[classes/:?]
	at de.wieczorek.rss.advisor.business.TrainingTimer.run(TrainingTimer.java:47) [classes/:?]
	at de.wieczorek.rss.advisor.business.TrainingTimer$Proxy$_$$_WeldClientProxy.run(Unknown Source) [classes/:?]
	at de.wieczorek.rss.core.timer.RecurrentTaskRunner.run(RecurrentTaskRunner.java:42) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:299) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

Apparently the number of parameters was too large. This code segment looks a bit fishy:
```            
            int paramLength = 0;
            val nParamsPerLayer = new long[nLayers];
            for (int i = 0; i < nLayers; i++) {
                NeuralNetConfiguration conf = layerWiseConfigurations.getConf(i);
                nParamsPerLayer[i] = conf.getLayer().initializer().numParams(conf);
                paramLength += nParamsPerLayer[i];
            }
```

The parameters are collected in a list of longs and accumulated in an int. Also the subsequent handling does not regard values < 0 for _paramLength_. This causes that _flattenedParams_ is never initialized since it is assumed that there are no parameters. 

No matter if my config makes sense, I would expect an Exception telling me to rethink my network design.

**Comment by AlexDBlack** [comment]
Yes, it should either work or should provide a useful exception.
ND4J supports long indexing, so there's no technical reason why we can't have nets with more than Integer.MAX_VALUE (~2.1 billion) parameters. Whether that makes sense (should be allowed) or is usually the sign of an error (should be disallowed) is another question.
