### ISSUE TITLE
Unexpected NullPointerException while trying to use RegressionScoreCalculator to do Early Stopping

### ISSUE THREAD

**Issue by tvicky4j247** [deeplearning4j/deeplearning4j#6635]
Hi, I ran into an unexpected `NullPointerException` while trying to use the `RegressionScoreCalculator` as part of the input into an `EarlyStoppingConfiguration`.

Below is some code to reproduce the error. I've also attached two files containing some test and train data for the regression. I had to upload them as .txt files since the .csv extension isn't allowed.

dl4j-version: 1.0.0-beta2

```
RecordReader recordReader = new CSVRecordReader();
recordReader.initialize(new FileSplit(new ClassPathResource("data-train.csv").getFile()));
RecordReader recordReaderTest = new CSVRecordReader();
recordReader.initialize(new FileSplit(new ClassPathResource("data-test.csv").getFile()));

final int numInputs = 4;
int numHidden1 = 5;
int numHidden2 = 100;
int outputNum = 1;
long seed = 3055;
double learningRate = 0.1;

MultiLayerConfiguration configuration = new NeuralNetConfiguration.Builder()
        .seed(seed)
        .weightInit(WeightInit.XAVIER)
        .miniBatch(true)
        .updater(new Sgd(learningRate))
        .list()
        .layer(0, new DenseLayer.Builder()
                .nIn(numInputs)
                .nOut(numHidden1)
                .activation(Activation.RELU)
                .dropOut(0.7)
                .build())
        .layer(1, new DenseLayer.Builder()
                .nIn(numHidden1)
                .nOut(numHidden2)
                .activation(Activation.RELU)
                .dropOut(0.7)
                .build())
        .layer(2, new OutputLayer.Builder(LossFunctions.LossFunction.MSE)
                .nIn(numHidden2)
                .nOut(outputNum)
                .activation(Activation.IDENTITY)
                .build())
        .backprop(true).pretrain(false)
        .build();

int labelIndex = 4;
int batchSizeTest = 200;
int batchSizeTrain = 1077;

DataSetIterator trainData = new RecordReaderDataSetIterator.Builder(recordReader, batchSizeTrain)
        .regression(labelIndex)
        .build();

DataSetIterator testData = new RecordReaderDataSetIterator.Builder(recordReaderTest, batchSizeTest)
        .regression(labelIndex)
        .build();

DataNormalization normalizer = new NormalizerStandardize();
normalizer.fitLabel(true);
normalizer.fit(trainData);
trainData.setPreProcessor(normalizer);
testData.setPreProcessor(normalizer);

EarlyStoppingConfiguration esConf = new EarlyStoppingConfiguration.Builder()
        .epochTerminationConditions(new MaxEpochsTerminationCondition(30))
        .iterationTerminationConditions(new MaxTimeIterationTerminationCondition(20, TimeUnit.MINUTES))
        .scoreCalculator(new RegressionScoreCalculator(RegressionEvaluation.Metric.MSE, testData))
        .evaluateEveryNEpochs(1)
        .modelSaver(new InMemoryModelSaver())
        .build();

EarlyStoppingTrainer trainer = new EarlyStoppingTrainer(esConf,configuration,trainData);

//Conduct early stopping training:
EarlyStoppingResult result = trainer.fit();
```
[data-test.txt](https://github.com/deeplearning4j/deeplearning4j/files/2515045/data-test.txt)
[data-train.txt](https://github.com/deeplearning4j/deeplearning4j/files/2515046/data-train.txt)

**Comment by treo** [comment]
Can you please also add the full stacktrace?

**Comment by tvicky4j247** [comment]
Sure. Right here.

```
[main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 4
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [8]; Memory: [7.1GB];
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [MKL]
[main] INFO org.deeplearning4j.nn.multilayer.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
[main] INFO org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer - Starting early stopping training
[main] INFO org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer - Completed training epoch 0
Exception in thread "main" java.lang.NullPointerException
    at org.datavec.api.records.reader.impl.LineRecordReader.next(LineRecordReader.java:68)
    at org.datavec.api.records.reader.impl.csv.CSVRecordReader.readStringLine(CSVRecordReader.java:190)
    at org.datavec.api.records.reader.impl.csv.CSVRecordReader.next(CSVRecordReader.java:171)
    at org.datavec.api.records.reader.impl.csv.CSVRecordReader.nextRecord(CSVRecordReader.java:196)
    at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.initializeUnderlying(RecordReaderDataSetIterator.java:218)
    at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.resetSupported(RecordReaderDataSetIterator.java:400)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doEvaluationHelper(MultiLayerNetwork.java:3200)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doEvaluation(MultiLayerNetwork.java:3192)
    at org.deeplearning4j.earlystopping.scorecalc.base.BaseIEvaluationScoreCalculator.calculateScore(BaseIEvaluationScoreCalculator.java:55)
    at org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer.fit(BaseEarlyStoppingTrainer.java:202)
    at classifier.EarlyStoppingModel.main(EarlyStoppingModel.java:123)
```

**Comment by AlexDBlack** [comment]
More useful exceptions added here: https://github.com/deeplearning4j/deeplearning4j/pull/6648
It will be merged soon.
Thanks for reporting.

**Comment by tvicky4j247** [comment]
Oops. A pretty obvious mistake there. Thanks for the help.
