### ISSUE TITLE
ArrayIndexOutOfBoundsException in MLPBackpropIrisExample

### ISSUE THREAD

**Issue by vallettea** [deeplearning4j/deeplearning4j#667]
I'm trying to run the exemple `MLPBackpropIrisExample.java` but i get the following error:

```
Load data....
Build model....
Train model....
[WARN] [BaseOptimizer] Objective function automatically set to minimize. Set stepFunction in neural net configuration to change default settings.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 12
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.put(BaseDataBuffer.java:617)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.exec(DefaultOpExecutioner.java:91)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.execAndReturn(DefaultOpExecutioner.java:283)
	at org.nd4j.linalg.ops.transforms.Transforms.exec(Transforms.java:698)
	at org.nd4j.linalg.ops.transforms.Transforms.abs(Transforms.java:558)
	at org.nd4j.linalg.ops.transforms.Transforms.abs(Transforms.java:351)
	at org.deeplearning4j.nn.layers.BaseLayer.calcL1(BaseLayer.java:363)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.calcL1(MultiLayerNetwork.java:1762)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1439)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:117)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:135)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1233)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1262)
	at org.template.classification.Algorithm.train(Algorithm.scala:87)
	at org.template.classification.Algorithm.train(Algorithm.scala:35)
	at io.prediction.controller.P2LAlgorithm.trainBase(Algorithm.scala:204)
	at io.prediction.controller.Engine$$anonfun$18.apply(Engine.scala:566)
	at io.prediction.controller.Engine$$anonfun$18.apply(Engine.scala:566)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at io.prediction.controller.Engine$.train(Engine.scala:566)
	at io.prediction.controller.Engine.train(Engine.scala:147)
	at io.prediction.workflow.CoreWorkflow$.runTrain(CoreWorkflow.scala:61)
	at io.prediction.workflow.CreateWorkflow$.main(CreateWorkflow.scala:258)
	at io.prediction.workflow.CreateWorkflow.main(CreateWorkflow.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:358)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

with these dependencies:

```
  "org.nd4j" % "nd4j-jblas" % "0.4-rc1.1",
  "org.deeplearning4j" % "deeplearning4j-core" % "0.4-rc1")
```

**Comment by agibsonccc** [comment]
Try with 1.2 (look at the examples for the version) thanks!
