### ISSUE TITLE
running keras model with custom layers

### ISSUE THREAD

**Issue by benman1** [deeplearning4j/deeplearning4j#6755]
I am trying to run a keras 2.0 model (dl4j 1.0.0-beta3). It's using building blocks from the recurrentshop library, particularly [RecurrentSequential](https://github.com/farizrahman4u/recurrentshop/blob/43635f3531d34f329501b1eaddd674a95fa413a5/recurrentshop/engine.py). How would I go about making this run?

Thanks!

> Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Currently only two types of recurrent Keras layers aresupported, 'LSTM' and 'SimpleRNN'. You tried to load a layer of class:RecurrentSequential. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.layers.wrappers.KerasBidirectional.<init>(KerasBidirectional.java:155)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:221)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:218)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:164)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:96)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:307)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:127)
	at languageModels.other.SimpleSequentialMlpImport.main(SimpleSequentialMlpImport.java:82)

**Comment by maxpumperla** [comment]
this needs a corresponding implementation of that layer in dl4j and mapping it. we only support Lambda layers when it comes to custom layers

**Comment by benman1** [comment]
That's what I suspected. Thanks!
