### ISSUE TITLE
java.util.LinkedHashMap cannot be cast to java.util.List

### ISSUE THREAD

**Issue by aakashganga** [deeplearning4j/deeplearning4j#6761]
I am using https://github.com/maxpumperla/dl4j_coursera/releases/download/v0.4/dl4j-snapshot.jar and running a Keras model on Spark using the Spark command.

spark2-submit --class skymind.dsx.KerasImportCSVSparkRunner --files iris.txt,iris_model.h5 --master yarn dl4j-snapshot.jar -batchSizePerWorker 15 -indexLabel 4 -numClasses 3 -modelFileName iris_model.h5 -dataFileName iris.txt

I get the following error.
========================================================================
Exception in thread "main" java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.List
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:99)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:60)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:120)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:142)
	at skymind.dsx.KerasImportCSVSparkRunner.entryPoint(KerasImportCSVSparkRunner.java:102)
	at skymind.dsx.KerasImportCSVSparkRunner.main(KerasImportCSVSparkRunner.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by maxpumperla** [comment]
that jar is about a year old. it doesn't support keras versions from 2.2.2 onwards. the reason is that keras changed its serde format slightly. Model is ok, Sequential isn't.

**Comment by aakashganga** [comment]
@maxpumperla where could I get the new jar from?

**Comment by maxpumperla** [comment]
you can build it yourself, file an issue in the other repo. also, is downgrading to keras 2.2.2 really that bad for your case?

**Comment by aakashganga** [comment]
I downgraded Keras to 2.2.2 and ran the model. Now get a different error.

Exception in thread "main" java.lang.RuntimeException: Kryo serialization detected without an appropriate registrator for ND4J INDArrays.
When using Kryo, An appropriate Kryo registrator must be used to avoid serialization issues (NullPointerException) with off-heap data in INDArrays.
Use nd4j-kryo_2.10 or _2.11 artifact, with sparkConf.set("spark.kryo.registrator", "org.nd4j.Nd4jRegistrator");
See https://deeplearning4j.org/spark#kryo for more details
	at org.deeplearning4j.spark.util.SparkUtils.checkKryoConfiguration(SparkUtils.java:96)
	at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.<init>(SparkDl4jMultiLayer.java:123)
	at skymind.dsx.KerasImportCSVSparkRunner.entryPoint(KerasImportCSVSparkRunner.java:112)
	at skymind.dsx.KerasImportCSVSparkRunner.main(KerasImportCSVSparkRunner.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NullPointerException
	at org.nd4j.linalg.api.shape.Shape.shapeOf(Shape.java:1959)
	at org.nd4j.linalg.api.shape.Shape.length(Shape.java:1733)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.lengthLong(BaseNDArray.java:4591)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.equalsWithEps(BaseNDArray.java:4415)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.equals(BaseNDArray.java:4484)
	at org.deeplearning4j.spark.util.SparkUtils.checkKryoConfiguration(SparkUtils.java:94)
	... 13 more

**Comment by agibsonccc** [comment]
@aakashganga this is completely unrelated. You're posting what amounts to a spark issue (with a description on how to fix it) on a resolved issue. I am locking this thread. Please read the error before you just copy and paste it on to the issue tracker. Thanks.
