### ISSUE TITLE
jnind4jcpu.dll: Can't find dependent libraries

### ISSUE THREAD

**Issue by daomeigou** [deeplearning4j/deeplearning4j#6831]
Hi guys, I got java.lang.UnsatisfiedLinkError when I tried to run my project. It showed "Can't find dependent libraries", but I checked, all necessary file exist. I tried to remove /.javacpp and compile again, still got same error. I also tried to add "-Djava.library.path=""" as VM parameter, but didn't work.

<dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>1.0.0-beta3</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>1.0.0-beta3</version>
        </dependency>
        <dependency>
            <groupId>org.datavec</groupId>
            <artifactId>datavec-api</artifactId>
            <version>1.0.0-beta3</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math3</artifactId>
            <version>3.6.1</version>
        </dependency>
    </dependencies>

log4j:WARN No appenders could be found for logger (org.nd4j.linalg.factory.Nd4jBackend).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:71)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.lang.Class.newInstance(Class.java:558)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5587)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5482)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:215)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:683)
	at deeplearning.Task.test(Task.java:37)
	at deeplearning.App.main(App.java:10)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:68)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:36)
	... 12 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2541)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:873)
	at java.base/java.lang.System.loadLibrary(System.java:1857)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1258)
	at org.bytedeco.javacpp.Loader.load(Loader.java:999)
	at org.bytedeco.javacpp.Loader.load(Loader.java:891)
	at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.bytedeco.javacpp.Loader.load(Loader.java:950)
	at org.bytedeco.javacpp.Loader.load(Loader.java:891)
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.<clinit>(Nd4jCpu.java:1613)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:292)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:46)
	... 13 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\redce\.javacpp\cache\nd4j-native-1.0.0-beta3-windows-x86_64.jar\org\nd4j\nativeblas\windows-x86_64\jnind4jcpu.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2614)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2499)
	at java.base/java.lang.Runtime.load0(Runtime.java:812)
	at java.base/java.lang.System.load(System.java:1821)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1238)
	... 24 more

**Comment by AlexDBlack** [comment]
How exactly are you managing your project dependencies?
Are you using a build tool (like maven, gradle, etc)? If so - please post your pom.xml or similar.

**Comment by daomeigou** [comment]
> 
> 
> How exactly are you managing your project dependencies?
> Are you using a build tool (like maven, gradle, etc)? If so - please post your pom.xml or similar.

Hi Alex, I built Maven project in IntelliJ. Following is pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dl.deeplearning</groupId>
    <artifactId>deeplearning</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>1.0.0-beta3</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>1.0.0-beta3</version>
        </dependency>
        <dependency>
            <groupId>org.datavec</groupId>
            <artifactId>datavec-api</artifactId>
            <version>1.0.0-beta3</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math3</artifactId>
            <version>3.6.1</version>
        </dependency>
    </dependencies>
</project>

**Comment by raver119** [comment]
You should run dependecy walker, to see what exactly is missed on your system.

cc @saudet

**Comment by daomeigou** [comment]
> 
> 
> Aha, if libmkldnn is absent, that's a problem.
> 
> What's your cpu model name and os version?

hmmm, my cpu is i5-5200U and OS is Win10 professional.

**Comment by saudet** [comment]
Dependency Walker doesn't work very well anymore, can you try again with the Dependencies tool?
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by AlexDBlack** [comment]
One other thing to try (to rule out IntelliJ causing this somehow) is to build and run it from the command line (mvn package + java cp ...)
To do that, make sure you have the maven shade plugin configured as per this:
https://github.com/deeplearning4j/dl4j-examples/blob/master/standalone-sample-project/pom.xml#L69-L135

**Comment by daomeigou** [comment]
> 
> 
> Dependency Walker doesn't work very well anymore, can you try again with the Dependencies tool?
> https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

It seems I already had all necessary files lol

![1](https://user-images.githubusercontent.com/22204795/49768675-63f87780-fcdd-11e8-9310-3edb2b40b1f3.jpg)
![2](https://user-images.githubusercontent.com/22204795/49768677-66f36800-fcdd-11e8-80e0-ae329400897d.jpg)

**Comment by saudet** [comment]
Try the recursive mode just to be sure: https://github.com/lucasg/Dependencies#installation-and-usage

**Comment by daomeigou** [comment]
Thanks guys, I fixed the issue by removing all maven dependencies and re-installing.
