### ISSUE TITLE
LSTM/RepeatVector Keras Incompatibility? ND4JWorkspaceException / Unexpected end-of-input

### ISSUE THREAD

**Issue by r-snijders** [deeplearning4j/deeplearning4j#6843]
Hello, my colleague made a network in Keras/Python using:
```python
model = Sequential()
model.add(LSTM(64, activation = 'sigmoid', input_shape=(12,1)))
model.add(RepeatVector(12))
model.add(LSTM(12, activation = 'relu', return_sequences=True))
model.add(Dense(1))
model.compile(optimizer='adam', loss = 'mse')
```
I like to use it in deeplearning4j (1.0.0-SNAPSHOT), so I import it:
```java
MultiLayerNetwork mln = KerasModelImport.importKerasSequentialModelAndWeights("mynetwork.h5");
System.out.println(mln.summary());
```
This results in:
```bash
LayerName (LayerType)            nIn,nOut   TotalParams   ParamsShape                      
lstm_1 (LastTimeStepLayer)       1,64       16896         W:{1,256}, RW:{64,256}, b:{1,256}
repeat_vector_1 (RepeatVector)   -,-        0             -                                
lstm_2 (LSTM)                    64,12      3696          W:{64,48}, RW:{12,48}, b:{1,48}  
dense_1 (DenseLayer)             12,1       13            W:{12,1}, b:{1,1}                
dense_1_loss (LossLayer)         -,-        0             -                                
-------------------------------------------------------------------------------------------
            Total Parameters:  20605
        Trainable Parameters:  20605
           Frozen Parameters:  0
```
But with a warning during loading:
```bash
INFO: Unexpected end-of-input: was expecting closing '"' for name
 at [Source: {"class_name": "Sequential", "config": [{"class_name": "LSTM", "config": {"name": "lstm_1", "trainable": true, "batch_input_shape": [null, 12, 1], "dtype": "float32", "return_sequences": false, "return_state": false, "go_backwards": false, "stateful": false, "unroll": false, "units": 64, "activation": "sigmoid", "recurrent_activation": "hard_sigmoid", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "recurrent_initializer": {"class_name": "Orthogonal", "config": {"gain": 1.0, "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "unit_forget_bias": true, "kernel_regularizer": null, "recurrent_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "recurrent_constraint": null, "bias_constraint": null, "dropout": 0.0, "recurrent_dropout": 0.0, "implementation": 1}}, {"class_name": "RepeatVector", "config": {"name": "repeat_vector_1", "trainable": true, "n": 12}}, {"class_name": "LSTM", "config": {"name": "lstm_2", "trainable": true, "return_sequences": true, "return_state": false, "go_backwards": false, "stateful": false, "unroll": false, "units": 12, "activation": "relu", "recurrent_activation": "hard_sigmoid", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "recurrent_initializer": {"class_name": "Orthogonal", "config": {"gain": 1.0, "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "unit_forget_bias": true, "kernel_regularizer": null, "recurrent_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "recurrent_constraint": null, "bias_constraint": null, "dropout": 0.0, "recurrent_dropout": 0.0, "implementation": 1}}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "units": 1, "act; line: 1, column: 4001]
Dec 12, 2018 11:41:58 AM org.nd4j.linalg.factory.Nd4jBackend load
INFO: Loaded [CpuBackend] backend
Dec 12, 2018 11:41:59 AM org.nd4j.nativeblas.NativeOpsHolder <init>
INFO: Number of threads used for NativeOps: 2
Dec 12, 2018 11:41:59 AM org.nd4j.nativeblas.Nd4jBlas <init>
INFO: Number of threads used for BLAS: 2
Dec 12, 2018 11:41:59 AM org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner printEnvironmentInformation
INFO: Backend used: [CPU]; OS: [Linux]
Dec 12, 2018 11:41:59 AM org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner printEnvironmentInformation
INFO: Cores: [4]; Memory: [3.5GB];
Dec 12, 2018 11:41:59 AM org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner printEnvironmentInformation
INFO: Blas vendor: [MKL]
```
Furthermore, if I apply some input to it:
```java
INDArray in = Nd4j.ones(1, 1, 1);
mln.feedForward(in);
```
I get:
```bash
java.lang.IllegalStateException: Feed forward to layer (inference): array (ACTIVATIONS) workspace validation failed (layer 1 - layer name "repeat_vector_1" - class: org.deeplearning4j.nn.layers.RepeatVector) - array is defined in incorrect workspace
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.validateArrayWorkspaces(MultiLayerNetwork.java:899)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.ffToLayerActivationsDetached(MultiLayerNetwork.java:980)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:802)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:1277)
       ...
Caused by: org.nd4j.linalg.workspace.ND4JWorkspaceException: Array workspace validation failed: Array of type ACTIVATIONS should be detached (no workspace) but is in workspace: WS_LAYER_WORKING_MEM
	at org.nd4j.linalg.workspace.BaseWorkspaceMgr.validateArrayLocation(BaseWorkspaceMgr.java:213)
	at org.deeplearning4j.nn.workspace.LayerWorkspaceMgr.validateArrayLocation(LayerWorkspaceMgr.java:86)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.validateArrayWorkspaces(MultiLayerNetwork.java:890)
	... 11 more
```
However, I don't get the error if I do this (it results in an INDArray of 12 elements):
```java
INDArray in = Nd4j.ones(1, 1, 1);
mln.output(in);
```

In this an incompatibility issue with Keras or am I doing something wrong myself?
It seems somewhat related to this issue although it should work in 1.0.0-SNAPSHOT:
https://github.com/deeplearning4j/deeplearning4j/issues/6487

Thanks for the help.

**Comment by maxpumperla** [comment]
@r-snijders thanks for reporting. The warning can be ignored, that's a little inconvenience we see when opening large hdf5 groups. The `feedforward` behaviour is indeed a bug, which I'll need to look into. The good news is that you probably don't need that functionality. For network predictions `output` is really all you want.
