### ISSUE TITLE
Unknown initializer

### ISSUE THREAD

**Issue by Nasikkarsumukh** [deeplearning4j/deeplearning4j#6845]
org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unknown keras weight initializer GlorotUniform. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasInitilizationUtils.mapWeightInitialization(KerasInitilizationUtils.java:183) ~[deeplearning4j-modelimport-1.0.0-beta3.jar:na]
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasInitilizationUtils.getWeightInitFromConfig(KerasInitilizationUtils.java:223) ~[deeplearning4j-modelimport-1.0.0-beta3.jar:na]
	at org.deeplearning4j.nn.modelimport.keras.layers.core.KerasDense.<init>(KerasDense.java:100) ~[deeplearning4j-modelimport-1.0.0-beta3.jar:na]
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:219) ~[deeplearning4j-modelimport-1.0.0-beta3.jar:na]
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:218) ~[deeplearning4j-modelimport-1.0.0-beta3.jar:na]
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:111) ~[deeplearning4j-modelimport-1.0.0-beta3.jar:na]
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:58) ~[deeplearning4j-modelimport-1.0.0-beta3.jar:na]
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:322) ~[deeplearning4j-modelimport-1.0.0-beta3.jar:na]
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:195) ~[deeplearning4j-modelimport-1.0.0-beta3.jar:na]

Facing this error while importing the model through.h5 file.
Please let me know the solution.

**Comment by maxpumperla** [comment]
small patch applied, should be in SNAPSHOT tomorrow. thanks for reporting, @Nasikkarsumukh
