### ISSUE TITLE
DL4J: MultiLayerNetwork.scoreHelper can use workspace for activations

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6856]
This array is detached but doesn't need to be, as it is not returned or used outside of the method:
https://github.com/deeplearning4j/deeplearning4j/blob/af7155d61dc810d3e7139f15f98810e0255b2e17/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L2464-L2465

**Comment by stolsvik** [comment]
Comment, as asked for in gitter:
I'm scoring inside a Workspace. However, I also want to score while running through the DataSets (as well as Evaluation, and ROC). This works with my "hacked" score-method (which includes the Worspace to the outputLayerDetached). When trying to use beta3's score method, I get this exception:

```
org.nd4j.linalg.workspace.ND4JWorkspaceException: Expected no workspace active in outputOfLayerDetached - Open/active workspaces: [Evaluation MemoryWorkspace]
	at org.nd4j.linalg.workspace.WorkspaceUtils.assertNoWorkspacesOpen(WorkspaceUtils.java:54)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1123)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.scoreHelper(MultiLayerNetwork.java:2476)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.score(MultiLayerNetwork.java:2444)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.score(MultiLayerNetwork.java:2433)
	at com.stolsvik.machinelearning.evaluate.MultiAspectEvaluator.evaluate(MultiAspectEvaluator.groovy:107)
```

I then try to use this piece of code to "get out" of the workspace:
```
                MemoryWorkspace outSideMemWs = Nd4j.getWorkspaceManager().scopeOutOfWorkspaces()
                try {
                    double scoreForDataSet =  model.score(testDataSet)
                    totalScoreForTestSet += scoreForDataSet * dsDataPoints.size()
                }
                finally {
                    outSideMemWs.close()
                }
```

But the Exception persists.

By cursory look through the Workspace code, it seems like the test which outputLayerDetached runs (`WorkspaceUtils.assertNoWorkspacesOpen("Expected no workspace active in outputOfLayerDetached")`) is not agreeing that a "scopeOutOfWorkspaces()" is (effectively) closed.

(Also notice that "open" and "active" seems to be used a bit interchangeably in this code. That method says "NoWorkspaces_Open_", while what it checks is `ws.isScopeActive()` - This is also revealed in the Exception's message (see above). This could be streamlined a bit; Nothing like a couple of different terms for the same concept to cause confusion)

**Comment by AlexDBlack** [comment]
Right, it's a bit of an edge case there for the check. I will add that adding a "scopeOutOfWorkspaces" before calling score would (other than the check) have no different behaviour than calling it normally.
i.e., it wouldn't fix anything or provide any performance benefit what-so-ever.
Not sure what the motivation is there.

Anyway, I'll look at fixing this score method properly soon.

**Comment by stolsvik** [comment]
> . I will add that adding a "scopeOutOfWorkspaces" before calling score would (other than the check) have no different behaviour than calling it normally. i.e., it wouldn't fix anything or provide any performance benefit what-so-ever.

The benefit would be that it works then. Or rather, it should, judging by .. well.. the intention of the code. That is, since it checks whether the caller have a Workspace active (which I do) and throws if there is an active WS.

I need to do this for the ROC.eval() code which is in the same WS-loop, otherwise it throws.

I'd rather supply the WS myself.

**Comment by AlexDBlack** [comment]
Workspace for scoring still needs to be implemented, but allowing scoped out for scoring etc is now supported: https://github.com/deeplearning4j/deeplearning4j/pull/6858
