### ISSUE TITLE
libnd4j: Normalize moments datatype validation incorrect

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6865]
Seems to expect all operands to have same type, but that doesn't hold for this op.

```
    @Test
    public void testNormalizeMoments(){
        INDArray data = Nd4j.linspace(1, 100, 100, DataType.DOUBLE).reshape(10, 10);
        INDArray ssSum = data.sum(0).castTo(DataType.DOUBLE);
        INDArray ssSqSum = data.mul(data).sum(0).castTo(DataType.DOUBLE);
        INDArray counts = Nd4j.scalar(DataType.INT, 10);

        INDArray mean = Nd4j.createUninitialized(DataType.DOUBLE, 1, 10);
        INDArray var = Nd4j.createUninitialized(DataType.DOUBLE, 1, 10);

        CustomOp op = DynamicCustomOp.builder("normalize_moments")
                .addInputs(counts, ssSum, ssSqSum)
                .addOutputs(mean, var)
                .addFloatingPointArguments(1e-4)
                .build();

        Nd4j.getExecutioner().exec(op);
    }
```

```
java.lang.RuntimeException: NativeOps::execScalar both operands must have same data type; Expected: [DOUBLE]; Actual: [INT32]

	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOp(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1812)
	at org.nd4j.autodiff.opvalidation.ReductionOpValidation.testNormalizeMoments(ReductionOpValidation.java:861)
```

**Comment by raver119** [comment]
Fixed in #6883
