### ISSUE TITLE
Libnd4j/SameDiff: multiply_bp edge case bug

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6871]
add, subtract, divide, reversedivide, reversesubtract ops are all fine with the same shapes.
Seems restricted to the "length 1 but not rank 0 scalar" broadcast case?

```
    @Test
    public void testMulBpBroadcast() {

        INDArray x = Nd4j.ones(DataType.DOUBLE, 3, 4, 5);
        INDArray y = Nd4j.ones(DataType.DOUBLE, 1, 1, 1);
        INDArray grad = Nd4j.ones(DataType.DOUBLE, 3, 4, 5);

        INDArray outFwd = Nd4j.create(DataType.DOUBLE, 3, 4, 5);

        CustomOp op = DynamicCustomOp.builder("multiply")
                .addInputs(x, y)
                .addOutputs(outFwd)
                .build();

        Nd4j.getExecutioner().exec(op);

        INDArray outBpX = Nd4j.create(DataType.DOUBLE, 3, 4, 5);
        INDArray outBpY = Nd4j.create(DataType.DOUBLE, 1, 1, 1);
        CustomOp opBp = DynamicCustomOp.builder("multiply_bp")
                .addInputs(x, y, grad)
                .addOutputs(outBpX, outBpY)
                .build();

        Nd4j.getExecutioner().exec(opBp);            //EXCEPTION
    }
```

```
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 8
o.n.n.Nd4jBlas - Number of threads used for BLAS: 8
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [7.1GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute op multiply_bp. Attempted to execute with 3 inputs, 2 outputs, 0 targs and 0 iargs. Inputs: [(DOUBLE,[3,4,5],c), (DOUBLE,[1,1,1],c), (DOUBLE,[3,4,5],c)]. Outputs: [(DOUBLE,[3,4,5],c), (DOUBLE,[1,1,1],c)] - Please see above message (printed out from c++) for a possible cause of error.

java.lang.RuntimeException: NDArray::applyScalarArr method: operand is not a scalar!

	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOp(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1812)
	at org.nd4j.autodiff.Temp.testMulBpBroadcast(Temp.java:72)
```

**Comment by AlexDBlack** [comment]
Consolidated to issue: https://github.com/deeplearning4j/deeplearning4j/issues/6873
