### ISSUE TITLE
 cudaEventSynchronize(...) failed

### ISSUE THREAD

**Issue by cqiaoYc** [deeplearning4j/deeplearning4j#6923]
#### Issue Description

I trained LSTM with GA and after running for more than 600 generations, an exception was thrown (There is one GXT 1080 graphics card, and 4 threads call the MultiLayerNetwork. rnnTimeStep method at the same time) : 
Exception in thread "JavaCPP Deallocator" CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4334 code=6(cudaErrorLaunchTimeout) "result"
CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4355 code=6(cudaErrorLaunchTimeout) "result"
CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4366 code=6(cudaErrorLaunchTimeout) "result"
CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4355 code=6(cudaErrorLaunchTimeout) "result"
CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4355 code=6(cudaErrorLaunchTimeout) "result"
java.lang.RuntimeException: CUDA error = 6: the launch timed out and was terminated
        at org.deeplearning4j.nn.layers.BaseCudnnHelper.checkCuda(BaseCudnnHelper.java:38)
        at org.deeplearning4j.nn.layers.BaseCudnnHelper$DataCache$Deallocator.deallocate(BaseCudnnHelper.java:92)
        at org.bytedeco.javacpp.Pointer$DeallocatorReference.clear(Pointer.java:281)
        at org.bytedeco.javacpp.Pointer$DeallocatorThread.run(Pointer.java:303)
Exception in thread "UniGC thread 0" java.lang.RuntimeException: cudaEventSynchronize(...) failed
        at org.nd4j.nativeblas.Nd4jCuda$NativeOps.eventSynchronize(Native Method)
CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4355 code=6(cudaErrorLaunchTimeout) "result"
        at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.synchronize(cudaEvent_t.java:69)CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4355 code=6(cudaErrorLaunchTimeout) "result"

        at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillFinished(SynchronousFlowController.java:134)CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4334 code=6(cudaErrorLaunchTimeout) "result"

        at org.nd4j.jita.flow.impl.GridFlowController.waitTillFinished(GridFlowController.java:63)
        at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillReleased(SynchronousFlowController.java:231)CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4355 code=6(cudaErrorLaunchTimeout) "result"

        at org.nd4j.jita.flow.impl.GridFlowController.waitTillReleased(GridFlowController.java:78)
        at org.nd4j.jita.allocator.impl.AtomicAllocator$UnifiedGarbageCollectorThread.run(AtomicAllocator.java:716)CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4355 code=6(cudaErrorLaunchTimeout) "result"

CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4355 code=6(cudaErrorLaunchTimeout) "result"
Exception in thread "pool-1-thread-3" Exception in thread "pool-1-thread-1" java.lang.RuntimeException: cudaStreamSynchronize(...) failed
CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4334 code=6(cudaErrorLaunchTimeout) "result"
        at org.nd4j.nativeblas.Nd4jCuda$NativeOps.streamSynchronize(Native Method)
        at org.nd4j.linalg.jcublas.context.CudaContext.syncSpecialStream(CudaContext.java:112)
CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4355 code=6(cudaErrorLaunchTimeout) "result"
        at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.flushQueueBlocking(CudaGridExecutioner.java:969)
        at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.commit(CudaGridExecutioner.java:1097)CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4355 code=6(cudaErrorLaunchTimeout) "result"

        at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:600)CUDA error at D:/jenkins/ws/dl4j-latest_release-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:4355 code=6(cudaErrorLaunchTimeout) "result"

        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1244)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3032)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3013)
        at com.cq.neurodl4j.rnn.trade.RnnNeuroTradeSimulator.simulateTrade(RnnNeuroTradeSimulator.java:126)
        at com.cq.neurodl4j.rnn.NeuroTradeIndiv.computeFitness(NeuroTradeIndiv.java:42)
        at com.cq.noninbreedingga.Population.computeFitness(Population.java:464)
        at com.cq.noninbreedingga.Population.evolute(Population.java:295)
        at com.cq.noninbreedingga.Population.evolute(Population.java:225)
        at com.cq.noninbreedingga.operator.PopulationEvolver.run(PopulationEvolver.java:25)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "pool-1-thread-2" java.lang.RuntimeException: cudaStreamSynchronize(...) failed
        at org.nd4j.nativeblas.Nd4jCuda$NativeOps.streamSynchronize(Native Method)
        at org.nd4j.linalg.jcublas.context.CudaContext.syncSpecialStream(CudaContext.java:112)
        at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.flushQueueBlocking(CudaGridExecutioner.java:969)
        at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.commit(CudaGridExecutioner.java:1097)
        at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:600)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1251)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3032)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3013)
        at com.cq.neurodl4j.rnn.trade.RnnNeuroTradeSimulator.simulateTrade(RnnNeuroTradeSimulator.java:126)
        at com.cq.neurodl4j.rnn.NeuroTradeIndiv.computeFitness(NeuroTradeIndiv.java:42)
        at com.cq.noninbreedingga.Population.computeFitness(Population.java:464)
        at com.cq.noninbreedingga.Population.evolute(Population.java:295)
        at com.cq.noninbreedingga.Population.evolute(Population.java:225)
        at com.cq.noninbreedingga.operator.PopulationEvolver.run(PopulationEvolver.java:25)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "pool-1-thread-4" java.lang.RuntimeException: cudaStreamSynchronize(...) failed
        at org.nd4j.nativeblas.Nd4jCuda$NativeOps.streamSynchronize(Native Method)
        at org.nd4j.linalg.jcublas.context.CudaContext.syncSpecialStream(CudaContext.java:112)
        at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.flushQueueBlocking(CudaGridExecutioner.java:969)
        at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.commit(CudaGridExecutioner.java:1097)
        at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:600)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1251)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3032)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3013)
        at com.cq.neurodl4j.rnn.trade.RnnNeuroTradeSimulator.simulateTrade(RnnNeuroTradeSimulator.java:126)
        at com.cq.neurodl4j.rnn.NeuroTradeIndiv.computeFitness(NeuroTradeIndiv.java:42)
        at com.cq.noninbreedingga.Population.computeFitness(Population.java:464)
        at com.cq.noninbreedingga.Population.evolute(Population.java:295)
        at com.cq.noninbreedingga.Population.evolute(Population.java:225)
        at com.cq.noninbreedingga.operator.PopulationEvolver.run(PopulationEvolver.java:25)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.RuntimeException: cudaStreamSynchronize(...) failed
        at org.nd4j.nativeblas.Nd4jCuda$NativeOps.streamSynchronize(Native Method)
        at org.nd4j.linalg.jcublas.context.CudaContext.syncSpecialStream(CudaContext.java:112)
        at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.flushQueueBlocking(CudaGridExecutioner.java:969)
        at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.commit(CudaGridExecutioner.java:1097)
        at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:600)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1244)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3032)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3013)
        at com.cq.neurodl4j.rnn.trade.RnnNeuroTradeSimulator.simulateTrade(RnnNeuroTradeSimulator.java:126)
        at com.cq.neurodl4j.rnn.NeuroTradeIndiv.computeFitness(NeuroTradeIndiv.java:42)
        at com.cq.noninbreedingga.Population.computeFitness(Population.java:464)
        at com.cq.noninbreedingga.Population.evolute(Population.java:295)
        at com.cq.noninbreedingga.Population.evolute(Population.java:225)
        at com.cq.noninbreedingga.operator.PopulationEvolver.run(PopulationEvolver.java:25)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

#### Version Information

* Deeplearning4j version : 1.0-beta3
* platform information : windows 10
* CUDA version, cuda10, cudnn 7.3
* NVIDIA driver version, GXT 1080 NVIDIA 25.21.14.1681

**Comment by cqiaoYc** [comment]
This exception is uncertain. I've run more than 2000 generations without throwing it out.

**Comment by raver119** [comment]
When running on Windows, and you don't have Tesla GPU - you must disable WDM timeout.

**Comment by raver119** [comment]
One more thing to consider: MultiLayerNetwork and ComputationGraph are NOT thread safe.

**Comment by cqiaoYc** [comment]
@raver119 Excuse me, how can I modify the code to avoid this error?

**Comment by raver119** [comment]
WDM timeout isn't a code thing. It's a windows nVidia driver setting. Google that one, there's registry option available for that.

**Comment by cqiaoYc** [comment]
@raver119 Thanks. About thread safe of MultiLayerNetwork, each thread handles a separate network. Should that be okay?

**Comment by raver119** [comment]
Yes, that's fine. You can even share their parameters, to reduce memory footprint. 

Anyway, just disable WDM timeout, and you'll be fine.

**Comment by raver119** [comment]
p.s. http://developer.download.nvidia.com/NsightVisualStudio/2.2/Documentation/UserGuide/HTML/Content/Timeout_Detection_Recovery.htm

**Comment by cqiaoYc** [comment]
@raver119 Thank you very much! I shared their input ndarray,  because the rnnTimeStep() method does not change the input parameters.
