### ISSUE TITLE
Tokenizer not serializable by Python

### ISSUE THREAD

**Issue by lo2aayy** [deeplearning4j/deeplearning4j#6981]
In this code:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-modelimport/src/test/java/org/deeplearning4j/nn/modelimport/keras/preprocessing/text/TokenizerImportTest.java

where the tokenizer is imported from Python, it is of type Json. However, when I tried to dump the tokenizer in python by json I got an error that it's not serializable, so how could the tokenizer be imported from python to java?

**Comment by lo2aayy** [comment]
Hey, thanks!
When I try it I get the following error: 

> Exception in thread "main" org.nd4j.shade.jackson.databind.JsonMappingException: Can not instantiate value of type [map type; class java.util.HashMap, [simple type, class java.lang.String] -> [simple type, class java.lang.Object]] from String value ('{"class_name": "Tokenizer", "config": {"num_words": 100, "filters": "!\"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n", "lower": true, "split": " ", "char_level": false, "oov_token": null, "document_count": 1, "word_counts": "{\"compensating\": 1, \"for\": 1, \"temperature\": 1, \"the\": 1, \"present\": 1, \"invention\": 1, \"relates\": 1, \"to\": 1, \"an\": 1, \"air\": 1, \"treatment\": 1, \"apparatus\": 1, \"which\": 1, \"is\": 1, \"controlled\": 1, \"by\": 1, \"a\": 1, \"control\": 1, \"and\": 1, \"regulating\": 1}", "word_docs": "{\"relates\": 1, \"an\": 1, \"control\": 1, \"for\": 1, \"temperature\": 1, \"by\": 1, \"to\": 1, \"present\": 1, \"controlled\": 1, \"apparatus\": 1, \"is\": 1, \"treatment\": 1, \"regulating\": 1, \"air\": 1, \"a\": 1, \"the\": 1, \"which\": 1, \"and\": 1, \"invention\": 1, \"compensating\": 1}", "index_docs": "{\"7\": 1, \"9\": 1, \"18\": 1, \"2\": 1, \"3\": 1, \"16\": 1, \"8\": 1, \"5\": 1, \"15\": 1, \"12\": 1, \"14\": 1, \"11\": 1, \"20\": 1, \"10\": 1, \"17\": 1, \"4\": 1, \"13\": 1, \"19\": 1, \"6\": 1, \"1\": 1}", "index_word": "{\"1\": \"compensating\", \"2\": \"for\", \"3\": \"temperature\", \"4\": \"the\", \"5\": \"present\", \"6\": \"invention\", \"7\": \"relates\", \"8\": \"to\", \"9\": \"an\", \"10\": \"air\", \"11\": \"treatment\", \"12\": \"apparatus\", \"13\": \"which\", \"14\": \"is\", \"15\": \"controlled\", \"16\": \"by\", \"17\": \"a\", \"18\": \"control\", \"19\": \"and\", \"20\": \"regulating\"}", "word_index": "{\"compensating\": 1, \"for\": 2, \"temperature\": 3, \"the\": 4, \"present\": 5, \"invention\": 6, \"relates\": 7, \"to\": 8, \"an\": 9, \"air\": 10, \"treatment\": 11, \"apparatus\": 12, \"which\": 13, \"is\": 14, \"controlled\": 15, \"by\": 16, \"a\": 17, \"control\": 18, \"and\": 19, \"regulating\": 20}"}}'); no single-String constructor/factory method
 at [Source: "{\"class_name\": \"Tokenizer\", \"config\": {\"num_words\": 100, \"filters\": \"!\\\"#$%&()*+,-./:;<=>?@[\\\\]^_`{|}~\\t\\n\", \"lower\": true, \"split\": \" \", \"char_level\": false, \"oov_token\": null, \"document_count\": 1, \"word_counts\": \"{\\\"compensating\\\": 1, \\\"for\\\": 1, \\\"temperature\\\": 1, \\\"the\\\": 1, \\\"present\\\": 1, \\\"invention\\\": 1, \\\"relates\\\": 1, \\\"to\\\": 1, \\\"an\\\": 1, \\\"air\\\": 1, \\\"treatment\\\": 1, \\\"apparatus\\\": 1, \\\"which\\\": 1, \\\"is\\\": 1, \\\"controlled\\\": 1, \\\"by\\\": 1, \\\"a\\\": 1, \\\"control\\\": 1, \\\"and\\\": 1, \\\"regulating\\\": 1}\", \"word_docs\": \"{\\\"relates\\\": 1, \\\"an\\\": 1, \\\"control\\\": 1, \\\"for\\\": 1, \\\"temperature\\\": 1, \\\"by\\\": 1, \\\"to\\\": 1, \\\"present\\\": 1, \\\"controlled\\\": 1, \\\"apparatus\\\": 1, \\\"is\\\": 1, \\\"treatment\\\": 1, \\\"regulating\\\": 1, \\\"air\\\": 1, \\\"a\\\": 1, \\\"the\\\": 1, \\\"which\\\": 1, \\\"and\\\": 1, \\\"invention\\\": 1, \\\"compensating\\\": 1}\", \"index_docs\": \"{\\\"7\\\": 1, \\\"9\\\": 1, \\\"18\\\": 1, \\\"2\\\": 1, \\\"3\\\": 1, \\\"16\\\": 1, \\\"8\\\": 1, \\\"5\\\": 1, \\\"15\\\": 1, \\\"12\\\": 1, \\\"14\\\": 1, \\\"11\\\": 1, \\\"20\\\": 1, \\\"10\\\": 1, \\\"17\\\": 1, \\\"4\\\": 1, \\\"13\\\": 1, \\\"19\\\": 1, \\\"6\\\": 1, \\\"1\\\": 1}\", \"index_word\": \"{\\\"1\\\": \\\"compensating\\\", \\\"2\\\": \\\"for\\\", \\\"3\\\": \\\"temperature\\\", \\\"4\\\": \\\"the\\\", \\\"5\\\": \\\"present\\\", \\\"6\\\": \\\"invention\\\", \\\"7\\\": \\\"relates\\\", \\\"8\\\": \\\"to\\\", \\\"9\\\": \\\"an\\\", \\\"10\\\": \\\"air\\\", \\\"11\\\": \\\"treatment\\\", \\\"12\\\": \\\"apparatus\\\", \\\"13\\\": \\\"which\\\", \\\"14\\\": \\\"is\\\", \\\"15\\\": \\\"controlled\\\", \\\"16\\\": \\\"by\\\", \\\"17\\\": \\\"a\\\", \\\"18\\\": \\\"control\\\", \\\"19\\\": \\\"and\\\", \\\"20\\\": \\\"regulating\\\"}\", \"word_index\": \"{\\\"compensating\\\": 1, \\\"for\\\": 2, \\\"temperature\\\": 3, \\\"the\\\": 4, \\\"present\\\": 5, \\\"invention\\\": 6, \\\"relates\\\": 7, \\\"to\\\": 8, \\\"an\\\": 9, \\\"air\\\": 10, \\\"treatment\\\": 11, \\\"apparatus\\\": 12, \\\"which\\\": 13, \\\"is\\\": 14, \\\"controlled\\\": 15, \\\"by\\\": 16, \\\"a\\\": 17, \\\"control\\\": 18, \\\"and\\\": 19, \\\"regulating\\\": 20}\"}}"; line: 1, column: 1]
	at org.nd4j.shade.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at org.nd4j.shade.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:843)
	at org.nd4j.shade.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:277)
	at org.nd4j.shade.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:284)
	at org.nd4j.shade.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:323)
	at org.nd4j.shade.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:25)
	at org.nd4j.shade.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at org.nd4j.shade.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2597)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.parseJsonString(KerasModelUtils.java:349)
	at org.deeplearning4j.nn.modelimport.keras.preprocessing.text.KerasTokenizer.fromJson(KerasTokenizer.java:109)
	at dl4jTrial.main(dl4jTrial.java:44)

**Comment by maxpumperla** [comment]
@lo2aayy this might indicate your json string is off. are you sure you serialize your config correctly?

You might want to run the unit test you referenced earlier (which works), to see what's going on. At least you could check your tokenizer json against this one https://github.com/deeplearning4j/dl4j-test-resources/blob/master/src/main/resources/modelimport/keras/preprocessing/tokenizer.json

or you use that json to test your app. the `\` escaping looks off in your example.

**Comment by lo2aayy** [comment]
The unit test works fine, but the tokenizer.json has no entries, it's an empty constructor.
When I add an entry to it in word_index for example, then the importing fails.

for example when changing from: 

> {"config": {"split": " ", "word_index": "{}", "filters": "!\"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n", "index_docs": "{}", "char_level": false, "document_count": 0, "num_words": 100, "word_docs": "{}", "word_counts": "{}", "lower": true, "index_word": "{}", "oov_token": null}, "class_name": "Tokenizer"}

to 

> {"config": {"split": " ", "word_index": "{ **"compensating": 1**}", "filters": "!\"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n", "index_docs": "{}", "char_level": false, "document_count": 0, "num_words": 100, "word_docs": "{}", "word_counts": "{}", "lower": true, "index_word": "{}", "oov_token": null}, "class_name": "Tokenizer"}

I get the following error:
`Exception in thread "main" org.nd4j.shade.jackson.core.JsonParseException: Unexpected character ('c' (code 99)): was expecting comma to separate OBJECT entries
 at ........`

**Comment by lo2aayy** [comment]
Thank you, no worries I got it working. The problem was that the \\" escaping was needed,  but to_json() from keras adds extra \ at some places and I had to write a small script to remove them.
