### ISSUE TITLE
ND4J/SameDiff: Jaccard, Euclidean, Manhattan and Cosine Distance throw Exceptions in backward pass

### ISSUE THREAD

**Issue by SchmaR** [deeplearning4j/deeplearning4j#7001]
#### Issue Description

The backward pass of the affected distance functions should work correctly without depending on what happened to their input beforehand. 

I encountered the problem that _Cosine_, _Euclidean_, and _Manhattan_ distance are throwing an `org.nd4j.linalg.exception.ND4JIllegalStateException: Cannot get rank from null shape array` in the backward pass. _Jaccard_ Distance throws a `java.lang.NullPointerException`. This problem occurs if the passed variables have been used in any other operation, such as addition or transpose before.

Here you can find two test cases one failing (one parameter of the distance function is used in addition) and the other passing: https://gist.github.com/SchmaR/9d691a518a182543a5ba970c8d24dbac

#### Stacktrace for euclidean distance
```
org.nd4j.linalg.exception.ND4JIllegalStateException: Cannot get rank from null shape array

	at org.nd4j.linalg.api.shape.Shape.rankFromShape(Shape.java:3510)
	at org.nd4j.linalg.api.ops.impl.reduce3.EuclideanDistance.doDiff(EuclideanDistance.java:95)
	at org.nd4j.autodiff.functions.DifferentialFunction.diff(DifferentialFunction.java:608)
	at org.nd4j.autodiff.samediff.SameDiff$1.define(SameDiff.java:10001)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:9791)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:9776)
	at org.nd4j.autodiff.samediff.SameDiff.createGradFunction(SameDiff.java:9892)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:9816)
```

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT with nd4j-native as backend.
* platform information (OS, etc): Ubuntu 18.10, 64 Bit, Intel I7
* ~CUDA version, if used~
* ~NVIDIA driver version, if in use~

Do you have advice on how I could proceed/workaround or try to fix this issue?

**Comment by AlexDBlack** [comment]
Thanks for reporting, issue was fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/7011
Fix should be available on snapshots in a few hours
