### ISSUE TITLE
Inference on a model that shares an embedding layer with multiple input fails

### ISSUE THREAD

**Issue by Isa-rentacs** [deeplearning4j/deeplearning4j#7021]
#### Issue Description
I imported a Keras model using Keras import, and it successfully loaded the model, but when I call ```model.output``` it failed with an error:
```Exception in thread "main" java.lang.IllegalStateException: Cannot do forward pass: inputs not set```

The model structure is as the screenshot below.
![model](https://user-images.githubusercontent.com/1147443/51298432-da6c6000-1a67-11e9-85b2-d6d39ffbf9eb.png)

The weights of ```Embedding``` layer are shared for the 3 inputs (```character_input```, ```forward_shifted_1```, ```backward_shifted_1```). The length of those 3 inputs are the same.
So if the shape for the inputs is ```(1,10)``` the output of the ```Embedding``` layer will be ```(1,10,32)```.
The following ```Concatenate``` layer will concatenate 3 inputs with shape ```(1,10,32)``` to ```(1,10,96)```

Here is the code I used : https://gist.github.com/Isa-rentacs/95cefe988b102609c164a7e0123ae0f4

#### Additional information
The full stacktrace is as follows:
```
Exception in thread "main" java.lang.IllegalStateException: Cannot do forward pass: inputs not set
	at org.deeplearning4j.nn.graph.vertex.impl.MergeVertex.doForward(MergeVertex.java:78)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputOfLayersDetached(ComputationGraph.java:2316)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1727)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1686)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1616)
	at org.deeplearning4j.examples.modelimport.keras.TestModelImport.main(TestModelImport.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

I looked into the vertices in the ```ComputationGraph```, and found for the vertices for ```forward_shifted_1``` and ```backward_shifted_1``` have no ```outputVertices``` and thus the vertex for ```embedding_1``` only have an ```inputVertices``` (from ```character_input```)

isn't this usage of ```embedding``` layer supported? 

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
  * 1.0.0-beta3
* platform information (OS, etc)
  * Ubuntu 16.04
* CUDA version, if used
  * N/A
* NVIDIA driver version, if in use
  * N/A

Thanks,
-Isa

**Comment by maxpumperla** [comment]
@Isa-rentacs thanks for reporting, we don't support this right now, but I'll look into it.
