### ISSUE TITLE
Error on execution IrisAnalysis (datavec-exmaples project) 

### ISSUE THREAD

**Issue by srssrs** [deeplearning4j/deeplearning4j#7055]
#### Issue Description
When I try to execute the example
[org.datavec.transform.analysis.IrisAnalysis](https://github.com/deeplearning4j/dl4j-examples/blob/master/datavec-examples/src/main/java/org/datavec/transform/analysis/IrisAnalysis.java) 
 I have the following stacktrace:
```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Could not find creator property with name 'id' (in class org.apache.spark.rdd.RDDOperationScope)
 at [Source: {"id":"0","name":"textFile"}; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:843)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:533)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:220)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:405)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:354)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:262)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:242)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:143)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:439)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3666)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3558)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at org.apache.spark.rdd.RDDOperationScope$.fromJson(RDDOperationScope.scala:85)
	at org.apache.spark.rdd.RDDOperationScope$$anonfun$5.apply(RDDOperationScope.scala:136)
	at org.apache.spark.rdd.RDDOperationScope$$anonfun$5.apply(RDDOperationScope.scala:136)
	at scala.Option.map(Option.scala:146)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:136)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.SparkContext.withScope(SparkContext.scala:714)
	at org.apache.spark.SparkContext.hadoopFile(SparkContext.scala:1011)
	at org.apache.spark.SparkContext$$anonfun$textFile$1.apply(SparkContext.scala:832)
	at org.apache.spark.SparkContext$$anonfun$textFile$1.apply(SparkContext.scala:830)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.SparkContext.withScope(SparkContext.scala:714)
	at org.apache.spark.SparkContext.textFile(SparkContext.scala:830)
	at org.apache.spark.api.java.JavaSparkContext.textFile(JavaSparkContext.scala:181)
	at org.datavec.transform.analysis.IrisAnalysis.main(IrisAnalysis.java:43)
19/01/22 15:47:25 INFO SparkContext: Invoking stop() from shutdown hook
19/01/22 15:47:25 INFO SparkUI: Stopped Spark web UI at http://192.168.1.3:4040
19/01/22 15:47:25 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/01/22 15:47:25 INFO MemoryStore: MemoryStore cleared
19/01/22 15:47:25 INFO BlockManager: BlockManager stopped
19/01/22 15:47:25 INFO BlockManagerMaster: BlockManagerMaster stopped
19/01/22 15:47:25 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
19/01/22 15:47:25 INFO SparkContext: Successfully stopped SparkContext
19/01/22 15:47:25 INFO ShutdownHookManager: Shutdown hook called
```

#### Version Information
* Deeplearning4j version
1.0.0-beta3
* platform information (OS, etc)
MacOS 10.14.2

**Comment by AlexDBlack** [comment]
Thanks for reporting, fixed here: https://github.com/deeplearning4j/dl4j-examples/pull/810
