### ISSUE TITLE
ND4J: INDArray.get(point(x), y) or .get(y, point(x)) should return rank 1 for rank 2 arrays

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7092]
In line with the recent rank 0/1 changes, I think we should change this.

Currently, [3,4].get(point(0), all()) returns a [1,4] (and [3,1] for all/point)
In rank 3+ contexts, point(x) always reduces the rank by 1.

Aha! Link: https://skymindai.aha.io/features/ND4J-130

**Comment by AlexDBlack** [comment]
Also: getColumn and getRow should probably return rank 1. Though we might want to add a getColumn(int, boolean keepDim) option for easy backward compatibility?

**Comment by AlexDBlack** [comment]
Also: INDArray.get(point(x)) on rank 1 arrays seems to be broken...
```
    @Test
    public void testRank1Get(){
        INDArray rank1 = Nd4j.create(5);
        assertEquals(1, rank1.rank());
        INDArray out = rank1.get(NDArrayIndex.point(0));
        assertEquals(1, out.rank());
    }
```

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.nd4j.linalg.indexing.ShapeOffsetResolution.exec(ShapeOffsetResolution.java:358)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:4976)
	at org.nd4j.Temp.test(Temp.java:25)
```
