### ISSUE TITLE
UI server and number of open file descriptors

### ISSUE THREAD

**Issue by madhs53** [deeplearning4j/deeplearning4j#7103]
I've noticed that a started UI Server consumes 321 file descriptors until it is stopped.

```
uiServer = new PlayUIServer(port);
uiServer.runMain(new String[]{"--uiPort", String.valueOf(port)});
```

Below is output showing that before starting the UI server, we had 37 descriptors open. Once UI server was started, we had 358 descriptors. When we stopped the UI server, descriptors went back down to 37.

```
[01-02-2019 21:52:47] Starting UI server. Open File Descriptors = 37
[01-02-2019 21:52:48] Started UI server. Open File Descriptors = 358
[01-02-2019 21:52:48] Attached UI server. Open File Descriptors = 358
[01-02-2019 21:52:48] Currently 1 users for UI Server on port 2900
[01-02-2019 21:52:52] Currently 0 users for UI Server on port 2900
[01-02-2019 21:52:52] Disposing UI Server on port 2900
[01-02-2019 21:52:52] Disposed UI server. Open File Descriptors = 36
[01-02-2019 22:12:10] Starting UI server. Open File Descriptors = 37
[01-02-2019 22:12:11] Started UI server. Open File Descriptors = 358
[01-02-2019 22:12:11] Attached UI server. Open File Descriptors = 358
[01-02-2019 22:12:11] Currently 1 users for UI Server on port 2901
```

Is this expected? The number of descriptors seems quite large.

We have multiple training sessions occurring concurrently on a single JVM, each of which enable the user to start a DL4J UI server to see the DL4J UI for that training session (from FileStatsStorage as we save it and can load it later). When there are no more users viewing that session we stop the UI server for that session.

When we have approx 10 UI servers running concurrently this brings our file descriptor usage up to the 4000 mark.

Is there a way we can re-use the same UI server for multiple sessions each with its own FileStatsStorage and specify in the URL which session to look at?

Or is there a way to reduce the number of file descriptors used by the play server?
Below is an example captured trace for which we can see thousands of entries (using the [Java File Leak Detector Agent](http://file-leak-detector.kohsuke.org/):

```
#2 selector by thread:pool-3-thread-3 on Fri Feb 01 17:01:32 AEDT 2019
        at java.nio.channels.spi.AbstractSelector.<init>(AbstractSelector.java:86)
        at sun.nio.ch.SelectorImpl.<init>(SelectorImpl.java:54)
        at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:64)
        at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
        at java.nio.channels.Selector.open(Selector.java:227)
        at org.jboss.netty.channel.socket.nio.SelectorUtil.open(SelectorUtil.java:63)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.openSelector(AbstractNioSelector.java:360)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.<init>(AbstractNioSelector.java:100)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.<init>(AbstractNioWorker.java:52)
        at org.jboss.netty.channel.socket.nio.NioWorker.<init>(NioWorker.java:45)
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.newWorker(NioWorkerPool.java:44)
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.newWorker(NioWorkerPool.java:28)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.init(AbstractNioWorkerPool.java:80)
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:39)
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:33)
        at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.<init>(NioServerSocketChannelFactory.java:149)
        at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.<init>(NioServerSocketChannelFactory.java:131)
        at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.<init>(NioServerSocketChannelFactory.java:115)
        at play.core.server.NettyServer.play$core$server$NettyServer$$newBootstrap(NettyServer.scala:50)
        at play.core.server.NettyServer$$anonfun$1.apply(NettyServer.scala:143)
        at play.core.server.NettyServer$$anonfun$1.apply(NettyServer.scala:142)
        at scala.Option.map(Option.scala:146)
        at play.core.server.NettyServer.<init>(NettyServer.scala:142)
        at play.core.server.NettyServerProvider.createServer(NettyServer.scala:213)
        at play.core.server.NettyServerProvider.createServer(NettyServer.scala:212)
        at play.core.server.ServerProvider$class.createServer(ServerProvider.scala:24)
        at play.core.server.NettyServerProvider.createServer(NettyServer.scala:212)
        at play.core.server.JavaServerHelper$.forRouter(Server.scala:155)
        at play.core.server.JavaServerHelper.forRouter(Server.scala)
        at play.server.Server.forRouter(Server.java:96)
        at org.deeplearning4j.ui.play.PlayUIServer.runMain(PlayUIServer.java:211)

```

In /proc/<pid>/fd (RHEL) I can see most of these are either of the following:
anon_inode:[eventpoll]
pipe:[121483487]

Any advice is greatly appreciated.

**Comment by madhs53** [comment]
Could this be due to some large default thread pool size with the netty implementation, with threads pre-started?

**Comment by AlexDBlack** [comment]
I can't think of any reason DL4J UI itself could be causing this. So yes, likely Play, or specifically Netty.
As for configuration - we don't do any file/thread configuration related to Play (it's in the application.conf) so it's using the defaults for thas (assuming such a configuration exists).
FWIW our application.conf is here, though it's pretty sparse and is basically the default one... https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-play/src/main/resources/application.conf

**Comment by madhs53** [comment]
Thanks Alex.

Looking at the netty code, for the constructor invoked on NioServerSocketChannelFactory it looks like it is indeed determining the maximum number of threads via ((ThreadPoolExecutor) executor).getMaximumPoolSize() and then creating 1 new worker from 0 to maximum straight away.

There is another constructor on NioServerSocketChannelFactory which allows you specify the maximum number of threads.

I'll look around to see if there's a way of specifying this.

**Comment by madhs53** [comment]
Here we go.
Under play.server.netty in the application.conf you linked.

eventLoopThreads = 0 
// This is the default and means netty can make up the number based on number of processors multiplied by 2

If we specify a value, it should limit the thread pool (and therefore the workers, and therefore the file descriptors).

**Comment by madhs53** [comment]
For reference: https://www.playframework.com/documentation/2.6.x/SettingsNetty

**Comment by AlexDBlack** [comment]
> now getting a NullPointException here: 

Hm... ok, I guess the message can in principle be null (we should add a check, that's easy).
Obviously you can just put a breakpoint on that line in your IDE to get the real exception.

**Comment by AlexDBlack** [comment]
Yes, we're still using Play 2.4 due to it being the last version with Scala 2.10 support.

**Comment by madhs53** [comment]
So.. It looks like netty is getting Runtime.getRuntime().availableProcessors()*2 and using that as the worker count, starting up each worker, with each holding a file descriptor. Since on our platform Runtime.getRuntime().availableProcessors() returns 160, this is a significant amount of workers per DL4J UI server instance.

Unfortunately I can't see how to devise a workaround with this version of Play. Any ideas?

**Comment by printomi** [comment]
@madhs53 if I understand what you wrote, I am interested in the same functionality that you described (multiple users using the same `PlayUIServer`, with their own *separate* training). I have to separate users, so that they can see only their model's training. If you don't have to separate users, sending a request to this URL: `/train/sessions/set/:to` might be what you need.

For me, I think that I have to modify `TrainModule` so that it holds all `StatsStorage` instances mapped to session IDs. I am working on two possible solutions to specify the session of the user: (1) with session cookies, or (2) URL path parameters. However, I had troubles with both ideas. 
1. I tried to set session cookie with a route like `/train/sessions/set/:to`, but it did not work, probably because the cookie that I set is not accessible higher in the hierarchy, say in `/train/overview`?
2. Rewriting URL-s to include session ID like `/train/overview` to `/train/overview/:sessionId` may be the solution, I guess? I did not finish this implementation, though.
What do you think about this?

**Comment by AlexDBlack** [comment]
@printomi Right, at present it's basically limited to one session at a time - current session is a global variable in the server, essentially.
As to why? A few reasons. It's been like that since the UI was implemented, and was implemented like that because it was quick and easy. (I build a lot of DL4J's UI functionality, and I'm far from a UI/front-end/JS expert).

Adding the session ID to the URLs may be the simplest solution here. Is this something you'd be interested in working on implementing? It's not really a high priority for us at present.

**Comment by printomi** [comment]
@AlexDBlack Yes, I want to work on this, and I would be happy to contribute to DL4J with this. My primary goal is not only training multiple models attached to the same UI, but also loading historical training results with given session ID.

I would do this by:
1. Modifying `TrainModule` so that it holds multiple `StatsStorage` instances mapped to session IDs. (Session ID can be set with `StatsListener.setSessionID()` before training, that is how I give unique IDs to my training statistics.)
2. Adding `PlayUIServer` a custom `StatsStorage` loader. This would handle session IDs not already loaded.
3. Making an option for hiding session selector dropdown from Java code, to separate users.
4. If these work properly, I would insert user authentication somehow, to get a truly multi-user UI server.

**Comment by AlexDBlack** [comment]
@printomi Let's move the discussion to here: https://github.com/deeplearning4j/deeplearning4j/issues/7110

This is getting a little off-topic in this issue (about file descriptors).

**Comment by madhs53** [comment]
Thanks all.
Happy for this issue to be closed off for now.

On our end we'll look at possibly writing an alternative UI server (WebSocket based). If successful, happy to contribute that back to the DL4J project for consideration.

**Comment by AlexDBlack** [comment]
@madhs53 Thanks, I'll close this.
Looks like there isn't an easy solution to the original file descriptors issue anyway...

A websocket based implementation would certainly be good. Maybe ping me before you get to work, as there's some UI work we'll be looking at with SameDiff too. The early prototype (fixed page only) uses flatbuffers instead of JSON for communication, which clearly is much more efficient... we might want to look at that for the DL4J UI also... or maybe even combine the two UIs.
