### ISSUE TITLE
ND4J/SameDiff: ND4JIllegalStateException "argument uses outdated workspace pointer" in SameDiff graph used in a ComputationGraph

### ISSUE THREAD

**Issue by SchmaR** [deeplearning4j/deeplearning4j#7120]
#### Issue Description

Hi,
I'm on the current snapshot build and get an ND4JIllegalStateException when I fit a ComputationGraph which contains a loss function which is written using SameDiff. I create one SameDiff graph and want to reuse it for every iteration by passing the new values via placeholders into it. 

Here is a test setup which causes the exception: https://gist.github.com/SchmaR/e4d697a2ca4309bef2a2e80a05771523
Here is a "minimal example" of the loss function: https://gist.github.com/SchmaR/c8577e9e546e63b5263f43a27ba3f7a1

##### Stacktrace
```
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: Op [add] X argument uses outdated workspace pointer from workspace [WS_LAYER_WORKING_MEM]
All open workspaces: [WS_LAYER_WORKING_MEM, test, WS_ALL_LAYERS_ACT]
For more details, see the ND4J User Guide: nd4j.org/userguide#workspaces-panic
    at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.checkWorkspace(DefaultOpExecutioner.java:286)
    at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.checkForWorkspaces(DefaultOpExecutioner.java:296)
    at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.profilingHookIn(DefaultOpExecutioner.java:356)
    at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1585)
    at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:371)
    at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:28)
    at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:244)
    at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:10433)
    at org.nd4j.autodiff.samediff.SameDiff.execAll(SameDiff.java:10398)
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: nd4j-api-1.0.0-20190131.150707-14381
* platform information: Ubuntu 18.10, 64 Bit, Intel I7
* ~CUDA version~
* ~NVIDIA driver version~

#### Contributing

If I can help to figure out what's going wrong let me know.

**Comment by AlexDBlack** [comment]
Thanks for reporting and for the code to reproduce the issue.
The problem was that SameDiff wasn't properly set up to work when executing in an external workspace (which is the case when executing inside a DL4J layer or ILossFunction for example).
That has been resolved here: https://github.com/deeplearning4j/deeplearning4j/pull/7124
The fix should be available in snapshots in a few hours.
