### ISSUE TITLE
Exception in thread "main" java.lang.NegativeArraySizeException while invoking totalOutcomes() on RecordReaderDataSetIterator

### ISSUE THREAD

**Issue by rahul-raj** [deeplearning4j/deeplearning4j#7140]
#### Issue Description

Please describe our issue, along with:
**- expected behavior**
 totalOutcomes() should return the number of labels. In the below dataset:
http://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv 
The first one is output label. So, it is expected to be 7.

**- encountered behavior**
I'm getting the below exception:
```
Exception in thread "main" java.lang.NegativeArraySizeException
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritablesBatched(RecordReaderMultiDataSetIterator.java:396)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:360)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:327)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:213)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:365)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:440)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.totalOutcomes(RecordReaderDataSetIterator.java:390)
	at com.javadeeplearningcookbook.app.CSVRecordExample.main(CSVRecordExample.java:54)
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* **Deeplearning4j** version -> 1.0.0-beta3
* **platform information** (OS, etc) -> Windows 7, 64-bit
* **CUDA version, if used** -> NA
* **NVIDIA driver version, if in use** -> NA

#### Contributing

You can use the below gist as reference to code:
https://gist.github.com/rahul-raj/d1c4dc088b94d784f49a6aaf023dbad7 

Let me know if further inputs required. Thank you.

**Comment by AlexDBlack** [comment]
OK, turns out this was a simple one: your data has 7 columns, hence should be indexed 0 to 6 inclusive, but you're indexing 0 to 7 (as if you had 8 total columns).
Runs fine with this:
```DataSetIterator dataSetIterator = new RecordReaderDataSetIterator(transformProcessRecordReader,writableConverter,8,1,6,2,-1,true);```
Note 6 not 7

As an aside, looks like you've got features and labels reversed... this might be what you want?
```
        DataSetIterator dataSetIterator = new RecordReaderDataSetIterator.Builder(transformProcessRecordReader, 8)
                .classification(0, 2)   //Column 0, 2 possible classes
                .build();
```
(You can also do the same with the constructors instnead of the builder)

**Comment by rahul-raj** [comment]
@AlexDBlack 
Thank you very much for the response. The alternate approach that you suggested will suit better in my case. I still got one question. 
![image](https://user-images.githubusercontent.com/517415/52565567-2b842f80-2e2d-11e9-902c-6317efc5cb4a.png)
Are you using the same dataset that I have? For me there are 8 columns in total.
In this case, the index should be still 1 to 7 provided index 0 is output label?

**Comment by AlexDBlack** [comment]
@rahul-raj You can check the output of the transformProcessRecordReader by using .next() on it and looking at the size of the returned list. That has 7 elements when I run your code locally.
