### ISSUE TITLE
DifferentialFunctionClassHolder.getInstance().getInstance("abs") fails due to guava

### ISSUE THREAD

**Issue by dd00f** [deeplearning4j/deeplearning4j#7170]
Environment : 
Windows 10, 
DL4J version 1.0.0-beta3. 
CUDA 9.2
Java version : OpenJDK 11.0.1

When I first tried to run a ComputationGraph fit function, I got the following exception:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at org.nd4j.linalg.api.ops.factory.DefaultOpFactory.createTransform(DefaultOpFactory.java:299)
	at org.nd4j.linalg.api.ops.factory.DefaultOpFactory.createTransform(DefaultOpFactory.java:246)
	at org.nd4j.linalg.lossfunctions.impl.LossL1.scoreArray(LossL1.java:88)
	at org.nd4j.linalg.lossfunctions.impl.LossL1.computeScore(LossL1.java:108)
	at org.nd4j.linalg.lossfunctions.impl.LossMAE.computeScore(LossMAE.java:62)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.computeScore(BaseOutputLayer.java:90)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1395)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1329)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:160)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1149)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1098)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1065)
	at kemet.ai.KemetNeuralNetwork.trainEpoch(KemetNeuralNetwork.java:72)
	at kemet.ai.KemetNeuralNetwork.train(KemetNeuralNetwork.java:55)
	at kemet.util.Coach.runTrainingIteration(Coach.java:273)
	at kemet.util.Coach.learn(Coach.java:212)
	at kemet.data.KemetLearn.main(KemetLearn.java:64)
Caused by: java.lang.NullPointerException
	at org.nd4j.linalg.api.ops.factory.DefaultOpFactory.createTransform(DefaultOpFactory.java:295)
	... 18 more
```

After a bit of investigation, I found that this method kept returning a null value : 
DifferentialFunctionClassHolder.getInstance().getInstance("abs") 

Turns out the introspection done in DifferentialFunctionClassHolder using com.google.common.reflect.ClassPath kept on returning an empty list of classes. I traced this to a similar bug in Guava : 

https://github.com/google/guava/issues/2152

I upgraded guava to version 27.0.1-jre and the problem went away.

The guava version seems to be specified here.

https://github.com/deeplearning4j/deeplearning4j/blob/bffbd9f3bcc881c55c7e70047531b7120d229e6a/pom.xml#L358

Hope this helps.

**Comment by AlexDBlack** [comment]
Thanks for the detailed issue, though this is in part no longer relevant.
DefaultOpFactory was removed entirely here: https://github.com/deeplearning4j/deeplearning4j/pull/6980
https://github.com/deeplearning4j/deeplearning4j/search?q=DefaultOpFactory&unscoped_q=DefaultOpFactory

LossL1 has been updated to use Transforms.abs instead: https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/lossfunctions/impl/LossL1.java#L88

Other than using the workaround of downloading guava, you can also consider using snapshots (though note there are a number of breaking changes there around ND4J datatypes, so you might need to make some modifications to your code to use snapshots) - https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots

Now, I will leave this issue open for now because we use ```DifferentialFunctionClassHolder.getInstance().getInstance(String)``` in a few other places - though I note we haven't run into this anywhere yet. That doesn't mean we won't, however.

https://github.com/deeplearning4j/deeplearning4j/search?q=DifferentialFunctionClassHolder.getInstance%28%29.getInstance&unscoped_q=DifferentialFunctionClassHolder.getInstance%28%29.getInstance

@dd00f Was there anything special about your environment, other than java 11?
i.e., it's just a standard "run in IDE" or "build uberjar with maven shade" type workflow?
Just thinking how to test other similar uses of DifferentialFunctionClassHolder that might reproduce this...

**Comment by dd00f** [comment]
@AlexDBlack I'm currently running this in a relatively recent version of the Eclipse IDE.
