### ISSUE TITLE
java.lang.IllegalStateException: Cannot convert categorical value to integer value for defined schema while using TransformProcessSequenceRecordReader

### ISSUE THREAD

**Issue by rahul-raj** [deeplearning4j/deeplearning4j#7191]
#### Issue Description

Here is the link to full code:
[https://github.com/rahul-raj/Java-Deep-Learning-Cookbook/blob/master/02_Data%20Extraction%2C%20Transform%20and%20Loading/sourceCode/cookbook-app/src/main/java/com/javadeeplearningcookbook/app/recordreaderexamples/SequenceRecordReaderExample.java](https://github.com/rahul-raj/Java-Deep-Learning-Cookbook/blob/master/02_Data%20Extraction%2C%20Transform%20and%20Loading/sourceCode/cookbook-app/src/main/java/com/javadeeplearningcookbook/app/recordreaderexamples/SequenceRecordReaderExample.java)

When I run this code, I get the below error:
```
Exception in thread "main" java.lang.IllegalStateException: Cannot convert categorical value to integer value: input value ("Sex") is not in the list of known categories (state names/categories: [male, female])
	at org.datavec.api.transform.transform.categorical.CategoricalToIntegerTransform.map(CategoricalToIntegerTransform.java:112)
	at org.datavec.api.transform.transform.BaseTransform.mapSequence(BaseTransform.java:57)
	at org.datavec.api.transform.TransformProcess.executeSequenceToSequence(TransformProcess.java:258)
	at org.datavec.api.transform.TransformProcess.executeSequence(TransformProcess.java:285)
	at org.datavec.api.records.reader.impl.transform.TransformProcessSequenceRecordReader.nextSequence(TransformProcessSequenceRecordReader.java:112)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.initializeUnderlyingFromReader(SequenceRecordReaderDataSetIterator.java:167)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.hasNext(SequenceRecordReaderDataSetIterator.java:337)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:358)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:344)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.preLoad(SequenceRecordReaderDataSetIterator.java:394)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.inputColumns(SequenceRecordReaderDataSetIterator.java:381)
	at com.javadeeplearningcookbook.app.recordreaderexamples.SequenceRecordReaderExample.main(SequenceRecordReaderExample.java:47)

```

I get the same error for `trainIterator.totalOutcomes()` as well.

Since schema is defined for both features and labels set,  ideally we should not see this error.  I tried different permutations and combinations like changing `SequenceRecordReaderDataSetIterator.AlignmentMode` hoping that would alter the error, but it stays the same. 

Can you please check on this. 

I have placed the data here if it's needed:
https://drive.google.com/file/d/1T5Y5GOx9mui7h4U_nBO7k1rpI1K4Mclg/view?usp=sharing

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version -> **1.0.0-beta3**
* platform information (OS, etc) -> **Windows 10, 64-bit**
* CUDA version, if used -> **NA**
* NVIDIA driver version, if in use -> **NA**

#### Contributing

You can refer to the earlier mentioned link for the full source code.

**Comment by rahul-raj** [comment]
Well, the solution was easier than I thought.
First line of the data is just plain feature tags.
Line Skip is introduced for both feature set and label set and the issue is resolved.
Thank you @AlexDBlack for the support.
