### ISSUE TITLE
UCISequenceClassificationExample error

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#7211]
When I run this LSTM example on CPU backend, it display error:

o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 4
o.n.n.Nd4jBlas - Number of threads used for BLAS: 4
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 7]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [3.5GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
Exception in thread "main" java.lang.IllegalStateException: C (result) array is not F order or is a view. Nd4j.gemm requires the result array to be F order and not a view. C (result) array: [Rank: 2,Offset: 0 Order: f Shape: [10,1],  stride: [1,10]]
	at org.nd4j.base.Preconditions.throwStateEx(Preconditions.java:641)
	at org.nd4j.base.Preconditions.checkState(Preconditions.java:304)
	at org.nd4j.linalg.factory.Nd4j.gemm(Nd4j.java:980)
	at org.deeplearning4j.nn.layers.recurrent.LSTMHelpers.backpropGradientHelper(LSTMHelpers.java:696)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.backpropGradientHelper(LSTM.java:122)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.backpropGradient(LSTM.java:93)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.calcBackpropGradients(MultiLayerNetwork.java:1826)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2644)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2587)

But it's okay on GPU backend:-)

**Comment by AlexDBlack** [comment]
Thanks for the issue, but this is a duplicate - it has already been fixed.
https://github.com/deeplearning4j/deeplearning4j/issues/6770

Unfortunately there isn't a workaround for 1.0.0-beta3 but the fix is available already on snapshots:
https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots
