### ISSUE TITLE
Rl4j Malmo example

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#7222]
When I want to run Malmo example, I get these messages:

o.d.r.u.DataManager - Created training data directory: C:\Users\Lotus\rl4j-data\25
Exception in thread "main" java.lang.ExceptionInInitializerError
	at rl4j.Malmo.createMDP(Malmo.java:79)
	at rl4j.Malmo.malmoCliffWalk(Malmo.java:87)
	at rl4j.Malmo.main(Malmo.java:58)
Caused by: java.lang.RuntimeException: MALMO_HOME must be set to your Malmo environement. Could not load native library at 'C:\Malmo/Java_Examples/'
	at org.deeplearning4j.malmo.MalmoEnv.<clinit>(MalmoEnv.java:65)
	... 3 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Malmo\Java_Examples\MalmoJava.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.deeplearning4j.malmo.MalmoEnv.<clinit>(MalmoEnv.java:58)
	... 3 more

In fact, I have set all others:
C:\Malmo\Java_Examples>set MALMO_HOME
MALMO_HOME=C:\Malmo

C:\Malmo\Java_Examples>dir
 驱动器 C 中的卷没有标签。
 卷的序列号是 B609-3579

 C:\Malmo\Java_Examples 的目录

2018/03/23  01:37    <DIR>          .
2018/03/23  01:37    <DIR>          ..
2018/03/23  01:29             2,903 JavaExamples_run_mission.jar
2017/11/30  21:41             6,138 JavaExamples_run_mission.java
2018/03/23  01:33         2,186,752 MalmoJava.dll
2018/03/23  01:29            31,365 MalmoJavaJar.jar
               4 个文件      2,227,158 字节
               2 个目录 111,893,004,288 可用字节

Any suggestion for this?

**Comment by saudet** [comment]
Use Dependencies on C:\Malmo\Java_Examples\MalmoJava.dll to find which missing DLL it wants:
https://lucasg.github.io/Dependencies/

**Comment by Charele** [comment]
I use DependenciesGui.exe, it hints I miss the "zlib.dll", 
I search many zlib.dll files on my C: driver, pick up one and copy to the C:\Malmo\Java_Examples\ folder.
DependenciesGui.exe seems to be okay.

But it doesn't work yet.

**Comment by saudet** [comment]
You'll need to either put those DLLs in the PATH or preload them with `System.load()`.
