### ISSUE TITLE
ubuntu18.04 java.lang.UnsatisfiedLinkError: no nd4jcuda in java.library.path

### ISSUE THREAD

**Issue by cqiaoYc** [deeplearning4j/deeplearning4j#7238]
#### Issue Description
$ java -jar NeuroDl4j-1.0-bin.jar
20:07:22.598 [main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.jita.concurrency.CudaAffinityManager.getNumberOfDevices(CudaAffinityManager.java:201)
	at org.nd4j.jita.constant.ConstantProtector.purgeProtector(ConstantProtector.java:56)
	at org.nd4j.jita.constant.ConstantProtector.<init>(ConstantProtector.java:49)
	at org.nd4j.jita.constant.ConstantProtector.<clinit>(ConstantProtector.java:37)
	at org.nd4j.jita.constant.ProtectedCudaConstantHandler.<clinit>(ProtectedCudaConstantHandler.java:64)
	at org.nd4j.jita.constant.CudaConstantHandler.<clinit>(CudaConstantHandler.java:33)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5549)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5482)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:215)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:683)
	at com.cq.neurodl4j.rnn.RnnEvolutionOptimizer.getNetConfig(RnnEvolutionOptimizer.java:120)
	at com.cq.neurodl4j.rnn.RnnEvolutionOptimizer.main(RnnEvolutionOptimizer.java:70)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:68)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:36)
	... 14 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1258)
	at org.bytedeco.javacpp.Loader.load(Loader.java:999)
	at org.bytedeco.javacpp.Loader.load(Loader.java:891)
	at org.nd4j.nativeblas.Nd4jCuda.<clinit>(Nd4jCuda.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:950)
	at org.bytedeco.javacpp.Loader.load(Loader.java:891)
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.<clinit>(Nd4jCuda.java:409)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:46)
	... 15 more
Caused by: java.lang.UnsatisfiedLinkError: no nd4jcuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1258)
	at org.bytedeco.javacpp.Loader.load(Loader.java:977)
	... 25 more

check cudnn:
 
$ function lib_installed() { /sbin/ldconfig -N -v $(sed 's/:/ /' <<< $LD_LIBRARY_PATH) 2>/dev/null | grep $1; }
cqiao@cqiao-PC:~/app$ function check() { lib_installed $1 && echo "$1 is installed" || echo "ERROR: $1 is NOT installed"; }
cqiao@cqiao-PC:~/app$ check libcudnn
	libcudnn.so.7 -> libcudnn.so.7.3.1	
libcudnn is installed

#### Version Information
<dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-cuda-10.0</artifactId>          
            <version>1.0.0-beta3</version>            
        </dependency>
Dev OS: win10
Run Os: ubuntu18.04

* CUDA version, 10.0.130
* NVIDIA driver version, NVIDIA-Linux-x86_64-418.43
cudnn version, libcudnn7_7.3.1.20-1+cuda10.0_amd64

**Comment by raver119** [comment]
show your pom.xml please

**Comment by cqiaoYc** [comment]
<dependencies>
        
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
     
        
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-cuda-10.0</artifactId>          
            <version>${dl4j.version}</version>            
        </dependency>
        
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>             

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-core</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

**Comment by saudet** [comment]
> org.deeplearning4j deeplearning4j-cuda-10.0 1.0.0-beta3 Dev OS: win10 Run Os: ubuntu18.04 
Also add nd4j-cuda-10.0-platform to get binaries for ND4J for both platforms.
