### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by hanbaoan123** [deeplearning4j/deeplearning4j#7283]
#### Issue Description

java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.create(DefaultDataBufferFactory.java:309)
	at org.nd4j.linalg.factory.Nd4j.createTypedBuffer(Nd4j.java:1602)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:350)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.trueScalar(BaseNDArrayFactory.java:1330)
	at org.nd4j.linalg.factory.Nd4j.scalar(Nd4j.java:5818)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4807)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4252)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:287)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.norm2(BaseNDArray.java:4809)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.norm2Number(BaseNDArray.java:1284)
	at org.nd4j.linalg.learning.regularization.L2Regularization.score(L2Regularization.java:63)
	at org.deeplearning4j.nn.layers.BaseLayer.calcRegularizationScore(BaseLayer.java:358)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.calcRegularizationScore(MultiLayerNetwork.java:2921)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2642)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2580)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:160)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fitHelper(MultiLayerNetwork.java:2209)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:2167)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:2154)
	at org.deeplearning4j.rl4j.network.dqn.DQN.fit(DQN.java:62)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j 1.0.0-SNAPSHOT

This is the error log.
[dl4j-memory-crash-dump-1552374455841_90.txt](https://github.com/deeplearning4j/deeplearning4j/files/2955592/dl4j-memory-crash-dump-1552374455841_90.txt)

**Comment by raver119** [comment]
This is known problem and WIP: https://github.com/deeplearning4j/deeplearning4j/issues/7125
