### ISSUE TITLE
java.lang.Thread.State: BLOCKED (on object monitor) at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:546)

### ISSUE THREAD

**Issue by zoe27** [deeplearning4j/deeplearning4j#7294]
#### Issue Description

In my system , the dl4j is predict word intention on line. but it offen not worked. When I use jastack command to get the jvm information , and I got this as bellow:
java.lang.Thread.State: BLOCKED (on object monitor)
        at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:546)
        - waiting to lock <0x00000005e30f3708> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
        at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
        at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
        at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
        at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:41)
        at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:218)
        at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:192)
        at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:153)
        at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:160)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1317)
        at org.nd4j.linalg.api.ndarra
y.BaseNDArray.<init>(BaseNDArray.java:390)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:632)
        at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:281)
        at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:351)
        at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1376)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3701)

Is it blocked in the thread ? And how can I solve this problem ?

**Comment by raver119** [comment]
what's your dl4j/nd4j version?

**Comment by zoe27** [comment]
The version is 1.0.0 Alpha

**Comment by raver119** [comment]
please upgrade to 1.0.0-beta3, lots of stuff was changed/fixed/improved since alpha

**Comment by zoe27** [comment]
But why this occured  ? Can I find out the reason ?

**Comment by zoe27** [comment]
Now I find another information , Thread 606 locked the memory address , then it sleep and did not release the addreess, so the others wait to lock all the time。 

"pool-2-thread-606" #1225 prio=5 os_prio=0 tid=0x00007fc70000f000 nid=0x96b7 sleeping[0x00007fac08788000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:557)
        - locked <0x00000005e30f3708> (a java.lang.Class for org.bytedeco.javacpp.Pointer$DeallocatorThread)
        at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
        at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
        at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
        at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:41)
        at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:218)
        at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:192)
        at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:153)
        at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFlo
at(DefaultDataBufferFactory.java:160)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1317)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:390)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:632)
        at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:281)
        at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:351)
        at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1376)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3701)

**Comment by saudet** [comment]
@zoe27 The garbage collector is probably getting flooded. Try to reduce the rate at which objects get created.
