### ISSUE TITLE
KMeansClustering

### ISSUE THREAD

**Issue by amithrc** [deeplearning4j/deeplearning4j#7298]
#### Issue Description

K-means clustering failing and here is the Exception
Followed this tutorial https://gist.github.com/rohanar/8b10e57743881a860099
Cluster Centers:
0fc7feebbcecaf185a8d667dc44a1ef82b2507a0
6019abc315e3afd5250d01a8897bee49b1646249
ab1b4b7b8281f43fa23e3d16880c9e36483291cb
2b66112b9092a962ccd9b32870396df2c2d3a501
f3f9b55478a98f01321ee33f8057bf3ed07a38cb
.[[    0.2235,   -0.2980,   -0.3537,   -0.0738,   -0.0899,    0.0553,    0.2701,    0.0753,    0.2906,   -0.0754,    0.2042,   -0.0387,    0.6108,    0.1624,   -0.0198,   -0.1726,    0.0660,   -0.0279,    0.0935,    0.0314,   -0.2968,   -0.2740,    0.0035,    0.4718,    0.1108,    0.8545,   -0.0484,   -0.1711,    0.0151,    0.3017,   -0.3156,   -0.1690,    0.2955,    0.0221,   -0.0097,    0.2650,   -0.1778,   -0.2640,   -0.4308,    0.1030,    0.1140,   -0.4149,    0.2678,    0.3372,   -0.0103,    0.0768,    0.3691,    0.1172,   -0.2931,   -0.1861]]
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: Number of columns should be positive for new INDArray
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3336)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3301)
	at org.deeplearning4j.clustering.algorithm.BaseClusteringAlgorithm.initClusters(BaseClusteringAlgorithm.java:146)
	at org.deeplearning4j.clustering.algorithm.BaseClusteringAlgorithm.applyTo(BaseClusteringAlgorithm.java:88)
	at main.java.clustering.ClusteringRanker.getClusters(ClusteringRanker.java:75)
	at main.java.clustering.ClusteringRanker.lambda$doCluster$0(ClusteringRanker.java:98)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at main.java.clustering.ClusteringRanker.doCluster(ClusteringRanker.java:93)
	at main.java.runner.SearchRunner.run(SearchRunner.java:272)
	at main.java.ProjectRunner.main(ProjectRunner.java:31)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 1.0.0-beta3
* platform information (OS, etc) Windows 10 64 bit
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

Not at this moment

Aha! Link: https://skymindai.aha.io/features/DL4J-1

**Comment by alexanderst** [comment]
Fixed for KMeans were applied and merged.
