### ISSUE TITLE
org.deeplearning4j.exception.DL4JInvalidInputException

### ISSUE THREAD

**Issue by Anriod** [deeplearning4j/deeplearning4j#7306]
including, if relevant:

* Deeplearning4j version : 1.0.0 SNAPSHOT
ND4J VERSION - 1.0.0 SNAPSHOT
OS: Android (7.0)
Hello,
When I'm trying to run my model I get a Invalid Input Exception but I know for a fact ( I triple checked) that my model is configured for the input shape I'm passing. For a previous configuration of my model which took in data in the shape (1,65,6) everything worked fine however when I switched to a shape (1,70,6) this error started popping up.  It seems to be expecting (1,6,6) which it should not. 
```
2019-03-17 18:36:50.708 12244-12244/com.anirudh.mercury W/System.err: org.deeplearning4j.exception.DL4JInvalidInputException: Received input with size(1) = 70 (input array shape = [1, 70, 6]); input.size(1) must match layer nIn size (nIn = 6)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at org.deeplearning4j.nn.layers.recurrent.LSTMHelpers.activateHelper(LSTMHelpers.java:187)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at org.deeplearning4j.nn.layers.recurrent.LSTM.activateHelper(LSTM.java:164)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at org.deeplearning4j.nn.layers.recurrent.LSTM.activate(LSTM.java:141)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at org.deeplearning4j.nn.layers.recurrent.LastTimeStepLayer.activate(LastTimeStepLayer.java:80)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:110)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at org.deeplearning4j.nn.graph.ComputationGraph.outputOfLayersDetached(ComputationGraph.java:2327)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1717)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1676)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1606)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at com.anirudh.mercury.Detect.setup(Detect.java:105)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at com.anirudh.mercury.Detect.onSensorChanged(Detect.java:83)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:710)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:323)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at android.os.Looper.loop(Looper.java:136)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6290)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
2019-03-17 18:36:50.709 12244-12244/com.anirudh.mercury W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
This my model config : 
`{"class_name": "Model", "config": {"name": "model_29", "layers": [{"name": "input_31", "class_name": "InputLayer", "config": {"batch_input_shape": [null, 70, 6], "dtype": "float32", "sparse": false, "name": "input_31"}, "inbound_nodes": []}, {"name": "lstm_29", "class_name": "LSTM", "config": {"name": "lstm_29", "trainable": true, "return_sequences": false, "return_state": false, "go_backwards": false, "stateful": false, "unroll": false, "units": 100, "activation": "tanh", "recurrent_activation": "hard_sigmoid", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "recurrent_initializer": {"class_name": "Orthogonal", "config": {"gain": 1.0, "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "unit_forget_bias": true, "kernel_regularizer": null, "recurrent_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "recurrent_constraint": null, "bias_constraint": null, "dropout": 0.0, "recurrent_dropout": 0.0, "implementation": 1}, "inbound_nodes": [[["input_31", 0, 0, {}]]]}, {"name": "dense_57", "class_name": "Dense", "config": {"name": "dense_57", "trainable": true, "units": 7, "activation": "tanh", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}, "inbound_nodes": [[["lstm_29", 0, 0, {}]]]}, {"name": "dense_58", "class_name": "Dense", "config": {"name": "dense_58", "trainable": true, "units": 1, "activation": "sigmoid", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "bias_initial; line: 1, column: 4001]`

**Comment by AlexDBlack** [comment]
Looks like you are just passing your sequence data with the wrong order.
DL4J RNN layers use ```[Minibatch,nIn,sequenceLength]``` format by default. You are incorrectly passing in ```[minibatch,sequenceLength,nIn]``` which is why when you use [1,6,6] it no longer gives the error.

You can see more information about RNN data layout in DL4J here: https://deeplearning4j.org/docs/latest/deeplearning4j-nn-recurrent#basics
