### ISSUE TITLE
SkipGram NullPointerException

### ISSUE THREAD

**Issue by sazame** [deeplearning4j/deeplearning4j#7314]
#### Issue Description
Sorry, I'm bad at English. So i use google translation.

I tried to analyze using SkipGram using yesterday's deeplearning4j latest Snapshot. The following error occurred at that time.

```
Exception in thread "VectorCalculationsThread 0" java.lang.RuntimeException: java.lang.NullPointerException
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1340)
Caused by: java.lang.NullPointerException
	at org.nd4j.jita.allocator.impl.AtomicAllocator.synchronizeHostData(AtomicAllocator.java:350)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.getHostPointer(AtomicAllocator.java:327)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2446)
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:533)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1315)
```

Perhaps the INDArray instance created by NDArray.empty (DataType dataType) has a data property of null ?
When creating an instance of SkipGramRound, I think that you have created an inferenceVector in inputArguments using NDArray.empty (DataType dataType).
It seems that the NullPointerException has occurred when an INDArray instance whose data property is null passes through method (synchronizeHostData(INDArray array)).

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
yesterday's snapshot
* platform information (OS, etc)
Windows10
* CUDA version, if used
Cuda10.0
* NVIDIA driver version, if in use
sorry, I have not confirmed yet

**Comment by raver119** [comment]
Please try to run the same code with CPU backend, instead of CUDA to see if it's reproducible there.

**Comment by sazame** [comment]
I tried, but the same error did not occur.

**Comment by raver119** [comment]
Tyvm, we'll fix it asap.

**Comment by sazame** [comment]
I tried, but the same error did not occur.
Thank you in advance.

**Comment by raver119** [comment]
Fix was merged yesterday.

**Comment by sazame** [comment]
I just tried it and confirmed that it actually works!
Thank you very much.
