### ISSUE TITLE
FP16 precision causing crashes in Android

### ISSUE THREAD

**Issue by RobrechtP** [deeplearning4j/deeplearning4j#7315]
#### Issue Description
Trying to use FP16 precision in Android causes crashes in certain methods, while using the standard FLOAT precision, no problems are encountered. For example:

        Nd4j.setDataType(DataType.HALF);
        DataSetIterator dataIter = new RecordReaderDataSetIterator(recordReader, batchSize, 1, outputNum);
        DataNormalization scalar = new ImagePreProcessingScaler(0, 1);
        scalar.fit(dataIter);
        dataIter.setPreProcessor(scalar);
        network.fit(dataIter);

the MultiLayerNetwork.fit() method crashes caused by
java.lang.IllegalStateException: Cannot use putScalar(int,int,double) on a rank 3 INDArray

Or after creating a MultiLayerNetwork and saving it:

     Nd4j.setDataType(DataType.HALF);
     File file = new File(Environment.getExternalStorageDirectory() + "/" + networkName + ".zip");
     OutputStream outputStream = new FileOutputStream(file);
     ModelSerializer.writeModel(network, outputStream, true);

The   ModelSerializer.writeModel() method crashes caused by
java.lang.UnsupportedOperationException

It does not seem to matter where I call the Nd4j.setDataType(DataType.HALF). The errors above occur only when in DataType.HALF mode. When this mode is not activated, everything behaves as expected.

#### Version Information

Deeplearning4j version 1.0.0-SNAPSHOT in Android

#### Stack trace 1

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.example.robrecht.mnistest, PID: 17838
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:365)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Cannot use putScalar(int,int,double) on a rank 3 INDArray
        at org.datavec.image.recordreader.BaseImageRecordReader.next(BaseImageRecordReader.java:257)
        at org.datavec.image.recordreader.BaseImageRecordReader.nextRecord(BaseImageRecordReader.java:495)
        at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.initializeUnderlying(RecordReaderDataSetIterator.java:220)
        at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.resetSupported(RecordReaderDataSetIterator.java:408)
        at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.<init>(AsyncDataSetIterator.java:130)
        at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.<init>(AsyncDataSetIterator.java:114)
        at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.<init>(AsyncDataSetIterator.java:109)
        at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.<init>(AsyncDataSetIterator.java:94)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fitHelper(MultiLayerNetwork.java:1586)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1573)
        at com.example.robrecht.mnistest.MNISTTester.trainNetwork(MNISTTester.java:214)
        at com.example.robrecht.mnistest.MNISTTester$AsyncTaskTrainer.doInBackground(MNISTTester.java:304)
        at com.example.robrecht.mnistest.MNISTTester$AsyncTaskTrainer.doInBackground(MNISTTester.java:294)
        at android.os.AsyncTask$2.call(AsyncTask.java:345)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:784) 
     Caused by: java.lang.IllegalStateException: Cannot use putScalar(int,int,double) on a rank 3 INDArray
        at org.nd4j.linalg.api.ndarray.BaseNDArray.putScalar(BaseNDArray.java:1517)
        at org.datavec.image.loader.NativeImageLoader.fillNDArray(NativeImageLoader.java:480)
        at org.datavec.image.loader.NativeImageLoader.transformImage(NativeImageLoader.java:618)
        at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:538)
        at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:252)
        at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:232)
        at org.datavec.image.recordreader.BaseImageRecordReader.next(BaseImageRecordReader.java:240)
        at org.datavec.image.recordreader.BaseImageRecordReader.nextRecord(BaseImageRecordReader.java:495) 
        at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.initializeUnderlying(RecordReaderDataSetIterator.java:220) 
        at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.resetSupported(RecordReaderDataSetIterator.java:408) 
        at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.<init>(AsyncDataSetIterator.java:130) 
        at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.<init>(AsyncDataSetIterator.java:114) 
        at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.<init>(AsyncDataSetIterator.java:109) 
        at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.<init>(AsyncDataSetIterator.java:94) 
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fitHelper(MultiLayerNetwork.java:1586) 
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1573) 
        at com.example.robrecht.mnistest.MNISTTester.trainNetwork(MNISTTester.java:214) 
        at com.example.robrecht.mnistest.MNISTTester$AsyncTaskTrainer.doInBackground(MNISTTester.java:304) 
        at com.example.robrecht.mnistest.MNISTTester$AsyncTaskTrainer.doInBackground(MNISTTester.java:294) 
        at android.os.AsyncTask$2.call(AsyncTask.java:345) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:784) 

#### Stack trace 2

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.example.robrecht.mnistest, PID: 16098
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:365)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.UnsupportedOperationException
        at org.nd4j.linalg.api.buffer.BaseDataBuffer.getShort(BaseDataBuffer.java:1297)
        at org.nd4j.linalg.api.buffer.BaseDataBuffer.write(BaseDataBuffer.java:1999)
        at org.nd4j.linalg.factory.Nd4j.write(Nd4j.java:2685)
        at org.deeplearning4j.util.ModelSerializer.writeModel(ModelSerializer.java:178)
        at org.deeplearning4j.util.ModelSerializer.writeModel(ModelSerializer.java:119)
        at com.example.robrecht.mnistest.MNISTTester.saveNetwork(MNISTTester.java:112)
        at com.example.robrecht.mnistest.MNISTTester.networkCreator(MNISTTester.java:156)
        at com.example.robrecht.mnistest.MNISTTester$asyncCreator.doInBackground(MNISTTester.java:328)
        at com.example.robrecht.mnistest.MNISTTester$asyncCreator.doInBackground(MNISTTester.java:323)
        at android.os.AsyncTask$2.call(AsyncTask.java:345)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:784)

**Comment by treo** [comment]
Can you add the full stack traces?

**Comment by RobrechtP** [comment]
Added stack traces

**Comment by raver119** [comment]
> Caused by: java.lang.UnsupportedOperationException at org.nd4j.linalg.api.buffer.BaseDataBuffer.getShort(BaseDataBuffer.java:1297)

Thanks, that helps

**Comment by raver119** [comment]
Issue should be fixed now. Please try again as soon as snapshots get rebuilt.

**Comment by raver119** [comment]
Another issue is in datavec. NativeImageLoader misses support for HalfIndexer. Will fix it too

**Comment by raver119** [comment]
Fixed once again
