### ISSUE TITLE
FP16 precision causing MultiLayerNetwork.fit() crash Android

### ISSUE THREAD

**Issue by RobrechtP** [deeplearning4j/deeplearning4j#7331]
####Issue Description
Trying to use FP16 precision in Android causes crashes in the MultiLayerNetwork.fit() method, while using the standard FLOAT precision, no problems are encountered. For example:

    Nd4j.setDataType(DataType.HALF);
    DataSetIterator dataIter = new RecordReaderDataSetIterator(recordReader, batchSize, 1, outputNum);
    DataNormalization scalar = new ImagePreProcessingScaler(0, 1);
    scalar.fit(dataIter);
    dataIter.setPreProcessor(scalar);
    network.fit(dataIter);
the MultiLayerNetwork.fit() method crashes

####Version Information
Deeplearning4j version 1.0.0-SNAPSHOT in Android

####Stack trace

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.example.robrecht.mnistest, PID: 6019
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:365)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.UnsupportedOperationException
        at org.nd4j.linalg.cpu.nativecpu.blas.CpuLevel3.hgemm(CpuLevel3.java:44)
        at org.nd4j.linalg.api.blas.impl.BaseLevel3.gemm(BaseLevel3.java:74)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:3727)
        at org.deeplearning4j.nn.layers.BaseLayer.preOutputWithPreNorm(BaseLayer.java:318)
        at org.deeplearning4j.nn.layers.BaseLayer.preOutput(BaseLayer.java:293)
        at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:339)
        at org.deeplearning4j.nn.layers.AbstractLayer.activate(AbstractLayer.java:259)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.ffToLayerActivationsInWs(MultiLayerNetwork.java:1099)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2622)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2580)
        at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:160)
        at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
        at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fitHelper(MultiLayerNetwork.java:1653)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1573)
        at com.example.robrecht.mnistest.MNISTTester.trainNetwork(MNISTTester.java:213)
        at com.example.robrecht.mnistest.MNISTTester$AsyncTaskTrainer.doInBackground(MNISTTester.java:303)
        at com.example.robrecht.mnistest.MNISTTester$AsyncTaskTrainer.doInBackground(MNISTTester.java:293)
        at android.os.AsyncTask$2.call(AsyncTask.java:345)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:784)

**Comment by raver119** [comment]
That just means absence of gemm for float16/bfloat16 on nd4j-native backend.

**Comment by raver119** [comment]
p.s. what's your android hardware? can you give me exact cpu model name?

**Comment by RobrechtP** [comment]
I am attempting to run it on a Huawei P10. Not sure about the CPU

**Comment by raver119** [comment]
HiSilicon Kirin 960 (16 nm). ARM in other words. Thanks
