### ISSUE TITLE
Exceptions in DL4J examples

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#7361]
CnnSentenceClassificationExample
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: Invalid shape: Requested INDArray shape [1, 1, 0, 300] contains dimension size values < 1 (all dimensions must be 1 or more)
    at org.nd4j.linalg.factory.Nd4j.checkShapeValues(Nd4j.java:4399)
    at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4354)
    at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3799)
    at org.deeplearning4j.iterator.CnnSentenceDataSetIterator.loadSingleSentence(CnnSentenceDataSetIterator.java:161)
    at org.deeplearning4j.examples.convolution.sentenceclassification.CnnSentenceClassificationExample.main(CnnSentenceClassificationExample.java:143)

Word2VecSentimentRNN
Exception in thread "ADSI prefetch thread" java.lang.RuntimeException: org.nd4j.linalg.exception.ND4JIllegalStateException: Invalid shape: Requested INDArray shape [64, 300, 0] contains dimension size values < 1 (all dimensions must be 1 or more)
    at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:445)
Caused by: org.nd4j.linalg.exception.ND4JIllegalStateException: Invalid shape: Requested INDArray shape [64, 300, 0] contains dimension size values < 1 (all dimensions must be 1 or more)
    at org.nd4j.linalg.factory.Nd4j.checkShapeValues(Nd4j.java:4399)
    at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4354)

**Comment by AlexDBlack** [comment]
I've been unable to reproduce this.
Can you try deleting ```dl4j_w2vSentiment/``` in your temp directory? (whatever directory is returned by ```System.getProperty("java.io.tmpdir")```)
I suspect that somehow your data got corrupted somehow, and that's where the zero shape comes from.

**Comment by AlexDBlack** [comment]
Both examples are still running fine for me. This still looks like data corruption issue as mentioned in previous comment.
