### ISSUE TITLE
ND4J CUDA: INDArray.shapeDescriptor() can return null

### ISSUE THREAD

**Issue by rnett** [deeplearning4j/deeplearning4j#7381]
I'm getting a NPE from my samediff layer, specifically when doing training.

Stacktrace:
```kotlin
java.lang.NullPointerException
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:645)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:37)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:249)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:3333)
	at org.deeplearning4j.nn.layers.samediff.SameDiffLayer.activate(SameDiffLayer.java:89)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:110)
	at org.deeplearning4j.nn.graph.ComputationGraph.ffToLayerActivationsInWS(ComputationGraph.java:2091)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1352)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1321)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:160)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1145)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1095)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1062)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:996)
```

Relevant code:
```java
if(currOutput == null || !currOutput.shapeDescriptor().equals(reqShape) || currOutput.isEmpty() != reqShape.isEmpty() || isLoop){
    INDArray out;
    try(MemoryWorkspace ws = Nd4j.getMemoryManager().scopeOutOfWorkspaces()) {
        //TODO Proper workspace support will be added to SameDiff later
        out = Nd4j.create(reqShape, false);
    }
    customOp.setOutputArgument(i, out);
}
```

Specifically, `currOutput.shapeDescriptor()` is null.

Dl4j: 1.0.0-SNAPSHOT
Windows 10
CUDA 10, cuDNN

**Comment by rnett** [comment]
This may be related to the fact that `tensorMmul` (which I'm using) doesn't define a `calculateOutputDataTypes()` method.

**Comment by AlexDBlack** [comment]
No, that's a cuda-specific issue, not a SameDiff issue. There was an issue open for this at one point but I can't find it...

Anyway, this is sufficient to reproduce:
```
    @Test
    public void testLongShapeDescriptor(){
        Nd4j.setDefaultDataTypes(DataType.DOUBLE, DataType.DOUBLE);
        INDArray arr = Nd4j.create(new float[]{1,2,3});

        LongShapeDescriptor lsd = arr.shapeDescriptor();
        assertNotNull(lsd);     //Fails here on CUDA, OK on native/cpu
    }
```

cc @raver119

**Comment by raver119** [comment]
Fixed.
