### ISSUE TITLE
Nd4j or SameDiff causes error when calculating gradients a single mul

### ISSUE THREAD

**Issue by rnett** [deeplearning4j/deeplearning4j#7421]
#### Issue Description

When calculating gradients for a single `mul` operation, a shape error is thrown.  I'm not sure if the error is in Libnd4j or SameDiff.

To reproduce:
```java
@Test
public void test2() {
    SameDiff SD = SameDiff.create();
    SDVariable a = SD.reshape("a", SD.linspace("at", 1, 15, 15), 3, 5);//.add(1);
    SDVariable b = SD.one("b", 3, 5);//.add(3);

    SDVariable out = a.mul(b);//.get(SDIndex.interval(0, 3), SDIndex.interval(0, 5 ));

    System.out.println(Arrays.toString(out.eval().shape()));
    out.eval();

    SD.execBackwards(null, Lists.asList("a", new String[]{}));
    System.out.println(out.eval());
    System.out.println(SD.grad("a").eval()); // <-- error here
}
```

Note that you can uncomment the get, and it works fine, even though the get doesn't really do anything.

This gives the error:
```java
Error at [C:/.../deeplearning4j/libnd4j/include/ops/declarable/generic/broadcastable/multiply.cpp:77:0]:
MULTIPLY_BP OP: wrong shape of next epsilon array (dLdOut), expected is [3, 5], but got [] instead !
[main] ERROR org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner - Failed to execute op multiply_bp. Attempted to execute with 3 inputs, 2 outputs, 0 targs and 0 iargs. Inputs: [(FLOAT,[3,5],c), (FLOAT,[3,5],c), (FLOAT,[],c)]. Outputs: [(FLOAT,[3,5],c), (FLOAT,[3,5],c)]. tArgs: -. iArgs: - - Please see above message (printed out from c++) for a possible cause of error.

java.lang.RuntimeException: Op validation failed

	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOp(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1679)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:449)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:37)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:250)
	at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:3357)
	at org.nd4j.autodiff.samediff.SDVariable.eval(SDVariable.java:1773)
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: SNAPSHOT
* platform information (OS, etc): Windows 10
* CPU Backend

**Comment by AlexDBlack** [comment]
This is the same issue that you've already flagged twice:
https://github.com/deeplearning4j/deeplearning4j/issues/7405
https://github.com/deeplearning4j/deeplearning4j/issues/7401 (other than the reduce_sqnorm_bp)

**Comment by rnett** [comment]
Is it?  Oops.  I wasn't sure if it was a SameDiff thing or a thing for the individual ops.

**Comment by AlexDBlack** [comment]
Np, that's fine. I know what's up here and will fix it soon.
