### ISSUE TITLE
NPE with windows CUDA 7.5

### ISSUE THREAD

**Issue by capdevc** [deeplearning4j/deeplearning4j#746]
running the snapshot w2v example under windows with cuda 7.5:
```
o.d.m.w.Word2Vec - Words so far 12 with alpha at 0.024999454872531027
o.d.p.Parallelization - Error occurred processing data
java.lang.NullPointerException: null
at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.getDevicePointer(BaseCudaDataBuffer.java:337) ~[nd4j-jcublas-7.5-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.jcublas.CublasPointer.<init>(CublasPointer.java:146) ~[nd4j-jcublas-7.5-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.jcublas.blas.JcublasLevel1.sdot(JcublasLevel1.java:37) ~[nd4j-jcublas-7.5-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.api.blas.impl.BaseLevel1.dot(BaseLevel1.java:33) ~[nd4j-api-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.factory.BaseBlasWrapper.dot(BaseBlasWrapper.java:185) ~[nd4j-api-0.4-rc4.4-SNAPSHOT.jar:na]
o.d.p.Parallelization - Error occurred processing data
java.lang.NullPointerException: null
at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.getDevicePointer(BaseCudaDataBuffer.java:337) ~[nd4j-jcublas-7.5-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.jcublas.CublasPointer.<init>(CublasPointer.java:146) ~[nd4j-jcublas-7.5-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.jcublas.blas.JcublasLevel1.sdot(JcublasLevel1.java:37) ~[nd4j-jcublas-7.5-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.api.blas.impl.BaseLevel1.dot(BaseLevel1.java:33) ~[nd4j-api-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.factory.BaseBlasWrapper.dot(BaseBlasWrapper.java:185) ~[nd4j-api-0.4-rc4.4-SNAPSHOT.jar:na]
o.d.p.Parallelization - Error occurred processing data
java.lang.NullPointerException: null
at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.getDevicePointer(BaseCudaDataBuffer.java:337) ~[nd4j-jcublas-7.5-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.jcublas.CublasPointer.<init>(CublasPointer.java:146) ~[nd4j-jcublas-7.5-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.jcublas.blas.JcublasLevel1.sdot(JcublasLevel1.java:37) ~[nd4j-jcublas-7.5-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.api.blas.impl.BaseLevel1.dot(BaseLevel1.java:33) ~[nd4j-api-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.factory.BaseBlasWrapper.dot(BaseBlasWrapper.java:185) ~[nd4j-api-0.4-rc4.4-SNAPSHOT.jar:na]
o.d.p.Parallelization - Error occurred processing data
java.lang.NullPointerException: null
at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.getDevicePointer(BaseCudaDataBuffer.java:337) ~[nd4j-jcublas-7.5-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.jcublas.CublasPointer.<init>(CublasPointer.java:146) ~[nd4j-jcublas-7.5-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.jcublas.blas.JcublasLevel1.sdot(JcublasLevel1.java:37) ~[nd4j-jcublas-7.5-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.api.blas.impl.BaseLevel1.dot(BaseLevel1.java:33) ~[nd4j-api-0.4-rc4.4-SNAPSHOT.jar:na]
at org.nd4j.linalg.factory.BaseBlasWrapper.dot(BaseBlasWrapper.java:185) ~[nd4j-api-0.4-rc4.4-SNAPSHOT.jar:na]
o.d.p.Parallelization - Error occurred processing data
```
it continues to run and appears to be working, but is constantly throwing this exception.

same code runs fine on a mac with the same version of cuda.

**Comment by nyghtowl** [comment]
Cuda being completely revised and newer version to be released soon. Please post if any issues occur after next release.
