### ISSUE TITLE
SharedTrainingMaster: ND4JIllegalStateException: originalLength [0] stored in encoded array doesn't match target length [24266]

### ISSUE THREAD

**Issue by daanvdn** [deeplearning4j/deeplearning4j#7494]
I'm creating this ticket as per @raver119 's request:

I'm training on a spark cluster with 4 slaves (all GPU machines with each 4 GPUs -- type Nvidia Tesla p40 with 24gb each).
I'm trying to fit a `SparkDl4jMultiLayer` using the `org.deeplearning4j.spark.parameterserver.training.SharedTrainingMaster`

During fitting I encounter the following error:
```
2019-04-08 14:26:28 WARN  SharedTrainingWrapper:478 - Exception encountered during fit operation
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: org.nd4j.linalg.exception.ND4JIllegalStateException: originalLength [0] stored in encoded array doesn't match target length [24266]
	at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:592)
	at org.deeplearning4j.spark.parameterserver.pw.SharedTrainingWrapper.run(SharedTrainingWrapper.java:455)
	at org.deeplearning4j.spark.parameterserver.functions.SharedFlatMapPathsAdapter.call(SharedFlatMapPaths.java:94)
	at org.deeplearning4j.spark.parameterserver.functions.SharedFlatMapPathsAdapter.call(SharedFlatMapPaths.java:62)
	at org.datavec.spark.transform.BaseFlatMapFunctionAdaptee.call(BaseFlatMapFunctionAdaptee.java:40)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.nd4j.linalg.exception.ND4JIllegalStateException: originalLength [0] stored in encoded array doesn't match target length [24266]
	at org.deeplearning4j.parallelism.trainer.DefaultTrainer.waitTillRunning(DefaultTrainer.java:463)
	at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:590)
	... 24 more
Caused by: java.lang.RuntimeException: org.nd4j.linalg.exception.ND4JIllegalStateException: originalLength [0] stored in encoded array doesn't match target length [24266]
	at org.deeplearning4j.optimize.solvers.accumulation.EncodedGradientsAccumulator.applyUpdate(EncodedGradientsAccumulator.java:341)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:59)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fitHelper(MultiLayerNetwork.java:2219)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:2177)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:2240)
	at org.deeplearning4j.parallelism.trainer.DefaultTrainer.fit(DefaultTrainer.java:236)
	at org.deeplearning4j.parallelism.trainer.DefaultTrainer.run(DefaultTrainer.java:385)
	... 3 more
Caused by: org.nd4j.linalg.exception.ND4JIllegalStateException: originalLength [0] stored in encoded array doesn't match target length [24266]
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.thresholdDecode(CudaExecutioner.java:2005)
	at org.deeplearning4j.optimize.solvers.accumulation.IndexedTail.smartDecompress(IndexedTail.java:339)
	at org.deeplearning4j.optimize.solvers.accumulation.IndexedTail.drainTo(IndexedTail.java:282)
	at org.deeplearning4j.optimize.solvers.accumulation.IndexedTail.drainTo(IndexedTail.java:194)
	at org.deeplearning4j.optimize.solvers.accumulation.EncodedGradientsAccumulator.applyUpdate(EncodedGradientsAccumulator.java:315)
	... 10 more
2019-04-08 14:26:28 ERROR ParallelWrapper:129 - Uncaught exception: java.lang.RuntimeException: java.lang.RuntimeException: org.nd4j.linalg.exception.ND4JIllegalStateException: originalLength [0] stored in encoded array doesn't match target length [24266]
2019-04-08 14:26:28 ERROR ParallelWrapper:129 - Uncaught exception: java.lang.RuntimeException: java.lang.RuntimeException: org.nd4j.linalg.exception.ND4JIllegalStateException: originalLength [0] stored in encoded array doesn't match target length [24266]
```

As far as spark-configuration is concerned, my setup is as follows:

1) `spark-defaults.conf`: has the following properties:
```
    spark.core.connection.ack.wait.timeout 600s
    spark.executor.heartbeatInterval 300
    spark.network.timeout 301
    spark.worker.cleanup.enabled true
    spark.worker.cleanup.interval 600
    spark.storage.cleanupFilesAfterExecutorExit      true
```

2) `spark-env.sh` has:
`SPARK_WORKER_INSTANCES=1`
`SPARK_WORKER_CORES=4`

I've uploaded the code I'm running to [GitHub](https://github.com/daanvdn/dl4j-azure-minimal-example).  The main class is <https://github.com/daanvdn/dl4j-azure-minimal-example/blob/master/dl4j-azure-spark/src/main/java/org/daanvdn/sandbox/spark/SparkTrainerCli.java>. The `MultiLayerConfiguration` is added as a java [resource](https://github.com/daanvdn/dl4j-azure-minimal-example/blob/master/dl4j-azure-spark/src/main/resources/org/daanvdn/sandbox/spark/cnnGlobalPooling_var_lRate.json)

The spark-submit command I'm using to launch the training is as follows (I'm hiding the `accountName` and `accountKey`, the ip prefixes and some paths for obvious reasons) :

``
nohup /opt/spark-2.3.2-bin-hadoop2.7/bin/spark-submit --master spark://12.0.0.4:7077 --class org.daanvdn.sandbox.spark.SparkTrainerCli --driver-memory 300G --executor-memory 80G --executor-cores 4  --num-executors 4 --conf '-Dorg.bytedeco.javacpp.maxbytes=24G -Djava.io.tmpdir=/mnt/tmp' --conf 'spark.driver.extraJavaOptions=-Dorg.bytedeco.javacpp.maxbytes=24G -Djava.io.tmpdir=/mnt/tmp' /home/my-host/sparkjars/dl4j-azure-spark-1.0.0-SNAPSHOT-bin.jar -epochs 100 -batch 128 -avg 2 -prefetch 1 -container some-container -trainFolder train -testFolder test -evalMode ALL_EPOCHS -rddTrainingApproach Export -train true -evalNumWorkers 1 -accountName #### -accountKey ####  -netConfig /some/location/netConf.json -networkMask ##.0.0.0/17 -controllerAddress ##.0.0.4 -workersPerNode 1| tee nohup.out
``

As far as versions are concerned I'm using the snapshot version

Version information
-------------------
- Ubuntu 16.04.6 LTS
- cuda version:
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2018 NVIDIA Corporation
     Built on Tue_Jun_12_23:07:04_CDT_2018
     Cuda compilation tools, release 9.2, V9.2.148

- dl4j version: 1.0.0-SNAPSHOT
- dl4j.spark.version: 1.0.0_spark_2-SNAPSHOT
- java version: 1.8
- spark binaries: spark-2.3.2-bin-hadoop2.7
- nvidia driver version: 418.40.04

Hardware information
--------------------
- cluster of 4 slave machines, 1 driver machine
- every machine is hosted in Azure and has:
    - 4x Tesla P40 (24gb) GPUs
    - 24 vcpus
    - 448 GB host memory

**Comment by daanvdn** [comment]
@raver119 I did some further experimenting regarding this issue: when I downgrade the version of the dl4j stack to `1.0.0-beta3` and make no other changes to my code whatsoever, I no longer have the exception mentioned above.
However when I use this version, the freezing issue raised here in ticket https://github.com/deeplearning4j/deeplearning4j/issues/7431 and for which  you provided a fix in the `SNAPSHOT` version, does reappear (as is probably expected).  Note that when using the `SharedTrainingMaster` of `1.0.0-beta3` evaluation works fine.

**Comment by raver119** [comment]
Can you please send me logs from driver and from one of workers?

**Comment by daanvdn** [comment]
@raver119: do you want logs from code that uses the `snapshot` versions or `1.0.0-beta3`?

**Comment by raver119** [comment]
snapshot, sure.

**Comment by daanvdn** [comment]
@raver119 you can find the master log here:

https://github.com/daanvdn/dl4j-azure-minimal-example/blob/master/logs/master.log

the logs of a single slave can be found here (two executors): 

https://github.com/daanvdn/dl4j-azure-minimal-example/tree/master/logs/slave-log

**Comment by daanvdn** [comment]
hi @raver119 is there any news on this issue? Thanks!

**Comment by raver119** [comment]
Yep, working on isolating it.

**Comment by daanvdn** [comment]
hi @raver119 , I tried again with dl4j `1.0.0-beta4` but the same problem occurs. Do you have any suggestions for a workaround?  I would use `ParameterAveraging` instead, but, interestingly, on a spark cluster with 2 slaves training take more than twice as long than on a single machine with the `ParallelWrapper`. Moreover, while on spark + parameter averaging the net learns nothing (even after 1K epochs) as opposed to the `ParallelWrapper` which already learns something after a couple of epochs

**Comment by raver119** [comment]
No, unfortunately you'll have to wait once CUDA overhaul is finished in c++. Before that moment we just can't take on Spark because CUDA is disabled in current master.

**Comment by agibsonccc** [comment]
Closing: Parameter server / distributed training is no longer supported.
