### ISSUE TITLE
ND4J CUDA: Can't create UTF8 DeviceLocalNDArrays

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7523]
This comes up in inference on TF import models on CUDA, though could happen in other contexts too.

```
    @Test
    public void testDeviceLocalStringArray(){
        INDArray arr = Nd4j.create(Arrays.asList("first", "second"), 2);
        assertEquals(DataType.UTF8, arr.dataType());
        assertArrayEquals(new long[]{2}, arr.shape());

        DeviceLocalNDArray dl = new DeviceLocalNDArray(arr);        //Exception here

        INDArray arr2 = dl.get();
        assertEquals(arr, arr2);
    }
```

```
java.lang.ClassCastException: org.nd4j.linalg.api.buffer.Utf8Buffer cannot be cast to org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer

	at org.nd4j.jita.handler.impl.CudaZeroHandler.getDevicePointer(CudaZeroHandler.java:775)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.getPointer(AtomicAllocator.java:320)
	at org.nd4j.jita.concurrency.CudaAffinityManager.replicateToDevice(CudaAffinityManager.java:274)
	at org.nd4j.linalg.util.DeviceLocalNDArray.broadcast(DeviceLocalNDArray.java:58)
	at org.nd4j.linalg.util.DeviceLocalNDArray.<init>(DeviceLocalNDArray.java:38)
	at org.nd4j.Temp.testDeviceLocalStringArray(Temp.java:42)
```

We don't have a CudaUtf8DataBuffer so I'm not sure if the solution is to add that, or handle Utf8 differently here...
https://github.com/deeplearning4j/deeplearning4j/tree/master/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/main/java/org/nd4j/linalg/jcublas/buffer

**Comment by raver119** [comment]
Fixed/implemented
