### ISSUE TITLE
Convnet: XERBLA: Error on argument 6

### ISSUE THREAD

**Issue by stephanduq** [deeplearning4j/deeplearning4j#755]
When I try to use a Conv net I always get this error. Wether it is with my own data, or if I use the CNNIris example. Changing the backend helped

Exception in thread "main" java.lang.IllegalArgumentException: XERBLA: Error on argument 6 (LDA) in SGEMV
	at org.jblas.NativeBlas.sgemv(Native Method)
	at org.nd4j.linalg.jblas.blas.JblasLevel2.sgemv(JblasLevel2.java:25)
	at org.nd4j.linalg.api.blas.impl.BaseLevel2.gemv(BaseLevel2.java:53)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2569)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2377)
	at org.nd4j.linalg.factory.Nd4j.tensorMmul(Nd4j.java:705)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.backpropGradient(ConvolutionLayer.java:102)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.backprop(MultiLayerNetwork.java:1095)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1571)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:117)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1342)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1372)

**Comment by agibsonccc** [comment]
You shouldn't be using jblas. Please use only x86 for the backend on cpu. Thanks!
