### ISSUE TITLE
NPE in DifferentialFunction.java:157 when using SelfAttentionLayer

### ISSUE THREAD

**Issue by tschut** [deeplearning4j/deeplearning4j#7563]
#### Issue Description
When running .fit() on a Graph which includes a SelfAttentionLayer I get a NPE:
```
Exception in thread "main" java.lang.NullPointerException
        at org.nd4j.autodiff.functions.DifferentialFunction.propertiesForFunction(DifferentialFunction.java:157)
        at org.nd4j.autodiff.functions.DifferentialFunction.resolvePropertiesFromSameDiffBeforeExecution(DifferentialFunction.java:544)
        at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:622)
        at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:37)
        at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:249)
        at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:3986)
        at org.deeplearning4j.nn.layers.samediff.SameDiffLayer.activate(SameDiffLayer.java:99)
        at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:110)
        at org.deeplearning4j.nn.graph.ComputationGraph.ffToLayerActivationsInWS(ComputationGraph.java:2120)
        at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1357)
        at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1326)
        at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:160)
        at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
        at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
        at org.deeplearning4j.nn.graph.ComputationGraph.doTruncatedBPTT(ComputationGraph.java:3600)
        at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1141)
        at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1100)
        at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1087)
        at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:967)
        at com.luiwammes.pc.trainer.Application.main(Application.java:72)
```

#### Version Information
This happens only on my Google Cloud instance, on my local windows 10 machine it runs fine.

* using dl4j snapshot release
```
$ uname -a
Linux gpu-instance 4.15.0-1029-gcp #31-Ubuntu SMP Thu Mar 21 09:40:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

It crashes with both CPU and GPU backend.

**Comment by tschut** [comment]
Using this network config:
```
==========================================================================================================================================
VertexName (VertexType)         nIn,nOut   TotalParams   ParamsShape                                                    Vertex Inputs     
==========================================================================================================================================
input (InputVertex)             -,-        -             -                                                              -                 
layer-0 (LSTM)                  80,256     345088        W:{80,1024}, RW:{256,1024}, b:{1,1024}                         [input]           
layer-1 (LSTM)                  256,256    525312        W:{256,1024}, RW:{256,1024}, b:{1,1024}                        [layer-0]         
attention-merge (MergeVertex)   -,-        -             -                                                              [layer-0, layer-1]
attention (SameDiffLayer)       -,-        458752        Wq:{1,256,512}, Wk:{1,256,512}, Wv:{1,256,512}, Wo:{256,256}   [attention-merge] 
outputLayer (RnnOutputLayer)    256,80     20560         W:{256,80}, b:{1,80}                                           [attention]       
------------------------------------------------------------------------------------------------------------------------------------------
            Total Parameters:  1349712
        Trainable Parameters:  1349712
           Frozen Parameters:  0
==========================================================================================================================================```

**Comment by tschut** [comment]
Generated using this code:
```
    private static ComputationGraph buildNetwork(Config config, int in, int out) {
        if (config.nLayers < 1) {
            throw new IllegalArgumentException("nlayers should be >= 1");
        }

        String[] outputLayerInputs = new String[config.nLayers];
        ComputationGraphConfiguration.GraphBuilder builder = new NeuralNetConfiguration.Builder()
                .seed(12345)
                .l2(config.l2)
                .weightInit(WeightInit.XAVIER)
                .updater(new Adam(config.lr))
                .graphBuilder()
                .addInputs("input")
                .addLayer("layer-0", new LSTM.Builder()
                        .nIn(in)
                        .nOut(config.layerSize)
                        .activation(Activation.TANH)
                        .dropOut(config.dropout)
                        .build(), "input");

        outputLayerInputs[0] = "layer-0";
        for (int i = 1; i < config.nLayers; i++) {
            builder.addLayer("layer-" + i, new LSTM.Builder()
                    .nIn(config.layerSize)
                    .nOut(config.layerSize)
                    .dropOut(config.dropout)
                    .activation(Activation.TANH)
                    .build(), "layer-" + (i - 1));
            outputLayerInputs[i] = "layer-" + i;
        }
        builder.addLayer("attention", new SelfAttentionLayer.Builder()
                .nHeads(1)
                .projectInput(true)
                .nIn(config.nLayers * config.layerSize)
                .nOut(config.layerSize)
                .build(), outputLayerInputs);
        ComputationGraphConfiguration conf = builder
                .addLayer("outputLayer", new RnnOutputLayer.Builder(LossFunctions.LossFunction.MCXENT)
                        .activation(Activation.SOFTMAX)
                        .nIn(config.layerSize)
                        .nOut(out)
                        .build(), "attention")
                .setOutputs("outputLayer")
                .backpropType(BackpropType.TruncatedBPTT).tBPTTForwardLength(config.tbpttLength)
                .tBPTTBackwardLength(config.tbpttLength)
                .build();

        ComputationGraph net = new ComputationGraph(conf);
        net.init();
        return net;
    }
```

With relevant config parameters:
tbttLength = 35
layerSize = 256
nLayers = 2
l2 = 0.00001
in = out = 80
dropout = 1

**Comment by treo** [comment]
@tschut 
Can you give me some more information on how you are training the network?
How did you build your jar file to run on the google cloud?

As far as I could test it, this does still work just fine on both linux (Ubuntu 19.04) and windows (10). 

The only difference I can think of is that I might have a slightly newer snapshot available, as the snapshots in my maven cache are based on local builds of dl4j.

**Comment by tschut** [comment]
I'm building with maven on google cloud and have maven create an uberjar using maven shade.

To be sure about dependency related stuff I wiped my m2 repo (both local and on cloud machine) and rebuild. Now there's another error that wasn't there before. I didn't change the code that's building the network.

```
Exception in thread "main" java.lang.IllegalArgumentException: Too many indices for array. Number of indexes must be <= rank(): rank 1 array with indices [Point(0), Interval(b=0,e=163840,s=1)]
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:5006)
	at org.deeplearning4j.nn.params.LSTMParamInitializer.init(LSTMParamInitializer.java:121)
	at org.deeplearning4j.nn.conf.layers.LSTM.instantiate(LSTM.java:84)
	at org.deeplearning4j.nn.conf.graph.LayerVertex.instantiate(LayerVertex.java:106)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:556)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:438)
	at com.luiwammes.pc.trainer.Application.buildNetwork(Application.java:127)
	at com.luiwammes.pc.trainer.Application.main(Application.java:40)
```
I guess this is unrelated to the NPE, but we can't be sure the NPE will no longer show up since that point isn't reached because of this new problem.

**Comment by tschut** [comment]
This new problem also is unrelated to the attention layer. I'll post it on gitter too.

**Comment by treo** [comment]
just to make sure you are actually getting the freshest available version, make sure to build with `mvn -U`.

Other than that, I can't reproduce your new error as well. It is something that you would only get by using a combination of packages that were build before https://github.com/deeplearning4j/deeplearning4j/pull/7531 was merged for dl4j and after it was merged for nd4j.

**Comment by treo** [comment]
@tschut given that I've copied your config I suspect that the bug maybe triggered by some kind of edge case with a weird input size, stride, order combination. 

So I'd need to know how exactly you are providing data to the network. Going by the stacktrace, it looks like you are calling `fit(DataSet)`. So in that case I'd like to see what you get from calling `shapeInfoToString()` on the provided features, labels and masks if applicable.

Also, the line numbers you had in the original post, they aren't lining up with current master anymore. So  please provide a new Stacktrace as well.

**Comment by tschut** [comment]
Updated stacktrace:
```Exception in thread "main" java.lang.NullPointerException
        at org.nd4j.autodiff.functions.DifferentialFunction.propertiesForFunction(DifferentialFunction.java:157)
        at org.nd4j.autodiff.functions.DifferentialFunction.resolvePropertiesFromSameDiffBeforeExecution(DifferentialFunction.java:544)
        at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:622)
        at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:37)
        at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:249)
        at org.nd4j.autodiff.samediff.SameDiff.exec(SameDiff.java:3932)
        at org.deeplearning4j.nn.layers.samediff.SameDiffLayer.activate(SameDiffLayer.java:98)
        at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:111)
        at org.deeplearning4j.nn.graph.ComputationGraph.ffToLayerActivationsInWS(ComputationGraph.java:2132)
        at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1369)
        at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1338)
        at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:160)
        at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
        at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
        at org.deeplearning4j.nn.graph.ComputationGraph.doTruncatedBPTT(ComputationGraph.java:3612)
        at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1153)
        at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1112)
        at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1099)
        at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:981)
        at com.luiwammes.pc.trainer.Application.main(Application.java:72)```

I'm training by calling net.fit(DataSet). Tried switching to net.fit(DataSetIterator) but no difference.

shapes:
```
21:16:53.723 [main] INFO  com.luiwammes.pc.trainer.Application - labels: Rank: 3, DataType: FLOAT, Offset: 0, Order: f, Shape: [128,80,1050],  Stride: [1,128,10240]
21:16:53.723 [main] INFO  com.luiwammes.pc.trainer.Application - features: Rank: 3, DataType: FLOAT, Offset: 0, Order: f, Shape: [128,80,1050],  Stride: [1,128,10240]
```
Masks are null.

**Comment by treo** [comment]
I've finally reproduced the problem.

It only happens when run with Java 12 (or maybe  Java >8, but I only have 8 and 12 in that linux env).

As a quick workaround you should be able to just use java 8 on your cloud machine while I try to figure out what is going on there.

**Comment by treo** [comment]
It looks like this isn't going to be a quick fix. See https://github.com/deeplearning4j/deeplearning4j/issues/7572 for more information.

Please confirm that using java 8 works for you and if it does close this issue. Working towards support of Java 12 with SameDiff (and SameDiff based layers) will be tracked in https://github.com/deeplearning4j/deeplearning4j/issues/7572.

**Comment by tschut** [comment]
I was running on openjdk-11. Switching to openjdk-8 indeed 'fixes' the problem.

When building for gpu I run into a segmentation fault, but that seems unrelated.
