### ISSUE TITLE
TupleStreamDataSetIteratorTest reports thread leak

### ISSUE THREAD

**Issue by cpoerschke** [deeplearning4j/deeplearning4j#7570]
To reproduce:
```
cd deeplearning4j/deeplearning4j-dataimport-solrj
mvn test
```

Example output:
```
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.901 sec <<< FAILURE! - in org.deeplearning4j.nn.dataimport.solr.client.solrj.io.stream.TupleStreamDataSetIteratorTest
org.deeplearning4j.nn.dataimport.solr.client.solrj.io.stream.TupleStreamDataSetIteratorTest  Time elapsed: 3.733 sec  <<< ERROR!
com.carrotsearch.randomizedtesting.ThreadLeakError: 
2 threads leaked from SUITE scope at org.deeplearning4j.nn.dataimport.solr.client.solrj.io.stream.TupleStreamDataSetIteratorTest: 
   1) Thread[id=213, name=DeallocatorServiceThread_0, state=WAITING, group=TGRP-TupleStreamDataSetIteratorTest]
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at org.nd4j.linalg.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:119)
   2) Thread[id=214, name=DeallocatorServiceThread_1, state=WAITING, group=TGRP-TupleStreamDataSetIteratorTest]
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at org.nd4j.linalg.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:119)


Results :

Tests in error: 
  TupleStreamDataSetIteratorTest.org.deeplearning4j.nn.dataimport.solr.client.solrj.io.stream.TupleStreamDataSetIteratorTest » ThreadLeak

Tests run: 3, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by cpoerschke** [comment]
Perhaps the `ThreadLeakFilters` logic of the test just needs updating? Haven't looked into as yet.

code link: https://github.com/deeplearning4j/deeplearning4j/blob/deeplearning4j-1.0.0-beta3/deeplearning4j/deeplearning4j-dataimport-solrj/src/test/java/org/deeplearning4j/nn/dataimport/solr/client/solrj/io/stream/TupleStreamDataSetIteratorTest.java#L60-L64

**Comment by AlexDBlack** [comment]
Yeah, my take on this is that those threads are supposed to be long-lived, so it's just filtering issue (thread names have changed - or, we change them back to old names)

**Comment by cpoerschke** [comment]
> ... it's just filtering issue ...

Thanks @AlexDBlack for including the filtering adjustment in your https://github.com/deeplearning4j/deeplearning4j/commit/5ce5fe8224590c02db14da22525c944e5c4e2de7#diff-f8d2b13b79c5d270c03fc09b5588a2a3 commit!
