### ISSUE TITLE
Function did not decrease: score = 1.361 > 1.3460041015625 = oldScore

### ISSUE THREAD

**Issue by MikeDepies** [deeplearning4j/deeplearning4j#760]
Using the optimizationAlgorithm : OptimizationAlgorithm.LBFGS this should be a warning rather than an error/exception.

Exception in thread "main" java.lang.IllegalStateException: Function did not decrease: score = 1.361 > 1.3460041015625 = oldScore
	at org.deeplearning4j.optimize.solvers.BackTrackLineSearch.optimize(BackTrackLineSearch.java:251)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:165)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.fit(BaseOutputLayer.java:328)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.finetune(MultiLayerNetwork.java:1285)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1337)
	at ...my code

**Comment by agibsonccc** [comment]
Can you show me the configuration you used please? It looks like it went down a maximize code path which shouldn't be the case normally.

**Comment by AlexDBlack** [comment]
Looking at the line numbers it's probably a case of minimizing objective function but slope (used in Wolfe line search termination condition) being > 0 (which normally shouldn't happen when minimizing objective function)
Would be good to be able to reproduce this and work out why it's happening (might be LBFGS being a little unstable or something)

**Comment by MikeDepies** [comment]
I don't think I have the code around anymore. I'll see if I can recreate it.
