### ISSUE TITLE
Error on SimpleCNN(ZooModel)

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#7607]
Hi, I try create a SimpleCNN model,
val x1 = SimpleCNN.builder().build().init()

The errors happen:
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 4
o.n.n.Nd4jBlas - Number of threads used for BLAS: 4
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 7]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [3.5GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
Exception in thread "main" org.deeplearning4j.exception.DL4JInvalidConfigException: ConvolutionLayer (index=30, name=layer30) nIn=256, nOut=0; nIn and nOut must be > 0
	at org.deeplearning4j.nn.conf.layers.LayerValidation.assertNInNOutSet(LayerValidation.java:57)
	at org.deeplearning4j.nn.conf.layers.ConvolutionLayer.instantiate(ConvolutionLayer.java:159)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:648)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:549)

**Comment by AlexDBlack** [comment]
Try adding an appropriate input shape and label number of classes.
For example, for imagenet (224x224 RGB) you could use:
```
        val x1 = SimpleCNN.builder()
                .inputShape(new int[]{3,224,224})
                .numClasses(1000)
                .build().init();
```
