### ISSUE TITLE
W2vec error on nearestWords using a vector

### ISSUE THREAD

**Issue by MikeDepies** [deeplearning4j/deeplearning4j#765]
When trying to feed a vector into the wordsNearest function of word2Vec, it fails with the following error:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at org.nd4j.linalg.api.shape.Shape.getOffset(Shape.java:498)
	at org.nd4j.linalg.api.shape.Shape.getDouble(Shape.java:249)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:1440)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getInt(BaseNDArray.java:1428)
	at org.deeplearning4j.models.embeddings.wordvectors.WordVectorsImpl.wordsNearest(WordVectorsImpl.java:198)
	at com.blackthorne.com.deeplearning_bt.W2VecRBM.main(W2VecRBM.java:67)
```
Here's the code:
https://gist.github.com/MikeDepies/71a4006d2a4e5a10454e

Here's the additional external files (vectorModel & a one sentence file to read in)
https://www.dropbox.com/s/iyy9qetf7aezcoq/resources.7z?dl=0

**Comment by akioWS** [comment]
I'm also getting this problem, in a very similar code. Did manager to solve it?

**Comment by agibsonccc** [comment]
This should be solved now.
