### ISSUE TITLE
NLP ParagraphVectorsTextExample run error

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#7681]
In 1.0.0-beta4, I run ParagraphVectorsTextExample test App, and report:
o.d.m.e.i.InMemoryLookupTable - Initializing syn1...
o.d.m.s.SequenceVectors - Building learning algorithms:
o.d.m.s.SequenceVectors -           building SequenceLearningAlgorithm: [PV-DBOW]
o.d.m.s.SequenceVectors - Starting learning process...
Exception in thread "VectorCalculationsThread 0" java.lang.RuntimeException: java.lang.NullPointerException
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1341)
Caused by: java.lang.NullPointerException
	at org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram.iterateSample(SkipGram.java:431)
	at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1316)

I think the reason is in SequenceVectors.java, 
look the run() method of the inner class VectorCalculationsThread,
...
for (int j = 0; j < chunks; ++j) {
if (elementsLearningAlgorithm instanceof SkipGram)                                    
   ((SkipGram) elementsLearningAlgorithm).iterateSample(batchSequences.get(j));
else if (elementsLearningAlgorithm instanceof CBOW)                                    
   ((CBOW) elementsLearningAlgorithm).iterateSample(batchSequences.get(j));

We have two "elementsLearningAlgorithm", 
A: is class variable of SequenceVectors, 
B: is sequenceLearningAlgorithm.getElementsLearningAlgorithm().

here we invoke the A's method:
((SkipGram) elementsLearningAlgorithm).iterateSample(batchSequences.get(j));
but A don't execute its configure() yet,so its configuration variable is null, 
so we get NPE!

B has executed its configure() method by the SequenceVectors's initLearners() method :-)

**Comment by AdithyaYelloju** [comment]
What is the solution for this NPE?

**Comment by beast1301** [comment]
I have same problem. Any suggestions?

**Comment by Charele** [comment]
@AdithyaYelloju @beast1301 
I say the reason above, we have noway unless commiter fix it.

**Comment by alexanderst** [comment]
Implemented in development branch. Will be merged soon.

**Comment by agibsonccc** [comment]
Closing — references a removed/rewritten subsystem (DataVec, NLP/Word2Vec, Model Zoo, Spark, UI, or Arbiter). These have been fundamentally rewritten or removed in the upcoming release. Please open a new issue if you experience similar problems with the new version.
