### ISSUE TITLE
ND4J - RuntimeException: Error loading DataSet

### ISSUE THREAD

**Issue by zouyu4524** [deeplearning4j/deeplearning4j#7720]
#### Issue Description

Exception occurs using `load` method of  `DataSet`.

Firstly, I ran the following [code](https://gist.github.com/zouyu4524/68d16bac7ed8081d51a7707a1154447e
) to save the dataset locally, named "labelled_dataset", without extension. The code runs fine. Here is a snippet.
```
File locationToSave = new File("labelled_dataset");

int [] sampleShape = {1, 270};
int [] labelShape = {1, 6};
boolean [] indexes = new boolean[6];
indexes[3] = true;
INDArray sensorData = Nd4j.create(ArrayUtil.flattenDoubleArray(localdata), sampleShape);
INDArray label = Nd4j.create(indexes);

DataSet dataSet = new DataSet(sensorData, label.reshape(labelShape));

dataSet.save(locationToSave);
```
Then, I tried to load it using the [code](https://gist.github.com/zouyu4524/2a2bae0cec46e5019d09e8eb1c8e8a23). Here is  a snippet.  
```
File locationToLoad = new File("labelled_dataset");

DataSet dataSet = new DataSet();
dataSet.load(locationToLoad);
```
But I got the following exceptions.
```
Exception in thread "main" java.lang.RuntimeException: Error loading DataSet
	at org.nd4j.linalg.dataset.DataSet.load(DataSet.java:275)
	at org.nd4j.linalg.dataset.DataSet.load(DataSet.java:283)
	at har.HARClassifierNNLoadTest.main(HARClassifierNNLoadTest.java:15)
Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.read(BaseDataBuffer.java:1922)
	at org.nd4j.linalg.compression.CompressedDataBuffer.readUnknown(CompressedDataBuffer.java:101)
	at org.nd4j.linalg.factory.Nd4j.read(Nd4j.java:2667)
	at org.nd4j.linalg.dataset.DataSet.load(DataSet.java:258)
	... 2 more
Caused by: java.lang.UnsupportedOperationException
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.pointerIndexerByCurrentType(BaseDataBuffer.java:1421)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.read(BaseDataBuffer.java:1916)
        ... 5 more
```
FYI: I used `gradle` to build the project. The `build.gradle` is [here](https://gist.github.com/zouyu4524/ba22eccac4117ffd6c3b1c1f18052369).

Please describe our issue, along with:
- expected behavior
dataSet.load(File) works as expected.
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
1.0.0-beta4
* platform information (OS, etc)
Win 10 / Ubuntu 16.04
* CUDA version, if used
No CUDA used.

**Comment by AlexDBlack** [comment]
Thanks for the issue. This appears to be due to an issue with the boolean type. I'd recommend casting the boolean labels array to a float/integer array instead, using INDArray.castTo(DataType.FLOAT) (this will give you values 0 and 1 suitable for training a binary multi-label classifier, for example). This cast is what would happen internally in the output layer anyway (unless you've got some sort of custom layer).

**Comment by zouyu4524** [comment]
@AlexDBlack Thank you very much. `INDArray.castTo(DataType.FLOAT)` works for me.

**Comment by raver119** [comment]
Still a bug, despite workaround helps.

**Comment by zouyu4524** [comment]
I see. Thank you.

**Comment by raver119** [comment]
Ser/de issues for new dtypes are fixed in current dev branch. Thanks for highlighting this issue.
