### ISSUE TITLE
javax.xml.bind.annotation.xmlschema not found

### ISSUE THREAD

**Issue by Volnetiks** [deeplearning4j/deeplearning4j#7727]
#### Issue Description

Hello, i'm trying to run MLPClassLinear.java, and i got this error:
Error: Internal error: (java.lang.ClassNotFoundException) javax.xml.bind.annotation.XmlSchema

#### Version Information

Please indicate relevant versions, including, if relevant:

DL4J Version: Latest - Cloned a few minutes ago
Platform: Windows 10
NVIDIA Driver Version: Latest

**Comment by AlexDBlack** [comment]
We'll need more information. First: Can you post the complete output - ND4J initialization, full stack trace etc - when you run the example?
Second: How are you running this? Via command line (maven) or via an IDE (intellij, eclipse, etc)?
Finally - what Java and Maven versions?

**Comment by Volnetiks** [comment]
> We'll need more information. First: Can you post the complete output - ND4J initialization, full stack trace etc - when you run the example?
> Second: How are you running this? Via command line (maven) or via an IDE (intellij, eclipse, etc)?
> Finally - what Java and Maven versions?

I'm running it with IntelliJ, i have java 1.8.0_202 and maven 3.6.1

Complete outpout:
Information:14/05/2019 07:27 - Build completed with 1 error and 0 warnings in 10 s 163 ms
Error:Internal error: (java.lang.ClassNotFoundException) javax.xml.bind.annotation.XmlSchema
java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:157)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:76)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:82)
	at org.jetbrains.jps.android.AndroidJpsUtil.getAndroidTarget(AndroidJpsUtil.java:404)
	at org.jetbrains.jps.android.AndroidJpsUtil.getAndroidPlatform(AndroidJpsUtil.java:480)
	at org.jetbrains.jps.android.builder.AndroidPreDexBuildTarget.computeRootDescriptors(AndroidPreDexBuildTarget.java:110)
	at org.jetbrains.jps.builders.impl.BuildRootIndexImpl.addRoots(BuildRootIndexImpl.java:72)
	at org.jetbrains.jps.builders.impl.BuildRootIndexImpl.<init>(BuildRootIndexImpl.java:62)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:85)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:279)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:135)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:228)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by AlexDBlack** [comment]
Thanks for the extra info.
Nothing in that stack trace is DL4J or ND4J-related.
I'm going to close this as not related to any of our code.
Maybe try a minimal project (no DL4J/ND4J dependencies) and see if that works.
In the unlikely event that this *is* due to DL4J/ND4J (or its transitive dependencies) somehow, we can re-open the issue and look into it further.
