### ISSUE TITLE
UnsatisfiedLinkError while loading trained Keras model. 

### ISSUE THREAD

**Issue by doszke** [deeplearning4j/deeplearning4j#7744]
#### Issue Description

Hi, 
I was trying to load a trained NN model used for digit recognition. 

While running my code, this error was thrown:

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnihdf5 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1336)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1077)
	at org.bytedeco.javacpp.Loader.load(Loader.java:947)
	at org.bytedeco.hdf5.global.hdf5.<clinit>(hdf5.java:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1006)
	at org.bytedeco.javacpp.Loader.load(Loader.java:963)
	at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.<clinit>(Hdf5Archive.java:59)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.modelHdf5Filename(KerasModelBuilder.java:225)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:222)
	at Deploy.main(Deploy.java:25)
Caused by: java.lang.UnsatisfiedLinkError: no libhdf5_hl_cpp in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1336)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1033)
	... 10 more`

#### Version Information

* Deeplearning4j version 10.0.0 beta 4 (tested also on ver 0.9.1 with the same effect)
* Intellij Idea Ultimate 2018.3.3
* Windows 10 64-bit

#### Contributing

My code:
`import org.datavec.image.loader.NativeImageLoader;
import org.deeplearning4j.nn.modelimport.keras.KerasModelImport;
import org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException;
import org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.dataset.api.preprocessor.DataNormalization;
import org.nd4j.linalg.dataset.api.preprocessor.ImagePreProcessingScaler;
import org.nd4j.linalg.io.ClassPathResource;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

public class Deploy {

    public static void main(String[] args) throws IOException, InvalidKerasConfigurationException, UnsupportedKerasConfigurationException {
        String modelRef = new ClassPathResource("model.h5").getFile().getPath();

        MultiLayerNetwork network = KerasModelImport.importKerasSequentialModelAndWeights(modelRef);

        NativeImageLoader nativeImageLoader = new NativeImageLoader(28, 28, 1);

        // 28x28 1-channel image representing the digit '1'
        FileInputStream inputStream = new FileInputStream(new File("C:\\Users\\pc\\Desktop\\one.bmp"));

        INDArray image = nativeImageLoader.asMatrix(inputStream);

        DataNormalization scaler = new ImagePreProcessingScaler(0,1);
        scaler.transform(image);

        INDArray output = network.output(image);

        System.out.println(output.toString());

    }

}
`

**Comment by saudet** [comment]
Could you also post your pom.xml file?

**Comment by doszke** [comment]
I've created a normal java project and added external libraries form Maven, so I don't have such a file. 
Maven coordinates:
org.deeplearning4j:deeplearning4j-core:1.0.0-beta4
org.deeplearning4j:deeplearning4j-modelimport:1.0.0-beta4
org.nd4j:nd4j-native-platform:1.0.0-beta4

**Comment by raver119** [comment]
This will not work. You're missing 100500 transitive dependencies.

**Comment by raver119** [comment]
P.s. it's 2019 now. Please use build system. Any build system will work: gradle, maven whatver.
