### ISSUE TITLE
Autoencoder with generating one node in the layer that encoding stops

### ISSUE THREAD

**Issue by Shima32** [deeplearning4j/deeplearning4j#775]
I have an autoecoder with 8 layers for a nlp task, in layer 4 encoding stops and i want 1 node in ‎layer 4 as a score of input sentence,
 but when i set the number of node in layer 4 to 1 it is not ‎working(with 2 or more node it works fine).

Version of DL4J : 0.4-rc3.2‎

Stack trace :‎
```
Exception in thread "main" java.lang.RuntimeException: Invalid order
at org.nd4j.linalg.api.shape.Shape.isContiguousInBuffer(Shape.java:1474)‎
at org.nd4j.linalg.api.shape.Shape.toOffsetZeroCopyHelper(Shape.java:171)‎
at org.nd4j.linalg.api.shape.Shape.toOffsetZeroCopy(Shape.java:129)‎
at org.nd4j.linalg.api.ndarray.BaseNDArray.dup(BaseNDArray.java:1411)‎
at org.nd4j.linalg.api.ndarray.BaseNDArray.mul(BaseNDArray.java:3032)‎
at org.deeplearning4j.nn.updater.BaseUpdater.postApply(BaseUpdater.java:42)‎
at org.deeplearning4j.nn.updater.BaseUpdater.update(BaseUpdater.java:27)‎
at org.deeplearning4j.optimize.solvers.BaseOptimizer.updateGradientAccordingToParams(BaseOptimizer.java:241)‎
at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:119)‎
at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)‎
at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)‎
at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:471)‎
at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.fit(RBM.java:410)‎
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:214)‎
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1327)‎
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1372)‎
at AutomatedTextSummarization.nuralNetwork.CreatingNN.main(CreatingNN.java:93)‎
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)‎
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)‎
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)‎
at java.lang.reflect.Method.invoke(Method.java:606)‎
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)‎
```

SAMPLE NEURAL NET:‎
```
public static void main(String[] args) throws  Exception { 
‎ RecordReader recordReader = new CSVRecordReader(0,","); 
‎ recordReader.initialize(new FileSplit(new ClassPathResource("features&Index.txt").getFile())); 
‎ 
‎    Nd4j.MAX_SLICES_TO_PRINT = 10; 
‎    Nd4j.MAX_ELEMENTS_PER_SLICE = 10; 
‎ 
‎    final int numRows = 4; 
‎    final int numColumns = 1; 
‎    final int numInputs = 4; 
‎    int outputNum = 3; 
‎    int iterations = 100; 
‎    long seed = 123; 
‎    int listenerFreq = iterations/5; 
‎ 
‎    log.info("Load data...."); 
‎    org.nd4j.linalg.dataset.api.iterator.DataSetIterator iterator = new RecordReaderDataSetIterator(recordReader,120,4,244); 
‎ 
‎ 
‎    log.info("Build model...."); 
‎    MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder() 
‎            .seed(seed) 
‎            .iterations(iterations) 
‎            .learningRate(1e-6f) 
‎            .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT) 
‎            .l1(1e-1).regularization(true).l2(2e-4) 
‎            .list(8) 
‎            .layer(0, new RBM.Builder().nIn(numRows * ‎numColumns).nOut(100).lossFunction(LossFunctions.LossFunction.RMSE_XENT).build()) 
‎            .layer(1, new RBM.Builder().nIn(100).nOut(80).lossFunction(LossFunctions.LossFunction.RMSE_XENT).build()) 
‎            .layer(2, new RBM.Builder().nIn(80).nOut(40).lossFunction(LossFunctions.LossFunction.RMSE_XENT).build()) 
‎            .layer(3, new ‎RBM.Builder().nIn(40).nOut(1).lossFunction(LossFunctions.LossFunction.RMSE_XENT).build())//encoding stops 
‎            .layer(4, new ‎RBM.Builder().nIn(1).nOut(40).lossFunction(LossFunctions.LossFunction.RMSE_XENT).build())//decoding starts 
‎            .layer(5, new RBM.Builder().nIn(40).nOut(80).lossFunction(LossFunctions.LossFunction.RMSE_XENT).build()) 
‎            .layer(6, new RBM.Builder().nIn(80).nOut(100).lossFunction(LossFunctions.LossFunction.RMSE_XENT).build()) 
‎            .layer(7, new OutputLayer.Builder(LossFunctions.LossFunction.RMSE_XENT).nIn(100).nOut(numRows * ‎numColumns).build()) 
‎            .pretrain(true).backprop(true) 
‎ 
‎            .build(); 
‎ 
‎    MultiLayerNetwork model = new MultiLayerNetwork(conf); 
‎    model.init();‎
‎  MultiLayerNetwork model = new MultiLayerNetwork(conf); 
‎  model.init(); 
‎ 
‎  model.setListeners(Arrays.asList((IterationListener) new ‎ScoreIterationListener(listenerFreq))); 
‎ 
‎  log.info("Train model...."); 
‎      DataSet next = iterator.next(); 
‎      next.normalizeZeroMeanZeroUnitVariance(); 
‎      model.fit(new DataSet(next.getFeatureMatrix(), next.getFeatureMatrix()));‎
‎}‎
```

**Comment by AlexDBlack** [comment]
Very likely fixed by https://github.com/deeplearning4j/nd4j/pull/452
I don't have access your data file so can't run your NN to verify
