### ISSUE TITLE
Cuda crashes while loading/saving data

### ISSUE THREAD

**Issue by JSpiegel** [deeplearning4j/deeplearning4j#7795]
#### Version Information

* dl4j-1.0.0-beta4
* Windows 10
* Cuda 10.0/10.1(happened on both)
* NVIDIA driver 430.64
* GPU: GTX 1650, 4GB

#### Issue Description

When trying to train a simple FNN on a GTX 1650 GPU, I encounter a Cuda crash after random amounts of time. This also happens when trying to pre-save the (fairly large) tabular dataset(which is loaded from a database using the JDBCRecordReader) without having entered the training process yet. The same procedure worked flawlessly on the CPU, so this problem should be related to Cuda/GPU. GPU-Z shows memory usage below 3 GB, so that should not be the issue.
If more details are required, please let me know. 

Stack trace:
```
Exception in thread "DeallocatorServiceThread_1" Exception in thread "DeallocatorServiceThread_0" Exception in thread "main" java.lang.RuntimeException: concat(...) failedError code [77]
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.concat(Native Method)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.concat(JCublasNDArrayFactory.java:520)
	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:5495)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.hstack(BaseNDArrayFactory.java:968)
	at org.nd4j.linalg.factory.Nd4j.hstack(Nd4j.java:5217)
	at org.deeplearning4j.nn.graph.vertex.impl.MergeVertex.doForward(MergeVertex.java:117)
	at org.deeplearning4j.nn.graph.ComputationGraph.ffToLayerActivationsInWS(ComputationGraph.java:2116)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1369)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1338)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:160)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1162)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1112)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1079)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1041)
	Suppressed: java.lang.RuntimeException: cudaStreamSynchronize(...) failed
		at org.nd4j.nativeblas.Nd4jCuda$NativeOps.streamSynchronize(Native Method)
		at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:131)
		at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:121)
		at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.commit(CudaExecutioner.java:1866)
		at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:602)
		at org.deeplearning4j.nn.graph.ComputationGraph.ffToLayerActivationsInWS(ComputationGraph.java:2159)
		... 11 more
	Suppressed: java.lang.RuntimeException: cudaStreamSynchronize(...) failed
		at org.nd4j.nativeblas.Nd4jCuda$NativeOps.streamSynchronize(Native Method)
		at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:131)
		at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:121)
		at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.commit(CudaExecutioner.java:1866)
		at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:602)
		at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1419)
		... 10 more
java.lang.RuntimeException: java.lang.RuntimeException: cudaEventSynchronize(...) failed
	at org.nd4j.linalg.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:127)
Caused by: java.lang.RuntimeException: cudaEventSynchronize(...) failed
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.eventSynchronize(Native Method)
	at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.synchronize(cudaEvent_t.java:67)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillReleased(SynchronousFlowController.java:234)
	at org.nd4j.jita.flow.impl.GridFlowController.waitTillReleased(GridFlowController.java:78)
	at org.nd4j.jita.allocator.impl.CudaDeallocator.deallocate(CudaDeallocator.java:31)
	at org.nd4j.linalg.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:122)
java.lang.RuntimeException: java.lang.RuntimeException: cudaEventSynchronize(...) failed
	at org.nd4j.linalg.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:127)
Caused by: java.lang.RuntimeException: cudaEventSynchronize(...) failed
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.eventSynchronize(Native Method)
	at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.synchronize(cudaEvent_t.java:67)
	at org.nd4j.jita.flow.impl.SynchronousFlowController.waitTillReleased(SynchronousFlowController.java:234)
	at org.nd4j.jita.flow.impl.GridFlowController.waitTillReleased(GridFlowController.java:78)
	at org.nd4j.jita.allocator.impl.CudaDeallocator.deallocate(CudaDeallocator.java:31)
	at org.nd4j.linalg.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:122)
CUDA error at D:/jenkins/ws/dl4j-deeplearning4j-1.0.0-beta4-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:1914 code=77(<unknown>) "dZ" 
CUDA error at D:/jenkins/ws/dl4j-deeplearning4j-1.0.0-beta4-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:1914 code=77(<unknown>) "dZ" 
CUDA error at D:/jenkins/ws/dl4j-deeplearning4j-1.0.0-beta4-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:1903 code=77(<unknown>) "dZ" 
CUDA error at D:/jenkins/ws/dl4j-deeplearning4j-1.0.0-beta4-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:1903 code=77(<unknown>) "dZ" 
CUDA error at D:/jenkins/ws/dl4j-deeplearning4j-1.0.0-beta4-windows-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:1858 code=77(<unknown>) "dZ" 
Failed on [3333412432] -> [231842224], size: [4096], direction: [0], dZ: [77]
Exception in thread "AMDSI prefetch thread" java.lang.RuntimeException: java.lang.RuntimeException: cudaMemcpyAsync(...) failed
	at org.deeplearning4j.datasets.iterator.AsyncMultiDataSetIterator$AsyncPrefetchThread.run(AsyncMultiDataSetIterator.java:396)
Caused by: java.lang.RuntimeException: cudaMemcpyAsync(...) failed
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.memcpyAsync(Native Method)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.memcpyAsync(CudaZeroHandler.java:589)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.memcpyAsync(AtomicAllocator.java:954)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.set(BaseCudaDataBuffer.java:800)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.setData(BaseCudaDataBuffer.java:935)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.setData(CudaFloatDataBuffer.java:166)
	at org.nd4j.linalg.factory.Nd4j.createTypedBuffer(Nd4j.java:1599)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:1585)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3616)
	at org.datavec.api.util.ndarray.RecordConverter.toMinibatchArray(RecordConverter.java:198)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:160)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:119)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:61)
	at org.deeplearning4j.datasets.iterator.AsyncMultiDataSetIterator$AsyncPrefetchThread.run(AsyncMultiDataSetIterator.java:368)
	Suppressed: java.lang.RuntimeException: cudaStreamSynchronize(...) failed
		at org.nd4j.nativeblas.Nd4jCuda$NativeOps.streamSynchronize(Native Method)
		at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:131)
		at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:121)
		at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.commit(CudaExecutioner.java:1866)
		at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:602)
		at org.deeplearning4j.datasets.iterator.AsyncMultiDataSetIterator$AsyncPrefetchThread.run(AsyncMultiDataSetIterator.java:372)
```

**Comment by AlexDBlack** [comment]
Thanks for the issue.
We'll need some way to reproduce this - the network configuration and information about the data (array shapes, mainly).
A minimal standalone example we can run without modifying things would help a lot.

**Comment by JSpiegel** [comment]
Alright, I will try to come up with an example that causes the crash on my PC. I am rather sure though that this does not depend on the exact configuration and data, as I have encountered it with different subsets of my data and different net structures.

**Comment by lpaatero** [comment]
This could be related to same problem. Unfortunately I do not have a simple way to reproduce this yet.
Any ideas on how to debug this would be welcome.

**Version Information**

    dl4j-1.0.0-beta4
    OpenSuse 15
    Cuda 10.0
    NVIDIA driver 430.14 / 415.27 (happens on both)
    GPU: GTX 1070 / 1080ti (happens on both)

When running inference, I am seeing (randomly) exceptions as below few times a day.
Model is quite complex convolutional model. Exception happends in multiple different data sizes (9x9,13x13,19x19).
Exception does not happen if run under cuda-memcheck. 

    CUDA error at /mnt/jenkins/workspace/deeplearning4j-deeplearning4j-1.0.0-beta4-linux-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:1903  code=77(<unknown>) "dZ"
    CUDA error at /mnt/jenkins/workspace/deeplearning4j-deeplearning4j-1.0.0-beta4-linux-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:1903 code=77(<unknown>) "dZ"
    CUDA error at /mnt/jenkins/workspace/deeplearning4j-deeplearning4j-1.0.0-beta4-linux-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:1903 code=77(<unknown>) "dZ"
    2019-05-28 10:22:18.139 net.gowrite.dcnn.batching.FastBatchPrediction$Evaluator run - SEVERE: Inference exception
    java.lang.RuntimeException: cudaStreamSynchronize(...) failed
            at org.nd4j.nativeblas.Nd4jCuda$NativeOps.streamSynchronize(Native Method)
            at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:131)
            at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:121)
            at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.commit(CudaExecutioner.java:1866)
            at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:602)
            at org.deeplearning4j.nn.graph.ComputationGraph.outputOfLayersDetached(ComputationGraph.java:2424)
            at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1737)
            at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1666)
            at net.gowrite.dcnn.batching.FastBatchPrediction$Evaluator.run(FastBatchPrediction.java:99)
            Suppressed: java.lang.RuntimeException: cudaStreamSynchronize(...) failed
                    at org.nd4j.nativeblas.Nd4jCuda$NativeOps.streamSynchronize(Native Method)
                    at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:131)
                    at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:121)
                    at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.commit(CudaExecutioner.java:1866)
                    at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:602)
                    at net.gowrite.dcnn.batching.FastBatchPrediction$Evaluator.run(FastBatchPrediction.java:92)

**Comment by JSpiegel** [comment]
I finally managed to create an example that causes the crash for me:
[https://gist.github.com/JSpiegel/207448c080af1501bab458a653c4e84c](url)

The example creates a random CSV dataset at the specified location, reads it , applies some transformations and trains a simple network.
The crash only seems to happen with larger batch sizes(>= 512). I want to use those because with smaller sizes, the GPU is utilized insufficiently(below 50% utilization). As mentioned before, the GPU memory is not fully utilized yet(GPU-Z shows about 2.8GB of the available 4GB used), so that should not be the issue.
Usually, it does not take long for the crash to occur. The time is not deterministic as the problem seems to be related to some kind of race condition.
If further information is needed, please let me know.

**Comment by raver119** [comment]
Thanks!

**Comment by agibsonccc** [comment]
Closing — the CUDA backend has been completely rewritten with new memory management, DSP execution engine, CUDA graph replay, and Triton compilation. If you still experience GPU-related issues with the upcoming release, please open a new issue.
