### ISSUE TITLE
DL4J: Async/Joint iterator can get stuck after exception in underlying iter?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7828]
The OOM was due to a memory shortage on system (unrelated to this test).
However, after this, the test just got stuck, never proceeding. Hypothetically, other exceptions could cause a similar issue?

```
o.d.BaseDL4JTest - JointParallelDataSetIteratorTest.testJointIterator1
Exception in thread "ADSI prefetch thread" Exception in thread "ADSI prefetch thread" java.lang.OutOfMemoryError: Failed to allocate [10486784] bytes
	at org.nd4j.linalg.cpu.nativecpu.CpuMemoryManager.allocate(CpuMemoryManager.java:51)
	at org.nd4j.linalg.cpu.nativecpu.workspace.CpuWorkspace.init(CpuWorkspace.java:99)
	at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.initializeWorkspace(Nd4jWorkspace.java:510)
	at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:653)
	at org.nd4j.linalg.dataset.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:422)
java.lang.OutOfMemoryError: Failed to allocate [10486784] bytes
	at org.nd4j.linalg.cpu.nativecpu.CpuMemoryManager.allocate(CpuMemoryManager.java:51)
	at org.nd4j.linalg.cpu.nativecpu.workspace.CpuWorkspace.init(CpuWorkspace.java:99)
	at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.initializeWorkspace(Nd4jWorkspace.java:510)
	at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:653)
	at org.nd4j.linalg.dataset.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:422)
```

Relevant parts of thread dump: https://gist.github.com/AlexDBlack/a89a94ad94f4ecafcd7ac242dc00e95b

**Comment by agibsonccc** [comment]
Closing — references a removed/rewritten subsystem (DataVec, NLP/Word2Vec, Model Zoo, Spark, UI, or Arbiter). These have been fundamentally rewritten or removed in the upcoming release. Please open a new issue if you experience similar problems with the new version.
