### ISSUE TITLE
Op.X must have same data type as Op.Y: X.datatype=FLOAT, Y.datatype=DOUBLE

### ISSUE THREAD

**Issue by 11aleksandrmd11** [deeplearning4j/deeplearning4j#7841]
#### Issue Description
An error occurs during the test run
Please describe our issue, along with:
- encountered behavior
```
Exception in thread "main" java.lang.IllegalArgumentException: Op.X must have same data type as Op.Y: X.datatype=FLOAT, Y.datatype=DOUBLE
       at org.nd4j.base.Preconditions.throwEx(Preconditions.java:636)
       at org.nd4j.base.Preconditions.checkArgument(Preconditions.java:137)
       at org.nd4j.linalg.api.ops.BaseBroadcastOp.validateDataTypes(BaseBroadcastOp.java:218)
       at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:866)
       at org.nd4j.linalg.factory.Broadcast.mul(Broadcast.java:143)
       at org.deeplearning4j.nn.layers.objdetect.YoloUtils.activate(YoloUtils.java:67)
       at org.deeplearning4j.nn.layers.objdetect.Yolo2OutputLayer.activate(Yolo2OutputLayer.java:391)
       at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:111)
       at org.deeplearning4j.nn.graph.ComputationGraph.outputOfLayersDetached(ComputationGraph.java:2355)
       at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1789)
       at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1771)
       at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1757)
       at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1635)
```

#### Version Information

Please indicate relevant versions, including, if relevant:

Windows 7
<Deeplearning4j.version> 1.0.0-beta4 </deeplearning4j.version>
<Nd4j.version> 1.0.0-beta4 </nd4j.version>
<Datavec.version> 1.0.0-beta4 </datavec.version>

#### Contributing
If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!
          

  
```
Random rng = new Random(seed);
             RandomPathFilter pathFilter = new RandomPathFilter(rng) {
                    protected boolean accept(String name) {
                           // name = name.replace(".png", ".xml");
                           File file = null;
                           try {
                                  file = new File(new URI(name));
                           } catch (URISyntaxException e) {
                                  file = new File(name);
                           }
                           return name.contains(".png") && file.exists();

                    }
             };
             InputSplit[] date = new FileSplit(file, NativeImageLoader.ALLOWED_FORMATS, rng).sample(pathFilter, 0.8, 0.2);
             InputSplit trainDate = date[0];
             InputSplit testDate = date[1];

             ObjectDetectionRecordReader recordReaderTtain = new ObjectDetectionRecordReader(inputShape[2], inputShape[1],
                           inputShape[0], gridH, gridW, new VocLabelProvider(file.getAbsolutePath()));
             recordReaderTtain.initialize(trainDate);
             recordReaderTtain.setLabels(dateClassesList);
             ObjectDetectionRecordReader recordReaderTest = new ObjectDetectionRecordReader(inputShape[2], inputShape[1],
                           inputShape[0], gridH, gridW, new VocLabelProvider(file.getAbsolutePath()));
             recordReaderTest.initialize(testDate);
             recordReaderTest.setLabels(dateClassesList);

             train = new RecordReaderDataSetIterator(recordReaderTtain, batchSize, 1, 1, true);
             train.setPreProcessor(new ImagePreProcessingScaler(0, 1));

             test = new RecordReaderDataSetIterator(recordReaderTest, 1, 1, 1, true);
             test.setPreProcessor(new ImagePreProcessingScaler(0, 1));
             test.setCollectMetaData(true);


org.nd4j.linalg.dataset.DataSet dataSet = test.next();
                    RecordMetaDataImageURI metaData = (RecordMetaDataImageURI) dataSet.getExampleMetaData().get(0);
                    INDArray features = dataSet.getFeatures();
                    INDArray results = model.outputSingle(features);
```

**Comment by AlexDBlack** [comment]
This has already been fixed on master/snapshots.

Are you configuring the bounding box sizes in your Yolo2OutputLayer?
If so, add a .castTo(DataType.FLOAT) at the end of the INDArray you are setting for the bounding box sizes.

**Comment by 11aleksandrmd11** [comment]
Thank! Understood what's the matter.
only priors.castTo (DataType.FLOAT) did not work
also did not help dataSet.getFeatures().castTo(DataType.DOUBLE)
helped only change the data type to float priorBoxes
INDArray priors = Nd4j.create(priorBoxes);
.addLayer("outputs", new Yolo2OutputLayer.Builder().boundingBoxPriors(priors).build(),
                                        "convolution2d_9")

**Comment by AlexDBlack** [comment]
What I meant specifically: `new Yolo2OutputLayer.Builder().boundingBoxPriors(priors.castTo(DataType.FLOAT)).build()`

That should work, which I think is what you did.
Anyway, as this has already been fixed on master/snapshots, I'll close this issue as resolved. Thanks for flagging the issue though.
