### ISSUE TITLE
Issue with loading CSV and tab-delimited files

### ISSUE THREAD

**Issue by admcl** [deeplearning4j/deeplearning4j#791]
Reading CSV and tab-delimited files of numeric data produces a cryptic error.  Below is a short example program that demonstrates the problem and the resulting stack trace.

```
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Random;

import org.canova.api.records.reader.RecordReader;
import org.canova.api.records.reader.impl.CSVRecordReader;
import org.canova.api.split.FileSplit;
import org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator;
import org.deeplearning4j.datasets.iterator.DataSetIterator;
import org.nd4j.linalg.dataset.DataSet;
import org.springframework.core.io.ClassPathResource;

public class CSVProblem {

	
	public static void main(String[] args) throws IOException, InterruptedException {
		makeRandomCSV("./target/classes/rand.csv");
		RecordReader testReader = new CSVRecordReader();
        testReader.initialize(new FileSplit(new ClassPathResource("rand.csv").getFile()));
        DataSetIterator iter = new RecordReaderDataSetIterator(testReader,null,1000,0,1,true);
        DataSet test = iter.next();
        System.err.println("Compelte.  Test length = " + test.numExamples());
	}
	
	
	public static void makeRandomCSV(String tempFile) {
		File temp = new File(tempFile);
		temp.deleteOnExit();
		Random rand = new Random(12345);
		try (PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(temp)))) {
			for (int i = 0; i < 4500; i++) {
				out.print(rand.nextDouble());
				for (int j = 0; j < 256; j++) {
					out.print("," + rand.nextDouble());
				}
				out.println();
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}

```

...Produces (my username removed from console output):

```
Oct 20, 2015 11:56:28 AM com.github.fommil.jni.JniLoader liberalLoad
INFO: successfully loaded /var/folders/zs/wkjnt2q52tzb48c7cw4l8y15z7k_6q/T/jniloader5794352939391595444netlib-native_system-osx-x86_64.jnilib
11:56:28.429 [main] DEBUG org.reflections.Reflections - going to scan these urls:
jar:file:/Users/****/.m2/repository/org/nd4j/nd4j-bytebuddy/0.4-rc3.5/nd4j-bytebuddy-0.4-rc3.5.jar!/
jar:file:/Users/****/.m2/repository/org/nd4j/nd4j-x86/0.4-rc3.5/nd4j-x86-0.4-rc3.5.jar!/
jar:file:/Users/****/.m2/repository/org/nd4j/nd4j-api/0.4-rc3.5/nd4j-api-0.4-rc3.5.jar!/
11:56:28.532 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/linalg/cpu/javacpp/linux-x86_64/libjniLoop.so in url jar:file:/Users/****/.m2/repository/org/nd4j/nd4j-x86/0.4-rc3.5/nd4j-x86-0.4-rc3.5.jar!/ with scanner SubTypesScanner
11:56:28.533 [main] DEBUG org.reflections.Reflections - could not scan file org/nd4j/linalg/cpu/javacpp/linux-x86_64/libjniLoop.so in url jar:file:/Users/****/.m2/repository/org/nd4j/nd4j-x86/0.4-rc3.5/nd4j-x86-0.4-rc3.5.jar!/ with scanner TypeAnnotationsScanner
11:56:28.578 [main] INFO  org.reflections.Reflections - Reflections took 144 ms to scan 3 urls, producing 85 keys and 378 values 
Exception in thread "main" java.lang.IllegalArgumentException: Illegal index [0, 256]
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putScalar(BaseNDArray.java:1116)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putScalar(BaseNDArray.java:1093)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.getDataSet(RecordReaderDataSetIterator.java:222)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:154)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:297)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:45)
	at CSVProblem.main(CSVProblem.java:26)
```

System is OSX 10.10.3, running JDK 1.8.0.45 in Eclipse Mars.

**Comment by admcl** [comment]
Issue appears to be connected with the LabelIndex argument of RecordReaderDataSetIterator().  You can recreate this problem int he RegressionExample of the DL4J examples by setting the labelIndex argument to 0.

**Comment by AlexDBlack** [comment]
Fixed:
https://github.com/deeplearning4j/deeplearning4j/pull/892
