### ISSUE TITLE
Word2VecTests#testRunWord2Vec fails

### ISSUE THREAD

**Issue by carschno** [deeplearning4j/deeplearning4j#824]
This exception occurs in `Word2VecTests#testRunWord2Vec()` after the #823 has been fixed:

```
Okt 29, 2015 4:47:39 PM com.github.fommil.jni.JniLoader liberalLoad
INFORMATION: successfully loaded /tmp/jniloader6558388166353965733netlib-native_system-linux-x86_64.so
o.s.v.DataBinder - DataBinder requires binding of required fields [sentenceModelPath,sentenceTypeName]
o.s.v.DataBinder - DataBinder requires binding of required fields [rootFile]
o.d.t.i.LuceneInvertedIndex - Creating directory word2vec-index

java.lang.RuntimeException: java.lang.IllegalArgumentException: Missing scheme
	at org.deeplearning4j.text.invertedindex.LuceneInvertedIndex.initReader(LuceneInvertedIndex.java:302)
	at org.deeplearning4j.text.invertedindex.LuceneInvertedIndex.<init>(LuceneInvertedIndex.java:103)
	at org.deeplearning4j.text.invertedindex.LuceneInvertedIndex.<init>(LuceneInvertedIndex.java:112)
	at org.deeplearning4j.text.invertedindex.LuceneInvertedIndex$Builder.build(LuceneInvertedIndex.java:903)
	at org.deeplearning4j.models.word2vec.Word2Vec.buildVocab(Word2Vec.java:276)
	at org.deeplearning4j.models.word2vec.Word2Vec.fit(Word2Vec.java:104)
	at org.deeplearning4j.models.word2vec.Word2VecTests.testRunWord2Vec(Word2VecTests.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.IllegalArgumentException: Missing scheme
	at java.nio.file.Paths.get(Paths.java:134)
	at org.deeplearning4j.text.invertedindex.LuceneInvertedIndex.ensureDirExists(LuceneInvertedIndex.java:547)
	at org.deeplearning4j.text.invertedindex.LuceneInvertedIndex.initReader(LuceneInvertedIndex.java:284)
	... 33 more
```

**Comment by agibsonccc** [comment]
This might be related to the lucene version upgrade.
