### ISSUE TITLE
Automatic differentiation always throws exceptions in GPU environments

### ISSUE THREAD

**Issue by zdl010** [deeplearning4j/deeplearning4j#8240]
#### Version Information
Please indicate relevant versions, including, if relevant:

* Deeplearning4j 1.0.0-beta5
* win10
* CUDA version，9.2

1、LayerNormaliztion

public class LayerNormaliztion extends SameDiffLayer {
	
	// gain * standardize(x) + bias
	
	private double  eps = 1e-5;
	 
	 private static String GAIN="gain";
	 private static String BIAS="bias";

    private int nOut;
    private int timeStep;

  
    public LayerNormaliztion( int nOut,int timeStep){
    	this.timeStep=timeStep;
        this.nOut = nOut;
    }

    protected LayerNormaliztion(){
    	
    }

    @Override
    public InputType getOutputType(int layerIndex, InputType inputType) {
        return InputType.recurrent(nOut);
    }

    
    @Override
    public void defineParameters(SDLayerParams params) {
        params.addWeightParam(GAIN, timeStep);
        params.addWeightParam(BIAS, timeStep);
    }

 
    @Override
    public SDVariable defineLayer(SameDiff sd, SDVariable layerInput, Map<String, SDVariable> paramTable, SDVariable mask) {
    	  SDVariable gain=paramTable.get(GAIN);
    	  SDVariable bias=paramTable.get(BIAS);
    	  SDVariable mean= sd.mean("mean",layerInput,true, 1);
          SDVariable variance= sd.variance("variance", layerInput, false,true, 1);
          SDVariable  standardDeviation=sd.math().sqrt("standardDeviation", variance.add(eps));
          long[] maskShape= mask.getShape();
    	return gain.mul(layerInput.sub(mean).div(standardDeviation)).add(bias).mul(mask.reshape(maskShape[0],1,timeStep));
    	 
       // return  sd.nn().layerNorm( layerInput, gain, bias, false, 1).mul(mask.reshape(maskShape[0],1,timeStep));
    	
    }

    @Override
    public void initializeParameters(Map<String, INDArray> params) {
        params.get(GAIN).assign(1);
        params.get(BIAS).assign(0);
    }

    public int getNOut() {
        return nOut;
    }

    public void setNOut(int nOut) {
        this.nOut = nOut;
    }

	public int getTimeStep() {
		return timeStep;
	}

	public void setTimeStep(int timeStep) {
		this.timeStep = timeStep;
	}

}

2、The network structure

ComputationGraphConfiguration config = new NeuralNetConfiguration.Builder()
				.weightInit(WeightInit.XAVIER).updater(new Adam(0.001))
				.l2(0.0001).graphBuilder().addInputs("input")
				.setInputTypes(InputType.recurrent(wordMap.size()))
				.addLayer("embedding",
						new EmbeddingLayer.Builder().activation(Activation.TANH).nIn(wordMap.size()).nOut(100).build(), "input")
				.addVertex("preprocessor", new PreprocessorVertex(new FeedForwardToRnnPreProcessor() ), "embedding")
				.addLayer("lstm1", new Bidirectional(Bidirectional.Mode.CONCAT,
						new LSTM.Builder().nIn(100).nOut(50)
						.activation(Activation.TANH).build()), "preprocessor")
				.addLayer("ln1",  new LayerNormaliztion(100,maxLength), "lstm1")
				.addLayer("lstm2", new Bidirectional(Bidirectional.Mode.CONCAT,
						new LSTM.Builder().nIn(100).nOut(50)
						.activation(Activation.TANH).build()), "ln1")
				.addLayer("ln2",  new LayerNormaliztion(100,maxLength), "lstm2")
				//.addVertex("merge", new MergeVertex(), "lstm1","lstm2")
				.addLayer("lstm", new LSTM.Builder().nIn(100).nOut(100)
						.activation(Activation.TANH).build(), "ln2")
				.addLayer("ln3",  new LayerNormaliztion(100,maxLength), "lstm")
				.addVertex("thoughtVector", new LastTimeStepVertex("input"), "ln3")
				.addLayer("out1",
						new OutputLayer.Builder().lossFunction(LossFunctions.LossFunction.XENT)
								.activation(Activation.SIGMOID).nIn(100).nOut(1) 
								.build(),
						"thoughtVector")
				.setOutputs("out1")
				.build();

		ComputationGraph net = new ComputationGraph(config);
		net.init();

3、exception
Exception in thread "main" java.lang.RuntimeException: Op [divide_bp] execution failed
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2307)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputsHelper(InferenceSession.java:505)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:119)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:56)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:335)
	at org.nd4j.autodiff.samediff.SameDiff.directExecHelper(SameDiff.java:3181)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:4693)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:4657)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:4666)
	at org.deeplearning4j.nn.layers.samediff.SameDiffLayer.backpropGradient(SameDiffLayer.java:159)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doBackward(LayerVertex.java:149)
	at org.deeplearning4j.nn.graph.ComputationGraph.calcBackpropGradients(ComputationGraph.java:2712)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1381)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1341)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:170)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1165)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1115)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1082)
	at org.deeplearning4j.AttentionClassifyTrained.main(AttentionClassifyTrained.java:209)
Caused by: java.lang.RuntimeException: [DEVICE] allocation failed; Error code: [2]
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2491)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2297)
	... 20 more

4、There are warning messages when the program starts

o.d.u.p.PlayUIServer - StatsStorage instance attached to UI: InMemoryStatsStorage(uid=318e7faa)
o.n.a.f.DifferentialFunction - No fields found for property name biasCorrected for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name mean for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name bias for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name biasCorrected for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name mean for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name bias for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name biasCorrected for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name mean for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name bias for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean

**Comment by zdl010** [comment]
@AlexDBlack

**Comment by raver119** [comment]
Does it fail on first iteration? Or after some number of iterations?

**Comment by zdl010** [comment]
@raver119 after some number of iterations

**Comment by raver119** [comment]
Sorry, there's a leak then. GPU code was finalized few days before release, so there might be issues... I'd propose to wait till this issue is fixed on snapshots.

**Comment by zdl010** [comment]
@raver119 What causes it？

**Comment by raver119** [comment]
If i knew answer, I'd just push fix. We'll need to find it first.

**Comment by zdl010** [comment]
I have an important feature that I need to implement with SameDiff. Can you fix it today? Thanks

**Comment by raver119** [comment]
Sure I'll fix it asap, but we provide no guarantees on time.

**Comment by zdl010** [comment]
@raver119 Warning message, will it affect the use of SameDiff？

**Comment by raver119** [comment]
Which warning message?

**Comment by zdl010** [comment]
@raver119 o.n.a.f.DifferentialFunction - No fields found for property name biasCorrected for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name mean for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name bias for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name biasCorrected for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name mean for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name bias for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name biasCorrected for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name mean for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean
o.n.a.f.DifferentialFunction - No fields found for property name bias for class org.nd4j.linalg.api.ops.impl.reduce.floating.Mean

**Comment by zdl010** [comment]
Did you find the problem？

**Comment by zdl010** [comment]
@raver119

**Comment by zdl010** [comment]
@raver119 [test-samediff.zip](https://github.com/eclipse/deeplearning4j/files/3700772/test-samediff.zip)

**Comment by agibsonccc** [comment]
Closing — references a removed/rewritten subsystem (DataVec, NLP/Word2Vec, Model Zoo, Spark, UI, or Arbiter). These have been fundamentally rewritten or removed in the upcoming release. Please open a new issue if you experience similar problems with the new version.
