### ISSUE TITLE
CC 3.0 still not supported

### ISSUE THREAD

**Issue by GPSforLEGENDS** [deeplearning4j/deeplearning4j#8255]
#### Issue Description

https://github.com/eclipse/deeplearning4j/issues/8018 is not fixed
GPUs with CC 3.0 are still not supported.

Please describe our issue, along with:

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
1.0.0-beta5
* Platform information (OS, etc)
Windows 10
* CUDA version, if used
release 10.1, V10.1.243
* NVIDIA driver version, if in use
V436.30

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
ND4J CUDA build version: 10.1.243
CUDA device 0: [GeForce GTX 770]; cc: [3.0]; Total memory: [2147483648];
o.n.n.NativeOpsHolder - Number of threads used for OpenMP: 32
o.n.n.Nd4jBlas - Number of threads used for OpenMP BLAS: 0
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [3,5GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.o.e.CudaExecutioner - Device Name: [GeForce GTX 770]; CC: [3.0]; Total/free memory: [2147483648]
o.d.n.g.ComputationGraph - Starting ComputationGraph with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [DEVICE]
Exception in thread "main" java.lang.RuntimeException: cudaGetSymbolAddress(...) failed; Error code: [13]
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.createShapeInfo(CudaExecutioner.java:2557)
	at org.nd4j.linalg.api.shape.Shape.createShapeInformation(Shape.java:3282)
	at org.nd4j.linalg.api.ndarray.BaseShapeInfoProvider.createShapeInformation(BaseShapeInfoProvider.java:76)
	at org.nd4j.jita.constant.ProtectedCudaShapeInfoProvider.createShapeInformation(ProtectedCudaShapeInfoProvider.java:96)
	at org.nd4j.jita.constant.ProtectedCudaShapeInfoProvider.createShapeInformation(ProtectedCudaShapeInfoProvider.java:77)
	at org.nd4j.linalg.jcublas.CachedShapeInfoProvider.createShapeInformation(CachedShapeInfoProvider.java:44)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:211)
	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:383)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:1543)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:1538)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4298)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3986)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:536)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:440)
	at org.deeplearning4j.zoo.model.VGG16.init(VGG16.java:178)
	at org.deeplearning4j.examples.multigpu.vgg16.MultiGpuVGG16TinyImageNetExample.main(MultiGpuVGG16TinyImageNetExample.java:61)

Process finished with exit code 1

**Comment by dvdmchl** [comment]
I have the same problem with CC 5.0:
`ND4J CUDA build version: 10.1.243
CUDA device 0: [GeForce GTX 950M]; cc: [5.0]; Total memory: [4294967296];
Exception in thread "main" java.lang.RuntimeException: cudaGetSymbolAddress(...) failed; Error code: [13]
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.createShapeInfo(CudaExecutioner.java:2557)
	at org.nd4j.linalg.api.shape.Shape.createShapeInformation(Shape.java:3282)
	at org.nd4j.linalg.api.ndarray.BaseShapeInfoProvider.createShapeInformation(BaseShapeInfoProvider.java:76)
	at org.nd4j.jita.constant.ProtectedCudaShapeInfoProvider.createShapeInformation(ProtectedCudaShapeInfoProvider.java:96)
	at org.nd4j.jita.constant.ProtectedCudaShapeInfoProvider.createShapeInformation(ProtectedCudaShapeInfoProvider.java:77)
	at org.nd4j.linalg.jcublas.CachedShapeInfoProvider.createShapeInformation(CachedShapeInfoProvider.java:44)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:211)
	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:383)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:1473)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3620)
	at org.datavec.api.util.ndarray.RecordConverter.toMinibatchArray(RecordConverter.java:198)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:160)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:377)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:452)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:85)
	at test.neural.CSVExample.main(CSVExample.java:67)`

**Comment by raver119** [comment]
cc @AlexDBlack

**Comment by saudet** [comment]
CC 5.0 is not in the list of architectures libnd4j gets built against:
https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/blas/CMakeLists.txt#L178

**Comment by raver119** [comment]
Yes, it's supposed to be one per generation. We hadn't tested 5.0 specifically, but we've tested compatibility between 6.0 <--> 6.1, 7.0 <--> 7.5 etc.

**Comment by dvdmchl** [comment]
So basically I should buy a new machine with more recent GPU to get it working?

**Comment by raver119** [comment]
No, you can build it locally while we're trying to figure out what could be done here, without bloating binary size...

**Comment by saudet** [comment]
`sed -i 's/_52/_50/g' libnd4j/blas/CMakeLists.txt` should do the trick :)

**Comment by saudet** [comment]
And also a `sed -i 's/_35/_30/g' libnd4j/blas/CMakeLists.txt`

**Comment by raver119** [comment]
If you compile for 1 arch, you can just pass `-cc 30` as argument for CUDA. or `-cc 50`

**Comment by saudet** [comment]
@raver119 Yes, ok, but why are you building against 3.5 and 5.2 instead of 3.0 and 5.0 by default?

**Comment by zealbell** [comment]
> Yes, it's supposed to be one per generation. We hadn't tested 5.0 specifically, but we've tested compatibility between 6.0 <--> 6.1, 7.0 <--> 7.5 etc.

Also have the same problem [GeForce 940MX]; CC: [5.0]. Are there any plans of resolving this issue with future updates

> If you compile for 1 arch, you can just pass -cc 30 as argument for CUDA. or -cc 50

Not sure I quite understand this

**Comment by agibsonccc** [comment]
Closing due to inactivity.
