### ISSUE TITLE
RecordReaderDataSetIterator / DataSetIterator not loading data from recordreader

### ISSUE THREAD

**Issue by ssy248** [deeplearning4j/deeplearning4j#8271]
I try to run my code that is posted here https://github.com/ssy248/deeplearningjava/blob/master/deeplearning2.java

And the record reader on line 181 does load and print from the csv data.
However, at line 207, there is an error given by the following ( it seems that the DataSetIterator is not able to load the data and there is null instead) 

Exception in thread "main" java.lang.NumberFormatException: empty String

	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
	at java.lang.Double.parseDouble(Unknown Source)
	at org.datavec.api.writable.Text.toDouble(Text.java:596)
	at org.datavec.api.util.ndarray.RecordConverter.toMinibatchArray(RecordConverter.java:183)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:160)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:365)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:440)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:84)
	at javaspark.deeplearning2.main(deeplearning2.java:207)

**Comment by agibsonccc** [comment]
Closing — references a removed/rewritten subsystem (DataVec, NLP/Word2Vec, Model Zoo, Spark, UI, or Arbiter). These have been fundamentally rewritten or removed in the upcoming release. Please open a new issue if you experience similar problems with the new version.
