### ISSUE TITLE
Platform "android-x86" not supported by class org.bytedeco.hdf5.global.hdf5

### ISSUE THREAD

**Issue by aungpyaekyaw** [deeplearning4j/deeplearning4j#8274]
#### Platform "android-x86" not supported by class org.bytedeco.hdf5.global.hdf5

I'm trying to import hdf5 keras model in android application and geting the
Platform "android-x86" not supported by class org.bytedeco.hdf5.global.hdf5 runtime error.

#### Version Information
* Deeplearning4j version

That is my android dependencies

compile (group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-beta4') {
            exclude group: 'org.bytedeco', module: 'opencv-platform'
            exclude group: 'org.bytedeco', module: 'leptonica-platform'
            /*exclude group: 'org.bytedeco', module: 'hdf5-platform'*/
            exclude group: 'org.nd4j', module: 'nd4j-base64'
        }

I'm trying to run on android.

#### Additional Information
 The following is my stack trace.
io.reactivex.exceptions.UndeliverableException: java.lang.UnsatisfiedLinkError: Platform "android-x86" not supported by class org.bytedeco.hdf5.global.hdf5
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.UnsatisfiedLinkError: Platform "android-x86" not supported by class org.bytedeco.hdf5.global.hdf5
        at org.bytedeco.javacpp.Loader.load(Loader.java:984)
        at org.bytedeco.javacpp.Loader.load(Loader.java:963)
        at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.<clinit>(Hdf5Archive.java:59)
        at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.modelHdf5Filename(KerasModelBuilder.java:225)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:222)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:113)
        at com.geek.vois.service.KerasHelper$1.call(KerasHelper.java:38)
        at com.geek.vois.service.KerasHelper$1.call(KerasHelper.java:31)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12030)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by saudet** [comment]
The message says it all: HDF5 doesn't support Android!
