### ISSUE TITLE
Op [reduce_sum_bp] execution failed  bug

### ISSUE THREAD

**Issue by zdl010** [deeplearning4j/deeplearning4j#8360]
#8233 ## Version Information

Please indicate relevant versions, including, if relevant:

* 1.0.0-beta5
* win10
* CUDA version,  no used

Code:
public static void main(String[] args) {

		SameDiff sd = SameDiff.create();
		SDVariable label = sd.var("label", DataType.FLOAT, new int[] { 3, 3, 4 });

		SDVariable m = sd.math().logSumExp(label, 1);
		sd.setLossVariables(m);

		ExternalErrorsFunction fn = sd.f().externalErrors(m);
		fn.outputVariable();
		System.out.println(sd.summary());
		if (!sd.hasGradientFunction()) {
			sd.createGradFunction("label");
		}
		sd.assignArray(Nd4j.rand(new int[] { 3, 3, 4 }), label);
		sd.execBackwards(null);

	}

Exception:

Mismatched shape: [2, 3, 4, 4, 1, 8192, 1, 99]
Shape requested: : {1, 1, 1}
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute op reduce_sum_bp. Attempted to execute with 2 inputs, 1 outputs, 1 targs,0 bargs and 0 iargs. Inputs: [(FLOAT,[3,3,4],c), (FLOAT,[3,4],c)]. Outputs: [(FLOAT,[3,3,4],c)]. tArgs: [0.0]. iArgs: -. bArgs: -. Op own name: "reduce_sum_bp_1". Input var names: [label, divide]. Output var names: [reduce_sum_bp_1] - Please see above message (printed out from c++) for a possible cause of error.
Exception in thread "main" java.lang.RuntimeException: Op [reduce_sum_bp] execution failed
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1710)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputsHelper(InferenceSession.java:505)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:119)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:56)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:335)
	at org.nd4j.autodiff.samediff.SameDiff.directExecHelper(SameDiff.java:3181)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:4693)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:4629)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:4587)
	at org.nd4j.autodiff.samediff.SameDiff.execBackwards(SameDiff.java:4596)
	at org.deeplearning4j.examples.LN6.main(LN6.java:66)
Caused by: java.lang.RuntimeException: NDArray::reshapei: bad input shape!
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:2006)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1700)
	... 10 more

**Comment by zdl010** [comment]
@AlexDBlack

**Comment by AlexDBlack** [comment]
What are you trying to accomplish here? i.e., what is your goal?

**Comment by zdl010** [comment]
@AlexDBlack The derivative of input to logSumExp, used for the implementation of CRF layer

**Comment by AlexDBlack** [comment]
But you're using an ExternalErrorsFunction... That's only used when you have gradients that are not coming from SameDiff...

So to be clear, your "full" network is something along the lines of:
SameDiff(label -> logsumexp) -> NotSameDiff(CRF)?
And you have gradient calculation that you want to pass in to SameDiff from the CRF implementation?

**Comment by zdl010** [comment]
@AlexDBlack "Label" is just a variable name, and the problem here is to compute the gradient to report an error

**Comment by AlexDBlack** [comment]
Ok, so this in unrelated to external errors function, it's bad LogSumExp (manually implemented) backprop here:
https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/reduce/custom/LogSumExp.java#L75-L85

**Comment by raver119** [comment]
mmm, this op definitely needs C++ implementation. cc @shugeo

**Comment by AlexDBlack** [comment]
Turns out cause was trivial mistake in constructor
https://github.com/KonduitAI/deeplearning4j/pull/35/files

**Comment by AlexDBlack** [comment]
@raver119 LogSumExp is on the list here btw: https://github.com/eclipse/deeplearning4j/issues/8099
