### ISSUE TITLE
ANDORID: java.lang.ExceptionInInitializerError at org.nd4j.nativeblas.NativeOpsHolder.getInstance  and java.lang.UnsatisfiedLinkError: dlopen failed: library "libopenblas.so" not found

### ISSUE THREAD

**Issue by SiR0N** [deeplearning4j/deeplearning4j#8372]
Hello,
I want to run in Android version 28 on x86_64 device. I followed the tutorial [here](https://deeplearning4j.org/docs/latest/deeplearning4j-android-prerequisites)

My dependencies: 
```
implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:2.0.0-beta2'
    

    //DL4J
    compileOnly "org.projectlombok:lombok:1.18.10"
    annotationProcessor 'org.projectlombok:lombok:1.18.10'
    implementation (group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-beta4') {
        exclude group: 'org.bytedeco.javacpp-presets', module: 'opencv-platform'
        exclude group: 'org.bytedeco.javacpp-presets', module: 'leptonica-platform'
        exclude group: 'org.bytedeco.javacpp-presets', module: 'hdf5-platform'
        exclude group: 'org.nd4j', module: 'nd4j-base64'
    }
    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta4'
    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta4', classifier: "android-x86_64"
```

I tested wih 1.0.0-beta5 version and I got erros as well.

The error appears at running:

```
 public float[] getFloatArrayFromResizedImage(Bitmap bm,int reqCH, int reqW, int reqH ) throws IOException {
  
      NativeImageLoader  loader = new NativeImageLoader (reqH, reqW, reqCH);
//I also tried with AndroidNativeImageLoader and I got the same error
      ImagePreProcessingScaler imagePreProcessingScaler = new ImagePreProcessingScaler(0, 1);

      INDArray indArray =  loader.asMatrix(bm);  //Error here
      imagePreProcessingScaler.transform(indArray);
      
return indArray.toFloatVector();
    }
```
Error:
```
java.lang.ExceptionInInitializerError
        at org.nd4j.nativeblas.NativeOpsHolder.getInstance(NativeOpsHolder.java:75)
        at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:88)
        at java.lang.Class.newInstance(Native Method)
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5858)
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5766)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:202)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4114)
        at org.datavec.image.loader.NativeImageLoader.transformImage(NativeImageLoader.java:624)
        at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:546)
        at org.datavec.image.loader.AndroidNativeImageLoader.asMatrix(AndroidNativeImageLoader.java:67)
        at org.datavec.image.loader.AndroidNativeImageLoader.asMatrix(AndroidNativeImageLoader.java:77)
        at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:352)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
        at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:68)
        at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:36)
        at org.nd4j.nativeblas.NativeOpsHolder.getInstance(NativeOpsHolder.java:75) 
        at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:88) 
        at java.lang.Class.newInstance(Native Method) 
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5858) 
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5766) 
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:202) 
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4114) 
        at org.datavec.image.loader.NativeImageLoader.transformImage(NativeImageLoader.java:624) 
        at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:546) 
        at org.datavec.image.loader.AndroidNativeImageLoader.asMatrix(AndroidNativeImageLoader.java:67) 
         
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libopenblas.so" not found
```

I realize that if I go to NativeOpsHolder and NativeOpExecutioner there is one message: 
```
Library source does not match the bytecode off class NativeOpsHolder 
```

Any advice to solve this problem?

**Comment by saudet** [comment]
You'll need to the "openblas" module as well...

**Comment by SiR0N** [comment]
hi, thanks for your quick reply

I added it:

```
implementation group: 'org.bytedeco.javacpp-presets', name: 'openblas', version: '0.3.3-1.4.3'
   implementation group: 'org.bytedeco.javacpp-presets', name: 'openblas', version: '0.3.3-1.4.3', classifier: "android-x86_64"
```
I got one warning:
```
W/linker: Warning: "/data/app/myapp-hHWTDWSH__Nv5RZYcE3xEw==/lib/x86_64/libjniopenblas_nolapack.so" unused DT entry: DT_RPATH (type 0xf arg 0xa0e6) (ignoring)
```
lot of errors with this format (about 500 lines)
```
E/linker: library "/system/bin/linker64" ("/system/bin/linker64") needed or dlopened by "/data/app/myapp-hHWTDWSH__Nv5RZYcE3xEw==/lib/x86_64/libjnind4jcpu.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/myapp-hHWTDWSH__Nv5RZYcE3xEw==/lib/x86_64:/data/app/myapp-hHWTDWSH__Nv5RZYcE3xEw==/base.apk!/lib/x86_64:/data/app/.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_dependencies_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_resources_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_slice_0_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_slice_1_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_slice_2_apk.apk!/l
E/linker: library "/system/lib64/libandroid_runtime.so" ("/system/lib64/libandroid_runtime.so") needed or dlopened by "/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/lib/x86_64/libjnind4jcpu.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/base.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_dependencies_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_resources_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_slice_0_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_slice_1_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw=

E/linker: library "/system/lib64/libselinux.so" ("/system/lib64/libselinux.so") needed or dlopened by "/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/lib/x86_64/libjnind4jcpu.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/base.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_dependencies_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_resources_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_slice_0_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_slice_1_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_slic
    library "/system/lib64/libmedia.so" ("/system/lib64/libmedia.so") needed or dlopened by "/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/lib/x86_64/libjnind4jcpu.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/base.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_dependencies_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_resources_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_slice_0_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_slice_1_apk.apk!/lib/x86_64:/data/app/myapp.-hHWTDWSH__Nv5RZYcE3xEw==/split_lib_slice_2_
```
and: 
```
 No implementation found for void org.bytedeco.openblas.presets.openblas_nolapack$SetNumThreads.allocate() (tried Java_org_bytedeco_openblas_presets_openblas_1nolapack_00024SetNumThreads_allocate and Java_org_bytedeco_openblas_presets_openblas_1nolapack_00024SetNumThreads_allocate__)
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: myapp., PID: 21192
    java.lang.UnsatisfiedLinkError: No implementation found for void org.bytedeco.openblas.presets.openblas_nolapack$SetNumThreads.allocate() (tried Java_org_bytedeco_openblas_presets_openblas_1nolapack_00024SetNumThreads_allocate and Java_org_bytedeco_openblas_presets_openblas_1nolapack_00024SetNumThreads_allocate__)
        at org.bytedeco.openblas.presets.openblas_nolapack$SetNumThreads.allocate(Native Method)
        at org.bytedeco.openblas.presets.openblas_nolapack$SetNumThreads.<init>(openblas_nolapack.java:162)
        at org.bytedeco.openblas.presets.openblas_nolapack.blas_set_num_threads(openblas_nolapack.java:215)
        at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.setMaxThreads(CpuBlas.java:135)
        at org.nd4j.nativeblas.Nd4jBlas.<init>(Nd4jBlas.java:52)
        at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.<init>(CpuBlas.java:30)
        at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createBlas(CpuNDArrayFactory.java:93)
        at org.nd4j.linalg.factory.BaseNDArrayFactory.blas(BaseNDArrayFactory.java:68)
        at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.getEnvironmentInformation(NativeOpExecutioner.java:1185)
        at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.printEnvironmentInformation(DefaultOpExecutioner.java:651)
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5878)
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5766)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:202)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4114)
        at org.datavec.image.loader.NativeImageLoader.transformImage(NativeImageLoader.java:624)
        at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:546)
        at org.datavec.image.loader.AndroidNativeImageLoader.asMatrix(AndroidNativeImageLoader.java:67)
        at 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by saudet** [comment]
You're not adding the right version. Try to use the same one that is used in the examples.

**Comment by SiR0N** [comment]
Hi, I figured out the problem: 
I added these dependencies:
```
implementation (group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-beta4') {
        exclude group: 'org.bytedeco', module: 'opencv-platform'
        exclude group: 'org.bytedeco', module: 'leptonica-platform'
        exclude group: 'org.bytedeco', module: 'hdf5-platform'
        exclude group: 'org.nd4j', module: 'nd4j-base64'
    }
    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta4'
    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta4', classifier: "android-x86_64"

    implementation group: 'org.bytedeco', name: 'openblas', version: '0.3.5-1.5'
    implementation group: 'org.bytedeco', name: 'openblas', version: '0.3.5-1.5', classifier: "android-x86_64"

    implementation group: 'org.bytedeco', name: 'opencv', version: '4.0.1-1.5'
    implementation group: 'org.bytedeco', name: 'opencv', version: '4.0.1-1.5', classifier: "android-x86_64"

    implementation group: 'org.bytedeco', name: 'leptonica', version: '1.78.0-1.5'
    implementation group: 'org.bytedeco', name: 'leptonica', version: '1.78.0-1.5', classifier: "android-x86_64"
```
As it is in [here](https://github.com/eclipse/deeplearning4j/commit/5027e7c77bbca782b8c8aefbffa79622458ef961)


btw, it seems that the return array is null here:
```
public float[] getFloatArrayFromResizedImage(Bitmap bm,int reqCH, int reqW, int reqH ) throws IOException {
  
      NativeImageLoader  loader = new NativeImageLoader (reqH, reqW, reqCH);

      ImagePreProcessingScaler imagePreProcessingScaler = new ImagePreProcessingScaler(0, 1);

      INDArray indArray =  loader.asMatrix(bm);  //Error here
      imagePreProcessingScaler.transform(indArray);
      
return indArray.toFloatVector();
    }

```
and I got this error:
```
: Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (light greylist, reflection)
I/System.out: Unable to create a 1d array from a non vector! Shape: FLOAT,[1,3,416,416],c
```
any idea of the error in the code?

**Comment by saudet** [comment]
Great! As for the other question, you'll need to flatten it to make that work, for example, with possibly:
https://deeplearning4j.org/api/latest/org/nd4j/linalg/api/ndarray/INDArray.html#ravel--

**Comment by SiR0N** [comment]
now the function works ^^

my last question, I have a lot of info from the logger, like:
```
E/linker: library "/system/lib64/libcamera_metadata.so" ("/system/lib64/libcamera_metadata.so") needed or dlopened by "/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/lib/x86_64/libjnind4jcpu.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/base.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_dependencies_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_resources_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_slice_0_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_slice_1_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ=
    library "/system/lib64/libsqlite.so" ("/system/lib64/libsqlite.so") needed or dlopened by "/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/lib/x86_64/libjnind4jcpu.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/base.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_dependencies_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_resources_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_slice_0_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_slice_1_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_slice_
E/linker: library "/system/lib64/libziparchive.so" ("/system/lib64/libziparchive.so") needed or dlopened by "/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/lib/x86_64/libjnind4jcpu.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/base.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_dependencies_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_resources_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_slice_0_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_slice_1_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_li
    library "/system/lib64/libETC1.so" ("/system/lib64/libETC1.so") needed or dlopened by "/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/lib/x86_64/libjnind4jcpu.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/base.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_dependencies_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_resources_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_slice_0_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_slice_1_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_slice_2_ap
E/linker: library "/system/lib64/libhardware.so" ("/system/lib64/libhardware.so") needed or dlopened by "/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/lib/x86_64/libjnind4jcpu.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/base.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_dependencies_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_resources_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_slice_0_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_slice_1_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_sl
    library "/system/lib64/libhardware_legacy.so" ("/system/lib64/libhardware_legacy.so") needed or dlopened by "/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/lib/x86_64/libjnind4jcpu.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/base.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_dependencies_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_resources_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_slice_0_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ==/split_lib_slice_1_apk.apk!/lib/x86_64:/data/app/myapp-9c6V-RQcHIIy4UfhmsCSiQ=
E/linker: library "/system/lib64/libselinux.so" ("/system/lib64/libselinux.so") needed or dlopened by "/data/app/
```
it seems that it is working fine.
how can I remove it??

**Comment by saudet** [comment]
That's a bug in old versions of the NDK, but you can ignore that. It will go away when we upgrade the version of the NDK for the builds to r18b (or later when we get newer ones working too). @sshepel
