### ISSUE TITLE
Unable to import keras functional model

### ISSUE THREAD

**Issue by kris1710** [deeplearning4j/deeplearning4j#8373]
I am trying to import a keras functional model DEEPFM  based on [paper](https://arxiv.org/pdf/1703.04247.pdf) into DL4J. There are 3 inputs, 1 numerical and 2 embedding inputs. The model has 3 parts :
1) Linear part : 
2) Factorization Machine
3) Deep NN Part
Attaching the keras model summary and JSON file for reference:

```
Model: "model_8"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
g (InputLayer)                  (None, 1)            0                                            
__________________________________________________________________________________________________
campaign_id (InputLayer)        (None, 1)            0                                            
__________________________________________________________________________________________________
client_id (InputLayer)          (None, 1)            0                                            
__________________________________________________________________________________________________
g_2d (Dense)                    (None, 8)            16          g[0][0]                          
__________________________________________________________________________________________________
reshape_6 (Reshape)             (None, 1, 8)         0           g_2d[0][0]                       
__________________________________________________________________________________________________
campaign_idemb_2d (Embedding)   (None, 1, 8)         1968        campaign_id[0][0]                
__________________________________________________________________________________________________
client_idemb_2d (Embedding)     (None, 1, 8)         31889352    client_id[0][0]                  
__________________________________________________________________________________________________
concat_embed_2d (Concatenate)   (None, 3, 8)         0           reshape_6[0][0]                  
                                                                 campaign_idemb_2d[0][0]          
                                                                 client_idemb_2d[0][0]            
__________________________________________________________________________________________________
flat_embed_2d (Flatten)         (None, 24)           0           concat_embed_2d[0][0]            
__________________________________________________________________________________________________
dropout_3 (Dropout)             (None, 24)           0           flat_embed_2d[0][0]              
__________________________________________________________________________________________________
sum_of_tensors (Lambda)         multiple             0           concat_embed_2d[0][0]            
                                                                 square_of_tensors[0][0]          
                                                                 lambda_2[0][0]                   
__________________________________________________________________________________________________
square_of_tensors (Lambda)      (None, 3, 8)         0           concat_embed_2d[0][0]            
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 128)          3200        dropout_3[0][0]                  
__________________________________________________________________________________________________
multiply_6 (Multiply)           (None, 8)            0           sum_of_tensors[0][0]             
                                                                 sum_of_tensors[0][0]             
__________________________________________________________________________________________________
batch_normalization_3 (BatchNor (None, 128)          512         dense_3[0][0]                    
__________________________________________________________________________________________________
subtract_2 (Subtract)           (None, 8)            0           multiply_6[0][0]                 
                                                                 sum_of_tensors[1][0]             
__________________________________________________________________________________________________
dropout_4 (Dropout)             (None, 128)          0           batch_normalization_3[0][0]      
__________________________________________________________________________________________________
campaign_idemb_linear (Embeddin (None, 1, 1)         246         campaign_id[0][0]                
__________________________________________________________________________________________________
client_idemb_linear (Embedding) (None, 1, 1)         3986169     client_id[0][0]                  
__________________________________________________________________________________________________
lambda_2 (Lambda)               (None, 8)            0           subtract_2[0][0]                 
__________________________________________________________________________________________________
dense_4 (Dense)                 (None, 128)          16512       dropout_4[0][0]                  
__________________________________________________________________________________________________
g_linear (Dense)                (None, 1)            2           g[0][0]                          
__________________________________________________________________________________________________
reshape_4 (Reshape)             (None, 1)            0           campaign_idemb_linear[0][0]      
__________________________________________________________________________________________________
reshape_5 (Reshape)             (None, 1)            0           client_idemb_linear[0][0]        
__________________________________________________________________________________________________
batch_normalization_4 (BatchNor (None, 128)          512         dense_4[0][0]                    
__________________________________________________________________________________________________
linear_output (Add)             (None, 1)            0           g_linear[0][0]                   
                                                                 reshape_4[0][0]                  
                                                                 reshape_5[0][0]                  
__________________________________________________________________________________________________
fm_2d_output (Reshape)          (None, 1)            0           sum_of_tensors[2][0]             
__________________________________________________________________________________________________
deep_output (Dense)             (None, 1)            129         batch_normalization_4[0][0]      
__________________________________________________________________________________________________
3_combined (Concatenate)        (None, 3)            0           linear_output[0][0]              
                                                                 fm_2d_output[0][0]               
                                                                 deep_output[0][0]                
__________________________________________________________________________________________________
deepfm_output (Dense)           (None, 1)            4           3_combined[0][0]                 
==================================================================================================
Total params: 35,898,622
Trainable params: 35,898,110
Non-trainable params: 512
```

Attaching the scala code. I defined the **sum of tensors, square of tensors and lambda_2** layer which were then registered in scala while importing the model in DL4J. 
```
class tensors_sum extends SameDiffLambdaLayer {
  override def defineLayer(sd: SameDiff, x: SDVariable): SDVariable = x.sum(false,1)
  override def getOutputType(layerIndex: Int, inputType: InputType): InputType = inputType
}


class tensors_square extends SameDiffLambdaLayer {
  override def defineLayer(sd: SameDiff, x: SDVariable): SDVariable = x mul x
  override def getOutputType(layerIndex: Int, inputType: InputType): InputType = inputType
}

class lambda1 extends SameDiffLambdaLayer {
  override def defineLayer(sd: SameDiff, x: SDVariable): SDVariable = x.mul(0.5)

  override def getOutputType(layerIndex: Int, inputType: InputType): InputType = inputType
}

KerasLayer.registerLambdaLayer("sum_of_tensors", new tensors_sum())
    KerasLayer.registerLambdaLayer("square_of_tensors", new tensors_square())
    KerasLayer.registerLambdaLayer("lambda_2", new lambda1())
    val resourcesPath = getClass.getResource("/deep_fm_sample.h5").getPath
val model1 = KerasModelImport.importKerasModelAndWeights(resourcesPath,false)


val gu1=Nd4j.zeros(1)
    val guin = gu1.reshape(1,1)


     val c1=Nd4j.zeros(1)
    val c1in=c1.reshape(1,1)

    val c2=Nd4j.zeros(1)
    val c2in=c2.reshape(1,1)


  
    model1.outputSingle(guin,c1in,c2in)
```
 After executing this I got the following error:
```
Error at [/home/jenkins/agent/workspace/ing4j_deeplearning4j-1.0.0-beta5/libnd4j/include/ops/declarable/generic/transforms/concat.cpp:155:0]:
CONCAT op: all input arrays must have the same dimensions (except those on input axis) !
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: Op name concat failed to execute. You can't execute non-inplace CustomOp without outputs being specified
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1679)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6606)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.concat(CpuNDArrayFactory.java:557)
	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:4917)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.hstack(BaseNDArrayFactory.java:963)
	at org.nd4j.linalg.factory.Nd4j.hstack(Nd4j.java:4673)
	at org.deeplearning4j.nn.graph.vertex.impl.MergeVertex.doForward(MergeVertex.java:117)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputOfLayersDetached(ComputationGraph.java:2379)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1792)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1774)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1760)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1638)
	at Demo1$.main(Demo1.scala:76)
	at Demo1.main(Demo1.scala)
```

[model.zip](https://github.com/eclipse/deeplearning4j/files/3824344/model.zip)

I might be doing something wrong here if its not the import issue. Please help

**Comment by kris1710** [comment]
Attaching the model plot as well 
![model](https://user-images.githubusercontent.com/13129503/68477360-4ddb9a00-0253-11ea-9299-bd5cc5eda729.png)

**Comment by kris1710** [comment]
Attaching the png plot for the model, Im implementing
![model](https://user-images.githubusercontent.com/13129503/68477644-f984ea00-0253-11ea-9c8f-fd28c64cc593.png)

**Comment by AlexDBlack** [comment]
I'm going to reopen this as unresolved, as I had to revert the fix for this.
@farizrahman4u's fix does result in this case importing ok, but it does change reshape vertex behaviour for at least 6 other tests (which only check the configuration, not expected outputs, hence don't show up in unit tests - only found via breakpoint)
Keras2ModelConfigurationTest.permuteRetinaUnet, .ReshapeEmbeddingConcatTest
KerasModelEndToEndTest.importSequentialModelH5Test, .importWganGenerator, .importDcganMnistGenerator, .importDcganGenerator, 

I don't believe this can be robustly solved (without side effects) until this issue is resolved:
https://github.com/eclipse/deeplearning4j/issues/8441
I'll take this and fix it once the above is resolved.

**Comment by muzixizhu** [comment]
I tried  a method to run around the bug, that is after Embedding for 2d for catagory id features, ,we just add another  Reshape layer to force the output layer to be same with the numeric features , and   then concate them together.   then it can be load right , but I met another problem ,the testoutput is not the same with my python keras version output

**Comment by kris1710** [comment]
@muzixizhu : if you are doing deepfm on spark, i have written it in scala from scratch without using keras import. Let me know if you need any inputs towards that :)

**Comment by dkalim** [comment]
@kris1710 Can you share the deepfm on scala spark script.

**Comment by agibsonccc** [comment]
I've since fixed the mentioned issue and am closing this.
