### ISSUE TITLE
org.deeplearning4j.exception.DL4JInvalidInputException: Problem with creating array with data to predict

### ISSUE THREAD

**Issue by ppozorski** [deeplearning4j/deeplearning4j#8404]
When I run below code:
```
model.output(samples).getDouble(0);
```
I receive error:

```
org.deeplearning4j.exception.DL4JInvalidInputException: 
Cannot do forward pass in Convolution layer (layer name = conv1d_1, layer index = 0): input array channels does not match CNN layer configuration 
(data input channels = 80, [minibatch,inputDepth,height,width]=[1, 80, 3, 1]; expected input channels = 3) 
(layer name: conv1d_1, layer index: 0, layer type: Convolution1DLayer)
```
I created the data as float[] array, with length = 240. Creation of INDArray:

 `INDArray features = Nd4j.create(data, new int[]{1, 240}, 'c');`

Here is my keras model:

```
model = Sequential()
model.add(Reshape((const.PERIOD, const.N_FEATURES), input_shape=(240,)))
model.add(Conv1D(100, 10, activation='relu', input_shape=(const.PERIOD, const.N_FEATURES)))
model.add(Conv1D(100, 10, activation='relu'))
model.add(MaxPooling1D(const.N_FEATURES))
model.add(Conv1D(160, 10, activation='relu'))
model.add(Conv1D(160, 10, activation='relu'))
model.add(Flatten())
model.add(Dropout(0.5))
model.add(Dense(7, activation='softmax'))
model.summary()
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
Where PERIOD = 80, N_FEATURES = 3
```

If I set shape as:

`INDArray features = Nd4j.create(data, new int[]{240, 1});`
Then error is:
```
IllegalStateException: Input shape [240, 1] and output shape[240, 1] do not match at org.deeplearning4j.nn.modelimport.keras.preprocessors.ReshapePreprocessor.preProcess(ReshapePreprocessor.java:103) at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.jav :1256)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2340)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2303)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2294)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2281)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2377)
```

Dependencies:
```
    <dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-common</artifactId>
      <version>1.0.0-beta4</version>
    </dependency>
    <dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-core</artifactId>
      <version>1.0.0-beta4</version>
    </dependency>
    <dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-modelimport</artifactId>
      <version>1.0.0-beta4</version>
    </dependency>
    <dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-native-platform</artifactId>
      <version>1.0.0-beta4</version>
    </dependency>
```

**Comment by SelfEvoAI** [comment]
did you solved this? I have the same error?

Why `Nd4j.create(3D Array)` shape is [5,5,1], but imported  LSTM model need shape is [5,1,5] ?

**Comment by agibsonccc** [comment]
Closing — references a removed/rewritten subsystem (DataVec, NLP/Word2Vec, Model Zoo, Spark, UI, or Arbiter). These have been fundamentally rewritten or removed in the upcoming release. Please open a new issue if you experience similar problems with the new version.
