### ISSUE TITLE
Error in reloading saved network in DBNIrisExample with new version of dl4j

### ISSUE THREAD

**Issue by Shima32** [deeplearning4j/deeplearning4j#841]
When i run DBNIrisExample with new version of dl4j,i get  this error : 

 Exception in thread "main" java.lang.IllegalArgumentException: Unable to set parameters: must be of length 12
	at org.deeplearning4j.nn.layers.BaseLayer.setParams(BaseLayer.java:277)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.setParameters(MultiLayerNetwork.java:1727)
	at org.deeplearning4j.examples.deepbelief.DBNIrisExample.main(DBNIrisExample.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by AlexDBlack** [comment]
Thanks for reporting this.
I've fixed the issue in current master: https://github.com/deeplearning4j/deeplearning4j/pull/842
I've also made a slight change to the DBN Iris example that avoids this issue on the current version: https://github.com/deeplearning4j/dl4j-0.4-examples/pull/36
