### ISSUE TITLE
DL4J Spark gradient sharing: low /dev/shm space can result in connections failing

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8416]
We use Aeron for our distributed training communication for our gradient sharing implementation.
Aeron relies on /dev/shm by default for storing buffers.

If /dev/shm doesn't have enough free space in it, it's possible for Aeron to _nearly silently_ fail to connect.
The only indication that something is wrong here the following lines (extracted from the driver stderr and logs, respectively):
```
Warning: space is running low in /dev/shm (shm) threshold=167,772,160 usable=50,323,456
...
2019-11-18 03:33:04 WARN  TaskSetManager:66 - Lost task 0.0 in stage 4.0 (TID 7, 10.5.0.7, executor 0): org.nd4j.linalg.exception.ND4JIllegalStateException: Can't establish connection to aeron:udp?endpoint=10.5.0.12:49876 (stream id=664882648) after 10 seconds. Terminating...
        at org.nd4j.parameterserver.distributed.v2.transport.impl.AeronUdpTransport.addConnection(AeronUdpTransport.java:322)
        at org.nd4j.parameterserver.distributed.v2.transport.impl.AeronUdpTransport.launch(AeronUdpTransport.java:353)
        at org.nd4j.parameterserver.distributed.v2.ModelParameterServer.launch(ModelParameterServer.java:400)
```

Strictly speaking this is an Aeron UX problem, but given we're using Aeron DL4J users could run into it, so we might want to see if we can do anything about it.

**Comment by zhaoyunyemu** [comment]
hi AlexDBlack:
**I encountered a similar problem, but I am not sure what went wrong：**
org.apache.spark.internal.Logging(Logging.scala:69): Lost task 0.0 in stage 12.0 (TID 17, hadoop1-server, executor 2): org.nd4j.linalg.exception.ND4JIllegalStateException: Can't establish connection afet 10 seconds. Terminating...
        at org.nd4j.parameterserver.distributed.v2.transport.impl.AeronUdpTransport.addConnection(AeronUdpTransport.java:322)
        at org.nd4j.parameterserver.distributed.v2.transport.impl.AeronUdpTransport.launch(AeronUdpTransport.java:352)
        at org.nd4j.parameterserver.distributed.v2.ModelParameterServer.launch(ModelParameterServer.java:377)
        at org.deeplearning4j.spark.parameterserver.pw.SharedTrainingWrapper.run(SharedTrainingWrapper.java:363)
        at org.deeplearning4j.spark.parameterserver.functions.SharedFlatMapPaths.call(SharedFlatMapPaths.java:86)
        at org.deeplearning4j.spark.parameterserver.functions.SharedFlatMapPaths.call(SharedFlatMapPaths.java:41)
        at org.apache.spark.api.java.JavaRDDLike.$anonfun$mapPartitions$1(JavaRDDLike.scala:153)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
**The following is the configuration information and other information：**
Deeplearning4j version： <dl4j.version>1.0.0-beta7</dl4j.version>
Platform information ：centos 7
CUDA version, if used： used cpu
NVIDIA driver version, if in use: used cpu
the code is:
        VoidConfiguration conf = VoidConfiguration.builder()
            .unicastPort(40123)
            .networkMask("192.168.11.0/24")
            .controllerAddress("0.0.0.0")
            .meshBuildMode(MeshBuildMode.PLAIN)
            .build();
**udp 40123 port is through test:UDP packet sent successfully.**
**also i seen the log of aeron use
 java -cp aeron-all-1.4.0.jar  -Daeron.dir=/dev/shm/aeron-yarn-d99cef31-acab-4af7-9ca4-fc7b6eb06939 io.aeron.samples.ErrorStat**
Command `n Control file /dev/shm/aeron-yarn-d99cef31-acab-4af7-9ca4-fc7b6eb06939/cnc.dat
***
1 observations from 2021-02-25 14:22:28.810+0800 to 2021-02-25 14:22:28.810+0800 for:
 java.lang.RuntimeException: Channel error: Address already in use : aeron:udp?endpoint=192.168.11.7:49876
        at io.aeron.driver.media.UdpChannelTransport.openDatagramChannel(UdpChannelTransport.java:130)
        at io.aeron.driver.media.ReceiveChannelEndpoint.openChannel(ReceiveChannelEndpoint.java:145)
        at io.aeron.driver.Receiver.onRegisterReceiveChannelEndpoint(Receiver.java:127)
        at io.aeron.driver.cmd.RegisterReceiveChannelEndpointCmd.execute(RegisterReceiveChannelEndpointCmd.java:32)
        at io.aeron.driver.Receiver.accept(Receiver.java:150)
        at io.aeron.driver.Receiver.accept(Receiver.java:37)
        at org.agrona.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:111)
        at org.agrona.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:86)
        at io.aeron.driver.Receiver.doWork(Receiver.java:66)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:220)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:159)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:691)
        at io.aeron.driver.media.UdpChannelTransport.openDatagramChannel(UdpChannelTransport.java:105)
        ... 11 more
what's the probleam? thank you

**Comment by agibsonccc** [comment]
@zhaoyunyemu  please avoid commenting on old issues. I'm closing this. For further support inquiries please post on: https://community.konduit.ai
