### ISSUE TITLE
Unable to resolve nd4j snapshot dependency in scala sbt

### ISSUE THREAD

**Issue by kris1710** [deeplearning4j/deeplearning4j#8418]
Hi,
With recent fixes, I was trying to get the snapshot versions of dl4j and nd4j. As per the directions in the given link [snapshots config](https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots) . Following is the build.sbt I am using
```
name := "scala1"

version := "0.1"

scalaVersion := "2.11.12"

ThisBuild / useCoursier := false

classpathTypes += "maven-plugin"

val d4jVersion = "1.0.0-Snapshot"
val sparkVersion = "2.4.4"

libraryDependencies += "org.apache.spark" %% "spark-core" % sparkVersion
libraryDependencies += "org.apache.spark" %% "spark-sql" % sparkVersion
libraryDependencies += "org.deeplearning4j" %% "dl4j-spark" % "1.0.0-beta2_spark_2"
libraryDependencies += "org.bytedeco.javacpp-presets" % "openblas" % "0.2.20-1.4.1" classifier "" classifier "linux-x86_64"
libraryDependencies += "org.deeplearning4j" % "deeplearning4j-core" % d4jVersion
//libraryDependencies += "org.deeplearning4j" % "deeplearning4j-modelimport" % d4jVersion
libraryDependencies += "org.nd4j" % "nd4j-native-platform" % d4jVersion
libraryDependencies += "org.nd4j" % "nd4j-native" % d4jVersion
libraryDependencies += "org.nd4j" % "nd4j-api" % d4jVersion
libraryDependencies += "org.datavec" %% "datavec-spark" % d4jVersion
libraryDependencies += "org.deeplearning4j" % "deeplearning4j-datavec-iterators" % d4jVersion

updateOptions := updateOptions.value.withLatestSnapshots(false)
resolvers += "snapshots-repo" at "https://oss.sonatype.org/content/repositories/snapshots"
resolvers in ThisBuild ++= Seq(Opts.resolver.sonatypeSnapshots)

```

This throws an error:
```
Error while importing sbt project:

List([info] Loading global plugins from /home/karunsingla/.sbt/1.0/plugins
[info] Loading project definition from /home/karunsingla/nov2/project
[info] Loading settings for project nov2 from build.sbt ...
[info] Set current project to scala1 (in build file:/home/karunsingla/nov2/)
[info] sbt server started at local:///home/karunsingla/.sbt/1.0/server/cbe013541138e7b8ea55/sock
sbt:scala1>
[info] Defining Global / sbtStructureOptions, Global / sbtStructureOutputFile and 1 others.
[info] The new values will be used by cleanKeepGlobs
[info] 	Run `last` for details.
[info] Reapplying settings...
[info] Set current project to scala1 (in build file:/home/karunsingla/nov2/)
[info] Applying State transformations org.jetbrains.sbt.CreateTasks from /home/karunsingla/.IdeaIC2019.2/config/plugins/Scala/repo/org.jetbrains/sbt-structure-extractor/scala_2.12/sbt_1.0/2018.2.1+4-88400d3f/jars/sbt-structure-extractor.jar
[info] Reapplying settings...
[info] Set current project to scala1 (in build file:/home/karunsingla/nov2/)
[warn] 	module not found: org.nd4j#nd4j-native-platform;1.0.0-Snapshot
[warn] ==== local: tried
[warn]   /home/karunsingla/.ivy2/local/org.nd4j/nd4j-native-platform/1.0.0-Snapshot/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/nd4j/nd4j-native-platform/1.0.0-Snapshot/nd4j-native-platform-1.0.0-Snapshot.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/karunsingla/.sbt/preloaded/org.nd4j/nd4j-native-platform/1.0.0-Snapshot/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/karunsingla/.sbt/preloaded/org/nd4j/nd4j-native-platform/1.0.0-Snapshot/nd4j-native-platform-1.0.0-Snapshot.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-native-platform/1.0.0-Snapshot/nd4j-native-platform-1.0.0-Snapshot.pom
[warn] ==== snapshots-repo: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-native-platform/1.0.0-Snapshot/nd4j-native-platform-1.0.0-Snapshot.pom
[warn] 	module not found: org.nd4j#nd4j-native;1.0.0-Snapshot
[warn] ==== local: tried
[warn]   /home/karunsingla/.ivy2/local/org.nd4j/nd4j-native/1.0.0-Snapshot/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/nd4j/nd4j-native/1.0.0-Snapshot/nd4j-native-1.0.0-Snapshot.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/karunsingla/.sbt/preloaded/org.nd4j/nd4j-native/1.0.0-Snapshot/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/karunsingla/.sbt/preloaded/org/nd4j/nd4j-native/1.0.0-Snapshot/nd4j-native-1.0.0-Snapshot.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-native/1.0.0-Snapshot/nd4j-native-1.0.0-Snapshot.pom
[warn] ==== snapshots-repo: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-native/1.0.0-Snapshot/nd4j-native-1.0.0-Snapshot.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.nd4j#nd4j-native-platform;1.0.0-Snapshot: not found
[warn] 	:: org.nd4j#nd4j-native;1.0.0-Snapshot: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.nd4j:nd4j-native-platform:1.0.0-Snapshot (/home/karunsingla/nov2/build.sbt#L23-24)
[warn] 		  +- scala1:scala1_2.11:0.1
[warn] 		org.nd4j:nd4j-native:1.0.0-Snapshot (/home/karunsingla/nov2/build.sbt#L23-24)
[warn] 		  +- scala1:scala1_2.11:0.1
```

How to get around this? I need the snapshot versions for some fixes pushed recently.

**Comment by raver119** [comment]
1.0.0-SNAPSHOT

Characters case matters

**Comment by kris1710** [comment]
I changed that as well, but it still gives an error at runtime. The code works fine if the versions are 1.0.0-beta5
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at s_version$.main(code_2.scala:243)
	at s_version.main(code_2.scala)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: 
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5597)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5447)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:213)
	... 2 more
Caused by: java.lang.ClassNotFoundException: 
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5501)
	... 4 more
```

**Comment by kris1710** [comment]
@raver119 : The sbt builds, but the error persists. Attaching sample code

```
object testing_2 {
  def main(args: Array[String]): Unit = {


    val conf = new NeuralNetConfiguration.Builder()
      .seed(1)
      .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
      .updater(new Nadam(0.01))
      .l2(1e-05)
      .graphBuilder()
      .addInputs("input1") //inputs

      .addLayer("dnn_1", new DenseLayer.Builder().nIn(15).nOut(128).weightInit(WeightInit.XAVIER).dropOut(0.8).build(), "input1")
      .addLayer("output", new OutputLayer.Builder(LossFunction.NEGATIVELOGLIKELIHOOD).activation(Activation.SOFTMAX).nIn(128).nOut(2).build(), "dnn_1")
      .setOutputs("output")
      .build()



  }
}

```

**Comment by raver119** [comment]
Show FULL stack trace please

**Comment by kris1710** [comment]
@raver119  , I did some debugging, I think the issue is coming from the class **SPARSE_NDARRAY_FACTORY_CLASS** not being present in the nd4j-native-1.0.0-SNAPSHOT.jar while its present in nd4j-native-1.0.0-beta5.jar (Attaching screenshots)

as the error comes from this line 5501 in Nd4j.java
```
 sparseNDArrayClazz = (Class<? extends NDArrayFactory>) Class.forName(
                    pp.toString(SPARSE_NDARRAY_FACTORY_CLASS));
```
![Screenshot from 2019-11-19 12-32-08](https://user-images.githubusercontent.com/13129503/69123984-cac70900-0ac8-11ea-847b-dbf7826de7b2.png)
![1 0 0-beta5](https://user-images.githubusercontent.com/13129503/69124342-a9b2e800-0ac9-11ea-8204-7636ced08bda.png)

**Comment by raver119** [comment]
Wow.. I wonder why it's not reproducible for us during tests. I'll take care of it ASAP.

**Comment by kris1710** [comment]
@raver119 : Is this resolved? I compiled my build.sbt,The SBT builds successfully but there are new errors when i run the code
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:91)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5165)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5079)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:176)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:579)
	at graph2$.main(Demo1.scala:45)
	at graph2.main(Demo1.scala)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:112)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:35)
	... 12 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1543)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1192)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1042)
	at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:85)
	... 13 more
Caused by: java.lang.UnsatisfiedLinkError: no nd4jcpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1543)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1143)
	... 18 more
```
I tried debugging this issue a lot, but I am stuck. I downloaded the following jars directly from the [snapshot-repo](https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-native/1.0.0-SNAPSHOT/)
-nd4j-native-1.0.0-20191119.032148-15928.jar
-nd4j-native-1.0.0-20191119.082212-15929.jar
-nd4j-native-1.0.0-20191119.082212-15929-javadoc.jar
-nd4j-native-1.0.0-20191119.082212-15929-sources.jar

and pasted them in the lib directory in my project but the error persists. can you please help? Is their any resolver issue?

**Comment by saudet** [comment]
sbt isn't able to handle snapshots on its own, see instructions here: http://bytedeco.org/builds/

**Comment by kris1710** [comment]
@saudet : Thanks for extending the help.Unfortunately, I've little knowledge in java. Can you explain a little bit more?

**Comment by kris1710** [comment]
I believe you meant to create a pom.xml as such :
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.dh.dl_test</groupId>
    <artifactId>testing</artifactId>
    <version>1.0-SNAPSHOT</version>
    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>  <!-- Optional, update daily -->
            </snapshots>
        </repository>
    </repositories>

   <properties>
       <dl4j.version>1.0.0-SNAPSHOT</dl4j.version>
       <nd4j.version>1.0.0-SNAPSHOT</nd4j.version> </properties>
    <dependencies>

    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-core</artifactId>
        <version>${dl4j.version}</version>
    </dependency>

        <dependency>
        <groupId>org.nd4j</groupId>
        <artifactId>nd4j-native</artifactId>
        <version>${nd4j.version}</version>
    </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>${nd4j.version}</version>
        </dependency>

    </dependencies>
</project>
```

and then use the SBT as follows :
```
name := "nov19"

version := "0.1"

scalaVersion := "2.11.12"

val d4jVersion = "1.0.0-SNAPSHOT"
ThisBuild / useCoursier := false

libraryDependencies += "org.bytedeco.javacpp-presets" % "openblas" % "0.2.20-1.4.1" classifier "" classifier "linux-x86_64"
libraryDependencies += "org.deeplearning4j" % "deeplearning4j-core" % d4jVersion
libraryDependencies += "org.nd4j" % "nd4j-native" % d4jVersion
libraryDependencies += "org.nd4j" % "nd4j-native-platform" % d4jVersion
resolvers+= Resolver.mavenLocal
```

the build.sbt compiles but at the runtime it still gives issues :
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:91)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5165)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5079)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:176)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:579)
	at sample_1$.main(sample_1.scala:15)
	at sample_1.main(sample_1.scala)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:112)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:35)
	... 12 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1867)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1543)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1192)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1042)
	at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:85)
	... 13 more
Caused by: java.lang.UnsatisfiedLinkError: /home/karunsingla/.javacpp/cache/nd4j-native-1.0.0-SNAPSHOT-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libjnind4jcpu.so: libopenblas.so.0: cannot open shared object file: No such file or directory
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:767)
	at java.base/java.lang.System.load(System.java:1831)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1493)
	... 19 more

```

what did i miss?

**Comment by kris1710** [comment]
Fixed it by installing libopenblas-dev. 
Thanks for the directions. The issue could serve as directions for configuring snapshot versions with scala build.sbt

**Comment by raver119** [comment]
hm, but it should not be needed, since openblas is provided as transitive dependency by javacpp

**Comment by kris1710** [comment]
Oh is that so? Did i miss something in sbt or pom file?
