### ISSUE TITLE
SameDiff tools: intermediate vars check broken

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#8434]
Apparently, we have issue with SameDiff import tests tooling: intermediate variables checks fail with two different messages:

1. 
```
RUNNING TEST is_strictly_increasing/rank2_float32...

java.lang.IllegalStateException: No variable are available for execution at step 21: 17 values remaining. First 10 missing variables: is_strictly_increasing/cond/StridedSlice_1,is_strictly_increasing/cond/ones_like_1/Shape,is_strictly_increasing/cond/ones_like_1/Const,is_strictly_increasing/cond/sub,is_strictly_increasing/cond/ones_like/Const,is_strictly_increasing/cond/switch_f,is_strictly_increasing/cond/StridedSlice_1/begin,is_strictly_increasing/cond/ones_like,is_strictly_increasing/cond/add/Switch,is_strictly_increasing/cond/StridedSlice
	at org.nd4j.autodiff.samediff.internal.AbstractSession.execFailed(AbstractSession.java:532)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:260)
```

2. 

```
RUNNING TEST resize_nearest_neighbor/int32...
java.lang.AssertionError: Shape not equal on node in_0/read: actual array was null
```

Both exceptions are reproducible with CUDA at least.

**Comment by agibsonccc** [comment]
Closing — SameDiff has been completely rewritten with a new DSP (Dynamic Shape Plan) execution engine, native plan compilation, CUDA graph replay, and Triton compilation. The architecture referenced in this issue no longer exists. If you still experience this issue with the upcoming release, please open a new issue.
