### ISSUE TITLE
java.lang.ArithmeticException: / by zero 

### ISSUE THREAD

**Issue by kris1710** [deeplearning4j/deeplearning4j#8447]
Hi I am trying to fit a computation graph on spark. I ve multidataset rdd objects of  batchsize 1024, total CSV rows~9 million. I ve stored the paths here
```
val data_paths="hdfs:////user/dh-ads/karun/proc.txt"
val loadedPaths = sc.textFile(data_paths)
```
However, when I run 

```
val trainingMaster: ParameterAveragingTrainingMaster = new ParameterAveragingTrainingMaster.Builder(1024).workerPrefetchNumBatches(2).averagingFrequency(2).batchSizePerWorker(17).build();
val sparknet=new SparkComputationGraph(sc,net5,trainingMaster)
sparknet.fitPathsMultiDataSet(loadedPaths)


```

It throws
```
java.lang.NullPointerException
  at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster.executeTrainingPathsHelper(ParameterAveragingTrainingMaster.java:414)
  at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster.executeTrainingPaths(ParameterAveragingTrainingMaster.java:408)
  at org.deeplearning4j.spark.impl.graph.SparkComputationGraph.fitPaths(SparkComputationGraph.java:328)
  at org.deeplearning4j.spark.impl.graph.SparkComputationGraph.fitPathsMultiDataSet(SparkComputationGraph.java:324)
```
I looked up the java class ParameterAveragingTrainingMaster.java at line 414 
```
if (numWorkers == null)
            numWorkers = network.getSparkContext().defaultParallelism();
```
if i print sparknet.getSparkContext().defaultParallelism() it outputs 60, but it seems the builder here is not able to fetch numworkers and throws a null point exception. 
Now, if I change the trainingmaster configuration to 
```
val trainingMaster: ParameterAveragingTrainingMaster = new ParameterAveragingTrainingMaster.Builder(numworkers=60, rddDatasetNumExamples=1024).workerPrefetchNumBatches(2).averagingFrequency(2).batchSizePerWorker(17).build();
val sparknet=new SparkComputationGraph(sc,net5,trainingMaster)
sparknet.fitPathsMultiDataSet(loadedPaths)


```
it throws the error as
```
java.lang.ArithmeticException: / by zero
	at org.deeplearning4j.spark.impl.common.repartition.BalancedPartitioner.getPartition
```
Is it a bug? or something wrong with the trainingmaster configuration? The count of loadedPaths=9125 (loadedPaths.count). 
If i am subsetting it to lets say 10 as 
```
val smallLoadedPaths = loadedPaths.zipWithIndex.filter(_._2 < 10).map(_._1)
 sparknet.fitPathsMultiDataSet(smallLoadedPaths)
```
^this works fine  when smallLoadedPaths.count=10, 

I am setting the batchsizeperworker to be = 1024/60 (multidataset size/numworkers)
works fine.  Can anyone please help in properly configuring the trainingmaster and why it is failing to get numworkers by its own?

**Comment by agibsonccc** [comment]
Closing: Spark is no longer supported in DL4J.
