### ISSUE TITLE
org.deeplearning4j.exception.DL4JInvalidInputException

### ISSUE THREAD

**Issue by SelfEvoAI** [deeplearning4j/deeplearning4j#8454]
#### Issue Description

`
    val XXndArr = new Array[Array[Array[Float]]](X.size())
    .....
    val XXnd = Nd4j.create(XXndArr)
    .....
    val pridictOut = model.output(XX)
`

`Exception in thread "main" org.deeplearning4j.exception.DL4JInvalidInputException: Received input with size(1) = 5 (input array shape = [5, 5, 1]); input.size(1) must match layer nIn size (nIn = 1)
	at org.deeplearning4j.nn.layers.recurrent.LSTMHelpers.activateHelper(LSTMHelpers.java:188)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.activateHelper(LSTM.java:159)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.activate(LSTM.java:131)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1298)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2412)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2375)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2366)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2353)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2449)
	at com.banma.dataops.timeSeriesDataPrediction.deepLearningModel$.main(deepLearningModel.scala:56)
	at com.banma.dataops.timeSeriesDataPrediction.deepLearningModel.main(deepLearningModel.scala)`

#### Version Information

1.0.0-beta5

#### Additional Information
I find the issue #4556

`Nd4j.create(XXndArr)` shpe is [5,5,1], but Dn4j imported lstm model need shape is [5,1,5]

keras on python default shape is [5,5,1]

How to convert `Nd4j.create(XXndArr)` shpe to [5,1,5] ?

thanks.

**Comment by raver119** [comment]
1) You can reorganize your XXndArr to become [5, 1, 5]
2) You can permute your NDArray, so it will become [5, 1, 5]
