### ISSUE TITLE
MatrixBandPart operation doesn't return valid output shapes

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#8455]
Output from TFGraphTestAllSameDiff test in nd4j:

```	RUNNING TEST matrix_band_part/float32...
o.n.i.T.TFGraphTestAllSameDiff - ERROR Executing test: matrix_band_part/float32 - input keys []
java.lang.IllegalStateException: Failed to calculate output shapes for op matrix_band_part (MatrixBandPart) - no shapes were returned by calculateOutputShape()
	at org.nd4j.base.Preconditions.throwStateEx(Preconditions.java:641)
	at org.nd4j.base.Preconditions.checkState(Preconditions.java:340)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:828)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:66)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:379)



java.lang.IllegalStateException: Failed to calculate output shapes for op matrix_band_part (MatrixBandPart) - no shapes were returned by calculateOutputShape()

	at org.nd4j.base.Preconditions.throwStateEx(Preconditions.java:641)
	at org.nd4j.base.Preconditions.checkState(Preconditions.java:340)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:828)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:66)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:379)
	at org.nd4j.autodiff.samediff.SameDiff.directExecHelper(SameDiff.java:2601)
	at org.nd4j.autodiff.samediff.SameDiff.batchOutputHelper(SameDiff.java:2569)
	at org.nd4j.autodiff.samediff.SameDiff.output(SameDiff.java:2544)
	at org.nd4j.autodiff.samediff.config.BatchOutputConfig.output(BatchOutputConfig.java:147)
	at org.nd4j.autodiff.samediff.SameDiff.output(SameDiff.java:2519)
	at org.nd4j.imports.TFGraphs.TFGraphTestAllHelper.getGraphAfterExec(TFGraphTestAllHelper.java:411)
	at org.nd4j.imports.TFGraphs.TFGraphTestAllHelper.checkOnlyOutput(TFGraphTestAllHelper.java:155)
	at org.nd4j.imports.TFGraphs.TFGraphTestAllSameDiff.testOutputOnly(TFGraphTestAllSameDiff.java:209)

**Comment by raver119** [comment]
Every time you see exception like this:

```
java.lang.IllegalStateException: Failed to calculate output shapes for op matrix_band_part (MatrixBandPart) - no shapes were returned by calculateOutputShape()
```

It just means you have problem in Java, op mapping is bad. I.e. some missed args.

**Comment by alexanderst** [comment]
@raver119 minLower and maxUpper are defined as int arguments in both libnd4j and nd4j, but they are tensors in graph:
```node {
  name: "MatrixBandPart/num_upper"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT64
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT64
        tensor_shape {
        }
        int64_val: -1
      }
    }
  }
}

**Comment by shugeo** [comment]
An failed java test is needed to be fix.
