### ISSUE TITLE
BarnesHutTSNE exception

### ISSUE THREAD

**Issue by tomsfood** [deeplearning4j/deeplearning4j#846]
BarnesHutTSNE cannot be run on the same INDArray that regular old TSNE can be run on just fine. In fact it seems BarnesHutTSNE cannot be run at all without throwing this exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: Indexes, shape, and stride must be the same length
	at org.nd4j.linalg.api.shape.Shape.getOffset(Shape.java:492)
	at org.nd4j.linalg.api.shape.Shape.getDouble(Shape.java:211)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:1449)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getInt(BaseNDArray.java:1437)
	at org.deeplearning4j.plot.BarnesHutTsne.computeGaussianPerplexity(BarnesHutTsne.java:239)
	at org.deeplearning4j.plot.BarnesHutTsne.fit(BarnesHutTsne.java:431)
	at org.deeplearning4j.plot.BarnesHutTsne.fit(BarnesHutTsne.java:609)
	at org.deeplearning4j.plot.BarnesHutTsne.plot(BarnesHutTsne.java:509)
```

**Comment by sbelak** [comment]
This seems to be caused by a change in ND4j: https://github.com/deeplearning4j/nd4j/commit/6af37f7511dd6c428a4e337c416477dc30a1ff00
which made it more stringent. Even 1D rows have stride = [1,1] and shape = [1, n], so my understanding is .getInt(i) should become .getInt(0, i)

**Comment by agibsonccc** [comment]
Mind trying again in master? I've fixed this.

**Comment by ozborn** [comment]
I experienced the same problem with the maven versions of 0.4-rc3.6 (nd4j) and 0.4-rc3.8 (dl4j) but I downloaded the 0.4-rc3.9-SNAPSHOT from master today and the problem is gone.

**Comment by raver119** [comment]
@ozborn your issue has nothing related to the original issue posted here.
