### ISSUE TITLE
Deserialization error at sparkcomputationgraph with custom layers

### ISSUE THREAD

**Issue by kris1710** [deeplearning4j/deeplearning4j#8462]
Hi i ve created custom layers in my model, [reference issue](https://github.com/eclipse/deeplearning4j/issues/8409) . I am deploying this model to the spark . The model trains fine but at the evaluation stage it throws the error 
```
java.lang.RuntimeException: org.nd4j.shade.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.deeplearning4j.nn.conf.layers.Layer` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (StringReader); line: 16252, column: 11] (through reference chain: org.deeplearning4j.nn.conf.ComputationGraphConfiguration["vertices"]->java.util.LinkedHashMap["a_plus_b"]->org.deeplearning4j.nn.conf.graph.LayerVertex["layerConf"]->org.deeplearning4j.nn.conf.NeuralNetConfiguration["layer"])
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.fromJson(ComputationGraphConfiguration.java:205)
	at org.deeplearning4j.spark.impl.evaluation.EvaluationRunner.execute(EvaluationRunner.java:135)
	at org.deeplearning4j.spark.impl.graph.evaluation.IEvaluateMDSPathsFlatMapFunction.call(IEvaluateMDSPathsFlatMapFunction.java:89)
	at org.deeplearning4j.spark.impl.graph.evaluation.IEvaluateMDSPathsFlatMapFunction.call(IEvaluateMDSPathsFlatMapFunction.java:45)
```

"a+b" is the layer that calls in my computation graph.
```
class tensors_sum extends SameDiffLambdaLayer {
  override def defineLayer(sd: SameDiff, x: SDVariable): SDVariable = sd.sum(x,false,1)
}
```

**Comment by kris1710** [comment]
If it helps, I am using the following method for evaluation:
passing the string path to the multidataset stored and a multidataloader
```
sparknet.evaluate("hdfs:////user/dh-ads/karun/proc_scala/mds_0-393ac3d_0.bin", new SerializedMultiDataSetLoader())
```

**Comment by kris1710** [comment]
Hi,
Any update on this?

**Comment by AlexDBlack** [comment]
I was able to reproduce this locally using the following code.
https://gist.github.com/AlexDBlack/a2ff44e98ba491230ba313fbfd48d431

The problem here is that your lambda layer is a non-static inner class.
If you make it a static class, it should deserialize fine.
