### ISSUE TITLE
cudaMalloc failure after repeated OpenCV captures

### ISSUE THREAD

**Issue by yquemener** [deeplearning4j/deeplearning4j#8506]
Consider this program:
```
import static org.bytedeco.opencv.global.opencv_highgui.imshow;
import static org.bytedeco.opencv.global.opencv_highgui.waitKey;
import static org.bytedeco.opencv.global.opencv_videoio.CAP_PROP_FRAME_HEIGHT;
import static org.bytedeco.opencv.global.opencv_videoio.CAP_PROP_FRAME_WIDTH;

public class TestOpenCVAllocationLeak {

    public static void main(String[] args) throws Exception {

        NativeImageLoader nil = new NativeImageLoader();

        VideoCapture vc = new VideoCapture();
        Mat cvImage = new Mat();
        vc.open(0);
        vc.set(CAP_PROP_FRAME_WIDTH, 1920);
        vc.set(CAP_PROP_FRAME_HEIGHT, 1080);
        int keypressed = -1;
        int frameNum = 0;
        while (keypressed == -1) {
            keypressed = waitKey(1);
            vc.grab();
            vc.retrieve(cvImage);

            INDArray image = nil.asMatrix(cvImage);
            System.out.println(image.shapeInfoToString());
            frameNum++;
            System.out.println("Frame #"+frameNum);
            imshow("Output", cvImage);
        }
    }
}
```
After 451 frames captured, it fails with 
```
Exception in thread "main" java.lang.RuntimeException: cudaMalloc failed
	at org.nd4j.jita.allocator.pointers.cuda.cudaStream_t.synchronize(cudaStream_t.java:41)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:307)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:526)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:438)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.initPointers(BaseCudaDataBuffer.java:297)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:316)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:63)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.create(CudaDataBufferFactory.java:380)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1443)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1432)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1411)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:312)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:365)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:788)
	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:284)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:183)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4223)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3940)
	at org.datavec.image.loader.NativeImageLoader.transformImage(NativeImageLoader.java:638)
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:561)
	at org.konduit.PlayingCardsVision.TestOpenCVAllocationLeak.main(TestOpenCVAllocationLeak.java:44)
```

Setup is identical to https://github.com/eclipse/deeplearning4j/issues/8505

`nvidia-smi` shows the GPU memory filling up at a rate of 30 MiB/sec

If the line 
```
INDArray image = nil.asMatrix(cvImageCropped);
```
is commented, the program runs continuously without problem for more than 1000 frames and does not consume GPU mem.

**Comment by yquemener** [comment]
I tried to manually release arrays but it did not work:

If I do image.close() at the end of the loop: 

```
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: Can't release this INDArray
	at org.nd4j.linalg.api.ndarray.BaseNDArray.close(BaseNDArray.java:5590)
	at org.konduit.PlayingCardsVision.TestOpenCVAllocationLeak.main(TestOpenCVAllocationLeak.java:37)
```

If I do cvImage.close(): 
```
Exception in thread "main" java.lang.NullPointerException: Pointer address of argument 0 is NULL.
	at org.bytedeco.opencv.opencv_videoio.VideoCapture.retrieve(Native Method)
	at org.konduit.PlayingCardsVision.TestOpenCVAllocationLeak.main(TestOpenCVAllocationLeak.java:30)
```

**Comment by saudet** [comment]
`NDArray` wasn't really designed to be closed manually. Could you try to add a call to `System.gc()` in the loop and see if that makes a difference? If so, it should be possible to use a workspace to manage this memory more efficiently: https://deeplearning4j.org/docs/latest/deeplearning4j-config-workspaces

Something like this should work but let us know if it doesn't:
```
while (...) {
    try (MemoryWorkspace workspace = Nd4j.getWorkspaceManager().getAndActivateWorkspace()) {
        ...
    }
}
```

**Comment by yquemener** [comment]
Yes I ended up solving this issue by calling `System.gc()` manually in the loop. I'll try the workspace solution

**Comment by agibsonccc** [comment]
Closing — the CUDA backend has been completely rewritten with new memory management, DSP execution engine, CUDA graph replay, and Triton compilation. If you still experience GPU-related issues with the upcoming release, please open a new issue.
