### ISSUE TITLE
Model save by CheckpointListener does not support dynamic dimension length

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#8527]
#### Issue Description

Please describe our issue, along with:
- expected behavior
Can use -1 for placeholder

- encountered behavior
Invalid array shape: cannot associate an array with shape [128, 2, 18] with a placeholder of shape [128, 1, 18]:shape is wrong rank or does not match on one or more dimensions
	at org.nd4j.base.Preconditions.throwStateEx(Preconditions.java:641)
	at org.nd4j.base.Preconditions.checkState(Preconditions.java:340)
	at org.nd4j.autodiff.samediff.SameDiff.associateArrayWithVariable(SameDiff.java:1063)
	at org.nd4j.autodiff.samediff.SameDiff.resolveVariablesWith(SameDiff.java:5254)
	at org.nd4j.autodiff.samediff.SameDiff.fitHelper(SameDiff.java:2148)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:2042)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1982)
	at org.nd4j.autodiff.samediff.config.FitConfig.exec(FitConfig.java:173)
	at com.pcng.ner.bert.NerBertTraining.main(NerBertTraining.java:70)
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
beta5
* Platform information (OS, etc)
win7,centos8
* CUDA version, if used
not use
* NVIDIA driver version, if in use
not use
#### Additional Information
with sd.placeHolder("label", DataType.FLOAT, 128, -1, 18);
when create the sd, [128,2,18] and then [128,1,18] can be associated, that means the -1 is working. 
However, after load the model which save by CheckpointListener, the -1 not work, the second dimension is freezen to a specific value.

**Comment by SidneyLann** [comment]
Fixed in beta6
