### ISSUE TITLE
HistogramIterationListener issue with pretrain layers

### ISSUE THREAD

**Issue by shankarlal** [deeplearning4j/deeplearning4j#853]
When using the histogram listener in the DBNIrisExample, it throws the following exception. Alex commented that it works fine for backprop, but has an issue with the pretrain layers 

java.lang.ArrayIndexOutOfBoundsException: -1
at java.util.ArrayList.elementData(ArrayList.java:400)
at java.util.ArrayList.get(ArrayList.java:413)
at org.deeplearning4j.ui.weights.HistogramIterationListener.iterationDone(HistogramIterationListener.java:103)
at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:189)
at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:471)
at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.fit(RBM.java:410)
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:214)
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1336)
at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1382)
at org.deeplearning4j.examples.deepbelief.DBNIrisExample.main(DBNIrisExample.java:112)

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/873
