### ISSUE TITLE
Unsupported keras layer type PositionEmbedding

### ISSUE THREAD

**Issue by ghost** [deeplearning4j/deeplearning4j#8546]
I am trying to import a BERT text classifying model that was trained via Ktrain into DL4J via the Keras import function. 

Before I encountered this error, I encountered it for layer TokenEmbedding but I was able to resolve it using registerCustomLayer. But PositionEmbedding does not exist in the keras.layer library. 

Any help would be appreciated, thanks!

**Comment by SidneyLann** [comment]
https://github.com/CyberZHG/keras-pos-embd
here is the keras PositionEmbedding layer

**Comment by SidneyLann** [comment]
and you also can import tf pb model of bert to dl4j

**Comment by ghost** [comment]
Hi SidneyLann, thanks for the reply, the PositionEmbedding layer is not present in DL4J, hence I am unable to import the class file into the registerCustomLayer function.

**Comment by SidneyLann** [comment]
There are 6 such custom layers need you to implement in DL4J, so I imported by tf pb

**Comment by ghost** [comment]
> There are 6 such custom layers need you to implement in DL4J, so I imported by tf pb

SidneyLann could you link me to a tutorial or write a snippet of the code that was implemented to achieve that? I keep encountering an activation layer error while trying to import the said model, much appreciated.

**Comment by SidneyLann** [comment]
I don't know how to write layers in dl4j, it is the reason that I import by tf but not by keras, no need to implement layers importing tf pb model to dl4j samediff model

**Comment by ghost** [comment]
> I don't know how to write layers in dl4j, it is the reason that I import by tf but not by keras, no need to implement layers importing tf pb model to dl4j samediff model

Sorry SidneyLann I meant examples by Tensorflow as I encountered errors using the approach you just mentioned. Thanks!

**Comment by SidneyLann** [comment]
https://github.com/CyberZHG?tab=repositories

Here has all 6 custom keras layers what you need for bert model

**Comment by mdavis95** [comment]
I also use ktrain and would love to be able to load [ktrain](https://github.com/amaiya/ktrain) models in dl4j.

**Comment by treo** [comment]
@mdavis95 please open a separate issue for feature requests like this.

**Comment by mdavis95** [comment]
sorry to be clear, ktrain is the library used above that produced the keras model that would not import.  I was just stating that I also have run into this issue trying to figure out how to import it

**Comment by treo** [comment]
Oh, I somehow missed that. As far as I can tell, Ktrain is using tf.keras, which is using a slightly different model format to "old" Keras itself and in addition to that also adds its own custom layer types. 

At the moment we only support "old" Keras import. We do have an issue to track that feature request here: https://github.com/eclipse/deeplearning4j/issues/8348 but at the moment we are working on ironing out other things before we get back to that.

**Comment by mdavis95** [comment]
I did a
```py
model.save("/home/mdavis/bert/", save_format="tf")
```
which generates the following files
```
.
./variables
./variables/variables.data-00001-of-00002
./variables/variables.data-00000-of-00002
./variables/variables.index
./assets
./saved_model.pb
```

And tried to load the model using
```java
SameDiff sameDiff = TFGraphMapper.importGraph(new File("saved_model.pb"));
```

And I get 
```
Caused by: org.nd4j.shade.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.

	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.skipRawBytes(CodedInputStream.java:3016)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.skipField(CodedInputStream.java:2103)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.skipMessage(CodedInputStream.java:2165)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.skipField(CodedInputStream.java:2096)
	at org.nd4j.shade.protobuf.MapEntryLite.parseEntry(MapEntryLite.java:186)
	at org.nd4j.shade.protobuf.MapEntry.<init>(MapEntry.java:107)
	at org.nd4j.shade.protobuf.MapEntry.<init>(MapEntry.java:50)
	at org.nd4j.shade.protobuf.MapEntry$Metadata$1.parsePartialFrom(MapEntry.java:71)
	at org.nd4j.shade.protobuf.MapEntry$Metadata$1.parsePartialFrom(MapEntry.java:65)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2364)
	at org.tensorflow.framework.FunctionDef.<init>(FunctionDef.java:90)
	at org.tensorflow.framework.FunctionDef.<init>(FunctionDef.java:17)
	at org.tensorflow.framework.FunctionDef$1.parsePartialFrom(FunctionDef.java:1730)
	at org.tensorflow.framework.FunctionDef$1.parsePartialFrom(FunctionDef.java:1725)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2364)
	at org.tensorflow.framework.FunctionDefLibrary.<init>(FunctionDefLibrary.java:64)
	at org.tensorflow.framework.FunctionDefLibrary.<init>(FunctionDefLibrary.java:13)
	at org.tensorflow.framework.FunctionDefLibrary$1.parsePartialFrom(FunctionDefLibrary.java:1067)
	at org.tensorflow.framework.FunctionDefLibrary$1.parsePartialFrom(FunctionDefLibrary.java:1062)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2364)
	at org.tensorflow.framework.GraphDef.<init>(GraphDef.java:72)
	at org.tensorflow.framework.GraphDef.<init>(GraphDef.java:13)
	at org.tensorflow.framework.GraphDef$1.parsePartialFrom(GraphDef.java:1543)
	at org.tensorflow.framework.GraphDef$1.parsePartialFrom(GraphDef.java:1538)
	at org.nd4j.shade.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:215)
	at org.nd4j.shade.protobuf.AbstractParser.parseFrom(AbstractParser.java:232)
	at org.nd4j.shade.protobuf.AbstractParser.parseFrom(AbstractParser.java:237)
	at org.nd4j.shade.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at org.nd4j.shade.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:317)
	at org.tensorflow.framework.GraphDef.parseFrom(GraphDef.java:454)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:136)
	... 3 more

```


Is this a function of tensor flow 2.x not being supported for import?

**Comment by saudet** [comment]
Yes, we haven't moved to TF 2.x for that yet.

**Comment by agibsonccc** [comment]
We've since implemented support for tf.keras. Closing this.

**Comment by guojian0614** [comment]
> We've since implemented support for tf.keras. Closing this.

“While parsing a protocol message, the input ended unexpectedly”
@agibsonccc 
could you tell me how to solve this problem?

**Comment by agibsonccc** [comment]
@guojian0614  can you open a new issue if you have one? In your other issue you're also using something that's a few years old. We do not support that. If you have a new version and still have a problem I will take  look.
