### ISSUE TITLE
Word2Vec fails on spark to average results

### ISSUE THREAD

**Issue by thomas-trendsoft** [deeplearning4j/deeplearning4j#8584]
I have a small code piece to calculate a word2vec model from some sentences inside a cassandra database. everything runs good until the end steps of the learning. then i got an exception:

```
19/12/30 12:46:24 INFO TaskSchedulerImpl: Removed TaskSet 4.0, whose tasks have all completed, from pool 
19/12/30 12:46:24 INFO DAGScheduler: ResultStage 4 (collect at Word2Vec.java:212) finished in 34,550 s
19/12/30 12:46:24 INFO DAGScheduler: Job 4 finished: collect at Word2Vec.java:212, took 34,575477 s
19/12/30 12:46:24 INFO Word2Vec: Averaging results...
Exception in thread "main" java.lang.IllegalStateException: Cannot perform in-place operation "addi": result array shape does not match the broadcast operation output shape: [150].addi([1, 150]) != [150].
In-place operations like x.addi(y) can only be performed when x and y have the same shape, or x and y are broadcastable with x.shape() == broadcastShape(x,y)
	at org.nd4j.linalg.api.shape.Shape.assertBroadcastable(Shape.java:283)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:3236)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:3230)
	at org.deeplearning4j.spark.models.embeddings.word2vec.Word2Vec.train(Word2Vec.java:222)
	at deep.data.reader.ImportTask.word2Vec(ImportTask.java:123)
	at deep.data.reader.ImportTask.main(ImportTask.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/12/30 12:46:25 INFO SerialShutdownHooks: Successfully executed shutdown hook: Clearing session cache for C* connector
19/12/30 12:46:25 INFO SparkContext: Invoking stop() from shutdown hook
19/12/30 12:46:25 INFO SparkUI: Stopped Spark web UI at http://chost1:4040
```
I use the current snapshot version from maven build with:

> mvn clean package -U 

No cuda only cpu backend is used on rasperry pi with openblas.

Build is from today (30.12.2019) 
My pom is following:

```
  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
  
  <repositories>
    <repository>
      <id>sona deeplearning snapshots</id>
      <name>sona deeplearning snapshots</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    </repository>
   </repositories>
  
  <build>
      <plugins>
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <version>3.7.0</version>
              <configuration>
                  <source>1.8</source>
                  <target>1.8</target>
              </configuration>
          </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4.3</version>
                <configuration>
                    <shadedArtifactAttached>true</shadedArtifactAttached>
                    <shadedClassifierName>bin</shadedClassifierName>
                    <createDependencyReducedPom>true</createDependencyReducedPom>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>org/datanucleus/**</exclude>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                            </excludes>
                        </filter>
                    </filters>
       				<artifactSet>
                		<excludes>
                  			<exclude>org.nd4j:nd4j-native:jar:macosx-x86_64:1.0.0-20190708.071723-13728</exclude>
                  			<exclude>org.bytedeco:mkl:jar:macosx-x86_64:2019.5-1.5.2</exclude>
                  			<exclude>org.bytedeco:hdf5:jar:linux-x86:1.10.5-1.5.2</exclude>
                  			<exclude>nd4j:nd4j-native:jar:android-arm:1.0.0-SNAPSHOT</exclude>
                  			<exclude>org.nd4j:nd4j-native:jar:android-arm64:1.0.0-SNAPSHOT</exclude>
                  			<exclude>org.nd4j:nd4j-native:jar:ios-arm64:1.0.0-SNAPSHOT</exclude>
                  			<exclude>org.nd4j:nd4j-native:jar:ios-x86_64:1.0.0-SNAPSHOT</exclude>
                  			<exclude>org.nd4j:nd4j-native:jar:windows-x86_64:1.0.0-SNAPSHOT</exclude>
                  			<exclude>org.nd4j:nd4j-native:jar:linux-ppc64le:1.0.0-SNAPSHOT</exclude>
                  			<exclude>org.bytedeco:openblas:jar:android-arm:0.3.7-1.5.2</exclude>
                  			<exclude>org.bytedeco:openblas:jar:android-arm64:0.3.7-1.5.2</exclude>
                  			<exclude>org.bytedeco:openblas:jar:android-x86:0.3.7-1.5.2</exclude>
                  			<exclude>org.bytedeco:openblas:jar:android-x86_64:0.3.7-1.5.2</exclude>
                  			<exclude>org.bytedeco:openblas:jar:ios-arm64:0.3.7-1.5.2</exclude>
                  			<exclude>org.bytedeco:openblas:jar:ios-x86_64:0.3.7-1.5.2</exclude>
                  			<exclude>org.bytedeco:openblas:jar:linux-x86:0.3.7-1.5.2</exclude>
                  			<exclude>org.bytedeco:openblas:jar:linux-x86_64:0.3.7-1.5.2</exclude>
                  			<exclude>org.bytedeco:openblas:jar:linux-ppc64le:0.3.7-1.5.2</exclude>
                  			<exclude>org.bytedeco:openblas:jar:windows-x86:0.3.7-1.5.2</exclude>
                  			<exclude>org.bytedeco:openblas:jar:windows-x86_64:0.3.7-1.5.2</exclude>
                  			<exclude>org.bytedeco:leptonica:jar:android-arm:1.78.0-1.5.2</exclude>
                  			<exclude>org.bytedeco:leptonica:jar:android-arm64:1.78.0-1.5.2</exclude>
                  			<exclude>org.bytedeco:leptonica:jar:android-x86:1.78.0-1.5.2</exclude>
                  			<exclude>org.bytedeco:leptonica:jar:android-x86_64:1.78.0-1.5.2</exclude>
                  			<exclude>org.bytedeco:leptonica:jar:linux-x86:1.78.0-1.5.2</exclude>
                  			<exclude>org.bytedeco:leptonica:jar:linux-x86_64:1.78.0-1.5.2</exclude>
                  			<exclude>org.bytedeco:leptonica:jar:linux-ppc64le:1.78.0-1.5.2</exclude>
                  			<exclude>org.bytedeco:leptonica:jar:macosx-x86_64:1.78.0-1.5.2</exclude>
                  			<exclude>org.bytedeco:leptonica:jar:windows-x86:1.78.0-1.5.2</exclude>
                  			<exclude>org.bytedeco:leptonica:jar:windows-x86_64:1.78.0-1.5.2</exclude>
                  			<exclude>org.bytedeco:opencv:jar:android-arm:4.1.2-1.5.2</exclude>
							<exclude>org.bytedeco:opencv:jar:android-arm64:4.1.2-1.5.2</exclude>
							<exclude>org.bytedeco:opencv:jar:android-x86:4.1.2-1.5.2</exclude>
							<exclude>org.bytedeco:opencv:jar:android-x86_64:4.1.2-1.5.2</exclude>
							<exclude>org.bytedeco:opencv:jar:ios-arm64:4.1.2-1.5.2</exclude>
							<exclude>org.bytedeco:opencv:jar:ios-x86_64:4.1.2-1.5.2</exclude>
							<exclude>org.bytedeco:opencv:jar:linux-x86:4.1.2-1.5.2</exclude>
							<exclude>org.bytedeco:opencv:jar:linux-x86_64:4.1.2-1.5.2</exclude>
							<exclude>org.bytedeco:opencv:jar:linux-arm64:4.1.2-1.5.2</exclude>
							<exclude>org.bytedeco:opencv:jar:linux-ppc64le:4.1.2-1.5.2</exclude>
							<exclude>org.bytedeco:opencv:jar:macosx-x86_64:4.1.2-1.5.2</exclude>
							<exclude>org.bytedeco:opencv:jar:windows-x86:4.1.2-1.5.2</exclude>
							<exclude>org.bytedeco:opencv:jar:windows-x86_64:4.1.2-1.5.2</exclude>
							<exclude>org.bytedeco:hdf5:jar:linux-x86:1.10.5-1.5.2</exclude>
							<exclude>org.bytedeco:hdf5:jar:linux-x86_64:1.10.5-1.5.2</exclude>
							<exclude>org.bytedeco:hdf5:jar:linux-ppc64le:1.10.5-1.5.2</exclude>
							<exclude>org.bytedeco:hdf5:jar:windows-x86:1.10.5-1.5.2</exclude>
							<exclude>org.bytedeco:hdf5:jar:windows-x86_64:1.10.5-1.5.2</exclude>
                  			<exclude>org.nd4j:nd4j-native:jar:android-arm:1.0.0-SNAPSHOT</exclude>
                  			<exclude>org.bytedeco:openblas:jar:macosx-x86_64:0.3.7-1.5.2</exclude>
                  			<exclude>org.bytedeco:leptonica:jar:linux-arm64:1.78.0-1.5.2</exclude>
                  			<exclude>org.bytedeco:hdf5:jar:linux-arm64:1.10.5-1.5.2</exclude>
                  			<exclude>org.bytedeco:hdf5:jar:macosx-x86_64:1.10.5-1.5.2</exclude>
                  			<exclude>org.nd4j:nd4j-native:jar:android-x86:1.0.0-SNAPSHOT</exclude>
                  			<exclude>org.nd4j:nd4j-native:jar:android-x86_64:1.0.0-SNAPSHOT</exclude>
                  			<exclude>org.nd4j:nd4j-native:jar:linux-x86_64:1.0.0-SNAPSHOT</exclude>
                  			<exclude> org.bytedeco:openblas:jar:linux-arm64:0.3.7-1.5.2</exclude>
                  			<!-- <exclude>org.nd4j:nd4j-native:jar:linux-armhf:1.0.0-beta6</exclude> -->
                		</excludes>
              		</artifactSet>                  
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>reference.conf</resource>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>                
            </plugin>
             
      </plugins>
  </build>
    
  <dependencies>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-core_2.11</artifactId>
      <version>2.4.4</version>
      <scope>provided</scope>
	</dependency>
      <dependency>
          <groupId>org.apache.spark</groupId>
          <artifactId>spark-sql_2.11</artifactId>
          <version>2.4.4</version>
          <scope>provided</scope>
      </dependency>
		<!-- https://mvnrepository.com/artifact/com.datastax.spark/spark-cassandra-connector -->
		<dependency>
		    <groupId>com.datastax.spark</groupId>
		    <artifactId>spark-cassandra-connector_2.11</artifactId>
		    <version>2.4.2</version>
		    <!-- <scope>provided</scope> -->
		</dependency>
		<dependency>
		    <groupId>com.googlecode.json-simple</groupId>
		    <artifactId>json-simple</artifactId>
		    <version>1.1.1</version>
		</dependency>
		
		<!-- https://mvnrepository.com/artifact/org.deeplearning4j/dl4j-spark -->
		
		<dependency>
		    <groupId>org.deeplearning4j</groupId>
		    <artifactId>dl4j-spark_2.11</artifactId>
		    <version>1.0.0-SNAPSHOT</version>
		</dependency> 
		<dependency>
		    <groupId>org.deeplearning4j</groupId>
		    <artifactId>dl4j-spark-nlp_2.11</artifactId>
		    <version>1.0.0-SNAPSHOT</version>
		</dependency>
	<dependency>
	    <groupId>org.nd4j</groupId>
	    <artifactId>nd4j-api</artifactId>
	    <version>1.0.0-SNAPSHOT</version>
	</dependency>
	<dependency>
	    <groupId>org.nd4j</groupId>
	    <artifactId>nd4j-native</artifactId>
	    <version>1.0.0-SNAPSHOT</version>
	    <classifier>linux-armhf</classifier>
	</dependency>
	<dependency>
	    <groupId>org.nd4j</groupId>
	    <artifactId>nd4j-native-platform</artifactId>
	    <version>1.0.0-SNAPSHOT</version>
	</dependency>
	<dependency>
	    <groupId>org.nd4j</groupId>
	    <artifactId>nd4j-common</artifactId>
	    <version>1.0.0-SNAPSHOT</version>
	</dependency>	
	<dependency>
	  <groupId>org.nd4j</groupId>
	  <artifactId>nd4j-native-api</artifactId>
	  <version>1.0.0-SNAPSHOT</version>
	</dependency>
	<dependency>
	    <groupId>org.bytedeco.javacpp-presets</groupId>
	    <artifactId>openblas</artifactId>
	    <version>0.3.5-1.4.4</version>
	    <classifier>linux-armhf</classifier>
	</dependency>
		<dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-kryo_2.11</artifactId>
            <version>1.0.0-SNAPSHOT</version>
		</dependency>
  </dependencies>
```

I tried to report before and found the issue: #8288 and #932 but this is closed an the small difference seems to be the context (spark and not standalone) and the operation here "add" not "multi".

**Comment by thomas-trendsoft** [comment]
forgot the code...
```
		JavaSparkContext ctx = getContext();
        
		JavaRDD<String> rows = CassandraJavaUtil.javaFunctions(ctx).cassandraTable("nlpone", "kv", CassandraJavaUtil.mapColumnTo(String.class)).select("key").limit(100L);
		
        TokenizerFactory t = new DefaultTokenizerFactory();
        t.setTokenPreProcessor(new CommonPreprocessor());

        Word2Vec word2Vec = new Word2Vec.Builder()
                .setNGrams(1)
                .tokenizerFactory(t)
                .seed(42L)
                .layerSize(150)
                .windowSize(5)
                .learningRate(0.025)
                .minLearningRate(0.0001)
                .iterations(1)
                .batchSize(100)
                .minWordFrequency(2)
                .build();
        
        Broadcast<Map<String, Object>> broadcastTokenizerVarMap = ctx.broadcast(word2Vec.getTokenizerVarMap());
        
        word2Vec.train(rows);
        System.out.println("training done");
		WordVectorSerializer.writeWordVectors(word2Vec.getLookupTable(), "lookup.net");
		WordVectorSerializer.writeVocabCache(word2Vec.getVocab(), new File("vocab.net"));
		
        System.out.println(word2Vec.wordsNearest("und", 5));
```

**Comment by Ghulam-Sarwar** [comment]
Hi, I am facing the same problem. I tried to point the spark library to 1.0.0-SNAPSHOT as well. Still same error. Can anyone help?

**Comment by agibsonccc** [comment]
Closing: Spark is no longer supported in DL4J.
