### ISSUE TITLE
DataAnalysis Exception

### ISSUE THREAD

**Issue by CCH0124** [deeplearning4j/deeplearning4j#8586]
#### Issue Description

Please describe our issue, along with:
- expected behavior

- encountered behavior
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "RowNumber"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.datavec.api.writable.Text.toInt(Text.java:611)
        at org.datavec.api.transform.analysis.counter.IntegerAnalysisCounter.add(IntegerAnalysisCounter.java:82)
        at org.datavec.api.transform.analysis.counter.IntegerAnalysisCounter.add(IntegerAnalysisCounter.java:30)
        at org.datavec.local.transforms.analysis.aggregate.AnalysisAddFunction.apply(AnalysisAddFunction.java:81)
        at org.datavec.local.transforms.AnalyzeLocal.analyze(AnalyzeLocal.java:64)
        at org.datavec.local.transforms.AnalyzeLocal.analyze(AnalyzeLocal.java:50)
        at com.cch.dl4j.Test.main(Test.java:36)
```
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version  1.0.0-beta4
* Platform information (OS, etc) Windows10
* CUDA version, if used 10.0
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
This doesn't look like a bug. You have text values in your integer column, that (by definition) don't match your schema.
`java.lang.NumberFormatException: For input string: "RowNumber"`

Possibly a header line that needs to be removed/filtered before analysis?
