### ISSUE TITLE
What i can do when it occured exceptions such as Unsupported keras layer type FactorizedEmbedding?

### ISSUE THREAD

**Issue by zhongzh1992** [deeplearning4j/deeplearning4j#8610]
#### Issue Description
org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type FactorizedEmbedding. Please file an issue at https://github.com/eclipse/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:320)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:218)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:164)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:96)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:307)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:262)
	at test.dl.DL4jtest.main(DL4jtest.java:54)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version

1.0.0-SNAPSHOT

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
Apologies for the delayed reply.
Is this a standard Keras model, or one built with tf.keras?
The former doesn't have a layer of that type - https://keras.io/layers/embeddings/
For tf.keras, they introduced a whole lot of incompatible changes to the file format that we are working to support (if this is the case, you wouldn't be able to load it in "normal"/multi-backend keras either)

https://github.com/eclipse/deeplearning4j/issues/8348

**Comment by agibsonccc** [comment]
Likely a custom layer: https://github.com/bojone/bert4keras/issues/18 That means it needs to eb registered. That or you can use tensorflow import. More here:  https://deeplearning4j.konduit.ai/keras-import/overview
