### ISSUE TITLE
java.lang.NoClassDefFoundError: org/deeplearning4j/nn/conf/NeuralNetConfiguration$Builder

### ISSUE THREAD

**Issue by SelfEvoAI** [deeplearning4j/deeplearning4j#8619]
When I import model.h5, I have the two errors.

```java.lang.NoClassDefFoundError: org/deeplearning4j/nn/conf/BackpropType
        at org.deeplearning4j.nn.conf.MultiLayerConfiguration$Builder.<init>(MultiLayerConfiguration.java:475)
        at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.<init>(NeuralNetConfiguration.java:153)
        at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.<init>(NeuralNetConfiguration.java:159)
        at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.list(NeuralNetConfiguration.java:538)
        at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerConfiguration(KerasSequentialModel.java:183)
        at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:245)
        at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:235)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:224)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:113)
        at com.banma.dataops.timeSeriesDataPrediction.zkWatcherSingleSet$.modelLoadHDFS(zkWatcherSingleSet.scala:97)
        at com.banma.dataops.timeSeriesDataPrediction.zkWatcherSingleSet$.com$banma$dataops$timeSeriesDataPrediction$zkWatcherSingleSet$$modelGet(zkWatcherSingleSet.scala:74)
        at com.banma.dataops.timeSeriesDataPrediction.zkWatcherSingleSet$$anon$1.nodeChanged(zkWatcherSingleSet.scala:56)
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:326)
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:320)
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:100)
        at org.apache.curator.shaded.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:92)
        at org.apache.curator.framework.recipes.cache.NodeCache.setNewData(NodeCache.java:318)
        at org.apache.curator.framework.recipes.cache.NodeCache.processBackgroundResult(NodeCache.java:285)
        at org.apache.curator.framework.recipes.cache.NodeCache.access$300(NodeCache.java:57)
        at org.apache.curator.framework.recipes.cache.NodeCache$3.processResult(NodeCache.java:123)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:883)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:653)
        at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152)
        at org.apache.curator.framework.imps.GetDataBuilderImpl$3.processResult(GetDataBuilderImpl.java:272)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:588)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:500)
Caused by: java.lang.ClassNotFoundException: org.deeplearning4j.nn.conf.BackpropType
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.apache.flink.util.ChildFirstClassLoader.loadClass(ChildFirstClassLoader.java:69)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```
		
		
```
java.lang.NoClassDefFoundError: org/deeplearning4j/nn/conf/NeuralNetConfiguration$Builder
        at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerConfiguration(KerasSequentialModel.java:177)
        at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:245)
        at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:235)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:224)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:113)
        at com.banma.dataops.timeSeriesDataPrediction.zkWatcherSingleSet$.modelLoadHDFS(zkWatcherSingleSet.scala:97)
        at com.banma.dataops.timeSeriesDataPrediction.zkWatcherSingleSet$.com$banma$dataops$timeSeriesDataPrediction$zkWatcherSingleSet$$modelGet(zkWatcherSingleSet.scala:74)
        at com.banma.dataops.timeSeriesDataPrediction.zkWatcherSingleSet$$anon$1.nodeChanged(zkWatcherSingleSet.scala:56)
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:326)
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:320)
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:100)
        at org.apache.curator.shaded.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:92)
        at org.apache.curator.framework.recipes.cache.NodeCache.setNewData(NodeCache.java:318)
        at org.apache.curator.framework.recipes.cache.NodeCache.processBackgroundResult(NodeCache.java:285)
        at org.apache.curator.framework.recipes.cache.NodeCache.access$300(NodeCache.java:57)
        at org.apache.curator.framework.recipes.cache.NodeCache$3.processResult(NodeCache.java:123)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:883)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:653)
        at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152)
        at org.apache.curator.framework.imps.GetDataBuilderImpl$3.processResult(GetDataBuilderImpl.java:272)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:588)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:500)
Caused by: java.lang.ClassNotFoundException: org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.apache.flink.util.ChildFirstClassLoader.loadClass(ChildFirstClassLoader.java:69)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

but I am add the dependency
```
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-nn</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
```

# pom.xml

```
.....................................................
    <!--nd4j-->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-native-platform</artifactId>
                <version>${nd4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-cuda-9.2-platform</artifactId>
                <version>${nd4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-cuda-10.0-platform</artifactId>
                <version>${nd4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-cuda-10.1-platform</artifactId>
                <version>${nd4j.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
.....................................................
      <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>${nd4j.backend}</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.nd4j/nd4j-api -->
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-api</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>jackson</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.nd4j/nd4j-common -->
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-common</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-nn -->
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-nn</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.bytedeco/openblas -->
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>openblas</artifactId>
            <version>0.3.7-1.5.2</version>
        </dependency>

        <!-- Core DL4J functionality -->
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-nlp</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-zoo</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        <!-- ParallelWrapper & ParallelInference live here -->
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-parallel-wrapper</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-core -->
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.bytedeco/hdf5-platform -->
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>hdf5-platform</artifactId>
            <version>1.10.5-1.5.2</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.bytedeco.javacpp-presets/openblas -->
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>openblas</artifactId>
            <version>0.3.5-1.4.4</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.bytedeco.javacpp-presets/openblas-platform -->
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>openblas-platform</artifactId>
            <version>0.3.5-1.4.4</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.bytedeco/javacpp -->
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>1.5.2</version>
        </dependency>
.....................................................
```

**Comment by saudet** [comment]
Please remove all the explicit "javacpp" dependencies.

**Comment by SelfEvoAI** [comment]
thanks.

I am try remove all the explicit "javacpp" dependencies, it works in local idea env.

But not worked in Flink cluster, throw the same exception.

So I add the `nd4j-api-1.0.0-beta5.jar` and `deeplearning4j-nn-1.0.0-beta5.jar` to flink cluster lib.

Throw the new exception:

```
2020-01-17 15:14:43,857 ERROR org.apache.curator.framework.listen.ListenerContainer         - Listener (com.banma.dataops.timeSeriesDataPrediction.zkWatcherSingleSet$$anon$1@6c4af2e3) threw an exception
java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "org/deeplearning4j/nn/conf/NeuralNetConfiguration$Builder"
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at org.apache.flink.util.ChildFirstClassLoader.loadClass(ChildFirstClassLoader.java:69)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerConfiguration(KerasSequentialModel.java:177)
        at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:245)
        at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.getMultiLayerNetwork(KerasSequentialModel.java:235)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:224)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:113)
        at com.banma.dataops.timeSeriesDataPrediction.zkWatcherSingleSet$.modelLoadHDFS(zkWatcherSingleSet.scala:98)
        at com.banma.dataops.timeSeriesDataPrediction.zkWatcherSingleSet$.com$banma$dataops$timeSeriesDataPrediction$zkWatcherSingleSet$$modelGet(zkWatcherSingleSet.scala:75)
        at com.banma.dataops.timeSeriesDataPrediction.zkWatcherSingleSet$$anon$1.nodeChanged(zkWatcherSingleSet.scala:57)
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:326)
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:320)
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:100)
        at org.apache.curator.shaded.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:92)
        at org.apache.curator.framework.recipes.cache.NodeCache.setNewData(NodeCache.java:318)
        at org.apache.curator.framework.recipes.cache.NodeCache.processBackgroundResult(NodeCache.java:285)
        at org.apache.curator.framework.recipes.cache.NodeCache.access$300(NodeCache.java:57)
        at org.apache.curator.framework.recipes.cache.NodeCache$3.processResult(NodeCache.java:123)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:883)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:653)
        at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152)
        at org.apache.curator.framework.imps.GetDataBuilderImpl$3.processResult(GetDataBuilderImpl.java:272)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:588)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:500)

```

why?

**Comment by saudet** [comment]
It looks like some of the classes are loaded by a different class loader for some reason. Try to get everything loaded with the same class loader.

**Comment by SelfEvoAI** [comment]
Thank you.

I am add the nd4j/deeplearnning dependencies to flink cluster env, it works.

```
datavec-api-1.0.0-beta5.jar
datavec-data-codec-1.0.0-beta5.jar
datavec-data-image-1.0.0-beta5.jar
datavec-hadoop-1.0.0-beta5.jar
deeplearning4j-common-1.0.0-beta5.jar
deeplearning4j-core-1.0.0-beta5.jar
deeplearning4j-datasets-1.0.0-beta5.jar
deeplearning4j-datavec-iterators-1.0.0-beta5.jar
deeplearning4j-modelimport-1.0.0-beta5.jar
deeplearning4j-nlp-1.0.0-beta5.jar
deeplearning4j-nn-1.0.0-beta5.jar
deeplearning4j-parallel-wrapper-1.0.0-beta5.jar
deeplearning4j-tsne-1.0.0-beta5.jar
deeplearning4j-ui-components-1.0.0-beta5.jar
deeplearning4j-util-1.0.0-beta5.jar
deeplearning4j-utility-iterators-1.0.0-beta5.jar
deeplearning4j-zoo-1.0.0-beta5.jar
guava-1.0.0-beta5.jar
hdf5-1.10.5-1.5.1.jar
hdf5-1.10.5-1.5.1-linux-ppc64le.jar
hdf5-1.10.5-1.5.1-linux-x86_64.jar
hdf5-1.10.5-1.5.1-linux-x86.jar
hdf5-1.10.5-1.5.1-macosx-x86_64.jar
hdf5-1.10.5-1.5.1-windows-x86_64.jar
hdf5-1.10.5-1.5.1-windows-x86.jar
hdf5-platform-1.10.5-1.5.1.jar
jackson-1.0.0-beta5.jar
javacpp-1.5.1-1.jar
mkl-2019.4-1.5.1.jar
mkl-2019.4-1.5.1-linux-x86_64.jar
mkl-dnn-0.20-1.5.1.jar
mkl-dnn-0.20-1.5.1-linux-x86_64.jar
mkl-dnn-platform-0.20-1.5.1.jar
mkl-platform-2019.4-1.5.1.jar
nd4j-aeron-1.0.0-beta5.jar
nd4j-api-1.0.0-beta5.jar
nd4j-buffer-1.0.0-beta5.jar
nd4j-common-1.0.0-beta5.jar
nd4j-context-1.0.0-beta5.jar
nd4j-jackson-1.0.0-beta5.jar
nd4j-native-1.0.0-beta5-android-arm64.jar
nd4j-native-1.0.0-beta5-android-arm.jar
nd4j-native-1.0.0-beta5-android-x86_64.jar
nd4j-native-1.0.0-beta5-android-x86.jar
nd4j-native-1.0.0-beta5-ios-arm64.jar
nd4j-native-1.0.0-beta5-ios-x86_64.jar
nd4j-native-1.0.0-beta5.jar
nd4j-native-1.0.0-beta5-linux-armhf.jar
nd4j-native-1.0.0-beta5-linux-ppc64le.jar
nd4j-native-1.0.0-beta5-linux-x86_64.jar
nd4j-native-1.0.0-beta5-macosx-x86_64.jar
nd4j-native-1.0.0-beta5-windows-x86_64.jar
nd4j-native-api-1.0.0-beta5.jar
nd4j-native-platform-1.0.0-beta5.jar
nd4j-parameter-server-1.0.0-beta5.jar
nd4j-parameter-server-client-1.0.0-beta5.jar
nd4j-parameter-server-model-1.0.0-beta5.jar
nearestneighbor-core-1.0.0-beta5.jar
openblas-0.3.6-1.5.1.jar
openblas-0.3.6-1.5.1-linux-x86_64.jar
openblas-platform-0.3.6-1.5.1.jar
opencsv-2.3.jar
opencsv-5.0.jar
opencv-4.1.0-1.5.1-linux-x86_64.jar
opencv-platform-4.1.0-1.5.1.jar
protobuf-1.0.0-beta5.jar
```

I do not known why fat jar does not work in flink cluster. Maybe the flink window task and zookeeper watch task excuted different Thread, and the zookeeper watch Thread did not use the prarent dependencies.

**Comment by saudet** [comment]
For uber JARs, we need to be careful to include all required resources, as per the examples:
https://github.com/eclipse/deeplearning4j-examples
