### ISSUE TITLE
error in FeedForwardToRnnPreProcessor when passing batch of different size in testing

### ISSUE THREAD

**Issue by fmorbini** [deeplearning4j/deeplearning4j#8622]
#### Issue Description

test code is provided in the gist below:

https://gist.github.com/fmorbini/62c9588ce36d4a2b441704b0a6435474

was working fine in beta4. switched to beta6 because of https://github.com/eclipse/deeplearning4j/issues/8156 but now the same code does not work.

expected behavior is that the batch sizes used in training and eval should not matter.

#### Version Information
beta6
cpu backend
macosx (catalina)

#### Additional Information
stacktrace:
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: New shape length doesn't match original length: [50] vs [60]. Original shape: [6, 10] New Shape: [5, 1, 10]
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3748)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3693)
	at org.deeplearning4j.nn.conf.preprocessor.FeedForwardToRnnPreProcessor.preProcess(FeedForwardToRnnPreProcessor.java:62)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.applyPreprocessorAndSetInput(LayerVertex.java:118)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.setInput(LayerVertex.java:170)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputOfLayersDetached(ComputationGraph.java:2413)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1741)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1697)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1627)
	at test.TestIssue.notWorking(TestIssue.java:138)
	at test.TestIssue.main(TestIssue.java:145)

**Comment by fmorbini** [comment]
it seems that adding
ComputationGraph.setLabels((INDArray[])null);
before testing fixes the problem. i'll investigate more.

**Comment by fmorbini** [comment]
yes the above change seems to work fine. i'll close the ticket.
