### ISSUE TITLE
java.net.UnknownHostException: blob.deeplearning4j.org

### ISSUE THREAD

**Issue by Murazyan** [deeplearning4j/deeplearning4j#8626]
#### Issue Description

Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information deeplearning4j-zoo : 1.0.0-beta6

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* Platform information (Windows)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

import org.deeplearning4j.zoo.*;
import org.deeplearning4j.zoo.model.VGG16;

ZooModel zooModel =  VGG16.builder().build();
Model net = zooModel.initPretrained(PretrainedType.VGGFACE)

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

Exception in thread "main" java.lang.IllegalStateException: Pretrained model file failed checksum. If this error persists, please open an issue at https://github.com/deeplearning4j/deeplearning4j.
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:93)
	at Main.main(Main.java:33)

but in version 0.9.1, I get error like this`

java.net.UnknownHostException: blob.deeplearning4j.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.URL.openStream(URL.java:1045)
	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1478)
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:64)
	at Main.main(Main.java:33)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by agibsonccc** [comment]
See: https://stackoverflow.com/questions/59096226/caused-by-java-net-unknownhostexception-blob-deeplearning4j-org-problem-with-d/59097874#59097874
