### ISSUE TITLE
sd.rnn.lstmLayer(...) can not be used

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#8640]
java.lang.UnsupportedOperationException: Not yet implemented
	at org.nd4j.linalg.api.ops.impl.layers.recurrent.LSTMLayer.doDiff(LSTMLayer.java:105)
	at org.nd4j.autodiff.functions.DifferentialFunction.diff(DifferentialFunction.java:560)
	at org.nd4j.autodiff.samediff.SameDiff$1.define(SameDiff.java:4443)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:3987)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:3972)
	at org.nd4j.autodiff.samediff.SameDiff.createGradFunction(SameDiff.java:4183)
	at org.nd4j.autodiff.samediff.SameDiff.createGradFunction(SameDiff.java:4090)
	at org.nd4j.autodiff.samediff.SameDiff.fitHelper(SameDiff.java:1669)

**Comment by raver119** [comment]
It means "can't be used for training", but still can be used for inference.
And, yes, it's WIP.
