### ISSUE TITLE
libnd4j: depthwise_conv2d fails with Float16 (+MKLDNN/DNNL)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8646]
The following test runs fine on float32 and bfloat16, fails on float16.
Also runs OK on float16 if I disable helpers, so it's MKLDNN-related.

```
    @Test
    public void test(){
//        Nd4j.getEnvironment().allowHelpers(false);
        DataType dt = DataType.FLOAT16;
//        DataType dt = DataType.BFLOAT16;
//        DataType dt = DataType.FLOAT;
        INDArray in = Nd4j.create(dt, 2, 3, 8, 8);
        INDArray w = Nd4j.create(dt, 5, 5, 3, 1);
        INDArray b = Nd4j.create(dt, 3);

        INDArray out = Nd4j.create(dt, 2, 3, 8, 8);

        DynamicCustomOp op = DynamicCustomOp.builder("depthwise_conv2d")
                .addInputs(in, w, b)
                .addOutputs(out)
                .addIntegerArguments(5, 5, 1, 1, 2, 2, 1, 1, 1)
                .build();

        Nd4j.exec(op);
    }
```

```
o.n.n.Nd4jBlas - Number of threads used for OpenMP BLAS: 8
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [7.1GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute op depthwise_conv2d. Attempted to execute with 3 inputs, 1 outputs, 0 targs,0 bargs and 9 iargs. Inputs: [(HALF,[2,3,8,8],c), (HALF,[5,5,3,1],c), (HALF,[3],c)]. Outputs: [(HALF,[2,3,8,8],c)]. tArgs: -. iArgs: [5, 5, 1, 1, 2, 2, 1, 1, 1]. bArgs: -. Op own name: "a39e3547-047b-43f7-b960-f2f0a72df8b5" - Please see above message (printed out from c++) for a possible cause of error.



java.lang.RuntimeException: Op [depthwise_conv2d] execution failed

	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1661)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6498)
	at org.deeplearning4j.Temp.test(Temp.java:29)
...
Caused by: java.lang.RuntimeException: could not create a primitive descriptor iterator
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1959)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1640)
```

**Comment by raver119** [comment]
float16 is excluded now.
