### ISSUE TITLE
ND4J: NPE for CUDA an Nd4j.create(new double[0])

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8659]
OK on CPU, NPE on CUDA

```
Nd4j.create(new double[0]);
```

```
java.lang.NullPointerException
	at org.nd4j.jita.handler.impl.CudaZeroHandler.memcpyAsync(CudaZeroHandler.java:342)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.memcpyAsync(AtomicAllocator.java:893)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.set(BaseCudaDataBuffer.java:1040)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.setData(BaseCudaDataBuffer.java:1068)
	at org.nd4j.linalg.factory.Nd4j.createTypedBuffer(Nd4j.java:1546)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:1454)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1350)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3540)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3374)
```

Causing a couple of test failures in nearestneighbor-core currently on master

**Comment by raver119** [comment]
Fixed
