### ISSUE TITLE
DL4J: CUDA in-place parallel inference - "Affinity for thread [X] wasn't defined yet"

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8681]
![image](https://user-images.githubusercontent.com/2360237/74003042-544def00-49c5-11ea-8e57-6d69cf2a1b79.png)

This is on a single-GPU (Titan X) windows system on current master.

All except testMultiOutputNet are failing with errors like the following:
```
java.lang.RuntimeException: Affinity for thread [433] wasn't defined yet
	at org.nd4j.jita.concurrency.CudaAffinityManager.getDeviceForThread(CudaAffinityManager.java:77)
	at org.deeplearning4j.parallelism.InplaceParallelInference$ModelSelector.getModelForThread(InplaceParallelInference.java:146)
	at org.deeplearning4j.parallelism.InplaceParallelInference$ModelSelector.getModelForThisThread(InplaceParallelInference.java:160)
	at org.deeplearning4j.parallelism.InplaceParallelInference$ModelSelector.output(InplaceParallelInference.java:156)
	at org.deeplearning4j.parallelism.InplaceParallelInference.output(InplaceParallelInference.java:97)
	at org.deeplearning4j.parallelism.ParallelInference.output(ParallelInference.java:195)
	at org.deeplearning4j.parallelism.ParallelInferenceTest$2.run(ParallelInferenceTest.java:904)
	at java.lang.Thread.run(Thread.java:748)
```

testMultiOutputNet is failing with:
```
arrays first differed at element [1]; 
Expected :[[    0.1522,    0.1803,    0.3499,    0.1026,    0.0988,    0.1162]]
Actual   :[[    0.0252,    0.2892,    0.1261,    0.1446,    0.1878,    0.2271]]
```

**Comment by AlexDBlack** [comment]
This also impacts JsonModelServerTest.basicServingTestForDLSynchronized on CUDA, looks to be exact same issue:
```
java.lang.RuntimeException: Affinity for thread [41] wasn't defined yet
	at org.nd4j.jita.concurrency.CudaAffinityManager.getDeviceForThread(CudaAffinityManager.java:77)
	at org.deeplearning4j.parallelism.InplaceParallelInference$ModelSelector.getModelForThread(InplaceParallelInference.java:146)
	at org.deeplearning4j.parallelism.InplaceParallelInference$ModelSelector.getModelForThisThread(InplaceParallelInference.java:160)
	at org.deeplearning4j.parallelism.InplaceParallelInference$ModelSelector.output(InplaceParallelInference.java:156)
	at org.deeplearning4j.parallelism.InplaceParallelInference.output(InplaceParallelInference.java:97)
```

**Comment by raver119** [comment]
Fixed in my branch. Will be merged later.
