### ISSUE TITLE
UI in snapshot is broken

### ISSUE THREAD

**Issue by lpaatero** [deeplearning4j/deeplearning4j#8725]
#### Issue Description

When creating UI, it should be available, and
` Deeplearning4j UI server started at: http://localhost:9000 `
should be in the log.

In current snapshot, UI is not available, and log entry is not generated.

#### Version Information

Current snapshot.

#### Additional Information

`
2020-02-22 10:51:41.190 - SEVERE: The FreeMarker version requested by "incompatibleImprovements" was 2.3.29, but the installed FreeMarker version is only 2.3.23. You may need to upgrade FreeMarker in your project.
java.lang.IllegalArgumentException: The FreeMarker version requested by "incompatibleImprovements" was 2.3.29, but the installed FreeMarker version is only 2.3.23. You may need to upgrade FreeMarker in your project.
        at freemarker.template._TemplateAPI.checkVersionNotNullAndSupported(_TemplateAPI.java:49)
        at freemarker.core.Configurable.<init>(Configurable.java:309)
        at freemarker.template.Configuration.<init>(Configuration.java:634)
        at org.deeplearning4j.ui.module.train.TrainModule.<init>(TrainModule.java:140)
        at org.deeplearning4j.ui.VertxUIServer.start(VertxUIServer.java:197)
        at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
        at io.vertx.core.Verticle.start(Verticle.java:66)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:556)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
`
Forcing FreeMarker version to 2.3.29 in application pom.xml seem to be workaround.

**Comment by treo** [comment]
You are probably affected by a variant of https://github.com/eclipse/deeplearning4j/issues/8724
please share your pom.xml file, and the output of `mvn dependency:tree` so we can help you find a workaround.

**Comment by lpaatero** [comment]
I have already workaround for this, so no need to find one.

I think problem is already visible in conflicting pom definitions; the 2 poms below should specify same version.
`
 deeplearning4j/deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-ui-components/pom.xml
<properties>
   <freemarker.version>2.3.23</freemarker.version>
</properties>
`
and
`
deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/pom.xml
<dependency>
  <groupId>org.freemarker</groupId>
  <artifactId>freemarker</artifactId>
  <version>2.3.29</version>
</dependency>
`

**Comment by AlexDBlack** [comment]
For future reference - this issue would also be fixed by resolving this issue, currently blocked however - https://github.com/eclipse/deeplearning4j/issues/8750#issuecomment-604244356
