### ISSUE TITLE
Unable to load Google model using loadStaticModel in a workspace. 

### ISSUE THREAD

**Issue by dgarcia-ccc** [deeplearning4j/deeplearning4j#8746]
#### Issue Description
Workspace for loading Google vectors model using loadStaticModel does not load the model outside JVM memory. 

I’m trying to load the google vectors model into DL4j, to use it later. I’m able to do it but with a big cost in RAM memory. I read about workspaces and how the memory is hold off-heap, so I tried to load it using loadStaticModel inside a workspace, just to see if my RAM consumption was lower. However, I’m not able to do it if I set my available amount of RAM to a number less of 3.4 GB (the size of Google vectors model).
So, does it mean the workspaces are there only for certain operations?.
 the code is quite simple:

final WorkspaceConfiguration mmap = WorkspaceConfiguration.builder()
.initialSize(9500000000L)
.policyLocation(LocationPolicy.MMAP)
.policyAllocation(AllocationPolicy.STRICT)
.policyReset(ResetPolicy.ENDOFBUFFER_REACHED)
.tempFilePath("/Users/Downloads/temporalFile.temp")
.build();
final File wordVectorsFile = new File("/sentiment/GoogleNews-vectors-negative3002.bin");
try (final MemoryWorkspace ws = Nd4j.getWorkspaceManager().getAndActivateWorkspace(mmap, "M2")) {
final WordVectors wordVectors = WordVectorSerializer.loadStaticModel(wordVectorsFile);
} 
- expected behavior: 
The memory consumption is lower and Google vectors model is loaded
- encountered behavior
The process fails because vectors couldn't be allocated. 

#### Version Information
* Deeplearning4j version: 1.0.0-beta6
* javacpp 1.5.2.
* Platform information (OS, etc): macOS Mojave or Unix System.

#### Additional Information
This is the stack trace. Numbers are random.
Caused by: java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes (2564) > maxPhysicalBytes (1998) 

#### Contributing
I'm willing to help for fixing this issue, of course.

**Comment by raver119** [comment]
Hm. This error message says that you have 2KB memory allowed? I'm afraid it's not going to work this way. There are other expenses that are unavoidable: libraries loaded, shapes, subarrays etc.

**Comment by dgarcia-ccc** [comment]
Thanks for your reply, @raver119 . 
No, as I said, numbers are random.  I have more than 10GB set. That stacktrace is when I did tests for that amount of memory, but the issue is the same: with less than 3.5 GB, Google vector model doesn't load and I receive an OutOfMemoryException (I set 3GB of memory). Anyway, the amount of memory needed to load the google vector model is the same whether I use Workspace or not.

**Comment by dgarcia-ccc** [comment]
@raver119 just in case this may help, here you are the stacktrace with 1GB set. 

Exception in thread "main" java.lang.OutOfMemoryError: Cannot allocate new LongPointer(1): totalBytes = 8, physicalBytes = 1873M
	at org.bytedeco.javacpp.LongPointer.<init>(LongPointer.java:76)
	at org.bytedeco.javacpp.LongPointer.<init>(LongPointer.java:41)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.createShapeInfo(NativeOpExecutioner.java:2116)
	at org.nd4j.linalg.api.shape.Shape.createShapeInformation(Shape.java:3249)
	at org.nd4j.linalg.api.ndarray.BaseShapeInfoProvider.createShapeInformation(BaseShapeInfoProvider.java:69)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:526)
	at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:125)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:334)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1338)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3536)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3351)
Caused by: java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes (1873M) > maxPhysicalBytes (1821M)
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:659)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:127)
	at org.bytedeco.javacpp.LongPointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.LongPointer.<init>(LongPointer.java:68)
	... 12 more

**Comment by dgarcia-ccc** [comment]
@raver119 I think we can close this issue as I discovered that the metrics I used for memory footprint were not correct at all. 
Sorry for the inconveniences.
