### ISSUE TITLE
Unsupported keras layer type SeparableConv1D

### ISSUE THREAD

**Issue by nesty92** [deeplearning4j/deeplearning4j#8774]
#### Issue Description
Try to load model generated with https://github.com/google/eng-edu/blob/master/ml/guides/text_classification/train_sequence_model.py

Please describe our issue, along with:
- expected behavior
Load keras model
- encountered behavior
Unsupported keras layer type SeparableConv1D

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
1.0.0-beta6
* Platform information (OS, etc) Linux
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
```java
org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type SeparableConv1D. Please file an issue at https://github.com/eclipse/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:320)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:218)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:110)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:57)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:322)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:223)

```
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by treo** [comment]
Unfortunately we don't support `tf.keras` at the moment. The progress is tracked in this issue: https://github.com/eclipse/deeplearning4j/issues/8348

I'm closing this issue as a duplicate.
