### ISSUE TITLE
SameDiff/ND4J: Intermittent threading issue (CPU backend)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8802]
Encountered on CI here:
https://jenkins.konduit.ai/blue/organizations/jenkins/konduitai%2Fdeeplearning4j/detail/PR-330/5/pipeline/672

Also reproduced locally at least once; the vast majority of runs are OK
Edit: increasing the number of threads and runs for SameDiffMultiThreadTests.testMobilenet reliably reproduces this locally.

```
[2020-03-20T20:42:04.487Z] Running org.nd4j.autodiff.samediff.SameDiffMultiThreadTests
[2020-03-20T20:42:04.487Z] o.n.BaseND4JTest - SameDiffMultiThreadTests.testMobilenet
[2020-03-20T20:42:06.385Z] o.n.a.s.SameDiff - Creating new InferenceSession for thread 2171
[2020-03-20T20:42:06.643Z] o.n.a.s.SameDiff - Creating new InferenceSession for thread 2172
[2020-03-20T20:42:06.643Z] o.n.a.s.SameDiff - Creating new InferenceSession for thread 2173
[2020-03-20T20:42:06.643Z] o.n.a.s.SameDiff - Creating new InferenceSession for thread 2174
[2020-03-20T20:42:06.643Z] o.n.a.s.SameDiff - Creating new InferenceSession for thread 2175
[2020-03-20T20:42:07.576Z] o.n.a.s.SameDiffMultiThreadTests - Error in thread: 2175
[2020-03-20T20:42:07.576Z] java.lang.RuntimeException: Bad datatype B
[2020-03-20T20:42:07.576Z] 	at org.nd4j.nativeblas.Nd4jCpu.setGraphContextOutputBuffer(Native Method)
[2020-03-20T20:42:07.576Z] 	at org.nd4j.linalg.cpu.nativecpu.ops.CpuOpContext.setOutputArray(CpuOpContext.java:117)
[2020-03-20T20:42:07.576Z] 	at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:895)
[2020-03-20T20:42:07.576Z] 	at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:69)
[2020-03-20T20:42:07.576Z] 	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:384)
```

**Comment by AlexDBlack** [comment]
OK, so it looks like the same error is happening at different locations:

* Nd4jCpu.setGraphContextOutputBuffer
* Nd4jCpu.setGraphContextInputBuffer
* NativeOpExecutioner.exec
* NativeOpExecutioner.calculateOutputShape

Note also that the error isn't occuring right at the start - iteration 590, iteration 7, iteration 95, etc


Note that in the exec case here, there's no boolean datatype used - it's just a simple reshape :/
(same thing in calculateOutputShape  for reshape op below)
```
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute op reshape. Attempted to execute with 2 inputs, 1 outputs, 0 targs,0 bargs and 0 iargs. Inputs: [(FLOAT,[1,1001],c), (INT,[2],c)]. Outputs: [(FLOAT,[1,1001],c)]. tArgs: -. iArgs: -. bArgs: -. Op own name: "MobilenetV2/Predictions/Reshape_1". Input var names: [MobilenetV2/Predictions/Softmax, MobilenetV2/Predictions/Shape]. Output var names: [MobilenetV2/Predictions/Reshape_1] - Please see above message (printed out from c++) for a possible cause of error.
o.n.a.s.SameDiffMultiThreadTests - Error in thread: 42 at iteration 7
java.lang.RuntimeException: Bad datatype B
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:2059)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6578)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.doExec(InferenceSession.java:496)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:223)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:69)
```

```
o.n.a.s.SameDiffMultiThreadTests - Error in thread: 34 at iteration 95
java.lang.RuntimeException: Bad datatype B
	at org.nd4j.nativeblas.Nd4jCpu.setGraphContextInputBuffer(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.CpuOpContext.setInputArray(CpuOpContext.java:109)
	at org.nd4j.linalg.api.ops.BaseOpContext.setInputArrays(BaseOpContext.java:187)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:858)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:69)
```

```
o.n.l.c.n.o.NativeOpExecutioner - Failed to calculate output shapes for op reshape. Attempted to execute with 2 inputs, 0 outputs, 0 targs, 0 iargs, 0 bargs and 0 dargs. Inputs: [(FLOAT,[1,1001],c), (INT,[2],c)]. Input var names: [MobilenetV2/Logits/Squeeze, MobilenetV2/Predictions/Reshape/shape]. Output var names: [MobilenetV2/Predictions/Reshape] - Please see above message (printed out from c++) for a possible cause of error.
o.n.a.s.SameDiffMultiThreadTests - Error in thread: 41 at iteration 59
java.lang.RuntimeException: Bad datatype B
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.calculateOutputShape(NativeOpExecutioner.java:1835)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.calculateOutputShape(DynamicCustomOp.java:546)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:876)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:69)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:384)
```

**Comment by AlexDBlack** [comment]
I have also noted that:
* it appears to always be the same reshape operation (never seen any other nodes for this).
* it is not related to SameDiff memory management (switching to ArrayCloseMemMgr makes no difference)

Here's the calculateOutputShape error in debugger. Note that:
* Same "Bad datatype B" error as before
* Shape infos look fine (no booleans here; dtype extra matches array datatype - 8192=float, 131072=int)


![image](https://user-images.githubusercontent.com/2360237/77380429-2551d800-6dcf-11ea-82c3-308b3ace4177.png)

**Comment by AlexDBlack** [comment]
Looks like it's almost certainly a threading issue... can't reproduce this single threaded after around 85,000 iterations of forward pass through this net.

**Comment by agibsonccc** [comment]
Closing — SameDiff has been completely rewritten with a new DSP (Dynamic Shape Plan) execution engine, native plan compilation, CUDA graph replay, and Triton compilation. The architecture referenced in this issue no longer exists. If you still experience this issue with the upcoming release, please open a new issue.
