### ISSUE TITLE
Uptraining ParagraphVectors issue

### ISSUE THREAD

**Issue by bewithme** [deeplearning4j/deeplearning4j#8805]
#### Issue Description

Please describe our issue, along with:
- train ParagraphVectors with LabelAwareIterator and save it by  
`WordVectorSerializer.writeParagraphVectors(paragraphVectors, MODEL_SAVE_PATH);`
and restore it by   `paragraphVectors=WordVectorSerializer.readParagraphVectors(MODEL_SAVE_PATH);`
and up train it by
 ```
 paragraphVectors=WordVectorSerializer.readParagraphVectors(MODEL_SAVE_PATH);
    	  paragraphVectors.setTokenizerFactory(tokenizerFactory);
    	  paragraphVectors.setLabelAwareIterator(iterator);
```

 throw an exception like bellow:
```
xception in thread "main" java.lang.IllegalStateException: You can't fit() data without SequenceIterator defined
	at org.deeplearning4j.models.sequencevectors.SequenceVectors.fit(SequenceVectors.java:260)
	at org.deeplearning4j.models.paragraphvectors.ParagraphVectors.fit(ParagraphVectors.java:669)
	at com.ctcc.cs.model.DialogueClassifierTrainer.makeParagraphVectors(DialogueClassifierTrainer.java:106)
	at com.ctcc.cs.model.DialogueClassifierTrainer.main(DialogueClassifierTrainer.java:51)
```
#### Version Information

Please indicate relevant versions, including, if relevant:

* DL4J beta4/DL4J beta5/DL4J beta6
* mac OS

**Comment by agibsonccc** [comment]
Closing — references a removed/rewritten subsystem (DataVec, NLP/Word2Vec, Model Zoo, Spark, UI, or Arbiter). These have been fundamentally rewritten or removed in the upcoming release. Please open a new issue if you experience similar problems with the new version.
