### ISSUE TITLE
TSNEStandardExample fails with exception

### ISSUE THREAD

**Issue by ejc123** [deeplearning4j/deeplearning4j#881]
o.d.e.t.TSNEStandardExample - Load & Vectorize data....
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.io.LineIterator.next()Ljava/lang/String;
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadTxt(WordVectorSerializer.java:472)
	at org.deeplearning4j.examples.tsne.TSNEStandardExample.main(TSNEStandardExample.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 1

**Comment by ejc123** [comment]
I actually found the issue while trying to run TSNEStandardExample from dl4j-0.4-examples, but the issue was with the deeplearning4j library, so I opened the issue here.

**Comment by agibsonccc** [comment]
Fixed in the next release.
