### ISSUE TITLE
Invalid input name: "fc6_2" not found in list of network inputs ([imageIn, descriptionOut]) while configuring network for Image Captioning

### ISSUE THREAD

**Issue by linuxciscoarnaud** [deeplearning4j/deeplearning4j#8811]
#### Issue Description

Hello,

I am having the following issue while trying to implement Image Captioning using DL4J.
I am basically trying to make use of the seq2seq RNNs implementation that was used to perform the addition operation and which can be found  [here](https://github.com/eclipse/deeplearning4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/seq2seq). 

But instead of using input strings as input of the encoder, I want to use vectors that contains features of onput images and which are the outputs of the second Dense Layer of VGG16 net.

So the architecture of my network contains two components: a CNN connected to a RNN. But I am having the following error:

```java
Exception in thread "main" java.lang.IllegalArgumentException: Invalid input name: "fc6_2" not found in list of network inputs ([imageIn, descriptionOut])
	at org.deeplearning4j.nn.graph.vertex.impl.rnn.LastTimeStepVertex.<init>(LastTimeStepVertex.java:64)
	at org.deeplearning4j.nn.graph.vertex.impl.rnn.LastTimeStepVertex.<init>(LastTimeStepVertex.java:53)
	at org.deeplearning4j.nn.conf.graph.rnn.LastTimeStepVertex.instantiate(LastTimeStepVertex.java:92)
	at org.deeplearning4j.nn.conf.graph.rnn.LastTimeStepVertex.instantiate(LastTimeStepVertex.java:38)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:552)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:434)
	at com.imagecaptioning.ImageCaptioning.execute(ImageCaptioning.java:58)
	at com.imagecaptioning.ImageCaptioning.main(ImageCaptioning.java:123)

```

Here is the network architecture:

```java
         ComputationGraphConfiguration conf = new NeuralNetConfiguration.Builder()
				.seed(params.getSeed())
				.optimizationAlgo(params.getOptimizationAlgorithm())
				.updater(params.getUpdater())
				.cacheMode(params.getCacheMode())
                .trainingWorkspaceMode(params.getWorkspaceMode())
                .inferenceWorkspaceMode(params.getWorkspaceMode())
				
				.graphBuilder()
				
				//The 2 inputs of the network )
                .addInputs("imageIn", "descriptionOut")
				
                // CNN blocks
                
				// block 1
                .addLayer("conv1_1", new ConvolutionLayer.Builder()
                		.kernelSize(3, 3)
                		.stride(1, 1)
                		.padding(1, 1)
                		.nIn(params.getChannels())
                		.nOut(64)
                		.activation(params.getActivation())
                		.build(), "imageIn") //Output: (224-3+2)/1+1 = 224 -> 224*224*64
                .addLayer("conv1_2", new ConvolutionLayer.Builder()
                		.kernelSize(3, 3)
                		.stride(1, 1)
                		.padding(1, 1)
                		.nIn(64)
                		.nOut(64)
                		.activation(params.getActivation())
                		.build(), "conv1_1") 
                .addLayer("maxpool1_1", new SubsamplingLayer.Builder()
                		.poolingType(SubsamplingLayer.PoolingType.MAX)
                		.kernelSize(2, 2)
                		.stride(2, 2)
                		.build(), "conv1_2")  //Output: (224-2+0)/2+1 = 112 -> 112*112*64
                
                // block 2
                .addLayer("conv2_1", new ConvolutionLayer.Builder()
                		.kernelSize(3, 3)
                		.stride(1, 1)
                		.padding(1, 1)
                		.nIn(64)
                		.nOut(128)
                		.activation(params.getActivation())
                		.build(), "maxpool1_1") //Output: (112-3+2)/1+1 = 112 -> 112*112*128
                .addLayer("conv2_2", new ConvolutionLayer.Builder()
                		.kernelSize(3, 3)
                		.stride(1, 1)
                		.padding(1, 1)
                		.nIn(128)
                		.nOut(128)
                		.activation(params.getActivation())
                		.build(), "conv2_1") 
                .addLayer("maxpool2_1", new SubsamplingLayer.Builder()
                		.poolingType(SubsamplingLayer.PoolingType.MAX)
                		.kernelSize(2, 2)
                		.stride(2, 2)
                		.build(), "conv2_2")   //Output: (112-2+0)/2+1 = 56 -> -> 56*56*128
                
                 // block 3
                .addLayer("conv3_1", new ConvolutionLayer.Builder()
                		.kernelSize(3, 3)
                		.stride(1, 1)
                		.padding(1, 1)
                		.nIn(128)
                		.nOut(256)
                		.activation(params.getActivation())
                		.build(), "maxpool2_1")   //Output: (56-3+2)/1+1 = 56 -> 56*56*256
                .addLayer("conv3_2", new ConvolutionLayer.Builder()
                		.kernelSize(3, 3)
                		.stride(1, 1)
                		.padding(1, 1)
                		.nIn(256)
                		.nOut(256)
                		.activation(params.getActivation())
                		.build(), "conv3_1")    
                .addLayer("conv3_3", new ConvolutionLayer.Builder()
                		.kernelSize(3, 3)
                		.stride(1, 1)
                		.padding(1, 1)
                		.nIn(256)
                		.nOut(256)
                		.activation(params.getActivation())
                		.build(), "conv3_2")   
                .addLayer("maxpool3_1", new SubsamplingLayer.Builder()
                		.poolingType(SubsamplingLayer.PoolingType.MAX)
                		.kernelSize(2, 2)
                		.stride(2, 2)
                		.build(), "conv3_3")    //Output: (56-2+0)/2+1 = 28 -> 28*28*256
                
                // block 4
                .addLayer("conv4_1", new ConvolutionLayer.Builder()
                		.kernelSize(3, 3)
                		.stride(1, 1)
                		.padding(1, 1)
                		.nIn(256)
                		.nOut(512)
                		.activation(params.getActivation())
                		.build(), "maxpool3_1")    //Output: (28-3+2)/1+1 = 28 -> 28*28*512
                .addLayer("conv4_2", new ConvolutionLayer.Builder()
                		.kernelSize(3, 3)
                		.stride(1, 1)
                		.padding(1, 1)
                		.nIn(512)
                		.nOut(512)
                		.activation(params.getActivation())
                		.build(), "conv4_1")  
                .addLayer("conv4_3", new ConvolutionLayer.Builder()
                		.kernelSize(3, 3)
                		.stride(1, 1)
                		.padding(1, 1)
                		.nIn(512)
                		.nOut(512)
                		.activation(params.getActivation())
                		.build(), "conv4_2")   
                .addLayer("maxpool4_1", new SubsamplingLayer.Builder()
                		.poolingType(SubsamplingLayer.PoolingType.MAX)
                		.kernelSize(2, 2)
                		.stride(2, 2)
                		.build(), "conv4_3")     //Output: (28-2+0)/2+1 = 14 -> 14*14*512
                
                // block 5
                .addLayer("conv5_1", new ConvolutionLayer.Builder()
                		.kernelSize(3, 3)
                		.stride(1, 1)
                		.padding(1, 1)
                		.nIn(512)
                		.nOut(512)
                		.activation(params.getActivation())
                		.build(), "maxpool4_1")   //Output: (14-3+2)/1+1 = 14 -> 14*14*512
                .addLayer("conv5_2", new ConvolutionLayer.Builder()
                		.kernelSize(3, 3)
                		.stride(1, 1)
                		.padding(1, 1)
                		.nIn(512)
                		.nOut(512)
                		.activation(params.getActivation())
                		.build(), "conv5_1")   
                .addLayer("conv5_3", new ConvolutionLayer.Builder()
                		.kernelSize(3, 3)
                		.stride(1, 1)
                		.padding(1, 1)
                		.nIn(512)
                		.nOut(512)
                		.activation(params.getActivation())
                		.build(), "conv5_2")   
                .addLayer("maxpool5_1", new SubsamplingLayer.Builder()
                		.poolingType(SubsamplingLayer.PoolingType.MAX)
                		.kernelSize(2, 2)
                		.stride(2, 2)
                		.build(), "conv5_3")  //Output: (14-2+0)/2+1 = 7 -> 7*7*512
                
                // block 6
                .addLayer("fc6_1", new DenseLayer.Builder()
                		.nIn(7*7*512)
                		.nOut(4096)
                		.activation(params.getActivation())
                		.dropOut(0.5)
                		.build(), "maxpool5_1")
                .addLayer("fc6_2", new DenseLayer.Builder()
                		.nIn(4096)
                		.nOut(4096)
                		.activation(params.getActivation())
                		.dropOut(0.5)
                		.build(), "fc6_1")
                
                
                // RNN block
                
                //All the inputs to the encoder will have size = batchSize * FeatureVectorSize * timesteps 
                .addLayer("encoder", new LSTM.Builder()
                		.nIn(4096)
                		.nOut(params.getNumHiddenNodes())
                		.activation(Activation.SOFTSIGN)
                		.build(), "fc6_2")
                
                //Vertex indicating the very last time step of the encoder layer
                .addVertex("lastTimeStep", new LastTimeStepVertex("fc6_2"), "encoder")
                
                //Create a vertex that allows the duplication of 2d input to a 3d input
                .addVertex("duplicateTimeStep", new DuplicateToTimeSeriesVertex("descriptionOut"), "lastTimeStep")
                
                //The inputs to the decoder will have size = size of output of last timestep of encoder (numHiddenNodes) + size of the other input
                .addLayer("decoder", new LSTM.Builder()
                		.nIn(params.getFeatureVectorSize() + params.getNumHiddenNodes())
                		.nOut(params.getNumHiddenNodes())
                		.activation(Activation.SOFTSIGN)
                		.build(), "descriptionOut", "duplicateTimeStep")
                
                .addLayer("output", new RnnOutputLayer.Builder()
                		.nIn(params.getNumHiddenNodes())
                		.nOut(params.getFeatureVectorSize())
                		.activation(Activation.SOFTMAX).lossFunction(LossFunctions.LossFunction.MCXENT)
                		.build(), "decoder")              
				
                
                .inputPreProcessor("conv1_1", new RnnToCnnPreProcessor(params.getHeight(), params.getWidth(), params.getChannels()))
                .inputPreProcessor("fc6_1", new CnnToFeedForwardPreProcessor(7, 7, 512))
                .inputPreProcessor("encoder", new FeedForwardToRnnPreProcessor())
                
                .setOutputs("output")
				.build();
				
		return new ComputationGraph(conf);	
```

#### Version Information

* Deeplearning4j version: 1.0.0-beta3
* Platform information: windows 8.1 64 bit

**Comment by AlexDBlack** [comment]
Sorry for not replying sooner.

I would suggest upgrading to 1.0.0-beta6.
Also try using the LastTimeStep wrapper layer instead - so something like:
.addLayer("lastTimeStep", new LastTimeStep(new LSTM... ), "fc6_2")
i.e., wrap the encoder LSTM layer with the LastTimeStep layer

**Comment by linuxciscoarnaud** [comment]
Sorry for the late reply

I have upgrated from 1.0.0-beta3 to 1.0.0-beta6, but got the following error:

```java
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:579)
	at com.imagecaptioning.NetworkConfig.getNetworkConfig(NetworkConfig.java:36)
	at com.imagecaptioning.ImageCaptioning.execute(ImageCaptioning.java:60)
	at com.imagecaptioning.ImageCaptioning.main(ImageCaptioning.java:126)
Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5131)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:226)
	... 4 more
Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:218)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5128)
	... 5 more
```

This error appears to be caused by the fact that the nd4j backend is missing. So I thought adding the latest version of nd4j-native-platform in pom file could fix it, but it didn't worked out (the same error message kept showing up). I decided to try deeplearning4j 1.0.0-beta5 and the error disappeared. I am curious to know why. But now (with 1.0.0-beta5), after using the LastTimeStep wrapper layer as suggested i am having another problem during training right after have completed the first mini batch:

```java
Exception in thread "main" java.lang.IllegalArgumentException: Incorrect number of arguments for permute function: got arguments [0, 2, 1] for rank 4 array. Number of arguments must equal array rank
	at org.nd4j.base.Preconditions.throwEx(Preconditions.java:636)
	at org.nd4j.base.Preconditions.checkArgument(Preconditions.java:137)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.permute(BaseNDArray.java:4888)
	at org.deeplearning4j.nn.conf.preprocessor.RnnToCnnPreProcessor.preProcess(RnnToCnnPreProcessor.java:84)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.applyPreprocessorAndSetInput(LayerVertex.java:118)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.setInput(LayerVertex.java:170)
	at org.deeplearning4j.nn.graph.ComputationGraph.ffToLayerActivationsInWS(ComputationGraph.java:2171)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1372)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1341)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:170)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1165)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1115)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1082)
	at com.imagecaptioning.ImageCaptioning.execute(ImageCaptioning.java:69)
	at com.imagecaptioning.ImageCaptioning.main(ImageCaptioning.java:126)
```

**Comment by AlexDBlack** [comment]
re: NoAvailableBackendException - my guess is maybe you're using Eclipse IDE?
It's notoriously bad with maven support.
i.e., you change the version in your pom.xml but it usually doesn't realize that anything has actually changed.

> Incorrect number of arguments for permute function: got arguments [0, 2, 1] for rank 4 array. Number of arguments must equal array rank

As for that - it's coming from this preprocessor:
```
.inputPreProcessor("conv1_1", new RnnToCnnPreProcessor(params.getHeight(), params.getWidth(), params.getChannels()))
```

It suggests that your data is bad - i.e., you're trying to feed in images while you're simultaneously telling it to expect time series.
Hard to say without more info, but maybe you just need to delete that preprocessor line altogether?

**Comment by linuxciscoarnaud** [comment]
Thanks for the quick reply.

1. Yes, you are right. I am using Eclipse IDE. I think I will definitely move to another IDE because this limitation is in addition to several others regarding this IDE. It's just that I was already used to it.

2. My data was bad and i think i have corrected it. But I am still having issues and as you said, it would be better for me to provide more infos to allow you to help me more effectively. So [here] (https://github.com/linuxciscoarnaud/ImageCaptioning)  is the github repository where you can find the entire code of how I am trying to solve this problem, because posting it all here would be very tedious. You will notice that there is very few training data (just 4). Right now I just wanna make sure I have an appropriate network architeture which can train data that is not bad. Here is the issue I am having now:

```java
Exception in thread "main" java.lang.IllegalStateException: Cannot do backward pass: all epsilons not set. Layer "encoder" (idx 22), numInputs :1; numOutputs: 0
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doBackward(LayerVertex.java:133)
	at org.deeplearning4j.nn.graph.ComputationGraph.calcBackpropGradients(ComputationGraph.java:2712)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1381)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1341)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:170)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1165)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1115)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1082)
	at com.imagecaptioning.ImageCaptioning.execute(ImageCaptioning.java:65)
	at com.imagecaptioning.ImageCaptioning.main(ImageCaptioning.java:122)
```
