### ISSUE TITLE
DL4J Spark + CUDA: CI NaN evaluation issue

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8830]
On current master, I'm seeing a CUDA-specific test failure: TestSparkDl4jMultiLayer.testEvaluationSimple
https://jenkins.konduit.ai/blue/organizations/jenkins/konduitai%2Fdeeplearning4j/detail/PR-364/1/pipeline

Basically, NaNs appear in the predictions (network output) during evaluation.

It's intermittent, but also reproducible locally on Windows (if I run the test in a loop).

Adding NaN check seems to "fix" it (i.e., not reproducible when enabled).
```
Nd4j.getExecutioner().setProfilingConfig(ProfilerConfig.builder().checkForNAN(true).checkWorkspaces(true).build());
```

```
[2020-04-08T01:39:04.441Z] o.a.s.e.Executor - Exception in task 1.0 in stage 13.0 (TID 53)
[2020-04-08T01:39:04.441Z] java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Cannot perform evaluation with NaNs present in predictions: 640 NaNs present in predictions INDArray
[2020-04-08T01:39:04.441Z] 	at org.deeplearning4j.spark.impl.evaluation.EvaluationRunner$EvaluationFuture.get(EvaluationRunner.java:242)
[2020-04-08T01:39:04.442Z] 	at org.deeplearning4j.spark.impl.evaluation.EvaluationRunner$EvaluationFuture.get(EvaluationRunner.java:214)
[2020-04-08T01:39:04.442Z] 	at org.deeplearning4j.spark.impl.multilayer.evaluation.IEvaluateFlatMapFunction.call(IEvaluateFlatMapFunction.java:73)
[2020-04-08T01:39:04.442Z] 	at org.deeplearning4j.spark.impl.multilayer.evaluation.IEvaluateFlatMapFunction.call(IEvaluateFlatMapFunction.java:38)
[2020-04-08T01:39:04.442Z] 	at org.apache.spark.api.java.JavaRDDLike.$anonfun$mapPartitions$1(JavaRDDLike.scala:153)
[2020-04-08T01:39:04.442Z] Caused by: java.lang.IllegalStateException: Cannot perform evaluation with NaNs present in predictions: 640 NaNs present in predictions INDArray
[2020-04-08T01:39:04.442Z] 	at org.nd4j.base.Preconditions.throwStateEx(Preconditions.java:641)
[2020-04-08T01:39:04.442Z] 	at org.nd4j.base.Preconditions.checkState(Preconditions.java:286)
[2020-04-08T01:39:04.442Z] 	at org.nd4j.evaluation.classification.Evaluation.eval(Evaluation.java:403)
[2020-04-08T01:39:04.442Z] 	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doEvaluationHelper(MultiLayerNetwork.java:3459)
[2020-04-08T01:39:04.442Z] 	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doEvaluation(MultiLayerNetwork.java:3406)
```

**Comment by AlexDBlack** [comment]
Closing in favor if this, which is the underlying cause: https://github.com/eclipse/deeplearning4j/issues/8831
