### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException on model.setListeners(new ConvolutionalIterationListener(1));

### ISSUE THREAD

**Issue by Eljah** [deeplearning4j/deeplearning4j#8839]
#### Issue Description

I have updated my pet project's class https://github.com/Eljah/worsecodeever/blob/master/src/main/java/Main3.java with adding 

`model.setListeners(new ConvolutionalIterationListener(1));`

to line 94 in order to obtain activation maps in UIServer.

As soon as line was added, the execution fails with:

```
Exception in thread "main" java.lang.RuntimeException
	at org.deeplearning4j.ui.weights.ConvolutionalIterationListener.onForwardPass(ConvolutionalIterationListener.java:143)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1378)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1342)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:170)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1166)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1116)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1083)
	at Main3.main(Main3.java:103)

```

#### Version Information

* Deeplearning4j version - 

        <nd4j.version>1.0.0-beta6</nd4j.version>
        <dl4j.version>1.0.0-beta6</dl4j.version>
        <datavec.version>1.0.0-beta6</datavec.version>
        <nd4j.backend>nd4j-native-platform</nd4j.backend>

* Platform information (OS, etc) - Windows10
* CUDA version, if used - not used
* NVIDIA driver version, if in use - not used

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

do I need a gist, if the full project can be downloaded from the github?

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

Data it is trained on: 

![image](https://user-images.githubusercontent.com/2749858/79431406-18419680-7fd3-11ea-9085-fd3d3ca8a04f.png)

one image in the /out folder is enough toreproduce

**Comment by treo** [comment]
Can you please provide some of the training data your are using? Without it I can't run your code to reproduce the issue.

**Comment by Eljah** [comment]
I have uploaded the only file that is enough to have as the only in the folder to reproduce the issue

It looks like it has been converted to PNG during my copy paste, please convert it to JPEG, put to the out folder, and you'll get exactly what happens.

**Comment by treo** [comment]
Does the file need a specific name in the folder? It fails with an exception from your code for me:
```
java.lang.ArrayIndexOutOfBoundsException: 6
	at CaptchaLoader.convertDataSet(CaptchaLoader.java:132)
	at CaptchaLoader.next(CaptchaLoader.java:722)
	at CaptchaSetIterator.next(CaptchaSetIterator.java:51)
	at CaptchaSetIterator.next(CaptchaSetIterator.java:95)
	at CaptchaSetIterator.next(CaptchaSetIterator.java:31)
```

**Comment by Eljah** [comment]
right, it should be placed at D:\captchas\out

D:\captchas is configured in https://github.com/Eljah/worsecodeever/blob/master/src/main/java/CaptchaLoader.java line 88 so you may change this to select another location. the out folder is configured in Main3.java  line 94

` MultiDataSetIterator trainMulIterator = new CaptchaSetIterator(batchSize, "out");`

**Comment by treo** [comment]
It is configured like that, but the filename of the file is now "79431406-18419680-7fd3-11ea-9085-fd3d3ca8a04f.png" (or with a .jpg after converting). Is this the name that it is supposed to have?

**Comment by Eljah** [comment]
Oh, it was just substituted by the github. The actual name should be "000164.jpg" (not "*.jpeg")

**Comment by treo** [comment]
You are seeing this error because the ConvolutionalListener at the moment doesn't support multiple outputs. 

But even then there appears to be issues when using it together with a Computation Graph, as even after fixing those compatibility issues, the resulting figure doesn't look right:
![image](https://user-images.githubusercontent.com/509379/79450233-f7823c80-7fe4-11ea-9f93-ed70fa0bd39a.png)

**Comment by Eljah** [comment]
So for now there is no easy work around for me as the end user, something should be fixed, right?

**Comment by treo** [comment]
Yes. Unfortunately, that feature seems to have issues at the moment. 

But, if you want to try to fix it yourself, you can do that pretty easily, because this listener is super modular :) You can just copy it into your project and start making it as you like it.

**Comment by agibsonccc** [comment]
Closing — references a removed/rewritten subsystem (DataVec, NLP/Word2Vec, Model Zoo, Spark, UI, or Arbiter). These have been fundamentally rewritten or removed in the upcoming release. Please open a new issue if you experience similar problems with the new version.
