### ISSUE TITLE
ArrayIndexOutOfBoundsException in KerasReshape.getInputPreprocessor

### ISSUE THREAD

**Issue by nfeybesse** [deeplearning4j/deeplearning4j#8846]
When importing Keras simple model : 

input_data = Input(name='input', shape=(64, 128, 32), dtype='float32')
output = Reshape(target_shape=(64,128 * 32), name='reshape')(input_data) 

Exception : 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at org.deeplearning4j.nn.modelimport.keras.layers.core.KerasReshape.getInputPreprocessor(KerasReshape.java:117)
	at org.deeplearning4j.nn.modelimport.keras.layers.core.KerasReshape.getOutputType(KerasReshape.java:179)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.inferOutputTypes(KerasModel.java:304)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:179)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:96)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:307)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelConfiguration(KerasModelImport.java:335)
	at org.genericsystem.ai.dl4j.KerasImport.main(KeraImport.java:21)

* Deeplearning4j beta6
* Kubuntu 1604
* CUDA 10.2
* Keras 2.3.1
* Tensorflow-gpu 2.1.0

Python full code : 

import os
from keras import backend as K
from keras.layers import Input, Dense
from keras.layers import Reshape, Lambda, Flatten
from keras.models import Model

if __name__ == '__main__':
  
    input_data = Input(name='input', shape=(64, 128, 32), dtype='float32')
    output = Reshape(target_shape=(64,128 * 32), name='reshape')(input_data)
    
    model = Model(inputs=input_data, outputs=output)
    model.summary()
    model_json = model.to_json()
    with open("model.json", "w") as json_file:
         json_file.write(model_json)
    print("done")

Java code :

ComputationGraphConfiguration configuration = KerasModelImport.importKerasModelConfiguration(model);

I Resolve the problem with an intermediary layer in model :
input_data = Input(name='input', shape=(64, 128, 32), dtype='float32')
inner = Flatten()(input_data)
output = Reshape(target_shape=(64,128 * 32), name='reshape')(inner)

**Comment by agibsonccc** [comment]
Closing — references a removed/rewritten subsystem (DataVec, NLP/Word2Vec, Model Zoo, Spark, UI, or Arbiter). These have been fundamentally rewritten or removed in the upcoming release. Please open a new issue if you experience similar problems with the new version.
