### ISSUE TITLE
"org.nd4j.linalg.api.blas.BlasException: Failed to execute sgesvd: -1011" when running PCA

### ISSUE THREAD

**Issue by lukaszbachman** [deeplearning4j/deeplearning4j#8873]
I am running PCA with MMAP on large matrix (2000 x 110000). At some point in the process `pca_factor()` is failing with the following exception:

```
org.nd4j.linalg.api.blas.BlasException: Failed to execute sgesvd: -1011
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuLapack.sgesvd(CpuLapack.java:202)
	at org.nd4j.linalg.api.blas.impl.BaseLapack.gesvd(BaseLapack.java:240)
	at org.nd4j.linalg.dimensionalityreduction.PCA.pca_factor(PCA.java:256)
```

Smaller experiments using the same code does not show the same error. Maybe a matter of scale then? Regardless, I was hoping you could shed some light as to what this exception and `-1011` really means.

#### Version Information

* ND4J 1.0.0-beta3, CPU backend
* Windows 10

**Comment by saudet** [comment]
@rcorbish Would you know?

**Comment by saudet** [comment]
According to the documentation of `sgesvd()`, that's what the number means:
```
          INFO is INTEGER
          = 0:  successful exit.
          < 0:  if INFO = -i, the i-th argument had an illegal value.
          > 0:  if SBDSQR did not converge, INFO specifies how many
                superdiagonals of an intermediate bidiagonal form B
                did not converge to zero. See the description of WORK
                above for details.
```

You may want to try MKL, which is often more stable than OpenBLAS. Follow these instructions:
https://github.com/bytedeco/javacpp-presets/tree/master/openblas#documentation

**Comment by lukaszbachman** [comment]
I think I'm using MKL already, at least that's what I can judge by this output:

```
11:25:48.914 [main] INFO  Loaded [CpuBackend] backend
11:25:50.904 [main] INFO  Number of threads used for NativeOps: 6
11:25:51.557 [main] INFO  Number of threads used for BLAS: 6
11:25:51.564 [main] INFO  Backend used: [CPU]; OS: [Windows 10]
11:25:51.564 [main] INFO  Cores: [12]; Memory: [8,0GB];
11:25:51.564 [main] INFO  Blas vendor: [MKL]
```
Am I right here?

**Comment by saudet** [comment]
Looks like it, yes.

**Comment by lukaszbachman** [comment]
Yeah I verified on my 2nd Linux box and I can see that it logged `Blas vendor: [OPENBLAS]`. I'll try to run some more tests to verify if this is really related to the size of the matrix.

**Comment by rcorbish** [comment]
Not obvious. The negative arg indicates which parameter is driving the issue, but -1011 is not right in this case. Let me try.
This might take about 30-60 seconds. Was the error returned very quickly?

**Comment by lukaszbachman** [comment]
It failed after 1 minute 9 seconds after `PCA.pca_factor()` was invoked. Hope that helps.

**Comment by rcorbish** [comment]
I get OOM errors trying to create an array of 110,000 x 110,000 (part of svd needs a buffer of nxn for the input mxn matrix).
If I use a size of 110_000 x 2000, it works, I used 8Gb, Java 11 on Linux  ND4J 1.0.0-beta6

        Nd4j.setDefaultDataTypes( DataType.FLOAT, DataType.FLOAT );
        INDArray A = Nd4j.rand(  2_000, 110_000 ) ;
        A = A.reshape('c', 110_000, 2_000);
        INDArray X = PCA.pca_factor( A, .80, false ) ;
        System.out.println( X ) ;

I tried both CPU and GPU  ( choose 1 of the platforms below)

    compile group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-beta6'
    compile group: 'org.nd4j', name: 'nd4j-native-platform', version: '1.0.0-beta6'   // OR
    compile group: 'org.nd4j', name: 'nd4j-cuda-10.2-platform', version: '1.0.0-beta6'

The GPU solver failed, with OOM or an error (GPU cannot solve tall-thin matrices if I remember). But this is a different issue.

**Comment by lukaszbachman** [comment]
Ok, so I ran few more tests. First of all - your sample code seems to be working fine on Linux. I'm running these tests on boxes of different hardware specs, but it didn't seem to be a problem.

Now, here comes the interesting part. I ran your sample on Windows where I had this problem originally. It works fine there too, but if I comment out the matrix reshaping it will fail with:

```
17:48:49.657 [main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for OpenMP BLAS: 6
17:48:49.670 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
17:48:49.670 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [12]; Memory: [8,0GB];
17:48:49.670 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
Exception in thread "main" org.nd4j.linalg.api.blas.BlasException: Failed to execute sgesvd: -1011
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuLapack.sgesvd(CpuLapack.java:207)
	at org.nd4j.linalg.api.blas.impl.BaseLapack.gesvd(BaseLapack.java:236)
	at org.nd4j.linalg.dimensionalityreduction.PCA.pca_factor(PCA.java:256)
	at xxx.yyy.pca.Dl4jPca.main(Dl4jPca.java:175)
Not enough memory to transpose matrix in LAPACKE_sgesvd_work
```

So it looks like this reshaping helps to avoid this issue. Why are you even doing this in the first place? Isn't computing PCA factor on `2k times 110k` the same as running it on `100k times 2k` matrix?

BTW in this experiment OpenBlas is logged as vendor, I have no idea why yet. I'll investigate later.

**Comment by saudet** [comment]
Yup, looks like a normal OOM error in LAPACK:
```
include/lapacke.h:#define LAPACK_TRANSPOSE_MEMORY_ERROR  -1011
```
Try to increase the size of the swap space/page file available to the OS, and/or decrease the amount of memory used by other processes, the JVM, etc.

**Comment by rcorbish** [comment]
Good questions:
I do the reshape to try 2 things:
1) assume matrix is in column order
2) to make sure OOM is **not** due to matrix allocation

in svd the outputs are a function of the input matrix:
svd A (m x n)  =>  U S V'
U is (m x m)
S is [special] diagonal (m x m)  { max N entries }
V is (n x n)  {transpose is same dimension}

So the SVD result  A(a x b) is not the same as A(b x a)

In PCA , depending on the factoring needed we may need nxn or mxm values. If you can share what you need to do - maybe we can help a better (less memory pressure) option/

110_000 x 110_000 = 12GB * sizeof(float)   

PCA can project N data points onto K data points ( K<N ), but we still have M observations

so we need a transformation PCA

A ( M x N )  * PCA  = R ( M x K )  (R is reduced dimension [K<N] observation)

implies PCA is shape ( N x K )   .. N is orig data points, K is magic from SVD

**Comment by lukaszbachman** [comment]
@saudet that could work in theory, although our app is pretty RAM hungry even without ND4J, so obviously we would hit a limit rather sooner than latter. I would also like to avoid causing too much stress on the OS, as this will run in a server environment. I guess ideal solution to me would be for these calculations to simply run longer under limited resources I assign to the process.

@rcorbish so if I understood you correctly the reshaping was only an experiment and can't serve as a workaround of any sort, as it would produce different results. That is what I was expecting.
To answer your question - we are using PCA for reducing the number of features on a TFIDF matrix. The more observations (aka. samples/documents/rows) we add, the more features (aka. terms/tokens/columns) will get produced. Especially that each observation can contribute random new features to the overall matrix, depending on how much unseen text it contains. Long story short - we can have N >> M. I'll start looking into changing our model so that we can reduce the number of features, but ideal situation for me would be to reduce the memory consumption even without it.

**Comment by rcorbish** [comment]
Yes, the transpose will produce a completely different result. I am trying to think of any other way to solve this. The only thing I have come up with is to limit N to the most popular elements in the dataset.

**Comment by lukaszbachman** [comment]
Yes we are already filtering N terms, so we will try to focus on doing it in a more effective way. I just wanted to know if there is something we can do to prepare for the unexpected growth of the matrix. I suppose making those calculations iteratively is not an option? Or even repeating some of them for the sake of less memory consumption?

**Comment by rcorbish** [comment]
It's hard to predict how much memory you will use, vs how cheap and available memory upgrades become.
It may be possible to iterate to calc each eigenvalue (power iterations), but you do that for each eigenvalue (in your case 100K ).

**Comment by agibsonccc** [comment]
Closing — references a removed/rewritten subsystem (DataVec, NLP/Word2Vec, Model Zoo, Spark, UI, or Arbiter). These have been fundamentally rewritten or removed in the upcoming release. Please open a new issue if you experience similar problems with the new version.
