### ISSUE TITLE
TfidfVectorizer.vectorize() throws NPE when fitted with LabelAwareIterator

### ISSUE THREAD

**Issue by bpossolo** [deeplearning4j/deeplearning4j#8886]
#### Issue Description

**Encountered**
TfidfVectorizer.vectorize() throws an NPE if a LabelAwareIterator is used to fit the TfidfVectorizer

cause: the LabelsSource isn't get populated during fitting and TfidfVectorizer.vectorize(String, String) expects LabelsSource to be non-empty... this results in an NPE

**Expected**
LabelsSource should be populated during fitting and vectorize() should not throw a NPE.

#### Version Information

* Deeplearning4j version: 1.0.0-beta6
* Platform information (OS, etc): mac os x 10.15.3 + java openjdk 11.0.6
* CUDA version: n/a
* NVIDIA driver version: n/a

#### Additional Information

Code to reproduce
```
public void testTfIdfVectorizerFromLabelAwareIterator() throws Exception {
  LabelledDocument doc1 = new LabelledDocument();
  doc1.addLabel("dog");
  doc1.setContent("it barks like a dog");

  LabelledDocument doc2 = new LabelledDocument();
  doc2.addLabel("cat");
  doc2.setContent("it meows like a cat");

  List<LabelledDocument> docs = new ArrayList<>(2);
  docs.add(doc1);
  docs.add(doc2);
        
  LabelAwareIterator iterator = new SimpleLabelAwareIterator(docs);
  TokenizerFactory tokenizerFactory = new DefaultTokenizerFactory();

  TfidfVectorizer vectorizer = new TfidfVectorizer
    .Builder()
    .setMinWordFrequency(1)
    .setStopWords(new ArrayList<String>())
    .setTokenizerFactory(tokenizerFactory)
    .setIterator(iterator)
    .allowParallelTokenization(false)
    .build();

  vectorizer.fit();
  vectorizer.vectorize("it meows like a cat", "cat"); // throws NPE
}
```

Stacktrace
```
java.lang.NullPointerException
	at org.deeplearning4j.text.documentiterator.LabelsSource.indexOf(LabelsSource.java:65)
	at org.deeplearning4j.bagofwords.vectorizer.TfidfVectorizer.vectorize(TfidfVectorizer.java:83)
	at org.deeplearning4j.bagofwords.vectorizer.TfidfVectorizerTest.testTfIdfVectorizerFromLabelAwareIterator(TfidfVectorizerTest.java:154)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

**Comment by raver119** [comment]
Fix merged
