### ISSUE TITLE
NPE on w2vec example

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/deeplearning4j#8902]
Running with snapshots. Code [here](https://github.com/KonduitAI/deeplearning4j-examples-refactor/blob/master/cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/advanced/w2vsentiment/ImdbReviewClassificationRNN.java#L64)

```
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for linear algebra: 32
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Linux]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [64]; Memory: [26.7GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.JCublasBackend - ND4J CUDA build version: 10.2.89
o.n.l.j.JCublasBackend - CUDA device 0: [GeForce RTX 2060 SUPER]; cc: [7.5]; Total memory: [8368685056]
o.n.l.j.JCublasBackend - CUDA device 1: [GeForce RTX 2060 SUPER]; cc: [7.5]; Total memory: [8370061312]
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
o.d.n.l.r.LSTM - cuDNN not found: use cuDNN for better GPU performance by including the deeplearning4j-cuda module. For more information, please refer to: https://deeplearning4j.org/docs/latest/deeplearning4j-config-cudnn
java.lang.ClassNotFoundException: org.deeplearning4j.cuda.recurrent.CudnnLSTMHelper
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
Exception in thread "main" java.lang.NullPointerException
        at org.nd4j.linalg.dataset.ExistingMiniBatchDataSetIterator.<init>(ExistingMiniBatchDataSetIterator.java:58)
        at org.nd4j.linalg.dataset.ExistingMiniBatchDataSetIterator.<init>(ExistingMiniBatchDataSetIterator.java:47)
        at org.deeplearning4j.examples.multigpu.advanced.w2vsentiment.ImdbReviewClassificationRNN.main(ImdbReviewClassificationRNN.java:106)
```

**Comment by raver119** [comment]
Is it reproducible on CPU?

**Comment by eraly** [comment]
Will check

**Comment by raver119** [comment]
Pure Java issue by the looks of it. Added null check to iterator constructor.

**Comment by eraly** [comment]
Closing. Also changed example to automatically run presave. Thank you @raver119
