### ISSUE TITLE
Gradient sharing mnist errors out

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/deeplearning4j#8903]
Running with snapshots, no cudnn

Code [here](https://github.com/KonduitAI/deeplearning4j-examples-refactor/blob/master/cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/quickstart/GradientsSharingLeNetMNIST.java#L48) 

```
o.d.o.s.a.EncodingHandler - Threshold at iter 0, epoch 0 [thread 31]: 1e-4, DENSE updates
o.d.p.ParallelWrapper - Uncaught exception: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: execDecoder(...) failedError code [700]
Exception in thread "main" o.d.p.ParallelWrapper - Uncaught exception: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: execDecoder(...) failedError code [700]
Exception in thread "DeallocatorServiceThread_3" Exception in thread "DeallocatorServiceThread_0" Exception in thread "DeallocatorServiceThread_1" Exception in thread "DeallocatorServiceThread_2" java.lang.RuntimeException: java.lang.RuntimeException: [DEVICE] deallocation failed; Error code: [700]
        at org.nd4j.linalg.api.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:139)
Caused by: java.lang.RuntimeException: [DEVICE] deallocation failed; Error code: [700]
        at org.nd4j.nativeblas.Nd4jCuda.deleteDataBuffer(Native Method)
        at org.nd4j.jita.allocator.impl.CudaDeallocator.deallocate(CudaDeallocator.java:38)
        at org.nd4j.linalg.api.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:134)
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: execDecoder(...) failedError code [700]
        at org.deeplearning4j.parallelism.trainer.DefaultTrainer.run(DefaultTrainer.java:449)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.deeplearning4j.parallelism.ParallelWrapper$2$1.run(ParallelWrapper.java:159)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: execDecoder(...) failedError code [700]
        at org.deeplearning4j.optimize.solvers.accumulation.EncodedGradientsAccumulator.applyUpdate(EncodedGradientsAccumulator.java:339)
        at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:88)
        at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fitHelper(MultiLayerNetwork.java:2311)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:2269)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:2332)
        at org.deeplearning4j.parallelism.trainer.DefaultTrainer.fit(DefaultTrainer.java:236)
        at org.deeplearning4j.parallelism.trainer.DefaultTrainer.run(DefaultTrainer.java:385)
        ... 4 more
Caused by: java.lang.RuntimeException: execDecoder(...) failedError code [700]
        at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.thresholdDecode(CudaExecutioner.java:1812)
        at org.deeplearning4j.optimize.solvers.accumulation.EncodedGradientsAccumulator.applyUpdate(EncodedGradientsAccumulator.java:298)
        ... 11 more
java.lang.RuntimeException: java.lang.RuntimeException: [DEVICE] deallocation failed; Error code: [700]
        at org.nd4j.linalg.api.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:139)
Caused by: java.lang.RuntimeException: [DEVICE] deallocation failed; Error code: [700]
        at org.nd4j.nativeblas.Nd4jCuda.deleteDataBuffer(Native Method)
        at org.nd4j.jita.allocator.impl.CudaDeallocator.deallocate(CudaDeallocator.java:38)
        at org.nd4j.linalg.api.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:134)
java.lang.RuntimeException: java.lang.RuntimeException: [DEVICE] deallocation failed; Error code: [700]
        at org.nd4j.linalg.api.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:139)
Caused by: java.lang.RuntimeException: [DEVICE] deallocation failed; Error code: [700]
        at org.nd4j.nativeblas.Nd4jCuda.deleteDataBuffer(Native Method)
        at org.nd4j.jita.allocator.impl.CudaDeallocator.deallocate(CudaDeallocator.java:38)
        at org.nd4j.linalg.api.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:134)
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: execDecoder(...) failedError code [700]
        at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:593)
        at org.deeplearning4j.examples.multigpu.quickstart.GradientsSharingLeNetMNIST.main(GradientsSharingLeNetMNIST.java:131)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: execDecoder(...) failedError code [700]
        at org.deeplearning4j.parallelism.trainer.DefaultTrainer.waitTillRunning(DefaultTrainer.java:463)
        at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:591)
        ... 1 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: execDecoder(...) failedError code [700]
        at org.deeplearning4j.optimize.solvers.accumulation.EncodedGradientsAccumulator.applyUpdate(EncodedGradientsAccumulator.java:339)
        at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:88)
        at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fitHelper(MultiLayerNetwork.java:2311)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:2269)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:2332)
        at org.deeplearning4j.parallelism.trainer.DefaultTrainer.fit(DefaultTrainer.java:236)
        at org.deeplearning4j.parallelism.trainer.DefaultTrainer.run(DefaultTrainer.java:385)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.deeplearning4j.parallelism.ParallelWrapper$2$1.run(ParallelWrapper.java:159)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: execDecoder(...) failedError code [700]
        at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.thresholdDecode(CudaExecutioner.java:1812)
        at org.deeplearning4j.optimize.solvers.accumulation.EncodedGradientsAccumulator.applyUpdate(EncodedGradientsAccumulator.java:298)
        ... 11 more
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: execDecoder(...) failedError code [700]
        at org.deeplearning4j.parallelism.trainer.DefaultTrainer.run(DefaultTrainer.java:449)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.deeplearning4j.parallelism.ParallelWrapper$2$1.run(ParallelWrapper.java:159)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: execDecoder(...) failedError code [700]
        at org.deeplearning4j.optimize.solvers.accumulation.EncodedGradientsAccumulator.applyUpdate(EncodedGradientsAccumulator.java:339)
        at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:88)
        at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fitHelper(MultiLayerNetwork.java:2311)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:2269)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:2332)
        at org.deeplearning4j.parallelism.trainer.DefaultTrainer.fit(DefaultTrainer.java:236)
        at org.deeplearning4j.parallelism.trainer.DefaultTrainer.run(DefaultTrainer.java:385)
        ... 4 more
Caused by: java.lang.RuntimeException: execDecoder(...) failedError code [700]
        at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.thresholdDecode(CudaExecutioner.java:1812)
        at org.deeplearning4j.optimize.solvers.accumulation.EncodedGradientsAccumulator.applyUpdate(EncodedGradientsAccumulator.java:298)
        ... 11 more
java.lang.RuntimeException: java.lang.RuntimeException: [DEVICE] deallocation failed; Error code: [700]
        at org.nd4j.linalg.api.memory.deallocation.DeallocatorService$DeallocatorServiceThread.run(DeallocatorService.java:139)
Caused by: java.lang.RuntimeException: [DEVICE] deallocation failed; Error code: [700]
        at org.nd4j.nativeblas.Nd4jCuda.deleteDataBuffer(Native Method)
```

**Comment by raver119** [comment]
Fixed
