### ISSUE TITLE
Exception thrown while loading some *.h5 keras models with deeplearning4j 1.0.0-beta6

### ISSUE THREAD

**Issue by mateuszbugaj** [deeplearning4j/deeplearning4j#8942]
#### Issue Description
I'm training models in keras and trying to use them in Java with dl4j and have encountered some unpredictable behavior. Some models successfully load while others throw `java.lang.NullPointerException`.
For example keras model from XOR example that looks like this:
```
model = Sequential([
    Dense(units=8, activation='tanh', input_dim=2), 
    Dense(units=1, activation='sigmoid')
])
``` 
will load and work just fine while model from iris classification example that looks like this:
```
model = Sequential([
    Dense(units=40, activation = "relu"),
    Dense(units=40, activation = "relu"),
    Dense(units=40, activation = "relu"),
    Dense(units=3, activation = "softmax")
])
```
will always throw exception.
I'm guessing it's compatibility issue? Is there a version of keras I should downgrade to and give a try?  

#### Version Information
* Deeplearning4j version 1.0.0-beta6
* Windows version 1903
* Keras version 2.2.4-tf

#### Additional Information

* Java code I'm running:
```
    static MultiLayerNetwork model;
    static String modelName = "iris_nn.h5";

    public static void main(String[] args) {

        try {
            String modelPatch = new ClassPathResource(modelName).getFile().getPath();
            model = KerasModelImport.importKerasSequentialModelAndWeights(modelPatch);
        } catch (IOException | UnsupportedKerasConfigurationException | InvalidKerasConfigurationException e) {
            e.printStackTrace();
        }
    }
```

* Exception stack trace:
```
Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.nn.modelimport.keras.layers.KerasInput.<init>(KerasInput.java:103)
	at org.deeplearning4j.nn.modelimport.keras.layers.KerasInput.<init>(KerasInput.java:83)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:120)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:57)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:322)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:223)
	at Main.main(Main.java:21)
```

* pom.xml
https://gist.github.com/mateuszbugaj/cb2ad7a8def86d77f46b683626a971ef

**Comment by mateuszbugaj** [comment]
Ok, I got this. The issue is that in the first layer input dimension have to be specified and I didn't know about it. Now it loads every time from what I see.
