### ISSUE TITLE
Android Model Loading Error with 1.0.0-beta6

### ISSUE THREAD

**Issue by zhangy10** [deeplearning4j/deeplearning4j#8951]
#### Issue Description

I got a runtime bug after updating the version to the latest 1.0.0-beta6. Please double-check the below log. It crashes when I am trying to normally load a model for inference. 

It seems to be the ```multidex``` issue, and it cannot find the class "org.slf4j.LoggerFactory", but I have tried the solutions and they didn't work. 

1.0.0-beta4 doesn't have this issue, and both 1.0.0-beta5 and beta6 have this one. So, I am wondering how to add this class into the project. 

Thanks.

#### Version Information

1.0.0-beta6
Mac Catalina 10.15.1
Android Studio 3.6.3

```
2020-05-14 21:11:59.823 28586-28632/? E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.zac, PID: 28586
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/slf4j/LoggerFactory;
        at org.deeplearning4j.util.ModelSerializer.<clinit>(ModelSerializer.java:56)
        at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:378)
        at com.zac.traintest.Inference.loadModel(Inference.java:42)
        at com.zac.service.ProviderService$2.run(ProviderService.java:138)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.slf4j.LoggerFactory" on path: DexPathList[[zip file "/data/app/com.zac-7lNS7ky76htsVLmlBKORBg==/base.apk"],nativeLibraryDirectories=[/data/app/com.zac-7lNS7ky76htsVLmlBKORBg==/lib/arm64, /data/app/com.zac-7lNS7ky76htsVLmlBKORBg==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.deeplearning4j.util.ModelSerializer.<clinit>(ModelSerializer.java:56) 
        at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:378) 
        at com.zac.traintest.Inference.loadModel(Inference.java:42) 
        at com.zac.service.ProviderService$2.run(ProviderService.java:138) 
        at java.lang.Thread.run(Thread.java:764) 


```

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
//        applicationId "com.samsung.android.sdk.accessory.example.hellomessage.provider"
        applicationId "com.zac"
        minSdkVersion 27
        targetSdkVersion 27
        versionCode 1
        versionName '1.0.0'
        // handle methods too much issue
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/INDEX.LIST'
    }

//    compileOptions {
//        sourceCompatibility 1.8
//        targetCompatibility 1.8
//    }


    dexOptions {
        javaMaxHeapSize '4g'
    }
}

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'


    // for dl4j training beta4
//    implementation(group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-beta4') {
//        exclude group: 'org.bytedeco.javacpp-presets', module: 'opencv-platform'
//        exclude group: 'org.bytedeco.javacpp-presets', module: 'leptonica-platform'
//        exclude group: 'org.bytedeco.javacpp-presets', module: 'hdf5-platform'
//        exclude group: 'org.nd4j', module: 'nd4j-base64'
//    }
//
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta4'
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta4', classifier: "android-arm"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta4', classifier: "android-arm64"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta4', classifier: "android-x86"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta4', classifier: "android-x86_64"



    implementation (group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-beta6') {
        exclude group: 'org.bytedeco', module: 'opencv-platform'
        exclude group: 'org.bytedeco', module: 'leptonica-platform'
        exclude group: 'org.bytedeco', module: 'hdf5-platform'
        exclude group: 'org.nd4j', module: 'nd4j-base64'
    }
    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta6'
    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta6', classifier: "android-arm"
    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta6', classifier: "android-arm64"
    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta6', classifier: "android-x86"
    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta6', classifier: "android-x86_64"


//    implementation (group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-beta5') {
//        exclude group: 'org.bytedeco', module: 'opencv-platform'
//        exclude group: 'org.bytedeco', module: 'leptonica-platform'
//        exclude group: 'org.bytedeco', module: 'hdf5-platform'
//        exclude group: 'org.nd4j', module: 'nd4j-base64'
//    }
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta5'
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta5', classifier: "android-arm"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta5', classifier: "android-arm64"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta5', classifier: "android-x86"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta5', classifier: "android-x86_64"


    implementation group: 'org.bytedeco', name: 'openblas', version: '0.3.5-1.5'
    implementation group: 'org.bytedeco', name: 'openblas', version: '0.3.5-1.5', classifier: "android-arm"
    implementation group: 'org.bytedeco', name: 'openblas', version: '0.3.5-1.5', classifier: "android-arm64"
    implementation group: 'org.bytedeco', name: 'openblas', version: '0.3.5-1.5', classifier: "android-x86"
    implementation group: 'org.bytedeco', name: 'openblas', version: '0.3.5-1.5', classifier: "android-x86_64"
    implementation group: 'org.bytedeco', name: 'opencv', version: '4.0.1-1.5'
    implementation group: 'org.bytedeco', name: 'opencv', version: '4.0.1-1.5', classifier: "android-arm"
    implementation group: 'org.bytedeco', name: 'opencv', version: '4.0.1-1.5', classifier: "android-arm64"
    implementation group: 'org.bytedeco', name: 'opencv', version: '4.0.1-1.5', classifier: "android-x86"
    implementation group: 'org.bytedeco', name: 'opencv', version: '4.0.1-1.5', classifier: "android-x86_64"
    implementation group: 'org.bytedeco', name: 'leptonica', version: '1.78.0-1.5'
    implementation group: 'org.bytedeco', name: 'leptonica', version: '1.78.0-1.5', classifier: "android-arm"
    implementation group: 'org.bytedeco', name: 'leptonica', version: '1.78.0-1.5', classifier: "android-arm64"
    implementation group: 'org.bytedeco', name: 'leptonica', version: '1.78.0-1.5', classifier: "android-x86"
    implementation group: 'org.bytedeco', name: 'leptonica', version: '1.78.0-1.5', classifier: "android-x86_64"


    //    compileOptions {
    //        sourceCompatibility JavaVersion.VERSION_1_8
    //        targetCompatibility JavaVersion.VERSION_1_8
    //    }

//    implementation 'org.slf4j:slf4j-nop:1.7.25'

//    implementation group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'


    implementation 'com.android.support:multidex:1.0.3'
}


```

**Comment by zhangy10** [comment]
Upate: training also has a similar issue that the class cannot be found, please see below.

```
2020-05-14 23:22:34.792 7250-7346/com.zac E/AndroidRuntime: FATAL EXCEPTION: TestTrainer
    Process: com.zac, PID: 7250
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/nd4j/linalg/function/Function;
        at com.zac.traintest.trainer.TestTrainer.train(TestTrainer.java:48)
        at com.zac.traintest.trainer.BaseTrainer.runTask(BaseTrainer.java:153)
        at com.zac.base.BaseTask.run(BaseTask.java:28)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.nd4j.linalg.function.Function" on path: DexPathList[[zip file "/data/app/com.zac-SUe584cdGG-YpUiobqucBQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.zac-SUe584cdGG-YpUiobqucBQ==/lib/arm64, /data/app/com.zac-SUe584cdGG-YpUiobqucBQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.zac.traintest.trainer.TestTrainer.train(TestTrainer.java:48) 
        at com.zac.traintest.trainer.BaseTrainer.runTask(BaseTrainer.java:153) 
        at com.zac.base.BaseTask.run(BaseTask.java:28) 
        at java.lang.Thread.run(Thread.java:764) 

```

**Comment by saudet** [comment]
Please try again with 1.0.0-beta7.

**Comment by zhangy10** [comment]
@saudet After trying the beta7, it seems I get the build error again. I already use the latest SDK and android studio, and beta6 and beta5 can work without this error.

I also put the gradle code and please double-check if anything is missing. Thanks.

```
java.lang.ArrayIndexOutOfBoundsException: 65535
	at com.android.tools.r8.graph.F0.b(:4)
	at com.android.tools.r8.dex.j.a(:587)
	at com.android.tools.r8.dex.a$a.b(:14)
	at com.android.tools.r8.dex.a$a.a(:28)
	at com.android.tools.r8.dex.a.a(:69)
	at com.android.tools.r8.dex.a.a(:12)
	at com.android.tools.r8.D8.d(:6)
	at com.android.tools.r8.D8.b(:1)
	at com.android.tools.r8.utils.O.a(:30)
	at com.android.tools.r8.D8.run(:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:117)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:445)
	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:348)
	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)


> Task :app:mergeExtDexDebug FAILED
> Task :app:mergeDebugNativeLibs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > java.lang.ArrayIndexOutOfBoundsException: 65535
```

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
//        applicationId "com.samsung.android.sdk.accessory.example.hellomessage.provider"
        applicationId "com.zac"
        minSdkVersion 27
        targetSdkVersion 27
        versionCode 1
        versionName '1.0.0'
        // handle methods too much issue
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/INDEX.LIST'
    }

//    compileOptions {
//        sourceCompatibility 1.8
//        targetCompatibility 1.8
//    }


    dexOptions {
        javaMaxHeapSize '4g'
    }
}

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'


    // for dl4j training beta4
//    implementation(group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-beta4') {
//        exclude group: 'org.bytedeco.javacpp-presets', module: 'opencv-platform'
//        exclude group: 'org.bytedeco.javacpp-presets', module: 'leptonica-platform'
//        exclude group: 'org.bytedeco.javacpp-presets', module: 'hdf5-platform'
//        exclude group: 'org.nd4j', module: 'nd4j-base64'
//    }
//
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta4'
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta4', classifier: "android-arm"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta4', classifier: "android-arm64"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta4', classifier: "android-x86"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta4', classifier: "android-x86_64"



//    implementation (group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-beta6') {
//        exclude group: 'org.bytedeco', module: 'opencv-platform'
//        exclude group: 'org.bytedeco', module: 'leptonica-platform'
//        exclude group: 'org.bytedeco', module: 'hdf5-platform'
//        exclude group: 'org.nd4j', module: 'nd4j-base64'
//    }
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta6'
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta6', classifier: "android-arm"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta6', classifier: "android-arm64"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta6', classifier: "android-x86"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta6', classifier: "android-x86_64"


//    implementation (group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-beta5') {
//        exclude group: 'org.bytedeco', module: 'opencv-platform'
//        exclude group: 'org.bytedeco', module: 'leptonica-platform'
//        exclude group: 'org.bytedeco', module: 'hdf5-platform'
//        exclude group: 'org.nd4j', module: 'nd4j-base64'
//    }
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta5'
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta5', classifier: "android-arm"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta5', classifier: "android-arm64"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta5', classifier: "android-x86"
//    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta5', classifier: "android-x86_64"

    implementation (group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-beta7') {
        exclude group: 'org.bytedeco', module: 'opencv-platform'
        exclude group: 'org.bytedeco', module: 'leptonica-platform'
        exclude group: 'org.bytedeco', module: 'hdf5-platform'
        exclude group: 'org.nd4j', module: 'nd4j-base64'
    }
    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta7'
    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta7', classifier: "android-arm"
    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta7', classifier: "android-arm64"
    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta7', classifier: "android-x86"
    implementation group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-beta7', classifier: "android-x86_64"


    implementation group: 'org.bytedeco', name: 'openblas', version: '0.3.5-1.5'
    implementation group: 'org.bytedeco', name: 'openblas', version: '0.3.5-1.5', classifier: "android-arm"
    implementation group: 'org.bytedeco', name: 'openblas', version: '0.3.5-1.5', classifier: "android-arm64"
    implementation group: 'org.bytedeco', name: 'openblas', version: '0.3.5-1.5', classifier: "android-x86"
    implementation group: 'org.bytedeco', name: 'openblas', version: '0.3.5-1.5', classifier: "android-x86_64"
    implementation group: 'org.bytedeco', name: 'opencv', version: '4.0.1-1.5'
    implementation group: 'org.bytedeco', name: 'opencv', version: '4.0.1-1.5', classifier: "android-arm"
    implementation group: 'org.bytedeco', name: 'opencv', version: '4.0.1-1.5', classifier: "android-arm64"
    implementation group: 'org.bytedeco', name: 'opencv', version: '4.0.1-1.5', classifier: "android-x86"
    implementation group: 'org.bytedeco', name: 'opencv', version: '4.0.1-1.5', classifier: "android-x86_64"
    implementation group: 'org.bytedeco', name: 'leptonica', version: '1.78.0-1.5'
    implementation group: 'org.bytedeco', name: 'leptonica', version: '1.78.0-1.5', classifier: "android-arm"
    implementation group: 'org.bytedeco', name: 'leptonica', version: '1.78.0-1.5', classifier: "android-arm64"
    implementation group: 'org.bytedeco', name: 'leptonica', version: '1.78.0-1.5', classifier: "android-x86"
    implementation group: 'org.bytedeco', name: 'leptonica', version: '1.78.0-1.5', classifier: "android-x86_64"


    //    compileOptions {
    //        sourceCompatibility JavaVersion.VERSION_1_8
    //        targetCompatibility JavaVersion.VERSION_1_8
    //    }

//    implementation 'org.slf4j:slf4j-nop:1.7.25'

//    implementation group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'


    implementation 'com.android.support:multidex:1.0.3'
}
```

**Comment by saudet** [comment]
@RobAltena Where are your working example projects?

**Comment by zhangy10** [comment]
@saudet I tried the example, which is the DL4JIrisClassifierDemo with the beta7 config. But, I get new build errors, and please check down below. I didn't modify any things.

```
One or more instruction is preventing default interface method from being desugared: java.lang.Double it.unimi.dsi.fastutil.objects.Reference2DoubleMap.getOrDefault(java.lang.Object, java.lang.Double)

One or more instruction is preventing default interface method from being desugared: java.util.function.Consumer it.unimi.dsi.fastutil.chars.CharConsumer.andThen(java.util.function.Consumer)


Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/zhangyu/.gradle/caches/modules-2/files-2.1/it.unimi.dsi/fastutil/8.1.1/5f0cc29ae9c2ea9a04db247abf2444cd6f14e0b4/fastutil-8.1.1.jar


Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.


Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete

Caused by: com.android.tools.r8.utils.AbortException: Error: /Users/zhangyu/.gradle/caches/modules-2/files-2.1/it.unimi.dsi/fastutil/8.1.1/5f0cc29ae9c2ea9a04db247abf2444cd6f14e0b4/fastutil-8.1.1.jar:it/unimi/dsi/fastutil/chars/CharConsumer.class, One or more instruction is preventing default interface method from being desugared: java.util.function.Consumer it.unimi.dsi.fastutil.chars.CharConsumer.andThen(java.util.function.Consumer)

Error: /Users/zhangyu/.gradle/caches/modules-2/files-2.1/it.unimi.dsi/fastutil/8.1.1/5f0cc29ae9c2ea9a04db247abf2444cd6f14e0b4/fastutil-8.1.1.jar:it/unimi/dsi/fastutil/chars/CharConsumer.class, One or more instruction is preventing default interface method from being desugared: java.util.function.Consumer it.unimi.dsi.fastutil.chars.CharConsumer.andThen(java.util.function.Consumer)


```

**Comment by zhangy10** [comment]
@saudet Update, I test beta6 works well using this example. So, the beta7 still shows the above build errors.

**Comment by zhangy10** [comment]
@saudet After some updates compared with the example, my app works well with beta6. So, all good for me. But, beta7 still has build errors. So, please double-check that. 

Thanks again.

**Comment by saudet** [comment]
Please try again with 1.0.0-SNAPSHOT.

**Comment by agibsonccc** [comment]
Closing due to inactivity
