### ISSUE TITLE
TF import / Nd4j : sort issue on CUDA

### ISSUE THREAD

**Issue by atuzhykov** [deeplearning4j/deeplearning4j#8960]
During TF import tests was noticed, that `Nd4j.sort` method returns incorrect array (prelast element can be the same as next or previous). For e.g. take a look how sorted shuffled before array for TF and SD. 
```
[2020-05-16T14:47:37.160Z] TF: [      2,      4,      7,      9]
[2020-05-16T14:47:37.160Z] SD: [      2,      4,      9,      9]
[2020-05-16T14:47:37.160Z] o.n.i.T.TFGraphTestAllSameDiff - ERROR Executing test: random_shuffle/rank1_int32 - input keys []
[2020-05-16T14:47:37.160Z] java.lang.AssertionError: Predictions do not match on random_shuffle/rank1_int32, node RandomShuffle
[2020-05-16T14:47:37.160Z] 	at org.junit.Assert.fail(Assert.java:88)
[2020-05-16T14:47:37.160Z] 	at org.junit.Assert.assertTrue(Assert.java:41)
[2020-05-16T14:47:37.160Z] 	at org.nd4j.imports.TFGraphs.TFGraphTestAllHelper.checkOnlyOutput(TFGraphTestAllHelper.java:236)
[2020-05-16T14:47:37.160Z] 	at org.nd4j.imports.TFGraphs.TFGraphTestAllSameDiff.testOutputOnly(TFGraphTestAllSameDiff.java:244)
[2020-05-16T14:47:37.160Z] 	at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
[2020-05-16T14:47:37.160Z] o.n.i.T.TFGraphTestAllSameDiff - TFGraphTestAllSameDiff: Starting parameterized test: testOutputOnly[random_shuffle/rank1_float32](org.nd4j.imports.TFGraphs.TFGraphTestAllSameDiff)
[2020-05-16T14:47:37.160Z] o.n.i.T.TFGraphTestAllHelper - RUNNING TEST random_shuffle/rank1_float32...
[2020-05-16T14:47:37.160Z] TF: [    0.230894327,    0.724374652,    0.778785586,    0.801197767]
[2020-05-16T14:47:37.160Z] SD: [    0.230894327,    0.724374652,    0.724374652,    0.801197767]
```
Also take a note for different implementations of `sort` for [CPU](https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/linalg/cpu/nativecpu/CpuNDArrayFactory.java#L1043-L1053) and [CUDA](https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/main/java/org/nd4j/linalg/jcublas/JCublasNDArrayFactory.java#L1331-L1384)

Those issue happens only on linux_x86_64_cuda_10.0, windows_x86_64_cuda_10.0 and windows_x86_64_cuda_10.2 on our CI

**Comment by raver119** [comment]
1. How Nd4j.sort is related to SameDiff tests? Not quire following.
2. Can i see actual code that reproduces issue with Nd4.sort please?

**Comment by atuzhykov** [comment]
1. to compare results of tensorflow and samediff random_shuffle op I use 
```
        if(modelName.startsWith("random_shuffle")){
            return (t, s) -> Nd4j.sort(t, true).equals(Nd4j.sort(s, true));
        }
```
and this returns me in CI log

```
[2020-05-16T14:47:37.160Z] TF: [      2,      4,      7,      9]
[2020-05-16T14:47:37.160Z] SD: [      2,      4,      9,      9]
[2020-05-16T14:47:37.160Z] o.n.i.T.TFGraphTestAllSameDiff - ERROR Executing test: random_shuffle/rank1_int32 - input keys []
[2020-05-16T14:47:37.160Z] java.lang.AssertionError: Predictions do not match on random_shuffle/rank1_int32, node RandomShuffle
```
2.  
```
@Test
    public void testSort(){
        INDArray arr = Nd4j.createFromArray(0.5, 0.4, 0.1, 0.2);
        INDArray expected = Nd4j.createFromArray(0.1, 0.2, 0.4, 0.5);
        INDArray sorted = Nd4j.sort(arr, true);
        System.out.println(sorted);
        assertEquals(expected, sorted);
    }
```
but looks for even on some CUDA devices test can pass
 cc @AlexDBlack

**Comment by raver119** [comment]
As far as I understand, it also passes with longer arrays? 

How about this test> https://github.com/KonduitAI/deeplearning4j/blob/69d91e272a5df21b763d80b5e11fe9f10d178fac/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/Nd4jTestsC.java#L5303-L5316


Also, what's your gpu model name on the system where your test fails?

**Comment by atuzhykov** [comment]
I see this bug only on CI, locally I have not gpu
Also Alex launched code for reproducing mentioned above on local gpu and test passed

**Comment by raver119** [comment]
Okay, great. So this means yes, longer test passes.

**Comment by raver119** [comment]
I have added bunch of tests, but they pass for me. Will see how they work on CI. But given the fact other sort tests pass, and there were no changes made recently - it might be something else.

**Comment by raver119** [comment]
So ye, these tests pass on CI, pass on cc 61 and 70. It can be anything, but not a sort op.

I'll close this issue, but please send me the code that reproduces this issue.
