### ISSUE TITLE
CXXABI_1.3.8 not found on Centos 7

### ISSUE THREAD

**Issue by hosuaby** [deeplearning4j/deeplearning4j#8984]
#### Issue Description

Looks like `libjnind4jcpu.so` requires a newer gcc (6.1.0+) and glibc (2.27+). While I can relativelly easy build a new gcc from source on Centos, making work a newer version of glibc is trickier. Until present, I failed to do so.

Do you have any suggestions to make run dl4j-beta7 on Centos 7 ?

#### Version Information
* Deeplearning4j version: dl4j-beta7
* Centos 7

#### Additional Information
Error stacktrace:

```
 Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660) ~[?:?]
 	at java.lang.Runtime.loadLibrary0(Runtime.java:829) ~[?:?]
 	at java.lang.System.loadLibrary(System.java:1867) ~[?:?]
 	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1631) ~[?:?]
 	at org.bytedeco.javacpp.Loader.load(Loader.java:1265) ~[?:?]
 	at org.bytedeco.javacpp.Loader.load(Loader.java:1109) ~[?:?]
 	at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:14) ~[?:?]
 	at java.lang.Class.forName0(Native Method) ~[?:?]
 	at java.lang.Class.forName(Class.java:398) ~[?:?]
 	at org.nd4j.common.config.ND4JClassLoading.loadClassByName(ND4JClassLoading.java:47) ~[?:?]
 	at org.nd4j.common.config.ND4JClassLoading.loadClassByName(ND4JClassLoading.java:41) ~[?:?]
 	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:88) ~[?:?]
 	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:37) ~[?:?]
 	... 29 more
 Caused by: java.lang.UnsatisfiedLinkError: /usr/share/elasticsearch/.javacpp/cache/libjnind4jcpu.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/share/elasticsearch/.javacpp/cache/libjnind4jcpu.so)
 	at java.lang.ClassLoader$NativeLibrary.load0(Native Method) ~[?:?]
 	at java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430) ~[?:?]
 	at java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487) ~[?:?]
 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684) ~[?:?]
 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617) ~[?:?]
 	at java.lang.Runtime.load0(Runtime.java:767) ~[?:?]
 	at java.lang.System.load(System.java:1831) ~[?:?]
 	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1581) ~[?:?]
 	at org.bytedeco.javacpp.Loader.load(Loader.java:1265) ~[?:?]
 	at org.bytedeco.javacpp.Loader.load(Loader.java:1109) ~[?:?]
 	at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:14) ~[?:?]
 	at java.lang.Class.forName0(Native Method) ~[?:?]
 	at java.lang.Class.forName(Class.java:398) ~[?:?]
 	at org.nd4j.common.config.ND4JClassLoading.loadClassByName(ND4JClassLoading.java:47) ~[?:?]
 	at org.nd4j.common.config.ND4JClassLoading.loadClassByName(ND4JClassLoading.java:41) ~[?:?]
 	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:88) ~[?:?]
 	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:37) ~[?:?]
 	... 29 more

```

**Comment by saudet** [comment]
@sshepel Are you sure the release was built with CentOS 6?

**Comment by sshepel** [comment]
@saudet double checked and I can see that build were in centos6 container, hm...

**Comment by hosuaby** [comment]
I think I have an idea. I built ND4J (with libnd4j) on Ubuntu first and after deployed it on Centos 7. Maybe `libjnind4jcpu.so` was linked to newer libraries on my Ubuntu, so it's not longer able to work with older libraries on Centos 7 ?

**Comment by raver119** [comment]
So, you've built libnd4j/ND4j manually for your needs?

**Comment by hosuaby** [comment]
@raver119 to accurate, I am testing this PR: https://github.com/eclipse/deeplearning4j/pull/8972

**Comment by raver119** [comment]
So yes, in this case you just need to use docker with Centos 6, like we do. Maybe @sshepel can share Dockerfile or image with you?

**Comment by hosuaby** [comment]
@raver119 So I need make a build of ND4J on Centos ? I am right ?
Yes, if you have a convenient image to make that build easily, I am will be grateful.

**Comment by sshepel** [comment]
@hosuaby sure, you can use this one: `konduit/jenkins-agent:amd64-centos6`
Default user inside container is `jenkins`.

**Comment by hosuaby** [comment]
I confirm my hypothesis. `UnsatisfiedLinkError : CXXABI_1.3.8 not found`  was due to the fact that ND4J was built and linked on the operating system with newer `gcc` and `glibc` (Ubuntu 18.04) and later was launched on system with older libraries (Centos 7).

(This comment is useful in case of someone else will have a similar problem)

**Comment by raver119** [comment]
@hosuaby thanks
