### ISSUE TITLE
Failed to import keras seq2seq model to DL4J with Merge Vertex error

### ISSUE THREAD

**Issue by ryentsao** [deeplearning4j/deeplearning4j#9000]
Here I have a basic seq2seq model in Keras as follows:
![image](https://user-images.githubusercontent.com/17917327/84467048-7cb86380-acad-11ea-9caa-30efdf9bf80b.png)
The inference decoder requires 3 inputs(cell input and hidden states), where the cell input is a 3D tensor and the hidden states are two 2D matrices.
### Here's the thing
When I use DL4J to import the decoder to Java, I get Merge Vertex error. The exception information is as follows:
`org.deeplearning4j.nn.conf.inputs.InvalidInputTypeException: Invalid input: MergeVertex cannot merge activations of different types: first type = RNN, input type 2 = FF
	at org.deeplearning4j.nn.conf.graph.MergeVertex.getOutputType(MergeVertex.java:139)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.getLayerActivationTypes(ComputationGraphConfiguration.java:537)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.addPreProcessors(ComputationGraphConfiguration.java:450)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.build(ComputationGraphConfiguration.java:1202)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraphConfiguration(KerasModel.java:394)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:415)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:404)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:173)
	at com.didi.woqu.scheduling.util.Seq2SeqModel.loadModel(Seq2SeqModel.java:163)`

Then I trace down the source code, finding that when DL4J builds the computation graph, it will add a 'merge' vertex if a layer vertex has multiple inputs and maxVertexInputs() = 1. Here decoder LSTM layer satisfies this condition.
![image](https://user-images.githubusercontent.com/17917327/84467635-5398d280-acaf-11ea-93f2-f51e1827262c.png)

BUT in MergeVertex, all the inputs must be the same type, or it'll throw an InvalidInputTypeException. 
![image](https://user-images.githubusercontent.com/17917327/84468114-9d35ed00-acb0-11ea-9741-c14a9c3dab88.png)

### So my guess is that DL4J thinks LSTM has only one input, ignoring the initial hidden states. But in seq2seq, the hidden states should be inputs of the layer.

Is this a bug? Or how can I import the model successfully?

**Comment by LightCampy** [comment]
I noticed that there is a similar problem at https://github.com/eclipse/deeplearning4j/issues/4743. Perhaps we can refer to this issue to find more context about the bug (e.g. the cause of the bug) ? 
Or maybe this can help us find the faulty lines and we can also refer to the [fix](https://github.com/eclipse/deeplearning4j/commit/27a652ea36ece2c26cab8f4bb6768c0dc6272ac9) to repair it?

**Comment by JenniferPruitt** [comment]
I noticed that there is a similar problem at https://github.com/eclipse/deeplearning4j/issues/4743. Perhaps we can refer to [this issue](https://github.com/eclipse/deeplearning4j/issues/4743) to find more context about the bug.
