### ISSUE TITLE
Unable to use CUDA at version 1.0.0-beta7

### ISSUE THREAD

**Issue by aeiplatform** [deeplearning4j/deeplearning4j#9003]
#### Issue Description

After upgrading the deeplearning library, I'm not able to use CUDA backed.
Same result for versions 10.2 and 10.1.
I also tried to install the CUDA driver with cuDNN manually both 10.2 and 10.1 show the same result.
However, in the file system, the **jnind4jcuda.dll** file exists at the location you are looking for.

#### Version Information
**build.gradle.kts**
```
dependencies {
    implementation("org.bytedeco:cuda-platform-redist:10.2-7.6-1.5.3")
    implementation("org.deeplearning4j:deeplearning4j-core:1.0.0-beta7")
    implementation("org.deeplearning4j:deeplearning4j-cuda-10.2:1.0.0-beta7")
    implementation("org.deeplearning4j:deeplearning4j-ui-model:1.0.0-beta7")
    implementation("org.deeplearning4j:deeplearning4j-zoo:1.0.0-beta7")
    implementation("org.nd4j:nd4j-cuda-10.2-platform:1.0.0-beta7")
}
```

#### Additional Information

```
Caused by: java.lang.ExceptionInInitializerError: null
	at org.nd4j.jita.concurrency.CudaAffinityManager.getNumberOfDevices(CudaAffinityManager.java:132) ~[nd4j-cuda-10.2-1.0.0-beta7.jar:na]
	at org.nd4j.jita.constant.ConstantProtector.purgeProtector(ConstantProtector.java:56) ~[nd4j-cuda-10.2-1.0.0-beta7.jar:na]
	at org.nd4j.jita.constant.ConstantProtector.<init>(ConstantProtector.java:49) ~[nd4j-cuda-10.2-1.0.0-beta7.jar:na]
	at org.nd4j.jita.constant.ConstantProtector.<clinit>(ConstantProtector.java:37) ~[nd4j-cuda-10.2-1.0.0-beta7.jar:na]
	at org.nd4j.jita.constant.ProtectedCudaConstantHandler.<clinit>(ProtectedCudaConstantHandler.java:65) ~[nd4j-cuda-10.2-1.0.0-beta7.jar:na]
	at org.nd4j.jita.constant.CudaConstantHandler.<clinit>(CudaConstantHandler.java:34) ~[nd4j-cuda-10.2-1.0.0-beta7.jar:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:315) ~[na:na]
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5151) ~[nd4j-api-1.0.0-beta7.jar:1.0.0-beta7]
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5092) ~[nd4j-api-1.0.0-beta7.jar:1.0.0-beta7]
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:270) ~[nd4j-api-1.0.0-beta7.jar:1.0.0-beta7]
	at org.datavec.image.loader.NativeImageLoader.transformImage(NativeImageLoader.java:671) ~[datavec-data-image-1.0.0-beta7.jar:na]
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:594) ~[datavec-data-image-1.0.0-beta7.jar:na]
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:282) ~[datavec-data-image-1.0.0-beta7.jar:na]
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:257) ~[datavec-data-image-1.0.0-beta7.jar:na]
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:251) ~[datavec-data-image-1.0.0-beta7.jar:na]
	at org.datavec.image.recordreader.BaseImageRecordReader.next(BaseImageRecordReader.java:248) ~[datavec-data-image-1.0.0-beta7.jar:na]
	at org.datavec.image.recordreader.BaseImageRecordReader.nextRecord(BaseImageRecordReader.java:512) ~[datavec-data-image-1.0.0-beta7.jar:na]
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.initializeUnderlying(RecordReaderDataSetIterator.java:226) ~[deeplearning4j-datavec-iterators-1.0.0-beta7.jar:na]
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.resetSupported(RecordReaderDataSetIterator.java:414) ~[deeplearning4j-datavec-iterators-1.0.0-beta7.jar:na]
	at org.deeplearning4j.datasets.iterator.DataSetIteratorSplitter.<init>(DataSetIteratorSplitter.java:99) ~[deeplearning4j-utility-iterators-1.0.0-beta7.jar:na]
	...
	...
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172) ~[spring-beans-5.1.15.RELEASE.jar:5.1.15.RELEASE]
	... 98 common frames omitted
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: https://deeplearning4j.konduit.ai/nd4j/backend
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:112) ~[nd4j-native-api-1.0.0-beta7.jar:na]
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:35) ~[nd4j-native-api-1.0.0-beta7.jar:na]
	... 126 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcuda in java.library.path: [...]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660) ~[na:na]
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829) ~[na:na]
	at java.base/java.lang.System.loadLibrary(System.java:1870) ~[na:na]
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1631) ~[javacpp-1.5.3.jar:1.5.3]
	at org.bytedeco.javacpp.Loader.load(Loader.java:1265) ~[javacpp-1.5.3.jar:1.5.3]
	at org.bytedeco.javacpp.Loader.load(Loader.java:1109) ~[javacpp-1.5.3.jar:1.5.3]
	at org.nd4j.nativeblas.Nd4jCuda.<clinit>(Nd4jCuda.java:10) ~[nd4j-cuda-10.2-1.0.0-beta7.jar:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:315) ~[na:na]
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:85) ~[nd4j-native-api-1.0.0-beta7.jar:na]
	... 127 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: ...\.javacpp\cache\nd4j-cuda-10.2-1.0.0-beta7-windows-x86_64.jar\org\nd4j\nativeblas\windows-x86_64\jnind4jcuda.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method) ~[na:na]
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430) ~[na:na]
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487) ~[na:na]
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684) ~[na:na]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617) ~[na:na]
	at java.base/java.lang.Runtime.load0(Runtime.java:767) ~[na:na]
	at java.base/java.lang.System.load(System.java:1834) ~[na:na]
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1581) ~[javacpp-1.5.3.jar:1.5.3]
	... 133 common frames omitted
```

**Comment by saudet** [comment]
Make sure you're using the right version of cuDNN:
https://deeplearning4j.konduit.ai/config/backends/config-cudnn

**Comment by aeiplatform** [comment]
I'm sure I installed the correct version.

Besides: 

> cuDNN comes bundled with the "redist" package

**Comment by saudet** [comment]
Right, ok, so there's something else missing. Could you check what Dependencies says?
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by agibsonccc** [comment]
Closing due to inactivity
