### ISSUE TITLE
Can I inference in the file-mapped workspace?

### ISSUE THREAD

**Issue by qq12cvhj** [deeplearning4j/deeplearning4j#9008]
I'm trying to get output from a computationgraph model,however when input datas to the model,there's not too much memory to allocate for computing.So I set a file-mapped workspace.
However I encounter this problem:
`org.nd4j.linalg.workspace.ND4JWorkspaceException: Expected no workspace active before call to outputOfLayersDetached - Open/active workspaces: [FILE-MAPPED]
        at org.nd4j.linalg.workspace.WorkspaceUtils.assertNoWorkspacesOpen(WorkspaceUtils.java:70)
        at org.nd4j.linalg.workspace.WorkspaceUtils.assertNoWorkspacesOpen(WorkspaceUtils.java:47)
        at org.deeplearning4j.nn.graph.ComputationGraph.outputOfLayersDetached(ComputationGraph.java:2228)
        at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1793)
        at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1775)
        at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1761)
        at org.deeplearning4j.nn.graph.ComputationGraph.outputSingle(ComputationGraph.java:1639)`

Note that I'm working on the android platform.The code is like below:
`WorkspaceConfiguration mmap = WorkspaceConfiguration.builder()
                    .initialSize(1073741824) //1GB
                    .policyLocation(LocationPolicy.MMAP)
                    .build();`
`try(MemoryWorkspace ws = Nd4j.getWorkspaceManager().getAndActivateWorkspace(mmap, "FILE-MAPPED"){
            outputTensor1 = computationGraph1.outputSingle(stft_mag);
            outputTensor2 = computationGraph2.outputSingle(stft_mag);
 }`.
And  I wonder if there is anyway else to do   inferring work on low memory devices like Android?For there's a limitation about heap for every app.

**Comment by raver119** [comment]
That's not a bug and not a problem. That's intentional validation.

**Comment by qq12cvhj** [comment]
@raver119  So there is nothing wrong.But now it is not able to do such works at this mode of workspace,yes? Thanks.
