### ISSUE TITLE
Not able to import unet based model

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/deeplearning4j#9014]
Model DM'd in slack channel.
Errors out in beta7 based on a serialization bug. Should be fixed in snapshots but gives this instead:

```
11:24:34.710 [main] INFO  org.nd4j.versioncheck.VersionCheck - org.nd4j : protobuf : 1.0.0-SNAPSHOT
Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.nd4j.nativeblas.Nd4jCpu$sqrtm
Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.nd4j.nativeblas.Nd4jCpu$argamin
Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.nd4j.nativeblas.Nd4jCpu$argamax
Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.nd4j.nativeblas.Nd4jCpu$clipbyavgnorm_bp
Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.nd4j.nativeblas.Nd4jCpu$ConstantOffsetsBuffer
Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.nd4j.nativeblas.Nd4jCpu$ConstantShapeBuffer
11:24:37.073 [main] INFO  org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for linear algebra: 1
11:24:37.077 [main] WARN  o.n.l.c.nativecpu.CpuNDArrayFactory - *********************************** CPU Feature Check Warning ***********************************
11:24:37.077 [main] WARN  o.n.l.c.nativecpu.CpuNDArrayFactory - Warning: Initializing ND4J with Generic x86 binary on a CPU with AVX/AVX2 support
11:24:37.077 [main] WARN  o.n.l.c.nativecpu.CpuNDArrayFactory - Using ND4J with AVX/AVX2 will improve performance. See deeplearning4j.org/cpu for more details
11:24:37.077 [main] WARN  o.n.l.c.nativecpu.CpuNDArrayFactory - Or set environment variable ND4J_IGNORE_AVX=true to suppress this warning
11:24:37.077 [main] WARN  o.n.l.c.nativecpu.CpuNDArrayFactory - *************************************************************************************************
11:24:37.169 [main] INFO  org.nd4j.nativeblas.Nd4jBlas - Number of threads used for OpenMP BLAS: 4
11:24:37.256 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Mac OS X]
11:24:37.256 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Cores: [4]; Memory: [3.6GB];
11:24:37.256 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
Exception in thread "main" java.lang.NoSuchMethodError: org.nd4j.nativeblas.NativeOps.shapeBuffer(ILorg/bytedeco/javacpp/LongPointer;Lorg/bytedeco/javacpp/LongPointer;ICJZ)Lorg/nd4j/nativeblas/OpaqueConstantDataBuffer;
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.createShapeInfo(NativeOpExecutioner.java:2021)
	at org.nd4j.linalg.api.shape.Shape.createShapeInformation(Shape.java:3249)
	at org.nd4j.linalg.api.ndarray.BaseShapeInfoProvider.createShapeInformation(BaseShapeInfoProvider.java:67)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:206)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:201)
	at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:99)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:430)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4065)
	at org.nd4j.linalg.factory.Nd4j.createArrayFromShapeBuffer(Nd4j.java:2541)
	at org.nd4j.linalg.factory.Nd4j.read(Nd4j.java:2593)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraphHelper(ModelSerializer.java:507)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:463)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:648)
	at org.deeplearning4j.nn.graph.ComputationGraph.load(ComputationGraph.java:4559)
	at ai.konduit.metertraining.keypoint.RunKeypointEval.main(RunKeypointEval.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by eraly** [comment]
Paul says possibly out of sync snapshots and try a local build. Will build on the 2080 box later and try.
