### ISSUE TITLE
weightedCrossEntropyWithLogits doesn't accept null weights

### ISSUE THREAD

**Issue by rnett** [deeplearning4j/deeplearning4j#9015]
From its javadoc:
`@param weights eights array. May be null. If null, a weight of 1.0 is used (NUMERIC type)`

However, passing null causes:
```java
org.nd4j.linalg.exception.ND4JIllegalStateException: Found null variable at index 2

	at org.nd4j.autodiff.samediff.SameDiff.addArgsFor(SameDiff.java:1124)
	at org.nd4j.autodiff.functions.DifferentialFunction.<init>(DifferentialFunction.java:455)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.<init>(DynamicCustomOp.java:178)
	at org.nd4j.linalg.api.ops.impl.loss.WeightedCrossEntropyLoss.<init>(WeightedCrossEntropyLoss.java:44)
	at org.nd4j.autodiff.samediff.ops.SDLoss.weightedCrossEntropyWithLogits(SDLoss.java:1035)
```

**Comment by agibsonccc** [comment]
Closing — this issue is over 5 years old with no recent activity. The codebase has been significantly rewritten. If this is still relevant, please open a new issue.
