### ISSUE TITLE
Errors occur when training word2vec on spark

### ISSUE THREAD

**Issue by WindQAQ** [deeplearning4j/deeplearning4j#9038]
#### Issue Description

Hi,

I'm using org.deeplearning4j.spark.models.embeddings.word2vec.Word2Vec to train word2vec, and the following errors occur

> Exception in thread "main" java.lang.IllegalStateException: Cannot perform in-place operation "addi": result array shape does not match the broadcast operation output shape: [200].addi([1, 200]) != [200].
In-place operations like x.addi(y) can only be performed when x and y have the same shape, or x and y are broadcastable with x.shape() == broadcastShape(x,y)
	at org.nd4j.linalg.api.shape.Shape.assertBroadcastable(Shape.java:283)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:3251)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.addi(BaseNDArray.java:3245)
	at org.deeplearning4j.spark.models.embeddings.word2vec.Word2Vec.train(Word2Vec.java:222)
	at dl4jword2vec.Fun.main(Fun.java:24)

Here is my testing program http://codepad.org/0ZZvNFZI, and the POM.xml is here http://codepad.org/xDuX20l7. I'm not sure if I do anything wrong. The training file "/tmp/test" is just 100 lines of "a b c d e f g h I j k".

Thank you all in advance.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0beta7
* Platform information (OS, etc): macOS Catalina 10.15.4
* CUDA version, if used: none
* NVIDIA driver version, if in use: none

#### Contributing

Of course, more guideline on how to run unit tests would be really appreciated.

**Comment by agibsonccc** [comment]
Closing — this issue references architecture (old UI, M1/M2.1 release, Spark, TF import, ParallelWrapper training, or legacy subsystem) that has been fundamentally rewritten in the upcoming release. If you still experience a similar issue with the new version, please open a new issue with reproduction steps.
