### ISSUE TITLE
LocalTransformExecutor.executeJoin returns list.size() = 0

### ISSUE THREAD

**Issue by cagneymoreau** [deeplearning4j/deeplearning4j#9042]
#### Issue Description
trying to combine two csv files of 17 and 27 columns. Both around 1260 rows
I have successfully done this with other csv files.

Maybe to many columns?
Any thoughts appreciated.

Attempting to use;
```

        Join join = new Join.Builder(Join.JoinType.Inner)
                .setJoinColumns("year", "month", "day")
                .setSchemas(techSchema, mixSchema)
                .build();

 List<List<Writable>> processedData = LocalTransformExecutor.executeJoin(join,techPrep, mixPrep);
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* Platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

```
13:57:44.338 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
13:57:44.338 [main] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
13:57:44.338 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
13:57:44.338 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
13:57:44.353 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: Windows
13:57:44.353 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
13:57:44.353 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 9
13:57:44.353 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
13:57:44.353 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
13:57:44.353 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
13:57:44.353 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:224)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:218)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.util.ResourceLeakDetector.<init>(ResourceLeakDetector.java:162)
	at io.netty.util.ResourceLeakDetector.<init>(ResourceLeakDetector.java:207)
	at io.netty.util.ResourceLeakDetectorFactory$DefaultResourceLeakDetectorFactory.newResourceLeakDetector(ResourceLeakDetectorFactory.java:201)
	at io.netty.util.ResourceLeakDetectorFactory.newResourceLeakDetector(ResourceLeakDetectorFactory.java:65)
	at io.netty.buffer.AbstractByteBuf.<clinit>(AbstractByteBuf.java:57)
	at org.apache.arrow.memory.BaseAllocator.createEmpty(BaseAllocator.java:250)
	at org.apache.arrow.memory.BaseAllocator.<init>(BaseAllocator.java:83)
	at org.apache.arrow.memory.RootAllocator.<init>(RootAllocator.java:34)
	at org.apache.arrow.memory.RootAllocator.<init>(RootAllocator.java:30)
	at org.datavec.local.transforms.LocalTransformExecutor.<clinit>(LocalTransformExecutor.java:70)
	at DataManager.FormattedDataRequester.createFullDataSet(FormattedDataRequester.java:725)
	at DataManager.FormattedDataRequester.fullSingleIterator(FormattedDataRequester.java:1123)
	at sample.Experiment.trainandTestFullSingle(Experiment.java:298)
	at sample.Experiment.init(Experiment.java:46)
	at sample.Experiment.main(Experiment.java:31)
13:57:44.353 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: unavailable true
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$5.run(PlatformDependent0.java:273)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:266)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.util.ResourceLeakDetector.<init>(ResourceLeakDetector.java:162)
	at io.netty.util.ResourceLeakDetector.<init>(ResourceLeakDetector.java:207)
	at io.netty.util.ResourceLeakDetectorFactory$DefaultResourceLeakDetectorFactory.newResourceLeakDetector(ResourceLeakDetectorFactory.java:201)
	at io.netty.util.ResourceLeakDetectorFactory.newResourceLeakDetector(ResourceLeakDetectorFactory.java:65)
	at io.netty.buffer.AbstractByteBuf.<clinit>(AbstractByteBuf.java:57)
	at org.apache.arrow.memory.BaseAllocator.createEmpty(BaseAllocator.java:250)
	at org.apache.arrow.memory.BaseAllocator.<init>(BaseAllocator.java:83)
	at org.apache.arrow.memory.RootAllocator.<init>(RootAllocator.java:34)
	at org.apache.arrow.memory.RootAllocator.<init>(RootAllocator.java:30)
	at org.datavec.local.transforms.LocalTransformExecutor.<clinit>(LocalTransformExecutor.java:70)
	at DataManager.FormattedDataRequester.createFullDataSet(FormattedDataRequester.java:725)
	at DataManager.FormattedDataRequester.fullSingleIterator(FormattedDataRequester.java:1123)
	at sample.Experiment.trainandTestFullSingle(Experiment.java:298)
	at sample.Experiment.init(Experiment.java:46)
	at sample.Experiment.main(Experiment.java:31)
13:57:44.353 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @3a3e4aff
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:315)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:306)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.util.ResourceLeakDetector.<init>(ResourceLeakDetector.java:162)
	at io.netty.util.ResourceLeakDetector.<init>(ResourceLeakDetector.java:207)
	at io.netty.util.ResourceLeakDetectorFactory$DefaultResourceLeakDetectorFactory.newResourceLeakDetector(ResourceLeakDetectorFactory.java:201)
	at io.netty.util.ResourceLeakDetectorFactory.newResourceLeakDetector(ResourceLeakDetectorFactory.java:65)
	at io.netty.buffer.AbstractByteBuf.<clinit>(AbstractByteBuf.java:57)
	at org.apache.arrow.memory.BaseAllocator.createEmpty(BaseAllocator.java:250)
	at org.apache.arrow.memory.BaseAllocator.<init>(BaseAllocator.java:83)
	at org.apache.arrow.memory.RootAllocator.<init>(RootAllocator.java:34)
	at org.apache.arrow.memory.RootAllocator.<init>(RootAllocator.java:30)
	at org.datavec.local.transforms.LocalTransformExecutor.<clinit>(LocalTransformExecutor.java:70)
	at DataManager.FormattedDataRequester.createFullDataSet(FormattedDataRequester.java:725)
	at DataManager.FormattedDataRequester.fullSingleIterator(FormattedDataRequester.java:1123)
	at sample.Experiment.trainandTestFullSingle(Experiment.java:298)
	at sample.Experiment.init(Experiment.java:46)
	at sample.Experiment.main(Experiment.java:31)
13:57:44.353 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
13:57:44.353 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
13:57:44.377 [main] DEBUG io.netty.util.internal.PlatformDependent - maxDirectMemory: 8577351680 bytes (maybe)
13:57:44.377 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\Cagney\AppData\Local\Temp (java.io.tmpdir)
13:57:44.378 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
13:57:44.378 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
13:57:44.378 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
13:57:44.378 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
13:57:44.379 [main] DEBUG io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
13:57:44.379 [main] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@20a8a64e
13:57:44.401 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 24
13:57:44.401 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 24
13:57:44.401 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
13:57:44.401 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
13:57:44.401 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
13:57:44.401 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
13:57:44.402 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
13:57:44.402 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
13:57:44.402 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
13:57:44.402 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
13:57:44.402 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
13:57:44.404 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
13:57:44.404 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
13:57:44.493 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
13:57:44.493 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
13:57:44.493 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
13:57:44.493 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
```

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by agibsonccc** [comment]
This isn't a dl4j issue. It appears to be related specifically to netty:
https://github.com/netty/netty/issues/7817
Google search this specific part:
```
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
```

and see what you come back with. This issue really isn't specific to dl4j. It involves mainly the netty library.

**Comment by cagneymoreau** [comment]
Its unfortunate that this issue is with netty. Instead of researching the issue more(due to lack of time) I assumed It would be faster to write a simple class that accomplishes my goal. Ill paste it below in case it saves someone else some typing in the future.

```

/** This class will allow you to merge two csv files. 
 * Each row needs a key (or multiple keys) and the imputation method is deletion
 * It places one of the files to the left of the rows and one to the right
 * 
 * Use at your own risk. Not well tested
 */

public class MergeCSV {

    private int[] leftcompareColumns;
    private int[] rightcompareColumns;
    private boolean deleteComapreColumns;

    private ArrayList<Row> leftRows;
    private ArrayList<Row> rightRows;


    private StringBuilder issues = new StringBuilder();

    public MergeCSV(int[] leftcompareColumns, int[] rightcompareColumns, boolean deleteCompareColumns )
    {
        this.leftcompareColumns = leftcompareColumns;
        this.rightcompareColumns = rightcompareColumns;
        this.deleteComapreColumns = deleteCompareColumns;
    }


    public ArrayList<String> mergeFile(ArrayList<String> lRows, ArrayList<String> rRows)
    {
        leftRows = (ArrayList<Row>) buildCollection(lRows, leftcompareColumns);
        rightRows = (ArrayList<Row>) buildCollection(rRows, rightcompareColumns);

        appendData();

        return rebuildCSV();


    }

    //build row objects
    private ArrayList<Row> buildCollection(ArrayList<String> rows, int[] keyPos)
    {
        ArrayList<Row> rowList = new ArrayList<>();

        for (int i = 0; i < rows.size(); i++) {

            String[] parts = rows.get(i).split(",");
            String[] key = new String[keyPos.length];

            for (int j = 0; j < key.length; j++) {
                key[j] = parts[keyPos[j]];
            }

            String[] body = new String[parts.length- keyPos.length];

            int count = 0;
            for (int j = 0; j < parts.length; j++) {
                boolean add = true;
                for (int k = 0; k < keyPos.length; k++) {
                    if (keyPos[k] == j) add = false;
                }

                if (add){
                    body[count] = parts[j];
                    count++;
                }
            }

            Row r = new Row(key, body);
            rowList.add(r);
        }

        return rowList;
    }

    //push all matching data into the left holder
    private void appendData()
    {
        for (int i = 0; i < leftRows.size(); i++) {

            for (int j = 0; j < rightRows.size(); j++) {
                leftRows.get(i).checkRightData(rightRows.get(j));
            }


        }
    }

    //write all rows that have been appended to a list of strings
    private ArrayList<String> rebuildCSV()
    {
        ArrayList<String> out = new ArrayList<>();

        for (int i = 0; i < leftRows.size(); i++) {
            if (leftRows.get(i).isSet()){
                out.add(leftRows.get(i).getDataFinal(deleteComapreColumns));
            }
        }

        return out;
    }



    private class Row{

        private boolean appended;

        private String[] key;

        private String[] data;

        private String[] rightData;


        public Row(String[] key, String[] data)
        {
            this.key = key;
            this.data = data;
        }

        public void checkRightData(Row oppRow){
            if (compare(oppRow)) {

                if (rightData != null){
                    issues.append("Double ADDED ROW!");
                }
                this.rightData = oppRow.getData();
                appended = true;
            }

        }



        public boolean compare(Row row){
            boolean match = true;
            String[] oppKey = row.getKey();

            if (oppKey.length != key.length){
                match = false;
                return match;
            }

            for (int i = 0; i < key.length; i++) {
                if (!oppKey[i].equals(key[i].substring(0, key[i].length()-2))){
                    match = false;
                    return match;
                }

            }
            return match;
        }

        public String[] getKey()
        {
            return key;
        }

        public String[] getData()
        {
            return data;
        }

        public boolean isSet()
        {
            return appended;
        }

        public String getDataFinal(boolean deleteCompare)
        {
            StringBuilder sb = new StringBuilder();

            if (!deleteCompare){
                for (int i = 0; i < key.length; i++) {
                    sb.append(key[i]).append(",");
                }
            }

            for (int i = 0; i < data.length; i++) {
                sb.append(data[i]).append(",");
            }

            for (int i = 0; i < rightData.length; i++) {
                sb.append(rightData[i]).append(",");
            }

            sb.setLength(sb.length()-1);
            return sb.toString();
        }

    }


}


```
