### ISSUE TITLE
LocallyConnected2D hashCode() NullPointerException

### ISSUE THREAD

**Issue by jljljl** [deeplearning4j/deeplearning4j#9049]
Method "hashCode()" implemented in wrong way for LocallyConnected2D class (and probably for some other classes too).
`new LinkedHashSet<>().add(new LocallyConnected2D.Builder().build());`
will cause
```
java.lang.NullPointerException
	at org.deeplearning4j.nn.conf.layers.LocallyConnected2D.defineParameters(LocallyConnected2D.java:151)
	at org.deeplearning4j.nn.conf.layers.samediff.AbstractSameDiffLayer.getLayerParams(AbstractSameDiffLayer.java:103)
	at org.deeplearning4j.nn.conf.layers.samediff.AbstractSameDiffLayer.hashCode(AbstractSameDiffLayer.java:52)
	at org.deeplearning4j.nn.conf.layers.samediff.SameDiffLayer.hashCode(SameDiffLayer.java:56)
	at org.deeplearning4j.nn.conf.layers.LocallyConnected2D.hashCode(LocallyConnected2D.java:51)
```
Methods hashCode() should never be overriden due to possible failures like that. But you can also implement
```
	@Override
	public int hashCode()
	{
		try
		{
			//Your code here
		}
		catch (Exception e)
		{
			return super.hashCode();
		}
	}
```

**Comment by agibsonccc** [comment]
This isn't relevant anymore. Closing this.
