### ISSUE TITLE
Op Profiler causes nullpointer exception when enabled with cuda backend

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#9068]
#### Issue Description
Example stack trace:
```
Exception in thread "main" java.lang.NullPointerException
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.address(BaseCudaDataBuffer.java:612)
	at org.nd4j.linalg.profiler.OpProfiler.processOpCall(OpProfiler.java:250)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.profilingConfigurableHookIn(DefaultOpExecutioner.java:497)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:1541)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:1526)
	at org.nd4j.linalg.factory.Nd4j.randn(Nd4j.java:3054)
	at org.nd4j.linalg.factory.Nd4j.randn(Nd4j.java:3137)
	at org.nd4j.weightinit.impl.XavierInitScheme.doCreate(XavierInitScheme.java:47)
	at org.nd4j.weightinit.BaseWeightInitScheme.create(BaseWeightInitScheme.java:58)
	at org.nd4j.autodiff.samediff.SameDiff.var(SameDiff.java:2776)
	at org.nd4j.autodiff.samediff.SameDiff.var(SameDiff.java:2732)
```

The host pointer on the data buffer appears to be null.

Note this happens when the profiler has the following that are true:
```
        if (OpProfiler.getInstance().getConfig().isStackTrace() ||
            OpProfiler.getInstance().getConfig().isCheckElapsedTime()) {
            OpProfiler.getInstance().processOpCall(op);
        }
```

#### Version Information
1.0.0-beta7
Please indicate relevant versions, including, if relevant:

* Deeplearning4j version master
* Platform information (OS, etc) windows
* CUDA version, if used 10.2
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by agibsonccc** [comment]
Closing — this issue is over 2 years old with no recent activity or reproduction steps. The underlying code has been significantly rewritten. If you still experience this issue with a recent version, please open a new issue.
