### ISSUE TITLE
Unable to deserialize model on CentOS: restoreMultiLayerNetwork -> NullPointerException

### ISSUE THREAD

**Issue by fasahath** [deeplearning4j/deeplearning4j#9081]
#### Issue Description
Unable to deserialize model on a CentOS release 6.8 (Final)

#### Expected behavior
Deserialization works on my local Mac 
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101 
Kernel: 19.5.0

#### Encountered behavior
*Deserialization fails on linux server*
CentOS release 6.8 (Final)
Kernel: 2.6.32-642.6.2.el6.x86_64

#### Version Information
* Deeplearning4j version
**1.0.0-beta7**
* platform information (OS, etc)
**CentOS release 6.8 (Final)**
* CUDA version, if used
No
* NVIDIA driver version, if in use
No

#### Additional Information
```
java.lang.NullPointerException
 394         at org.nd4j.linalg.factory.Nd4j.createBufferDetachedImpl(Nd4j.java:1336)
 395         at org.nd4j.linalg.factory.Nd4j.createBufferDetached(Nd4j.java:1318)
 396         at org.nd4j.linalg.factory.Nd4j.read(Nd4j.java:2575)
 397         at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetworkHelper(ModelSerializer.java:283)
 398         at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:238)
 399         at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:368)
```

**Comment by agibsonccc** [comment]
I'm guessing this is libc related potentially? I think we only support centos 7 in our binaries. @saudet ?

**Comment by saudet** [comment]
CentOS 6, that's not a link error.

**Comment by agibsonccc** [comment]
Ok @fasahath can you provide the model so we can reproduce this? Thanks @saudet

**Comment by fasahath** [comment]
I have sent you the model over email.
Sorry for the delay.

**Comment by fasahath** [comment]
Here is the full [stack trace](https://gist.github.com/fasahath/8003894cb1609019167d8a18e494bb62)
You can download the model file from [here](https://drive.google.com/file/d/1BJixwOlPRu-9cmD34d-UG6Wu7QT-0Ssv/view?usp=sharing)

**Comment by quickwritereader** [comment]
I just tested beta7 in centos6.8, it loaded the model 
```
        MultiLayerNetwork net2;
        try {
            net2 = MultiLayerNetwork.load(new File("lstm_model_rnd_09042020.ipdl4j"), true);
            var x = net2.getLayers();
            for(var h : x){
               System.out.println("-----" +h);
            }
        } catch (IOException e) { 
            e.printStackTrace();
        }
```

**Comment by quickwritereader** [comment]
I faced glibc 2.14 problem for snapshots, though.

**Comment by agibsonccc** [comment]
Closing — this issue references architecture (old UI, M1/M2.1 release, Spark, TF import, ParallelWrapper training, or legacy subsystem) that has been fundamentally rewritten in the upcoming release. If you still experience a similar issue with the new version, please open a new issue with reproduction steps.
