### ISSUE TITLE
Cannot calculate gradients/score: labels are null

### ISSUE THREAD

**Issue by androuino** [deeplearning4j/deeplearning4j#9096]
#### Issue Description

I was trying to run the **RedBloodCellDetection.java** and got this error on my console:

```
Exception in thread "main" java.lang.IllegalStateException: Cannot calculate gradients/score: labels are null

	at org.nd4j.common.base.Preconditions.throwStateEx(Preconditions.java:641)
	at org.nd4j.common.base.Preconditions.checkState(Preconditions.java:268)
	at org.deeplearning4j.nn.layers.objdetect.Yolo2OutputLayer.computeBackpropGradientAndScore(Yolo2OutputLayer.java:109)
	at org.deeplearning4j.nn.layers.objdetect.Yolo2OutputLayer.backpropGradient(Yolo2OutputLayer.java:102)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doBackward(LayerVertex.java:149)
	at org.deeplearning4j.nn.graph.ComputationGraph.calcBackpropGradients(ComputationGraph.java:2713)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1382)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1342)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:170)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1166)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1116)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1103)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:985)
```

* Deeplearning4j version
From master's latest commit
* Platform information (OS, etc)
macOS Catalina 10.15.6
* CUDA version, if used
CPU only
* NVIDIA driver version, if in use
CPU only

**Comment by agibsonccc** [comment]
@androuino sorry still getting through issue backlog. So you're running that example after building from source? I believe @saudet had worked on that example.
Edit: Looking through it, I think we removed that example from: https://github.com/eclipse/deeplearning4j-examples @treo had done a pass getting rid of old examples.

**Comment by androuino** [comment]
hi @agibsonccc, so the object detection example right now has been removed and became not compatible with the new version of the framework?

**Comment by saudet** [comment]
That example was just never added actually. The code probably needs to be updated to run on newer version, yes.

**Comment by agibsonccc** [comment]
@androuino you can use this one: https://github.com/eclipse/deeplearning4j-examples/blob/9e971fdb782249873786a960f248247dd28650fa/dl4j-examples/src/main/java/org/deeplearning4j/examples/advanced/modelling/objectdetection/TinyYoloHouseNumberDetection.java Always try to search the examples for what's current there.

**Comment by androuino** [comment]
Thanks for the support, I will try the above links.
