### ISSUE TITLE
CuDNN cudaMalloc failed

### ISSUE THREAD

**Issue by Hendekagon** [deeplearning4j/deeplearning4j#9119]
#### CuDNN cudaMalloc failed in `ComputationGraph.fit`
```
WARN  org.deeplearning4j.nn.layers.convolution.ConvolutionLayer: CuDNN execution failed - falling back on built-in implementation
java.lang.RuntimeException: cudaMalloc failed; Bytes: [1077940224]; Error code [2]; DEVICE [0]
	at org.nd4j.jita.memory.CudaMemoryManager.allocate(CudaMemoryManager.java:79)
	at org.nd4j.jita.workspace.CudaWorkspace.alloc(CudaWorkspace.java:222)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:421)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:72)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.create(CudaDataBufferFactory.java:415)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1466)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:1524)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:1519)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4298)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3986)
	at org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper.getCudnnForwardArgs(CudnnConvolutionHelper.java:684)
	at org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper.backpropGradient(CudnnConvolutionHelper.java:167)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.backpropGradient(ConvolutionLayer.java:186)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doBackward(LayerVertex.java:149)
	at org.deeplearning4j.nn.graph.ComputationGraph.calcBackpropGradients(ComputationGraph.java:2713)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1382)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1342)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:170)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1166)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1116)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1083)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1019)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1007)
```

* deeplearning4j-cuda-10.2
* nd4j-cuda-10.2
* Ubuntu 18.04
* cuda-10.2
* NVRM version: NVIDIA UNIX x86_64 Kernel Module  440.33.01

I've verified the cuda installation and the cuDNN installation by compiling & running examples and confirming their success.

**Comment by agibsonccc** [comment]
@Hendekagon  could you tell us a bit about the workload size?  You may have to specify higher limits: https://deeplearning4j.konduit.ai/config/config-memory 
Did you try tuning the batch sizes for your workload?

**Comment by Hendekagon** [comment]
thank you! double-checking my off-heap settings plus dropping the batch size for the size of input fixed it
