### ISSUE TITLE
I have error cudaGetSymbolAddress(...) failed; Error code: [13] with any samples with CUDA, how I can resolve it?

### ISSUE THREAD

**Issue by RkVladimir** [deeplearning4j/deeplearning4j#9123]
Good afternoon, I tried to install CUDA version 10, 10.1, 10.2, now 11.1 is installed, except for 10.0, versions in all examples with cuda I have an error similar to the one indicated in the listing below. I read in the forums that this is possible, when my version CC = 8.6 (GeForce3090) is not supported in the current DP4J implementation, how can this problem be solved?
Thanks!

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j 1.0.0-beta7
* Platform information Windows 10
* CUDA 11.1 cuDnn 8
* NVIDIA driver 457.09
VS 2019

OUTPUT:
Exception in thread "main" java.lang.RuntimeException: **cudaGetSymbolAddress(...) failed; Error code: [13]**
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.createShapeInfo(CudaExecutioner.java:2162)
	at org.nd4j.linalg.api.shape.Shape.createShapeInformation(Shape.java:3280)
	at org.nd4j.linalg.api.ndarray.BaseShapeInfoProvider.createShapeInformation(BaseShapeInfoProvider.java:74)
	at org.nd4j.jita.constant.ProtectedCudaShapeInfoProvider.createShapeInformation(ProtectedCudaShapeInfoProvider.java:92)
	at org.nd4j.jita.constant.ProtectedCudaShapeInfoProvider.createShapeInformation(ProtectedCudaShapeInfoProvider.java:73)
	at org.nd4j.linalg.jcublas.CachedShapeInfoProvider.createShapeInformation(CachedShapeInfoProvider.java:42)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:181)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:310)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:363)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:786)
	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:287)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:172)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4247)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritablesSequence(RecordReaderMultiDataSetIterator.java:612)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:369)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:327)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:213)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:365)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:344)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:48)
	at org.nd4j.linalg.dataset.api.preprocessor.AbstractDataSetNormalizer.fit(AbstractDataSetNormalizer.java:109)
	at cudlstm.main(cudlstm.java:50)

Process finished with exit code 1

**Comment by mouradski** [comment]
same, with RTX 3080, i tried cuda 10.0 and 10.2

**Comment by agibsonccc** [comment]
@RkVladimir  @mouradski  we'll be releasing a version with 11.0 in a bit, for now you can use snapshots and see if that works? https://deeplearning4j.konduit.ai/config/config-snapshots

**Comment by RkVladimir** [comment]
Cannot resolve org.nd4j:nd4j-cuda-11.0:1.0.0-SNAPSHOT - this error are present....
and
from
https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.nd4j&a=nd4j-cuda-11.0&v=1.0.0-SNAPSHOT&e=jar&c=windows-x86_64

404 - Not Found

Path /org/nd4j/nd4j-cuda-11.0/1.0.0-SNAPSHOT/nd4j-cuda-11.0-1.0.0-20201117.023522-181-windows-x86_64.jar not found in local storage of repository "Snapshots" [id=snapshots]

**Comment by RkVladimir** [comment]
I’m resolved it! Now my example working on GeForce3090!!!

Part of my POM:

    org.example
    dl4jCuda
    1.0-SNAPSHOT
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-cuda-11.0</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

Also you need build nd4j-cuda-11.0 from sources and add all *jar and dll files to your project!

**Comment by RkVladimir** [comment]
> 
> 
> @RkVladimir @mouradski we'll be releasing a version with 11.0 in a bit, for now you can use snapshots and see if that works? https://deeplearning4j.konduit.ai/config/config-snapshots

Thanks, its help me (partly)!

**Comment by mouradski** [comment]
> > @RkVladimir @mouradski we'll be releasing a version with 11.0 in a bit, for now you can use snapshots and see if that works? https://deeplearning4j.konduit.ai/config/config-snapshots
> 
> Thanks, its help me (partly)!

thanks bro :)

**Comment by mouradski** [comment]
I builded libnd4j with cuda (-c cuda -cc auto) support, then builded nd4j-cuda & deeplearning4j-cuda  (all on snapshot version) then I added thoses dependancies 

<dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-cuda-11.0</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </dependency>
    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-core</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </dependency>
 

I got this error :( 

`21:36:14.009 [main] WARN  org.nd4j.linalg.factory.Nd4jBackend - Skipped [JCublasBackend] backend (unavailable): java.lang.UnsatisfiedLinkError: C:\Users\mouradski\.javacpp\cache\cuda-11.0-8.0-1.5.4-windows-x86_64.jar\org\bytedeco\cuda\windows-x86_64\jnicublas.dll: La procédure spécifiée est introuvable`

**Comment by agibsonccc** [comment]
@mouradski  this looks to be a bad cuda install or something missed during compilation. Could you elaborate a bit on https://community.konduit.ai? I'm closing this issue.

**Comment by RkVladimir** [comment]
> I builded libnd4j with cuda (-c cuda -cc auto) support, then builded nd4j-cuda & deeplearning4j-cuda (all on snapshot version) then I added thoses dependancies
> org.deeplearning4j deeplearning4j-cuda-11.0 1.0.0-SNAPSHOT org.deeplearning4j deeplearning4j-core 1.0.0-SNAPSHOT
> 
> I got this error :(
> 
> `21:36:14.009 [main] WARN org.nd4j.linalg.factory.Nd4jBackend - Skipped [JCublasBackend] backend (unavailable): java.lang.UnsatisfiedLinkError: C:\Users\mouradski\.javacpp\cache\cuda-11.0-8.0-1.5.4-windows-x86_64.jar\org\bytedeco\cuda\windows-x86_64\jnicublas.dll: La procédure spécifiée est introuvable`

Here I posted the libraries
https://community.konduit.ai/t/cuda-error-during-run-the-example/946
