### ISSUE TITLE
Nullpointer Exception only with Cuda (not with CPU)

### ISSUE THREAD

**Issue by cyberbeat** [deeplearning4j/deeplearning4j#9148]
#### Issue Description

```
[pool-1-thread-4] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
[pool-1-thread-4] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for linear algebra: 32
[pool-1-thread-4] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Linux]
[pool-1-thread-4] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [2]; Memory: [2,8GB];
[pool-1-thread-4] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [CUBLAS]
[pool-1-thread-4] INFO org.nd4j.linalg.jcublas.JCublasBackend - ND4J CUDA build version: 10.0.130
[pool-1-thread-4] INFO org.nd4j.linalg.jcublas.JCublasBackend - CUDA device 0: [GeForce GTX 1060 6GB]; cc: [6.1]; Total memory: [6372196352]
[pool-1-thread-3] INFO org.deeplearning4j.nn.graph.ComputationGraph - Starting ComputationGraph with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
Exception in thread "AMDSI prefetch thread" java.lang.RuntimeException: java.lang.NullPointerException
        at org.nd4j.linalg.dataset.AsyncMultiDataSetIterator$AsyncPrefetchThread.run(AsyncMultiDataSetIterator.java:389)
Caused by: java.lang.NullPointerException
        at org.nd4j.jita.concurrency.CudaAffinityManager.ensureLocation(CudaAffinityManager.java:307)
        at org.nd4j.linalg.dataset.callbacks.DefaultCallback.call(DefaultCallback.java:65)
        at org.nd4j.linalg.dataset.AsyncMultiDataSetIterator$AsyncPrefetchThread.run(AsyncMultiDataSetIterator.java:364)

```

This is the ND4j Code where it happens:

```
@Override
public void ensureLocation(INDArray array, Location location) {
    // to location to ensure for empty array
    if (array.isEmpty() || array.isS()) // HERE THE NPE HAPPENS
        return;
    ...
```

#### Version Information

* Deeplearning4j version: 1 beta7
* Platform information (OS, etc): linux x86-64
* CUDA version, if used: 10
* NVIDIA driver version, if in use: 304.137

#### Additional Information

Using an LSTM, but based on Dagli, which relies on DL4j: https://github.com/linkedin/dagli/

I saw a similar issue here: https://community.konduit.ai/t/bertiterator-produces-npe-while-training-on-gpu/580

Should there be a null-handling on the array in your code?

**Comment by jljljl** [comment]
@agibsonccc please close it if it is correct

**Comment by agibsonccc** [comment]
@jljljl  the main issue was the way the commit was handled. The author didn't want to add the signed off by commit in their PR. The eclipse foundation has removed this policy so I was able to merge this.
