### ISSUE TITLE
 "Cannot do backward pass: all epsilons not set" when using frozen layer

### ISSUE THREAD

**Issue by HGuillemet** [deeplearning4j/deeplearning4j#9159]
I have a convolution layer that, when its output feeds a frozen deconvolution2D layer, triggers the following exception:
```
java.lang.IllegalStateException: Cannot do backward pass: all epsilons not set. Layer "fc" (idx 1876), numInputs :1; numOutputs: 1
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doBackward(LayerVertex.java:133)
	at org.deeplearning4j.nn.graph.ComputationGraph.calcBackpropGradients(ComputationGraph.java:2713)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1382)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1342)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:170)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:63)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1166)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1116)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1083)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1019)
```
Here is the creation of the frozen layer:
```
 graph.appendLayer("transpose",
                    new FrozenLayer(
                    new Deconvolution2D.Builder(new int[]{upFactor * 2, upFactor * 2}, new int[]{upFactor, upFactor},
                            new int[]{upFactor / 2, upFactor / 2})
                            .nOut(numClasses)
                            .hasBias(false)
                            .weightInit(linearInterpolationInit)
                            .build()
                    )
        );
```
if I remove the FrozenLayer (keeping an unfrozen Deconvolution2D layer), the exception doesn't show up.

Using DL4J beta 7.

**Comment by jljljl** [comment]
@HGuillemet please check with debugger if it goes into org.deeplearning4j.nn.layers.FrozenLayer.java:159 at gradientAndScore() method

**Comment by jljljl** [comment]
Also seems like "fc" layer is another layer and it's not provided here. Debugging requires full code or probably at least graph declaration and initialization.

**Comment by agibsonccc** [comment]
@HGuillemet (and future readers)  I'll get to this after the M1 release. I plan on doing a bug fix sprint for bugs like this and in samediff. Sorry for the wait.

**Comment by agibsonccc** [comment]
@HGuillemet I'll be getting to this now that M1 is out. If you have any updates on this, let me know. Sorry this took so long, but focus on getting the CI infrastructure and tests reliable + the cleanup took way longer than I would have liked. Hopefully we can start getting some of these minor issues addressed now. Feedback is appreciated!

**Comment by agibsonccc** [comment]
Closing this, we support backprop with: FrozenLayerWithBackprop - usages here. https://github.com/eclipse/deeplearning4j/blob/5e8951cd8ee8106bb393635f840c398a1759b2fa/deeplearning4j/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/layers/FrozenLayerWithBackpropTest.java#L90 I assume this is for GANs.
