### ISSUE TITLE
Unsupported keras layer type KerasLayer exception

### ISSUE THREAD

**Issue by glenn-boudaer1990** [deeplearning4j/deeplearning4j#9174]
#### Issue Description

I have created and trained a TensorFlow Keras model in Python and saved it as _trained_model.h5:_

```
model = tf.keras.Sequential([hub.KerasLayer("https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4",
                                            output_shape = [1280],
                                            trainable = False),
                                            tf.keras.layers.Dropout(0.4),
                                            tf.keras.layers.Dense(train_generator.num_classes, activation='softmax')
                             ])

model.build([None, 224, 224, 3])
model.summary()

optimizer = tf.keras.optimizers.Adam(lr=1e-3)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics = ['acc'])

steps_per_epoch = np.ceil(train_generator.samples /train_generator.batch_size)
val_steps_per_epoch = np.ceil(valid_generator.samples/valid_generator.batch_size)
hist = model.fit(
    train_generator,
    epochs=3,
    verbose=1,
    steps_per_epoch=steps_per_epoch,
    validation_data=valid_generator,
    validation_steps=val_steps_per_epoch).history
```

Now I want to load my model into Deeplearning4J as follows:

```
public static void main(String[] args) throws Exception
{
  String simpleMlp = new ClassPathResource("trained_model.h5").getFile().getPath();
  MultiLayerNetwork model = KerasModelImport.importKerasSequentialModelAndWeights(simpleMlp);

  String imagePath = new ClassPathResource("image.png").getFile().getPath();
  File imageFile = new File(imagePath);
  ImageLoader imageLoader = new ImageLoader(height, width, channels);
  INDArray image = imageLoader.asRowVector(imageFile);

  INDArray outut = model.output(image);
}
```

However, this results in the following error:

```
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type KerasLayer. Please file an issue at https://github.com/eclipse/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:334)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:218)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:110)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:57)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:322)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:223)
```

I believe this has to do with the custom KerasLayer where I use Mobilenet V2's feature vector. Can this be solved, is there a workaround?

#### Version Information

* Deeplearning4j version **1.0.0-beta7**
* Platform information (OS, etc) **Windows 10 NT 64bit**

**Comment by agibsonccc** [comment]
@glenn-boudaer1990  that would have to be a custom layer. You can find docs on that here: https://deeplearning4j.konduit.ai/keras-import/custom-layers

**Comment by agibsonccc** [comment]
@glenn-boudaer1990  ok looking at this, I"ll have to find the associated underlying TF file and map it to this: https://github.com/eclipse/deeplearning4j/blob/c715aea405980eb043420af86c671032bbb78ec6/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/layers/TFOpLayer.java#L46 What it does is downloads a TF  file. More here: https://www.tensorflow.org/hub/api_docs/python/hub/KerasLayer ideally on the dl4j side we would know how to download these files and load them. I'll have to look in to that a bit.
