### ISSUE TITLE
ExceptionInInitializerError CPU user

### ISSUE THREAD

**Issue by nikkisingh111333** [deeplearning4j/deeplearning4j#9182]
hey there i m started to laearn deep4j but frustrated with error 'ExceptionInInitializerError',i dont have GPU followed tutorial on baeldung heres my code:
`	try { 
			
			RecordReader recordReader = new CSVRecordReader(0, ',') ;
		
		    recordReader.initialize(new FileSplit(new File("C:\\\\Users\\\\Nikki singh\\\\Downloads\\\\Iris.csv")));
            System.out.println(recordReader);
            DataSetIterator iterator = new RecordReaderDataSetIterator(
            		  recordReader, 150, 3,3);
            		DataSet allData = iterator.next();
            		allData.shuffle(42);
            		System.out.println(allData);
		    // …
		}
		catch(Exception ex) {
			System.out.println(ex);
		}`
Error i m getting 
`15:32:26.894 [main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
15:32:26.961 [main] WARN org.reflections.Reflections - given scan urls are empty. set urls in the configuration
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritables(RecordReaderMultiDataSetIterator.java:377)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:271)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:234)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:177)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:306)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:393)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:51)
	at Gamoneynew.Gamoneywelcomenew.Deep4JExamples.main(Deep4JExamples.java:27)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Properties.get(Object)" is null
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6212)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	... 8 more
Caused by: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Properties.get(Object)" is null
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6135)
	... 10 more
`
my pom.xml:
DL4J.VERSION:0.9.1
`<dependency>
    <groupId>org.deeplearning4j</groupId>
    <artifactId>deeplearning4j-core</artifactId>
    <version>${DL4J.VERSION}</version>
</dependency>
<dependency>
  <groupId>org.nd4j</groupId>
  <artifactId>nd4j-x86</artifactId>
  <version>0.4-rc3.8</version>
</dependency>
<dependency>
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native-platform</artifactId>
    <version>${DL4J.VERSION}</version>
</dependency>
`
what i m missing .....????

**Comment by agibsonccc** [comment]
@nikkisingh111333  this is not a bug. The issue tracker is not a place for support issues like this. Please post over on https://community.konduit.ai  - since this is your first time I'll respond. We document this right here: https://deeplearning4j.konduit.ai/config/backends - a simple self contained project can be found in the examples as well: https://github.com/eclipse/deeplearning4j-examples/tree/master/mvn-project-template

**Comment by nikkisingh111333** [comment]
it worked thankyouuu
