### ISSUE TITLE
when use spark to train network, encountered a problem: Can't establish connection after 10 seconds.

### ISSUE THREAD

**Issue by zhaoyunyemu** [deeplearning4j/deeplearning4j#9189]
I encountered a problem, but I am not sure what went wrong：
org.apache.spark.internal.Logging(Logging.scala:69): Lost task 0.0 in stage 12.0 (TID 17, hadoop1-server, executor 2): org.nd4j.linalg.exception.ND4JIllegalStateException: Can't establish connection afet 10 seconds. Terminating...
at org.nd4j.parameterserver.distributed.v2.transport.impl.AeronUdpTransport.addConnection(AeronUdpTransport.java:322)
at org.nd4j.parameterserver.distributed.v2.transport.impl.AeronUdpTransport.launch(AeronUdpTransport.java:352)
at org.nd4j.parameterserver.distributed.v2.ModelParameterServer.launch(ModelParameterServer.java:377)
at org.deeplearning4j.spark.parameterserver.pw.SharedTrainingWrapper.run(SharedTrainingWrapper.java:363)
at org.deeplearning4j.spark.parameterserver.functions.SharedFlatMapPaths.call(SharedFlatMapPaths.java:86)
at org.deeplearning4j.spark.parameterserver.functions.SharedFlatMapPaths.call(SharedFlatMapPaths.java:41)
at org.apache.spark.api.java.JavaRDDLike.$anonfun$mapPartitions$1(JavaRDDLike.scala:153)
at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:837)
at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:837)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
at org.apache.spark.scheduler.Task.run(Task.scala:127)
at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
The following is the configuration information and other information：
Deeplearning4j version： <dl4j.version>1.0.0-beta7</dl4j.version>
Platform information ：centos 7
CUDA version, if used： used cpu
NVIDIA driver version, if in use: used cpu
the code is:
VoidConfiguration conf = VoidConfiguration.builder()
.unicastPort(40123)
.networkMask("192.168.11.0/24")
.controllerAddress("0.0.0.0")
.meshBuildMode(MeshBuildMode.PLAIN)
.build();
udp 40123 port is through test:UDP packet sent successfully.
also i seen the log of aeron use
java -cp aeron-all-1.4.0.jar -Daeron.dir=/dev/shm/aeron-yarn-d99cef31-acab-4af7-9ca4-fc7b6eb06939 io.aeron.samples.ErrorStat
Command `n Control file /dev/shm/aeron-yarn-d99cef31-acab-4af7-9ca4-fc7b6eb06939/cnc.dat

1 observations from 2021-02-25 14:22:28.810+0800 to 2021-02-25 14:22:28.810+0800 for:
java.lang.RuntimeException: Channel error: Address already in use : aeron:udp?endpoint=192.168.11.7:49876
at io.aeron.driver.media.UdpChannelTransport.openDatagramChannel(UdpChannelTransport.java:130)
at io.aeron.driver.media.ReceiveChannelEndpoint.openChannel(ReceiveChannelEndpoint.java:145)
at io.aeron.driver.Receiver.onRegisterReceiveChannelEndpoint(Receiver.java:127)
at io.aeron.driver.cmd.RegisterReceiveChannelEndpointCmd.execute(RegisterReceiveChannelEndpointCmd.java:32)
at io.aeron.driver.Receiver.accept(Receiver.java:150)
at io.aeron.driver.Receiver.accept(Receiver.java:37)
at org.agrona.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:111)
at org.agrona.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:86)
at io.aeron.driver.Receiver.doWork(Receiver.java:66)
at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:220)
at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:159)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Address already in use
at sun.nio.ch.Net.bind0(Native Method)
at sun.nio.ch.Net.bind(Net.java:433)
at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:691)
at io.aeron.driver.media.UdpChannelTransport.openDatagramChannel(UdpChannelTransport.java:105)
... 11 more
what's the probleam? thank you

**Comment by zhaoyunyemu** [comment]
sometime aeron log has no error,but always Can't establish connection after
 10 seconds

**Comment by agibsonccc** [comment]
Should be fixed. Significant upgrade to aeron and spark versions in the next release.
