### ISSUE TITLE
Keras asymmetric size UpSampling2D layer import fails

### ISSUE THREAD

**Issue by aangelos28** [deeplearning4j/deeplearning4j#9201]
#### Issue Description

Importing a Keras model with asymmetric upsampling layers fails. There is an exception thrown because the size of one upsampling layer is not symmetric. The Keras model `UpSampling2D` layer has size 3x2 (Height-Width). However, the `KerasUpsampling2D` class in DL4J expects the two sizes to be the same (e.g. 2x2). I do not understand why this limit is present. The following code in KerasUpsampling2D throws the exception:

```java
    public KerasUpsampling2D(Map<String, Object> layerConfig, boolean enforceTrainingConfig) throws InvalidKerasConfigurationException, UnsupportedKerasConfigurationException {
        super(layerConfig, enforceTrainingConfig);
        int[] size = KerasConvolutionUtils.getUpsamplingSizeFromConfig(layerConfig, 2, this.conf);
        if (size[0] != size[1]) {
            throw new UnsupportedKerasConfigurationException("First and second size arguments have to be the samegot: " + size[0] + " and " + size[1]);
        } else {
            Builder builder = ((Builder)((Builder)(new Builder()).name(this.layerName)).dropOut(this.dropout)).size(size[0]);
            this.layer = builder.build();
            this.vertex = null;
        }
    }
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta6
* OS: Ubuntu 20.04.2 LTS

#### Additional Information

Exception:

```
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: First and second size arguments have to be the samegot: 3 and 2. Please file an issue at https://github.com/eclipse/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.layers.convolutional.KerasUpsampling2D.<init>(KerasUpsampling2D.java:61)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:298)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:218)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:110)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:57)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:322)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:301)
```

**Comment by agibsonccc** [comment]
@aangelos28  beta6 is not the most recent released version. Update to beta7 first and if that doesn't work, give me a copy of your model so I can look at this and make sure this is fixed in the next release.

**Comment by aangelos28** [comment]
@agibsonccc I have tried this with beta7, but the same issue is present. I have attached the Keras sequential model configuration (zipped). I am using `KerasModelImport.importKerasSequentialConfiguration` to load it.
[keras_model.zip](https://github.com/eclipse/deeplearning4j/files/6087650/keras_model.zip)

**Comment by agibsonccc** [comment]
@aangelos28  sorry this took a bit: https://github.com/eclipse/deeplearning4j/pull/9259
It was only a few lines, but I had backlog for release to take care of :) this will make it in to the next release since it's a fairly straightforward fix. You're welcome to use snapshots for testing in the mean time. https://deeplearning4j.konduit.ai/config/config-snapshots

**Comment by aangelos28** [comment]
@agibsonccc That's great! Thanks.
