### ISSUE TITLE
java.lang.UnsupportedOperationException in createShapeInfo with SNAPSHOT on DL4J Examples

### ISSUE THREAD

**Issue by MPdaedalus** [deeplearning4j/deeplearning4j#9242]
expected behavior

examples  LinearDataClassifier and IrisClassifier run successfully (success with beta7 on cuda10.2),

- encountered behavior
- failure with snapshot on cuda 10.2  (native cpu works fine)
`Example data present in /home/daedalus/dl4j-examples-data/dl4j-examples/classification
17:27:25.265 [main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
17:27:25.291 [main] ERROR org.nd4j.common.config.ND4JClassLoading - Cannot find class [org.nd4j.linalg.jblas.JblasBackend] of provided class-loader.
17:27:25.291 [main] ERROR org.nd4j.common.config.ND4JClassLoading - Cannot find class [org.canova.api.io.data.DoubleWritable] of provided class-loader.
17:27:25.447 [main] ERROR org.nd4j.common.config.ND4JClassLoading - Cannot find class [org.nd4j.linalg.jblas.JblasBackend] of provided class-loader.
17:27:25.449 [main] ERROR org.nd4j.common.config.ND4JClassLoading - Cannot find class [org.canova.api.io.data.DoubleWritable] of provided class-loader.
17:27:30.124 [main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for linear algebra: 32
17:27:30.194 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Linux]
17:27:30.194 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [4]; Memory: [3.9GB];
17:27:30.194 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [CUBLAS]
17:27:30.233 [main] INFO org.nd4j.linalg.jcublas.JCublasBackend - ND4J CUDA build version: 10.2.89
17:27:30.235 [main] INFO org.nd4j.linalg.jcublas.JCublasBackend - CUDA device 0: [GeForce GTX 1060 6GB]; cc: [6.1]; Total memory: [6373179392]
17:27:30.439 [main] INFO org.deeplearning4j.nn.multilayer.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
Exception in thread "main" java.lang.UnsupportedOperationException
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.createShapeInfo(DefaultOpExecutioner.java:945)
	at org.nd4j.linalg.api.shape.Shape.createShapeInformation(Shape.java:3279)
	at org.nd4j.linalg.api.ndarray.BaseShapeInfoProvider.createShapeInformation(BaseShapeInfoProvider.java:75)
	at org.nd4j.jita.constant.ProtectedCudaShapeInfoProvider.createShapeInformation(ProtectedCudaShapeInfoProvider.java:92)
	at org.nd4j.jita.constant.ProtectedCudaShapeInfoProvider.createShapeInformation(ProtectedCudaShapeInfoProvider.java:73)
	at org.nd4j.linalg.jcublas.CachedShapeInfoProvider.createShapeInformation(CachedShapeInfoProvider.java:42)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:197)
	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:386)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:1524)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:1519)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4299)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3987)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:688)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:604)
	at test.LinearDataClassifier.main(LinearDataClassifier.java:93)`

Deeplearning4j  snapshot
fedora 32 cuda 10.2 with cuddnn installed (both native cuda and cuda-platform-redist produce same result) 
nvidia driver 460.56

my pom.xml>
https://gist.github.com/MPdaedalus/c123cc5f89752066a6142aa1255dda8b
my full launch command generated by eclipse>
https://gist.github.com/MPdaedalus/c123cc5f89752066a6142aa1255dda8b#file-gistfile1-txt

I don't know the internals of dl4j but i'm guessing that DefaultOpExecutioner which methods throw new UnsupportedOperationException() by default is not the correct implementation OpExecutioner to be used by cuda?

see also>
https://community.konduit.ai/t/rnn-and-ff-getting-mixed-up-in-mergevertex-new-filestatsstorage-not-work/1228/6

**Comment by agibsonccc** [comment]
@MPdaedalus  thanks, let me fix this by next week. I'm still cleaning up the tests a bit.

**Comment by agibsonccc** [comment]
@MPdaedalus  closing this due to resolution in the forums. Cuda 10.2 will not be supported for this release.
