### ISSUE TITLE
Euclidean Distance with allDistances true not working

### ISSUE THREAD

**Issue by Rolnire** [deeplearning4j/deeplearning4j#9257]
#### Issue Description
Hello 
Calculation of Euclidean distance with allDistances parameter set to true is not working with GPU backend. With CPU backend it is working correctly. There are two scenarios:
**Scenario 1:**
`INDArray positive = Nd4j.rand(5, 256);`
`INDArray negative = Nd4j.rand(10, 256);`
I want to calculate distance between every positive vector (at 0th index) and every negative vector.
`INDArray distances = Nd4j.exec(new EuclideanDistance(negative, positive, true, 1));`
With CPU backend I'm getting distances with shape [10,5] and correct distances.
With GPU there is this exception:
```
org.nd4j.linalg.exception.ND4JIllegalStateException: Size of TADs along dimension don't match for pairwise execution: (x TAD size = 256, y size = 1280

	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.invoke(CudaExecutioner.java:973)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:650)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:619)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6553)
```
**Scenario 2:**
`INDArray positive = Nd4j.rand(5, 256);`
I want to calculate distance of every combination of vectors.
`INDArray distances = Nd4j.exec(new EuclideanDistance(positive, positive, true, 1));`
Again with CPU backend there is result with [5,5] shape and correct distances, but with GPU backend there is result with [5] shape and every value is 0.

#### Version Information

* DL4J beta 1.0.0-beta7
* Ubuntu 20.04.1 LTS, kernel 5.4.0-64-generic
* CUDA version 11.0
* NVIDIA driver version 450.102.04

#### Additional Information

I want to try SNAPSHOT, but it is not working for me now for some reason, so if it is already solved, I'm sorry :).

**Comment by agibsonccc** [comment]
@Rolnire  do you know why snapshots  isn't working for you? Are you trying on a specific platform? It'd be great to ensure the quality of the release. I apologize for the volatility, but I'm looking at user issues now. I'll have to look at this one later.

**Comment by Rolnire** [comment]
@agibsonccc I don't know to be honest, but I just created issue for that, so it can be hopefully solved. There is issue link https://github.com/eclipse/deeplearning4j/issues/9264. My platform informations are in **Version information** section. Thank you for your help.

**Comment by agibsonccc** [comment]
@Rolnire  I addressed your issue. You just need to upgrade your cuda version and you're good to go. Thanks for being open to helping with testing!

**Comment by Rolnire** [comment]
@agibsonccc I finally had time to update CUDA and try SNAPSHOT. I installed CUDA 11.2 without cuDNN and SNAPSHOT was working. After cuDNN 8.1.1 installation it is not working for me anymore. cuDNN should be installed correctly, because test passed (see log) [mnistCUDNN.log](https://github.com/eclipse/deeplearning4j/files/6466113/mnistCUDNN.log)
I cannot open ZOO models. Exception: 

> Exception in thread "main" java.lang.RuntimeException: java.lang.NoSuchMethodException: org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper.<init>(java.lang.Class,org.nd4j.linalg.api.buffer.DataType)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:108)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:89)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:74)
	at org.deeplearning4j.nn.layers.HelperUtils.createHelper(HelperUtils.java:58)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.initializeHelper(ConvolutionLayer.java:75)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.<init>(ConvolutionLayer.java:70)
	at org.deeplearning4j.nn.conf.layers.ConvolutionLayer.instantiate(ConvolutionLayer.java:173)
	at org.deeplearning4j.nn.conf.graph.LayerVertex.instantiate(LayerVertex.java:106)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:572)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraphHelper(ModelSerializer.java:572)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:462)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:647)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:603)
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:99)

I have same issue with my serialized models. Am I missing some migration?

**Comment by agibsonccc** [comment]
@Rolnire  that's just related to deeplearning4j-cuda. You can either remove that for now or install deeplearning4j-cuda on my branch here: https://github.com/eclipse/deeplearning4j/pull/9308

Depending on which cuda version you use, ensure you run change-cuda-versions.sh to either 11.0 or 11.2 depending on which version you install. deeplearning4j-cuda doesn't need anything (just snapshots) so as long as you use that you should be good. Otherwise we should merge this pull request tomorrow or early next week depending on review.

**Comment by Rolnire** [comment]
@agibsonccc I can see, request is merged, but for me nothing changed. I'm getting same exception again. To get libraries I use this command:
`mvn dependency:copy-dependencies -U -DoutputDirectory=../../lib/mvnLibs/`
Any idea, what can be wrong?

**Comment by agibsonccc** [comment]
@Rolnire  rerun the actual downloads first with mvn -U clean package first. Maybe even delete the org/deeplearning4j/deeplearning4j-cuda-11.2/1.0.0-SNAPSHOT directory completely under your .m2 just to be sure. I have multiple unit tests in that branch showing it works. If I missed something, I'm open to that but I'd like to make sure that it's not just a flaky update. Snapshots are known to have issues sometimes.

**Comment by Rolnire** [comment]
@agibsonccc I deleted whole .m2 file and run downloads again. It did not help, same exception again. There is log, you can see some additional errors there:
```
2021-05-17 11:30:57,344 | INFO | Loaded [JCublasBackend] backend 
2021-05-17 11:30:57,349 | ERROR | Cannot find class [org.nd4j.linalg.jblas.JblasBackend] of provided class-loader. 
2021-05-17 11:30:57,349 | ERROR | Cannot find class [org.canova.api.io.data.DoubleWritable] of provided class-loader. 
2021-05-17 11:30:57,351 | ERROR | Cannot find class [org.nd4j.linalg.jblas.JblasBackend] of provided class-loader. 
2021-05-17 11:30:57,352 | ERROR | Cannot find class [org.canova.api.io.data.DoubleWritable] of provided class-loader. 
2021-05-17 11:30:59,160 | INFO | Number of threads used for linear algebra: 32 
2021-05-17 11:30:59,193 | INFO | Backend used: [CUDA]; OS: [Linux] 
2021-05-17 11:30:59,193 | INFO | Cores: [24]; Memory: [48.0GB]; 
2021-05-17 11:30:59,193 | INFO | Blas vendor: [CUBLAS] 
2021-05-17 11:30:59,201 | INFO | ND4J CUDA build version: 11.2.152 
2021-05-17 11:30:59,225 | INFO | CUDA device 0: [Tesla V100-PCIE-16GB]; cc: [7.0]; Total memory: [16945512448] 
2021-05-17 11:30:59,226 | INFO | Backend build information:
 GCC: "7.5.0"
STD version: 201402L
CUDA: 11.2.152
DEFAULT_ENGINE: samediff::ENGINE_CUDA
HAVE_FLATBUFFERS 
```

**Comment by agibsonccc** [comment]
@Rolnire actually that looks great. Sorry for the confusion. Those classes not being found is actually a good thing. That means no old versions are present. I will make sure that gets fixed in the next update so that's less confusing. If there's more to your log though, I'm happy to take a look.

**Comment by Rolnire** [comment]
@agibsonccc Good to hear that :). But main issue for me is that I can't load serialized models and zoo models. For example if I run simple main just with this line
`Darknet19.builder().build().initPretrained(PretrainedType.IMAGENET);`
I will get this:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.NoSuchMethodException: org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper.<init>(java.lang.Class,org.nd4j.linalg.api.buffer.DataType)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:108)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:89)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:74)
	at org.deeplearning4j.nn.layers.HelperUtils.createHelper(HelperUtils.java:58)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.initializeHelper(ConvolutionLayer.java:75)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.<init>(ConvolutionLayer.java:70)
	at org.deeplearning4j.nn.conf.layers.ConvolutionLayer.instantiate(ConvolutionLayer.java:173)
	at org.deeplearning4j.nn.conf.graph.LayerVertex.instantiate(LayerVertex.java:106)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:572)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraphHelper(ModelSerializer.java:572)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:462)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:647)
	at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:603)
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:99)
	at eu.extech.Test.main(Test.java:35)
Caused by: java.lang.NoSuchMethodException: org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper.<init>(java.lang.Class,org.nd4j.linalg.api.buffer.DataType)
	at java.base/java.lang.Class.getConstructor0(Class.java:3508)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2711)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:103)
	... 14 more
```

**Comment by agibsonccc** [comment]
@Rolnire  that's indicative of a missing constructor, specifically the data type one. That one is found here: 
https://github.com/eclipse/deeplearning4j/blob/46dbd0b2035fab86f5d500508af46690b97af7c8/deeplearning4j/deeplearning4j-cuda/src/main/java/org/deeplearning4j/cuda/convolution/CudnnConvolutionHelper.java#L77
I'd still guess something is missing. For now, could you try installing from master? I think it's because snapshots aren't up to date with the fix. I'll look at that over the next day or so. All you have to do is run:
```bash
mvn clean install -DskipTests 
```
in the deeplearning4j-cuda directory. cuda defaults to 11.0 right now. If you want 11.2, before you do anything run:
./change-cuda-versions.sh 11.2

What should happen locally is it will pull snapshots for everything but deeplearning4j-cuda which will have the source installed version. Note that you should do this right in the deeplearning4j-cuda directory otherwise you have to setup profiles and all sorts of other noise that isn't relevant to just getting the right java files installed.

Sorry for the minor hiccup, but working on GH actions with just the github hosted runners has long build times (especially for cuda) and so sometimes things get missed yet. We're working on making sure all of the relevant combinations of builds get in there for end users for the release. Some of that takes a bit of time :)

**Comment by Rolnire** [comment]
@agibsonccc Thank you for you time and help. As we are not much confident using github and maven, there are steps we did:
```
git clone https://github.com/eclipse/deeplearning4j.git
cd deeplearning4j
./change-cuda-versions.sh 11.2
cd deeplearning4j/deeplearning4j-cuda
mvn clean install -DskipTests
```
We've got following error. Is there something we did wrong?
We are also willing to wait until the SNAPSHOT version will be built correctly.

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/benda/dl4j-github/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/test/java/org/deeplearning4j/cuda/HelperUtilsTests.java:[28,94] incompatible types: java.lang.Class<org.deeplearning4j.nn.layers.recurrent.LSTMHelper> cannot be converted to org.nd4j.linalg.api.buffer.DataType
[ERROR] /home/benda/dl4j-github/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/test/java/org/deeplearning4j/cuda/HelperUtilsTests.java:[29,100] incompatible types: java.lang.Class<org.deeplearning4j.nn.conf.dropout.DropoutHelper> cannot be converted to org.nd4j.linalg.api.buffer.DataType
[ERROR] /home/benda/dl4j-github/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/test/java/org/deeplearning4j/cuda/HelperUtilsTests.java:[30,108] incompatible types: java.lang.Class<org.deeplearning4j.nn.layers.convolution.ConvolutionHelper> cannot be converted to org.nd4j.linalg.api.buffer.DataType
[ERROR] /home/benda/dl4j-github/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/test/java/org/deeplearning4j/cuda/HelperUtilsTests.java:[31,138] incompatible types: java.lang.Class<org.deeplearning4j.nn.layers.normalization.LocalResponseNormalizationHelper> cannot be converted to org.nd4j.linalg.api.buffer.DataType
[ERROR] /home/benda/dl4j-github/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/test/java/org/deeplearning4j/cuda/HelperUtilsTests.java:[32,108] incompatible types: java.lang.Class<org.deeplearning4j.nn.layers.convolution.subsampling.SubsamplingHelper> cannot be converted to org.nd4j.linalg.api.buffer.DataType
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.170 s
[INFO] Finished at: 2021-05-17T13:38:19+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (testCompile) on project deeplearning4j-cuda-11.2: Compilation failure: Compilation failure: 
[ERROR] /home/benda/dl4j-github/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/test/java/org/deeplearning4j/cuda/HelperUtilsTests.java:[28,94] incompatible types: java.lang.Class<org.deeplearning4j.nn.layers.recurrent.LSTMHelper> cannot be converted to org.nd4j.linalg.api.buffer.DataType
[ERROR] /home/benda/dl4j-github/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/test/java/org/deeplearning4j/cuda/HelperUtilsTests.java:[29,100] incompatible types: java.lang.Class<org.deeplearning4j.nn.conf.dropout.DropoutHelper> cannot be converted to org.nd4j.linalg.api.buffer.DataType
[ERROR] /home/benda/dl4j-github/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/test/java/org/deeplearning4j/cuda/HelperUtilsTests.java:[30,108] incompatible types: java.lang.Class<org.deeplearning4j.nn.layers.convolution.ConvolutionHelper> cannot be converted to org.nd4j.linalg.api.buffer.DataType
[ERROR] /home/benda/dl4j-github/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/test/java/org/deeplearning4j/cuda/HelperUtilsTests.java:[31,138] incompatible types: java.lang.Class<org.deeplearning4j.nn.layers.normalization.LocalResponseNormalizationHelper> cannot be converted to org.nd4j.linalg.api.buffer.DataType
[ERROR] /home/benda/dl4j-github/deeplearning4j/deeplearning4j/deeplearning4j-cuda/src/test/java/org/deeplearning4j/cuda/HelperUtilsTests.java:[32,108] incompatible types: java.lang.Class<org.deeplearning4j.nn.layers.convolution.subsampling.SubsamplingHelper> cannot be converted to org.nd4j.linalg.api.buffer.DataType
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by agibsonccc** [comment]
@Rolnire :
```bash
mvn clean install -DskipTests -Dmaven.test.skip=true
```

That will skip compiling the tests.

**Comment by agibsonccc** [comment]
@Rolnire  actually, you also need to compile deeplearning4j-nn. Please do the same steps as I mentioned above. Those will be the only 2 folders you need. Sorry for the confusion. This is the relevant file:
https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/HelperUtils.java

Then deeplearning4j-cuda will use that HelperUtils. Install both just to be safe.

**Comment by Rolnire** [comment]
@agibsonccc great job, it is working now without exception! Thank you for great job.

Now back to my first question about Euclidean distance. It is still not working - same result with cuda 10.2 + beta7 and cuda 11.2 + SNAPSHOT.

**Comment by agibsonccc** [comment]
@Rolnire  ok let me look in to this after M1 is out (should be in the next day or 2) - we'll do a follow up M2 release with a batch of bug fixes. I'll test stuff like this and then you can use snapshots.
