### ISSUE TITLE
CUDA broken after a while

### ISSUE THREAD

**Issue by jljljl** [deeplearning4j/deeplearning4j#9307]
Some time ago i ran on that pc cuda dl4j programs.
After some time of inactivity CUDA has become unable to work with dl4j. Running LeNetMNIST example caused an exception. Also tried MNISTCUDNN.java from cuda-specific-examples.

The file is present but looks like it don't contain some special procedure.
I tried to reinstall NVIDIA driver because it became patrially broken (won't open control panel), but problem remains.

File is attached.

Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information

* i have HDD separated so my OS is not on C:/
* pom.xml from cuda-specific-examples and some different variations. Also check this pom cause it contains depencency duplication
* user\ .javacpp\cache\cuda-10.2-7.6-1.5.3-windows-x86_64.jar\org\bytedeco\cuda\windows-x86_64
* dl4j beta7
* CUDA 10.2.89
* cuDNN windows7-x64-v7.6.5.32
* Windows 7
* NVIDIA driver version 391.35

#### Additional Information
<details>
  <summary>Log</summary>

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnicudart in java.library.path: [verylongpath]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2654)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:876)
	at java.base/java.lang.System.loadLibrary(System.java:1875)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1631)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1265)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1109)
	at org.bytedeco.cuda.global.cudart.<clinit>(cudart.java:14)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1176)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1109)
	at org.bytedeco.cuda.global.cudnn.<clinit>(cudnn.java:16)
	at MNISTCUDNN$network_t.createHandles(MNISTCUDNN.java:342)
	at MNISTCUDNN$network_t.<init>(MNISTCUDNN.java:115)
	at MNISTCUDNN.main(MNISTCUDNN.java:501)
Caused by: java.lang.UnsatisfiedLinkError: [path]: Procedure not found
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2424)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2481)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2678)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2611)
	at java.base/java.lang.Runtime.load0(Runtime.java:814)
	at java.base/java.lang.System.load(System.java:1838)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1581)
	... 11 more

```
  
</details>

#### Additional information
It took many times of reading for me to get how to install CUDA and cuDNN.
Please provide a lot more information how to select CUDA and cuDNN verion, install CUDA, install cuDNN, configure pom.xml, upto when to restart PC. I guess it would be hard for ppl who want to check.
If i get it right i could help with that.

**Comment by treo** [comment]
It looks like you are using quite an old driver version. And given that you've had some cuda trouble, I guess it may be a good idea to use DDU (https://www.guru3d.com/files-details/display-driver-uninstaller-download.html) to uninstall your driver, and then reinstall the newest version.

Other than that, the easiest way to get it working is to use this dependency:
```
<dependency>
  <groupId>org.bytedeco</groupId>
  <artifactId>cuda-platform-redist</artifactId>
  <version>10.2-7.6-1.5.3</version>
</dependency>
```

It has the drawback, that unless you use `-Djavacpp.platform=windows-x86_64` when building your application, it will download cuda for all supported platforms. But you will get both cuda and cudnn that way.

**Comment by jljljl** [comment]
It's fun because i ran MNIST learning example on my video card, but it should not run at all. It has CUDA compute capability of 2.1 or driver compatibility with CUDA 9. I dunno how to get know if it should work with CUDA.

**Comment by jljljl** [comment]
This dependency don't contain cuda 9.
```
<dependency>
  <groupId>org.bytedeco</groupId>
  <artifactId>cuda-platform-redist</artifactId>
  <version>10.2-7.6-1.5.3</version>
</dependency>
```
`-Djavacpp.platform=windows-x86_64` is that argument for VM option? Or build option? I don't know

**Comment by treo** [comment]
> It's fun because i ran MNIST learning example on my video card, but it should not run at all. It has CUDA compute capability of 2.1 or driver compatibility with CUDA 9

These days we only support cards that are at least in the 900 family and have compute capability 5.2 if I remember correctly. And in beta7 we don't support cuda 9 at all.

The dependency that I've shared includes cuda 10.2 along with cudnn 7.6 and should work with nd4j-cuda-10.2.

**Comment by jljljl** [comment]
I see, but somehow i get it to work correctly. As i remember it was CUDA 10.2 or 10.0. It was 2 times slower than CPU, but here is less than 100 CUDA cores.

**Comment by jljljl** [comment]
Anyway CUDA 10.2 is successfully installed on my PC. I guess i miss some libraries or configuration. It was working so i am pretty sure i could get it working again
