### ISSUE TITLE
arm64 builds require too new glibc

### ISSUE THREAD

**Issue by euclio** [deeplearning4j/deeplearning4j#9325]
#### Issue Description

I'm trying to use nd4j-native-platform on Amazon Linux 2 aarch64, which uses GLIBC 2.26. It appears that libjnind4jcpu.so requires GLIB 2.27, however:

```
        java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
            at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:112)
            at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:35)
            ... 12 more

            Caused by:
            java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
                at java.lang.Runtime.loadLibrary0(Runtime.java:871)
                at java.lang.System.loadLibrary(System.java:1124)
                at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1543)
                at org.bytedeco.javacpp.Loader.load(Loader.java:1192)
                at org.bytedeco.javacpp.Loader.load(Loader.java:1042)
                at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:13)
                at java.lang.Class.forName0(Native Method)
                at java.lang.Class.forName(Class.java:264)
                at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:85)
                ... 13 more

                Caused by:
                java.lang.UnsatisfiedLinkError: /local/home/andyru/.javacpp/cache/nd4j-native-1.0.0-beta6-linux-arm64.jar/org/nd4j/nativeblas/linux-arm64/libjnind4jcpu.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /local/home/andyru/.javacpp/cache/nd4j-native-1.0.0-beta7-linux-arm64.jar/org/nd4j/nativeblas/linux-arm64/libnd4jcpu.so)
                    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
                    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
                    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
                    at java.lang.Runtime.load0(Runtime.java:810)
                    at java.lang.System.load(System.java:1088)
                    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1493)
                    ... 19 more
```

Would it be possible to use an older GLIBC to build the artifact so that I can link it on Amazon Linux 2?

#### Version Information

* Deeplearning4j version 1.0.0_beta7
* Platform information (OS, etc) Amazon Linux 2 aarch64

**Comment by agibsonccc** [comment]
@euclio the latest release will be using glibc from ubuntu 16. I'm closing this issue as this has  already been solved. If you need an older glibc, you can try snapshots and see if that works for you.
