### ISSUE TITLE
Multi-threaded classify causes NPE

### ISSUE THREAD

**Issue by daw3rd** [deeplearning4j/deeplearning4j#9336]
#### Issue Description

I have a trained CNN on which I am making classification requests using multiple threads on a GPU machine.  I get the NPE shown below.  This problem does NOT happen when not using multi-threaded classifications (i.e. multiple threads, each making a call to our classify() method (see below).

#### Version Information

* Deeplearning4j beta7
* Red Hat Enterprise Linux Server release 7.8 (Maipo)
* CUDA 10.2 libraries 
* NVIDIA 450.80.02
* Java openjdk version "1.8.0_262"

#### Additional Information

Caused by: java.lang.NullPointerException
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.setInputMiniBatchSize(MultiLayerNetwork.java:3087)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.setInput(MultiLayerNetwork.java:2821)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1191)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2415)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2378)
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2369)
        at com.ibm.watson.iot.sound.modeling.cnn.FixedCNNClassifier.classify(FixedCNNClassifier.java:123)

**Comment by agibsonccc** [comment]
@daw3rd if you want thread safety, please consider using parallel wrapper and ParallelInference for the models setting the number of workers to 1.
