### ISSUE TITLE
HistogramIterationListener error in Scala - ExceptionInInitializerError

### ISSUE THREAD

**Issue by octavian-ganea** [deeplearning4j/deeplearning4j#934]
I try to use the HistogramIterationListener by doing: 
```
network.setListeners(new HistogramIterationListener(1)) 
```
I then get the error:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
at org.deeplearning4j.ui.weights.HistogramIterationListener.<init>(HistogramIterationListener.java:50)
at org.deeplearning4j.ui.weights.HistogramIterationListener.<init>(HistogramIterationListener.java:45)
at neural.el.RegressionExample$.main(RegressionExample.scala:76)
at neural.el.RegressionExample.main(RegressionExample.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassCastException: org.slf4j.impl.Log4jLoggerAdapter cannot be cast to ch.qos.logback.classic.Logger
at io.dropwizard.logging.LoggingFactory.bootstrap(LoggingFactory.java:43)
at io.dropwizard.logging.LoggingFactory.bootstrap(LoggingFactory.java:37)
at io.dropwizard.Application.<clinit>(Application.java:20)
```

The code that I modified is the RegressionExample one http://pastebin.com/3uyKyCPU . The only thing that I modified is the listener line.

**Comment by horsehour** [comment]
I get the same exception when I add the new HistogramIteratorListener script to my java code.

**Comment by raver119** [comment]
use another logger.

**Comment by horsehour** [comment]
which logger pls?
