### ISSUE TITLE
WeightedCrossEntropyLoss.java has no doDiff method

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#9361]
java.lang.UnsupportedOperationException: Please extend DynamicCustomOp.doDiff to support SameDiff backprop operations. Op: org.nd4j.linalg.api.ops.impl.loss.WeightedCrossEntropyLoss
	at org.nd4j.linalg.api.ops.DynamicCustomOp.doDiff(DynamicCustomOp.java:593)
	at org.nd4j.autodiff.functions.DifferentialFunction.diff(DifferentialFunction.java:577)
	at org.nd4j.autodiff.samediff.SameDiff$1.define(SameDiff.java:4445)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:3989)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:3974)
	at org.nd4j.autodiff.samediff.SameDiff.createGradFunction(SameDiff.java:4185)
	at org.nd4j.autodiff.samediff.SameDiff.createGradFunction(SameDiff.java:4092)
	at org.nd4j.autodiff.samediff.SameDiff.fitHelper(SameDiff.java:1647)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1569)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1509)
	at org.nd4j.autodiff.samediff.config.FitConfig.exec(FitConfig.java:172)

**Comment by agibsonccc** [comment]
@SidneyLann  let's keep your separate issue you already raised as the main one. Thanks for notifying, we just haven't gotten around to finishing looking at this yet. I put one of our other engineers on this and will try to get this fixed in the next week or so, after that the fix will be available via snapshots.
