### ISSUE TITLE
Bug: Workspace Memory consumption

### ISSUE THREAD

**Issue by sascha08-15** [deeplearning4j/deeplearning4j#9370]
worked in beta 7, only occurs in 1.0.0-M1 now (Win and native Backends)
Following test crashes cause it's allocating 16 bytes instead of 8 bytes for a double.

````
    @Test
    public void testWorkspace(){

        Nd4j.setDefaultDataTypes(DataType.DOUBLE,DataType.DOUBLE);
        var wsMgr = Nd4j.getWorkspaceManager();
        var initialSize = 1 * Double.BYTES;
        var learningConfig = WorkspaceConfiguration.builder()
                .policyAllocation(AllocationPolicy.STRICT)
                .policySpill(SpillPolicy.FAIL)
                .initialSize(initialSize)
                .policyLearning(LearningPolicy.NONE)
                .policyReset(ResetPolicy.BLOCK_LEFT)
                //.policyLocation(LocationPolicy.RAM)
                .build();
        var workspace = wsMgr.getWorkspaceForCurrentThread(learningConfig, "test");
        workspace.enableDebug(true);
        workspace.notifyScopeEntered();

        var matrix = Nd4j.zeros(1,1,'c'); // 1 Element in our matrix
        matrix.migrate(); //supposed to alloc 1 element = 1 Double = 8 Bytes, but it's taking 16
        
    }
````

Leads to this exception
````
00:34:21.769 [INFO ] [Nd4jWorkspace alloc]: Workspace [test]: Allocating array of 16 bytes, capacity of 1 elements, prevOffset: 0; currentOffset: 16; address: 2524809659792
00:34:21.910 [INFO ] [Nd4jWorkspace alloc]: Workspace [test]: step: 0, spilled  16 bytes, capacity of 1 elements

org.nd4j.linalg.exception.ND4JIllegalStateException: Can't allocate memory: Workspace is full

	at org.nd4j.linalg.api.memory.abstracts.Nd4jWorkspace.alloc(Nd4jWorkspace.java:440)
	at org.nd4j.linalg.api.memory.abstracts.Nd4jWorkspace.alloc(Nd4jWorkspace.java:320)
	at org.nd4j.linalg.cpu.nativecpu.buffer.BaseCpuDataBuffer.<init>(BaseCpuDataBuffer.java:485)
	at org.nd4j.linalg.cpu.nativecpu.buffer.DoubleBuffer.<init>(DoubleBuffer.java:74)
	at org.nd4j.linalg.cpu.nativecpu.buffer.DefaultDataBufferFactory.create(DefaultDataBufferFactory.java:327)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1455)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.migrate(BaseNDArray.java:5363)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.migrate(BaseNDArray.java:5342)
````

However 2 doubles will be allocated with 16 bytes. Some off by one issue?

**Comment by agibsonccc** [comment]
@sascha08-15  thanks for the reproducer. We'll look in to this. We'll be turning around a follow up release pretty quickly (this week or next week) to address some issues the community has raised.

**Comment by agibsonccc** [comment]
@sascha08-15 actually this isn't a bug. We pad the memory for alignment reasons. If you look at the actual required memory we actually require that for performance reasons. (We force alignment which causes the padding), you can see that here: https://github.com/eclipse/deeplearning4j/blob/4766032444de8e0c2c3389270576bb6e7c466211/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/memory/abstracts/Nd4jWorkspace.java#L345

Migrate() also allocates more memory. You only need to call notify scope entered and the create to show this case. I'm closing this.
