### ISSUE TITLE
LSTM not work in M1

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#9389]
#### Issue Description

Please describe our issue, along with:
- expected behavior
let M1 work like it does in beta7

- encountered behavior

Could not calculate output shape for op DynamicCustomOp: not fully initialized (0 TArgs specified, 1 required)

```
java.lang.NullPointerException: array is marked non-null but is null
	at org.deeplearning4j.nn.workspace.LayerWorkspaceMgr.validateArrayLocation(LayerWorkspaceMgr.java:80)
	at org.deeplearning4j.nn.graph.ComputationGraph.validateArrayWorkspaces(ComputationGraph.java:1877)
	at org.deeplearning4j.nn.graph.ComputationGraph.ffToLayerActivationsInWS(ComputationGraph.java:2159)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1371)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1340)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:174)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:61)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1164)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1114)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1081)
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version M1
* Platform information (OS, etc) WIN7
* CUDA version, if used  NO
* NVIDIA driver version, if in use NO

**Comment by agibsonccc** [comment]
@SidneyLann  could you please provide a complete example including input I can just run to verify this? Thanks!

**Comment by SidneyLann** [comment]
[dl4j-lstm.zip](https://github.com/eclipse/deeplearning4j/files/6739104/dl4j-lstm.zip)
[lstm.zip](https://github.com/eclipse/deeplearning4j/files/6739114/lstm.zip)

**Comment by SidneyLann** [comment]
@agibsonccc uploaded. Please change the DATA_HOME folder in LstmUtil.java

**Comment by SidneyLann** [comment]
@agibsonccc Please give me your email address.

**Comment by agibsonccc** [comment]
@SidneyLann  DM me on the forums please.

**Comment by SidneyLann** [comment]
But there can't upload zip files.

**Comment by agibsonccc** [comment]
@SidneyLann  that's fine. I'm happy to have the conversation on there, then if needed you can send me sharing links or an email. I just don't want an email publicly accessible for bots to spam.

**Comment by agibsonccc** [comment]
@SidneyLann  confirmed already fixed on snapshots/new release version. I was able to run your code just fine. I downloaded it from the archives. It was likely related to the helpers issues that were already fixed. Thanks for reporting!
