### ISSUE TITLE
Keras Import Problem: Unsupported keras layer type Functional

### ISSUE THREAD

**Issue by marquies** [deeplearning4j/deeplearning4j#9398]
Hey all, thank you for your efforts in this project. KUDOS.

#### Issue Description

I'm trying to load a Keras Model created with TF. It is a Yolov3. Looks like the Functional Layer Type is not supported (?)

```
Model: "yolov3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input (InputLayer)              [(None, 100, 100, 3) 0                                            
__________________________________________________________________________________________________
yolo_darknet (Functional)       ((None, None, None,  40620640    input[0][0]                      
__________________________________________________________________________________________________
yolo_conv_0 (Functional)        (None, 3, 3, 512)    11024384    yolo_darknet[0][2]               
__________________________________________________________________________________________________
yolo_conv_1 (Functional)        (None, 6, 6, 256)    2957312     yolo_conv_0[0][0]                
                                                                 yolo_darknet[0][1]               
__________________________________________________________________________________________________
yolo_conv_2 (Functional)        (None, 12, 12, 128)  741376      yolo_conv_1[0][0]                
                                                                 yolo_darknet[0][0]               
__________________________________________________________________________________________________
yolo_output_0 (Functional)      (None, None, None, 3 5140888     yolo_conv_0[0][0]                
__________________________________________________________________________________________________
yolo_output_1 (Functional)      (None, None, None, 3 1391000     yolo_conv_1[0][0]                
__________________________________________________________________________________________________
yolo_output_2 (Functional)      (None, None, None, 3 400792      yolo_conv_2[0][0]                
==================================================================================================
Total params: 62,276,392
Trainable params: 62,223,784
Non-trainable params: 52,608
__________________________________________________________________________________________________
````

![model](https://user-images.githubusercontent.com/376818/126827201-0b298279-0247-4746-91b5-a61cbbf1f575.png)

I'm loading the model simply with this code:
` KerasModelImport.importKerasModelAndWeights("./yolo_v3_fruits360_2021_07_23_4/yolo_model_export.h5", false);` 

The error message looks like this:

```
org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Functional. Please file an issue at https://github.com/eclipse/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:337)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:225)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:167)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:99)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:311)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:150)
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-M1.1
* Platform information (OS, etc): macOS 11.4 (20F71) 
* CUDA version, if used: not used
* NVIDIA driver version, if in use: not used

* TensorFlow Version (the saved model was created with): 2.4.1 in compat mode

#### Additional Information
Logs and Gradle config
https://gist.github.com/marquies/9a9bf787232c5de513d2ba700ccc61a5

Thanks for help!

**Comment by agibsonccc** [comment]
@marquies do you mind  just giving me a direct reproducer + test input for the model? That could be a python script that saves the model or an h5 model + sample input.

**Comment by marquies** [comment]
Well, I don't mind, but it is not straight forward. I have a link to a kaggle notebook. It contains some parts of this project (https://github.com/zzh8829/yolov3-tf2) to create and train a YoloV3 net in TensorFlow2.

My project on kaggle -> https://www.kaggle.com/patricksteinert/prepare-and-train-fruits360-tf-object-detection

I can provide you a saved model and sample input as well: https://www.patricksteinert.de/stuff/yolov3-fruits360.zip

Please let me know, if I can provide you more stuff to reproduce.

**Comment by agibsonccc** [comment]
@marquies  generally just a saved model and a sample ndarray is all I would need. The input would be something like:
```python

model = keras.models.load_model('path/to/location')
input = np.ones(..)
model.predict(input)
```
I can try to reverse engineer that from your notebook, but generally it's helpful when I just have a sample ndarray to look at. The reason for this is so I don't have to dissect your data pipeline just to get to what we both really want: me seeing a stack trace.
I also use it for validating that the model processed the input correctly before committing a fix.

**Comment by marquies** [comment]
So I guess this is what you are looking for: https://github.com/marquies/recognizer2/blob/master/src/main/resources/inference.py

Side note: it's really wicked, not even tensorflow.keras can load the file. In the jupyter notebook itself, I get this error:
```
yolo.save('/kaggle/working/yolo_model_export.h5', save_format='h5' )
my_model_from_file = keras.models.load_model('/kaggle/working/yolo_model_export.h5')

....

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py in <lambda>(x)
    243         return Model(inputs, (output_0, output_1, output_2), name='yolov3')
    244 
--> 245     boxes_0 = Lambda(lambda x: yolo_boxes(x, anchors[masks[0]], classes),
    246                      name='yolo_boxes_0')(output_0)
    247     boxes_1 = Lambda(lambda x: yolo_boxes(x, anchors[masks[1]], classes),

TypeError: list indices must be integers or slices, not list
```

On my local machine:

```
...
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 783, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)
```

**Comment by agibsonccc** [comment]
Not quite... I would need whatever this is: https://github.com/marquies/recognizer2/blob/master/src/main/resources/inference.py#L91

**Comment by marquies** [comment]
hey, sorry for the delay. Unfortunately, it is a quite big file. I have uploaded it here: https://www.patricksteinert.de/stuff/yolov3-fruits360.zip
But I have used the before mentioned and linked hdf5 file 
`            model = KerasModelImport.importKerasModelAndWeights("yolo_v3_fruits360_2021_07_23_4/yolo_model_export.h5", false);
`

**Comment by marcopaglio** [comment]
I encountered the same error, i.e. `org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Functional. Please file an issue at https://github.com/eclipse/deeplearning4j/issues.`, when importing the following Keras model:
```
base_model = VGG16(include_top=False, input_shape=(32, 32, 3), weights=None)
model = models.Sequential([
        base_model,
        layers.Flatten(),
        layers.Dense(4096, activation='relu'),
        layers.Dense(4096, activation='relu'),
        layers.Dense(num_classes, activation='softmax')
    ])
model.save('vgg16.h5')
```
through:
```
MultiLayerNetwork importedVgg16 = KerasModelImport.importKerasSequentialModelAndWeights("vgg16.h5", false);
```
The Boolean argument of the import function is irrelevant as is the version of Keras.


#### Workaround

In my (simple) case, I solved the error by changing the Python code:
```
base_model = VGG16(include_top=False, input_shape=(32, 32, 3), weights=None)
model = models.Sequential()
    
for layer in base_model.layers:
    model.add(layer)
    
model.add(layers.Flatten())
model.add(layers.Dense(4096, activation='relu'))
model.add(layers.Dense(4096, activation='relu'))
model.add(layers.Dense(num_classes, activation='softmax'))
```
This mode is only DL4J-oriented because I would never write Tensorflow/Keras code in this way. So, it would be appreciated if it is fixed in the future.

#### Version Information

- Deeplearning4j version: 1.0.0-M2.1
- Platform information: Windows 11 Home (Build 26100.4652)

**Comment by agibsonccc** [comment]
@marquies what version of keras is this?

**Comment by agibsonccc** [comment]
Closing — this has been addressed in the upcoming release (branch ag_new_release_updates_2). The relevant code has been rewritten/fixed.
