### ISSUE TITLE
FeedForwardToCnnPreProcessor columns() call is not valid

### ISSUE THREAD

**Issue by ndr09** [deeplearning4j/deeplearning4j#9405]
Good day, 

#### Issue Description

I'm trying to built a convolutional autoencoder. The encoder is composed by the alternation of convolution and pooling and it ends with a dense layer. It starts with a matrix of double of 200x39 and it ends with a vector of size 4. The decoder is specular: it starts with a dense layer (from 4 to 9 features) and recompose the matrix through unpooling and deconvolution layers. The problem is that the first layer of the decoder gives in input to the next layer a _FeedForwardInput_, while the next layer, which is a _Upsampling2D_ expected to receive CNN input type (returning the following error: `Invalid input for Upsampling 2D layer (layer name="unpool1"): Expected CNN input, got InputTypeFeedForward(9)`). Therefore I add the the network configuration  the following line:
`.inputPreProcessor("unpool1",new FeedForwardToCnnPreProcessor(9,1,1))`.

In this way I solved the first error, however it gives me the following error:
`java.lang.IllegalStateException: Rank is [3]; columns() call is not valid
	at org.nd4j.linalg.api.ndarray.BaseNDArray.columns(BaseNDArray.java:4036)
	at org.deeplearning4j.nn.conf.preprocessor.FeedForwardToCnnPreProcessor.preProcess(FeedForwardToCnnPreProcessor.java:76)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.applyPreprocessorAndSetInput(LayerVertex.java:117)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.setInput(LayerVertex.java:169)
	at org.deeplearning4j.nn.graph.ComputationGraph.ffToLayerActivationsDetached(ComputationGraph.java:2027)
	at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1579)
	at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1522)`
Is this due a wrong assumption by me? I don't understand why _FeedForwardToCnnPreProcessor_ should not expect to have 3d matrix (width\*height\*channels).

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-M1
* Platform information: windows 10 pro Versione	10.0.19042 Build 19042, Java 14.0.1

Thanks for the support,
Andrea

**Comment by agibsonccc** [comment]
@ndr09 do you have a reproducer for me? Happy to fix if I can get a simple configuration that does this with sample input.

**Comment by agibsonccc** [comment]
@ndr09 figured I would ask 1 more time. We're getting ready to do a release and are trying to close off issues people have run in otherwise, I'll close this due to lack of response. Thanks!

**Comment by agibsonccc** [comment]
Closing due to inactivity
