### ISSUE TITLE
some errors happened when I import  TF  PB file 

### ISSUE THREAD

**Issue by benbenwt** [deeplearning4j/deeplearning4j#9419]
#### Issue Description

this is my code:
```
File modelFile=new File("")
SameDiff sd = SameDiff.importFrozenTF(modelFile);
```

the following is error log:
```
Exception in thread "main" java.lang.UnsupportedOperationException: Cannot get array for ARRAY type SDVariable - use SDVariable.exec or SameDiff.output instead
	at org.nd4j.autodiff.samediff.SameDiff.getArrForVarName(SameDiff.java:747)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.initFunctionFromProperties(TFGraphMapper.java:826)
	at org.nd4j.linalg.api.ops.impl.shape.Gather.initFromTensorFlow(Gather.java:99)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:356)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:141)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:87)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:73)
	at org.nd4j.autodiff.samediff.SameDiff.importFrozenTF(SameDiff.java:5751)
	at org.deeplearning4j.examples.mine.learn01.ImportPBFile.main(ImportPBFile.java:12)
```
#### Version Information

Please indicate relevant versions, including, if relevant:
 <dl4j-master.version>1.0.0-M1.1</dl4j-master.version>
I work on windows10 

#### Additional Information

The model is downloaded from https://github.com/google-research/bert,and this is  my script to tranform it into PB File.

python script :
```
import tensorflow as tf
from tensorflow.python.tools import freeze_graph
from tensorflow.tools.graph_transforms import TransformGraph
from tensorflow.summary import FileWriter
import argparse

def load_graph(checkpoint_path, mb, seq_len):
          init_all_op = tf.initialize_all_variables()
          graph2 = tf.Graph()
          with graph2.as_default():
              with tf.Session(graph=graph2) as sess:
                  saver = tf.train.import_meta_graph(checkpoint_path + '.meta')
                  saver.restore(sess, checkpoint_path)
                  print("Restored structure...")
                  saver.restore(sess, checkpoint_path)
                  print("Restored params...")
                  graph_def = graph2.as_graph_def()
                  FileWriter("__tb-ch", graph2)
                  input_names = ["Placeholder", "Placeholder_1", "Placeholder_2"]
                  output_names = ["bert/pooler/dense/Tanh"]
                  transforms = ['strip_unused_nodes(type=int32, shape="' + str(mb) + ',' + str(seq_len) + '")']
                  graph2 = TransformGraph(graph2.as_graph_def(), inputs=input_names, outputs=output_names, transforms=transforms)
                  return graph2


parser = argparse.ArgumentParser(description='Freeze BERT model')
parser.add_argument('--minibatch', help='Minibatch size', default=4)
parser.add_argument('--seq_length', help='Sequence length', default=128)
parser.add_argument('--input_dir', help='Input directory for model', default="D:/chinese_L-12_H-768_A-12/chinese_L-12_H-768_A-12/")
parser.add_argument('--ckpt', help='Checkpoint filename in input dir', default="bert_model.ckpt")

args = parser.parse_args()
mb = int(args.minibatch)
seq_len = int(args.seq_length)

print("minibatch: ", mb)
print("seq_length: ", seq_len)
print("input_dir: ", args.input_dir)
print("checkpoint: ", args.ckpt)

dirIn = args.input_dir
dirOut = dirIn + "frozen/"
ckpt = args.ckpt
graph = load_graph(dirIn + ckpt, mb, seq_len)
txtName = "bert_export_mb" + str(mb) + "_len" + str(seq_len) + ".pb.txt"
txtPath = dirOut + txtName
tf.train.write_graph(graph, dirOut, txtName, True)


output_graph = dirOut + "bert_frozen_mb" + str(mb) + "_len" + str(seq_len) + ".pb"
print("Freezing Graph...")
freeze_graph.freeze_graph(
    input_graph=txtPath,
    input_checkpoint=dirIn+ckpt,
    input_saver="",
    output_graph=output_graph,
    input_binary=False,
    output_node_names="bert/pooler/dense/Tanh",     #This is log(prob(x))
    # output_node_names="loss/Softmax",     #This is log(prob(x))
    restore_op_name="save/restore_all",
    filename_tensor_name="save/Const:0",
    clear_devices=True,
    initializer_nodes="")
print("Freezing graph complete...")
```

**Comment by agibsonccc** [comment]
@benbenwt See: https://community.konduit.ai/t/unsupportedoperationexception-while-training/1546 closing this since you also have a forum thread.
