### ISSUE TITLE
Glove model with scala exception

### ISSUE THREAD

**Issue by huangjiakun1991** [deeplearning4j/deeplearning4j#942]
Here is my glove example:
    File file = new File("raw_sentences.txt");
    SentenceIterator iter = new LineSentenceIterator(file);
    iter.setPreProcessor(new SentencePreProcessor() {
      @Override
      public String preProcess(String s) {
        return s;
      }
    });
    final EndingPreProcessor preProcessor = new EndingPreProcessor();
    TokenizerFactory tokenizer = new DefaultTokenizerFactory();
    tokenizer.setTokenPreProcessor(new TokenPreProcess() {
      @Override
      public String preProcess(String token) {
        token = token.toLowerCase();
        String base = preProcessor.preProcess(token);
        base = base.replaceAll("\\d", "d");
        if (base.endsWith("ly") || base.endsWith("ing"))
          System.out.println();
        return base;
      }
    });
    Glove vec = new Glove.Builder().iterate(iter).symmetric(true).shuffle(true)
      .minWordFrequency(1).iterations(10).learningRate(0.1)
      .layerSize(300)
      .build();

    vec.fit();

    Collection<String> words = vec.wordsNearest("day", 10);
    Iterator i = words.iterator();
    while(i.hasNext()){
      System.out.println(i.next());
    }

However, it doesn't work properly:
Exception in thread "main" java.lang.NoSuchMethodError: scala.collection.immutable.HashSet$.empty()Lscala/collection/immutable/HashSet;
	at akka.actor.ActorCell$.<init>(ActorCell.scala:336)
	at akka.actor.ActorCell$.<clinit>(ActorCell.scala)
	at akka.actor.RootActorPath.$div(ActorPath.scala:159)
	at akka.actor.LocalActorRefProvider.<init>(ActorRefProvider.scala:464)
	at akka.remote.RemoteActorRefProvider.<init>(RemoteActorRefProvider.scala:124)
	at akka.cluster.ClusterActorRefProvider.<init>(ClusterActorRefProvider.scala:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
	at scala.util.Try$.apply(Try.scala:192)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
	at scala.util.Success.flatMap(Try.scala:231)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
	at akka.actor.ActorSystemImpl.liftedTree1$1(ActorSystem.scala:584)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:577)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:141)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:108)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:99)
	at akka.actor.ActorSystem$.create(ActorSystem.scala:47)
	at akka.actor.ActorSystem.create(ActorSystem.scala)
	at org.deeplearning4j.bagofwords.vectorizer.BaseTextVectorizer.fit(BaseTextVectorizer.java:110)
	at org.deeplearning4j.models.glove.Glove.fit(Glove.java:123)

is it an issue and I'm doing something wrong ?

**Comment by raver119** [comment]
I'm afraid that GloVe implementation requires the same changes, that were already applied to W2V and D2V.

**Comment by agibsonccc** [comment]
This already happened.
