### ISSUE TITLE
Some error happened when I importFrozenTF by SameDiffI 

### ISSUE THREAD

**Issue by benbenwt** [deeplearning4j/deeplearning4j#9420]
#### Issue Description

when I execute " package org.deeplearning4j.modelimportexamples.tf.advanced.bert.BertInferenceExample",some error happened.

the following is error log:
```
Exception in thread "main" java.lang.UnsupportedOperationException: Cannot get array for ARRAY type SDVariable - use SDVariable.exec or SameDiff.output instead
	at org.nd4j.autodiff.samediff.SameDiff.getArrForVarName(SameDiff.java:747)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.initFunctionFromProperties(TFGraphMapper.java:826)
	at org.nd4j.linalg.api.ops.impl.shape.Gather.initFromTensorFlow(Gather.java:99)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:356)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:141)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:87)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:73)
	at org.nd4j.autodiff.samediff.SameDiff.importFrozenTF(SameDiff.java:5751)
	at org.deeplearning4j.examples.mine.learn01.ImportPBFile.main(ImportPBFile.java:12)
```
After solving this,I got a new error:
```
Exception in thread "main" java.lang.IllegalArgumentException: No import process defined for IteratorV2
	at org.nd4j.samediff.frameworkimport.registry.OpMappingRegistry.lookupOpMappingProcess(OpMappingRegistry.kt:129)
	at org.nd4j.samediff.frameworkimport.tensorflow.ir.TensorflowIRNode.<init>(TensorflowIRNode.kt:45)
	at org.nd4j.samediff.frameworkimport.tensorflow.ir.TensorflowIRGraph.nodeList(TensorflowIRGraph.kt:78)
	at org.nd4j.samediff.frameworkimport.ir.IRFunctionsKt.importInfoForEachNodeInGraph(IRFunctions.kt:49)
	at org.nd4j.samediff.frameworkimport.tensorflow.ir.TensorflowIRGraph.importInfoForEachNode(TensorflowIRGraph.kt:152)
	at org.nd4j.samediff.frameworkimport.ImportGraph.importGraph(ImportGraph.kt:227)
	at org.nd4j.samediff.frameworkimport.tensorflow.importer.TensorflowFrameworkImporter.importFromGraph(TensorflowFrameworkImporter.kt:58)
	at org.nd4j.samediff.frameworkimport.tensorflow.importer.TensorflowFrameworkImporter.runImport(TensorflowFrameworkImporter.kt:64)
	at org.deeplearning4j.modelimportexamples.tf.advanced.bert.BertInferenceExample.main(BertInferenceExample.java:81)
```
this my revised code:
```
 File frozenBertPB = new File("D:\\deeplearning4j-examples\\mydownload\\bert_mrpc_frozen_v1", "bert_mrpc_frozen.pb");
        Map<String, TFImportOverride> iterToPlaceholderOverride = overrideIteratorsToPlaceholders();
        TFOpImportFilter filterNodeIterV2 = filterNodeByName("IteratorV2");
        TensorflowFrameworkImporter tensorflowFrameworkImporter = new TensorflowFrameworkImporter();
        SameDiff sd = tensorflowFrameworkImporter.runImport(frozenBertPB.getAbsolutePath(), Collections.emptyMap());
```

#### Version Information
<dl4j-master.version>1.0.0-M1.1</dl4j-master.version>
windows10
#### Additional Information

The model is PB file downloaded from https://dl4jdata.blob.core.windows.net/testresources/bert_mrpc_frozen_v1.zip

this the forum link:
https://community.konduit.ai/t/some-error-happened-when-i-importfrozentf-by-samediffi/1552

**Comment by agibsonccc** [comment]
@behrisch found out what happened. The old TF import example actually used to filter those ops out: https://github.com/eclipse/deeplearning4j-examples/blob/master/tensorflow-keras-import-examples/src/main/java/org/deeplearning4j/modelimportexamples/tf/advanced/bert/BertInferenceExample.java

The new import now has those ops as no ops so we can just skip those when we see them as we would in other places. 

I have a pull request up addressing this.  This is a bit WIP yet, but I also have the file for this as well. You may find that download here: https://drive.google.com/file/d/15G_VBXNbMVOgbymhKxL259MoQBHqEjC9/view?usp=sharing

I'll polish this tomorrow otherwise you're welcome to give this a try and give me feedback. Thanks! Sorry this took a bit.

**Comment by benbenwt** [comment]
Thank you very much for your help!Sorry to reply now, because work was delayed for some reasons.So,All I need to do is pull the code  in maser branch and  build it.Then,I should test the new code with the model you provided.Is that right？

**Comment by benbenwt** [comment]
I have browsed the deeplearning-example and import the model by  '"SameDiff.fromFlatFile".It looks like the problem has been solved, thank you for your help.
