### ISSUE TITLE
Exception not finding some CustomOps since last snapshot-update

### ISSUE THREAD

**Issue by cyberbeat** [deeplearning4j/deeplearning4j#9497]
```
Caused by: org.nd4j.linalg.exception.ND4JIllegalStateException: Op name concat - no output arrays were provided and calculateOutputShape failed to execute
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:1862)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6568)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.concat(JCublasNDArrayFactory.java:358)
	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:4857)
	at org.deeplearning4j.nn.graph.vertex.impl.MergeVertex.doForward(MergeVertex.java:112)
	at org.deeplearning4j.nn.graph.ComputationGraph.ffToLayerActivationsInWS(ComputationGraph.java:2135)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1372)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1341)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:174)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:61)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1165)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1115)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1082)
...
Caused by: org.nd4j.linalg.exception.ND4JIllegalStateException: Op name concat is missing!
	at org.nd4j.linalg.api.ops.DynamicCustomOp.opHash(DynamicCustomOp.java:279)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.calculateOutputShape(CudaExecutioner.java:1736)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.calculateOutputShape(CudaExecutioner.java:1727)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:1853)
	... 22 more

More from debugging, the map with customOps is empty in opHash:

Thread [pool-2-thread-32] (Suspended)	
	owns: ComputationGraph  (id=74)	
	Concat(DynamicCustomOp).opHash() line: 276	
	CudaExecutioner.calculateOutputShape(CustomOp, OpContext) line: 1736	
	CudaExecutioner.calculateOutputShape(CustomOp) line: 1727	
	CudaExecutioner.exec(CustomOp) line: 1853	
	Nd4j.exec(CustomOp) line: 6568	
	JCublasNDArrayFactory.concat(int, INDArray...) line: 358	
	Nd4j.concat(int, INDArray...) line: 4857	
	MergeVertex.doForward(boolean, LayerWorkspaceMgr) line: 112	
	ComputationGraph.ffToLayerActivationsInWS(boolean, int, int[], FwdPassType, boolean, INDArray[], INDArray[], INDArray[], boolean) line: 2135	
	ComputationGraph.computeGradientAndScore() line: 1372	
	ComputationGraph.computeGradientAndScore(LayerWorkspaceMgr) line: 1341	
	StochasticGradientDescent(BaseOptimizer).gradientAndScore(LayerWorkspaceMgr) line: 174	
	StochasticGradientDescent.optimize(LayerWorkspaceMgr) line: 61	
	Solver.optimize(LayerWorkspaceMgr) line: 52	
	ComputationGraph.fitHelper(INDArray[], INDArray[], INDArray[], INDArray[]) line: 1165	
	ComputationGraph.fit(INDArray[], INDArray[], INDArray[], INDArray[]) line: 1115	
	ComputationGraph.fit(MultiDataSetIterator) line: 1082	
...

```

**Comment by agibsonccc** [comment]
@cyberbeat can you confirm this is backend specific for you? I can't reproduce this with cpu. I'll try GPU in a bit.

**Comment by cyberbeat** [comment]
The problem is, I now switched to the last stable M1.1 release with my project, because of the many problems with snapshots. Sorry.

**Comment by agibsonccc** [comment]
@cyberbeat thanks for confirming. We're doing test QA now and are prepping for the next release here in the next week or so.  If you have any issues in the mean time let me know.

**Comment by agibsonccc** [comment]
Closing this as this should be resolved.
