### ISSUE TITLE
 NeuralNetPlotterIterationListener does not work with MultiLayerNetwork

### ISSUE THREAD

**Issue by Ingwar** [deeplearning4j/deeplearning4j#958]
Hello, 

I am trying to use `NeuralnetPlotIterationListener` in a following way:
```scala
model.setListeners(new ScoreIterationListener(), new NeuralNetPlotterIterationListener(10, true))
```

I got this error:
```
16:43:13.334 [main] INFO  o.d.plot.NeuralNetPlotter - Rendering histogram graphs for data analysis...
16:43:37.856 [main] INFO  o.d.plot.NeuralNetPlotter - Std out [Loading matrix 0_W, , Loading matrix 0_b, , Loading matrix 1_W, , Loading matrix 1_b, , Loading matrix 3_W, , Loading matrix 3_b, , Loading matrix 4_W, , Loading matrix 4_b, , Loading matrix 6_W, , Loading matrix 6_b, , Loading matrix 7_W, , Loading matrix 7_b, , Loading matrix 0_W-gradient, , Loading matrix 0_b-gradient, , Loading matrix 1_W-gradient, , Loading matrix 1_b-gradient, , Loading matrix 3_W-gradient, , Loading matrix 3_b-gradient, , Loading matrix 4_W-gradient, , Loading matrix 4_b-gradient, , Loading matrix 6_W-gradient, , Loading matrix 6_b-gradient, , Loading matrix 7_W-gradient, , Loading matrix 7_b-gradient, ]
16:43:37.856 [main] ERROR o.d.plot.NeuralNetPlotter - Std error [/usr/lib/python2.7/dist-packages/matplotlib/__init__.py:874: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.,   warnings.warn(self.msg_depr % (key, alt_key))]
Exception in thread "main" java.lang.UnsupportedOperationException
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationMean(MultiLayerNetwork.java:410)
	at org.deeplearning4j.plot.NeuralNetPlotter.plotActivations(NeuralNetPlotter.java:275)
	at org.deeplearning4j.plot.NeuralNetPlotter.plotNetworkGradient(NeuralNetPlotter.java:326)
	at org.deeplearning4j.plot.iterationlistener.NeuralNetPlotterIterationListener.iterationDone(NeuralNetPlotterIterationListener.java:111)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:193)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1452)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1482)
	at
```

The same thing is also happened with the `GradientPlotterIterationListener`

**Comment by agibsonccc** [comment]
Neither of those iterationlisteners are supported anymore. Please move to deeplearning4j-ui with the histogramiterationlistener.

**Comment by Ingwar** [comment]
Thank you.  I think that marking them as deprecated or removing could help to avoid such confusion in future. If you agree with that, I, probably, will make a PR with deprecation in near future.
