### ISSUE TITLE
NPE in UIListener

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#9583]
#### Issue Description

Please describe our issue, along with:
- expected behavior
Training successfully

- encountered behavior
NPE

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version SNAPSHOT
* Platform information (OS, etc) Win7
* CUDA version, if used No
* NVIDIA driver version, if in use No

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)
java.lang.NullPointerException
	at org.nd4j.autodiff.listeners.impl.UIListener.opExecution(UIListener.java:427)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:249)
	at org.nd4j.autodiff.samediff.internal.TrainingSession.getOutputs(TrainingSession.java:161)
	at org.nd4j.autodiff.samediff.internal.TrainingSession.getOutputs(TrainingSession.java:43)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:387)
	at org.nd4j.autodiff.samediff.internal.TrainingSession.trainingIteration(TrainingSession.java:127)
	at org.nd4j.autodiff.samediff.SameDiff.fitHelper(SameDiff.java:1819)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1675)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1615)

            if(relevantOpsForEval == null){
                //Build list for quick lookups to know if we should do anything for this op
                relevantOpsForEval = new HashSet<>();
                for (Pair<String, Integer> p : trainEvalMetrics.keySet()) {
                    Variable v = sd.getVariables().get(p.getFirst());
                    String opName = v.getOutputOfOp();//java.lang.NullPointerException
                    Preconditions.checkState(opName != null, "Cannot evaluate on variable of type %s - variable name: \"%s\"",
                            v.getVariable().getVariableType(), opName);
                    relevantOpsForEval.add(v.getOutputOfOp());
                }
            }

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by SidneyLann** [comment]
Same code run successfully in beta7.

**Comment by SidneyLann** [comment]
sameDiff.setOutputs("out");

Solved by added this line.
