### ISSUE TITLE
Implement Einsum op

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#9596]
#### Issue Description
Einsum is used in lots of operations and is needed for both tensorflow and onnx import.

Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* Platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by SidneyLann** [comment]
Need Einsum to implement GAT.

**Comment by genolve** [comment]
And also add to ONNX please 
```
Exception in thread "main" java.lang.IllegalArgumentException: No import process defined for Einsum
	at org.nd4j.samediff.frameworkimport.registry.OpMappingRegistry.lookupOpMappingProcess(OpMappingRegistry.kt:130)
	at org.nd4j.samediff.frameworkimport.onnx.ir.OnnxIRNode.<init>(OnnxIRNode.kt:48)
	at org.nd4j.samediff.frameworkimport.onnx.ir.OnnxIRGraph.nodeList(OnnxIRGraph.kt:195)
	at org.nd4j.samediff.frameworkimport.onnx.ir.OnnxIRGraph.<init>(OnnxIRGraph.kt:74)
	at org.nd4j.samediff.frameworkimport.onnx.importer.OnnxFrameworkImporter.loadGraph(OnnxFrameworkImporter.kt:53)
	at org.nd4j.samediff.frameworkimport.onnx.importer.OnnxFrameworkImporter.runImport(OnnxFrameworkImporter.kt:57)
	at org.deeplearning4j.modelimportexamples.onnx.OnnxImportSave.main(OnnxImportSave.java:64)
```

**Comment by agibsonccc** [comment]
Closing — this has been addressed in the upcoming release (branch ag_new_release_updates_2). The relevant code has been rewritten/fixed.
