### ISSUE TITLE
Cannot instantiate Cifar10DataSetIterator on Android

### ISSUE THREAD

**Issue by thangnbn** [deeplearning4j/deeplearning4j#9652]
#### Issue Description

I tried to instantiate the `Cifar10DataSetIterator` but received the below exception. I expected it to just return me the iterator normally like if it is run on a Linux or Windows machine.

```
Caused by: java.io.FileNotFoundException: /.deeplearning4j/data/cifar10/labels.txt: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:575)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
        at org.nd4j.common.util.ArchiveUtils.unzipFileTo(ArchiveUtils.java:109)
        at org.deeplearning4j.datasets.fetchers.CacheableExtractableDataSetFetcher.downloadAndExtract(CacheableExtractableDataSetFetcher.java:88)
        at org.deeplearning4j.datasets.fetchers.CacheableExtractableDataSetFetcher.downloadAndExtract(CacheableExtractableDataSetFetcher.java:41)
        at org.deeplearning4j.datasets.fetchers.Cifar10Fetcher.getRecordReader(Cifar10Fetcher.java:63)
        at org.deeplearning4j.datasets.iterator.impl.Cifar10DataSetIterator.<init>(Cifar10DataSetIterator.java:88) 
```

#### Version Information

- Deeplearning4j version: 1.0.0-M2
- Platform: Android API 32

#### Contributing

I think the error might be due to some unexpected return value of the `getBaseDirectory` method in `org.deeplearning4j.common.resources.DL4JResources` class when running on Android. When I try to instantiate `Cifar10DataSetIterator` on Windows, `getBaseDirectory` returns me my user home directory. I think on Android there is no concept of "user home directory", so it leads to unexpected behavior.

**Comment by agibsonccc** [comment]
@bnnthang those iterators weren't really meant for use on android. Could you clarify your use case a bit?

**Comment by thangnbn** [comment]
I am building a testbed for federated learning. One target is to offload the training to Android devices. That's why I want to instantiate `Cifar10DataSetIterator` on Android.

**Comment by agibsonccc** [comment]
@bnnthang I would recommend maybe pre creating the ndarrays on a windows machine then if you want them running on android just save the ndarrays. If you want to work with images you can use NativeImageLoader (which uses opencv underneath and is well tested on android)

I'm closing this as those iterators were never really built for mobile and there's plenty of workarounds for them in the mean time. If you want help with the pre save part feel free to post over on the community forums: https://community.konduit.ai/
