### ISSUE TITLE
ModelSerializer throws an  exception when Normalizer is saved as well

### ISSUE THREAD

**Issue by thhart** [deeplearning4j/deeplearning4j#9653]
#### Issue Description

When I include the normalizer in ModelSerializer.writeModel it throws an exception. IMHO the NormalizerSerializer closes the stream and then ModelSerializer tries it afterwards again.
NormalizerSerializer uses StandardizeSerializerStrategy.write which closes the dos.

`ModelSerializer.writeModel(model, stream, true, normalizer);
`

<pre>
java.io.IOException: flush() failed: stream is closed
	at org.apache.commons.io.output.ClosedOutputStream.flush(ClosedOutputStream.java:56)
	at org.apache.commons.io.output.ProxyOutputStream.flush(ProxyOutputStream.java:105)
	at java.base/java.util.zip.DeflaterOutputStream.flush(DeflaterOutputStream.java:281)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:143)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:191)
	at org.deeplearning4j.util.ModelSerializer.writeModel(ModelSerializer.java:195)
	at org.deeplearning4j.examples.quickstart.modeling.feedforward.classification.RdClassifier.main(RdClassifier.java:239)
	Suppressed: java.io.IOException: flush() failed: stream is closed
		at org.apache.commons.io.output.ClosedOutputStream.flush(ClosedOutputStream.java:56)
		at org.apache.commons.io.output.ProxyOutputStream.flush(ProxyOutputStream.java:105)
		at java.base/java.util.zip.DeflaterOutputStream.flush(DeflaterOutputStream.java:281)
		at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:143)
		at java.base/java.io.DataOutputStream.flush(DataOutputStream.java:128)
		at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
		... 2 more
</pre>

#### Version Information

1.0.0-M2

**Comment by agibsonccc** [comment]
Closing this. We have a test case for this already: https://github.com/eclipse/deeplearning4j/blob/6d2cd99ade85ccbd5f9cd165c7db27c56e9856e7/platform-tests/src/test/java/org/eclipse/deeplearning4j/dl4jcore/util/ModelSerializerTest.java#L161
In summary:
```java
  DataSet dataSet = trivialDataSet();
        NormalizerStandardize norm = new NormalizerStandardize();
        norm.fit(dataSet);
        ComputationGraph cg = simpleComputationGraph();
        cg.init();
        File tempFile = tempDir.toFile();
        ModelSerializer.writeModel(cg, tempFile, true);
        ModelSerializer.addNormalizerToModel(tempFile, norm);
        FileInputStream fis = new FileInputStream(tempFile);
        NormalizerStandardize restored = ModelSerializer.restoreNormalizerFromInputStream(fis);
        assertNotEquals(null, restored);
        DataSet dataSet2 = dataSet.copy();
        norm.preProcess(dataSet2);
        assertNotEquals(dataSet.getFeatures(), dataSet2.getFeatures());
        restored.revert(dataSet2);
        assertEquals(dataSet.getFeatures(), dataSet2.getFeatures());
```

Save the model then add the normalizer to it.
