### ISSUE TITLE
Can't infer bert model

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#9661]
[main] INFO org.nd4j.autodiff.samediff.SameDiff - Creating getInferenceFactory().create for thread 1
Error at [D:/a/deeplearning4j/deeplearning4j/libnd4j/include/ops/declarable/generic/parity_ops/onehot.cpp:87:0]:
OneHot: depth must be positive value
[main] ERROR org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner - Failed to calculate output shapes for op onehot. Attempted to execute with 4 inputs, 0 outputs, 2 targs, 2 iargs, 0 bargs and 0 dargs. Inputs: [(INT,[128],c), (INT,[],c), (FLOAT,[],c), (FLOAT,[],c)]. Input var names: [bert/embeddings/Reshape_1, bert/embeddings/one_hot/depth, bert/embeddings/one_hot/on_value, bert/embeddings/one_hot/off_value]. Output var names: [bert/embeddings/one_hot] - Please see above message (printed out from c++) for a possible cause of error.
java.lang.RuntimeException: Op onehot with name bert/embeddings/one_hot failed to execute. Here is the error from c++: Op validation failed
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.calculateOutputShape(NativeOpExecutioner.java:1672)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.calculateOutputShape(DynamicCustomOp.java:687)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:880)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getAndParameterizeOp(InferenceSession.java:60)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:390)
	at org.nd4j.autodiff.samediff.SameDiff.directExecHelper(SameDiff.java:2754)
	at org.nd4j.autodiff.samediff.SameDiff.batchOutputHelper(SameDiff.java:2722)
	at org.nd4j.autodiff.samediff.SameDiff.output(SameDiff.java:2697)
	at org.nd4j.autodiff.samediff.config.BatchOutputConfig.output(BatchOutputConfig.java:142)
	at org.nd4j.autodiff.samediff.SameDiff.output(SameDiff.java:2683)

**Comment by SidneyLann** [comment]
Reproduced project had sent by email, please check email, thanks.

**Comment by agibsonccc** [comment]
@SidneyLann Closing this as this is just similar to other issues you've already posted. I've reproduced your errors in your project but it was inconsistent at best. You appear to have 2 models in here. Could you clarify what the input data should be for each? Please post more on your older issues.

**Comment by SidneyLann** [comment]
1. This issue is different from other issues. other issues can get output form BERT model but this one can't.
2. The first model is original BERT model, it's output INDarray is the input of my own model like sd.output(placeholders, "bert/encoder/Reshape_13").get("bert/encoder/Reshape_13");
3. The second model is my own model.
4. The 2 models are  work together well in beta7.

**Comment by SidneyLann** [comment]
Sorry, just mistake to use old import framework!

**Comment by agibsonccc** [comment]
@SidneyLann let me get some snapshot builds up for you. I merged fixes for both of these things but would appreciate you looking at the results.
