### ISSUE TITLE
Can't train samediff model when reloaded

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#9744]
java.lang.NullPointerException: Cannot load from object array because "inputsForOp" is null
at org.nd4j.linalg.api.ops.impl.layers.recurrent.LSTMLayer.configureWithSameDiff(LSTMLayer.java:210)
at org.nd4j.autodiff.samediff.SameDiff.fromFlatBuffers(SameDiff.java:5503)
at org.nd4j.autodiff.samediff.SameDiff.fromFlatFile(SameDiff.java:5359)
at org.nd4j.autodiff.samediff.SameDiff.load(SameDiff.java:5250)
at org.nd4j.autodiff.listeners.checkpoint.CheckpointListener.loadCheckpoint(CheckpointListener.java:407)
at org.nd4j.autodiff.listeners.checkpoint.CheckpointListener.loadLastCheckpoint(CheckpointListener.java:417)

**Comment by SidneyLann** [comment]
#9145 mark this issue as fixed, but the exception still exists in SNAPSHOT.

**Comment by agibsonccc** [comment]
@SidneyLann could you give me a reproducer please? This means that something is missing that probably shouldn't be.

**Comment by agibsonccc** [comment]
@SidneyLann I found out what it was. For some reason the fix was reverted. Great catch! This will be fixed in a PR we'll merge in a bit.
