### ISSUE TITLE
ND4J is probably missing dependencies

### ISSUE THREAD

**Issue by norhu1130** [deeplearning4j/deeplearning4j#9746]
#### Issue Description
When I use Minecraft's plug-in, I get an error like this.
It is an Arm64 environment and I am using java.
I'm not a developer, I'm a user.
I asked the developer, but there is no answer, so please leave it here.
I'm sorry.

```[12:48:45] [Server thread/ERROR]: Error occurred while enabling AntiAura v12.14-2 (Is it up to date?)
[12:48:45] [Server thread/ERROR]: Suspected Plugins:
[12:48:45] [Server thread/ERROR]:       AntiAura{enabled,ver=12.14-2,path=plugins/AntiAura.jar}
[12:48:45] [Server thread/ERROR]:       AntiAura-ML{enabled,ver=1.0,path=plugins/AntiAura-ML.jar}
[12:48:45] [Server thread/ERROR]: Exception details below:
java.lang.ExceptionInInitializerError: null
        at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:53) ~[AntiAura-ML.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6185) ~[AntiAura-ML.jar:?]
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087) ~[AntiAura-ML.jar:?]
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201) ~[AntiAura-ML.jar:?]
        at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:188) ~[AntiAura-ML.jar:?]
        at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:138) ~[AntiAura-ML.jar:?]
        at joehot200.ah.b(ah.java:161) ~[AntiAura.jar:?]
        at joehot200.a9.a(a9.java:163) ~[AntiAura.jar:?]
        at joehot200.a9.d(a9.java:149) ~[AntiAura.jar:?]
        at joehot200.a9.c(a9.java:106) ~[AntiAura.jar:?]
        at joehot200.a9.<init>(a9.java:48) ~[AntiAura.jar:?]
        at joehot200.a_.<init>(a_.java:24) ~[AntiAura.jar:?]
        at joehot200.ah.a(ah.java:102) ~[AntiAura.jar:?]
        at joehot200.M.<init>(M.java:95) ~[AntiAura.jar:?]
        at joehot200.ah.<init>(ah.java:34) ~[AntiAura.jar:?]
        at joehot200.M.a(M.java:378) ~[AntiAura.jar:?]
        at joehot200.M.e(M.java:313) ~[AntiAura.jar:?]
        at joehot200.cq.a(cq.java:1185) ~[AntiAura.jar:?]
        at joehot200.AntiAura.onEnable(AntiAura.java:35) ~[AntiAura.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[nextpatina-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[nextpatina-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[nextpatina-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[nextpatina-1.19.1.jar:git-NextPatina-"23e03bf"]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[nextpatina-1.19.1.jar:git-NextPatina-"23e03bf"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:639) ~[nextpatina-1.19.1.jar:git-NextPatina-"23e03bf"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:425) ~[nextpatina-1.19.1.jar:git-NextPatina-"23e03bf"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[nextpatina-1.19.1.jar:git-NextPatina-"23e03bf"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1127) ~[nextpatina-1.19.1.jar:git-NextPatina-"23e03bf"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308) ~[nextpatina-1.19.1.jar:git-NextPatina-"23e03bf"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
        at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51) ~[AntiAura-ML.jar:?]
        at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19) ~[AntiAura-ML.jar:?]
        ... 37 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429) ~[?:?]
        at java.lang.Runtime.loadLibrary0(Runtime.java:818) ~[?:?]
        at java.lang.System.loadLibrary(System.java:1989) ~[?:?]
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976) ~[AntiAura-ML.jar:?]
        at org.bytedeco.javacpp.Loader.load(Loader.java:777) ~[AntiAura-ML.jar:?]
        at org.bytedeco.javacpp.Loader.load(Loader.java:684) ~[AntiAura-ML.jar:?]
        at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10) ~[AntiAura-ML.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bytedeco.javacpp.Loader.load(Loader.java:739) ~[AntiAura-ML.jar:?]
        at org.bytedeco.javacpp.Loader.load(Loader.java:684) ~[AntiAura-ML.jar:?]
        at org.nd4j.nativeblas.Nd4jCpu$NativeOps.<clinit>(Nd4jCpu.java:63) ~[AntiAura-ML.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:29) ~[AntiAura-ML.jar:?]
```
#### Version Information

* Deeplearning4j version : I don't know
* Platform information (OS, etc) : Ubuntu 22.04 Server

**Comment by norhu1130** [comment]
amd64 works well in a window environment

**Comment by agibsonccc** [comment]
@norhu1130 could you give me the minecraft plugin you are trying to use? I can try to figure out the information from that. If I had to guess it only has intel binaries for running the right code and you would need ARM.

**Comment by norhu1130** [comment]
> @norhu1130 could you give me the minecraft plugin you are trying to use? I can try to figure out the information from that. If I had to guess it only has intel binaries for running the right code and you would need ARM.

It's kind of hard because it's a premium plug-in.

**Comment by agibsonccc** [comment]
Where did you buy it? I am not asking for source code or anything just a way to contact the plugin author myself.

**Comment by norhu1130** [comment]
> Where did you buy it? I am not asking for source code or anything just a way to contact the plugin author myself.

https://www.spigotmc.org/resources/antiaura-%C2%BB-reliable-cheat-detection-%C2%BB-anti-cheat-plugin.1368/update?update=43601

**Comment by agibsonccc** [comment]
Thanks let me see what I can do. I've seen spigot popup before: https://community.konduit.ai/t/deeplearning4j-for-minecraft-plugins-doesnt-work-due-to-different-entry-point/1719

**Comment by agibsonccc** [comment]
@norhu1130 I've contacted the developers and will let you know when I hear back.  This error isn't really your fault. They just aren't bundling arm compatible code in their plugin.

**Comment by agibsonccc** [comment]
@norhu1130 I haven't heard back yet unfortunately. Feel free to direct message me on the forums: https://community.konduit.ai if you have any private files you want to send me. Maybe I can help you modify the jar files to include the right dependencies.

**Comment by agibsonccc** [comment]
@norhu1130 please have the plugin author contact me. I have reached out to spigot-mc and they said it should be the direct plugin author's responsibility. They're making money off of this and this should be a part of the product. Unfortunately there is no commercial engagement with the vendor to provide this so there's not much I can do. Feel free to show them this github issue if you would like. It should just be a small amount of packaging work on their part (maybe provide different jars for different platforms)

With that said I'm closing this.
