### ISSUE TITLE
ScatterUpdate throws exception

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9763]
#### Issue Description

- expected behavior: `scatterUpdate` should update the specified indices of an `INDArray`/`SDVariable`.
- encountered behavior:  `scatterUpdate` throws a `RuntimeException` caused by a validation error in LibND4J.

This code reproduces the error:
```
INDArray v1 = Nd4j.zeros(5);
INDArray v2 = new NDBase().scatterUpdate(v1, Nd4j.scalar(2), Nd4j.scalar(1f));
System.out.println(v2); // expected result: [0, 0, 1, 0, 0]
```
The same error occurs when using SameDiff instead of Nd4j. The error does _not_ occur when using any other scatter operation.

Side note: You may also want to update the [online documentation](https://deeplearning4j.konduit.ai/samediff/reference/operation-namespaces/base-operations#scatteradd) of the scatter ops, as they all describe `scatterAdd` and not what they actually do.

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
* Platform information (OS, etc): Linux Mint 20.3
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

#### Additional Information

* Full log or exception stack trace:
```
[main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
[main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for linear algebra: 2
[main] INFO org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory - Binary level Generic x86 optimization level Generic x86
[main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for OpenMP BLAS: 2
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Linux]
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [4]; Memory: [1,9GB];
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
[main] INFO org.nd4j.linalg.cpu.nativecpu.CpuBackend - Backend build information:
 GCC: "7.5.0"
STD version: 201103L
DEFAULT_ENGINE: samediff::ENGINE_CPU
HAVE_FLATBUFFERS
HAVE_OPENBLAS
scatter_update: Number of Integer arguments should be positive number, but got 0 arguments
Validation error at /home/runner/work/deeplearning4j/deeplearning4j/libnd4j/include/ops/declarable/impl/DeclarableOp.cpp:615 code=4() "this->validateArguments(*block)" 
[main] ERROR org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner - Failed to execute op scatter_update. Attempted to execute with 3 inputs, 1 outputs, 0 targs,0 bargs and 0 iargs. Inputs: [(FLOAT,[5],c), (INT,[],c), (FLOAT,[],c)]. Outputs: [(FLOAT,[5],c)]. tArgs: -. iArgs: -. bArgs: -. Op own name: "7df65b25-3cbc-43c2-96c9-6f8887b4086d" - Please see above message (printed out from c++) for a possible cause of error.
Exception in thread "main" java.lang.RuntimeException: Op [scatter_update] execution failed
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1561)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6563)
	at org.nd4j.linalg.factory.ops.NDBase.scatterUpdate(NDBase.java:1796)
	at ScatterUpdate.main(ScatterUpdate.java:9)
Caused by: java.lang.RuntimeException: Op with name 7df65b25-3cbc-43c2-96c9-6f8887b4086d and op type [scatter_update] execution failed with message 
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1905)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1540)
	... 3 more
```
* pom.xml file or similar: see [here](https://github.com/CompilerCrash/DL4J-Bug-Reproduction/blob/master/pom.xml)

**Comment by agibsonccc** [comment]
@CompilerCrash thanks for the reproducer let me take a look and get back to you.

**Comment by agibsonccc** [comment]
@CompilerCrash  btw, did you also try with M2.1? There was just a release a bit ago. The snapshot cron job had to move to a new server so those might be out of date. I'll still look at this but would want you to double check that as well. Thanks!

**Comment by CompilerCrash** [comment]
@agibsonccc good hint, but yes, I get the same error with M2.1.
