### ISSUE TITLE
BatchMmul issues

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9773]
#### Issue Description

I found three bugs related to the `batchMmul` operation. See code below and the attached stack traces:
```
INDArray a = Nd4j.ones(2, 6);
INDArray b = Nd4j.ones(6, 4);

// 1. batchMmul in Nd4j causes an error in LibND4J
INDArray[] res1 = Nd4j.base.batchMmul(new INDArray[]{a}, b); // throws exception
System.out.println(res1[0]);

// 2. batchMmul in SameDiff produces a wrong result and sometimes even crashes (hard to reproduce; crash log linked below)
SameDiff sd = SameDiff.create();
SDVariable[] res2 = sd.batchMmul(new SDVariable[]{sd.constant(a)}, sd.constant(b));
System.out.println(res2[0].eval()); // wrong result
/*
expected:
[[    6.0000,    6.0000,    6.0000,    6.0000], 
 [    6.0000,    6.0000,    6.0000,    6.0000]]
got:
[[    6.0000,    6.0000,         0,         0], 
 [         0,         0,    6.0000,    6.0000]]
*/

// 3. batchMmul in SameDiff on SDVariables of type ARRAY causes a NullPointerException
sd = SameDiff.create();
SDVariable[] res3 = sd.batchMmul(new SDVariable[]{sd.constant(a).add(0)}, sd.constant(b).add(0)); // throws exception
System.out.println(res3[0].eval());
```
Bug 3 is somewhat similar to issue #9698. Maybe it can be fixed in a similar way.

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
* Platform information (OS, etc): Linux Mint 20.3
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

#### Additional Information

* Exception stack trace for bug 1:
```
Error at [/home/runner/work/deeplearning4j/deeplearning4j/libnd4j/include/ops/declarable/generic/blas/batched_gemm.cpp:58:0]:
BatchedGemm: expected number of input arrays is 4, but got 2 instead
[main] ERROR org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner - Failed to execute op batched_gemm. Attempted to execute with 2 inputs, 1 outputs, 0 targs,0 bargs and 9 iargs. Inputs: [(FLOAT,[2,6],c), (FLOAT,[6,4],c)]. Outputs: [(FLOAT,[2,4],f)]. tArgs: -. iArgs: [0, 0, 2, 4, 6, 2, 4, 6, 1]. bArgs: -. Op own name: "b8c3012b-7a33-4a2a-966b-37377951fbaf" - Please see above message (printed out from c++) for a possible cause of error.
Exception in thread "main" java.lang.RuntimeException: Op [batched_gemm] execution failed
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1561)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6566)
	at org.nd4j.linalg.factory.ops.NDBase.batchMmul(NDBase.java:211)
	at Mmul.main(Mmul.java:23)
Caused by: java.lang.RuntimeException: Op with name b8c3012b-7a33-4a2a-966b-37377951fbaf and op type [batched_gemm] execution failed with message Op validation failed
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1905)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1540)
	... 3 more
```
* Crash log for bug 2: see this [Gist](https://gist.github.com/CompilerCrash/1bdd75efb5448fa726aed49cb66bc2e9).
* Exception stack trace for bug 3:
```
Exception in thread "main" java.lang.NullPointerException
	at org.nd4j.linalg.api.ops.impl.reduce.custom.BatchMmul.<init>(BatchMmul.java:79)
	at org.nd4j.linalg.api.ops.impl.reduce.custom.BatchMmul.<init>(BatchMmul.java:48)
	at org.nd4j.autodiff.samediff.ops.SDBaseOps.batchMmul(SDBaseOps.java:384)
	at Mmul.main(Mmul.java:41)
```

**Comment by agibsonccc** [comment]
@CompilerCrash thanks! This has been amazing. Let me compare this to our test cases and see what the deal here is.

**Comment by agibsonccc** [comment]
@CompilerCrash it looks like we're expecting alpha/beta as inputs here. Let me update the interface there: https://github.com/deeplearning4j/deeplearning4j/blob/d77597bae3253e13a3384a168fda789f68309c1a/libnd4j/include/ops/declarable/generic/blas/batched_gemm.cpp#L52

**Comment by CompilerCrash** [comment]
@agibsonccc you're welcome. Indeed, the check for alpha and beta seems to be the reason for bug 1.

**Comment by agibsonccc** [comment]
@CompilerCrash https://github.com/deeplearning4j/deeplearning4j/pull/9776
