### ISSUE TITLE
TensorMmul backpropagation error

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9775]
#### Issue Description

- expected behavior: if SameDiff `tensorMmul` works in the forward pass (inference), then it should also work in the backward pass (backpropagation).
- encountered behavior: the backward pass of `tensorMmul` throws an exception complaining about incorrect input shapes, even if the forward pass worked fine.

The following (meaningless) computation graph performs the `tensorMmul` operation. Inference (`sd.output(...)`) in this graph works fine, but backpropagation (`sd.fit(...)`) throws an exception. The stack trace is shown below.
```
int batchSize = 4;
int seqLength = 8;

SameDiff sd = SameDiff.create();

SDVariable features = sd.placeHolder("features", DataType.FLOAT, batchSize, seqLength);
SDVariable labels = sd.placeHolder("labels", DataType.FLOAT, batchSize, batchSize);
SDVariable var = sd.var("variable", seqLength, batchSize);
SDVariable predictions = sd.tensorMmul("predictions", features, var, new int[]{1}, 0);
sd.loss.meanSquaredError("loss", labels, predictions, null);

TrainingConfig config = new TrainingConfig.Builder()
        .updater(new Adam(0.1))
        .dataSetFeatureMapping("features")
        .dataSetLabelMapping("labels")
        .build();
sd.setTrainingConfig(config);

RecordReader reader = new CollectionRecordReader(
        Collections.nCopies(batchSize, Collections.nCopies(seqLength + batchSize, new IntWritable(1))));
DataSetIterator iterator = new RecordReaderDataSetIterator(
        reader, batchSize, seqLength, seqLength + batchSize - 1, true);

System.out.println(sd.output(iterator, "predictions").get("predictions")); // forward pass works

sd.fit(iterator, 1); // backward pass throws exception
```

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
* Platform information (OS, etc): Linux Mint 20.3
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

#### Additional Information

* Full log or exception stack trace:
```
[main] ERROR org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner - Failed to execute op tensormmul_bp. Attempted to execute with 3 inputs, 2 outputs, 0 targs,0 bargs and 4 iargs. Inputs: [(FLOAT,[4,8],c), (FLOAT,[8,4],c), (FLOAT,[4,4],c)]. Outputs: [(FLOAT,[4,8],c), (FLOAT,[8,4],c)]. tArgs: -. iArgs: [1, 1, 1, 2]. bArgs: -. Input var names: [features, variable, predictions-grad]. Output var names: [features-grad, variable-grad] - Please see above message (printed out from c++) for a possible cause of error.
Exception in thread "main" java.lang.RuntimeException: Op with name tensormmul_bp and op type [tensormmul_bp] execution failed with message ShapeUtils::evalShapeForTensorDot method: the dimensions at given axes for both input arrays must be the same !
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1905)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6575)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.doExec(InferenceSession.java:805)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:255)
	at org.nd4j.autodiff.samediff.internal.TrainingSession.getOutputs(TrainingSession.java:163)
	at org.nd4j.autodiff.samediff.internal.TrainingSession.getOutputs(TrainingSession.java:45)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:533)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:154)
	at org.nd4j.autodiff.samediff.internal.TrainingSession.trainingIteration(TrainingSession.java:129)
	at org.nd4j.autodiff.samediff.SameDiff.fitHelper(SameDiff.java:1938)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1792)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1732)
	at org.nd4j.autodiff.samediff.config.FitConfig.exec(FitConfig.java:172)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1712)
	at Mmul.main(Mmul.java:44)
```

**Comment by agibsonccc** [comment]
@CompilerCrash just like the other issue seriously thanks for this. Let me take a look at this tomorrow.

**Comment by agibsonccc** [comment]
@CompilerCrash thanks for looking at this please do keep them coming when you seem them! This was an off by 1 error when serializing axes. 
Our training works by creating a mirror graph of the original inputs which involves a serialization of the ops (this is only done once). When we create a backprop op we create it using a doDiff(..) which inherits some properties from the original op. 

The problem arose when we were creating a new op copy for training of TensorMmul (a mirror of the original feed forward) and calling a configureFromArguments() which based on the present int arguments in the op can configure some of its properties.

These properties were initialized wrong due to an off by 1 error which then propagated to the creation of the backpropagation op. I've incorporated your test case in to the tests.

**Comment by CompilerCrash** [comment]
@agibsonccc interesting insight, thanks!

I encountered these bugs in the course of the last several months, in which I was working with DL4J (mainly SameDiff). Now I finally have the time to report them. So there is indeed more to come (probably next week).
