### ISSUE TITLE
java.lang.IndexOutOfBoundsException by HistogramIterationListener

### ISSUE THREAD

**Issue by sato-cloudian** [deeplearning4j/deeplearning4j#983]
Here's the way to reproduce.

1. open DBNIrisExample
2. add backprop(true)
3. add HistogramIterationListener

Then, you get the following exception.

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at org.deeplearning4j.ui.weights.HistogramIterationListener.iterationDone(HistogramIterationListener.java:103)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:64)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1452)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1482)
	at org.deeplearning4j.examples.deepbelief.MyDBNIrisExample.main(MyDBNIrisExample.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```
Here's my branch.

```
$ git branch -v
* master    7a1c8bc Merge pull request #51 from napsternxg/master
```

**Comment by AlexDBlack** [comment]
Works fine with current DL4J master. HistogramIterationListener has been improved since this issue was reported.

**Comment by raver119** [comment]
I'll check that.
