### ISSUE TITLE
nd4j.linalg.cpu.nativecpu.CpuBackend not found

### ISSUE THREAD

**Issue by yang162132** [deeplearning4j/deeplearning4j#9857]
when I use nd4j in my linux(centos7). It's seem some things wrong.
 
Caused by: java.util.ServiceConfigurationError: org.nd4j.linalg.factory.Nd4jBackend: Provider org.    nd4j.linalg.cpu.nativecpu.CpuBackend not found
        at java.util.ServiceLoader.fail(ServiceLoader.java:239)
        at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:139)
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5092)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:270

nd4j verson is libraryDependencies += "org.nd4j" % "nd4j-native" % "1.0.0-M1.1" classifier "linux-x86_64-compat",

**Comment by agibsonccc** [comment]
@yang162132  can you provide a full stack trace? -compat should work for that. If not, you may need to build from source.

**Comment by agibsonccc** [comment]
In the mean time I'm closing this. These kinds of issues belong on our forums. This issue tracker is only for bugs. Please find our forums at: https://community.konduit.ai/

**Comment by agibsonccc** [comment]
@yang162132  just to leave you with something you can see from our builds we use centos 7 here: https://github.com/deeplearning4j/deeplearning4j/blob/3ef99ef2b8715158dc6ed04e0183c6cd3763b26b/.github/actions/build-centos/README.md#L4 feel free to post more on the forums if you have something specific and we can dive in a bit deeper.
