### ISSUE TITLE
no jnind4jcpu in java.library.path

### ISSUE THREAD

**Issue by msche** [deeplearning4j/deeplearning4j#9860]
#### Issue Description

I'm trying to start using ND4J in my project using gradle on a MAC with the M1 chipset.
When I try to compile the project and run a JMH benchmark test I get the following exception:

```
java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:79)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5152)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5064)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:284)
	at io.datapith.math.matrix.nd4j.ND4JArrayBenchmark$IterationState.<init>(ND4JArrayBenchmark.kt:28)
	at io.datapith.math.matrix.nd4j.generated.ND4JArrayBenchmark_IterationState_jmhType_B1.<init>(ND4JArrayBenchmark_IterationState_jmhType_B1.java:3)
	at io.datapith.math.matrix.nd4j.generated.ND4JArrayBenchmark_IterationState_jmhType_B2.<init>(ND4JArrayBenchmark_IterationState_jmhType_B2.java:3)
	at io.datapith.math.matrix.nd4j.generated.ND4JArrayBenchmark_IterationState_jmhType_B3.<init>(ND4JArrayBenchmark_IterationState_jmhType_B3.java:2)
	at io.datapith.math.matrix.nd4j.generated.ND4JArrayBenchmark_IterationState_jmhType.<init>(ND4JArrayBenchmark_IterationState_jmhType.java:2)
	at io.datapith.math.matrix.nd4j.generated.ND4JArrayBenchmark_throughputMultiplyMatrices_jmhTest._jmh_tryInit_f_iterationstate1_0(ND4JArrayBenchmark_throughputMultiplyMatrices_jmhTest.java:375)
	at io.datapith.math.matrix.nd4j.generated.ND4JArrayBenchmark_throughputMultiplyMatrices_jmhTest.throughputMultiplyMatrices_Throughput(ND4JArrayBenchmark_throughputMultiplyMatrices_jmhTest.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: https://deeplearning4j.konduit.ai/nd4j/backend
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:107)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:41)
	... 28 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path: [/Users/masc/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1800)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1402)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1214)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at org.nd4j.linalg.cpu.nativecpu.bindings.Nd4jCpu.<clinit>(Nd4jCpu.java:14)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.nd4j.common.config.ND4JClassLoading.loadClassByName(ND4JClassLoading.java:62)
	at org.nd4j.common.config.ND4JClassLoading.loadClassByName(ND4JClassLoading.java:56)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:97)
	... 29 more
Caused by: java.lang.UnsatisfiedLinkError: Could not find jnind4jcpu in class, module, and library paths.
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1767)
	... 38 more
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* `org.nd4j:nd4j-native-platform` version: `1.0.0-M2.1`
* Platform information (OS, etc): Mac OS Monterey version 12.2.1 with M1 chipset

**Comment by msche** [comment]
When I try it with version `1.0.0-M1` I get the following exception:

```
java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:78)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5178)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5093)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:270)
	at io.datapith.math.matrix.nd4j.ND4JArrayBenchmark$IterationState.<init>(ND4JArrayBenchmark.kt:28)
	at io.datapith.math.matrix.nd4j.generated.ND4JArrayBenchmark_IterationState_jmhType_B1.<init>(ND4JArrayBenchmark_IterationState_jmhType_B1.java:3)
	at io.datapith.math.matrix.nd4j.generated.ND4JArrayBenchmark_IterationState_jmhType_B2.<init>(ND4JArrayBenchmark_IterationState_jmhType_B2.java:3)
	at io.datapith.math.matrix.nd4j.generated.ND4JArrayBenchmark_IterationState_jmhType_B3.<init>(ND4JArrayBenchmark_IterationState_jmhType_B3.java:2)
	at io.datapith.math.matrix.nd4j.generated.ND4JArrayBenchmark_IterationState_jmhType.<init>(ND4JArrayBenchmark_IterationState_jmhType.java:2)
	at io.datapith.math.matrix.nd4j.generated.ND4JArrayBenchmark_throughputMultiplyMatrices_jmhTest._jmh_tryInit_f_iterationstate1_0(ND4JArrayBenchmark_throughputMultiplyMatrices_jmhTest.java:375)
	at io.datapith.math.matrix.nd4j.generated.ND4JArrayBenchmark_throughputMultiplyMatrices_jmhTest.throughputMultiplyMatrices_Throughput(ND4JArrayBenchmark_throughputMultiplyMatrices_jmhTest.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: https://deeplearning4j.konduit.ai/nd4j/backend
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:116)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:37)
	... 28 more
Caused by: java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path: [/Users/masc/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1718)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1328)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1132)
	at org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:12)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1200)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1132)
	at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:14)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.nd4j.common.config.ND4JClassLoading.loadClassByName(ND4JClassLoading.java:62)
	at org.nd4j.common.config.ND4JClassLoading.loadClassByName(ND4JClassLoading.java:56)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:88)
	... 29 more
Caused by: java.lang.UnsatisfiedLinkError: no openblas_nolapack in java.library.path: [/Users/masc/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1718)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1239)
	... 41 more
```

**Comment by agibsonccc** [comment]
@msche  only the latest M2.1 version should be used. Could you show me your pom.xml ? There's a new macosx-arm64 classifier you can use.

**Comment by msche** [comment]
Hi @agibsonccc,

I'm using Gradle to build my project. Within the `gradle.properties` I have defined the version of the libraries as follows:

```
nd4jVersion=1.0.0-M2.1
```

In the settings file, I'm using the catalogue functionality and have defined the following dependency (kind like dependency management in maven):

```
include("matrix")

val nd4jVersion: String by settings

enableFeaturePreview("VERSION_CATALOGS")

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            library("nd4j.native.platform", "org.nd4j:nd4j-native-platform:$nd4jVersion")
        }
    }
}
```

And finally, I have within the matrix subproject the following dependency:

```
dependencies {
    implementation(libs.nd4j.native.platform)
}
```

**Comment by agibsonccc** [comment]
@msche  ah yeah you have to use nd4j-native + openblas with explicit classifiers. nd4j-native-platform does not include mac arm64 due to the lack of platform support for many javacpp libraries. I also remember the most recent javacpp (1.5.8) openblas only now properly supports mac arm64. Please try that first.

**Comment by msche** [comment]
I added the following dependencies:

```
    implementation("org.nd4j:nd4j-native:1.0.0-M2.1")
    // For M1 apple processor
    implementation("org.nd4j:nd4j-native:1.0.0-M2.1:macosx-arm64")
    implementation("org.bytedeco:openblas:0.3.21-1.5.8:macosx-arm64")
```

And the benchmark is now working.

**Comment by msche** [comment]
Thanks for the help. I'm closing the issue
