### ISSUE TITLE
Split Op fails if numSplit parameter is an SDVariable

### ISSUE THREAD

**Issue by partarstu** [deeplearning4j/deeplearning4j#9872]
#### Issue Description

**The error message:**  _org.nd4j.linalg.exception.ND4UnresolvedOutputVariables: Could not determine number of output variables for op split - Split. Ops can override getNumOutputs() to specify number of outputs if required_

- expected behavior : successful operation execution
- encountered behavior: Exception

#### Version Information

* Deeplearning4j version - M 2.1
* Platform information: Windows 10
* CUDA version - N/A
* NVIDIA driver version - N/A

#### Additional Information
Split Op uses the integer `numSplit `parameter in order to define the number of output variables. That doesn't work in case `numSplit `is an `SDVariable`. For that case an additional handling of override of the method `getNumOutputs()` is needed. 

Stack Trace:

```
org.nd4j.linalg.exception.ND4UnresolvedOutputVariables: Could not determine number of output variables for op split - Split. Ops can override getNumOutputs() to specify number of outputs if required
	at org.nd4j.autodiff.samediff.SameDiff.generateOutputVariableForOp(SameDiff.java:4383)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:254)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.outputVariables(DynamicCustomOp.java:237)
	at org.nd4j.autodiff.samediff.ops.SDBaseOps.split(SDBaseOps.java:4375)
```

**Comment by agibsonccc** [comment]
@partarstu  what would you expect to be available here? I mainly allowed that in the context of model import. That also relies on our eager mode. I have a semi solution to this but it has limitations (eg: the variable type must be derivable during declaration) but for example say that split variable is a placeholder. What would you want to happen within that scenario? 

The only thing I could think of there would be to allow the user to define a set of "default" placeholders for resolving these kinds of things. I still need to think further on how that might affect overall graph execution though.

**Comment by partarstu** [comment]
@agibsonccc well the idea is that if this Op can't function without having an integer `numSplit` variable, I'd like to know about it. I mean even if the model is imported and the `numSplit` is used as an SDVariable, it will fail anyway during execution. Any kind of warning or at least mentioning in the JavaDoc about this behavior could be a good mitigation step in my opinion.

**Comment by agibsonccc** [comment]
@partarstu  actually that's fine...i"m just trying to get the appropriate trade off in there. That fully should work.
