### ISSUE TITLE
CreateView Op issues

### ISSUE THREAD

**Issue by partarstu** [deeplearning4j/deeplearning4j#9873]
#### Issue Description

There are 2 identified issues for org.nd4j.linalg.api.ops.impl.shape.CreateView:

1. if the Op is called using SDVariable.getView() then` No op known for hash: -6201726597031682680 and name create_view` is thrown.
2. if the Op is called directly as SameDiff.createView(), then `Please extend DynamicCustomOp.doDiff to support SameDiff backprop operations. Op: org.nd4j.linalg.api.ops.impl.shape.CreateView` is thrown

**Anyway, this Op is currently non-functional.**

- expected behavior : successful operation execution
- encountered behavior: Exception

#### Version Information

* Deeplearning4j version - M 2.1
* Platform information: Windows 10
* CUDA version - N/A
* NVIDIA driver version - N/A

#### Additional Information

Stack Trace for the first issue:

```
java.lang.IllegalStateException: No op known for hash: -6201726597031682680 and name create_view
	at org.nd4j.imports.converters.DifferentialFunctionClassHolder.customOpClassForHashAndName(DifferentialFunctionClassHolder.java:389)
	at org.nd4j.autodiff.samediff.serde.FlatBuffersMapper.fromFlatNode(FlatBuffersMapper.java:448)
	at org.nd4j.autodiff.samediff.serde.FlatBuffersMapper.cloneViaSerialize(FlatBuffersMapper.java:1065)
	at org.nd4j.autodiff.samediff.SameDiff.invokeGraphOn(SameDiff.java:656)
	at org.nd4j.autodiff.samediff.SameDiff.lambda$createGradFunction$1(SameDiff.java:4770)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:4557)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:4542)
	at org.nd4j.autodiff.samediff.SameDiff.createGradFunction(SameDiff.java:4762)
	at org.nd4j.autodiff.samediff.SameDiff.createGradFunction(SameDiff.java:4669)
	at org.nd4j.autodiff.samediff.SameDiff.fitHelper(SameDiff.java:1870)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1792)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1732)
```

Stack Trace for the second issue:

```
java.lang.UnsupportedOperationException: Please extend DynamicCustomOp.doDiff to support SameDiff backprop operations. Op: org.nd4j.linalg.api.ops.impl.shape.CreateView
	at org.nd4j.linalg.api.ops.DynamicCustomOp.doDiff(DynamicCustomOp.java:744)
	at org.nd4j.autodiff.functions.DifferentialFunction.diff(DifferentialFunction.java:677)
	at org.nd4j.autodiff.samediff.SameDiff.lambda$createGradFunction$1(SameDiff.java:5042)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:4557)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:4542)
	at org.nd4j.autodiff.samediff.SameDiff.createGradFunction(SameDiff.java:4762)
	at org.nd4j.autodiff.samediff.SameDiff.createGradFunction(SameDiff.java:4669)
	at org.nd4j.autodiff.samediff.SameDiff.fitHelper(SameDiff.java:1870)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1792)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1732)
```

**Comment by agibsonccc** [comment]
@partarstu sorry just getting to this after a mix of customer issues, holiday and test release cleanup...when I wrote this originally it was mainly for internal use...let me polish that. Thanks for filing!

**Comment by partarstu** [comment]
> @partarstu sorry just getting to this after a mix of customer issues, holiday and test release cleanup...when I wrote this originally it was mainly for internal use...let me polish that. Thanks for filing!

Thanks a lot!
