### ISSUE TITLE
Problem importing keras model

### ISSUE THREAD

**Issue by stevo32800** [deeplearning4j/deeplearning4j#9875]
`####` Issue Description

Please describe our issue, along with:
I try to import a deeplearning model created in Python using last tensorflow version and a pre-trained model (EfficientNet). 
My goal is to import my H5 model into java but i always get an error saying "Unsupported keras layer type Functional."

- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version : 1.0.0-M2.1
* Platform information (OS, etc) : Windows
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

Exception in thread "main" java.lang.RuntimeException: org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Functional. Please file an issue at https://github.com/eclipse/deeplearning4j/issues.
	at net.PneumoniaDetection.makePrediction(PneumoniaDetection.java:85)
	at net.Main.main(Main.java:25)
Caused by: org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Functional. Please file an issue at https://github.com/eclipse/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:337)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:223)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:165)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:97)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:311)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:167)
	at net.PneumoniaDetection.makePrediction(PneumoniaDetection.java:78)
	... 1 more

Process finished with exit code 1

#### Contributing
```     public void makePrediction(){
    try {
            String fullModel = new ClassPathResource("/model_multi_B4_3_1.h5").getFile().getPath();
        ComputationGraph model = KerasModelImport.importKerasModelAndWeights(fullModel);
        System.out.println("model loaded");

    } catch (IOException e) {
        System.out.println(e);

    } catch (UnsupportedKerasConfigurationException | InvalidKerasConfigurationException e) {
        throw new RuntimeException(e);
    }
    }

**Comment by treo** [comment]
@agibsonccc Side note: I think we need to take a pass on the exceptions to link to the documentation at deeplearning4j.konduit.ai, as the deeplearning4j.org links unfortunately are broken.

**Comment by thangnbn** [comment]
@stevo32800 Can you share the h5 file so that others can scrutinize?

**Comment by agibsonccc** [comment]
Closing as dup: https://github.com/deeplearning4j/deeplearning4j/issues/9398
