### ISSUE TITLE
Using DL4J in a web application - RuntimeException: Op [matmul] execution failed

### ISSUE THREAD

**Issue by ThomasGVoss** [deeplearning4j/deeplearning4j#9906]
#### Issue Description

I have been using a MultiLayerNetwork in a EJB Service in a Payara Application Server. The initilization works fine given the output below:

``` 
org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for linear algebra: 4
org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory - Binary level Generic x86 optimization level AVX512
org.nd4j.nativeblas.Nd4jBlas - Number of threads used for OpenMP BLAS: 8
org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Linux]
org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [16]; Memory: [7,1GB]
org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [OPENBLAS]

org.nd4j.linalg.cpu.nativecpu.CpuBackend - Backend build information:
 GCC: "7.5.0"
STD version: 201103L
DEFAULT_ENGINE: samediff::ENGINE_CPU
HAVE_FLATBUFFERS
HAVE_OPENBLAS

org.deeplearning4j.nn.multilayer.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
```

Calling the output function of the loaded network results in an error: 
```
ERROR org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner - Failed to execute op matmul. Attempted to execute with 2 inputs, 1 outputs, 2 targs,0 bargs and 3 iargs. Inputs: [(FLOAT,[1,9],c), (FLOAT,[9,400],f)]. Outputs: [(FLOAT,[1,400],f)]. tArgs: [1.0, 0.0]. iArgs: [0, 0, 0]. bArgs: -. Op own name: "81f000d9-6011-4d1f-adc4-af57fb7d11e6" - Please see above message (printed out from c++) for a possible cause of error. 
```
With the stacktrace:

``` 
java.lang.RuntimeException: Op [matmul] execution failed
        at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1561) ~[nd4j-native-1.0.0-M2.jar:?]
        at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6522) ~[nd4j-api-1.0.0-M2.jar:?]
        at org.nd4j.linalg.api.blas.impl.BaseLevel3.gemm(BaseLevel3.java:62) ~[nd4j-api-1.0.0-M2.jar:?]
        at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:3194) ~[nd4j-api-1.0.0-M2.jar:?]
        at org.deeplearning4j.nn.layers.BaseLayer.preOutputWithPreNorm(BaseLayer.java:322) ~[deeplearning4j-nn-1.0.0-M2.jar:?]
        at org.deeplearning4j.nn.layers.BaseLayer.preOutput(BaseLayer.java:295) ~[deeplearning4j-nn-1.0.0-M2.jar:?]
        at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:343) ~[deeplearning4j-nn-1.0.0-M2.jar:?]
        at org.deeplearning4j.nn.layers.AbstractLayer.activate(AbstractLayer.java:262) ~[deeplearning4j-nn-1.0.0-M2.jar:?]
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1341) ~[deeplearning4j-nn-1.0.0-M2.jar:?]
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2453) ~[deeplearning4j-nn-1.0.0-M2.jar:?]
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2416) ~[deeplearning4j-nn-1.0.0-M2.jar:?]
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2407) ~[deeplearning4j-nn-1.0.0-M2.jar:?]
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2394) ~[deeplearning4j-nn-1.0.0-M2.jar:?]
        at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:2490) ~[deeplearning4j-nn-1.0.0-M2.jar:?]
        at com.[****].lambda$nnRegression$1(myCustomJavaClass.java:264)

Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.getCustomOperations(NativeOpExecutioner.java:1365) ~[nd4j-native-1.0.0-M2.jar:?]
        at org.nd4j.linalg.api.ops.DynamicCustomOp.opHash(DynamicCustomOp.java:392) ~[nd4j-api-1.0.0-M2.jar:?]
        at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1900) ~[nd4j-native-1.0.0-M2.jar:?]
        at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1540) ~[nd4j-native-1.0.0-M2.jar:?]
        ... 139 more

```
Running the same ear file and command on another servers (OS: Windows and Red Hat Enterprise Linux 8.7 (Ootpa)) worked fine.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - 1.0.0-M2
* Platform information (OS, etc) - Cent OS 8 Linux
* Payara Server - Payara Server 5.193.1 #badassfish (build 275).

#### Contributing

Will gladly try to help fix this.

**Comment by treo** [comment]
Did you get any additional messages above the one you've shared? 
``` Please see above message (printed out from c++) for a possible cause of error. ```

**Comment by ThomasGVoss** [comment]
Since i'm running this in an application server unfortunately not - where would i have to look for them?

**Comment by treo** [comment]
That is essentially something that goes to stdout. So wherever that goes, you should be able to find it.

**Comment by agibsonccc** [comment]
@ThomasGVoss any updates on this? The fact this is an EAR stands out to me...some resources are likely not being included. A reproducer would get this fixed quickly. It's just hard to know where to start with this.

**Comment by ThomasGVoss** [comment]
thank you for getting back to me - i'm having trouble getting the logs as well as a MVP together. 
Since everything is running inside the application server, i can not located the c++ output. I'm getting the regular java logging but nothing more. 
Furthermore, it works on a similar server configuration on a different OS (Issue on Cent OS / no issues on Redhat Enterprise and windows)
Next thing is, that i generated a standalone java application and the loading as well as the inference both work fine on Cent OS Server.
So I second the idea that something must go missing somewhere along the lines compiling the ear. For that reason i did wrap everything in one large ear, using compile scope - still no success. 
My next step is to remote debug the application to pin point this issues more detailed.

**Comment by agibsonccc** [comment]
@ThomasGVoss  You can turn on:
```
Nd4j.getExectioner().enableVerboseMode(true);
Nd4j.getExecutioner().enableDebugMode(true);
```
Also if you can please set the system property: org.bytedeco.javacpp.logger.debug=true
This will debug the loading of .so files (basically java loading the c++ libraries)
I suspect (based on the OS and how old it is) it's related to glibc somehow.

If you want, please consider using nd4j-native (no classifier) and nd4j-native with the classifier linux-x86_64-compat which works with older glibcs to see if that helps.

I can't for sure say that's it either though.  That error looks very weird and only happens post library init so something still seems to happen in the middle. Any information is useful though.

Overall here though I do feel that you should look around nd4j's init code. It also might have to do with the classloader. If needed you can actually override that. From my understanding wars and ears can be a bit different and it maybe how you're setting your WAR up:
https://stackoverflow.com/questions/58070472/using-same-classloader-for-ear-and-war

**Comment by ThomasGVoss** [comment]
After multiple tries on various servers i can only reproduce the error in one particular combination - as mentioned above. 
For that reason we will contact payara support first, to see what the issue might be on their end. Thanks for the assistance!

**Comment by agibsonccc** [comment]
Please have them contact me if it does end up being something on our end as
well. Thanks!
