### ISSUE TITLE
Protocol message end-group tag did not match expected tag.

### ISSUE THREAD

**Issue by nomatter18** [deeplearning4j/deeplearning4j#9961]
Hi everyone!

Trying to import TF  model from https://tfhub.dev/google/bert_multi_cased_L-12_H-768_A-12/1 and have an exception:

Exception in thread "main" java.lang.RuntimeException: org.nd4j.shade.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:138)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:87)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:73)
	at com.word2vec.BertTFimport.main(BertTFimport.java:24)
Caused by: org.nd4j.shade.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
	at org.nd4j.shade.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:137)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.checkLastTagWas(CodedInputStream.java:2124)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2410)
	at org.tensorflow.framework.FunctionDef.<init>(FunctionDef.java:90)
	at org.tensorflow.framework.FunctionDef$1.parsePartialFrom(FunctionDef.java:1798)
	at org.tensorflow.framework.FunctionDef$1.parsePartialFrom(FunctionDef.java:1792)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2409)
	at org.tensorflow.framework.FunctionDefLibrary.<init>(FunctionDefLibrary.java:64)
	at org.tensorflow.framework.FunctionDefLibrary$1.parsePartialFrom(FunctionDefLibrary.java:1109)
	at org.tensorflow.framework.FunctionDefLibrary$1.parsePartialFrom(FunctionDefLibrary.java:1103)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2409)
	at org.tensorflow.framework.GraphDef.<init>(GraphDef.java:71)
	at org.tensorflow.framework.GraphDef$1.parsePartialFrom(GraphDef.java:1605)
	at org.tensorflow.framework.GraphDef$1.parsePartialFrom(GraphDef.java:1599)
	at org.nd4j.shade.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:215)
	at org.nd4j.shade.protobuf.AbstractParser.parseFrom(AbstractParser.java:232)
	at org.nd4j.shade.protobuf.AbstractParser.parseFrom(AbstractParser.java:237)
	at org.nd4j.shade.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at org.nd4j.shade.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:339)
	at org.tensorflow.framework.GraphDef.parseFrom(GraphDef.java:483)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:136)
	... 3 more

versions:
<java.version>19</java.version>
<dl4j-master.version>1.0.0-M2.1</dl4j-master.version>
<nd4j.backend>nd4j-native</nd4j.backend>

Pice of code:

private static SameDiff sd;
private static String dataLocalPath = "/home/nomatter/nnet/tf/bert/";
private static String filepath = "saved_model.pb";

File file = new File(dataLocalPath, filepath);
sd = TFGraphMapper.importGraph(file);

Thank for have any help.

**Comment by agibsonccc** [comment]
@nomatter18 
 Those aren't frozen pbs out of the box (which we expect normally) - you have to convert them with something like:
 https://github.com/deeplearning4j/deeplearning4j/blob/ab43b47a19638f19edf93f39bea50ce86c3f2b60/contrib/omnihub/src/omnihub/frameworks/tensorflow.py#L6


 Also of note, that's the old api. Please the new one: https://deeplearning4j.konduit.ai/samediff/explanation/model-import-framework


Closing this as you aren't actually trying to import a pb. Move over to the community forums if you have any other issues: https://community.konduit.ai/

I try to keep the issues for bugs only. Thanks!

**Comment by nomatter18** [comment]
@agibsonccc thanks for the help
