### ISSUE TITLE
org.nd4j.shade.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field. 

### ISSUE THREAD

**Issue by guojian0614** [deeplearning4j/deeplearning4j#9968]
#### Issue Description

Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version  
![image](https://user-images.githubusercontent.com/29422500/236598999-ad323e7a-bf7c-4745-86ad-e04d9827afd2.png)
     
* Platform information (OS, etc)    win10 86_64
* CUDA version, if used                          11.3
* NVIDIA driver version, if in use             
![image](https://user-images.githubusercontent.com/29422500/236598810-66f6a997-4a4b-4784-8a9b-c5b5f3d6be75.png)

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
Exception in thread "main" java.lang.RuntimeException: org.nd4j.shade.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:138)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:100)
	at org.deeplearning4j.modelimportexamples.tf.advanced.mobilenet.Test.main(Test.java:44)
Caused by: org.nd4j.shade.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at org.nd4j.shade.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:115)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.skipRawBytesSlowPath(CodedInputStream.java:3082)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.skipRawBytes(CodedInputStream.java:3065)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.skipField(CodedInputStream.java:2153)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.skipMessage(CodedInputStream.java:2215)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.skipField(CodedInputStream.java:2146)
	at org.nd4j.shade.protobuf.MapEntryLite.parseEntry(MapEntryLite.java:186)
	at org.nd4j.shade.protobuf.MapEntry.<init>(MapEntry.java:107)
	at org.nd4j.shade.protobuf.MapEntry.<init>(MapEntry.java:50)
	at org.nd4j.shade.protobuf.MapEntry$Metadata$1.parsePartialFrom(MapEntry.java:71)
	at org.nd4j.shade.protobuf.MapEntry$Metadata$1.parsePartialFrom(MapEntry.java:65)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2409)
	at org.tensorflow.framework.FunctionDef.<init>(FunctionDef.java:90)
	at org.tensorflow.framework.FunctionDef$1.parsePartialFrom(FunctionDef.java:1798)
	at org.tensorflow.framework.FunctionDef$1.parsePartialFrom(FunctionDef.java:1792)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2409)
	at org.tensorflow.framework.FunctionDefLibrary.<init>(FunctionDefLibrary.java:64)
	at org.tensorflow.framework.FunctionDefLibrary$1.parsePartialFrom(FunctionDefLibrary.java:1109)
	at org.tensorflow.framework.FunctionDefLibrary$1.parsePartialFrom(FunctionDefLibrary.java:1103)
	at org.nd4j.shade.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2409)
	at org.tensorflow.framework.GraphDef.<init>(GraphDef.java:71)
	at org.tensorflow.framework.GraphDef$1.parsePartialFrom(GraphDef.java:1605)
	at org.tensorflow.framework.GraphDef$1.parsePartialFrom(GraphDef.java:1599)
	at org.nd4j.shade.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:215)
	at org.nd4j.shade.protobuf.AbstractParser.parseFrom(AbstractParser.java:232)
	at org.nd4j.shade.protobuf.AbstractParser.parseFrom(AbstractParser.java:237)
	at org.nd4j.shade.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at org.nd4j.shade.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:339)
	at org.tensorflow.framework.GraphDef.parseFrom(GraphDef.java:483)
	at org.nd4j.imports.graphmapper.tf.TFGraphMapper.importGraph(TFGraphMapper.java:136)
	... 2 more
* pom.xml file or similar (also in a Gist)
just your expamples module code for version 1.0.0-beta7  not custom 

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by agibsonccc** [comment]
@guojian0614 closing this as beta7 is years this old at this point.

**Comment by guojian0614** [comment]
> @guojian0614 closing this as beta7 is years this old at this point.
@agibsonccc 
i don't know your mean? is this problem no matter ?
now ，i even can't load my model normal!
  is this problem cause by version older？if yes ，tell me normal version please！
  actully，i run it on the master branch also ，has same problem！

**Comment by agibsonccc** [comment]
@guojian0614  please open a new issue with your pom.xml then. I will need your model file as well.
Also, please be calm. I will not be responsive to people who are yelling. If you want help, be professional. You are not entitled to support as you are not a paying customer. You received the code for free and are expected to abide by very basic code of conduct: https://www.rust-lang.org/policies/code-of-conduct (for your point here just be polite it's not a big ask)
